### ISSUE TITLE
spammy warnings from multi-stage build with ARG

### ISSUE THREAD

**Issue by cjyar** [GoogleContainerTools/skaffold#1051]
This Dockerfile provokes skaffold to print warnings once a second:

```Dockerfile
ARG GO_VERSION=1.10
ARG ALPINE_VERSION=3.8
ARG PACKAGE=example.com/skaffold-spam
ARG APP=spam

FROM golang:${GO_VERSION}-alpine${ALPINE_VERSION} as builder

ARG PACKAGE
RUN mkdir -p /go/src/${PACKAGE}
WORKDIR /go/src/${PACKAGE}

COPY . ./
ARG APP
RUN go build -o /${APP}

FROM alpine:${ALPINE_VERSION} as target

ARG APP
COPY --from=builder /${APP} /
CMD [ "/${APP}" ]
```

See full repro case at [https://github.com/cjyar/skaffold-bug](https://github.com/cjyar/skaffold-bug).

### Expected behavior
- Skaffold shouldn't complain about valid Dockerfiles.
- Warnings should be printed only when the source code has changed. They shouldn't be streamed continuously to the user's terminal.

### Actual behavior
- Skaffold complains `Error processing base image for onbuild triggers: getting remote config: getting image: parsing initial ref: could not parse reference. Dependencies may be incomplete.`
- The warning is printed twice every second.

### Information

- Skaffold version: 3ecef93d0af79deefbc72ec6917e67d8d4e84272
- Operating system: Windows 10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
  - imageName: example/skaffold-spam
deploy:
  kubectl:
    manifests:
    - k8s/*
```

### Steps to reproduce the behavior

1. `skaffold dev`
