### ISSUE TITLE
"COPY ." not copying all files to the image

### ISSUE THREAD

**Issue by alexfrancavilla** [GoogleContainerTools/skaffold#1110]
Hi there. I've recently updated my skaffold version which broke the image building process. Usually I work with Skaffold + Minikube + Helm. The following Dockerfile line behaves differently:

```
COPY . ./
```
I've nailed it down to work with skaffold 0.10.0 and breaks with 0.11.0 (also the newest version 0.15.1 is affected for me). What happens is that the COPY task is not adding ALL files to the image but is missing some. The "some" is a little hard to describe, it is always the same files and not randomly, but is different between projects. In an extremely simple Nodejs/Express project the task only added the Dockerfile, and misses the `src/` dir as well as top level config files like `tsconfig.json`. In another PHP project other (randomly looking) directories and files are affected.

The building process then goes on and my project will eventually fail at runtime because of missing sources or other relevant stuff.

It may be worth noting that every project for me has the skaffold.yaml file in a different directory. The node project's skaffold file is located in a separate repository (`../dev/skaffold.yaml`), the PHP project stores it in a subdirectory (`build/skaffold.yaml`).

The Dockerfile has not changed, usual `docker build .` commands result in the same working image as the 0.10.0 skaffold version.

My workaround is to use `COPY * dest/` instead of `COPY . dest/`, but this obviously may skip hidden files/directories.

### Information

- Skaffold version: 0.10.0 works, 0.11.0 fails up until 0.15.1
- Operating system: macOS 10.13.6 using Homebrew, zsh, Docker 18.06.1-ce, Minikube's Docker version is 17.12.1-ce

skaffold.yaml (0.11.0+)
```yaml
apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
    - imageName: api
      workspace: ../api
deploy:
  helm:
    releases:
      - name: foo-project
        chartPath: ../chart
        valuesFiles:
          - skaffold-values.yaml
        values:
          api.image: api
```

skaffold.yaml (0.10.0)
```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
    - imageName: api
      workspace: ../api
deploy:
  helm:
    releases:
      - name: foo-project
        chartPath: ../chart
        valuesFilePath: skaffold-values.yaml
        values:
          api.image: api
```

Dockerfile
```
FROM node:10.11.0-alpine
EXPOSE 8080
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn

# This COPY breaks!
COPY . ./
RUN yarn exec tsc

CMD ["node", "dist/main.js"]
```

.dockerignore of the project (if that is relevant)
```
/.*
/Dockerfile
/node_modules/
```
