### ISSUE TITLE
'skaffold dev' does not clean up secrets if content changes when using kustomize

### ISSUE THREAD

**Issue by ianlewis** [GoogleContainerTools/skaffold#1111]
### Expected behavior
- When running skaffold dev with kustomize, a secret's content changes causing a new secret to be created.
- The old secret is deleted.

### Actual behavior
- Skaffold creates the new secret but old secrets are not cleaned up.
- Skaffold does not clean up these secrets when 'skaffold dev' is stopped leaving cruft in the dev environment

### Information

- Skaffold version: v0.15.1
- Operating system: linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
    ...
deploy:
  kustomize:
    kustomizePath: ./kubernetes
```

### Steps to reproduce the behavior

1. Create a kustomization file with a secretGenerator
2. Start 'skaffold dev'; the secret is created
3. Change the secret's generated content and cause a re-deploy; a new secret is created, but the old one is not deleted
