### ISSUE TITLE
`skaffold fix` should not specify the default values

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1118]
When I run `skaffold fix on:
```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
    - imageName: api
      workspace: ../api
deploy:
  helm:
    releases:
      - name: bug-demo
        chartPath: ../chart
        valuesFilePath: skaffold-values.yaml
        values:
          api.image: api
```

I get:
```
apiVersion: skaffold/v1alpha4
kind: ""
build:
  artifacts:
  - image: api
    context: ../api
deploy:
  helm:
    releases:
    - name: bug-demo
      chartPath: ../chart
      valuesFiles:
      - skaffold-values.yaml
      values:
        api.image: api
      namespace: ""
      version: ""
      setValues: {}
      setValueTemplates: {}
      wait: false
      recreatePods: false
      overrides: {}
      packaged: null
      imageStrategy:
        fqn: null
        helm: null
```

I expected:

```
apiVersion: skaffold/v1alpha4
kind: "Config"
build:
  artifacts:
  - image: api
    context: ../api
deploy:
  helm:
    releases:
    - name: bug-demo
      chartPath: ../chart
      valuesFiles:
      - skaffold-values.yaml
      values:
        api.image: api
```

Note that default values are added and that the `kind` field is invalid
