### ISSUE TITLE
Specifying a target on an artifact can have an impact on files to watch

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1120]
Here's a Dockerfile with two targets:

```
FROM alpine as dev
COPY dev.txt .

FROM alpine as prod
COPY prod.txt .
```

An artifact that is built with the target set to `dev` should depend only on `dev.txt`, so only this file should be watched for changes and if `prod.txt` is changed, it should not trigger a rebuild of the artifact.

**Comment by radityasurya** [comment]
**Current Condition**
When updating the dev.txt all the images is rebuild

**Expectation**
Only the dev.txt is rebuild

Dockerfile
```
FROM alpine as base
COPY base.txt .

FROM base as dev
COPY dev.txt .

FROM dev as test
COPY dev.txt .
RUN test

FROM dev as prod
COPY prod.txt .
```

skaffold.yaml
```
build:
    artifacts:
    - imageName: dev
      workspace: ../project
      docker:
        dockerfilePath: Dockerfile
        target: dev
    - imageName: prod
      workspace: ../project
      docker:
        dockerfilePath: Dockerfile
        target: prod
    - imageName: test
      workspace: ../project
      docker:
        dockerfilePath: Dockerfile
        target: test
```
