### ISSUE TITLE
Expose the watcher on the config

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1151]
Why not even expose the watcher type through the artifact? I intended to do that at some point.

For services you don't "own", you could watch them through a "git-repository" watcher to "live-at-head" or even use it as a way to check out versions of apps from a known tag.

```yaml
# this will just check out the dependency and 
- image: some_dependency
  watcher:
    gitRepository:
      version: v0.1.0
      pollInterval: -1

# this gets updated on any push to master (gitops)
- image: some_dependency_at_head
  watcher:
    gitRepository: {}

# uses the filesystem watcher
- image: stuff_im_working_on

# exposes an "event" listener on port:9000 which you can send 
# CRUD updates that trigger skaffold's loop
- image: stuff_im_working_on
    watcher:
      http:
        port: 9000
```

ref #1149
