### ISSUE TITLE
Split getting-started into two examples

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1154]
I think the getting-started should be the smallest possible example.

current
```yaml
apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
test:
  - image: gcr.io/k8s-skaffold/skaffold-example
    structureTests:
      - ./test/*
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: k8s-skaffold
  - name: test
    test:
      - image: gcr.io/k8s-skaffold/skaffold-example
        structureTests:
          - ./test/profile_structure_test.yaml
```

proposed
```yaml
apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
deploy:
  kubectl:
    manifests:
```
