### ISSUE TITLE
UNAUTHORIZED: "Requested repository does not match bearer token resource: my-project/my-image"

### ISSUE THREAD

**Issue by Alirun** [GoogleContainerTools/skaffold#1164]
### Expected behavior

- Image built using `Google Cloud Build`
- Image pushed to`Google Cloud Repository`
- Image tagged with `latest` and `commitHash` tags

### Actual behavior

- Image built using `Google Cloud Build`
- Image pushed to`Google Cloud Repository`
- Image tagged with `latest`
- Image wasn't tagged with `commitHash` tags due to error:

```
INFO[0110] Deleted object source/my-project-0927d93a0567e75a713478eff81c6fb4.tar.gz
INFO[0110] Image built at gcr.io/my-project/my-image@sha256:a6a61b08d1383b00780383f7236b984603479e46caed196e31fc747acd22d675
FATA[0112] build step: building [gcr.io/my-project/my-image]: tagging image: UNAUTHORIZED: "Requested repository does not match bearer token resource: my-project/my-image"
```

### Information

- Skaffold version: 0.11.0 (forced to use this version as part of `jenkins-x`)
- Operating system: MacOS, CentOS, basically any of them
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}-{{.BRANCH_NAME}}:{{.COMMIT_SHORT}}'
  artifacts:
  - imageName: gcr.io/my-project/my-image
    workspace: .
    docker: 
      dockerfilePath: Dockerfile-prod
  googleCloudBuild:
    projectId: my-project
    diskSizeGb: 200
    machineType: "N1_HIGHCPU_8"
deploy:
  helm:
    releases:
    - name: my-project-{{.BRANCH_NAME}}
      chartPath: deployment/chart
      setValueTemplates:
        frontend.image: gcr.io/my-project/my-image
```

### Steps to reproduce the behavior

1. Run `skaffold build -f skaffold.yaml`

### Possible fix

Changins 

```
template: '{{.IMAGE_NAME}}-{{.BRANCH_NAME}}:{{.COMMIT_SHORT}}'
```

to

```
template: '{{.IMAGE_NAME}}:{{.COMMIT_SHORT}}'
```

fixes the problem
