### ISSUE TITLE
Sync map can be inferred from artifact Dockerfile

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1166]
We already parse the source in a dockerfile's COPY and ADD, but we should also capture the destination.

```Dockerfile
FROM python:3.7-slim
CMD ["python", "-m", "flask", "run"]
ENV FLASK_DEBUG=1
ENV FLASK_APP=app.py

COPY requirements.txt .
RUN pip install -r requirements.txt
COPY *.py . # Should parse dst here
```
So that instead of writing this:
```yaml
  - image: gcr.io/k8s-skaffold/python-reload
    context: python
    sync:
      '*.py': .
```

Users could write this
```yaml
  - image: gcr.io/k8s-skaffold/python-reload
    context: python
    sync:
      '*.py':
```

However, there are many corner cases to watch out for. COPY can take multiple arguments to copy to the same destination folder, and there are rules of when the destination must be inferred as a directory or not.

Overlapping copies may be another corner case. Ultimately I think it will need to be modeled as a map of source files to possibly multiple locations.

Different artifact types can also provide different hints on how to fill in the sync map.
