### ISSUE TITLE
[Proposal] Artifact-level builders/deployers

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#1179]
This is an idea we've been toying with for a little while, so I wanted to write up a proposal to make the discussion public and get feedback.

We're considering introducing the idea of builders and deployers on a per-artifact basis, as a way to support using multiple different implementations within a single skaffold workflow. Additionally, this change will make it more clear what combinations of build "strategies" (i.e. what is actually doing the building) and build "contexts" (i.e. where the build is happening) are possible in a skaffold workflow. see #953 and #955 for more context on this.

As an example, currently, if a user wanted to build one artifact with local docker and deploy with kubectl, and build another artifact on-cluster with kaniko and deploy with kustomize, this isn't possible due to the way builders/deployers are specified in the config, but there's no reason why it shouldn't be possible.

Users could still specify project-level build and deploy configurations, which would be used as fallbacks for each artifact if none were specified. `skaffold fix`-ing existing skaffold.yamls would be simple.

An example using project-level build/deploy specs (which will be applied to all artifacts) looks very similar to the current skaffold.yaml:
```
apiVersion: skaffold/v1alpha4
kind: Config
artifacts:
- image: gcr.io/k8s-skaffold/leeroy-web
  context: ./leeroy-web/
- image: gcr.io/k8s-skaffold/leeroy-app
  context: ./leeroy-app/

build:
  local: {} // build everything with docker

deploy:
  kubectl:
    manifests:
      - ./leeroy-web/kubernetes/*
      - ./leeroy-app/kubernetes/*
```

An example of what a more specialized pipeline config might look like:
```
apiVersion: skaffold/v1alpha4
kind: Config
artifacts:
- image: gcr.io/k8s-skaffold/leeroy-web
  context: ./leeroy-web/
  build:
    local:
      docker:
        useBuildKit: true
    # bazel:
    #   target: //:skaffold_example.tar
  deploy:
    kubectl:
      manifests:
      - ./leeroy-web/kubernetes/*
- image: gcr.io/k8s-skaffold/leeroy-app
  context: ./leeroy-app/
  build:
    in-cluster:
      docker: {} # we are explicit about which artifact type we're building
    # bazel: {} would fail, since we don't currently support in-cluster bazel builds 
      buildContext:
        gcsBucket: k8s-skaffold
      pullSecret: ./leeroy-app/secret.json
  deploy:
    kustomize:
      path: ./leeroy-app/kubernetes

profiles:
  - name: local-leeroy-app-debug
    # normally I want on-cluster, but I want to inspect
    # changes manually with container-diff locally
    artifacts:
      - image: gcr.io/k8s-skaffold/leeroy-app
        build:
          local: {} # this will default to docker
  - name: gcp-leeroy-web
    # just to demonstrate with this would look like
    artifacts:
      - image: gcr.io/k8s-skaffold/leeroy-web
        build:
          googleCloudBuild:
            docker: {}
```

Features:

* Clarifies what build context/strategy combinations are possible within skaffold
* Enables significantly more workflows for developers
* Enables combining pre-existing projects with different builder/deployer setups more easily into a single skaffold project

Cost:
* Increases average size of skaffold.yaml
* Makes profiles a bit more complex to apply
* Needs a significant rework of the skaffold runner, as we'll need to embed the builders/deployers into the artifacts themselves

**Comment by dlorenc** [comment]
I love the breakdown. My only comment is to try to figure out a better word than "build context", since context is terribly overloaded, even within "build".

But I have no better suggestions. :(

**Comment by r2d4** [comment]
* Is there any data to back this up? Issues, bug reports?
* Currently some heterogeneous build combinations are supported, e.g. bazel + docker + jib. How many skaffold configuration files use multiple builders? That would be a good indication of how many users might use this feature.
* Using deployers together is already supported and splitting them out by artifact wouldn't do much except make users write more configuration. https://github.com/GoogleContainerTools/skaffold/pull/586. In fact, this won't work for helm unless you have a separate chart per artifact.

**Features:**
> Clarifies what build context/strategy combinations are possible within skaffold

I'm unclear how it actually achieves this. It seems like you could still specify the invalid combinations.

> Enables significantly more workflows for developers

Can you expand on what these workflows are? 

> Enables combining pre-existing projects with different builder/deployer setups more easily into a single skaffold project

How many projects exist like this? Are there any higher profile projects that build their containers in multiple ways? e.g. a project that calls cloud build and shells out to docker? or a project that builds some images on the cluster, and others on cloud build?

Having this motivated by real world examples would be a lot more convincing.

--- 

The features only benefit a very specific use case (which in my opinion hasn't been validated), but the costs affect every skaffold user.

**Comment by nkubala** [comment]
> * Is there any data to back this up? Issues, bug reports?

I assume you're talking about the motivation for this. This originally stemmed from a few things: the issue about builders building all artifact types (#953), which sparked #954 to validate existing combinations before running skaffold; and also, the discussion around making the skaffold config "beta", which I argued shouldn't happen until we've though a little more about the config structure in terms of what we do/don't support now, and what we plan on supporting later down the line.

> * Currently some heterogeneous build combinations are supported, e.g. bazel + docker + jib. How many skaffold configuration files use multiple builders? That would be a good indication of how many users might use this feature.

This is a good question, and one that I don't have an answer to right now. It would be interesting to think about how heterogenous combinations could be supported in this scheme; the implementation of this would probably include getting rid of the `oneOf` yaml tag we have on the config structs, so I don't see any inherent reason why this wouldn't be possible.

> * Using deployers together is already supported and splitting them out by artifact wouldn't do much except make users write more configuration. #586. In fact, this won't work for helm unless you have a separate chart per artifact.

Helm and kubectl is IMO a special case that we added to support a somewhat specific use case, and the behavior of this isn't very well-defined. This was another motivating factor for me wanting to have a more explicit way to define which artifacts are built and deployed in which ways. That said, that's a good point about helm not working without per-artifact charts and we should probably think about that a little more.

> I'm unclear how it actually achieves this. It seems like you could still specify the invalid combinations.

Each build "context" (or whatever you want to call it) would have a list of supported build strategies in its corresponding struct in the config schema, e.g.

```golang
type InClusterBuild struct {
  DockerBuild *DockerBuild `yaml:"docker"`
  // no BazelBuild field here because we don't support bazel in-cluster
}
```
so if in your config you tried to write
```yaml
build:
  in-cluster:
    bazel: {}
```
this wouldn't parse, and skaffold would throw an error before it even ran.

> Can you expand on what these workflows are?

Any workflow in which you want to use different builders or different deployers at the same time.

> How many projects exist like this? Are there any higher profile projects that build their containers in multiple ways? e.g. a project that calls cloud build and shells out to docker? or a project that builds some images on the cluster, and others on cloud build?

I don't have any concrete examples for this at the moment, but I don't think it's that hard to imagine a scenario in which you have a component being built with bazel and another being built with docker. skaffold shouldn't require you to rewrite one of your build configurations to work on these in the same skaffold workflow.

---

I think I should have put a little less emphasis on the "enabling developers with different workflows" part of this proposal, because I don't think that's the most important part of this. I wouldn't say this is motivated by wanting to add new capabilities to skaffold; rather, the main motivation of this is to refine the way we specify how artifacts are built and deployed in the skaffold config, and to be more explicit on both the user's end and on skaffold's end what combinations are supported.

**Comment by r2d4** [comment]
> this wouldn't parse, and skaffold would throw an error before it even ran.

You can achieve the same exact behavior with only 7 lines. The end result is the exact same for the user.
```diff
diff --git a/pkg/skaffold/build/gcb/cloud_build.go b/pkg/skaffold/build/gcb/cloud_build.go
index 5b82f804..c6005412 100644
--- a/pkg/skaffold/build/gcb/cloud_build.go
+++ b/pkg/skaffold/build/gcb/cloud_build.go
@@ -48,6 +48,9 @@ func (b *Builder) Build(ctx context.Context, out io.Writer, tagger tag.Tagger, a
 }

 func (b *Builder) buildArtifact(ctx context.Context, out io.Writer, tagger tag.Tagger, artifact *latest.Artifact) (string, error) {
+       if artifact.DockerArtifact == nil {
+               return "", fmt.Errorf("Non docker builds are not supported with GCB")
+       }
        client, err := google.DefaultClient(ctx, cloudbuild.CloudPlatformScope)
        if err != nil {
                return "", errors.Wrap(err, "getting google client")
diff --git a/pkg/skaffold/build/kaniko/kaniko.go b/pkg/skaffold/build/kaniko/kaniko.go
 import (
        "context"
+       "fmt"
        "io"

        "github.com/GoogleContainerTools/skaffold/pkg/skaffold/build"
@@ -39,6 +40,9 @@ func (b *Builder) Build(ctx context.Context, out io.Writer, tagger tag.Tagger, a
 }

 func (b *Builder) buildArtifact(ctx context.Context, out io.Writer, tagger tag.Tagger, artifact *latest.Artifact) (string, error) {
+       if artifact.DockerArtifact == nil {
+               return "", fmt.Errorf("Non docker builds are not supported with Kaniko")
+       }
        initialTag, err := b.run(ctx, out, artifact, b.KanikoBuild)
        if err != nil {
                return "", errors.Wrapf(err, "kaniko build for [%s]", artifact.ImageName)
```

> a component being built with bazel and another being built with docker. 

This is possible today.

> Any workflow in which you want to use different builders or different deployers at the same time.

This needs to be qualified: what is not supported today is building with a combination of local, managed, and cluster builders. 

If it were me implementing this feature, I'd want to have a concrete example of why you'd need this, because I don't think its a legitimate use case. Why is it not legitimate?

1. All of them will give you the same result for a given artifact. A docker artifact should give you the same image using docker locally, managed docker on a VM, and docker on the cluster. It's not how its built, its where the builder is.
2. You would only use one because of some constraint in your environment. In development you'll want to use local docker if you have it available, in CI/CD you might choose to use managed or cluster depending on your architecture.

> Helm and kubectl is IMO a special case that we added to support a somewhat specific use case, and the behavior of this isn't very well-defined. 

How is it not well defined? We just iterate over the deployers and execute them as normal. This will continue to work for additional deployers with minimal effort. You can multi-deploy with all deployers today.

**Comment by dlorenc** [comment]
I'd like to see one main thing here - a decoupling of the two overloaded concepts. The two concepts are:

- where the build happens
- how it is specified

For an example of why I find this confusing today, here's an example yaml:

```yaml
apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-bazel
    context: .
    bazel:
      target: //:skaffold_example.tar
    googleCloudBuild:
      projectId: YOUR_PROJECT
``

To me, this reads as if bazel would run in cloud build. Skaffold currently seems to try to do a gcb dockerfile build, which panics because there's no dockerfile.

So `googleCloudBuild` actually represents both concepts today - the build specification (Dockerfile) and execution environment (cloud/hosted). Same for `local`, it's a build specification (Dockerfile) and execution environment (local/Docker daemon). And kaniko.

Yes, this could be fixed by making these scenarios actually work or by validating and throwing an error if an invalid combination is specified. But it's still confusing and conceptual overload.

I think/hope we can come up with a way to clean up these concepts without adding much complexity to the yaml.

One way to do that is to move the build specification (dockerfile/bazel/jib) under the execution environment (cluster/hosted/local). This makes it more clear that the concepts are related (not all environments need to support all specifications) but orthogonal - cloudBuild/local/cluster clearly become execution environments rather than hybrids.

**Comment by r2d4** [comment]
> So googleCloudBuild actually represents both concepts today - the build specification (Dockerfile) and execution environment (cloud/hosted). Same for local, it's a build specification (Dockerfile) and execution environment (local/Docker daemon). And kaniko.

This is not correct and I think you're a bit confused. The YAML you provided is not skaffold YAML.

This is the correct YAML
```yaml
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/something-else
  - image: gcr.io/k8s-skaffold/skaffold-example
    context: .
    bazel:
      target: //:skaffold_example.tar
  googleCloudBuild:
    projectId: r2d4minikube
```

The execution environment is separated from the artifact representation today. The only issue is that we don't validation the artifact type/execution platform specification.

You might want to take a look at the annotated YAML to get a better idea of the configuration schema. https://github.com/GoogleContainerTools/skaffold/blob/master/examples/annotated-skaffold.yaml

**Comment by dlorenc** [comment]
Sorry, copy paste error. Here's what I ran:

```yaml
apiVersion: skaffold/v1alpha4
kind: Config
build:
  googleCloudBuild:
    projectId: dlorenc-vmtest2
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-bazel
    context: .
    bazel:
      target: //:skaffold_example.tar
```

This panics at HEAD.
