### ISSUE TITLE
helm deploy not resulting in a patched release

### ISSUE THREAD

**Issue by Morriz** [GoogleContainerTools/skaffold#1184]
### Expected behavior
When I make a change to my helm package, I expect skaffold to update my deployment image with it's generated tag
### Actual behavior
`tag` stays at `latest`
### Information
I use the standard helm image notation:

```
image:
  repository: localhost:5000/api
  tag: latest
  pullPolicy: Always
```
- Skaffold version: 0.16.0
- Operating system: osx
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: localhost:5000/api
deploy:
  helm:
    releases:
    - name: team-frontend-api
      chartPath: chart
```
adding
```
    imageStrategy:
        helm: {}
```
did not make a change

**Comment by Miouge1** [comment]
A `helm get values myrelease` shows that the `image.repository` and `image.tag` values are not passed when `imageStrategy` is set `helm: {}`

**Comment by balopat** [comment]
Hi @Miouge1, can you try to add `localhost:5000/api` to the release? 

```
deploy:
  helm:
    releases:
    - name: team-frontend-api
      chartPath: chart
      values: 
          image: localhost:5000/api
```
