### ISSUE TITLE
Port Forwarder races with Helm chart deployment

### ISSUE THREAD

**Issue by eaceaser** [GoogleContainerTools/skaffold#1189]
Starting the logger and the port forwarder after the deployment is race-y with the events fired from the deployment. The logger seems to be more resilient as its less picky about what events it picks up.

### Expected behavior
Skaffold detects helm chart containers when they come up and port forwards appropriately.

### Actual behavior
When a container comes up quickly, the port forwarder isn't started in time to see the k8s pod modified event to trigger port forwarding.

### Information

- Skaffold version: `v0.16.0-77-g62b33279`
- Operating system: `Linux 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux`
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: <REDACTED>
    context: .
deploy:
  helm:
    releases:
      - name: my-service-dev
        namespace: test-skaffold
        chartPath: /path/to/local/chart
        values:
          image: <REDACTED>
        imageStrategy:
          helm: {}
```

### Steps to reproduce the behavior

1. Run `skaffold dev [--port-forward]` where k8s will be able to start the pod and container very quickly.

### Notes

I have confirmed that this a race -- starting the port forward watcher before the deployment guarantees that the event is picked up.
