### ISSUE TITLE
Skaffold unable to push to private docker registry when using docker login

### ISSUE THREAD

**Issue by hpio** [GoogleContainerTools/skaffold#1191]
After upgrading from Skaffold 0.14.0 to 0.16.0. **docker login** authentication no longer works and results in the following error when pushing to a private docker registry
```
    - docker login -u _json_key -p "$(echo $GCP_DOCKER_REGISTRY_SA | base64 -d)" https://eu.gcr.io
    - skaffold build -p no-deploy
```
```
time="2018-10-17T15:40:57Z" level=fatal msg="build step: building [eu.gcr.io/project-production/scheduler]: tagging: pushing: getting auth config for eu.gcr.io/project-production/scheduler:alpha.tasks-api-facets: getting auth config: error getting credentials - err: exit status 1, out: ``"
```

Everything works as expected when using `gcloud auth configure-docker`

### Expected behavior
`docker login` should succed and Skaffold should be able to push to a private docker registry
### Actual behavior
Skaffold throws en error `time="2018-10-17T15:40:57Z" level=fatal msg="build step: building [eu.gcr.io/project-production/scheduler]: tagging: pushing: getting auth config for eu.gcr.io/project-production/scheduler:alpha.tasks-api-facets: getting auth config: error getting credentials - err: exit status 1, out: ``"`

### Information

- Skaffold version: 0.16.0
- Operating system: Gitlab Runner

```yaml
apiVersion: skaffold/v1alpha4
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.APP_VERSION}}"

# add new packages here...
  artifacts:
  - image: eu.gcr.io/project-production/scheduler
    context: ./debug

profiles:
  - name: no-deploy
    deploy: {}
```

### Steps to reproduce the behavior

1. login to a private registry using `docker login`
2. run `skaffold build -p no-deploy`
