### ISSUE TITLE
[proposal] Move ArtifactType -> artifact.type, BuildConfig.BuildType -> build.location

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1203]
## Background

We have three places in our pipeline config where we use "inline oneOf" fields currently: `BuildConfig.BuildType`, `DeployConfig.DeployType`, `Artifact.ArtifactType` They are "oneOf" fields - our DIY "union types" - choices are represented as fields and we validate against multiple choices runtime. They are "inline" as these "choice fields" become part of the parent element.

e.g.: 
````
apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
    docker:
        target: "mytarget"
        cacheFrom:
          - "baseimage1"
          - "baseimage2"
  kaniko:
    buildContext: 
      localDir: {}
    pullSecretName: e2esecret
    namespace: default
````
 
## Problem 

Out of these `BuildConfig.BuildType` and `Artifact.ArtifactType` are mixed in with other properties. For example `Artifact.Image`, `Artifact.Sync`, `Artifact.Context`, which becomes confusing when used in an IntelliSense context: 

![image](https://user-images.githubusercontent.com/635073/47521095-e66ccb00-d846-11e8-976e-61a6ae74d5a3.png)

## Proposal 

1.) Move ArtifactType to a non-inline field: `artifact.type`: 
 
![image](https://user-images.githubusercontent.com/635073/47521239-62671300-d847-11e8-9e8b-170c8952babc.png)

![image](https://user-images.githubusercontent.com/635073/47521213-482d3500-d847-11e8-965f-65c61a246a45.png)

2.) Move BuildConfig.BuildType under `build.location`
This would also help with resolving some of the readability arguments in 

https://github.com/GoogleContainerTools/skaffold/issues/1179 
https://github.com/GoogleContainerTools/skaffold/issues/955
https://github.com/GoogleContainerTools/skaffold/issues/953
