### ISSUE TITLE
Skaffold fix fails when overwriting existing file on Windows

### ISSUE THREAD

**Issue by aleksamagicka** [GoogleContainerTools/skaffold#1214]
### Expected behavior
The file is overwritten with new configuration.
### Actual behavior
λ skaffold fix > skaffold.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1216574]

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.NewCmdFix.func1(0xc0422d3b80, 0x1ff16f0, 0x0, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/fix.go:45 +0xd4
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).execute(0xc0422d3b80, 0x1ff16f0, 0x0, 0x0, 0xc0422d3b80, 0x1ff16f0)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:766 +0x2c8
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1fbefa0, 0xc0422d3180, 0xc0422d2f00, 0xc0422d2c80)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:852 +0x311
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).Execute(0x1fbefa0, 0xc0420ae008, 0x1685340)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:800 +0x32
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x0, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/skaffold.go:27 +0x5f
main.main()
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/skaffold.go:26 +0x29
### Information

- Skaffold version: v0.17.0
- Operating system: Windows 7 Ultimate SP1 x64
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha4
kind: Config
build:
  tagPolicy:
    # Tag the image with the git commit of your current repository.
    gitCommit: {}

  artifacts:
  - image: myproject
    # The path to your dockerfile context. Defaults to ".".
    context: ./myproject

    docker:
      # Dockerfile's location relative to workspace. Defaults to "Dockerfile"
      dockerfile: Dockerfile
      # Images to consider as cache sources
      cacheFrom:
      - microsoft/dotnet:2.1-aspnetcore-runtime
      - microsoft/dotnet:2.1-sdk

# The deploy section has all the information needed to deploy. Along with build:
# it is a required section.
deploy: {}
```

### Steps to reproduce the behavior

1. `skaffold fix > skaffold.yaml'
2. It crashes and the file ends up empty.
