### ISSUE TITLE
skaffold.yaml misconfiguration throws SIGSEGV without an error message

### ISSUE THREAD

**Issue by gintautassulskus** [GoogleContainerTools/skaffold#1215]
Running `skaffold dev` on `exapmples/skaffold-helm` with a bad configuration throws a SIGSEGV error without giving a clue on what has cused it.

Configuration errors should be expected and handled gracefully.

### Expected behavior
An informative error output, ideally pointing to the line that has caused the error.

### Actual behavior
$ skaffold dev
```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1dd3507]

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.newRunner(0x2b83120, 0xc420476110, 0x22595e0, 0xc420046200, 0xc420476110)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/runner.go:36 +0x67
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.delete(0x223e420, 0xc4200ca008, 0x0, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/delete.go:46 +0x9a
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.dev.func1(0x223e420, 0xc4200ca008)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/dev.go:57 +0x39
panic(0x1f48360, 0x2b5b4b0)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.newRunner(0x2b83120, 0xc420438000, 0x223e400, 0xc4200ca008, 0xc420526590)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/runner.go:36 +0x67
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.dev(0x223e420, 0xc4200ca008, 0x0, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/dev.go:68 +0xf8
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.NewCmdDev.func1(0xc42055e780, 0x2ba1ac8, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/dev.go:36 +0x33
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).execute(0xc42055e780, 0x2ba1ac8, 0x0, 0x0, 0xc42055e780, 0x2ba1ac8)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2b6e140, 0xc42055e780, 0xc42055e500, 0xc42055e280)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).Execute(0x2b6e140, 0xc4200ca008, 0x223e420)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x0, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/skaffold.go:27 +0x58
main.main()
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/skaffold.go:26 +0x22
```
### skaffold.yaml

```yaml
apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: skaffold-helm-non-exitent
      #wait: true
      #valuesFiles:
      #- helm-skaffold-values.yaml
      values:
        image: gcr.io/k8s-skaffold/skaffold-helm
      #recreatePods will pass --recreate-pods to helm upgrade
      #recreatePods: true
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.  
      #setValues:
        #some.key: someValue
```

### Information

- Skaffold version: 0.17.0 (as far as aI can remember affects previous release as well)
- Operating system: macOS 10.14
- Contents of skaffold.yaml: examples/skaffold-helm/skaffold.yaml (unchanged)

### Steps to reproduce the behavior

1. `cd examples/skaffold-helm`
2. edit `skaffold.yaml`, change `chartPath` to `skaffold-helm-non-exitent`
3. run `skaffold dev`
