### ISSUE TITLE
Add port forwarding options to global config

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#1219]
We should add port forwarding options into the global config, so users don't have to provide the `--port-forward=false` flag on every run. This would make sense on a per-context basis as well. e.g.

```yaml
global:
  default-repo: gcr.io/k8s-skaffold
  port-forward: false
...
kubeContexts:
- kube-context: gke_k8s-skaffold_us-west1-a_cluster
  port-forward: false
```

ref #1038
