### ISSUE TITLE
Labeling doesn't work for hardcoded namespace

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1224]
```
apiVersion: v1
kind: Pod
metadata:
  name: something
  namespace: something
```

WARN[0047] error adding label to runtime object: patching resource /something: pods "something" not found
