### ISSUE TITLE
Using Skaffold on Ubuntu Subsystem errors when building

### ISSUE THREAD

**Issue by taylorKonigsmark** [GoogleContainerTools/skaffold#1232]
### Expected behavior
When I have a Docker Engine Running on Windows 10 with an Ubuntu subsystem, I would expect that Skaffold can build and push to the engine on Windows 10
### Actual behavior
I get an error saying:

`WARN[0000] cleanup: creating runner: creating runner: parsing skaffold build config: getting docker client: Error getting docker client: unable to parse docker host `"localhost:2375"`
FATA[0000] creating runner: creating runner: parsing skaffold build config: getting docker client: Error getting docker client: unable to parse docker host `"localhost:2375"``
### Information
- Docker Engine is running on Windows 10
- Docker daemon is exposed on tcp://localhost:2375
- Ubuntu subsystem is running on Windows 10
- I can view docker images available in engine on both windows and Ubuntu
- Skaffold version: v0.17.0
- Operating system: Windows 10
- Ubuntu subsystem: Ubuntu 18.04.1 LTS
- Contents of skaffold.yaml:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: gcr.io/k8s-skaffold/skaffold-jib
```

### Steps to reproduce the behavior

1. Run skaffold dev command on the Ubuntu subsystem
2. Observe the error
