### ISSUE TITLE
skaffold init produces yaml with empty `kind`

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1236]
```
skaffold init
```
```
apiVersion: skaffold/v1alpha5
kind: ""
build:
  artifacts:
  - image: gcr.io/dga-demo/hello
deploy:
  kubectl:
    manifests:
    - k8s/pod.yaml
```
