### ISSUE TITLE
scaffold Dev:

### ISSUE THREAD

**Issue by mohade09** [GoogleContainerTools/skaffold#1238]
@skaffold dev -v debug doesn't work with sample example

- Skaffold version: v0.17.0
- Operating system: Mac OS 10.13.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: debadatta/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
```
