### ISSUE TITLE
[Proposal] - Allow passing custom GCB build config (KMS, secrets, steps, config)

### ISSUE THREAD

**Issue by ss-vdav-debug** [GoogleContainerTools/skaffold#1262]
While trying to review the possibility to implement the development workflows with Skaffold,
I found that currently there is no secure way to pass encrypted credentials.

For many companies it is required to be able to follow KMS based key decryption
https://cloud.google.com/cloud-build/docs/access-private-github-repos

### Information

- Skaffold version: 0.18.0
- Operating system: All
- Contents of typical build configuration within GCB:

```yaml
timeout: 1200s
images: ['${_IMAGE}']
steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build --build-arg GITHUB_PRIVATE_KEY="$$GITHUB_PRIVATE_KEY" -t ${_IMAGE} .']
  secretEnv: ['GITHUB_PRIVATE_KEY']
options:
 logging: GCS_ONLY
secrets:
- kmsKeyName: <<<KEY>>>
  secretEnv:
    GITHUB_PRIVATE_KEY: <<<PRIVATE_KEY>>>
```

### Steps to reproduce the behavior

Try to follow KMS build workflow.
