### ISSUE TITLE
skaffold dev fails to pass the image to container-structure-test correctly

### ISSUE THREAD

**Issue by NorthIsUp** [GoogleContainerTools/skaffold#1296]
I'm trying to use the test phase and something is failing when passing the image to container-structure-test.

### Expected behavior
`skaffold dev` successfully runs tests

### Actual behavior
`skaffold dev` test fails with the error `Error: error setting env vars: Error creating container: no such image`

### Information

- Skaffold version: v0.18.0
- container-structure-test version: v1.5.0
- Operating system: 10.13.6 (17G3025)
- Contents of skaffold.yaml: examples/structure-tests/skaffold.yaml from 9239cc4c64390e944e94918141165ab3ed4d39e4

```yaml
apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
test:
  - image: gcr.io/k8s-skaffold/skaffold-example
    structureTests:
      - ./test/*
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: k8s-skaffold
  - name: test
    test:
      - image: gcr.io/k8s-skaffold/skaffold-example
        structureTests:
          - ./test/profile_structure_test.yaml
```

### Steps to reproduce the behavior

1. cd examples/structure-tests
2. skaffold dev

```
> pwd
~/src/skaffold/examples/structure-tests

> skaffold dev
Starting build...
Found [minikube] context, using local docker daemon.
Building [gcr.io/k8s-skaffold/skaffold-example]...
Sending build context to Docker daemon  3.072kB
Step 1/6 : FROM golang:1.10.1-alpine3.7 as builder
1.10.1-alpine3.7: Pulling from library/golang
ff3a5c916c92: Already exists
f32d2ea73378: Pulling fs layer
c6678747892c: Pulling fs layer
16b5f22d8b23: Pulling fs layer
16b5f22d8b23: Verifying Checksum
16b5f22d8b23: Download complete
f32d2ea73378: Verifying Checksum
f32d2ea73378: Download complete
f32d2ea73378: Pull complete
c6678747892c: Verifying Checksum
c6678747892c: Download complete
c6678747892c: Pull complete
16b5f22d8b23: Pull complete
Digest: sha256:356aea725be911d52e0f2f0344a17ac3d97c54c74d50b8561f58eae6cc0871bf
Status: Downloaded newer image for golang:1.10.1-alpine3.7
 ---> 52d894fca6d4
Step 2/6 : COPY main.go .
 ---> 138fa2c9e5be
Step 3/6 : RUN go build -o /app main.go
 ---> Running in 70de49e80c68
 ---> 5e0fd04fece9
Step 4/6 : FROM alpine:3.7
3.7: Pulling from library/alpine
c67f3896b22c: Pulling fs layer
c67f3896b22c: Verifying Checksum
c67f3896b22c: Download complete
c67f3896b22c: Pull complete
Digest: sha256:a52b4edb6240d1534d54ee488d7cf15b3778a5cfd0e4161d426c550487cddc5d
Status: Downloaded newer image for alpine:3.7
 ---> 34ea7509dcad
Step 5/6 : CMD ./app
 ---> Running in 2d894b5ef1e3
 ---> 383f09918425
Step 6/6 : COPY --from=builder /app .
 ---> c9e30e132333
Successfully built c9e30e132333
Successfully tagged 43df85c036e2f65f2cb62928b310e39d:latest
Build complete in 36.165387284s
Starting test...

====================================================
====== Test file: profile_structure_test.yaml ======
====================================================

=== RUN: no go binary
--- FAIL
Error: error setting env vars: Error creating container: no such image

============================================
====== Test file: structure_test.yaml ======
============================================

=== RUN: no local go binary
--- FAIL
Error: error setting env vars: Error creating container: no such image
ERROR: FAIL

=============================================
================== RESULTS ==================
=============================================
Passes:      0
Failures:    2
Total tests: 2

FAIL

ERROR: FAIL
Cleaning up...
Cleanup complete in 366.239698ms
FATA[0039] exiting dev mode because the first test run failed: running structure tests: running container-structure-test: exit status 1
```
