### ISSUE TITLE
Helm section ignores templating

### ISSUE THREAD

**Issue by yurchenkosv** [GoogleContainerTools/skaffold#1301]
### Expected behavior
Skaffold will inject tag in helm values, so with new skaffold run, k8s will pull new image.
It can be achieved  by adding templating into helm section like this:
```yaml
      setValues:
        image.repository: <imageRepo>
        image.tag: {{ .IMAGE_NAME}}:0.0.2-{{ .DIGEST_HEX }}
```
### Actual behavior

Helm using same tag as  tagPolicy define.
If I using image with tag latest, k8s will not pull new image, because of image with tag latest already present on machine (k8s node) and I cannot assign tag, which skaffold assigns
```yaml
      setValues:
        image.repository: <imageRepo>
        image.tag: latest
```

### Information

- Skaffold version: v0.17.0
- Operating system: Debian stretch 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: <imageName>
  tagPolicy:
    envTemplate:
      template: "{{ .IMAGE_NAME}}:3.0.0.1-SNAPSHOT-{{ .DIGEST_HEX }}"
deploy:
  helm:
    releases:
    - name: skaffold-dev-server
      chartPath: "helm/dev-server"
      namespace: dev
      setValues:
        image.repository: <imageRepo>
        image.tag: latest
      valuesFiles:
        - "helm/server/values.yaml"
profiles:
   - name: gcb
     build:
       googleCloudBuild:
         projectId: <projID>
```

### Steps to reproduce the behavior

1. ...
2. ...

**Comment by maximbaz** [comment]
Am I right to assume that even if I use `sha256: {}` as `tagPolicy`, I should still be able to use `{{ .DIGEST }}` and others in the helm section, like so?

```
apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: <imageName>
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
    - name: skaffold-dev-server
      chartPath: "helm/dev-server"
      setValues:
        image.tag: "{{ .DIGEST }}"
      valuesFiles:
        - "helm/server/values.yaml"
```

Also, I can't seem to grasp what's the difference between:

```
values:
  image.tag: "{{ .DIGEST }}"
```

and 

```
setValues:
  image.tag: "{{ .DIGEST }}"
```

Does anyone know?
