### ISSUE TITLE
How could a production cluster reject yamls applied by `skaffold dev`?

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1313]
It’s super dangerous that developers can deploy to production from `skaffold dev` just because they forgot to switch the kube context.

Is there a way to reject yamls coming from `skaffold dev` in production?

I first thought of an admission controller that would recognize the labels applied by Skaffold but then I remembered those labels are applied afterwards.

**Comment by nkubala** [comment]
Hmm, could we do something like blacklisting kube contexts in the global config? Something like 
`skaffold config add blacklist <context>` or `skaffold config blacklist` (to blacklist the current context).

Then skaffold can quickly check the current context against the list of blacklisted contexts, and refuse to run.

**Comment by dgageot** [comment]
@nkubala That's something that could work. Something cluster-side would protect the production environment even if users forget to edit their blacklist

**Comment by nkubala** [comment]
Yeah, my only concern with that is that by nature skaffold is more of a client side tool, so it feels a little weird to delve into running something by default in a cluster, especially a production cluster. Maybe not the end of the world though.

We could provide a small "protector" image that skaffold deploys to a user's cluster, that protects against all deployments coming from skaffold (through labels or whatever). Then a user could run a command like `skaffold protect` or `skaffold protect-cluster` to deploy the image as a pod in their cluster, which would block all deploys coming from skaffold until they undo it with another skaffold command. Just a thought.

**Comment by dgageot** [comment]
Clearly not top priority but I like the idea of `skaffold protect-cluster`

**Comment by pscarey** [comment]
I don't think the issue is just about `skaffold dev`, but also `skaffold deploy` and any other cluster changing commands.

My opinion is that protection of production clusters from accidental (or intentional) damage should be achieved via Kubernetes user accounts and `helm`/`tiller` SSL. (i.e. existing permissions systems). Regardless of `skaffold` usage or not, your average developer should not have full permissions for a production cluster on their local machine (or any of the configuration secrets required to run a production application).

There are also a couple of challenges with the protector image approach:
- It would need to be disabled + re-enabled either side of deploy, e.g. `skaffold unprotect && skaffold deploy && skaffold protect`. This could end up in a broken, unprotected state if the `skaffold deploy` fails from a CI system.
- Additionally, how do you control who can run `skaffold protect` or `skaffold unprotect`. Back to the permissions the developer should have.

The problem to then solve is then about switching between multiple unauthenticated or low privelige clusters, e.g. a development cluster and a local cluster.

I think it makes more send to use a configuration whitelist over a blacklist. A developer could be switching between many different projects with different `skaffold.yaml` configurations. A blacklist would mean listing out all the clusters the developer has permission to access, rather than just the clusters pertinent to that specific project. This could be implemented at the `deploy` level, and could support profiles:

```
...
deploy:
  contexts:
     - name: minikube # Only deploy if to minikube (local configuration)
...
profiles:
  - name: dev
    deploy:
      contexts:   
        - name: gke_project_name_country-region1_dev # Development cluster
      ...
  - name: staging
    deploy:
      contexts:   
        - name: gke_project_name_country-region1_staging # Staging cluster
      ...
  - name: production
    deploy:
      contexts:   
        - name: gke_project_name_country-region1_production # Staging cluster
      ...
```

In this example, a developer might have permission to deploy locally to `minikube` and in the `gke_project_name_country-region1_dev` clusters, and so is prevented from being in the wrong context by accident.

However, it should be documented and strongly advised that additional protection over who can deploy what should be implemented from production clusters, regardless of the use of Skaffold.

**Comment by stevesea** [comment]
As a  work around for devs accidentally doing this to production/staging envs... I stick an invalid namespace in the helm deployment section of skaffold.yaml:

```
  deploy:
    helm:
      releases:
      - name: localdev-mysvc
        namespace: YOU_MUST_OVERRIDE_THE_NAMESPACE_ON_CLI
        chartPath: ./chart/mysvc
        values:
          imageName: mysvc
```

Then the developer has to run like `skaffold dev -n <namespace>`
