### ISSUE TITLE
Skaffold retriggers pipeline when helm chart is inside the main directory

### ISSUE THREAD

**Issue by netcho** [GoogleContainerTools/skaffold#1320]
### Expected behavior
Running "skaffold dev" command with helm configured as deployment method would build the artifacts, deploy and then watch for changes. The helm chart directory is in the same directory as the skaffold.yaml

### Actual behavior
Running "skaffold dev" with the helm chart directory in the same place as skaffold.yaml produces an infinite loop of building, deploying.

### Information

- Skaffold version: v0.18.0
- Operating system: Windows 10 Pro x64
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: netcho/bnetserver
    docker:

deploy:
  helm:
    releases:
    - name: aurora-development
      chartPath: ./chart/
      namespace: default
      values:
        image: netcho/bnetserver
      setValues:
        rabbitmq.rabbitmq.password: 65sdof6516
        mysql.hostname: 192.168.1.5
        mysql.database: battlenet
        authentication.debug: true
        env: development
```

### Steps to reproduce the behavior
1. Run skaffold dev with helm deployment method as in the config provided.

Apparently helm is making some changes to its chart directory which makes skaffold think file changes have occurred. Perhaps have a .skaffoldignore file or another mean of telling skaffold to ignore files and directories? If so, how would it find out that a change in the helm chart has occurred and therefore it needs to redeploy the app?
