### ISSUE TITLE
Doesn't detect changes to subcharts

### ISSUE THREAD

**Issue by rootd00d** [GoogleContainerTools/skaffold#1347]
Skaffold seems to not detect changes to subcharts.  I've created an umbrella chart, and am using subcharts for various sites & services.  In 'dev' mode, changing the contents of a subchart in "charts" ought be detected & deployed.

### Expected behavior

Modifying a subchart in "charts" should trigger a redeploy.

### Actual behavior

Seemingly, nothing.

### Information

- Skaffold version: v0.18.0
- Operating system: MacOS 10.14.1

**Comment by nkubala** [comment]
@rootd00d thanks for the issue. Can you provide your `skaffold.yaml`? I'm wondering if this is an issue with the file watcher, or with the way that we handle helm redeploys.

**Comment by rootd00d** [comment]
Does the version of the subchart need to be incremented in order to trigger a redeploy?

```
apiVersion: skaffold/v1alpha5
kind: Config
profiles:
  - name: development
    build:
      artifacts:
      - image: [REDACTED]
        context: ./docs

    deploy:
      helm:
        releases:
        - name: aries
          chartPath: .
          namespace: aries-development
          values:
            gated-content.image: [REDACTED]
          valuesFiles:
            - development/values.yaml
```
