### ISSUE TITLE
Windows to Linux file sync does not properly sync files in subfolders

### ISSUE THREAD

**Issue by valery-vitko** [GoogleContainerTools/skaffold#1350]
### Expected behavior

When running skaffold on Windows with file sync set up for a folder structure, it should sync all files properly.

### Actual behavior

Sync creates files with backslashes, e.g. file `src\app.ts` in the `/usr/src/app/` instead of `app.ts` in the `/usr/src/app/src/`:

``` powershell
$ > kubectl exec $pod -- ls /usr/src/app
...
src
src\app.ts # not a file in the src/ but on the same level
...

$ > kubectl exec $pod -- ls /usr/src/app/src
app.html
app.ts
...
```

### Information

- Skaffold version: v0.19.0
- Operating system: Windows 10 Build 17134
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: ...
    sync:
      'src/**': ./src
 ...
```

### Steps to reproduce the behavior

1. Configure sync with a glob pattern to match a subfolder, e.g. `'**': .`.
2. Change a file in a subfolder.
3. Observe the file in a root sync folder with a wrong name.
