### ISSUE TITLE
Support kubectl deploy using manifest from url

### ISSUE THREAD

**Issue by ahmadnurus** [GoogleContainerTools/skaffold#1353]
### Expected behavior

Sometimes we need to deploy using manifests that doesn't exist in the local machine. like someone only provides the manifest in remote repository, snippet or gists. it would be better if skaffold support deploying using manifest from url.

This might look the following:

```yaml
apiVersion: skaffold/v1beta1
kind: Config
build:
...
deploy:
  kubectl:
  # ------------- from file ------------- #
    manifests:
    - mylocal/manifest/*.yml
  # ------------- from url -------------- #
    urlManifests:
    - https://gist.githubusercontent.com/someone/somesnippet/raw
    - https://raw.githubusercontent.com/GoogleContainerTools/skaffold/master/examples/getting-started/k8s-pod.yaml
```

and we don't need to execute `kubectl apply -f https://gist.githubusercontent.com/someone/somesnippet/raw` for manifests that doesn't exist in the local machine.

### Actual behavior

Not supported yet

### Steps to reproduce the behavior

1. Add `URLManifests` in `KubectlDeploy` struct schema
2. Create some function to read manifest from url `eg: using http.NewRequest` and append it to `kubectl.ManifestList`
