### ISSUE TITLE
Sync does not sync new directories

### ISSUE THREAD

**Issue by DylanArnold** [GoogleContainerTools/skaffold#1365]
### Expected behavior
- Creating a new directory when sync is enabled should create the directory in the target container
- (`Syncing 1 files for example:xxxxx` should appear in the console when a new directory is created)
- This is a problem if you subsequently create a file inside the directory. It will not sync the file because the target directory does not exist, resulting in an error

### Actual behavior
A new directory is not created in the target container.

### Information

- Skaffold version: v0.19.0
- Operating system: Ubuntu 18.04.1

`kubectl cp` supports copying a directory but it appears as though Skaffold skips new directories. I believe the problem originates in `pkg/skaffold/docker/parse.go` in `GetDependencies`. 

It looks like execution for a directory executes `case mode.IsDir():` at: https://github.com/GoogleContainerTools/skaffold/blob/v0.19.0/pkg/skaffold/docker/parse.go#L305

and `if info.IsDir() {` at: https://github.com/GoogleContainerTools/skaffold/blob/v0.19.0/pkg/skaffold/docker/parse.go#L323

Note that `files` is never modified in this case. 

EDIT: Even though `kubectl cp` will copy a directory, after further testing this won't be a good solution. It is fine when a directory is initially created, however as new files are added to it, the directories modification time is updated. This would trigger a resync of the directory, and the resulting `kubectl cp` of the directory would (unnecessarily) copy all contents as well...  A possible solution could be to use `kubectl exec` and `mkdir`. 

#### skaffold.yaml
```yaml
apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
    - image: example
      context: .
      docker:
        dockerfile: ./Dockerfile
      sync:
        '**': /root

deploy:
  kubectl:
    manifests:
      - "example.yaml"
```

#### Dockerfile
```
FROM ubuntu:18.04

COPY . /root

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"
```

#### example.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    component: example
spec:
  containers:
    - name: example
      image: example
```

### Steps to reproduce the behavior

1. `skaffold dev`
2. `mkdir this-doesnt-sync`
