### ISSUE TITLE
Skaffold failing to sync with helm

### ISSUE THREAD

**Issue by gevans22** [GoogleContainerTools/skaffold#1379]
### Expected behavior
Skaffold using Helm  should sync the same as with Kubectl. 

### Actual behavior
Skaffold-dev with helm loads the cluster and the helm charts but does not sync properly when updating the project files. Has been tried with a node.js backend server and a front-end application. 

Error received is "WARN[0090] Skipping deploy due to sync error: copying files: couldn't sync all the files".

### Information

- Skaffold version: v0.19.0
- Operating system: OSX 10.13.4
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta1
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: [registryaddress]/rest-api
    context: ./rest-api
    sync:
      '*.js' : .
      'app/**/*.js': app/
      'test/**/*.js': test/
  - image: [registryaddress]/frontend
    context: ./frontend/
    sync:
      '*.js' : .
      'src/**/*.js': src/
      'src/**/*.jsx': src/
deploy:
#  kubectl:
#    manifests:
#    - ./**/k8s/*
  helm:
    releases:
    - name: rest-api
      chartPath: rest-api
    - name: microservice1
      chartPath: microservice1
    - name: microservice2
      chartPath: microservice2
    - name: redis
      chartPath: redis
    - name: db1
      chartPath: db1
    - name: db2
      chartPath: db2
```

error seems to be occuring from 

### Steps to reproduce the behavior

1. skaffold-dev
2. edit file from application in local repo
3. skaffold doesn't sync and WARN

**Comment by kwngo** [comment]
Anyone have any idea what issue might be? I'd be willing to put together a patch with a bit of guidance

**Comment by kwngo** [comment]
Turns out my issue wasn't a bug, I was just missing some configuration in `deployment.yaml`. In my case, I needed to pass `values.global.image`, which will be of format `base-image:<sha256>`, to `deployment.yaml` using {{ $.Values.global.image }}

```
# skaffold.yaml
....
build:
  - image: base-image
    context: .
    sync:
        '**/*.py': /src
deploy:
  helm:
    releases:
     - name: frontend
       chartPath: charts/
       values:
         global.image: base-image

# deployment.yaml
container:
    - name: uwsgi
      image: {{ $.Values.global.image | default "base_image" }} 
      imagePullPolicy: Never
```
