### ISSUE TITLE
envTemplate.template ignored on skaffold dev

### ISSUE THREAD

**Issue by gbates101** [GoogleContainerTools/skaffold#1389]
Not sure if I'm missing something obvious, but...

### Expected behavior
When image is tagged during `skaffold dev`, the `envTemplate.template` definition under `tagPolicy` section should be used.
### Actual behavior
When image is tagged during `skaffold dev`, the `envTemplate.template` definition is ignored completely, and a \<random-hash\>:latest tag is used instead. Even on repeat runs, it will tag the same image each time with a different random hash. I've used literal strings and templates (`{{.IMAGE_NAME}}`, for example), and it does not change the behavior.
### Information

- Skaffold version: v0.19.0
- Operating system: WSL (Ubuntu on Windows)
- Running on Minikube
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: docker.io/plaidcloud/workflow
    sync:
      '*.py': .
  tagPolicy:
    envTemplate:
      template: "plaidcloud/workflow:dev"
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml

```

### Steps to reproduce the behavior

1. ...
2. ...
