### ISSUE TITLE
--tail Option Doesn't Work In Deploy Mode

### ISSUE THREAD

**Issue by cliffburdick** [GoogleContainerTools/skaffold#1393]
### Expected behavior
--tail behaves identically in run and deploy mode

### Actual behavior
Option doesn't work in run mode

### Information
```
- Skaffold version: 0.19
- Operating system: Ubuntu 18.04
```
Skaffold.yaml:
```
apiVersion: skaffold/v1beta1
build:
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.SALT}}'
deploy:
  kubectl:
    manifests:
    - con-fa7f86.yaml*
kind: Config
```

Kubernetes manifest:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: con-fa7f86
spec:
  template:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        image: 10.10.1.1:8100/uncommitted:0d9204
        name: main
        tty: true
```

### Steps to reproduce the behavior

1. Use skaffold run --tail and verify output works on pod
2. Run the same configs, but with skaffold deploy --tail and observe no output
3. kubectl log shows output is occurring in pod
