### ISSUE TITLE
Add support for Kustomize deployer mutations

### ISSUE THREAD

**Issue by paultiplady** [GoogleContainerTools/skaffold#1395]
### Expected behavior

It should be possible to configure the namespace of the kustomization dynamically.

### Actual behavior

It appears there is no way to configure the namespace dynamically in a Kustomization.

### Information

A common pattern for deploying k8s apps is to use a namespace per deploy. Another alternative is to use name prefixes inside a single namespace.

Both of these options are supported in Kustomize using the `kustomize edit set namespace|nameprefix` commands.

I don't see a way to achieve this effect in Skaffold. The best I can do is 

```
  - name: builds
    deploy:
      kustomize:
        path: deploy/kustomize/overlays/review
        flags:
          global:
            - "--namespace=foo"
```
but this fixes the namespace, rather than allowing it to be configured dynamically by the build environment (e.g. based on a PR slug).

- Skaffold version: v0.19.0
- Operating system: MacOS 10.14 (18A391)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
    - image: us.gcr.io/qwil-build/monolith
deploy:
  kustomize:
    path: deploy/kustomize/overlays/minikube
profiles:
 - name: builds
    deploy:
      kustomize:
        path: deploy/kustomize/overlays/review
        flags:
          global:
            - "--namespace="
```

This is certainly a feature request, but it's also not clear exactly what the best approach here would be.
