### ISSUE TITLE
error adding label to runtime object: patching resource: the server could not find the requested resource

### ISSUE THREAD

**Issue by r0bj** [GoogleContainerTools/skaffold#1404]
### Expected behavior

skaffold deploys workload without warning.

### Actual behavior

skaffold deploys workload with warning:
```
WARN[0001] error adding label to runtime object: patching resource /prod: the server could not find the requested resource
```

### Information

- Skaffold version: v0.19.0
- Operating system: macOS 10.14.2
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta1
kind: Config
deploy:
  kubectl:
    manifests:
    - ./prod.yaml
```

- Contents of prod.yaml:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: prod
spec:
  finalizers:
  - kubernetes
```

Similar behaviour is with cluster scoped workloads like `ClusterRole`, `ClusterRoleBinding`.

### Steps to reproduce the behavior

```
$ skaffold run
Starting build...
Build complete in 644.24µs
Starting test...
Test complete in 26.123µs
Starting deploy...
kubectl client version: 1.13
namespace/prod unchanged
WARN[0001] error adding label to runtime object: patching resource /prod: the server could not find the requested resource
Deploy complete in 1.929368483s
```
