### ISSUE TITLE
error adding label to runtime object: patching resource: deployments.apps not found

### ISSUE THREAD

**Issue by r0bj** [GoogleContainerTools/skaffold#1405]
### Expected behavior

skaffold properly deploys workload (and add labels) without warning.

### Actual behavior

skaffold deploys workload with warning and without adding labels.

### Information

- Skaffold version: v0.19.0
- Operating system: macOS 10.14.2
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta1
kind: Config
deploy:
  kubectl:
    manifests:
    - ./test.yaml
```

- Contents of test.yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: prod
spec:
  selector:
    matchLabels:
      app: nginx-test
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx
```

Note: namespace `prod` is used in this manifest.

### Steps to reproduce the behavior

1. set current kubectl context to use other namespace than `prod`

2. run skaffold
```
$ skaffold run
[...]
WARN[0003] error adding label to runtime object: patching resource /nginx-test: deployments.apps "nginx-test" not found
```

Warning is generated.

3. set current kubectl context to use `prod` namespace:
```
$ skaffold run
Starting build...
Build complete in 331.055µs
Starting test...
Test complete in 8.884µs
Starting deploy...
kubectl client version: 1.13
deployment.apps/nginx-test unchanged
Deploy complete in 658.545266ms
```

Skaffold runs without warnings.

**Comment by r2d4** [comment]
There was an issue where labeling was not namespace aware. I'm not sure if I've upstreamed the patch

**Comment by pscarey** [comment]
Experiencing a similar issue:

```
...
WARN[0029] error adding label to runtime object: patching resource default/istio-security-post-install-role-binding-istio-system: the server could not find the requested resource
...
```

Lots of other similar errors when installing Istio. We have a helm chart which installs our apps in the `default` namespace, and Istio installs in `istio-system`, under the same chart.

For our case, I believe this is caused by lines 150-155 of `pkg/skaffold/deploy/label.go`:

```
	var namespace string
	if accessor.GetNamespace() != "" {
		namespace = accessor.GetNamespace()
	} else {
		namespace = res.Namespace
	}
```

I believe the logic should be the other way round, i.e. use the `res.Namespace`, and fall back to the `accessor.GetNamespace()`. For us, `accessor` must be in `default`, but `res` should be in `istio-system` for the `istio` components.

I'll be making & testing changes locally, but we need to run them on top of other changes I've made (which there are pull requests for). Wanted to raise this here so that we dont bounce between breaking things for different scenarios.

**Comment by corneliusweig** [comment]
Seems to be fixed in master. Release 0.22.0 still has the issue, though.

**Comment by dgageot** [comment]
I'm going to close this issue since it seems to be fixed in master

**Comment by lduparc** [comment]
Using skaffold 0.34.1, issue still exist, it is not fixed.

**Comment by corneliusweig** [comment]
@lduparc Can you provide an example? This issue was closed, because it could not be reproduced.

**Comment by NotSoShaby** [comment]
I just had this issue when trying to play with skaffold (v1.0):

skaffold.yaml:

```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.BASE_TAG}}"
  artifacts:
  - imageName: <ECR>/<IMAGE_NAME>
    workspace: ..
    docker:
      dockerfilePath: ./Dockerfile
  local:
deploy:
  kubectl:
    manifests:
      - k8s-*
```

k8s-celery-pod.yaml:

```
apiVersion: v1
kind: Pod
metadata:
  name: celery
spec:
  containers:
  - name: celery
    image: <ECR>/<IMAGE_NAME>:<IMAGE_TAG>
    command: "pipenv run celery worker -c 4 -l INFO -A celery.core.celery"
```

Error:

```
Starting deploy...
Cleaning up...
WARN[0001] deployer cleanup: reading manifests: kubectl create: Running [kubectl --context  create --dry-run -oyaml -f l/Desktop/code/romee/k8s/k8s-celery-pod.yaml]: stdout , stderr: Error from server (NotFound): the server could not find the requested resource
, err: exit status 1: exit status 1
FATA[0001] exiting dev mode because first deploy failed: reading manifests: kubectl create: Running [kubectl --context  create --dry-run -oyaml -f /Desktop/code/romee/k8s/k8s-celery-pod.yaml]: stdout , stderr: Error from server (NotFound): the server could not find the requested resource
, err: exit status 1: exit status 1
```
