### ISSUE TITLE
[feature request] Add support for remote Kubernetes manifests

### ISSUE THREAD

**Issue by tariq-islam** [GoogleContainerTools/skaffold#1407]
### Expected behavior
Specify a remote URI for a manifest, or a set of manifests (akin to specifying a wildcard pattern) so that skaffold can utilize manifests for deployment that may not be locally available.

### Actual behavior
Skaffold currently expects all deployment manifests to be locally available on the file system, with the exception of remoteManifests which looks at pre-deployed resources, however I would like to not have to pre-deploy anything.
### Information

- Skaffold version: 0.19
- Operating system: Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: gcr.io/gcp-demo-200100/hello-world-nginx
  googleCloudBuild:
    projectId: gcp-demo-200100
deploy:
  kubectl:
    manifests:
    - https://raw.githubusercontent.com/tariq-islam/hello-world-nginx/master/hello-world-nginx-deploy.yaml

```

### Steps to reproduce the behavior

1. Under `deploy.kubectl.manifests`, specify a URI to a K8s manifest
2. Execute `skaffold run`
3. Note the error expecting a locally available manifest (home path is prepended to the URI)
