### ISSUE TITLE
tagging image: UNAUTHORIZED

### ISSUE THREAD

**Issue by NicklasWallgren** [GoogleContainerTools/skaffold#1460]
Expected behavior
Pulls image down and starts pods/etc.

Actual behavior
```
Built and pushed image as gcr.io/<project-id>/app:9ab10c77d7caf3f5db394542347be146
Executing tasks:
[==================================================] 100.0% complete


BUILD SUCCESSFUL in 8s
3 actionable tasks: 1 executed, 2 up-to-date
DEBU[0009] Running command: [git rev-parse --short HEAD] 
DEBU[0009] Command output: [43fa0e4
]                   
DEBU[0009] Running command: [git status . --porcelain]  
DEBU[0009] Command output: [?? app/.DS_Store
?? app/build/
?? app/out/
] 
FATA[0012] build failed: building [gcr.io/<project id>/app]: tagging: tagging image: UNAUTHORIZED: "authentication required" 
```

Information
I have run gcloud docker -a as well as can pull image locally with no issue.

Content of skaffold.yml
```
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
    - image: gcr.io/<project-id>/app
      jibGradle: {}
      context: app
```

I configured docker credentials through docker-credential-gcr configure-docker before running skaffold.
