### ISSUE TITLE
Add ability to pass in additional ports to port-forward

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/skaffold#1480]
As discussed offline, adding for tracking purposes:

It would be useful to be able to pass in a flag to the Skaffold execution with ports for Skaffold to port-forward in addition to those specified as container ports.

One use-case is for configuring debugging. In order to attach a debugger, it is necessary to port-forward the debug port. With this feature, tools like IDEs could then automate this by passing the debug port as a flag to Skaffold.

**Comment by priyawadhwa** [comment]
Hey @etanshaul , is it necessary for this to be a flag, or would a skaffold.yaml field work as well? Initially I preferred the flag but I forgot that the pod and container name may need to be passed in as well :sweat_smile: 

```yaml
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
  port-forward:
    - pod: getting-started
      container: hello-world
      ports: 
        - 8080
        - 9000
```
