### ISSUE TITLE
skaffold deploy should not automatically re-create resources

### ISSUE THREAD

**Issue by mxey** [GoogleContainerTools/skaffold#1484]
### Expected behavior

`skaffold deploy` when encountering an immutable field should fail with an error.
(`skaffold dev` can continue to automatically re-create)

### Actual behavior

`skaffold deploy` deletes and recreates the resource automatically, because it always uses `kubectl apply --force`. This leads to downtime of workloads.

### Information

- Skaffold version: v0.20.0
- Operating system: macOS 10.14.2 (18C54)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta2
kind: Config
deploy:
  kubectl:
    manifests:
      - deployment.yaml
```

- Contents of deployment.yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
```

### Steps to reproduce the behavior

1. `skaffold deploy`
2. Change `app: nginx` in deployment.yaml to `app: nginx2` (the selectors for Deployment are immutable)
3. `skaffold deploy`
