### ISSUE TITLE
Getting started throws unknown api version: 'skaffold/v1beta3'

### ISSUE THREAD

**Issue by clehene** [GoogleContainerTools/skaffold#1490]
### Expected behavior

Getting started example should work out of the box

### Actual behavior
```bash
skaffold dev
FATA[0000] creating runner: parsing skaffold config: unknown api version: 'skaffold/v1beta3'
```
### Information

- Skaffold version: version v0.20.0
- Operating system: osx
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. brew install skaffold
2. git clone https://github.com/GoogleContainerTools/skaffold
3. cd skaffold/examples/getting-started
4. skaffold dev
