### ISSUE TITLE
sync issue for local dev

### ISSUE THREAD

**Issue by shavo007** [GoogleContainerTools/skaffold#1503]
### Expected behavior
Sync files and reload the application without rebuilding docker image

### Actual behavior

Error complains does not match any sync pattern

```bash
INFO[0139] files modified: [src/index.js]
INFO[0140] Changed file src/index.js does not match any sync pattern. Skipping sync
```

### Information

- Skaffold version: version v0.20.0
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
    - image: shanelee007/graphql

deploy:
  kubectl:
    manifests:
      - kubernetes/config.yaml
      - kubernetes/deployment.yaml
      - kubernetes/secret.yaml

profiles:
  - name: dev
    build:
      artifacts:
        - image: shanelee007/graphql
          # context: dev
          sync:
            '/**/*.js': .
          docker:
            dockerfile: Dockerfile.dev

```

### Steps to reproduce the behavior
https://github.com/shavo007/graphql-playground/tree/master/api#run-locally

1.  clone repo https://github.com/shavo007/graphql-playground
2. run command `cd api &&  skaffold dev -p dev -v=info`
3. make a change to a src file
