### ISSUE TITLE
Change the explanation of "default repo" setting in the doc to reflect actual implementation 

### ISSUE THREAD

**Issue by ymotongpoo** [GoogleContainerTools/skaffold#1516]
### Expected behavior
Describe that 3rd default-repo config option described in the doc depends on kubectl context, not global.
https://skaffold.dev/docs/concepts/#image-repository-handling

### Actual behavior
It's documented as "skaffold’s global config", which is misleading. (Though `~/.skaffold/config` is global to all command call, the default repo setting is not "global")

### Information

- Skaffold version: v0.20.0
- Operating system: Debian 9.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: frontendservice
    context: src/frontend
  - image: arrayparseservice
    context: src/arrayparse
  - image: addnumberservice
    context: src/addnumber
deploy:
  kubectl:
    manifests:
    - ./k8s-manifests/**.yaml
profiles:
- name: gcb
  build:
    googleCloudBuild:
      diskSizeGb: 30
      machineType: N1_HIGHCPU_32
      timeout: 4000s
```

### Steps to reproduce the behavior

1. Set `artifacts/image` without target repo path.
2. Call `skaffold config set default-repo <REPO>` in some kubectl context
3. Change kubectl context
4. See the log `The push refers to repository [docker.io/library/xxxxxx]` and fail to deploy images during `skaffold dev/run`
