### ISSUE TITLE
Skaffold needs to work within namespace RBAC restrictions

### ISSUE THREAD

**Issue by michaelfig** [GoogleContainerTools/skaffold#1521]
### Expected behavior

`skaffold dev` works when the user only has access to the namespace specified in their `$HOME/.kube/config`.

### Actual behavior

Skaffold fails with a fatal error.

```
$ skaffold dev
[...]
Starting deploy...
kubectl client version: 1.13
[...]
Deploy complete in 753.995494ms
Cleaning up...
[..]
Cleanup complete in 7.630801087s
FATA[0016] starting logger: initializing pod watcher: unknown (get pods)
$
```

### Information

- Skaffold version: v0.20.0
- Operating system: darwin-amd64
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: registry.example.com/mypkg
    sync:
      'bin/**': '/opt/mypkg/bin/'
      'etc/**': '/opt/mypkg/etc/'
      'lib/**': '/opt/mypkg/lib/'
      'sbin/**': '/opt/mypkg/sbin/'

deploy:
  kubectl:
    manifests:
    - 'k8s/*.yaml'
```

### Steps to reproduce the behavior

1. Create a new namespace, and a user who only can access that namespace via RBAC.
2. Set the `.kube/config` for that user's credentials and namespace.
3. Run `skaffold dev` and have it create some resources in that namespace.
