### ISSUE TITLE
local port mapping with replicas collision

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/skaffold#1528]
Skaffold version `v0.21.1`

Setup:
I have a single service deployment with more than 1 replica with a single containerPort:

```
 replicas: 3
    ...
    spec:
      containers:
        - name: my-app
          image: [my-image]
          ports:
            - containerPort: 8081
              name: http-server
```

Expected (since https://github.com/GoogleContainerTools/skaffold/pull/1474 was merged and released) that Skaffold would map each replica to a different port on the machine.

Instead skaffold (attempts to) map each to `8081`:
```
Port Forwarding my-app-79c6565ccc-6pfr2 8081 -> 8081
Port Forwarding my-app-79c6565ccc-vsmlq 8081 -> 8081
Port Forwarding my-app-79c6565ccc-dmrsx 8081 -> 8081
```

So only one pod ends up being mapped.

Is this intended behavior? If so I would have expected a different message in the logs.
