### ISSUE TITLE
Support Profile patches

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1536]
It's currently hard to change only a single field with profiles. 

For example if one wants to change the `Dockerfile` for one of the artifacts in that yaml:

```
apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-app
    docker:
      dockerfile: Dockerfile
    context: app
  - image: gcr.io/k8s-skaffold/skaffold-web
    docker:
      dockerfile: Dockerfile
    context: web
```

then, the a profile has to duplicate all the artifacts definition:

```
profiles:
- name: DEV
  build:
  - image: gcr.io/k8s-skaffold/skaffold-app
    docker:
      dockerfile: Dockerfile.dev
    context: app
  - image: gcr.io/k8s-skaffold/skaffold-web
    docker:
      dockerfile: Dockerfile
    context: web
```

It would be nice if profiles supported patches like that:

```
profiles:
- name: DEV
  patches:
  - path: /build/artifacts/0/docker/dockerfile
    value: Dockerfile.dev
    op: replace
```

And if the default `op` is `replace` then we'd write:

```
profiles:
- name: DEV
  patches:
  - path: /build/artifacts/0/docker/dockerfile
    value: Dockerfile.dev
```
