### ISSUE TITLE
Sync does not sync the file in folder

### ISSUE THREAD

**Issue by chenlein** [GoogleContainerTools/skaffold#1558]
### Expected behavior
**a.txt can be synchronized, but b.txt can't.**

Structure of my project:
```
core
core/chart
core/src
core/src/main
core/src/main/java
core/src/main/resources
core/src/main/resources/a.txt
core/b.txt
core/Dockerfile
core/skaffold.yaml
```

However, when my modifed a.txt and b.txt, the following message show on STDOUT:
```
...
WARN[0004] error adding label to runtime object: patching resource /cloud-boot-test-connection: pods "cloud-boot-test-connection" not found 
Deploy complete in 2.160963833s
Watching for changes every 1s...
Port Forwarding cloud-boot-685cbfffd6-fp7hx 8080 -> 8080
Syncing 1 files for registry.kube.com/skaffold/cloud-boot:9711b1886df96f1452467b1de1710aa795c19772560c6911f7c16c2ce78edc55
Watching for changes every 1s...
Syncing 1 files for registry.kube.com/skaffold/cloud-boot:9711b1886df96f1452467b1de1710aa795c19772560c6911f7c16c2ce78edc55
Watching for changes every 1s...
```

Dockerfile:
```
FROM 192.168.101.88:5000/dmcop2/java:8
MAINTAINER leichen.china@gmail.com

ADD ./src/main/resources/a.txt /
ADD ./b.txt /

CMD sleep infinity
```

### Actual behavior
All of the txt file should be synced
### Information

- Skaffold version: v0.21.1
- Operating system: macOS 10.14.3 Darwin Kernel Version 18.2.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
    - image: registry.kube.com/skaffold/cloud-boot
      sync:
        '**/*.txt': /
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: cloud-boot
        chartPath: chart
        setValueTemplates:
          image.repository: "{{ .IMAGE_NAME }}"
          image.tag: "{{ .DIGEST }}"
          image.pullPolicy: "Always"
```

### Steps to reproduce the behavior
1. Execute `skaffold dev`
2. Modify file b.txt
3. Modify file a.txt
4. Execute `kubectl exec -ti cloud-boot-xxxxxxx bash`
5. Execute `cat /b.txt` in the container
6. Execute `cat /a.txt` in the container
