### ISSUE TITLE
Provide additional flags for Maven/Gradle

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1565]
It would be useful to set additional flags at the artifact level that would be passed to gradle or maven.
For eg, if one wants to skip tests.

Something like: 
```
apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-jib
    jibMaven:
      additionalFlags:
      - -x
      - -Dmaven.test.skip
```
