### ISSUE TITLE
DOCKER_TLS environment variable is not honored

### ISSUE THREAD

**Issue by turip** [GoogleContainerTools/skaffold#1582]
### Expected behavior

I would expect skaffold to work the same way as docker regarding the DOCKER_TLS flag: If it is set but no other TLS flag is set then TLS is still enabled but no actual certificate verification is done or needed.

(Note: this setup protected using VPN or the traffic is never leaving our AWS VPC so we are not too concerned about issues with self signed certificates)

#### Background

I have a setup in which I am using a remote dind pod running on a kubernetes cluster for building the images.

I cannot use kubectl proxy as it does not support HTTP/2:
```
failed to dial gRPC: unable to upgrade to h2c, received 404
FATA[0001] exiting dev mode because first run failed: build failed: building [dx-k8s-django-test]: build artifact: running build: exit status 1 
```
which is fine, so after creating a setup in which I am using nginx-ingress to direct the traffic to the dind pod over TLS (self signed) I can do this:

```
DOCKER_BUILDKIT=1 DOCKER_TLS=1 DOCKER_HOST="tcp://turip2.dev.XXXX:443" docker build --rm .
[+] Building 1.3s (19/19) FINISHED          
````
My expectation would be that 

```
DOCKER_TLS=1 DOCKER_HOST="tcp://turip2.dev.XXXX:443" skaffold dev
```
with the following settings:
```yaml
  - name: dev
    build:
      tagPolicy:
        envTemplate:
          template: "****"

      local:
        push: true
        useDockerCLI: false
        useBuildkit: true
    ...
```
Would work the same.

### Actual behavior

```
DOCKER_TLS=1 DOCKER_HOST="tcp://<NLB>:443" skaffold dev -p dev
Starting build...
Building [dx-k8s-django-test]...
[+] Building 1.3s (19/19) FINISHED                                                                                                                                                                                 
 FATA[0004] exiting dev mode because first run failed: build failed: building [dx-k8s-django-test]: build artifact: inspecting image: EOF 
```
I suspsect that this is due to this code: https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/docker/client.go#L97-L115 that is either forcing TLS verification or forces TLS off.

Could it be that we include the TLS initialization logic with empty CAFile, etc. when DOCKER_TLS is set to 1?

### Information

- Skaffold version: v0.22.0
- Operating system: ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "dx/{{.IMAGE_NAME}}:lde-black"

  artifacts:
    # The name of the image to be built.
  - image: dx-k8s-django-test
    context: .
    sync:
      '**/*.py': .
      '**/*.js': .
      '**/*.png': .
      '**/*.html': .

    docker:
      dockerfile: Dockerfile

  local:
    push: false
    useDockerCLI: false
    useBuildkit: false
...
profiles:
  - name: dev
    build:
      tagPolicy:
        envTemplate:
          template: "XXXX.dkr.ecr.us-east-1.amazonaws.com/dx-k8s:django-draf-test"

      local:
        push: true
        useDockerCLI: false
        useBuildkit: true
    deploy:
      helm:
        releases:
        - name: dx-k8s-django-test
          chartPath: charts/dx-k8s-django-test
          values:
            image: dx-k8s-django-test
          setValues:
            deployment.containers.imagePullPolicy: Always
          namespace: turip
          recreatePods: false

```

### Steps to reproduce the behavior

1. Have nginx-ingress in your cluster with TLS enabled
2. Create a dind pod:
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: dind-turip
  namespace: turip
  labels:
    app: turip-dind
spec:
  containers:
    - name: dind
      image: docker:stable-dind
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
      ports:
        - containerPort: 2375
  volumes:
    - name: dind-storage
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dind-turip
  namespace: turip
  labels:
    app: dind
spec:
  type: ClusterIP
  ports:
  - port: 2375
    targetPort: 2375
    protocol: TCP
    name: dind
  selector:
    app: turip-dind
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dind-ingress-ssl
  namespace: turip
  labels:
    app: turip-dind
spec:
  tls:
  - hosts:
    - turip2.dev.XXXX
  rules:
    - host: turip2.dev.XXXX
      http:
        paths:
        - path: /
          backend:
            serviceName: dind-turip
            servicePort: 2375
```
3. Use the commands above to reproduce
