### ISSUE TITLE
upgrading old config fails with unsupported type error

### ISSUE THREAD

**Issue by cpoole** [GoogleContainerTools/skaffold#1585]
### Expected behavior
my file should correctly parse and update

### Actual behavior
parsing fails but file is valid and works if we just manually change the apiVersion.

### Information

- Skaffold version: 0.21.0 to 0.22.0
- Operating system: linux - ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: local/app1
    context: .
  - image: local/redis-cl
    context: ./redis-local/
deploy:
  helm:
    releases:
    - name: app1
      chartPath: app1
      values:
        image: local/app1
        redisImage: local/redis-cl
      overrides:
        global:
          localstack:
            enabled: true
          environment: "local"
      namespace: "default"
      wait: false
      recreatePods: false
```

### Steps to reproduce the behavior

run skaffold fix and the following is printed:
```
WARN[0000] config version (skaffold/v1beta3) out of date: upgrading to latest (skaffold/v1beta4) 
FATA[0000] creating runner: parsing skaffold config: transforming skaffold config: converting deploy config: marshalling old: json: unsupported type: map[interface {}]interface {} 
```

but if I simply update the `apiVersion` to beta4 it works fine and skaffold is totally happy actually parsing the config
