### ISSUE TITLE
Custom kaniko image is ignored

### ISSUE THREAD

**Issue by everflux** [GoogleContainerTools/skaffold#1586]
### Expected behavior
When specifying build.kaniko.image it is possible to choose a custom image instead of the default gcr.io/kaniko-project/executor:v0.7.0@sha256:0b4e08...  image.

### Actual behavior
The default image is always used.

### Information

- Skaffold version: v.0.22.0
- Operating system: linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
  - image: localhost:31000/kaniko-demo
  kaniko:
    buildContext:
      localDir: {}
    Image: localhost:31000/kaniko/executor
    namespace: default
    cache: {}
deploy:
  kubectl:
    manifests:
    - k8s-*

```

### Steps to reproduce the behavior

1. skaffold run produces a pod with the (pinned) default skaffold executor image
