### ISSUE TITLE
kaniko --no-push flag fails build when getting non-existent digest

### ISSUE THREAD

**Issue by khrisrichardson** [GoogleContainerTools/skaffold#1597]
### Expected behavior

Whereas the following configuration does not attempt to get the digest:

```yaml
build:
  local:
    push: false
```

The following configuration should likewise circumvent the behavior introduced in #1428 

```yaml
build:
  kaniko:
    flags:
    - --no-push
```

### Actual behavior

```bash
INFO[0018] Skipping push to container registry due to --no-push flag
FATA[0032] build failed: building [foo/bar]: getting digest: getting digest: MANIFEST_UNKNOWN: "manifest unknown"
```

### Information

- Skaffold version: v0.22.0
- Operating system: N/A
- Contents of skaffold.yaml:

```yaml
build:
  kaniko:
    flags:
    - --no-push
```

### Steps to reproduce the behavior

1. add the `--no-push` flag to a kaniko build configuration
2. `skaffold build`
