### ISSUE TITLE
Dockerfile dependencies improperly computed

### ISSUE THREAD

**Issue by nathanph** [GoogleContainerTools/skaffold#1605]
It seems like there is a regression in how Skaffold discovers the dependencies for a Dockerfile.

### Expected behavior
With `skaffold-v0.21.1`:
```
DEBU[0000] setting Docker user agent to skaffold-v0.21.1
DEBU[0000] Checking base image node:10.13-alpine for ONBUILD triggers.
DEBU[0000] Found dependencies for dockerfile: [tslint.json webpack.config.ts yarn.lock .yarnrc tsconfig.json .env integration-test tslint-rules package.json yarn-offline-mirror src locales]
DEBU[0000] Checking base image node:10.13-alpine for ONBUILD triggers.
DEBU[0000] Found dependencies for dockerfile: [src locales .env integration-test webpack.config.ts yarn-offline-mirror yarn.lock .yarnrc tsconfig.json tslint.json tslint-rules package.json]
DEBU[0000] Checking base image node:10.13-alpine for ONBUILD triggers.
DEBU[0000] Found dependencies for dockerfile: [tslint.json webpack.config.ts package.json .yarnrc locales .env integration-test tslint-rules yarn-offline-mirror yarn.lock src tsconfig.json]
DEBU[0000] Checking base image node:10.13-alpine for ONBUILD triggers.
DEBU[0000] Found dependencies for dockerfile: [package.json yarn-offline-mirror locales .env webpack.config.ts yarn.lock .yarnrc src tsconfig.json integration-test tslint.json tslint-rules]
```

### Actual behavior
Note that none of the correct dependencies were discovered.
```
DEBU[0000] setting Docker user agent to skaffold-v0.22.0
INFO[0000] no config entry found for kube-context minikube
DEBU[0000] Checking base image node:10.13-alpine for ONBUILD triggers.
DEBU[0000] Found dependencies for dockerfile: [src locales tsconfig.json .env package.json]
DEBU[0000] Checking base image node:10.13-alpine for ONBUILD triggers.
DEBU[0000] Found dependencies for dockerfile: [package.json src locales tsconfig.json .env]
DEBU[0000] Checking base image node:10.13-alpine for ONBUILD triggers.
DEBU[0000] Found dependencies for dockerfile: [package.json src locales tsconfig.json .env]
DEBU[0000] Checking base image node:10.13-alpine for ONBUILD triggers.
DEBU[0000] Found dependencies for dockerfile: [tsconfig.json .env integration-test package.json src locales]
```

### Information

- Skaffold version: `skaffold-v0.22.0`
- Operating system: `Ubuntu 18.04 x64`
- Contents of skaffold.yaml:

Sorry, I'm probably not able to provide more.
```yaml
# Skaffold Profiles
profiles:
  # Debugging development build
  - name: debug
    build:
      local:  { push: false }
      tagPolicy: { envTemplate: { template: '{{ .IMAGE_NAME }}:latest' } }
      artifacts:
        - image: registry.ng.bluemix.net/redacted
          docker: { target: target1 }
        - image: registry.ng.bluemix.net/redacted
          docker: { target: target2 }
        - image: registry.ng.bluemix.net/redacted
          docker: { target: target3 }
        - image: registry.ng.bluemix.net/redacted
          docker: { target: target4 }

```

### Steps to reproduce the behavior

1. Run `skaffold dev --profile debug --cleanup=false`
