### ISSUE TITLE
`skaffold dev` does not work with remote Helm charts

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#1615]
### Expected behavior

`skaffold dev` should deploy a remote chart and remove it on quit, but it fails.
`skaffold run` works.

### Actual behavior

```
$ skaffold version
v0.22.0

$ skaffold dev
FATA[0001] watching files for deployer: listing files: listing files: issue walking releases: failure accessing path 'stable/redis': lstat stable/redis: no such file or directory 
```
### Information

- Skaffold version: v0.22.0
- Operating system: macOS 10.14
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta4
kind: Config
deploy:
  helm:
    releases:
      # redis
      - name: redis
        chartPath: stable/redis
        # set to true if you need to skip "helm dep build". Necessary for use with remote chart.
        skipBuildDependencies: true
        namespace: dev
```

### Steps to reproduce the behavior

1. `skaffold dev`
