### ISSUE TITLE
Allow specifying an explicit image tag

### ISSUE THREAD

**Issue by michaelfig** [GoogleContainerTools/skaffold#1623]
### Expected behavior

Specifying an explicit image tag will be used by Skaffold.  See the `skaffold.yaml` below.

I have a PR for this change: #1622

The rationale is that I want to make a staged `./Dockerfile` that depends on the `./docker/**/Dockerfile` to create build and install base images that are pushed to the build registry so that builder processes can also find them there as a cache:

```
ARG BUILD_REGISTRY=registry.example.com
ARG BUILD_BASE=${BUILD_REGISTRY}/citest:build-base-1.0.0
ARG INSTALL_BASE=${BUILD_REGISTRY}/citest:install-base-1.0.0
FROM ${BUILD_BASE} AS build
[...]
FROM ${INSTALL_BASE}
COPY --from=build /some/path /some/new/path
[...]
```

### Actual behavior

```
$ skaffold build
[...]
Successfully built 12d5565cc0f3
Successfully tagged 975c05a3af0fe406bb5244d510eef4b4:latest
FATA[0000] build failed: building [michaelfig/citest:build-base-1.0.0]: tagging: Error parsing reference: "michaelfig/citest:build-base-1.0.0:0dd8dfd" is not a valid repository/tag: invalid reference format
$
```

### Information

- Skaffold version: 0.22.0
- Operating system: darwin
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
  - image: michaelfig/citest:build-base-1.0.0
    context: ./docker/build-base
  - image: michaelfig/citest:install-base-1.0.0
    context: ./docker/install-base
  - image: michaelfig/citest
    docker:
      buildArgs:
        BUILD_REGISTRY: michaelfig
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
```

### Steps to reproduce the behavior

1. Run `skaffold build` or `skaffold dev` with artifacts that have explicit tags.

**Comment by michaelfig** [comment]
As @balopat explained, this works as expected with:

```yaml
build:
  tagPolicy:
    sha256: {}
```
