### ISSUE TITLE
Handle multiline docker ENV commands correctly

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#1625]
### Expected behavior
Skaffold correctly builds dockerfiles with multiline ENV commands.

### Actual behavior
Skaffold fails with
```
FATA[0000] build failed: building [test-build-with-multiline-env]: build artifact: COPY failed: stat <redacted>/tmp/docker-builder563927127/b/file: no such file or directory
```
### Information

- Skaffold version: master
- Operating system: Linux

### Steps to reproduce the behavior
1. preparation:
   ```sh
   # prepare folders environment:
   mkdir b && echo "file in dir b" > b/file
   mkdir a && echo "file in dir a" > a/file
   ```
  
2. `skaffold.yaml`:
   ```yaml
   apiVersion: skaffold/v1beta4
   kind: Config
   build:
     artifacts:
     - image: test-build-with-multiline-env
   ```
  
3. `Dockerfile`:
   ```Dockerfile
   FROM busybox
   
   ENV AAA=a \
       BBB=b
   
   COPY ./${BBB}/file /tmp/

   ```
  
4. `skaffold build` fails, whereas `docker build .` works fine
