### ISSUE TITLE
Skip pipeline with error if manifest doesnt exist

### ISSUE THREAD

**Issue by sniederm** [GoogleContainerTools/skaffold#1645]
### Expected behavior
When a deploment manifest file defined in skaffold.yml: deploy.kubectl.manifests[] doesn't exist, I would expect an error to be thrown and the pipeline to be skipped. 

### Actual behavior
The full build  is executed, then finally I get an output one could assume everything was deployed fine but its not the case:
Build complete in 33.280387096s
Starting test...
Test complete in 9.169µs
Starting deploy...
kubectl client version: 1.13
Deploy complete in 93.559821ms

### Information

- Skaffold version: v0.22.0
- Operating system: Mac OS Mojave
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
  - image: image_name
    context: path_to_sources
    jibMaven: {}
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - this_file_doesnt_exist.yaml
```

### Steps to reproduce the behavior

1. Create a ```skaffold.yaml``` like the one from above
2. Execute ```skaffold -f skaffold.yaml```
3. Skaffold doesnt inform you that the file ```this_file_doesnt_exist.yaml``` doesnt exist
