### ISSUE TITLE
tagging-with-environment-variables: Updated code not deployed 

### ISSUE THREAD

**Issue by muniyalr** [GoogleContainerTools/skaffold#1650]
### Expected behavior
In the example provided, `tagging-with-environment-variables` 
i have exported FOO as local
`export FOO=local`
`skaffold dev`

When file changes are done to main.go with 
`		fmt.Println("Hello world 3!")`
Still seeing the output with 
```
[getting-started] Hello world!
```
### Actual behavior
Still not getting the updated code output, It is building the new images but not using the updated code

```
[getting-started] Hello world!
[getting-started] Hello world!
Starting build...
Found [docker-for-desktop] context, using local docker daemon.
Building [gcr.io/k8s-skaffold/skaffold-example]...
Sending build context to Docker daemon   5.12kB
Step 1/4 : FROM golang:1.10.1-alpine3.7
 ---> 52d894fca6d4
Step 2/4 : CMD ["./app"]
 ---> Using cache
 ---> ac950e06480d
Step 3/4 : COPY main.go .
 ---> Using cache
 ---> 23cc1ab77f9e
Step 4/4 : RUN go build -o app main.go
 ---> Using cache
 ---> 2e710142c870
Successfully built 2e710142c870
Successfully tagged f6cfc3a68963dfaa37c70fa4c47959b2:latest
Build complete in 2.280502642s
Starting test...
Test complete in 9.191µs
Starting deploy...
kubectl client version: 1.10
kubectl version 1.12.0 or greater is recommended for use with skaffold
Deploy complete in 834.334324ms
Watching for changes every 1s...
**[getting-started] Hello world!**
[getting-started] Hello world!
```
### Information

- Skaffold version: v0.22.0
- Operating system: macOS Sierra 10.12.6
- Docker: Docker Desktop Community Version 2.0.1.0 (30090)
- Contents of skaffold.yaml:

```
apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.FOO}}"
deploy:
  kubectl:
    manifests:
      - k8s-*
```
```docker images | grep skaffold
gcr.io/k8s-skaffold/skaffold-example                                     local               2e710142c870
```
### Steps to reproduce the behavior

1. clone the repo
2. cd examples/tagging-with-environment-variables
3. export FOO=local
4. skaffold dev
5. Change main.go with `Hello world 3!`

Please advice if i am missing something with this
