### ISSUE TITLE
Microk8s connection issue

### ISSUE THREAD

**Issue by soullivaneuh** [GoogleContainerTools/skaffold#1651]
I'm trying Skaffold but I'm stuck at the beginning, it does not seem to detect my microk8s instance

Maybe some configuration is required but I can't found anything on the documentation about this.

### Expected behavior

```bash
skaffold init
# Should create my configs files
```

### Actual behavior

```bash
$ skaffold init
FATA[0000] one or more valid kubernetes manifests is required to run skaffold 
```

### Information

- Skaffold version: v0.22.0
- Operating system: `Linux sweetnexy 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
$ kubectl config current-context
microk8s
```

### Steps to reproduce the behavior

1. Install microk8s with snap
2. Install Skaffold
3. Run `skaffold init`

**Comment by Soullivaneuh** [comment]
Right, it does not seem to be a microk8s connectivity issue as it works with a manual file creation.

Then, I don't understand the error message. :smile:

**Comment by balopat** [comment]
Hey @Soullivaneuh, thanks for opening this issue. 
The `skaffold init` command doesn't generate yet kubernetes manifests - although it probably will in the future. The error you're getting shows that there are no K8s manifest files, currently you'll have to manually create them: see for example the k8s-pod.yaml in the [getting-started](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/getting-started)

**Comment by Soullivaneuh** [comment]
Hi @balopat, thanks for the answer! :-)

I'm not sure what is the goal of the `k8s-pod.yaml` file here.

Before testing Skaffold, I just setup a helm chart project and it worked fine without it.

BTW, I did manually setup the skaffold configuration file:

```yaml
apiVersion: skaffold/v1beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: localhost:32000/sweetforeign_web
deploy:
  helm:
    releases:
      - name: sweetforeign
        chartPath: .
```

And it works fine, except the `ADD` directive of my `Dockerfile` being not updated, but I think it's an another configuration issue...
