### ISSUE TITLE
Configure other helm repository than the official helm hub

### ISSUE THREAD

**Issue by soullivaneuh** [GoogleContainerTools/skaffold#1665]
## The need

There is currently no way to configure any repository under the helm section.

Plus, I tried this config:

```yaml
deploy:
  helm:
    releases:
      - name: gitlab
        chartPath: gitlab/gitlab
        skipBuildDependencies: true
```

And:

```
$ helm repo add gitlab https://charts.gitlab.io/
"gitlab" has been added to your repositories
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "gitlab" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
```

But skaffold does not find the gitlab chart.

## The proposal

I propose to add the possibility to setup helm repositories on the Skaffold configurations.

I see two possible ways:

1. Adding the `repository` key for each release as [Helm does](https://github.com/helm/helm/blob/master/docs/helm/helm_dependency.md#synopsis):

```yaml
deploy:
  helm:
    releases:
      - name: sweetforeign
        chartPath: .
      - name: minio
        # No repository set here so fallback to default hub.
        chartPath: stable/minio
        skipBuildDependencies: true
      - name: gitlab
        chartPath: gitlab/gitlab
        repository: https://charts.gitlab.io/
        skipBuildDependencies: true
```

2. Setup repositories first under the `helm` section:

```yaml
deploy:
  helm:
    repositories:
      gitlab: https://charts.gitlab.io/
      fabric8: https://fabric8.io/helm
    releases:
      - name: sweetforeign
        chartPath: .
      - name: minio
        chartPath: stable/minio
        skipBuildDependencies: true
      - name: gitlab
        chartPath: gitlab/gitlab
        skipBuildDependencies: true
```

This second approach has one advantage: You have less repeated configuration. On the first one, you will have to repeat the repository configuration on each chart you use from this one.

## Personal use case

I would like to setup my whole personal remote apps and related project onto a single git repositories managed  by skaffold. Using the helm deploy feature avoid helm manual installation and update.

Don't hesitate to tell me if the way I'm doing is not the best, I'm always hearing! :+1:
