### ISSUE TITLE
helm deploy not working

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#1670]
### Expected behavior
I expected skaffold to set the helm values `image.repository` and `image.tag`

### Actual behavior
```
  Normal   BackOff         
6s (x6 over 13s)  kubelet, gke-clust..  Back-off pulling image "eu.gcr.io/my-proj/demo-one:86918feb7004978da86b1c5865a4c89f533e9d14ebb5624bc954dec74f72653a"
```

### Information

- Skaffold version: v0.23.0
- Operating system: Windows 10 using GitBASH
- Contents of skaffold.yaml:

*I've tried a few taggers nothing seems to work*
```yaml
apiVersion: skaffold/v1beta5
kind: Config

build:
  tagPolicy:
    sha256: {}

  artifacts:
    - image: eu.gcr.io/my-proj/demo-one
      jibMaven: {}

deploy:
  helm:
    releases:
      - name: demo-one
        chartPath: helm/demo-one
        values:
          image.repository: eu.gcr.io/my-proj/demo-one
#          image.tag: me
```

### Steps to reproduce the behavior

1. Created helm chart using the Helm convention for Image and tag name
```
# image:
#   repository: eu.gcr.io/my-proj/demo-one
#   tag: latest
#   pullPolicy: IfNotPresent
```
2.  skaffold run

**Comment by dkirrane** [comment]
Found my issue.

I needed to use `setValueTemplates` instead of `values`. This worked

```yaml
apiVersion: skaffold/v1beta5
kind: Config

build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.USERNAME}}"

  artifacts:
    - image: eu.gcr.io/my-proj/demo-one
      jibMaven: {}
  local:
    push: true

deploy:
  helm:
    releases:
      - name: demo-one
        chartPath: helm/demo
        setValueTemplates:
          image.repository: "{{.IMAGE_NAME}}"
          image.tag: "{{.USERNAME}}"
```
