### ISSUE TITLE
Skaffold ignores errors in Dockerfiles

### ISSUE THREAD

**Issue by Ken-LiuL** [GoogleContainerTools/skaffold#1712]
### Expected behavior
Give an error information when there are errors in the Dockerfile:
![image](https://user-images.githubusercontent.com/7971987/53615200-d1021600-3c17-11e9-9f46-feebb19081f1.png)

### Actual behavior
No explicit information showed
 
![image](https://user-images.githubusercontent.com/7971987/53615211-deb79b80-3c17-11e9-8947-f46048e8b143.png)

- Skaffold version: v0.23.0
-  Operating system: macos
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: my-image-name
```

### Steps to reproduce the behavior

1. An incorrect Dockerfile
