### ISSUE TITLE
logs only show when pod is just created and as its being terminated

### ISSUE THREAD

**Issue by scottwilson312** [GoogleContainerTools/skaffold#1720]
### Expected behavior
Expect to see all the output of kubectl logs 
### Actual behavior
I only see the output for the first seconds of the pod. Then the output of skaffold dev goes silent until I make a code change, at that point in time, logs from the old pod will briefly start showing up before its killed.

### Information

- Skaffold version: 24
- Operating system: Ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - imageName: mw
deploy:
  kubectl:
    manifests:
      - development_release/deployment.yml

```

### Steps to reproduce the behavior

1. ... skaffold dev
2. ... wait for logs

I run skaffold dev  -v DEBUG and it says its running the command `kubectl logs --since=3s -f mw-847f957c7d-98zzx -c multiple-workers --namespace default`.

Note that when I run the above command in another terminal, all the logs appear as you'd expect.

Any help in debugging this would be greatly appreciated. Let me know if I can provide helpful info. Thanks
