### ISSUE TITLE
Build and push to an insecure registry completes unsuccessfully

### ISSUE THREAD

**Issue by NicklasWallgren** [GoogleContainerTools/skaffold#1732]
### Expected behavior
A Skaffold driven build should complete successfully even if the image is pushed to an insecure registry.

### Actual behavior
Skaffold errors on building/pushing  the new image.

```
FATA[0005] build failed: building [<registry>:32000/<app>]: build artifact: getting image: Get https://<registry>:32000/v2/: http: server gave HTTP response to HTTPS client 
```

Works fine using jib directly.
```
gradle jib -Djib.to.image=<repository>:32000/<app>:latest
```

### Information
- Skaffold version: 0.24

- ~/.docker/deamon.json
```
{
"insecure-registries" : [
    "<registry>:32000"
  ],
}
```

- Skaffold configuration
```yaml
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
    - image: <registry>:32000/<app>
      jibGradle: {}
      context: app
```

- Authentication
```
docker login <registry>:32000
Login Succeeded
```

- Jib configuration
```
jib {
   allowInsecureRegistries = true
}
```
