### ISSUE TITLE
--tail In Deploy Mode Mixes Outputs

### ISSUE THREAD

**Issue by cliffburdick** [GoogleContainerTools/skaffold#1753]
### Expected behavior
Independent outputs from two processes

### Actual behavior
If I run two skaffold commands in separate windows with the deploy mode and --image, the output of one spills onto the other screen, and both are seen. This behavior does not occur with run --tail.

### Information

- Skaffold version: v0.24.0
- Operating system: Ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta1
build:
  artifacts:
  - context: ./
    docker:
      buildArgs:
        BASE_VER: 2018.12.11.0
      dockerfile: deploy/docker/Dockerfile
    image: mydomain.com:8151/prj/uncommitted
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.SALT}}'
deploy:
  kubectl:
    manifests:
    - prj_runman-e23db7.yaml*
kind: Config
```

### Steps to reproduce the behavior

1. Run skaffold deploy --tail in two windows
2. Observe container output mixing in both windows.
