### ISSUE TITLE
Pass --network=host during docker build

### ISSUE THREAD

**Issue by romil-punetha** [GoogleContainerTools/skaffold#1771]
When using skaffold build during jenkins, the docker build is failing because the containers aren't able to connect to the internet. However, I tried ssh-ing into the machines and ran docker build --network=host and it worked. Is there any provisioning to provide the --network flag to skaffold build ?

### Expected behavior
skaffold build should succeed.

### Actual behavior
The build is failing as no command with internet as a requirement is passing.

### Information

- Skaffold version: v0.24.0
- Operating system: aws ami
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta3
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/romil-punetha/doorman:{{.VERSION}}"
  artifacts:
  - image: doorman
    context: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/romil-punetha/doorman:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: doorman
        chartPath: charts/doorman
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/romil-punetha/doorman"
          image.tag: "{{.DIGEST_HEX}}"
```

### Steps to reproduce the behavior

1. ... setup a jenkinsx cluster on EKS with nodes in private networking mode(theres a flag when using  eksctl ) 
2. ... run a jenkins job with a command like apt-get update in the dockerfile

**Comment by corneliusweig** [comment]
This sounds more like an EKS configuration issue, than a problem in Skaffold. Besides, could you provide some debug log output?

**Comment by romil-punetha** [comment]
The output log is that the yarn install on my jenkins job fails to fetch files from the repository due to connectivity issue. I tried `apt-get update` inside the docker container and that failed for the same reason. I used `docker build --network` and everything worked fine. 
I'm using jenkins-x and the build happens in containers. However, the build containers mount the docker.sock from the instance. The build containers have internet, but the containers being built do not (atleast not without the `--network` flag).

**Comment by corneliusweig** [comment]
Have you tried adjusting the mtu inside your containers? Using a too large mtu can lead to black-hole connections, if ICMP mtu discovery is blocked.

**Comment by moshid** [comment]
I'm having the same issue, when skaffold build during jenkins the container have no internet access and fail. I ended up using `docker build --network=host` instead of skaffold but I was wondering if anyone found a solution for this?

**Comment by romil-punetha** [comment]
@corneliusweig How to adjust mtu?

**Comment by corneliusweig** [comment]
@romil-punetha e.g. https://mlohr.com/docker-mtu/

**Comment by remzisenel** [comment]
Having the same issue. 
skaffold.yaml used in build step: 
https://gist.github.com/remzisenel/be6bbd52b43941ffba185ead8dc4adde
jenkinsfile used in buikd:
https://gist.github.com/remzisenel/3de44d740745d10d9675cf94b883f44d

When I use skaffold build -f skaffold.yaml, there is only the loopback interface within the container. However, when I use docker build --network=host . I have the regular interfaces and can access network as expected.

**Comment by corneliusweig** [comment]
@remzisenel Can you check what interfaces are set up when using `docker build --network=bridge`? This should be the default for docker, but what you are observing looks more like `--network=none`.

Can you also check if the network setting is configured in `/etc/docker/daemon.json`, or via arguments for the docker daemon (`pgrep -a dockerd`).

**Comment by moshid** [comment]
It is an EKS configuration issue they disabled the bridge network. Take a look at: https://github.com/awslabs/amazon-eks-ami/issues/183

**Comment by corneliusweig** [comment]
@moshid Thanks for demystifying that :man_facepalming:

So right now there is no way to pass this flag from skaffold to docker. You can do a very dirty hack to inject the flag: put this file as `docker` somewhere on your path:
```bash
#!/bin/bash
if [[ "$1" = 'build' ]]; then
  exec docker build --network=host "${@:2}"
else
  exec docker "$@"
fi
```
Then use the CLI docker in skaffold by
```yaml
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/romil-punetha/doorman:{{.VERSION}}"
  artifacts:
  - image: doorman
    context: .
    docker: {}
  local:
    useDockerCLI: true   # <<<<<<<<<<<<<<<
```
