### ISSUE TITLE
Remove kustomize requirement if kubectl version > 1.14

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1781]
[kustomize got merged into kubectl](https://github.com/kubernetes/enhancements/issues/633) we should remove the dependency if we detect kubectl version that is greater or equal to 1.14.

**Comment by dkirrane** [comment]
Fyi: at the moment this config throws `no matches for kind \"Kustomization\"`

```
apiVersion: skaffold/v1beta14
kind: Config

deploy:
  kubectl:
    manifests:
      - ./kustomize/kustomization.yaml
    flags:
      apply:
        - -k
```

1. `git clone https://github.com/dkirrane/strimzi-skaffold-kustomise`  (See README)
2. `skaffold depoy`
3. `no matches for kind \"Kustomization\" in version \"kustomize.config.k8s.io/v1beta1\"\n, err: exit status 1: exit status`

**Comment by raul1991** [comment]
For me, 

This configuration leads to an error

```
deploy:
  kubectl:
    flags:
      global:
        - -k
    manifests:
     - kustomizer/dev/kustomization.yaml

```

**Error**

`kubectl --context <my-context> create -k --dry-run -oyaml -f <some-path>/kustomizer/dev/kustomization.yaml`

Since I added the -k it seems only logical that it appears after the kubectl create but why does it appends -f when -k is already given ?
