### ISSUE TITLE
helm timeout flag not working on install

### ISSUE THREAD

**Issue by hakimlilo** [GoogleContainerTools/skaffold#1806]
### Expected behavior
success (should install within the timeout)
### Actual behavior
```
DEBU[0006] Running command: [helm --kube-context docker-for-desktop install --name api --timeout 1800 charts/api --namespace default -f skaffold-overrides.yaml --wait --set api_version=671fbbeda53404e740b9ebc7e3708cd46431683276c154b074764c0b70009efd] 
Error: unknown flag: --timeout 1800
```

### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```
```
apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
    - image: name
      context: folder
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
  local:
    push: false
    useDockerCLI: false
    useBuildkit: false
deploy:
  helm:
    releases:
    - name: api
      chartPath: charts/api
      namespace: default
      recreatePods: false
      wait: true
      overrides:
        global:
          baseClusterName: localhost
        deployment:
          image: api
        api_reg: reg
      setValueTemplates:
        api_version: "{{ .DIGEST }}"
    flags:
      upgrade:
        ["--timeout 1800"]
      install:
        ["--timeout 1800"]
```
### Steps to reproduce the behavior

1. composed the skaffold file

2. ran : ```skaffold dev -v debug```

**Comment by hakimlilo** [comment]
I added the '=' operator in [--timeout=1800] in both arguments and it worked

**Comment by priyawadhwa** [comment]
@hakimlilo glad you were able to get this to work! I'm going to go ahead and close this issue, please comment or open another if you run into any more problems.

**Comment by AndiDog** [comment]
The value must be a separate command line argument, e.g.

```
deploy:
  helm:
    flags:
      upgrade: ["--timeout", "30"]
      install: ["--timeout", "30"]
```

(or use single argument `--timeout=30`)

**Comment by Don-CA** [comment]
For those that find this comment via google, you need to use a specific a unit so try `m` for minutes

```
deploy:
  helm:
    flags:
      upgrade: ["--timeout", "30m"]
      install: ["--timeout", "30m"]
      
```

or `--timeout=30m`
