### ISSUE TITLE
Sync does not work in containers without the tar command

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#1814]
### Expected behavior
Changed files are synced to the container. The example below does not make much sense, but it does also affect distroless containers.

### Actual behavior
Sync fails with
```
DEBU[0007] Running command: [kubectl exec getting-started --namespace default -c getting-started -i -- tar xmf - -C / --no-same-owner] 
WARN[0007] Skipping deploy due to sync error: copying files: exit status 126
```

### Information

- Skaffold version: >0.24

### Steps to reproduce the behavior
Based on the examples/getting-started example
1. Modify Dockerfile to
```
FROM golang:1.10.1-alpine3.7 as builder
COPY main.go .
RUN go build -o /app main.go

FROM scratch
ENTRYPOINT ["./app"]
COPY . /unused
COPY --from=builder /app .
```
2. Modify skaffold.yaml
```
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
    sync:
    - '*.go': /
deploy:
  kubectl:
    manifests:
      - k8s-*
```
3. `skaffold dev -v debug`
4. Change `main.go` and wait for sync.
