### ISSUE TITLE
Seemingly we are not validating colliding "oneOf" fields under artifact

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1836]
Based on #1649  - there is an example that does not fail with the following: 

```
apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
  - image: acmeprivate.azurecr.io/blah/whatever/application
    jibMaven: {}
    context: api-app # Multi-module Maven project, api-app is the app module
    docker:
      dockerfile: Dockerfile
  local: {}
```

where jibMaven and docker should never be able to coexist on the same artifact.
