### ISSUE TITLE
Nodejs Skaffold local development to prod process

### ISSUE THREAD

**Issue by pebcakerror** [GoogleContainerTools/skaffold#1852]
https://github.com/GoogleContainerTools/skaffold/blob/e8ba04530b9849bacc40539c00688f4a6da6bacd/examples/nodejs/backend/package.json#L7

https://github.com/GoogleContainerTools/skaffold/blob/e8ba04530b9849bacc40539c00688f4a6da6bacd/examples/nodejs/backend/Dockerfile#L5

The Dockerfile appears to run the app with nodemon to achieve the live reloading . Wouldn't this same container be used in prod? Wouldn't it be bad to be running nodemon in prod?

What is actual best practice to set up a kubernetes local development environment with live file sync and use the same resources for production?

**Comment by casret** [comment]
We use the kustomize deployer, and override the CMD to use nodemon in our development overlay.

**Comment by tejal29** [comment]
Thanks @pebcakerror for creating this issue.
We should definitely add examples for nodejs which mentions @casret's suggestions and document other alternatives.

**Comment by tejal29** [comment]
@balopat this is good issue to link under the EPIC "Document end to end solutions"

**Comment by cymarechal** [comment]
> We use the kustomize deployer, and override the CMD to use nodemon in our development overlay.

It interests me as well. @casret, how do you manage to do it? Here is how I would like it to look like:
```
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: cymarechal/helloworld
    context: ./helloworld/
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
deploy:
  kustomize:
    path: ./**/k8s/base
profiles:
- name: dev
  activation:
    - command: dev
  deploy:
    kustomize:
      path: ./**/k8s/overlays/development
```

Sadly, kustomize's path does not accept "**"...
