### ISSUE TITLE
sha256 tagpolicy uses `latest` as tag

### ISSUE THREAD

**Issue by tdickman** [GoogleContainerTools/skaffold#1884]
### Expected behavior
Image is tagged with sha256 hash causing the deployment to create new pods when changes are made.

### Actual behavior
Image is tagged with `latest`, so new pods are not created when changes occur.

### Information

- Skaffold version: v0.25.0
- Operating system: ubuntu
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: localhost:32000/us.gcr.io/test-registry/name
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: name
        chartPath: infrastructure/kube
        namespace: name
        values:
          image: localhost:32000/us.gcr.io/test-registry/name
        imageStrategy:
          helm: {}
        valuesFiles:
          - infrastructure/kube/values.yaml
          - infrastructure/kube/values-lcl.yaml
```

### Steps to reproduce the behavior

1. Create a project that uses helm for k8s templates
2. Run `skaffold run`
