### ISSUE TITLE
Get generated image tag value from build command to use in deploy command

### ISSUE THREAD

**Issue by thangbn** [GoogleContainerTools/skaffold#1889]
I'm using helm with skaffold for development. My skaffold config:
```yaml
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: "gcr.io/equity-ai/ai-api-skaffold"
    context: .
  tagPolicy:
    dateTime:
      format: 2006-01-02_15-04-05.999_MST
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: ci/helm-chart
      wait: true
      valuesFiles:
      - values-dev.yaml
```
my **values-dev.yaml**
```yaml
replicaCount: 1
image: "gcr.io/equity-ai/ai-api-skaffold"
imageTag: 0d0143b014e083c1c91b3f0c9504254a121ab7a5
```
How to I inject generated tag value based on timestamp policy into **values-dev.yaml** when i do **skaffold deploy**:

**Comment by corneliusweig** [comment]
Have a look at the [helm-deployment](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/helm-deployment) example.

> This part tells skaffold to set the image parameter of the values file to the built skaffold-helm image and tag.
>
>      values:
>        image: skaffold-helm

In other words, you are missing the `image` in your helm `releases` spec:

```yaml
releases:
    - name: skaffold-helm
      chartPath: ci/helm-chart
      wait: true
      valuesFiles:
      - values-dev.yaml
      values:
         image: "gcr.io/equity-ai/ai-api-skaffold"
```
