### ISSUE TITLE
kaniko local build

### ISSUE THREAD

**Issue by tuapuikia** [GoogleContainerTools/skaffold#1928]
### Expected behavior
Kaniko build the image and push to docker hub
### Actual behavior
Skaffold exit with following error.
FATA[0017] build failed: building [xxx/skaffold-example]: kaniko build for [xxx/skaffold-example]: modifying kaniko pod: copying and extracting buildcontext to empty dir: exit status 2
### Information

- Skaffold version: v0.26.0
- Operating system: Ubuntu 18.04
- Kubectl version : 1.14.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: xxx/skaffold-example
      kaniko:
        buildContext:
          localDir: {}
  cluster:
    namespace: default
    dockerConfig:
         secretName: docker-cfg
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. ...
2. ...
