### ISSUE TITLE
Document end-to-end GitOps solutions

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1937]
Document solutions that walk the user through best practices from dev, testing and production deployment using GitOps using Skaffold.

**Comment by ItsLeeOwen** [comment]
In particular I'm curious how one uses skaffold to commit the built k8s manifests to a target repo or branch when using `skaffold deploy`.  Is there a way to get the manifests built output similarly to `kustomize build` or otherwise?

**Comment by nkubala** [comment]
>  Is there a way to get the manifest build output from skaffold deploy similarly to kustomize build?

currently the only way to see them is by running with `-v DEBUG`, but we could also accomplish this with a `--dry-run` flag. see https://github.com/GoogleContainerTools/skaffold/issues/1739

> For example if your development image is tagged with the gitCommit, when promoted to staging how to add a tag such as staging-${gitCommit}

right now in skaffold we don't support multiple tagging strategies, this has been discussed in https://github.com/GoogleContainerTools/skaffold/issues/1269. maybe it's worth revisiting different solutions for this now.

not very pretty, but you can accomplish something similar with this right now using profiles (and a little unix foo):

```yaml
build:
  tagPolicy:
    sha256: {}
...
profiles:
- name: staging
   build:
     tagPolicy:
       envTemplate:
         template: staging-{{.GIT_COMMIT}}
```

`$ skaffold dev -p staging $GIT_COMMIT=$(git rev-parse --short HEAD)`
