### ISSUE TITLE
If not in relevant namespace, skaffold dev does not port-forward or tail logs in macOS

### ISSUE THREAD

**Issue by arshbot** [GoogleContainerTools/skaffold#1948]
### Expected behavior

When `deployment.yaml` is configured properly and has containerPorts set, running `skaffold dev` should tail the logs and show the relevant port is listening.

```
$ skaffold dev
Generating tags...
...
...
...
Deploy complete in 3.931363576s
Watching for changes every 1s...
Forwarding container myAppName to local port 4503.
...
...
# logs
```

### Actual behavior

On macOS, it seems it is absolutely required that the current namespace must be the same as the pods being run, or else the kubectl commands to tail logs and port-forward will silently fail while everything else functions normally. 

### Information

- Skaffold version: v0.26.0
- kubectl client version: GitVersion:"v1.14.0"
- Operating system: macOS Mojave 10.14.1 (18B75)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: localhost:32000/myAppName
deploy:
  helm:
    releases:
      - name: myAppName
        chartPath: infrastructure/kube
        namespace: dubbin
        setValueTemplates:
          image.repository: "{{.IMAGE_NAME}}"
          image.tag: "{{.DIGEST}}"
        imageStrategy:
          helm: {}
        valuesFiles:
          - infrastructure/kube/values.yaml
          - infrastructure/kube/values-lcl.yaml
```

### Steps to reproduce the behavior

1. Be on macOS
2. Set context to Docker for Mac
3. Set context's namespace to default or something other than namespace skaffold will run
4. Run `skaffold dev`
5. Watch as logs are not tailed, and ports are not forwarded.

Note: it seems like this issue was previously reported [here](https://github.com/GoogleContainerTools/skaffold/issues/1177) but was not reproducible
