### ISSUE TITLE
Feature Request - Support trigger file

### ISSUE THREAD

**Issue by saturnism** [GoogleContainerTools/skaffold#1954]
Currently Skaffold triggers rebuild/redeploy on every file change and may be too frequent.  Add a mode to rather watching all files, watch only one specified trigger file to kick off rebuid/redeploy.

**Comment by nkubala** [comment]
+1 to this, we're discussing different enhancements to the way skaffold triggers builds.

it might make sense to configure this on a per-artifact basis as well, since different artifacts might represent different "areas of the code" which might have separate triggers. this could live in the skaffold.yaml and look something like 

```yaml
build:
  artifacts:
  - image: my_image
    triggerFiles:
    - code.go
    - app.go
  - image: my_java_image
    triggerFiles:
    - app.java
```

we're also considering adding a way for users to switch to manual trigger mode, which would be exposed through a gRPC/HTTP endpoint. this could also be exposed through a UI element in Cloud Code.
