### ISSUE TITLE
Profile can't be auto-activated for `skaffold debug` command

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1955]
Profiles can be auto-activated on the skaffold command that runs.

For eg, this configuration changes the list of k8s manifests when using `skaffold run`
```
apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
  - image: hello

profiles:
- name: profile1
  activation:
    - command: run
  deploy:
    kubectl:
      manifests:
      - k8s/dep.yaml
```

If a profile is set to auto-activate with the `debug` command, this currently has no effect.
