### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jimanvlad** [GoogleContainerTools/skaffold#1961]
### Expected behavior
```
build:
  insecureRegistries:
    - artifactory.xx.xx.com
```
The error in the title shouldn't occur if repo is added to the insecure registries.

### Actual behavior

> error pushing image: failed to push to destination artifactory.xx.xx.com/data/<image>:<tag>: Get https://artifactory.xx.xx.com/v2/: x509: certificate signed by unknown authority

### Information

- Skaffold version: 0.27
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta8
kind: Config
build:
  insecureRegistries:
    - artifactory.xx.xx.com
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: artifactory.xx.xx.com/data/my-image
      context: src
      kaniko:
        buildContext:
          localDir: {}
  cluster:
    dockerConfig:
      path: /Users/xx/.docker/config_old.json
      secretName: docker-secret
    pullSecretName: kaniko-secret
```
### Steps to reproduce the behavior

1. Run skaffold with the attached yaml

kaniko.flags is also deprecated so there is no way to use kaniko's [--skip-tls-verify-registry](https://github.com/GoogleContainerTools/kaniko#additional-flags)

**Comment by balopat** [comment]
Thanks for filing! This should be relatively straightforward to create a field for and passing it to kaniko. PRs are welcome!

**Comment by jimanvlad** [comment]
Not 100% sure this is a feature request, as https://github.com/GoogleContainerTools/skaffold/pull/1870 should have already allowed insecure registries to be used.

**Comment by balopat** [comment]
Ahhh, fair enough - I misunderstood, you're right, this is more of a bug / gap for kaniko. We should pass the `--insecure-registry` list to kaniko. Would you like to submit a PR for this fix?

**Comment by jimanvlad** [comment]
My go is pretty rusty so won't be able to send a PR.

**Comment by tjk** [comment]
I took a quick stab at this (https://github.com/GoogleContainerTools/skaffold/pull/1977) but have no idea if this even solves the issue -- running it to see if it works and adding a test would be wonderful! :)

**Comment by tjk** [comment]
@jimanvlad would you be able to try my patch? 

(I'm done changing it just not sure how to set stuff up to verify it fixes the issue.)

**Comment by jimanvlad** [comment]
Sure, where can I get a macOS binary from?

**Comment by tjk** [comment]
I just built this but might be issues sine I just used `go build` (gzipped):

[skaffold.gz](https://github.com/GoogleContainerTools/skaffold/files/3109366/skaffold.gz)

**Comment by jimanvlad** [comment]
Hi,

I used your provided binary and added:
```
  insecureRegistries:
    - artifactory.xx.xx.com
    - artifactory.xx.xx.com:5000
```
to the `build` section, but it still failed:
`error pushing image: failed to push to destination artifactory.xx.xx.com/data/project:e2e157f-dirty: Get https://artifactory.xx.xx.com/v2/: x509: certificate signed by unknown authority
`

**Comment by tjk** [comment]
I need to figure out a way to test this myself but in the meantime, if you could try something like `watch -n1 'ps aux | grep kaniko'` and copy paste the kaniko command it runs maybe? I imagine for some reason or another the arguments are not being passed to kaniko command... but I'm really out of my element -- I'll try to set up a repro myself if I find time.

**Comment by jimanvlad** [comment]
Hi,

This is what gets sent:

```
(base) UK-AL-6631:~ jimanv$ ps aux | grep kaniko
jimanv           96571  10.7  0.1  4419860  21240   ??  S     2:11pm   0:00.07 kubectl exec -i kaniko-8td2r -c kaniko-init-container -n default -- tar -xzf - -C /kaniko/buildcontext
(base) UK-AL-6631:~ jimanv$ ps aux | grep kaniko
jimanv           96584   0.0  0.1  4419020  10604   ??  R     2:12pm   0:00.01 kubectl exec kaniko-8td2r -c kaniko-init-container -n default -- touch /tmp/complete
```

**Comment by tjk** [comment]
I will try to set up kaniko this weekend since I've wanted to play with it and will try to get back to you by then to avoid wasting your time. :)

**Comment by jimanvlad** [comment]
Your help is greatly appreciated and I'm happy to test any further changes :)

**Comment by priyawadhwa** [comment]
Hey @jimanvlad we are now passing in insecure registries to kaniko as of #2266. Could you try with the latest release and see if it fixes your issue?

**Comment by jimanvlad** [comment]
Hi, happy to check. Is this in the released binaries or do I have to build from source?

**Comment by priyawadhwa** [comment]
The latest release should incorporate this change!

**Comment by jimanvlad** [comment]
Thanks, I am getting a different error not but not sure if it's related or not.

`error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "artifactory.xx.xx.com:5000/data/peoject:bae7185-dirty": unrecognized HTTP status: 400 Bad Request`

This is with the following config:
```
build:
  artifacts:
    - image: artifactory.xx.xx.com:5000/data/project
      context: src
      kaniko:
        buildContext:
          localDir: {}
  cluster:
    namespace: default
    dockerConfig:
      path: ~/.docker/config.json
```
And docker login works fine:
```
>>docker login https://artifactory.xx.xx.com:5000
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /Users/user/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

**Comment by balopat** [comment]
I think this fell through the cracks a little bit - #1977 got closed due to inactivity, and I can't see how https://github.com/GoogleContainerTools/skaffold/pull/2266 pipes insecure registries definition to kaniko - maybe I'm missing something, @priyawadhwa?

Also just a sanity check @jimanvlad - do you have the insecure registries defined in your global config?

**Comment by priyawadhwa** [comment]
Looks like we need to pass in the following flags to kaniko [here](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/build/cluster/kaniko.go#L88) if we are pushing to one of the insecure registries listed [here](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/build/cluster/types.go#L43):
- `--insecure`
- `--insecure-pull`
- `--skip-tls-verify`
- `--skip-tls-verify-pull`

Alternatively, we could add these flags to [KanikoArtifact](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/latest/config.go#L675) and have the user set them manually in the skaffold config. Personally I prefer the first option. 

@jimanvlad, would you be interested in opening a PR for this?

**Comment by balopat** [comment]
I started looking into this stay tuned on #2809

**Comment by tejal29** [comment]
Thank you @jimanvlad. we are actively working on this issue and share an update soon.

**Comment by jimanvlad** [comment]
Thanks for your help, I stand ready to test further updates.

**Comment by balopat** [comment]
Thanks @jimanvlad - @priyawadhwa took over - she is our local kaniko expert.

**Comment by priyawadhwa** [comment]
Hey @jimanvlad I just merged #2976 -- could you try installing the [bleeding edge binary](https://skaffold.dev/docs/getting-started/#installing-skaffold) and adding the new `skipTLS` field to your skaffold config:

```yaml
  artifacts:
    - image: artifactory.xx.xx.com/data/my-image
      context: src
      kaniko:
        buildContext:
          localDir: {}
        skipTLS: true
```

please let us know if this does or doesn't resolve your issue!
