### ISSUE TITLE
skaffold not working with kind and docker for mac

### ISSUE THREAD

**Issue by sbhardwaj-mt** [GoogleContainerTools/skaffold#1980]
### Expected behavior.
skaffold deployment with helm should be able to pull the images that are build during development phase.

### Actual behavior
skaffold deployment with helm is not able to pull the images that are built during development mode at the run time in pod

### Information

- Skaffold version: version... 0.27.0
- Operating system: ... Mac OSx 10.14.2
- Contents of skaffold.yaml: 

```yaml
apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
    - image: munimji
      context: ./../munimG
      sync:
        'src/*.go': .
        'src/**/*.go': .

  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"

deploy:
  helm:
    releases:
      - name: initservice
        version: 0.1.0
        chartPath: ./../baton-helm-charts/initservice

      - name: munimji
        version: 0.1.0
        chartPath: ./../baton-helm-charts/munimji
        recreatePods: true
        setValues:
          env.GIN:
```

### Steps to reproduce the behavior
1. install kind with docker. 
2. try to build any image and deploy using helm.
