### ISSUE TITLE
Skaffold not able to parse image name from git commit when commit is numeric.

### ISSUE THREAD

**Issue by thejasn** [GoogleContainerTools/skaffold#1992]
### Expected behavior

Should parse git commit (8202758) as string and not as a numeric constant.

### Actual behavior

Failed to apply default image tag "docker08.helpchat.in:5000/nuclei-billpayment-forward:8.202758e+06": couldn't parse image reference "docker08.helpchat.in:5000/nuclei-billpayment-forward:8.202758e+06": invalid reference format

### Information

- Skaffold version: version: v0.23.0
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
  - image: <image-name>
    context: <some-context>
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
- name: dev
  build:
    tagPolicy:
      gitCommit: {}
  deploy:
    helm:
      releases:
      - name: <image-name>
        chartPath: <chart-path>
        imageStrategy:
          helm: {}
        version: "dev"
        valuesFiles:
          - <some-files>
          - <some-files>
        values:
          image: <image-name>

```

### Steps to reproduce the behavior

1. Make sure your git commit hash has only numbers.
2. skaffold deploy
