### ISSUE TITLE
Unable to connect to the server: EOF

### ISSUE THREAD

**Issue by demisx** [GoogleContainerTools/skaffold#1996]
Hi, 

I am new to this tool and I really like it. One issue I keep running into that prevents me from using it is that after I start `skaffold dev` and let it run for a few minutes, I start getting `Unable to connect to the server: EOF` when trying to run any `kubectl` command. I do not see anything awkward in the skaffold streaming logs, but my app and k8s stop responding. When I ^C skaffold, I am usually able to run `kubectl` commands. But sometimes, I have to reset the local k8s cluster completely and redeploy all resources from scratch. 

Here is the difference in the `cluster-info` output for example:

```sh
# When skaffold is not running
$ kubectl cluster-info 
Kubernetes master is running at https://localhost:6443
KubeDNS is running at https://localhost:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

# When skaffold is running
$ kubectl cluster-info 
Kubernetes master is running at https://localhost:6443
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: EOF
```

Interesting that if I deploy manifests manually via `kubectl --context docker-for-desktop apply -oyaml -f [path/to/manifest] ...` then I don't recall seeing this issue.  Please let me know if you need any additional info. I will update the issue if I notice any additional patterns.

### Information
- Skaffold version: v0.27.0
- Operating system: 10.14.4
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta8
kind: Config
deploy:
  kubectl:
    manifests:
    - app/db/k8s/000-role.yaml
    - app/db/k8s/010-role-binding.yaml
    - app/db/k8s/020-stolon-sentinel.yaml
    - app/db/k8s/030-secret.yaml
    - app/db/k8s/040-stolon-keeper.yaml
    - app/db/k8s/050-stolon-proxy.yaml
    - app/api/k8s/api.yaml
profiles:
- name: dev
  activation:
    - kubeContext: docker-for-desktop
      command: dev
  build:
    artifacts:
    - image: dl-org-db
      docker:
        dockerfile: app/db/Dockerfile
        buildArgs:
          pull: false
    - image: dl-org-api
      context: .
      sync:
        dist/***/*.js*: app/api
      docker:
        dockerfile: app/api/Dockerfile
        buildArgs:
          pull: false
```

### Steps to reproduce the behavior
Run `skaffold dev` and let it run for some time streaming logs from all active pods. If the cluster is brand new, it make take a couple of hours until the problem appears. Sometimes I let `skaffold dev` run overnight to see the problem in the morning, Not sure if this is related to very active logging output (by Stolon) mentioned in #1991 or not.
