### ISSUE TITLE
skaffold cloudbuild ignores gitignore

### ISSUE THREAD

**Issue by panitaxx** [GoogleContainerTools/skaffold#1998]
### Expected behavior

Cloudbuild builds should files in ignore .gitignore

### Actual behavior

It uploads .git and uploads node_modules. 

Sometime they are ignored sometimes they aren't. I have another project with same .gitignore and no .dockerignore file  in which .git and node_modules dirs are not uploaded. I provided a sample repo in which everything is ignore notwithstanding the contents of .gitignore. 

### Information

- Skaffold version: v0.27.0
- Operating system: macOs mojave
- Contents of skaffold.yaml: 

```yaml
apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
  - image: gcr.io/ipcom-vcc/example
    sync:
      '*.js': .
  googleCloudBuild:
    projectId: ipcom-vcc
deploy:
  kubectl:
    manifests:
    - k8s/pod.yaml
```

### Steps to reproduce the behavior

1.  pull repo https://github.com/panitaxx/skaffold-test
2. npm install (so to have a local node_modules)
3. skaffold run (change project name in skaffold.yaml)
4. download the generated tar.gz from cloudstorage to see what is uploaded  

This may not be an issue with small projects, but I have here a project with >1000 packages in node_modules and  almost 150mb  in .git and is very slow to upload.
