### ISSUE TITLE
Add CustomArtifact to local builder to support arbitrary build scripts

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/skaffold#2009]
Add a CustomArtifact artifact type to the local builder so that users can build images with their own build scripts, and thus with whatever builder they desire.

```yaml
apiVersion: skaffold/v1beta9
kind: Config
build:
 artifacts:
   - image: gcr.io/k8s-skaffold/skaffold-bazel
     custom:
       buildCommand: ./build.sh
       dependencies:
         paths:
           - .
         ignore:
           - bazel*
```

WIP #1999 

TODO:
- [ ] consider a distribution method for custom builders

**Comment by sretlawd** [comment]
Would it make sense to allow arguments to be passed to the buildCommand?  Maybe make it an array, or run the command with sh -c?

I'm playing with this a bit, and a good starting point seemed to be to replicate stock behavior with a simple docker build/push like:

```bash
#!/bin/bash
docker build -t ${IMAGE_NAME:?} ${1:-.}
${PUSH_IMAGE:?} && docker push $IMAGE_NAME
```

I'm building multiple artifacts/images in the same skaffold.yaml, so something like:

```yaml
apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: base
    context: base
    custom:
      buildCommand: ./build.sh
  - image: app
    custom:
      buildCommand: ./build.sh
```

But l don't see any way to get the current context path, or specify it as an argument to the buildCommand (since buildCommand is just exec'd).  So as currently implemented, I have to make a separate copy of the build script for each artifact, or deduce the path using the $IMAGE_NAME, which doesn't seem ideal.

Adding an env var with that information would work too, but being able to specify a buildCommand like `"./build.sh some/subdir"` would ultimately provide the most flexibility.

**Comment by priyawadhwa** [comment]
@sretlawd thanks for the feedback! The context is definitely something skaffold could pass in as an environment variable.  We've also been thinking about ways to reuse the same build script with minimal duplication. We considered environment variable substitution, which would look something like this:

```yaml
build:
 artifacts:
   - name: gcr.io/my-image/image1
     custom:
       script: ./cloudbuild.sh
       env:
         CLOUDBUILD_PATH: image1/cloudbuild.yaml
   - name: gcr.io/my-image/image2
     custom:
       script: ./cloudbuild.sh
       env:
         CLOUDBUILD_PATH: image2/cloudbuild.yaml
```
where skaffold would pass in `env` to the build script. WDYT?

**Comment by sretlawd** [comment]
That’d be perfect!  At the moment I’m just working around it by using $IMAGE_NAME and “local conventions”.

Other than that, love the custom builder, I’m able to use an in-cluster buildkitd for my builds and push them to ECR, and it was all pretty easy.

**Comment by MagicShoebox** [comment]
As a piece of feedback: I found it confusing that `custom.buildCommand` didn't depend on `context` the way `docker.dockerfile` did.

```
- image: my-static-content-image
  context: static/
  custom:
    buildCommand: ./build.sh
```

runs `./build.sh` NOT `./static/build.sh`.

In contrast:
```
- image: my-static-content-image
  context: static/
  docker:
    dockerfile: Dockerfile
```

builds `./static/Dockerfile`.

I would also echo the desire to pass command-line arguments.

**Comment by priyawadhwa** [comment]
@MagicShoebox thanks for pointing that out, I think it makes sense that the buildCommand should be run within the context. I've opened #2125 to track that issue.

By command-line arguments, do you mean you would like to be able to specify arbitrary flags to pass in to the build command? Or, would the environment variables described in my comment [here](https://github.com/GoogleContainerTools/skaffold/issues/2009#issuecomment-487672259) suffice?

**Comment by MagicShoebox** [comment]
> By command-line arguments, do you mean you would like to be able to specify arbitrary flags to pass in to the build command? Or, would the environment variables described in my comment here suffice?

I meant arbitrary flags, rather than having the entire build command considered as a single executable.

I'm working on Windows and wanted to run a PowerShell script rather than a .bat script. Since the build command is always run using Windows CMD, I was hoping I could simply make it a call to PowerShell, e.g.
`buildCommand: powershell -ExecutionPolicy Bypass -File %BUILD_CONTEXT%\build.ps1`

When I tried this, Skaffold kept telling me it couldn't find the executable. My assumption was that it was considering the entire command as a single file, rather than recognizing it as a shell command (and that the executable was `powershell`).

I didn't do exhaustive testing— there may have been an error in my setup or this might be a consequence of how Windows handles the `exec` instruction. But none of the examples for `buildCommand` were of the form `buildCommand: ./build.sh -v foo` so I assumed arguments weren't possible.

(For the record, my workaround was to simply make a 1-line "shim" .bat that ran the powershell command above.)

Also, to be clear, running arbitrary commands across multiple platforms is a huge rabbit hole that Skaffold may not want to go down. Just look at Docker's sprawling run/exec/RUN/CMD/ENTRYPOINT/SHELL with it's " "s and []s and / and \\. But if it does, I think keeping it simple and intuitive is a worthy goal.

**Comment by priyawadhwa** [comment]
@MagicShoebox ah I see, flags should definitely work.  I have a fix in to separate the executable from additional arguments (#2130). Once that goes through, would you be willing to try it out and let us know if it fixes your issue?

**Comment by NavyM** [comment]
@priyawadhwa we are actually trying to pass "--ssh default" thro skaffold build args but it is not working. If we pass " --sh default"  to the docker build command it works. Is there any way /example where you can show how to pass "--ssh default " to the buildArgs  in skaffold.yaml .  Thanks.

**Comment by priyawadhwa** [comment]
Hey @NavyM just to clarify, you're using the local docker builder and not the custom builder?

**Comment by NavyM** [comment]
@priyawadhwa thanks for ur prompt reply. Yes, we are using the local docker . Following  is the skaffold.yaml where we are trying to pass  " --ssh= default " in buildArgs and for some reasons it is not working.   
```

apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: skaffold/example
      docker:
        buildArgs:
          ssh: "default"
  local:
    useBuildkit: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
    - k8s/k8s.yml                                                                                                                                                                                                                 

```
