### ISSUE TITLE
No logs after 'skaffold dev' (Jib build, Helm deployment)

### ISSUE THREAD

**Issue by MisterTimn** [GoogleContainerTools/skaffold#2040]
### Expected behavior
Run skaffold dev and receive stream of the logs for the deployed pods.
### Actual behavior
After running skaffold dev there's no logs shown, '-v debug' gives following every 1s:
```
DEBU[0025] could not stat dependency: stat /home/jveessen/ibcndevs/dyversify/data-processor/src/main/resources: no such file or directory 
DEBU[0025] could not stat dependency: stat /home/jveessen/ibcndevs/dyversify/data-processor/src/main/jib: no such file or directory 
DEBU[0025] Found dependencies for jibMaven artifact: [pom.xml src/main/java/technology/idlab.iot/dyversify/ServiceProperty.java src/main/java/technology/idlab.iot/dyversify/main/DataProcessingVerticle.java src/main/java/technology/idlab.iot/dyversify/main/Main.java src/main/java/technology/idlab.iot/dyversify/main/MetricsVerticle.java src/main/java/technology/idlab.iot/dyversify/main/SourceMetricCounter.java] 
```
### Information

- Skaffold version: version 0.28.0
- Operating system: Arch Linux (Manjaro)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
    - image: company-repo/ibcndevs/dyversify/kubernetes-auto-scaler
      context: .
      jibMaven:
        module: ""
        profile: ""
deploy:
  helm:
    releases:
      - name: skaffold-helm
        chartPath: helm/kubernetes-auto-scaler
        valuesFiles:
          - helm/dyversify-values.yaml
        values:
          image: company-repo/ibcndevs/dyversify/kubernetes-auto-scaler
        namespace: default
        recreatePods: true
        imageStrategy:
          helm: {}
profiles:
  - name: obelisk-staging
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/0
        value: helm/obelisk-staging-values.yaml
    activation:
      - kubeContext: obelisk-staging
  - name: dyversify
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/0
        value: helm/dyversify-values.yaml
    activation:
      - kubeContext: dyversify

```

### Steps to reproduce the behavior

1. Set up skaffold project which uses Jib to build and Helm to deploy
2. `skaffold dev -v debug`
