### ISSUE TITLE
Force rebuild if copy fails due to crashing pod

### ISSUE THREAD

**Issue by tdickman** [GoogleContainerTools/skaffold#2042]
### Expected behavior

Skaffold should rebuild the containers if the copy command fails.

### Actual behavior

Skaffold fails to copy objects if a pod is crashing, and I have to manually restart skaffold to get the application working properly.

For example: The copy command will fail if one of the containers is crashing due to a typo in my code. If I attempt to fix this issue, the copy command will continue to fail since the pod is crashing. The only way to fix the issue is to restart skaffold. Ideally skaffold should rebuild the container if the copy command fails.

### Information

- Skaffold version: v0.27.0
- Operating system: Ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: localhost:32000/app
      sync:
        "app/***/*.py": .
deploy:
  helm:
    releases:
      - name: app-name
        chartPath: infrastructure/kube
        namespace: default
        setValueTemplates:
          image.repository: "{{.IMAGE_NAME}}"
          image.tag: "{{.DIGEST}}"
        imageStrategy:
          helm: {}
        valuesFiles:
          - infrastructure/kube/values.yaml
```

### Steps to reproduce the behavior

1. Create an application with at least one pod that uses `sync`
2. Run `skaffold dev`
3. Update the code in a way that causes the pod to crash
4. Fix the code from step 3
5. The copy command from 4 will fail, and you will have to restart skaffold to fix the crash
