### ISSUE TITLE
Dev build cleanup deletes all layers

### ISSUE THREAD

**Issue by tdickman** [GoogleContainerTools/skaffold#2050]
### Expected behavior

Skaffold dev should only cleanup layers it created.

### Actual behavior

Skaffold dev cleans up all layers for a given image (even layers that already existed before it started).

For example, if I run skaffold run once, then run skaffold dev to start developing my application, and later hit control-c to stop the process, skaffold deletes all layers of the image it used, even the layers it didn't build (ex: layers that were built during skaffold run).

My current workflow is to run `skaffold dev` to develop my application, and use control-c when I am done working on it for the time being. I then resume with `skaffold dev` again the next day. This used to start the application in a few seconds (since the previous layers already existed). Now it results in 5 - 10 minutes of build time since it has to rebuild a multi-gigabit docker image.

I believe we should either:
* Update skaffold to only delete new layers that it is responsible for
* Disable image cleanup (pruning) as a default

### Information

- Skaffold version: v0.28.0
- Operating system: Ubuntu 18.10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: localhost:32000/app
deploy:
  helm:
    releases:
      - name: app
        chartPath: infrastructure/kube
        namespace: default
        setValueTemplates:
          image.repository: "{{.IMAGE_NAME}}"
          image.tag: "{{.DIGEST}}"
        imageStrategy:
          helm: {}
        valuesFiles:
          - infrastructure/kube/values.yaml

```

### Steps to reproduce the behavior

1. Run `skaffold run` once (to build and deploy an app)
2. Run `skaffold dev`
3. Control-c out of `skaffold dev`
4. Run `skaffold dev` again
