### ISSUE TITLE
Override k8s yaml file location for Bazel generated k8s configs

### ISSUE THREAD

**Issue by jschaf** [GoogleContainerTools/skaffold#2051]
### Expected behavior

**myapp/skaffold.yaml**
```
apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: bazel/myapp
    bazel:
      target: //myapp:server_image.tar
```

**myapp/BUILD.bazel**
```
go_image(
    name = "server_image",
    library = ":go_default_library",
    ports = ["8001", "8080"],
)

jsonnet_to_json(
    name = "k8s_config",
    src = "k8s_config.jsonnet",
    outs = [
        "dev.deployment.json", 
        "dev.service.json",
    ],
    deps = ["//config/template/k8s"]
)
```

I want to run to specify the location of the k8s files on the command line, since they're generated by bazel from a Jsonnet file.

```
skaffold dev --filename myapp/skaffold.yaml
```

### Actual behavior

Errors with:

```
WARN[0024] k8s/*.yaml did not match any file
```

### Information

- Skaffold version: v0.28.0
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: bazel/myapp
    bazel:
      target: //myapp:server_image.tar
```

### Steps to reproduce the behavior

1. Use k8s files that aren't in `k8s/*`.

**Comment by tejal29** [comment]
you can do that right now by specifying deploy config which points the manifests to the directory they are generated to .
Skaffold by default uses "KubeCtl" deployer with path as "k8s/". The examples use that feature.

Please add the following diff and you be fine.
```
index 31aacc5d..d9178059 100644
--- a/examples/bazel/skaffold.yaml
+++ b/examples/bazel/skaffold.yaml
@@ -5,3 +5,8 @@ build:
   - image: gcr.io/k8s-skaffold/skaffold-bazel
     bazel:
       target: //:skaffold_example.tar
+deploy:
+  kubectl:
+   manifests: [k8s-some/*.yaml]
````

**Comment by jschaf** [comment]
Thanks, that did the trick.  Looks like:

```
deploy:
  kubectl:
    manifests: [
      bazel-out/darwin-fastbuild/bin/myserver/dev.deployment.json,
      bazel-out/darwin-fastbuild/bin/myserver/dev.service.json,
    ]
```

**Comment by tejal29** [comment]
great you can also use file glob pattern like "bazel-out/darwin-fastbuild/bin/myserver/**"

**Comment by tejal29** [comment]
e.g : 
```
deploy:
  kubectl:
    manifests:
    - "backend/k8s/**"

```
