### ISSUE TITLE
Issue deploying to GKE with cloud build / skaffold run

### ISSUE THREAD

**Issue by shavo007** [GoogleContainerTools/skaffold#2057]
### Expected behavior
Deploy sample application to GKE with cloud run

### Actual behavior
Get error:

```
FATA[0002] build failed: building [gcr.io/cloud-build-1/helloworld]: checking bucket is in correct project: iterating over buckets: Get https://www.googleapis.com/storage/v1/b?alt=json&pageToken=&prefix=cloud-build-1_cloudbuild&project=cloud-build-1&projection=full: oauth2: cannot fetch token: unexpected EOF 
```

### Information

- Skaffold version: version v0.28.0
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml

apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: gcr.io/cloud-build-1/helloworld
    context: .
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild:
      projectId: cloud-build-1

```

### Steps to reproduce the behavior

1. Setup a project with vs code extension Cloud code
2. Create GKE cluster
3. Try and run the application with cloudbuild profile

My demo repo can be found here:
https://github.com/shavo007/hello-world#skaffold

The other options worked
