### ISSUE TITLE
Port forwarding not working when official image is referenced

### ISSUE THREAD

**Issue by demisx** [GoogleContainerTools/skaffold#2066]
### Expected behavior
Port forwarding should work no matter if the image is pulled directly from Docker hub or built locally

### Actual behavior
Port forwarding works only if image is build locally.

### Information

- Skaffold version: version: v0.28.0
- Operating system: MacOS 10.14.4
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta9
kind: Config
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kubectl:
        manifests:
          - app/k8s/dev/k8s-elastic-search.yaml
    build:
      artifacts:
        - image: dl-org-elasticsearch
          docker:
            dockerfile: app/elastic-search/Dockerfile
```

### Steps to reproduce the behavior
```Dockerfile
# Dockerfile
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
```

```yaml
# Port forwarding works here
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    tier: backend
spec:
  # type: LoadBalancer
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    component: elasticsearch
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
      tier: backend
  template:
    metadata:
      labels:
        component: elasticsearch
        tier: backend
    spec:
      containers:
        - name: elasticsearch
          image: dl-org-elasticsearch # <-- locally built image
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
```

```yaml
# Port forwarding DOES NOT WORK
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    tier: backend
spec:
  # type: LoadBalancer
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    component: elasticsearch
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
      tier: backend
  template:
    metadata:
      labels:
        component: elasticsearch
        tier: backend
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1 # <-- official image
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
```
