### ISSUE TITLE
Bazel doesn't rebuild images when files change in subdirectories

### ISSUE THREAD

**Issue by jschaf** [GoogleContainerTools/skaffold#2070]
### Expected behavior

Skaffold detects changes in a Bazel workspace and triggers a rebuild and upload.

### Actual behavior

Skaffold doesn't see the change.

### Information

- Skaffold version: v 0.28.0
- Operating system: MacOS
- Contents of skaffold.yaml:  https://github.com/jschaf/bazel-skaffold-bug/tree/474a1c5e9184970a9490bd19acfc232f3a01e711/foobarbaz

```
apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: bazel/foobarbaz
    bazel:
      target: //foobarbaz:skaffold_example.tar
```

### Steps to reproduce the behavior

```
git clone https://github.com/jschaf/bazel-skaffold-bug.git
cd bazel-skaffold-bug
git checkout 474a1c5e9184970a9490bd19acfc232f3a01e711

cd foobarbaz
bazel build :all # to see progress
skaffold dev

# In separate terminal
sed -i '' -e 's/Bazel-0/Bazel-1/' main.go
```

Using the `go_image` target instead of the `.tar` target suggested in https://github.com/GoogleContainerTools/skaffold/issues/482 produces the following error:

```
exiting dev mode because first run failed: build failed: 
  building [bazel/foobarbaz]: build artifact: 
  loading image into docker daemon: reading from image load response: 
  Error processing tar file(exit status 1): archive/tar: invalid tar header
```
