### ISSUE TITLE
Bazel example uses external image instead of locally built image

### ISSUE THREAD

**Issue by jschaf** [GoogleContainerTools/skaffold#2071]
### Expected behavior

Building `examples/bazel` should use the local `main.go` binary.

### Actual behavior

I think Docker downloads gcr.io/k8s-skaffold/skaffold-bazel and uses that instead.

Interestingly, skaffold will detect changes and update the container.  But I'm not sure what's updating.  I don't see any connection between the bazel `go_image` and `gcr.io/k8s-skaffold/skaffold-bazel`.

### Information

- Skaffold version: v0.28.0
- Operating system: MacOS
- Contents of skaffold.yaml:

https://github.com/GoogleContainerTools/skaffold/blob/25f1b66402507440a12a0c1173806b190ff76eb8/examples/bazel/skaffold.yaml

### Steps to reproduce the behavior

1. Download skaffold repo

```
cd examples/bazel
docker run -d -p 5000:5000 --restart=always --name registry registry:2
minikube start --insecure-registry localhost:5000 --vm-driver=hyperkit
eval $(minikube docker-env)

skaffold dev
```

**Comment by jschaf** [comment]
Hmmm, it works now so probably configuration error on my end.  I don't understand how skaffold maps the bazel `go_image` to the `gcr.io` repo.

Some other notes

1. ~~There's no output from the `examples/bazel` repo.  It appears to hang after displaying:~~

2. I can use the local image directly by changing the image references in `skaffold.yaml` and `k8s-pod.yaml` to the image generated by `go_image` which is just called `bazel`.  The image naming convention for `go_image` is `bazel/path/relative/to/workspace:label_name`.  Since the example is in the root, the name is just `bazel`.

```
λ docker images
REPOSITORY  TAG               IMAGE ID      CREATED       SIZE
bazel       skaffold_example  cb33d3659d45  49 years ago  18.2MB
```

**skaffold.yaml**
```
apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: bazel
    bazel:
      target: //:skaffold_example.tar
```

**k8s-pod.yaml**
```
apiVersion: v1
kind: Pod
metadata:
  name: bazel
spec:
  containers:
  - name: bazel
    image: bazel
```
