### ISSUE TITLE
Unable to use kustomize deploy with kustomize base coming from remote git repository

### ISSUE THREAD

**Issue by rgoodwin** [GoogleContainerTools/skaffold#2082]
### Expected behavior

I should be able to run `skaffold -p airflow-dev  and get my deployment to work (in this case deploying airflow. Which is fully working when I do not use a git repo for the kustomize base).

### Actual behavior

I run `skaffold dev -p airflow-dev -v debug` and this error (not i have masked the actual domain and org as its an internal enterprise repo)

```
...
DEBU[0000] setting Docker user agent to skaffold-v0.28.0
INFO[0000] no config entry found for kube-context minikube
DEBU[0000] push value not present, defaulting to false because localCluster is true
FATA[0000] watching files for deployer: listing files: listing files: open local-dev/config/k8s-config/my-development/git@github.enterprise.com:ORG/local-development.git/base/config/k8s-config/kustomization.yaml: no such file or directory
```
### Information

- Skaffold version: version: v0.28.0
- Kustomize Version: `Version: {KustomizeVersion:v2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8 BuildDate:2019-03-18T22:15:21+00:00 GoOs:darwin GoArch:amd64}`
- Operating system: MacOS 10.4 - using hombrew for all tools
- Kubernetes environnment: minikube v1.0.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta9
kind: Config

profiles:
- name: airflow-dev
  deploy:
    kustomize:
      path: local-dev/config/k8s-config/airflow-development

- name: pod-dev
  deploy:
    kustomize:
      path: local-dev/config/k8s-config/pod-development
```

Contents of kustomize.yaml

```yaml
commonLabels:
    run_envrionrment: local-airflow-dev

bases:
  - git@github.enterprise.com:ORG/local-development.git/base/config/k8s-config/kustomization.yaml:

patches:
  - deployment-airflow-local-enviornment-settings.yaml
```
### Steps to reproduce the behavior

1. run: `skaffold dev -p airflow-dev -v debug`
