### ISSUE TITLE
Trouble with pulling image vs manual pull

### ISSUE THREAD

**Issue by sfxworks** [GoogleContainerTools/skaffold#2089]
I am trying to build my image locally and pull it with crio on the cluster so I can dev.

### Expected behavior
The image pulls and pod starts so I can start dev. 

### Actual behavior
Image fails to pull

### Information
When trying to troubeshoot this,

`kubectl run --image docker.io/quantomworks/git-to-k8s:2019-05-08_01-30-59.487_EDT@sha256:8119b054b57e8624644ba3f1db71913990c75d4965bff6866e4a3c2f39f45b9e test --port 8080`

vs

`kubectl run --image docker.io/quantomworks/git-to-k8s:2019-05-08_01-30-59.487_EDT nosha --port 8080`

The one without the sha works. I think this may have something to do with crio as I have tested it with a docker based cluster before, but unsure.

- Skaffold version: v0.28.0
- Operating system: Windows 10 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta9
kind: Config
deploy:
  kubectl:
    manifests:
    - manifest\skaffold\pod.yml
    - manifest\skaffold\service.yml
build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05.999_MST"
      timezone: "Local"
  artifacts:
  - image: docker.io/quantomworks/git-to-k8s
    context: operator
    sync:
      'src/***/*.js': src/
```

### Steps to reproduce the behavior

1. Pull my branch https://github.com/sfxworks/git-to-k8s/tree/skaffold
2. Configure & Build
3. `skaffold dev`
