### ISSUE TITLE
Doc defect - Templated fields in Helm packaged section

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#2092]
Skaffold [currently states](https://skaffold.dev/docs/how-tos/templating/) that Templated fields are allowed in:
-  `build.tagPolicy.envTemplate.template`
-  `deploy.helm.releases.setValueTemplates`

But, I've checked skaffold version `v0.28.0`. It also allows Templated fields in:
- `deploy.helm.releases.packaged`

**For example:**
```yaml
apiVersion: skaffold/v1beta9
kind: Config

build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.MY_VERSION_NUMBER}}"
  artifacts:
  - image: my-repo.com/my-app
    context: .
    jibMaven:

deploy:
  helm:
    releases:
      - name: my-app
        chartPath: helm/my-app
        setValueTemplates:
          image.repository: "{{.IMAGE_NAME}}"
          image.tag: "{{.MY_VERSION_NUMBER}}"
        packaged:
  ############ Templated Fields can be used here!! #################
           version: "{{.MY_VERSION_NUMBER}}"
           appVersion: "{{.MY_VERSION_NUMBER}}"
```
