### ISSUE TITLE
`skaffold dev` always rebuilds container from base image

### ISSUE THREAD

**Issue by expz** [GoogleContainerTools/skaffold#2094]
### Expected behavior

If nothing has changed in the repository or base image, then the build images have the same SHA digest and hence can use the cache. (If the current behavior is a feature and not a bug, then perhaps a skaffold dev --use-cache flag could be added?)

I have a huge container that takes ~15 minutes to build on my laptop with most of it spent installing python libraries, etc that do not need to be changed often. I need a way to use skaffold without having to wait 15 minutes to see, e.g. if my one line change at the end of a Dockerfile has a bug.

### Actual behavior

If I run `skaffold dev --no-prune` twice in a row without changing anything, then the SHA digests of all but the base image change, so the cache is not used.

### Information

- Skaffold version: v0.28.0
- Operating system: Ubuntu 18.04 LTS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: skaffold-test/postgres
    context: .
    docker:
      dockerfile: Dockerfile
      cacheFrom:
      - postgres:9.6
deploy:
  kubectl:
    manifests:
      - postgres.yaml
```

### Steps to reproduce the behavior

Put these in the same directory as `skaffold.yaml`.

`postgres.yaml`:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: postgres-datahub
  labels:
    name: postgres
spec:
  containers:
  - name: postgres
    image: skaffold-test/postgres
    ports:
    - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: LoadBalancer
  ports:
  - port: 5432
  selector:
    name: postgres
```

`init.sh`:
```bash
#!/bin/sh

psql postgres -c 'CREATE DATABASE test'
```

`Dockerfile`:
```docker
FROM postgres:9.6

COPY init.sh /docker-entrypoint-initdb.d/

RUN chmod a+x /docker-entrypoint-initdb.d/init.sh
```

Now run `skaffold dev --no-prune` twice in a row from the same directory.
