### ISSUE TITLE
Add Jib tagPolicy

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#2098]
Allow using pom.xml as the version for the Docker Image tag. Maybe Jib can provide this?

For example:
```
apiVersion: skaffold/v1beta9
kind: Config

build:
  tagPolicy:
    # jibMaven HERE!!!!!
  artifacts:
    - image: my-repo.com/my-app
      context: .
      jibMaven:
```

The Jib equivalent would be
```
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>1.2.0</version>
                    <configuration>
                        <to>
                            <tags>
                                <tag>${project.version}</tag>
                            </tags>
                        </to>
                    </configuration>
                </plugin>
```
