### ISSUE TITLE
Can't build and deploy with Skaffold Release v0.29.0

### ISSUE THREAD

**Issue by levkov** [GoogleContainerTools/skaffold#2106]
Trying to deploy helm-deployment from examples. 
https://github.com/GoogleContainerTools/skaffold/tree/master/examples/helm-deployment

It was working in the past releases.

### Expected behavior
Successfully build the image locally and deploy helm chart. 

### Actual behavior
Skaffold exits with error: 
```
FATA[0000] deploying skaffold-helm: matching build results to chart values: no build present for gcr.io/k8s-skaffold/skaffold-helm 
```
### Information

- Skaffold version: 0.29.0
- Operating system: Ubuntu 18.10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta10
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: skaffold-helm
      #wait: true
      #valuesFiles:
      #- helm-skaffold-values.yaml
      values:
        image: gcr.io/k8s-skaffold/skaffold-helm
      #recreatePods will pass --recreate-pods to helm upgrade
      #recreatePods: true
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.
      #setValues:
        #some.key: someValue
```

### Steps to reproduce the behavior

1. Git clone skaffold git repository
2. Run `skaffold deploy` inside examples/helm-deployment directory.
