### ISSUE TITLE
creating a cronjob

### ISSUE THREAD

**Issue by tuananh** [GoogleContainerTools/skaffold#2114]
i want to create a cronjob with schedule is every 10 minutes so i put this as schedule value : `*/10 * * * *`. However, this will fail with error 

    error converting YAML to JSON: yaml: line 14: did not find expected alphabetic or numeric character

when I use it with value `0 2 * * *` (every 2 hours), it seems fine however.

### Expected behavior
cronjob created
### Actual behavior
deploy failed
### Information

- Skaffold version: v0.29.0
- Operating system: ... macOS 10.14.4
- Contents of skaffold.yaml:

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "example.fullname" . }}-cache-cron
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "example.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.mySchedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ template "example.name" . }}
        spec:
          restartPolicy: OnFailure
          containers:
          - name: example-script
            image: {{ .Values.image }}
            imagePullPolicy: Always
            command: ["npm",  "run", "example-script"]
```

### Steps to reproduce the behavior

1. skaffold run xxx.yaml
2. ...
