### ISSUE TITLE
Bazel build target is not parsed correctly resulting in "required value not set: target"

### ISSUE THREAD

**Issue by hipstern** [GoogleContainerTools/skaffold#2117]
Since attempting to upgrade to skaffold 0.28/0.29 i'm getting "required value not set: target" on what seems like a failed validation. however the field "target" does indeed exist and does indeed have a string value which maps to a real bazel target. not sure what's up with that!

In fact, the official bazel example from this repo produces the same error:
https://github.com/GoogleContainerTools/skaffold/tree/master/examples/bazel

### Expected behavior
Should run the skaffold file and not complain on missing target value
### Actual behavior
required value not set: target
### Information

- Skaffold version: 0.28 and 0.29
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
    - image: myrepo.com/myimage
      context: .
      bazel:
        target: //:mytarget.tar
```
