### ISSUE TITLE
Partial apply interferes with pruning

### ISSUE THREAD

**Issue by mxey** [GoogleContainerTools/skaffold#2120]
`skaffold dev` only passes modified resources to `kubectl apply`. If using `--prune` as a kubectl flag, that will remove all matching resources but the modifies ones.

### Expected behavior

kubectl does not delete unmodified resources if using pruning

### Actual behavior

kubectl deletes unmodified resources if using pruning

```
$ skaffold dev 
Generating tags...
Tags generated in 29.849µs
Starting build...
Found [minikube] context, using local docker daemon.
Build complete in 25.143µs
Starting test...
Test complete in 4.662µs
Starting deploy...
kubectl client version: 1.14
configmap/configmap-1 created
configmap/configmap-2 created
Deploy complete in 2.730178131s
Watching for changes every 1s...
Starting deploy...
kubectl client version: 1.14
configmap/configmap-2 configured
configmap/configmap-1 pruned
Deploy complete in 1.921527698s
Watching for changes every 1s...
```

### Information

- Skaffold version: v0.29.0
- Operating system: macOS 10.14.4
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta10
kind: Config
deploy:
  kubectl:
    manifests:
    - manifest.yaml
    flags:
      apply:
      - --prune
      - -l app=skaffold-reproduction
```

- Contents of manifest.yaml:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-1
  labels:
    app: skaffold-reproduction
data:
  foo: bar

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-2
  labels:
    app: skaffold-reproduction
data:
  foo: bar
```

### Steps to reproduce the behavior

1. skaffold dev
2. Modify data of configmap-2 in `manifest.yaml`
