### ISSUE TITLE
Custom artifact build command should run in the artifact context

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/skaffold#2125]
As described in this [comment](https://github.com/GoogleContainerTools/skaffold/issues/2009#issuecomment-492317902), the `buildCommand` for a custom artifact should be run in the context of that artifact.

From the comment:

>I found it confusing that `custom.buildCommand` didn't depend on `context` the way `docker.dockerfile` did.
```
- image: my-static-content-image
  context: static/
  custom:
    buildCommand: ./build.sh
```
>runs `./build.sh` NOT `./static/build.sh`.

>In contrast:
```
- image: my-static-content-image
  context: static/
  docker:
    dockerfile: Dockerfile
```

> builds `./static/Dockerfile`.
