### ISSUE TITLE
Skaffold couldn't find local image artifacts

### ISSUE THREAD

**Issue by yfei1** [GoogleContainerTools/skaffold#2126]
I have a project with a base-image and a few application images based on that. I am working on migrating from my current building workflow to skaffold.

The base build dockerfile is responsible for downloading my project's dependency
```
# Dockerfile.base-build
FROM golang:latest
ENV GO111MODULE=on

WORKDIR /go/src/path/to/workspace
COPY . .
RUN go mod download
```
The application image will then build an executable file based on the dependencies.
```
# Dockerfile.application
FROM base-image as base
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .

FROM gcr.io/distroless/static
COPY --from=base /path/to/application .

ENTRYPOINT ["/application"]
```
I tried to let skaffold understand the dependency between these images but failed.
- Skaffold version: v0.29.0
- Operating system:  Linux Debian
- Contents of skaffold.yaml:
```
apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: base-image
    docker:
      dockerfile: Dockerfile.base-image
  - image: application-image
    docker:
      dockerfile: Dockerfile.application
      cacheFrom:
      - base-image
```
### Expected behavior
Skaffold is able to build both images successfully.
### Actual behavior
```
WARN[0002] Error processing base image (base-image) for ONBUILD triggers: getting remote config: getting image: UNAUTHORIZED: authentication required; [map[Type:repository Class: Name:library/base-image Action:pull]]. Dependencies may be incomplete.
FATA[0005] exiting dev mode because first run failed: build failed: building [base-image]: Error parsing reference: "" is not a valid repository/tag: invalid reference format
```
### Steps to reproduce the behavior
```
skaffold dev
```

Is there anything missing from my skaffold.yaml? Did I misconfigure something?
