### ISSUE TITLE
File sync Ignoring Files

### ISSUE THREAD

**Issue by RSWilli** [GoogleContainerTools/skaffold#2127]
I'm using Skaffold filesync with NodeJS hotreload and its working pretty fine, except that the image gets rebuild even if I didn't change any files.

I suppose the reason for that is that VSCode does a git fetch in the background, and updates the .git folder (as shown by the mtime of ls -la)

is there any way of a "blacklist" of files that should not be watched?

### Information

- Skaffold version: v0.29.0 
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: my-nodejs
    sync:
      manual:
        - src: "**/*.ts"
          dest: "."
        - src: "**/*.tsx"
          dest: "."
    context: ./subfolder/
    docker:
      dockerfile: Dockerfile.dev
  local: {}
deploy:
  kubectl:
    manifests:
      - subfolder/k8s/**
```
