### ISSUE TITLE
kaniko buildArgs env variable not properly interpolated

### ISSUE THREAD

**Issue by r0bj** [GoogleContainerTools/skaffold#2153]
### Expected behavior

kaniko buildArgs env variable is interpolated to kaniko executor parameter.

### Actual behavior

kaniko buildArgs env variable is not interpolated to kaniko executor parameter and it's passed literally.

### Information

- Skaffold version: v0.29.0
- Operating system: ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: gcr.io/example/app
    kaniko:
      buildContext:
        localDir: {}
      cache: {}
      buildArgs:
        TAG: "{{.APP_VERSION}}"
      image: gcr.io/kaniko-project/executor:debug
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.APP_VERSION}}"
  cluster:
    pullSecretName: kaniko-secret
```

### Steps to reproduce the behavior

Execute:
```
APP_VERSION=v1.31.6 skaffold build
```

This translates to kaniko executor command line:
```
/kaniko/executor --dockerfile Dockerfile --context dir:///kaniko/buildcontext --destination gcr.io/example/app:v1.31.6 -v info --build-arg TAG={{.APP_VERSION}} --cache=true
```
Note:
`--build-arg TAG={{.APP_VERSION}}` instead of `--build-arg TAG=v1.31.6`

So instead of interpolating env variable as a build argument `TAG` to `v1.31.6`, skaffold passes literally `{{.APP_VERSION}}` as a parameter.

**Comment by demisx** [comment]
I am experiencing the same issue passing environment var to dockerfile as buildArgs:

```yaml
    docker:
            dockerfile: app/api/Dockerfile
            target: dev-env
            buildArgs:
              AWS_ACCOUNT_ID: "{{.AWS_ACCOUNT_ID}}"
```

```sh
# In container
$ env | grep AWS
AWS_ACCOUNT_ID={{.AWS_ACCOUNT_ID}} # <- literal value instead of interpolated one
````
