### ISSUE TITLE
Skaffold sync unable to parse config

### ISSUE THREAD

**Issue by Hudsonzp** [GoogleContainerTools/skaffold#2158]
### Expected behavior
Yaml file parses correctly and directory syncing works.

### Actual behavior
Parse error on the latest version.  No more directory sync.

### Information
A little while ago I approached skaffold with an issue syncing entire directories.  I was instructed to use an undocumented pattern `***/*.js`.  That worked, but it appears that pattern has been removed on the latest version so I'm looking for a solution to be able to do that again? 

- Skaffold version: Version 0.29 (latest as of May 20).
- Operating system: macOS Mojave 10.14.4
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta10
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: test/dev-client
      docker:
        dockerfile: Dockerfile.dev
      context: ./client
      sync:
        '***/*.css': .
        '***/*.scss': .
        '***/*.js': .
        '***/*.less': .
    - image: test/dev-server
      docker:
        dockerfile: Dockerfile.dev
      context: ./server
      sync:
        '***/*.py': .

deploy:
  kubectl:
    manifests:
      - k8s-dev/client-deployment.yaml
      - k8s-dev/server-deployment.yaml

```

### Steps to reproduce the behavior

1. Use the undocumented *** star pattern above.
2. Try to run `skaffold dev`

```shell
FATA[0000] creating runner: parsing skaffold config: unable to parse config: yaml: unmarshal errors:
  line 12: field ***/*.css not found in type latest.Sync
  line 13: field ***/*.scss not found in type latest.Sync
  line 14: field ***/*.js not found in type latest.Sync
  line 15: field ***/*.less not found in type latest.Sync
  line 21: field ***/*.py not found in type latest.Sync
```

**Comment by corneliusweig** [comment]
The sync config was improved with version v1beta10. The easiest fix is to change your config version to `v1beta9` and call `skaffold fix`. Skaffold will update your sync config for you.

**Comment by Hudsonzp** [comment]
@corneliusweig thank you!  Very help and solved my issue.

**Comment by Hudsonzp** [comment]
@corneliusweig 

So this is the proper approach now for the triple star?
```
 manual:
          - src: '**/*.css'
            dest: .
          - src: '**/*.scss'
            dest: .
          - src: '**/*.js'
            dest: .
          - src: '**/*.less'
            dest: .
      docker:
```

Just checking that "dest" is meant to be empty?

**Comment by corneliusweig** [comment]
Yes this is expected. Please see https://skaffold.dev/docs/how-tos/filesync/ for details.

**Comment by Hudsonzp** [comment]
@corneliusweig thanks for the info and link.  

I've noticed now that I'm back to the problem I had previously when files get flattened.

- Here is the original issue: https://github.com/GoogleContainerTools/skaffold/issues/1896
- Looks like you solved it with the triple asterisk: https://github.com/GoogleContainerTools/skaffold/issues/1837
- It was then superseded by this: https://github.com/GoogleContainerTools/skaffold/pull/1994

However, the current filesync documentation found here doesn't show anything about preserving that file structure that the triple asterisk used to accomplish.  https://skaffold.dev/docs/how-tos/filesync/

Any thoughts on how I can get this back in there?

**Comment by Hudsonzp** [comment]
Oh...perhaps I can still use that triple asterisk pattern even though it isn't documented?

```
 manual:
          - src: '**/*.css'
            dest: .
          - src: '**/*.scss'
```
To
```
 manual:
          - src: '***/*.css'
            dest: .
          - src: '***/*.scss'

```
