### ISSUE TITLE
skaffold run --tail not working as of 0.30.0.

### ISSUE THREAD

**Issue by bmcstdio** [GoogleContainerTools/skaffold#2167]
### Expected behavior

Running `skaffold run --tail` should block while streaming logs from deployed object.

### Actual behavior

Running `skaffold run --tail` exits with the following message:

```text
(...)
Deploy complete in 500.796952ms
You can also run [skaffold run --tail] to get the logs
```

### Information

- Skaffold version: 0.30.0.
- Operating system: Linux.
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: "gcr.io/my-project/my-image"
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - pod.yaml
profiles:
- name: gke
  build:
    googleCloudBuild:
      projectId: "my-project"
```

### Steps to reproduce the behavior

1. Run `skaffold run --tail -f skaffold.yaml -p gke`.
