### ISSUE TITLE
Feature request: allow skaffold build once and tag&push Image to multiple repos

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#2169]
I'd like to use Skaffold+Jib to build my container image and push it to both an in-house Nexus Docker Registry and also push to eu.gcr.io

Currently I'm having to rebuild the Image for each repository using skaffold profiles.
Could Jib build the image once and tag it with each repo name I need (same tag version) and then push it to each repo.

Benefit:
Build once, push to different repos I use and then use skaffold profiles to do the deployment to the different environments.

**Comment by briandealwis** [comment]
Unfortunately this isn't possible.  Basically Skaffold+Jib ends up running something like
```
mvn prepare-package jib:build -Dimage=<skaffold-image>
```

Maven supports invoking plugin goals with [different `<execution>` IDs](https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_executions_Tag), so I wondered if you could use the `args` field to add additional `jib:build` to that command-line (e.g., `jib:build@id2`).  Unfortunately Jib treats command-line properties as over-riding those set in the pom, so the `-Dimage=xxx` will prevail.

Instead of Skaffold profiles, you could duplicate your artifact in your `skaffold.yaml` and just never reference the second artifact.  For example:
```
build:
  artifacts:
  - image: gcr.io/project/image
    context: my-jib-project
    jibMaven: {}
  - image: local.nexus.host/project/image
    context: my-jib-project
    jibMaven: {}
```
Skaffold will warn:
```
WARN[0015] image [localhost:5000/foo] is not used by the deployment 
```

**Comment by dkirrane** [comment]
@briandealwis I tried with duplicate artifacts but only 1 image `foo` is passed to Maven:

```
$ VERSION=1.2.3 skaffold run -v debug 2>&1 | grep -i 'Running command'
"Running command: [mvn -Djib.console=plain --non-recursive prepare-package jib:build -Dimage=eu.gcr.io/project/foo:1.2.3]"
```

```
apiVersion: skaffold/v1beta10
kind: Config

build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: eu.gcr.io/project/foo
      context: ./app
      jibMaven: {}
    - image: local.nexus.host/bar
      context: ./app
      jibMaven: {}
```
