### ISSUE TITLE
Image repo handling strategies don't work for EU repos

### ISSUE THREAD

**Issue by trenslow** [GoogleContainerTools/skaffold#2185]
### Expected behavior
A push to default repo eu.gcr.io/{PROJECT_ID}/example-directory should overwrite the image name, not create a new repo/directory within default repo

### Actual behavior
Image is pushed to eu.gcr.io/example-project/example-directory/eu_gcr_io_example-project_example-directory 

### Information
My guess is that this functionality only works for repositories beginning with 'gcr.io', based on the documentation [here](https://skaffold.dev/docs/concepts/). Would be nice if this functionality worked for EU GCR repos, in order to reduce latency in the continuous deployment pipeline.

- Skaffold version: version... v0.30.0
- Operating system: ... Windows 10 Enterprise
- Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: eu.gcr.io/{PROJECT_ID}/example-directory
```

### Steps to reproduce the behavior

1. ... skaffold config set default-repo eu.gcr.io/{PROJECT_ID}/example-directory
2. ... skaffold run
