### ISSUE TITLE
Skaffold craches when building with the docker daemon inside minikube

### ISSUE THREAD

**Issue by rugwirobaker** [GoogleContainerTools/skaffold#2187]
### Expected behavior
`skaffold dev` or `skaffold  build` is supposed to work with my current docker context which in this case is the minikube docker daemon when it's running.
### Actual behavior
My build fail with the following error when I run the above commands with minikube running which I believe is due to my laptop's docker client being newer :

`FATA[0057] build failed: building [guestbook-backend]: build artifact: docker build: Error response from daemon: client version 1.39 is too new. Maximum supported API version is 1.38`

### Information

- Skaffold version: v0.30.0
- Operating system: ubuntu/amd64
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: guestbook-backend
    context: src/backend
  - image: guestbook-frontend
    context: src/frontend
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
```

### Steps to reproduce the behavior

1. First I stopped minikube and built locally `skaffold dev`. The build process finishes without a problem.
2. I got an error while you trying to build with minikube running since this time skaffold was sending the context to the docker daemon inside of minikube. 
3. Following instructions from this issue on the minikube repo: https://github.com/kubernetes/minikube/issues/338# I tried to downgrade my client with `eval $(minikube docker-env | grep -v DOCKER_API_VERSION)` which also didn't work.

### Note:
I tried to get feedback from this issue: #1749 but since it seems abandoned I filled my own issue
