### ISSUE TITLE
kaniko pull secret should be optional

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#2190]
Right now PullSecretName is created while building image using kaniko with buildcontext of localdir.

### Expected behavior
When build context is set to localdir, then there is no need to create a pull secret.
### Actual behavior
Secret is getting created
### Information

- Skaffold version: 30
- Operating system: linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
# denotes the user’s image push location in artifactory, ensure user write permission in artifactory, this should be the same location referenced in your respective deployment yml
  - image: www.someurl.com/docker-sandbox/kube/pythonserver
    context: .
    kaniko:
      buildContext:
        localDir: {}
  cluster:
    namespace: 103000-pras-dev
#    pullSecretName: regcred
    dockerConfig:
      path: ~/.docker/config.json
deploy:
  kubectl:
    manifests:
#must match the kubernetes deploy file name of application
      - deploy.yml
```

### Steps to reproduce the behavior

1. Run the skaffold wiht kaniko builder and build context equal to localdir
