### ISSUE TITLE
Skaffold --cache-artifacts should check remote registry instead of local

### ISSUE THREAD

**Issue by zodiac1214** [GoogleContainerTools/skaffold#2197]
### Expected behavior
Do not rebuild the docker image when it is cached on remote docker registry even you don't have the cached image on local

### Actual behavior
Rebuild the docker images regardless of the state on remote registry. If you have the cached image removed from your local, skaffold will trigger a full build

### Information

- Skaffold version: version0.28 and 0.30
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
    - image: myimage
      docker:
        dockerfile: Dockerfile
        target: stage1
  local:
    useDockerCLI: false
    useBuildkit: false
```

### Steps to reproduce the behavior

1. `skaffold build --cache-artifacts --default-repo x.y.z:5000 --insecure-registry x.y.z:5000`, i can see the cache image has been pushed to my remote registry
2. `docker rmi -f $(docker images -aq)`

3. `skaffold build --cache-artifacts --default-repo x.y.z:5000 --insecure-registry x.y.z:5000` again:
```
Checking cache...
 - myimage: Not found. Rebuilding.
```
in step 3, i can see that a new cache image with the **same tag** has been pushed to my remote registry again
