### ISSUE TITLE
'skaffold dev' does not work with multiple jibGradle builds

### ISSUE THREAD

**Issue by ymahajan98** [GoogleContainerTools/skaffold#2206]
### Expected behavior
'skaffold dev' starts.

### Actual behavior
I get this error message regarding the version of jib although I am using jib version 1.2.0.
```
FATA[0001] watching files for artifact localhost:5000/cata-j: listing files: listing files: getting jibGradle dependencies: failed to walk Jib build files for changes: failed to get Jib dependencies; it's possible you are using an old version of Jib (Skaffold requires Jib v1.0.2+): exec: Stdout already set
```

### Information
With multiple images 'skaffold dev' fails to run. However, it does work if I use jibGradle for one image and use a dockerfile/custom script to build the other image. 
Using two different .yaml files to build the images using jibGradle also works. 
I am using a local docker registry with Minikube.

- Skaffold version: v0.30.0
- Operating system:  Ubuntu 16.04.6 LTS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    sha256: {}
  local:
    push: true
  artifacts:
  - image:  localhost:5000/book-j
    context: Booking
    jibGradle: {}
  - image:  localhost:5000/cata-j
    context: Catalog
    jibGradle: {}
deploy:
  kubectl:
    manifests:
    - kubernetes/booking-service.yaml
    - kubernetes/catalog-service.yaml
```

### Steps to reproduce the behavior

1. 'skaffold dev --trigger notify'
