### ISSUE TITLE
Templated Docker buildArgs work with useDockerCLI but not with the Docker Engine

### ISSUE THREAD

**Issue by sandhose** [GoogleContainerTools/skaffold#2234]
### Expected behavior

Templated field should work with `build.artifacts[].docker.buildArgs.*` for docker builds.

### Actual behavior

They only work if `build.local.useDockerCLI` is set to `true`.

### Information

- Skaffold version: 0.31.0
- Operating system: macOS 10.14.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: myimages
    docker:
      buildArgs:
        BUILD_DATE: '{{ .BUILD_DATE }}'
        COMMIT: '{{ .COMMIT }}'
        VERSION: '{{ .VERSION }}'
  local:
    useDockerCLI: true
deploy:
  kustomize:
    path: "k8s/"
```

### Steps to reproduce the behavior

1. Have a docker image that use build args
2. Set that build arg with a template
3. Run `skaffold build` with the environment variable set
4. Inspect the built image label

`Dockerfile`:
```dockerfile
FROM scratch

ARG MY_ARG
LABEL my_label=$MY_ARG
```

`skaffold.yaml`:
```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: my_image
    docker:
      buildArgs:
        MY_ARG: '{{ .MY_ARG }}'
  local:
    useDockerCLI: true
```

```sh
$ MY_ARG=foo skaffold build
...
Successfully tagged my_image:latest
...
$ docker inspect my_image:latest -f '{{.ContainerConfig.Labels.my_label}}'
foo
```

---

After setting `build.local.useDockerCLI` to `false` in `skaffold.yaml`:

```sh
$ MY_ARG=foo skaffold build
...
Successfully tagged my_image:latest
...
$ docker inspect my_image:latest -f '{{.ContainerConfig.Labels.my_label}}'
{{ .MY_ARG }}
```

---

The code that does this for the docker CLI builder seems to be here:

https://github.com/GoogleContainerTools/skaffold/blob/6cb1d519c275fa88af5ac34df961d00188e87497/pkg/skaffold/docker/image.go#L345-L358
