### ISSUE TITLE
Remote helm chart shouldn't be upgraded on code changes

### ISSUE THREAD

**Issue by dahovey** [GoogleContainerTools/skaffold#2245]
### Expected behavior

A remote helm chart shouldn't be upgraded on code changes. In my workflow `skaffold.yaml` is configured with several remote helm charts (i.e. `stable/mssql-linux`, `stable/redis`, `internal/shared-component`). I run `skaffold dev` which builds images, deploys remote helm charts as well as local helm chart. When code changes in the current project, I don't expect to re-deploy the sql server instance or redis cache.

If `skaffold.yaml` or values file of applicable remote repository is changed, then upgrade chart.

### Actual behavior

After every code change, all configured helm releases within skaffold.yaml are upgraded, even remote charts.

### Information

- Skaffold version: v0.31.0
- Operating system: Windows
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: app
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  helm:
    releases:
    - name: mssql-linux
      chartPath: stable/mssql-linux
      setValues:
        ...
      remote: true
    - name: redis
      chartPath: stable/redis
      setValues:
        ...
      remote: true
    - name: shared-component1
      chartPath: internal/shared-component1
      remote: true
      valuesFiles:
        ...
    - name: app
      chartPath: charts/app
      values:
        "image": app
```

## Resolution

In my opinion, remote helm charts shouldn't be upgraded, but there could be other use cases besides mine?
