### ISSUE TITLE
Changes after v0.31.0 release not working on Windows

### ISSUE THREAD

**Issue by dahovey** [GoogleContainerTools/skaffold#2256]
Checking out current master, building, and running `skaffold dev` outputs the following. _image name replaced with <app>_

```
time="2019-06-11T08:32:54-07:00" level=fatal msg="watching files for artifact <app>: listing files: listing files: listing copied files: retrieving image config: getting image: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/base Type:repository]]"
```

If I checkout tag `v0.31.0` and rebuild, `skaffold dev` works as expected.

### Information

- Skaffold version: v0.31.0-dirty
- Operating system: Windows 10 Pro

Appears to be from:
https://github.com/GoogleContainerTools/skaffold/blob/e8302bbe633059e68079c6954cf7649d78256aeb/pkg/skaffold/docker/parse.go#L92-L95

**Comment by nkubala** [comment]
hey @dahovey, can you give us a little more information about your project? are you using a private/insecure registry to push your images? I'm not able to reproduce this.

**Comment by dahovey** [comment]
Using local K8s cluster from Docker Desktop Version: 2.0.5.0

![image](https://user-images.githubusercontent.com/22330242/59805617-a6ab9580-92a6-11e9-938e-7a0672aea24a.png)

Skaffold.yaml:
```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: app
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  helm:
    releases:
    - name: app
      chartPath: charts/app
      values:
        "image": app
```

Output at command prompt:
![image](https://user-images.githubusercontent.com/22330242/59805726-effbe500-92a6-11e9-954d-7b914c41361b.png)
