### ISSUE TITLE
Sync does not sync to other namespaces

### ISSUE THREAD

**Issue by Yerhabe** [GoogleContainerTools/skaffold#2262]
### Expected behavior
Skaffold should be able to successfully sync across multiple namespaces. Skaffold should be aware what namespace pods are deployed to and ensure that the syncing is applied within that namespace so that it succeeds.

### Actual behavior
Skaffold is only able to sync to the currently set namespace (whether it was set via kubectl, helm or the skaffold `-n` flag). If the files we're trying to sync belong to a pod that is in a different namespace we get the following error on sync: `Skipping deploy due to sync error: copying files: didn't sync any files`.

This is particularly an issue if you have deployments for multiple namespaces and you want to just run a single `skaffold dev` and have syncing work for all of them.

### Information

- Skaffold version: v0.31.0
- Operating system: macOS Sierra 10.12.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/node-example
    context: node
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
        strip: src/
```
- Contents of `k8s/node.yaml`:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: test-ns
spec:
  ports:
  - port: 3000
  type: LoadBalancer
  selector:
    app: node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: gcr.io/k8s-skaffold/node-example
        ports:
        - containerPort: 3000
```

### Steps to reproduce the behavior

1. Download https://github.com/GoogleContainerTools/skaffold/tree/master/examples/hot-reload.
2. Run `skaffold dev` and modify `node/src/index.js` and the sync will be successful.
3. Stop `skaffold dev`.
4. Create a namespace `test-ns` (either via kubectl or by adding a yaml file defining type Namespace and having skaffold apply it, both ways have the same issue). 
5. In `k8s/node.yaml` add `namespace: test-ns` to the Service and Deployment.
6. Run `skaffold dev` and modify `node/src/index.js` and the sync will error out with: `Skipping deploy due to sync error: copying files: didn't sync any files`.
