### ISSUE TITLE
Support for custom push, e.g. for use with kind load

### ISSUE THREAD

**Issue by vasu1124** [GoogleContainerTools/skaffold#2264]
Would be nice if you could support local testing with [kind](https://kind.sigs.k8s.io/).

Currently, you can skip pushing to a registry when detecting kind, I use
```
apiVersion: skaffold/v1beta11
kind: Config
profiles:
- name: dev
  build:
    local:
      push: false
  activation:
  - kubeContext: "kubernetes-admin@kind"
```
but now you still need to be able to call a custom cmd to "push" the image, in particular with `kind load docker-image $IMAGE.`
