### ISSUE TITLE
Support Docker Build secret mounts (--mount=type=secret)

### ISSUE THREAD

**Issue by braderhart** [GoogleContainerTools/skaffold#2273]
### Expected behavior
skaffold.yaml to support new Docker Build secrets
- https://docs.docker.com/develop/develop-images/build_enhancements/

### Actual behavior
```sh
 => ERROR [2/4] RUN --mount=type=secret,id=mysecret cat /run/secrets/mysecret                                                                                                                               0.4s
------
 > [2/4] RUN --mount=type=secret,id=mysecret cat /run/secrets/mysecret:
#9 0.379 cat: can't open '/run/secrets/mysecret': No such file or directory
------
rpc error: code = Unknown desc = executor failed running [/bin/sh -c cat /run/secrets/mysecret]: exit code: 1
Complete in 3.254675056s
FATA[0003] build failed: building [image-test]: build artifact: running build: exit status 1 
```

### Information

- Skaffold version: v0.31.0
- Operating system: Arch 5.1.9-arch1-1-ARCH
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: image-test
deploy:
  kustomize: {}

profiles:
- name: dev
  activation:
  - kubeContext: minikube
  build:
    local:
      useBuildkit: true
```

- Contents of Dockerfile:

```yaml
# syntax=docker/dockerfile:1.0.0-experimental

FROM alpine

RUN --mount=type=secret,id=mysecret cat /run/secrets/mysecret
```

### Steps to reproduce the behavior

1. `skaffold build`

### Suggestions
Make skaffold easier to adapt to new features without having to change sourcecode

**Comment by balopat** [comment]
Thanks for opening this @braderhart. 
Secret management is important for us and we do want to help with the workflows around it. 

Regarding "Make skaffold easier to adapt to new features in underlying tools": that's another area that we are thinking about - same issues crop up around kaniko for example.

**Comment by aksharpanchal** [comment]
Does that mean the support for mount=type=ssh is something you would have along with this feature implementation?

**Comment by mbow** [comment]
@aksharpanchal are you also hitting issues with buildkit in skaffold with ssh and private repos ?
if so did you ever solve that ? ssh was working until trying new buildkit options, just wondered if you noticed if i've misunderstood something.
```yaml
build:
      local:
        useDockerCLI: true
        useBuildkit: true
        concurrency: 4
```
examples 
```
RUN git config \
    --global \
    url."git@git.internal.com:".insteadOf \
    	"https://github.com/"
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh git clone git@github.com:repo-name/repo.git
```
or moutning go mod cache to share when doing a concurrency!=1 build
```docker
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -a -o /main 
```
