### ISSUE TITLE
Old sync config stops working

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#2280]
I had this sync config working with skaffold beta8:

```
apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
  - image: myimage
    sync:
      public/*: /app/public
```

It stopped working with `v0.31.0`. Looks like when I change a file under `public`, it's synced to `/app/public/public/`.

To fix it, I changed the skaffold.yaml to:

```
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: myimage
    sync:
      manual:
      - src: public/*
        dest: /app
```

Can we do something to fix the backward compatibility?

ping @corneliusweig @balopat
