### ISSUE TITLE
skaffold run - python code not updating

### ISSUE THREAD

**Issue by jtlz2** [GoogleContainerTools/skaffold#2295]
### Expected behavior

When I execute `skaffold run`, I expect the very next deployment to contain the python flask code changes that I have just made in PyCharm.

### Actual behaviour

Sometimes (but not always), the code changes are not reflected in the new container when I do this.

A fix is to do a git commit and rerun.

### Information

- Skaffold version: 3f0dab6
- Operating system: macOS High Sierra 10.13.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: registry.../image
    context: .
    sync:
      manual:
      - src: "app/***/*.py"
        dest: "/app/"
    docker:
      noCache: false
deploy:
  helm:
    releases:
    - name: releasename
      chartPath: ...
      valuesFiles:
      - overrides_jtlz2.yaml
      values:
        global.image: registry.../image
      namespace: jtlz2
      imageStrategy:
        helm: {}

```

### Steps to reproduce the behaviour

1. `skaffold run`

I realise this is an incredibly difficult one to diagnose because it's intermittent, but that makes it no less frustrating. PyCharm? Image repo caching?

Is anyone else experiencing this?

Thanks for all help
