### ISSUE TITLE
ability to set default repo from profile

### ISSUE THREAD

**Issue by saturnism** [GoogleContainerTools/skaffold#2317]
currently, the default repo can be associated w/ a kubecontext and is stored in `$HOME/.skaffold/config`. It would be useful if the default repo is configured from skaffold profile.

**Comment by balopat** [comment]
cc @tejal29

**Comment by saturnism** [comment]
quick ping on this one. We are starting a new project, and the global default repo is not helping us to expand easily.

**Comment by zhuzeng** [comment]
Yes the global default repo is definitely causing us some debugging time and only find out it's not any mis-configurations in the project itself.

**Comment by tejal29** [comment]
Thanks @saturnism. This is on our team's radar. Bumping priority to p1.

**Comment by dgageot** [comment]
This is still on the roadmap!

**Comment by MarlonGamez** [comment]
Hi! It's been a while since we've updated on this. Recently we've been talking about what we want to do with default-repo, as its functionality is currently confusing for a lot of users. I believe we're trying to hammer out those issues before we prioritize this, but we're definitely still looking into this :)

**Comment by yhrn** [comment]
Any updates on this? Being able to control this via profiles would be very beneficial for us.

We have multi artifact cases where artifact A needs to go to repo 1 for profile dev/repo 2 for profile prod and artifact B needs to go to repo 3 for profile dev/repo 4 for profile prod. In these cases the command line arg won't work at all and I can't come up with a reasonably good workaround at all.

**Comment by tejal29** [comment]
Currently, we don't have plans to support this in v1, v2 skaffold config.
However, the team is in midst of re-designing  v3 skaffold and this is an interesting use case

**Comment by tejal29** [comment]
Refer https://github.com/GoogleContainerTools/skaffold/issues/5857 for v3 config tracking issue

**Comment by dhodun** [comment]
Interested in this as well. We recently removed the need for namespaces in our app which gave us a lot of flexibility to point skaffold at per-developer and per-PR namespaces. Would be cool to have the same flexibility at the project / cluster / gcr level.

**Comment by tejal29** [comment]
Thanks @dhodun We will definitely share stuff internally once we have v3 schema ready

**Comment by damlys** [comment]
Totally agree. It would be very useful:

```yaml
build:
  artifacts:
    - image: myapp
      docker:
        dockerfile: build/myapp/Dockerfile
profiles:
  - name: dev
    deploy:
      defaultRepo: 127.0.0.1:5000             <---
      kubeContext: minikube
      kustomize:
        defaultNamespace: default
        paths:
          - deploy/myapp/overlays/dev
```

**Comment by theodiem** [comment]
Missing the mentioned funcionality and please include at least `multi-level-repo` also. Allows to:
```
build:
  artifacts:
    - image: myapp/frontend
      docker:
        dockerfile: build/myapp/Dockerfile.frontend
    - image: myapp/backend
      docker:
        dockerfile: build/myapp/Dockerfile.backend
profiles:
  - name: dev
    deploy:
      multi-level-repo: true                       <---
      defaultRepo: 127.0.0.1:5000             <---
```
I find very odd that there's global options that you can't configure in a config file and have the globals as an override instead (similar to env vars).
