### ISSUE TITLE
kubectl deploy URL manifests not working as expected

### ISSUE THREAD

**Issue by braderhart** [GoogleContainerTools/skaffold#2322]
### Expected behavior
According to https://github.com/GoogleContainerTools/skaffold/pull/1408, a URL for a `kubectl` manifest should work

### Actual behavior
```
WARN[0000] https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.5/aws-k8s-cni.yaml did not match any file
```

### Information

- Skaffold version: v0.32.0 & v0.31.0
- Operating system: Arch 5.1.12-arch1-1-ARCH
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config

deploy:
  kubectl:
    manifests:
    - https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.5/aws-k8s-cni.yaml
```

### Steps to reproduce the behavior

1. `skaffold deploy`
2. Get the following error:

```
Starting deploy...
kubectl client version: 1.15
WARN[0000] https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.5/aws-k8s-cni.yaml did not match any file 
Deploy complete in 65.696914ms
```

**Comment by dgageot** [comment]
Hi @braderhart, you should use this config:

```
apiVersion: skaffold/v1beta11
kind: Config

deploy:
  kubectl:
    remoteManifests:
    - https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.5/aws-k8s-cni.yaml
```
