### ISSUE TITLE
skaffold run failing 

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#2330]
Skaffold run fail's after upgrade

### Expected behavior
Should build and deploy 
### Actual behavior
But skaffold fails with following error

> FATA[0000] creating runner: invalid skaffold config: only one element in set dockerSecret can be set. got Path and SecretName

### Information

```
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: someurl
    context: .
    kaniko:
      buildContext:
        localDir: {}
  cluster:
    namespace: prashant
    dockerConfig:
      path: C:\Users\prashant\.docker\config.json
deploy:
  kubectl:
    manifests:
      - deploy.yml

```
### Steps to reproduce the behavior

1. Use latest skaffold and run with above yaml.

looks like 

> Path string `yaml:"path,omitempty" yamltags:"oneOf=dockerSecret"`

is the culpit
