### ISSUE TITLE
only one element in set deploy can be set

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#2334]
### Expected behavior
This worked in previous versions I believe. And it is a good feature.

I was using it do deploy extra yaml not included in Helm Chart. In my case I'm using kubectl to add a Istio VirtualService yaml for keycloak since its not in Helm chart.

### Actual behavior 
```
$ skaffold deploy
time="2019-06-25T16:41:53+01:00" level=fatal msg="creating runner: invalid skaffold config: only one element in set deploy can be set. got HelmDeploy and KubectlDeploy"
```

### Information

- Skaffold version: version. v0.32.0
- Operating system: windows
Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
deploy:

  helm:
    releases:
      - name: keycloak
        chartPath: codecentric/keycloak
        skipBuildDependencies: true

  kubectl:
    manifests:
      - other/*.yaml
```

### Steps to reproduce the behavior

1. skaffold deploy
