### ISSUE TITLE
skaffold dev with kustomize doesn't pick up patchesStrategicMerge changes

### ISSUE THREAD

**Issue by reegnz** [GoogleContainerTools/skaffold#2344]
### Expected behavior

When I use a kustomize v2.x manifest, skaffold dev should pick up changes to any of the changes to files kustomize is working with.

### Actual behavior

If I am using patchesStrategicMerge the changes to the patches aren't picked up.
If I use 1.x format (patches) the patch changes are picked up by skaffold dev properly.

### Information

- Skaffold version: v0.32.0
- Operating system: MacOS Mojave 10.14.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: my-image
deploy:
  kustomize:
    path: deployment
```

### Steps to reproduce the behavior

1. create a basic deployment
2. add a kustomize.yaml
3. create a strategic merge patch file to patch the deployment
4. add the patch with kustomize cli:
```
kustomize edit add patch thepatch.yaml
```
This creates a patchesStrategicMerge entry in the kustomization file
5. Run skaffold dev
6. Change the patch
7. Observe that no new deployment is made.

Why this change is important is because patches is deprecated since 2.0 in favour of patchesStrategicMerge.
