### ISSUE TITLE
UNAUTHORIZED authentication required as of 0.32.0

### ISSUE THREAD

**Issue by hach-que** [GoogleContainerTools/skaffold#2355]
### Expected behavior

`skaffold dev` should work like it does in `0.31.0`.

### Actual behavior

`skaffold dev` outputs (hidden the GCP project name):

```
time="2019-06-26T12:12:28-07:00" level=fatal msg="watching files for artifact gcr.io/<HIDDEN>/migrator: listing files: listing files: listing copied files: retrieving image config: getting image: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/baseline Type:repository]]"
2019/06/26 12:12:28
```

### Information

- Skaffold version: version 0.32.0
- Operating system: Windows
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta7
kind: Config
build:
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: gcr.io/<HIDDEN>/admin
      context: .
      docker:
        dockerfile: build/kubernetes/admin.Dockerfile
    - image: gcr.io/<HIDDEN>/aggregator
      context: .
      docker:
        dockerfile: build/kubernetes/aggregator.Dockerfile
    - image: gcr.io/<HIDDEN>/billing
      context: .
      docker:
        dockerfile: build/kubernetes/billing.Dockerfile
    - image: gcr.io/<HIDDEN>/relay-ingress
      context: .
      docker:
        dockerfile: build/kubernetes/relay_ingress.Dockerfile
    - image: gcr.io/<HIDDEN>/relay-database
      context: .
      docker:
        dockerfile: build/kubernetes/relay_database.Dockerfile
    - image: gcr.io/<HIDDEN>/server-ingress
      context: .
      docker:
        dockerfile: build/kubernetes/server_ingress.Dockerfile
    - image: gcr.io/<HIDDEN>/server-database
      context: .
      docker:
        dockerfile: build/kubernetes/server_database.Dockerfile
    - image: gcr.io/<HIDDEN>/matcher
      context: .
      docker:
        dockerfile: build/kubernetes/matcher.Dockerfile
    - image: gcr.io/<HIDDEN>/migrator
      context: .
      docker:
        dockerfile: build/kubernetes/migrator.Dockerfile
        target: dev_target
    - image: gcr.io/<HIDDEN>/optimizer
      context: .
      docker:
        dockerfile: build/kubernetes/optimizer.Dockerfile
    - image: gcr.io/<HIDDEN>/router
      context: .
      docker:
        dockerfile: build/kubernetes/router.Dockerfile
    - image: gcr.io/<HIDDEN>/counters
      context: .
      docker:
        dockerfile: build/kubernetes/counters.Dockerfile
    - image: gcr.io/<HIDDEN>/near
      context: .
      docker:
        dockerfile: build/kubernetes/near.Dockerfile
    - image: gcr.io/<HIDDEN>/ip2location
      context: .
      docker:
        dockerfile: build/kubernetes/ip2location.Dockerfile
        target: dev_runtime
    - image: gcr.io/<HIDDEN>/udp
      context: .
      docker:
        dockerfile: build/kubernetes/udp.Dockerfile
    - image: gcr.io/<HIDDEN>/connhack
      context: .
      docker:
        dockerfile: build/kubernetes/connhack.Dockerfile
    - image: gcr.io/<HIDDEN>/waiter
      context: .
      docker:
        dockerfile: build/kubernetes/waiter.Dockerfile
    - image: gcr.io/<HIDDEN>/configstore
      context: .
      docker:
        dockerfile: build/kubernetes/configstore.Dockerfile
    - image: gcr.io/<HIDDEN>/configstore-dashboard
      context: .
      docker:
        dockerfile: build/kubernetes/environments/dev/configstore-dashboard.Dockerfile
      sync:
        services/configstore/src/server-ui/src/***/*: src
    - image: <HIDDEN>-dashboard
      context: .
      docker:
        dockerfile: build/kubernetes/environments/dev/dashboard.Dockerfile
      sync:
        services/dashboard/<HIDDEN>/src/***/*: src
    - image: <HIDDEN>-gcloud-firestore
      context: .
      docker:
        dockerfile: build/kubernetes/environments/dev/gcloud-firestore.Dockerfile
    - image: <HIDDEN>-dataflow-local
      context: .
      docker:
        dockerfile: build/kubernetes/environments/dev/dataflow-local.Dockerfile
    - image: <HIDDEN>-relay
      context: .
      docker:
        dockerfile: build/kubernetes/environments/dev/relay.Dockerfile
    - image: <HIDDEN>-server
      context: sdk-v2
      docker:
        dockerfile: .dockerfiles/server
    - image: <HIDDEN>-selfregister-relay
      context: .
      docker:
        dockerfile: build/kubernetes/environments/dev/selfregister-relay.Dockerfile
    - image: <HIDDEN>-selfregister-server
      context: .
      docker:
        dockerfile: build/kubernetes/environments/dev/selfregister-server.Dockerfile
deploy:
  kustomize:
    path: build/kubernetes/environments/dev
```

### Steps to reproduce the behavior

1. Upgrade to 0.32.0.
2. Find out you can't run `skaffold dev` any more without it complaining about authorization or something.

### Workaround

Downgrade with `choco uninstall -y skaffold; choco install -y skaffold --version 0.31.0 --force`.
