### ISSUE TITLE
Kaniko build returned success after building only one of two images

### ISSUE THREAD

**Issue by tbarrella** [GoogleContainerTools/skaffold#2358]
### Expected behavior
`skaffold build` builds and pushes two images using Kaniko, or exits with failure if either build fails
### Actual behavior
Only one image was built but `skaffold build` still returned 0. Build output:
```
time="2019-06-26T22:05:21Z" level=warning msg="The additionalFlags field in kaniko is deprecated, please consult the current schema at skaffold.dev to update your skaffold.yaml."
time="2019-06-26T22:05:22Z" level=warning msg="The additionalFlags field in kaniko is deprecated, please consult the current schema at skaffold.dev to update your skaffold.yaml."
ERROR: logging before flag.Parse: E0626 22:09:41.534397   97795 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=29, ErrCode=NO_ERROR, debug=""
ERROR: logging before flag.Parse: E0626 22:09:41.534399   97795 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=29, ErrCode=NO_ERROR, debug=""
Generating tags...
 - image1 -> image1:f3e59271c8b-dirty
 - image2 -> image2:f3e59271c8b-dirty
Tags generated in 2.783261496s
Starting build...
Creating kaniko secret [kaniko-secret]...
Creating docker config secret [docker-cfg]...
Building [image1]...
Storing build context at /tmp/context-0e76ebf52a4ef4613296bcd3ca1c6529.tar.gz
... (build logs for image1)
Complete in 4m25.254702191s
```
### Information

- Skaffold version: v0.32.0
- Operating system: Ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
profiles:
  - name: p
    build:
      artifacts:
        - image: image1
          kaniko:
            flags:
              - --reproducible
            buildArgs:
              key: value
            buildContext:
              localDir: {}
        - image: image2
          kaniko:
            flags:
              - --reproducible
            dockerfile: Dockerfile.two
            buildArgs:
              key: value2
            buildContext:
              localDir: {}
      cluster:
        namespace: n
        timeout: 50m
        dockerConfig: {}
        resources:
          limits:
            cpu: 1000m
            memory: 8G
    deploy:
      kustomize:
        path: p
```

### Steps to reproduce the behavior
(not sure if easily reproducible)
