### ISSUE TITLE
sync to compeleted job fails, terminating the rest of the sync

### ISSUE THREAD

**Issue by MarkBennett** [GoogleContainerTools/skaffold#2360]
### Expected behavior

Given I've got a few pods running in my cluster and using the same build (such as Rails webserver, worker, and rspec job), then when I make a change to synced file skaffold to restart the job rather than try to sync files to a completed/terminated pod. Alternatively, as a less ideal outcome skaffold could ignore the completed job and not do anything.

### Actual behavior

Currently, if I make a change to a synced file then skaffold will try to sync it to all pods using the build, including jobs which have completed. When trying to exec into a completed pod this error is generated:

```
WARN[2020] Skipping deploy due to sync error: copying files: Running [kubectl exec dev-run-specs-kfqfs --namespace default -c run-specs -i -- tar xmf - -C / --no-same-owner]: stdout , stderr: error: canno
t exec into a container in a completed pod; current phase is Succeeded
, err: exit status 1: exit status 1
```

### Information

- Skaffold version: v0.31.0
- Operating system: Mac OS 10.14.5
- Cluster: Minikube v1.1.1
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image:  gcr.io/litdistco-pro/litdistco-rails
      docker:
        cacheFrom:
          - gcr.io/litdistco-pro/litdistco-rails 
  googleCloudBuild:
    projectId: litdistco-pro
deploy:
  kustomize:
    path: k8s/overlays/production
profiles:
  - name: dev
    build:
      artifacts:
      - image:  gcr.io/litdistco-pro/litdistco-rails
        docker:
          target: developer
        sync:
          manual:
            - src: 'app/**'
              dest: /project
      local: {}
    deploy:
      kustomize:
        path: k8s/overlays/development
    activation:
      - command: dev
  - name: staging
    build:
      artifacts:
      - image:  gcr.io/litdistco-pro/litdistco-rails
        docker:
          target: developer
      local: {}
    deploy:
      kustomize:
        path: k8s/overlays/staging
```

### Steps to reproduce the behavior

1. Create `skaffold.yaml` which uses `build.artificats.sync` and deploys to both a pod and a job.
2. Start development with `skaffold dev`
3. Change a synced file.
4. `skaffold dev` fails to sync changed files to pods as running `exec` in the terminated job seems to abort the entire sync.

Note, I realize I'm running the previous version of `skaffold` but I've got a multistage build and can't build on v0.32.0 until #2340 is merged into the latest version.
