### ISSUE TITLE
Sync does not work because the image string is not match

### ISSUE THREAD

**Issue by yoshwata** [GoogleContainerTools/skaffold#2366]
### Expected behavior
Sync works properly.

### Actual behavior
Sync do not work by this error.
```
Watching for changes every 1s...
Syncing 1 files for docker.io/yoshwata/yoshwata_test-file-sync:v0.32.0-86-g6bcaa54e-dirty@sha256:54d89670d4c20a49f0f03b3608a1766bea59f84d2b210a94b63c5080e1b6d8fd
WARN[0040] Skipping deploy due to sync error: copying files: didn't sync any files
Watching for changes every 1s...
```

### Information

- Skaffold version: 
```
$ skaffold version
v0.32.0-100-g5be1fa24
```
- Operating system: ...
mac OS Mojave 10.14.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: yoshwata/test-file-sync
    context: .
    sync:
      manual:
      - src: 'foo'
        dest: /
deploy:
 kubectl:
   manifests:
   - deployment.yaml
```

- Workaround
The workaround is this [PR](https://github.com/GoogleContainerTools/skaffold/pull/2365).
I find that image string of skaffold includes sha, but `Spec.Containers.Image` does not have sha.

### Steps to reproduce the behavior

1. execute `skaffold dev --default-repo docker.io/yoshwata`
2. modify local file `foo`
