### ISSUE TITLE
cancel googleCloudBuild on SIGINT

### ISSUE THREAD

**Issue by giladsh1** [GoogleContainerTools/skaffold#2376]
### Expected behavior
When supplying Ctrl + C (SIGINT) to the `skaffold run` command with googleCloudBuild builder, skaffold should cancel the builds in the cloud.
### Actual behavior
skaffold crashes and returns an error  -
```
getting logs: unknown error: Get https://storage.googleapis.com/riscale_cloudbuild/log-<log-hash>.txt: context canceled
```
### Information

- Skaffold version: v0.31.0
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: eu.gcr.io/example-project/example-service
      context: example-service
      docker:
        dockerfile: Dockerfile-dev
        buildArgs:
          ENVIRONMENT: ""

profiles:
  - name: local-dev
    build:
      local:
        push: false
    activation:
      - kubeContext: minikube
    deploy:
      kubectl:
        manifests:
          - k8s/local/**

  - name: gke-test
    build:
      googleCloudBuild:
        projectId: example-project
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Dockerfile
      - op: replace
        path: /build/artifacts/0/docker/buildArgs/ENVIRONMENT
        value: demo
    deploy:
      kubectl:
        manifests:
          - k8s/gke/**
```

### Steps to reproduce the behavior
1. run - `skaffold run -p  gke-test` and hit Ctrl+C in the middle of the run.
2. watch skaffold's logs and cloud build status.
