### ISSUE TITLE
Support kaniko builder in googleCloudBuild

### ISSUE THREAD

**Issue by ptone** [GoogleContainerTools/skaffold#2377]
### Expected behavior

Set gcr.io/kaniko-project/executor:latest as the builder image in cloud build

### Actual behavior

Status: Downloaded newer image for gcr.io/kaniko-project/executor:latest
Error: unknown flag: --tag

### Information

- Skaffold version: version...

v0.32.0

- Operating system: ...

OSX Mojave

- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: gcr.io/ptone-kf/auth-client
  googleCloudBuild:
    timeout: 600s
    dockerImage: gcr.io/kaniko-project/executor:latest
deploy:
  kubectl:
    flags:
      global:
        - --namespace id-namespace
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

Run with a builder config as in the yaml above
