### ISSUE TITLE
Sync not working with profiles

### ISSUE THREAD

**Issue by gaetansnl** [GoogleContainerTools/skaffold#2407]
### Expected behavior
I expect sync to work when it's configured in a profile
### Actual behavior
Skaffold trigger full rebuild

### Information

- Skaffold version: 0.33.0
- Operating system: Windows 10

### Steps to reproduce the behavior

1. Sync Working
```
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: ********************
      context: .
      sync:
        'packages/server/***': ./
      docker:
        target: server-dev
        dockerfile: ./k8s/image/Dockerfile
  local:
    useBuildkit: true
deploy:
  kustomize:
    path: ./k8s/env-specific/internal-dev
```
2. Sync not working (skaffold trigger full rebuild)
```
apiVersion: skaffold/v1beta7
kind: Config
profiles:
  - name: dev
    build:
      artifacts:
        - image: ***************
          context: .
          sync:
            'packages/server/***': ./
          docker:
            target: server-dev
            dockerfile: ./k8s/image/Dockerfile
      local:
        useBuildkit: true
    deploy:
      kustomize:
        path: ./k8s/env-specific/internal-dev

```
