### ISSUE TITLE
Port forwarding not work when pods recreated

### ISSUE THREAD

**Issue by cheung-chifung** [GoogleContainerTools/skaffold#2408]
I'm making a simple golang app and trying to use skaffold for local development with`skaffold dev --port-forward`.

However, it only works for the first time, then fails to open ports again when files changed and pods recreated. I even tried v0.33.0 and the latest version `2f2a6f4`, neither works.

I checked issue  #1594 #1815 and tried v0.29.0, and it works as I expected.

I notice that when I use v0.33.0, every time I changed files, skaffold will start a new pod then exit (delete?) the old one, but when I use v0.29.0, only the new one starts, and there is no exit log. So I guess is the old one blocks port-forward somehow since v0.29.0

### Expected behavior

Recreate port forwarding correctly just like v0.29.0 did.

### Actual behavior

Only successful for the first time.

### Information

- Skaffold version: v0.33.0
- Operating system: MacOSX 10.14.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
    - image: api
      context: ./api/
deploy:
  kubectl:
    manifests:
      - ./manifests/*
profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
        command: dev
```

### Steps to reproduce the behavior

1. use minikube and v0.33.0, checkout a minimal app with service and deployment only.
2. run `skaffold dev --port-forward`, can see port-forward works for the first time.
3. change the source codes, trigger the pod recreate.
4. from the logs, you can see skaffold starts a new pod with a different name with the old one, which will be deleted after the new one started listening on the port.
5. stop skaffold and rerun the same command `skaffold dev --port-forward`, it works again.
