### ISSUE TITLE
The deployed pod did not deleted in 'dev' option

### ISSUE THREAD

**Issue by jaredbark** [GoogleContainerTools/skaffold#2412]
### Expected behavior
The deployed pod should be deleted when stopping the process which launched in 'dev' option

### Actual behavior
The deployed pod did not deleted from the cluster.

Log
DEBU[0025] Running command: [helm --kube-context eks-dev-cluster delete configmgmt --purge]
release "configmgmt" deleted
Cleanup complete in 3.989216938s
FATA[0029] exiting dev mode because first deploy failed: deploying configmgmt: exit status 1

### Information

- Skaffold version: a43cf56
- Operating system: CentOS 7
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:0.1"
  artifacts:
  - image: XXX
    jibMaven:
      args:
      - -DskipTests=true
deploy:
  helm:
    releases:
    - name: configmgmt
      namespace: devel
      version: 0.1
      chartPath: pod
      valuesFiles:
      - ./pod/values.yaml
      - ../../globalvalues/globalvalues.yaml
      values:
        image: XXX
    flags:
      install: ["--name=configmgmt", "--tiller-namespace=devel", "--namespace=devel"]
```

### Steps to reproduce the behavior

1. Set flags with contents of skaffold.yaml above.
2. Execute 'skaffold dev -f skaffold.yaml'.
3. Stop the process by Ctrl-C.
4. The deployed pod did not deleted from the cluster.
