### ISSUE TITLE
feature request: support forcing a context and a namespace for a profile / command

### ISSUE THREAD

**Issue by giladsh1** [GoogleContainerTools/skaffold#2426]
It would be awesome if skaffold will support forcing a kube context and/or namespace for a specific profile and/or command. 
For example, when running the `skaffold dev` command make sure the current context is Minikube or otherwise exit with error. 

I suggest adding to the `deploy` section the following keys - 
```yaml
deploy:
  forceKubeContext: minikune
  forceKubeNamespace: stage
  kubectl:
    manifests:
      - k8s/**
```

We use skaffold to develop and deploy applications with Minikube and GKE.
Unfortunately, users often forget to switch contexts before running skaffold commands, and can accidentally deploy to the wrong cluster. 
Although this could be achieved with a wrapper, I would rather use the native skaffold command and not create a custom script which may interrupt with some built-in features (such as file watchers).
