### ISSUE TITLE
How deploy with multi repositories of the microservices

### ISSUE THREAD

**Issue by sergeytkachenko** [GoogleContainerTools/skaffold#2448]
I have 20 repositories of the one business product.
Each microservice is in a separate repository.
What is the right approach to deploying in such an infrastructure using scaffold?

**Comment by nkubala** [comment]
one way you could do this is by cloning the repositories locally under a single parent directory, and then placing your skaffold.yaml in the top level of the parent directory. your skaffold.yaml can have an artifact per microservice, and the artifact workspace can point to the subdirectory containing the cloned repository corresponding to that microservice.

the directory structure can look something like
```
├── skaffold.yaml
├── repo_1
|   ├── service_1.go
│   └── k8s-service1.yaml
├── repo_2
|   ├── service_2.go
│   └── k8s-service2.yaml
├── repo_3
|   ├── service_3.go
│   └── k8s-service3.yaml
```

and your skaffold.yaml:
```yaml
apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
    - image: gcr.io/project/service-1
      context: ./repo_1/
    - image: quay.io/service-2
      context: ./repo_2/
    - image: localhost:12345/service-3
      context: ./repo_3/
deploy:
  kubectl:
    manifests:
      - ./repo_1/k8s-*
      - ./repo_2/k8s-*
      - ./repo_3/k8s-*
```

then just run `skaffold dev` from the top level. hope this helps!

**Comment by balopat** [comment]
Hi @sergeytkachenko - I wonder if @nkubala's answer worked for you or not?

**Comment by sergeytkachenko** [comment]
@balopat @nkubala 
Thank you for answer.

**Comment by LeoDupont** [comment]
@nkubala But this means we have to clone the repo which contains the `skaffold.yaml` file elsewhere and then copy and paste it in this handmade directory structure?

**Comment by tstromberg** [comment]
@balopat - this question seems answered. Is there something else to do?

**Comment by nkubala** [comment]
@LeoDupont unfortunately yes, and I agree that this approach is less than satisfactory.

just wanted to give an update from the team here: we're actively working on a design to support grouping artifacts into "modules", and allowing parent skaffold.yaml configuration to make references to these modules. there are several use cases we're trying to support, and multiple microservices in separate repositories is one of them. we'll be sure and share our design when it's ready to get feedback from you all.

**Comment by HofmannZ** [comment]
@nkubala That sounds great, anywhere I can find a spec draft? 🚀

**Comment by briandealwis** [comment]
We're still iterating over the draft, and hope to have something soon.

**Comment by balopat** [comment]
@HofmannZ here's the design doc: http://tinyurl.com/skaffold-modules, all comments are welcome!

**Comment by pie-r** [comment]
Interested on this topic

**Comment by gsquared94** [comment]
We've released this feature in v1.20.0. You can compose multiple `skaffold.yaml` files coming from different repositories together and run them. The docs are [here](https://skaffold.dev/docs/design/config/#configuration-dependencies). 

Either:
- clone all repositories manually and reference the local paths in the main `skaffold.yaml` ([example](https://github.com/gsquared94/bank-of-anthos-demo)) ; or
- reference the git repositories directly and skaffold will download and manage them. ([example](https://github.com/gsquared94/skaffold-remote-configs-demo))

**Comment by realArcherL** [comment]
Would this work for repositories that are private? Like GitHub private repositories?

**Comment by walter-developer** [comment]
@gsquared94 

Great functionality, congratulations, however I found a bug, I'm using version

API version: skaffold/v4beta13

and it only works for the first included file, it doesn't build anything from the second included file.

```
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: skff-main 
    
requires:
  
  - path: ./skff/infra.skff.yaml
    configs: ["skff-infra"]

  - path: ./skff/deploy.skff.yaml
    configs: ["skff-deploy"]
```
