### ISSUE TITLE
When pruning images, Skaffold removes images that were created by Docker Compose

### ISSUE THREAD

**Issue by jpetazzo** [GoogleContainerTools/skaffold#2464]
### Expected behavior

Skaffold leaves my existing images alone.

(To clarify, I'm talking about images stored in my local Docker Engine.)

### Actual behavior

Skaffold removes images that I've built with Docker Compose. This defeats the build cache that I use with my other tools.

Note: it doesn't remove images that I've built manually (with `docker build`) but it does remove images that I've built with `docker-compose build`.

### Information

- Skaffold version: v0.33.0
- Operating system: Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: localhost:30000/hasher
    context: hasher
  - image: localhost:30000/rng
    context: rng
  - image: localhost:30000/webui
    context: webui
  - image: localhost:30000/worker
    context: worker
deploy:
  kubectl:
    manifests:
    - kubercoins/hasher-deployment.yaml
    - kubercoins/hasher-service.yaml
    - kubercoins/redis-deployment.yaml
    - kubercoins/redis-service.yaml
    - kubercoins/rng-daemonset.yaml
    - kubercoins/rng-service.yaml
    - kubercoins/webui-deployment.yaml
    - kubercoins/webui-service.yaml
    - kubercoins/worker-deployment.yaml
```
(This file was created by `skaffold init`.)

### Steps to reproduce the behavior

1. Use Compose for local development.
2. Run `skaffold dev`.
3. Wait for Skaffold to build+run all the things.
4. Stop Skaffold (I used Ctrl-C).
5. Watch as Skaffold prunes its images.
6. Check with `docker images` that the images previously built by Compose are gone.

I suppose I can work around the bug by running `skaffold dev --no-prune` or setting the env var `SKAFFOLD_NO_PRUNE`. Or maybe there is also a way to do that in the Skaffold configuration file?

By the way, what's the rationale for pruning the images? I couldn't find an explanation why.

Thank you!
