### ISSUE TITLE
Artifacts syntax could look more alike docker-compose syntax

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#247]
Skaffold syntax:

```
artifacts:
- imageName: domain/image
  workspace: ./src
  dockerfilePath: Dockerfile
```

Docker-compose syntax for the same thing:

```
services:
- image: domain/image
  context: ./src
  dockerfile: Dockerfile
```

By using the same syntax, we'd help some developers learn skaffold quicker.
