### ISSUE TITLE
filesync loop

### ISSUE THREAD

**Issue by japsen** [GoogleContainerTools/skaffold#2472]
### Expected behavior
When changing a file in a synced folder; it should be synced to the running pod **only once** per edit+save. 

### Actual behavior
It looks like skaffold is getting stuck in a sync loop. 
```
Syncing 1 files for eu.gcr.io/reponame ......
Syncing 1 files for eu.gcr.io/reponame ......
Syncing 1 files for eu.gcr.io/reponame ......
Syncing 1 files for eu.gcr.io/reponame ......
Syncing 1 files for eu.gcr.io/reponame ......
...... endless, with ~ 1sec wait between each line....
```
Not sure if it's relevant, but if I stop the process I get the following message just before cleaning up && pruning:
`time="2019-07-15T15:32:26+02:00" level=warning msg="Skipping deploy due to sync error: copying files: starting command &{/Users/MY_USERNAME/google-cloud-sdk/bin/kubectl [kubectl exec POD_ID --namespace default -c PRODUCT_NAME -i -- tar xmf - -C / --no-same-owner] []  0xc000010bb8 0xc0003fa708 0xc0003fa718 [] <nil> <nil> <nil> 0xc000aa4100 <nil> false [] [0xc0003fa708 0xc0003fa718] [0xc0003fa700 0xc0003fa710] [] <nil> <nil>}: context canceled"`

(some names replaced with uppercase values)

### Information

- Skaffold version: fe68372      (It does work as expected in v0.33.0)
- Operating system: Mac OS, pyCharm with google code plugin. 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta12
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: eu.gcr.io/reponame
    context:
    sync:
      manual:
      - src: 'syncedFolderName/**/*'
        dest: /
    docker:
      dockerfile: syncedFolderName/path/to/relevant/Dockerfile
  local:
    useDockerCLI: true
    useBuildkit: false
deploy:
  kubectl:
    manifests:
    - syncedFolderName/docker/kubernetes-manifests/*.yaml


```

### Steps to reproduce the behavior

1. Run the above config from pycharm Google Code > Kubernetes Continuous Deploy, which in fact runs the following command:
`skaffold dev --filename syncedFolderName/docker/skaffold.yaml --label ide=PyCharmCore --label ideVersion=2019.1.3.0.0 --label ijPluginVersion=unknown --port-forward=true
`
2. Edit a file in the synced folder and save it. 
3. Console output will be filled with a continuous stream of Syncing 1 file messages.
