### ISSUE TITLE
Skaffold fails to sync with helm and non root user

### ISSUE THREAD

**Issue by igoooor** [GoogleContainerTools/skaffold#2479]
### Expected behavior

Skaffold using Helm should sync files when using sync.manual configuration even with a non root container's running user.

### Actual behavior

Sync fails when the container is ran by a non root user.
It works though if the user of the Dockerfile is not changed (i.e. is root)

### Information

- Skaffold version: v0.33.0
- Operating system: mac os 10.14.5
- Minikube v1.2.0
- Kubernetes v1.12.8
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta12
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-helm
    sync:
      manual:
        - src: "static/**"
          dest: "/usr/share/nginx/html/"
          strip: "static/"

deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: skaffold-helm
      values:
        image: gcr.io/k8s-skaffold/skaffold-helm
```

### Steps to reproduce the behavior

1. I've used the "helm-deployment" example from this repository
2. I've changed the Dockerfile with the following content:

```
FROM php:7.2-fpm-alpine
COPY static /usr/share/nginx/html/
USER www-data
CMD ["php-fpm"]
```

3. run the command `skaffold dev`
4. update the content of the file `static/index.html`
5. a. When the sync tries to overwrite an existing file, following error appear:

```
WARN[0025] Skipping deploy due to sync error: copying files: Running [kubectl exec skaffold-helm-6c4fc489bc-2dhbb --namespace default -c skaffold-helm -i -- tar xmf - -C / --no-same-owner]: stdout , stderr: tar: Removing leading `/' from member names
tar: usr/share/nginx/html/index.html: Cannot open: File exists
```

5. b. When the sync tries to create a new file/directory, following error appear:

```
tar: usr/share/nginx/html/static: Cannot mkdir: Permission denied
```

If you remove the line `USER www-data` from the Dockerfile, everything works as expected.
