### ISSUE TITLE
Passing flags to kustomize

### ISSUE THREAD

**Issue by daddz** [GoogleContainerTools/skaffold#2488]
### Expected behavior
I would like to pass a flag to the `kustomize build` call that skaffold uses but I can't find an option to do so.
The flag I try to pass in this case is `--load_restrictor none`.

### Actual behavior
Existing flags in `skaffold.yaml` are ignored when calling `skaffold dev/deploy`
Log: `DEBU[0001] Running command: [kustomize build ./k8s/test/] `
### Information

- Skaffold version: v0.33.0
- Operating system: Linux
- Contents of skaffold.yaml:

```yaml
deploy:
  kustomize:
    path: ./k8s/test/
    flags:
      global:
        - "--load_restrictor none"
```
