### ISSUE TITLE
Integration tests with reduced privileges

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#2502]
Currently, integration tests always run with a user who has unconstrained privileges. This misses bugs that only manifest when a user has constrained privileges -- however enough privileges to reasonably expect a Skaffold run to succeed.

For example, https://github.com/GoogleContainerTools/skaffold/issues/2495 describes a problem which only manifests when a user cannot list deployments at cluster scope.

It would be good to have some integration tests run with a reduced set of privileges, to catch these kind of issues early.

---

A reasonable restriction would be edit rights in a _single_ namespace. This can be set up via [1]
```bash
kubectl config set-context reduced-privileges-context --user skaffold-test-user --cluster (..)
```
and define a `RoleBinding` in namespace `tbd` which references the default edit `ClusterRole`:
```yaml
   apiVersion: rbac.authorization.k8s.io/v1
   kind: RoleBinding
   metadata:
     name: skaffold-test-user
     namespace: tbd
   roleRef:
     apiGroup: rbac.authorization.k8s.io
     kind: ClusterRole
     name: edit
   subjects:
   - apiGroup: rbac.authorization.k8s.io
     kind: User
     name: default-user
     namespace: default
```
This new reduced-privileges-context can then be enabled with the new `--kube-context` flag.

Depends on https://github.com/GoogleContainerTools/skaffold/pull/2447

[1]: probably incomplete instructions
