### ISSUE TITLE
Helm deploy: difference between values and setValues parameters

### ISSUE THREAD

**Issue by george-oakling** [GoogleContainerTools/skaffold#2508]
Hi guys,
coud not find the difference between those two params - from my point of view, values and setValues does the same. How they differ?

**Comment by tejal29** [comment]
@george-oakling , the setValues as the documentation [here](https://skaffold.dev/docs/references/yaml/) mentions  is pumped into  to helm as `--set` flag.
```
setValues: {} | # | key-value pairs. If present, Skaffold will send --set flag to Helm CLI and append all pairs after the flag.
-- | -- | --

```

The `values` config can be list of images which will get resolved with the build output by skaffold. 
Meaning in the case below:
```
apiVersion: skaffold/v1beta12
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: skaffold-helm
      values:
        image: gcr.io/k8s-skaffold/skaffold-helm
```
The image value will be resolved to the digest of the image to the one built.
