### ISSUE TITLE
Port forwarding doesn't work anymore since update 0.33.0 -> 0.34.0

### ISSUE THREAD

**Issue by Bastorx** [GoogleContainerTools/skaffold#2523]
```
Sadly no error logs
```

### Expected behavior

Port fowarding should work

### Actual behavior

Port fowarding doesn't work

### Information

- Skaffold version: 0.34.0
- Operating system: MacOS 10.14.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - context: api
      image: eu.gcr.io/my-app/api
      sync:
        manual:
          - src: "src/**/*"
            dest: .
    - context: client
      image: eu.gcr.io/my-app/client
      sync:
        manual:
          - src: "src/**/*"
            dest: .
      docker:
        buildArgs:
          NODE_ENV: development
deploy:
  kubectl:
    manifests:
      - ./k8-manifests/client/*
      - ./k8-manifests/api/*
profiles:
  - name: api
    deploy:
      kubectl:
        manifests:
          - ./k8-manifests/api/*
  - name: client
    deploy:
      kubectl:
        manifests:
          - ./k8-manifests/client/*
portForward:
  - resourceType: service
    resourceName: my-app-service
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: my-app-client-service
    port: 8080
    localPort: 8080
```

### Steps to reproduce the behavior

1. Create a node/typescript project. Doesn't share sources. Try to forwards port.
2. `skaffold dev --port-forwarding`

Would like to know if others have this kind of issue since last update
