### ISSUE TITLE
Allow specifying an explicit image tag when '--default-repo' option is used

### ISSUE THREAD

**Issue by DKBgit** [GoogleContainerTools/skaffold#2528]
### Expected behavior
Skaffold to specify an explicit tag for an artifact image even when the '--default-repo' option is used. 

This is similar to [#1623](https://github.com/GoogleContainerTools/skaffold/issues/1623).
WORKS : 
If artifact image has an explicit tag (that includes the registry) _'[registry]/pytester2.test'_ and uses '_tagpolicy: sha256: {}'_ 
```
apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: local.insecure-registry.io/pytester2:test
    context: ./src
  insecureRegistries: ["local.insecure-registry.io"]
```

`skaffold build -o -q | grep "local.insecure"`
```
 - local.insecure-registry.io/pytester2:test -> local.insecure-registry.io/pytester2:test
Building [local.insecure-registry.io/pytester2:test]...
Successfully tagged local.insecure-registry.io/pytester2:test
The push refers to repository [local.insecure-registry.io/pytester2]
```

### Actual behavior
DOES NOT WORK:
If artifact image has an explicit tag _'pytester2.test'_ and uses _'tagpolicy: sha256: {}'_ and the '**_--default-repo local.insecure-registry.io'_** is passed in the command
```
apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: pytester2:test
    context: ./src
  insecureRegistries: ["local.insecure-registry.io"]
```

`skaffold build  --default-repo local.insecure-registry.io -o -q | grep "local.insecure"`
```
 - local.insecure-registry.io/pytester2_test -> local.insecure-registry.io/pytester2_test:latest
Building [local.insecure-registry.io/pytester2_test]...
Successfully tagged local.insecure-registry.io/pytester2_test:latest
The push refers to repository [local.insecure-registry.io/pytester2_test]
```
Note: the image is now stored as **'pytester2_test:latest'** instead of **'pytester2:test'**.

### Information

- Skaffold version: v0.34.0
- Operating system: Debian Stretch
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: pytester2:test
    context: ./src
  insecureRegistries: ["local.insecure-registry.io"]
```

### Steps to reproduce the behavior

1. Run skaffold build or skaffold dev with artifacts that have explicit tags and set the '--default-repo' option.

**Comment by dgageot** [comment]
Thank you @DKBgit for opening this issue.

Skaffold will always ignore the tag part of the images given in the skaffold.yaml. That's one of the main features of Skaffold: it will handle the tags for you.

One thing you can do is use the `EnvTemplateTagger` instead of the `sha256`. This way you have more control on the tags.
One thing we can do in Skaffold is print a warning to help the users figure that out.

**Comment by dgageot** [comment]
I removed the `kind/bug` since it works as expected. Even though it could be made clearer to the users.

**Comment by dgageot** [comment]
@DKBgit You are right that in some cases it is not ignored. But it should! That's a bug.
It fails for me and it works for you because you are working with a remote cluster and I'm working with a local cluster. That changes a bit how images are tagged and pushed.

I'm going to submit a PR to make sure tags in artifact image names are always an error.

What you can do is use the `EnvTemplateTagger` like this:

```
apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:test"
  artifacts:
  - image: pytester2
    context: ./src
  insecureRegistries: ["local.insecure-registry.io"]
```
