### ISSUE TITLE
kaniko build never finishes

### ISSUE THREAD

**Issue by daddz** [GoogleContainerTools/skaffold#2529]
### Expected behavior
Kaniko build finishes after uploading to registry.
### Actual behavior
The process never finishes after uploading the image to the registry.
I can see that the kaniko pod finished successfully but skaffold doesn't do anything after that.
The image is also successfully uploaded to the registry.

Tried with both `skaffold build -q > build_test.out` and `skaffold -v info --file-output build_test.out` and there's no info that shows any problem.

### Information

- Skaffold version: v0.34.0
- Operating system: Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  cluster: 
    namespace: kaniko-build
    # needed as workaround until https://github.com/GoogleContainerTools/skaffold/issues/2190 is fixed and released
    pullSecretName: docker-cfg
    # end workaround
    dockerConfig:
      secretName: docker-cfg
  artifacts:
  - image: my-registry/test-image
    kaniko:
      buildContext:
        localDir: {}
      cache:
        repo: my-registry/test-image/cache
      reproducible: true
```

### Steps to reproduce the behavior

1. `skaffold build` with above config
