### ISSUE TITLE
Multiple profiles - How to

### ISSUE THREAD

**Issue by lduparc** [GoogleContainerTools/skaffold#2535]
Hi all,

Skaffold documentation give option -p, --profile=[], but I'm not able to use multiple profiles. 
I've tried command like this : 

`skaffold deploy -p p1,p2`
`skaffold deploy -p p1 p2`
`skaffold deploy -p p1 -p p2`
`skaffold deploy --profile p1,p2`

but nothing is working. Can you give the way to use mutliple profile  and update documentation ?

Idea is to use a first profile de setup some config and the second one to override some config for a specific use case.

Thanks

**Comment by nkubala** [comment]
@lduparc your third option here should work: `skaffold deploy -p p1 -p p2`

can you try again and see if this works? and if not, what error you see? (along with your skaffold.yaml and OS/skaffold version info if possible)

**Comment by jl-ward** [comment]
I am also noticing that passing multiple profiles is not working as the documentation suggests.
https://skaffold.dev/docs/environment/profiles/
I am on version 1.0.1
Here is an example of a skaffold.yaml that can be used to verify:
```
apiVersion: skaffold/v1
kind: Config

profiles:
  - name: kafka
    deploy:
      helm:
        releases:
        - name: kafka
          namespace: kafka
          chartPath: bitnami/kafka
          remote: true
          version: 7.0.2
          valuesFiles:
            - yamls/kafka-values.yaml          
  - name: zookeeper
    deploy:
      helm:
        releases:
        - name: zookeeper
          namespace: zookeeper
          chartPath: bitnami/zookeeper
          remote: true
          version: 5.1.1
```
