### ISSUE TITLE
Skaffold should push the built image with the latest tag on GoogleCloudBuild for faster cached builds

### ISSUE THREAD

**Issue by Inkdpixels** [GoogleContainerTools/skaffold#2536]
### Expected behavior

Using skaffold with GoogleCloudBuild and a `cacheFrom` directive using the same image name, we expect skaffold to instruct GCB to push the built image not only with the `dirty-...` tag, but also with the `latest` tag so we can re-use the layers on consecutive builds.  

### Actual behavior

Skaffold instructs GoogleCloudBuild to push the built image with the `dirty` tag, but not with the `latest` one.

### Information

- Skaffold version: `v0.34.0`
- Operating system: `MacOS 10.14.5`
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: eu.gcr.io/my-project-id/my-image
    context: .
    docker:
      dockerfile: Dockerfile
      cacheFrom:
      - eu.gcr.io/my-project-id/my-image
  googleCloudBuild:
    projectId: my-project-id
```

### Steps to reproduce the behavior

1. Create a gcloud project
2. Adjust the values of the `skaffold.yml` (e.g. `my-project-id` and `my-image`)
3. Create a dockerfile with multiple layers
3. `skaffold dev`
4. Another `skaffold dev` so you can see that no layers are being re-used.

**Comment by iasinDev** [comment]
Hi, if you put

      cacheFrom:
      - eu.gcr.io/my-project-id/my-image

with latest:

      cacheFrom:
      - eu.gcr.io/my-project-id/my-image:latest

as long as you have a latest tag in the registry it would work right?

**Comment by Inkdpixels** [comment]
@iasinDev  The problem is that you have to manually push to the `:latest` tag each time a new image was built and pushed by skaffold, this is quite tedious. 

What I would suggest is that skaffold should take care of that (maybe enabled/disabled via a setting in the `skaffold.yml`) so each time skaffold builds and pushes a new image, it will also be pushed as the `latest` image, that way the developer can enjoy cached builds.

**Comment by tstromberg** [comment]
Raising the priority, both because of the reactions, and because this seems like something we should sort out sooner than later. Thank you for raising this issue!

**Comment by iasinDev** [comment]
> @iasinDev The problem is that you have to manually push to the `:latest` tag each time a new image was built and pushed by skaffold, this is quite tedious.
> 
> What I would suggest is that skaffold should take care of that (maybe enabled/disabled via a setting in the `skaffold.yml`) so each time skaffold builds and pushes a new image, it will also be pushed as the `latest` image, that way the developer can enjoy cached builds.

Yeah, that's the thing for that reason I downgraded to use Skaffold 0.20; this version makes the double tag, it creates the tag of the new version and at the same time tag the same image also with the latest tag, I don't know how and why in the last versions it has lost this behaviour (or maybe can be set but I don't know how)

**Comment by tejal29** [comment]
v0.20.0 fixes this because, skaffold created the build step with output as `artifact.ImageName` 
https://github.com/GoogleContainerTools/skaffold/blob/v0.20.0/pkg/skaffold/build/gcb/desc.go#L53

vs now, its tag computed for the artifact.
https://github.com/GoogleContainerTools/skaffold/blob/5a9227ce7dfd9709547d5d2c7ad9f896ee74bafc/pkg/skaffold/build/gcb/buildpacks.go#L62

The easy way would be add image name also to the same line

**Comment by briandealwis** [comment]
Skaffold v1.25.0 incorporates PR #5903, which allows Docker builds on GoogleCloudBuild to cache from the previous build by including the artifact image in the `cacheFrom`.
```
build:
  googleCloudBuild:
    projectId: k8s-skaffold
  artifacts:
  - image: skaffold-example
    docker:
      cacheFrom:
      - skaffold-example # replaced with tagged image
      - gcr.io/k8s-skaffold/skaffold-example:latest # used if the tagged image is not found
```

This change does require using a tag-policy that won't change between builds, like the misnamed `sha256` or an environment-based tag.

There are some subtleties involved in Docker image caching, particularly in the order in which images are provided, and this [StackOverflow answer](https://stackoverflow.com/q/54574821/600339) provides helpful details.

Closing this issue as fixed.

**Comment by andreacasarin** [comment]
Hello, sorry to bump this old one, but this change affected GitLab (and probably other systems) aswell. 

Previously I was able to specify `cacheFrom` with IMAGE:latest to be able to retrieve last built images for caching purposes, now you can't (or you'll need to push latest manually).

Is there any way to get the old behavior back? Maybe an optional tag?

Thanks!

**Comment by emilecaron** [comment]
Had the same issue.
If it can be of any use, I scripted the process of tagging artifact images again with `latest` tag and pushing them again

Get script here: https://gist.github.com/emilecaron/76f0a6816260bfc08d8edff0f8a8d245
Then add this extra step to your cloudbuild.yaml to run the script after `skaffold build` 

```
   - name: 'gcr.io/cloud-builders/docker'
     entrypoint: python3
     args:
       - skaffold-latest-repush.py
```
