### ISSUE TITLE
Allow kustomization folders as source for skaffold config

### ISSUE THREAD

**Issue by botwhytho** [GoogleContainerTools/skaffold#2542]
This is a follow up to the work done for https://github.com/GoogleContainerTools/skaffold/issues/2200

We are using `kustomize` to merge multiple `skaffold.yaml` files with great results. We have centralized remote bases with profiles activated by `kubeContext` which centralizes and simplifies some CI logic. We then apply patches at the repo level to specify things that are more repo-specific: build details, image name, number of artifacts, etc.

Right now in our CI, we have steps like the following:
```bash
kustomize build deploy/skaffold/ > skaffold.yaml
skaffold run
```

Ideally we'd like to only have to run:
```bash
skaffold run -f deploy/skaffold/
```
In this case skaffold would test if the string provided to the `-f|--filename` flag is either a compatible skaffold config or a folder that contains a kustomization, if the latter it would use the output of the kustomization as the skaffold config.

Not necessary but would also be useful if the same functionality works even if no `-f|--filename` flag is provided, so skaffold would first test a `skaffold.yaml` file in the current directory, then if none exists would test if the current directory contains a kustomization and proceed if the output is a valid skaffold config.

Considering a remote skaffold config can be provided by specifying a URL to the `-f` flag, skaffold should be flexible enough to accept kustomizations as a source for it's config.

**Comment by wstrange** [comment]
@botwhytho Would be interested in seeing a sample of how you combine multiple skaffold.yaml files with kustomize.

**Comment by balopat** [comment]
This is very interesting, but I'm not convinced yet that we can tackle everything with this. Also profiles seem to collide a bit with this direction. Can you share a little bit more about the structure of your project and examples of what your overlays/kustomizations are?

**Comment by botwhytho** [comment]
Hi, the idea behind the feature request is centralizing best practices and 'shared config' while keeping project/repo specific details where it belongs (in a specific repo). I think this works in tandem with profiles (and now yaml anchors, as I saw the merged PR), and not against it.

Currently we have a central repo that has some kustomize and scaffold config. We might have a base skaffold file similar to this one:
```yaml
apiVersion: skaffold/v1beta10
kind: Config
metadata:
  name: base-config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.ARTIFACT_PREFIX}}_{{.VERSION}}"

profiles:
- name: local-dev
  deploy:
    kustomize:
      path: kustomize/overlays/local

- name: dev
  activation:
  - kubeContext: dev_cluster_name
  deploy:
    kustomize:
      path: kustomize/overlays/dev

- name: staging
  activation:
  - kubeContext: staging_cluster_name
  deploy:
    kustomize:
      path: kustomize/overlays/staging

- name: prod
  activation:
  - kubeContext: prod_cluster_name
  deploy:
    kustomize:
      path: kustomize/overlays/prod
```

In down stream repos we might have a patch that specicies the project specific artifacts, that looks like this:
```yaml
- op: add
  path: /build/artifacts
  value:
    - image: gcr.io/service-name
      context: path/to/context
      docker:
        dockerfile: service.dockerfile
```

Skaffold would run as part of CI and because of profile activation (and previous CI steps not shown, that set the kubectl context) would automatically know where to deploy. In a bigger organization, NOT working off a mono-repo, centralizing such config and some conventions definitely makes sense and enables central, update-once, functionality.

Currently we have to run additional steps in CI like the one below, before running something like `skaffold run` which seem a bit hacky. I think that native support in skaffold would promote reuse of skaffold configs which I think is a good thing.
```
kustomize build skaffold/ > skaffold.yaml
skaffold run
```
For clarity, the `skaffold` folder above contains a `kustomization.yaml` file that would point to a remote base/resource like so:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- git@github.com:org-name/repo.git//kustomize/skaffold

patches:
- target:
    group: skaffold
    kind: Config
  path: patch-add-artifacts.yaml
```
