### ISSUE TITLE
config: Merge insecure registries for context and global?

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#2554]
The goal of this issue is to resolve the requirements around insecure registry configurations in the global config.

Given a global config such as
```yaml
global:
  insecure-registries:
  - allowed-globally.io
kube-contexts:
- name: my-context
  insecure-registries:
  - allowed-for-my-context.io
```

It is pretty clear that the allowed insecure registries is just `allowed-globally.io` when running
```bash
skaffold run --kube-context other-context  # -> allowed-globally.io
```

But what about:
```bash
skaffold run --kube-context my-context
```

Should that result in

1) only `allowed-for-my-context.io` (current behavior)
2) both `allowed-for-my-context.io` _and_ `allowed-globally.io`

Both options make sense, whereas option 2) seems more user-friendly to me. WDYT?
