### ISSUE TITLE
Fail-fast on environment variable not set

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#2562]
### Expected behavior

Fail fast if an environment variable is not set.

### Actual behavior

**\<no value\>** because `VERSION` environment variable is not set.

```
$ skaffold run
?[34mGenerating tags...?[0m
?[34m - eu.gcr.io/oceana-team/ip-office-poc -> ?[0meu.gcr.io/my-project/my-app:<no value>
```

_sometime later ... after jib build:_

**Invalid image reference: eu.gcr.io/my-project/my-app:<no value>**
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.4.0:build (default-cli) on project my-app: Invalid image reference eu.gcr.io/my-project/my-app:<no value>, perhaps you should check that the reference is formatted correctly according to https://docs.docker.com/engine/reference/commandline/tag/#extended-description
[ERROR] For example, slash-separated name components cannot have uppercase letters: Invalid image reference: eu.gcr.io/my-project/my-app:<no value>
```

### Information

- Skaffold version: v0.34.1
- Operating system: Windows 10 64-bit PC
- Contents of skaffold.yaml: 

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: eu.gcr.io/my-project/my-app
    context: ./app
    jibMaven:
      args:
      - -Djib.httpTimeout=300000
      - -Dmaven.test.skip=true
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.VERSION}}'
```

### Steps to reproduce the behavior

1. `skaffold run`
