### ISSUE TITLE
skaffold Build - custom command

### ISSUE THREAD

**Issue by lduparc** [GoogleContainerTools/skaffold#2578]
Regarding some constraints on our infrastructure, we need to use custom buildCommand but we don't know how to use it. We got an error on build and we need to add hosts to build command. I think it is not possible using docker stage, we have to use custom build. 

Can you give an example ?

See what we are doing : 

```
build:
  artifacts:
    - image: some.repository.com/image_name
      context: my/path/to/context/
      custom:
        buildCommand: "docker build -f Dockerfile --network my_custom_network --add-host some.host.com:XXX.XX.XXX.XXX --add-host other.host.com:10.XXX.XXX.XXX
        dependencies:
          dockerfile:
            path: Dockerfile
            buildArgs:
              ARG1: true
              ARG2: "some value"
              ARG3: 42

```

Error : 

```
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
FATA[0000] build failed: building [some.repository.com/image_name]: build artifact: building custom artifact: exit status 1
[ERROR] Skaffold build failed
{"builds":null}
```
