### ISSUE TITLE
Skaffold rebuild image for no obvious reason

### ISSUE THREAD

**Issue by gaetansnl** [GoogleContainerTools/skaffold#2583]
### Expected behavior

I expect skaffold to sync files without a full rebuild

### Actual behavior
File change trigger rebuild (sometimes) for no obvious reason. It works most of the time

### Information

- Skaffold version: v0.34.1
- Operating system: Windows 10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
profiles:
  - name: dev
    build:
      artifacts:
        - image: custom-registry/custom-repo/NAME_C-dev
          context: .
          sync:
            manual:
              - src: packages/NAME_C/**
                dest: ./
                strip: packages/NAME_C/
          docker:
            dockerfile: ./k8s/image/Dockerfile
            target: NAME_C-dev
        - image: custom-registry/custom-repo/NAME_B-dev
          context: .
          sync:
            manual:
              - src: packages/NAME_B/**
                dest: ./
                strip: packages/NAME_B/
          docker:
            dockerfile: ./k8s/image/Dockerfile
            target: NAME_B-dev
        - image: custom-registry/custom-repo/NAME_B-proxy
          context: ./packages/NAME_B/image
          docker:
            dockerfile: fileNAME_CCache.Dockerfile
        - image: custom-registry/custom-repo/client-dev
          context: .
          sync:
            manual:
              - src: packages/NAME_D/**
                dest: ./
                strip: packages/NAME_D/
          docker:
            dockerfile: ./k8s/image/Dockerfile
            target: client-dev
        - image: custom-registry/custom-repo/NAME_A-dev
          context: .
          sync:
            manual:
              - src: packages/NAME_A/**
                dest: ./
                strip: packages/NAME_A/
          docker:
            dockerfile: ./k8s/image/Dockerfile
            target: NAME_A-dev
      local:
        useBuildKit: true
    deploy:
      kustomize:
        path: ./k8s/env-specific/internal-dev

```

### Logs
```
time="2019-07-31T18:08:01+02:00" level=debug msg="Change detected notify.Write: \"**********\\app\\app\\packages\\NAME_D\\.idea\\workspace.xml\""
time="2019-07-31T18:08:01+02:00" level=debug msg="Change detected notify.Write: \"**********\\app\\app\\packages\\NAME_D\\.idea\\workspace.xml\""
...
time="2019-07-31T18:08:02+02:00" level=debug msg="Skipping excluded path: packages\\NAME_D\\.idea"
```

I can't see any explanation for the rebuild in the logs
