### ISSUE TITLE
Add watching folders that lives outside of artifact's directory

### ISSUE THREAD

**Issue by shqyking** [GoogleContainerTools/skaffold#2615]
### Expected behavior
I could specify watching folders that are not in artifact's directory. For example, I have a common lib directory used by various artifacts. When I change the code in common lib, skaffold triggers a rebuild

### Actual behavior
Can't find a place to specify such watching folders.

### Information
"context" doesn't work for me since that's the directory for application code. The folder I want to watch isn't part of any artifact, but a standalone common library. 

- Skaffold version: v0.33.0
- Operating system: Debian linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: abc-service
    jibGradle:
      project: services:abc
deploy:
  kustomize:
    path: deployment/kustomize/overlay/local
```

### Steps to reproduce the behavior
N/A
