### ISSUE TITLE
.dockerignore behaviour delta: docker<->skaffold

### ISSUE THREAD

**Issue by haf** [GoogleContainerTools/skaffold#2628]
### Expected behavior

Full repro: https://github.com/haf/skaffold-dockerignore

### Actual behavior

Skaffold doesn't handle `**`—ignore everything patterns, with _include_ behaviour thereafter.

Why do I use `**`? Because it drastically simplifies the management of `.dockerignore` to be whitelisting build requirements, than blacklisting every single added file or binary.

### Information

- Skaffold version: v0.35.0
- Operating system: macOS
- Contents of skaffold.yaml: see full repro

### Steps to reproduce the behavior

See repro

### Workaround

```yaml
  # see the commented-out section in the repro skaffold.yaml file.
  local:
    useDockerCLI: true
```
