### ISSUE TITLE
Image tag not injected into Helm value file

### ISSUE THREAD

**Issue by emichaf** [GoogleContainerTools/skaffold#2630]
Can't get the generated Image tag to be injected into the Helm value file:

**skaffold file:** 
```
  - name: stage  
    build:
      tagPolicy:
        gitCommit: {}
      artifacts:
      - image: docker.io/myrepo/backend
        docker: 
          dockerfile: src/main/docker/Dockerfile
          noCache: true
        context: . 
    deploy:
      helm:   
        releases:
        - name: myapplication 
          recreatePods: true
          chartPath: deployment/backend
          valuesFiles: 
            - deployment/backend/values-stage.yaml 
          values:
            image: "docker.io/myrepo/backend" <-- Not working, value file got registry, repository and tag
```
**Helm Value file:**
```
image:
  registry: docker.io
  repository: myrepo/backend
  tag: mytesttag    <-- this should be replaced by generated tag gitCommit: {}
```

Is it possible to get the generated Image tag via any env var etc, and set i via setValues: ?

**Comment by balopat** [comment]
Hi @emichaf, thanks for filing! 
Can you try with `explicitRegistry:true`? 

From https://skaffold.dev/docs/references/yaml/:

```yaml
helm:  #  image configuration uses the syntax IMAGE-NAME.repository=IMAGE-REPOSITORY, IMAGE-NAME.tag=IMAGE-TAG.
    explicitRegistry: true  #  separates image.registry to the image config syntax. Useful for some charts e.g. postgresql.
```

**Comment by raniejade** [comment]
Looks like the tag passed to `deploy` (helm) is not the one used during building.

```yaml
apiVersion: skaffold/v1beta13
kind: Config
metadata:
  name: kuripz
build:
  artifacts:
    - image: api-gateway
      jibGradle:
        project: api-gateway

deploy:
  helm:
    releases:
      - name: api-gateway
        chartPath: cluster/charts/api-gateway
        imageStrategy:
          fqn: {}
        values:
          image: api-gateway
```

Running `skaffold run -v debug --tail` yields:

```
INFO[0000] Skaffold &{Version:v0.35.0 ConfigVersion:skaffold/v1beta13 GitVersion: GitCommit:1da7608f9eb21ebe722bc054584e591e4223a3dc GitTreeState:clean BuildDate:2019-08-03T03:28:57Z GoVersion:go1.12.7 Compiler:gc Platform:darwin/amd64}
DEBU[0000] Defaulting build type to local build
DEBU[0000] validating yamltags of struct SkaffoldConfig
DEBU[0000] validating yamltags of struct Metadata
DEBU[0000] validating yamltags of struct Pipeline
DEBU[0000] validating yamltags of struct BuildConfig
DEBU[0000] validating yamltags of struct Artifact
DEBU[0000] validating yamltags of struct ArtifactType
DEBU[0000] validating yamltags of struct JibGradleArtifact
DEBU[0000] validating yamltags of struct TagPolicy
DEBU[0000] validating yamltags of struct GitTagger
DEBU[0000] validating yamltags of struct BuildType
DEBU[0000] validating yamltags of struct LocalBuild
DEBU[0000] validating yamltags of struct DeployConfig
DEBU[0000] validating yamltags of struct DeployType
DEBU[0000] validating yamltags of struct HelmDeploy
DEBU[0000] validating yamltags of struct HelmRelease
DEBU[0000] validating yamltags of struct HelmOverrides
DEBU[0000] validating yamltags of struct HelmImageStrategy
DEBU[0000] validating yamltags of struct HelmImageConfig
DEBU[0000] validating yamltags of struct HelmFQNConfig
DEBU[0000] validating yamltags of struct HelmDeployFlags
INFO[0000] Using kubectl context: docker-desktop
INFO[0000] no config entry found for kube-context docker-desktop
INFO[0000] no config entry found for kube-context docker-desktop
DEBU[0000] Using builder: local
DEBU[0000] setting Docker user agent to skaffold-v0.35.0
INFO[0000] no config entry found for kube-context docker-desktop
DEBU[0000] push value not present, defaulting to false because localCluster is true
Generating tags...
 - api-gateway -> DEBU[0000] Running command: [git describe --tags --always]
DEBU[0000] Command output: [5eaaab7
]
DEBU[0000] Running command: [git status . --porcelain]
DEBU[0000] Command output: []
api-gateway:5eaaab7
Tags generated in 14.97502ms
Starting build...
Found [docker-desktop] context, using local docker daemon.
Building [api-gateway]...
DEBU[0000] Using wrapper for gradlew: gradle
INFO[0000] Building .: /Users/ranie/personal/kuripz/gradlew, [/Users/ranie/personal/kuripz/gradlew -Djib.console=plain _skaffoldFailIfJibOutOfDate -Djib.requiredVersion=1.4.0 :api-gateway:jibDockerBuild --image=api-gateway:5eaaab7]
DEBU[0000] Running command: [/Users/ranie/personal/kuripz/gradlew -Djib.console=plain _skaffoldFailIfJibOutOfDate -Djib.requiredVersion=1.4.0 :api-gateway:jibDockerBuild --image=api-gateway:5eaaab7]

> Task :api-gateway:jibDockerBuild

Containerizing application to Docker daemon as api-gateway:5eaaab7...
Getting base image gcr.io/distroless/java:11...
Building dependencies layer...
Building resources layer...
Building classes layer...

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, io.ktor.server.netty.EngineMain]
Loading to Docker daemon...

Built image to Docker daemon as api-gateway:5eaaab7

BUILD SUCCESSFUL in 5s
4 actionable tasks: 2 executed, 2 up-to-date
Build complete in 5.494937088s
Starting test...
Test complete in 6.613µs
Starting deploy...
DEBU[0005] Executing template &{envTemplate 0xc0001a8300 0xc0000ce1c0  } with environment *ommitted*
DEBU[0005] Running command: [helm --kube-context docker-desktop get api-gateway]
REVISION: 1
RELEASED: Thu Aug 15 22:46:15 2019
CHART: api-gateway-0.1.0
USER-SUPPLIED VALUES:
image: api-gateway:c343e1672ced7f6a1d080353e4564e27a031cb73c8946d3a79268abe44fac9d0

COMPUTED VALUES:
image: api-gateway:c343e1672ced7f6a1d080353e4564e27a031cb73c8946d3a79268abe44fac9d0
imagePullPolicy: Always
replicaCount: 1

HOOKS:
MANIFEST:

---
# Source: api-gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
  type: ClusterIP
---
# Source: api-gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:c343e1672ced7f6a1d080353e4564e27a031cb73c8946d3a79268abe44fac9d0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
INFO[0005] Building helm dependencies...
DEBU[0005] Running command: [helm --kube-context docker-desktop dep build cluster/charts/api-gateway]
No requirements found in cluster/charts/api-gateway/charts.
DEBU[0005] Running command: [helm --kube-context docker-desktop upgrade api-gateway --force cluster/charts/api-gateway --set image=api-gateway:c343e1672ced7f6a1d080353e4564e27a031cb73c8946d3a79268abe44fac9d0]
Release "api-gateway" has been upgraded.
LAST DEPLOYED: Thu Aug 15 22:48:02 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME         READY  UP-TO-DATE  AVAILABLE  AGE
api-gateway  0/1    1           0          107s

==> v1/Pod(related)
NAME                          READY  STATUS            RESTARTS  AGE
api-gateway-64f88f8785-g84fn  0/1    ImagePullBackOff  0         107s

==> v1/Service
NAME         TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)   AGE
api-gateway  ClusterIP  10.106.40.204  <none>       8080/TCP  107s


DEBU[0005] Running command: [helm --kube-context docker-desktop get api-gateway]
INFO[0006] error decoding parsed yaml: Object 'Kind' is missing in 'REVISION: 2
RELEASED: Thu Aug 15 22:48:02 2019
CHART: api-gateway-0.1.0
USER-SUPPLIED VALUES:
image: api-gateway:c343e1672ced7f6a1d080353e4564e27a031cb73c8946d3a79268abe44fac9d0

COMPUTED VALUES:
image: api-gateway:c343e1672ced7f6a1d080353e4564e27a031cb73c8946d3a79268abe44fac9d0
imagePullPolicy: Always
replicaCount: 1

HOOKS:
MANIFEST:

'
DEBU[0006] Patching api-gateway in namespace default
DEBU[0006] Patching api-gateway in namespace default
Deploy complete in 554.946869ms
Back-off pulling image "api-gateway:c343e1672ced7f6a1d080353e4564e27a031cb73c8946d3a79268abe44fac9d0"
```

So the tag used in build is `api-gateway:5eaaab7` while the image tag passed to helm during deploy is `api-gateway:c343e1672ced7f6a1d080353e4564e27a031cb73c8946d3a79268abe44fac9d0`.
