### ISSUE TITLE
Image pull fail on helm deploy when sync is enabled

### ISSUE THREAD

**Issue by yoshwata** [GoogleContainerTools/skaffold#2631]
### Expected behavior
Image pull as the settings of values.yaml on `skaffold deploy`.
`skaffold dev` is no problem.

### Actual behavior
ImagePullBackOff occurs to pull image name like `skaffold-helm:skaffold-helm`

When I try to sync with [this code](https://github.com/yoshwata/skaffold/pull/1/files)(This is also put as reproduction example too), syncing works well.

<details>
<summary>Logs of skaffold dev</summary>
$ ../../out/skaffold-darwin-amd64 dev --default-repo docker.io/yoshwata
Generating tags...
 - docker.io/yoshwata/skaffold-helm -> docker.io/yoshwata/skaffold-helm:latest
Tags generated in 97.378µs
Starting build...
Building [docker.io/yoshwata/skaffold-helm]...
Sending build context to Docker daemon  4.096kB
Step 1/2 : FROM nginx:stable
 ---> 18ff9f3390d6
Step 2/2 : COPY static /usr/share/nginx/html/
 ---> 6018f43d17f9
Successfully built 6018f43d17f9
Successfully tagged yoshwata/skaffold-helm:latest
The push refers to repository [docker.io/yoshwata/skaffold-helm]
f16acba8faf9: Preparing
20435c24eb60: Preparing
7c6961c07bf2: Preparing
6270adb5794c: Preparing
6270adb5794c: Layer already exists
7c6961c07bf2: Layer already exists
20435c24eb60: Layer already exists
f16acba8faf9: Pushed
latest: digest: sha256:cbb7c452b0d812e82300b833c201049e588202b9e819469c7e414eb2bf156712 size: 1155
Build complete in 16.122171527s
Starting test...
Test complete in 6.802µs
Starting deploy...
Error: release: "skaffold-helm" not found
Helm release skaffold-helm not installed. Installing...
No requirements found in skaffold-helm/charts.
NAME:   skaffold-helm
LAST DEPLOYED: Fri Aug 23 11:14:12 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Pod(related)
NAME                            READY  STATUS   RESTARTS  AGE
skaffold-helm-56898c9f46-g6gbp  0/1    Pending  0         0s

==> v1/Service
NAME                         TYPE       CLUSTER-IP  EXTERNAL-IP  PORT(S)  AGE
skaffold-helm-skaffold-helm  ClusterIP  10.43.15.1  <none>       80/TCP   0s

==> v1beta1/Deployment
NAME           READY  UP-TO-DATE  AVAILABLE  AGE
skaffold-helm  0/1    1           0          0s

==> v1beta1/Ingress
NAME                         HOSTS  ADDRESS  PORTS  AGE
skaffold-helm-skaffold-helm  *      80       0s

Deploy complete in 922.265861ms
Watching for changes...
Syncing 1 files for docker.io/yoshwata/skaffold-helm:latest@sha256:cbb7c452b0d812e82300b833c201049e588202b9e819469c7e414eb2bf156712
Watching for changes...
</details>

However `skaffold deploy` does not work at this condition because of `ImagePullBackOff`.

<details>
<summary>Logs of skaffold deploy</summary>
$ ../../out/skaffold-darwin-amd64 deploy --default-repo docker.io/yoshwata
Starting deploy...
Error: release: "skaffold-helm" not found
Helm release skaffold-helm not installed. Installing...
No requirements found in skaffold-helm/charts.
NAME:   skaffold-helm
LAST DEPLOYED: Fri Aug 23 11:15:39 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Pod(related)
NAME                            READY  STATUS       RESTARTS  AGE
skaffold-helm-56898c9f46-g6gbp  0/1    Terminating  0         87s
skaffold-helm-5dfc67475-k85vg   0/1    Pending      0         0s

==> v1/Service
NAME                         TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)  AGE
skaffold-helm-skaffold-helm  ClusterIP  10.43.100.130  <none>       80/TCP   0s

==> v1beta1/Deployment
NAME           READY  UP-TO-DATE  AVAILABLE  AGE
skaffold-helm  0/1    1           0          0s

==> v1beta1/Ingress
NAME                         HOSTS  ADDRESS  PORTS  AGE
skaffold-helm-skaffold-helm  *      80       0s

Deploy complete in 1.084552247s
There is a new version (0.36.0) of Skaffold available. Download it at https://storage.googleapis.com/skaffold/releases/latest/skaffold-darwin-amd64

</details>

Result of kubectl get po
```
NAME                            READY   STATUS             RESTARTS   AGE
skaffold-helm-5dfc67475-k85vg   0/1     ImagePullBackOff   0          24s
svclb-node-4j2j8                1/1     Running            0          47d
svclb-node-74b9w                1/1     Running            0          47d
```

Image name is wrong, that should be `nginx:stable` as it is specified at [values.yaml](https://github.com/yoshwata/skaffold/pull/1/files#diff-d0e06e8e40332f8da67e5a8604ecef6cR7).
```
$ k get po skaffold-helm-5dfc67475-k85vg -o=jsonpath='{.spec.containers[0].image}'
skaffold-helm:skaffold-helm
```

### Information

- Skaffold version: version v0.33.0-357-g706469d9-dirty
- Operating system: mac osx
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: skaffold-helm
    sync:
      manual:
      - src: 'static/**/*.*'
        dest: '/usr/share/nginx/html'
        strip: static/
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: skaffold-helm
      #wait: true
      #valuesFiles:
      #- helm-skaffold-values.yaml
      values:
        # image: gcr.io/k8s-skaffold/skaffold-helm
        image: skaffold-helm
      #recreatePods will pass --recreate-pods to helm upgrade
      #recreatePods: true
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.
      #setValues:
        #some.key: someValue
      imageStrategy:
        helm: {}
```

### Steps to reproduce the behavior

1.  checkout this [sample](https://github.com/yoshwata/skaffold/pull/1/files)
2. `skaffold deploy --default-repo docker.io/yoshwata`
3. deployment can not pull image

### What I guess
[This line](https://github.com/GoogleContainerTools/skaffold/blob/d89f07af7ceca9e21b050c43b46776a23b316188/pkg/skaffold/deploy/helm.go#L437) might be something wrong.
