### ISSUE TITLE
Private/Secured Docker Registry: Fails with error - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by ramukima** [GoogleContainerTools/skaffold#2633]
### Expected behavior
Ability to work with a secured private docker registry
### Actual behavior
Fails with error - x509: certificate signed by unknown authority
### Information

- Skaffold version: v0.34
- Operating system: OSX Darwin
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: <private-registry>/<org>/sample-image
      kaniko:
        flags:
        - --skip-tls-verify
        buildContext:
          localDir: {}
        cache: {}
  cluster:
    pullSecretName: e2esecret
    namespace: ramukima
    timeout: 15m
    dockerConfig:
      secretName: e2esecret
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

Looking at the comments https://github.com/GoogleContainerTools/kaniko/pull/169#issuecomment-401572059, I am not sure how to achieve the same using Skaffold.

ERROR: 

INFO[0040] Taking snapshot of files...
2019/08/12 16:33:54 existing blob: sha256:5d20c808ce198565ff70b3ed23a991dd49afac45dece63474b27ce6ed036adc6
2019/08/12 16:33:54 pushed blob: sha256:09122320b650d56471912602eda322e12ea2abf6f30b0895e70a77c7dbeabf8d
2019/08/12 16:33:54 pushed blob: sha256:5e5a5673536343cb76edab6af522e63b06186f283d0cbbfeac424b4d22c51bea
2019/08/12 16:33:54 <private-registry><org>/<sample-image>:v0.26.0-104-g642f7f92-dirty: digest: sha256:b453224c5cb791139262e2cbff230287ada738d41ddb8f5def6f351b0257f3b2 size: 591
FATA[0055] failed to build: build failed: building [<private-registry><org>/<sample-image>]: kaniko build for [<private-registry><org>/<sample-image>]: getting image: Get https://<private-registry>/v2/: x509: certificate signed by unknown authority

Also, this issue https://github.com/GoogleContainerTools/skaffold/issues/2217 looks like the one I am hitting except for the error is about TLS.
