### ISSUE TITLE
Manifests apply order

### ISSUE THREAD

**Issue by thomas-tabbaza** [GoogleContainerTools/skaffold#2645]
### Expected behavior
Skaffold should apply the manifests in the order they are supplied in the `manifests` property.
(see @briandealwis below for use case/context)

### Actual behavior
Uses (apparently) alphabetical order for everything.

### Information

- Skaffold version: v0.35.0
- Operating system: osx

### Steps to reproduce the behavior

```yaml
apiVersion: skaffold/v1beta13
kind: Config
deploy:
  kubectl:
    manifests:
      - ../folder_a/*
      - ./some_other_manifest.yaml
```
Whatever the order the manifests is in the `manifests` property, `skaffold dev -v debug` still shows they are applied in the same order.

**Comment by briandealwis** [comment]
Relevance here is that @thomas-tabbaza is trying to create and use namespaces within his manifests, but [these are required to be ordered to the top](https://github.com/kubernetes/kubernetes/issues/44511#issuecomment-294504592):
> create the namespace before running apply, or sort your input files to put hard dependencies first.
>
> there are very few hard dependencies in kube, but the namespace existing is one of them

There is some more discussion in kubernetes/kubernetes#16448.  Skaffold's `kubectl` deployer should retain the manifest order specified.

Apparently [`kustomize` sorts resources](https://github.com/kubernetes/kubernetes/issues/16448#issuecomment-490257460) and so using the `kustomize` deployer may be a workaround.

**Comment by balopat** [comment]
So, we create a single big list of manifests out of the manifest list and throw that at `kubectl apply` and kubectl doesn't sort resources. 
Options: 
1) instead of a single monolithic apply, apply per manifest entry  - can make things significantly slower on remote clusters
2) sort the manifests - reimplementing the wheel - also requires parsing the manifests. It's doable but not a small change. 
3) turn on -k if the user has kubectl 1.14+ installed (<1.14 doesn't work) 

I'm currently thinking we could do 3) and 2) for <1.14 and retire 2) when <1.14 kubectl versions are not supported (https://kubernetes.io/docs/setup/release/version-skew-policy/) ...

**Comment by thomas-tabbaza** [comment]
Just passing the manifest files in the order listed in the `manifests:` property, and advising people to put namespaces first should do the trick without any downsides.

Example:
```yaml
apiVersion: skaffold/v1beta13
kind: Config
deploy:
  kubectl:
    manifests:
      # 1st file in the apply command
      - traefik-ingress.yaml
      # 2nd file in the apply command
      - k8s-dashboard-ingress.yaml  
```

Currently, this is not the case, k8s would be first (alphabetical order). When referencing folder though `- folder/*` it should stay alphabetical, since this is the expected behaviour.
