### ISSUE TITLE
User defined port-forward context

### ISSUE THREAD

**Issue by ollieayre-oc** [GoogleContainerTools/skaffold#2646]
Apologies if this isn't the correct forum in which to ask this.

Would it be feasible to allow an overriding context to be declared per user defined port-forward rather than assuming all target resources will exist within a singe cluster?

A theoretical example:
```
portForward:
- resourceType: deployment
  resourceName: myDep
  namespace: mynamespace 
  port: 8080
  context: mycontext
- resourceType: deployment
  resourceName: myDep2
  namespace: mynamespace 
  port: 8080
  context: different-context
```

**Comment by balopat** [comment]
Hi @ollieayre-oc,

It is totally okay to ask questions here as we mainly follow Github Issues and the Slack channel. 

Skaffold currently assumes that we are targeting a single cluster in a `skaffold dev` loop or a `skaffold run` execution. 

Thus, for context specific port forwarding, I would use [profiles](https://skaffold.dev/docs/how-tos/profiles/), activated by different kube contexts. E.g. 

```
profiles:
  - name: prof_1
    activation:
      - kubeContext: mycontext
    portForward:
      - resourceType: deployment
        resourceName: myDep
        namespace: mynamespace
        port: 8080
  - name: prof_2
    activation:
      - kubeContext: different-context
    portForward:
     - resourceType: deployment
       resourceName: myDep2
       namespace: mynamespace
       port: 8080
```

Hope this helps!

**Comment by ollieayre-oc** [comment]
Thanks @balopat 

I didn't ask my question very well but you've somewhat answered it anyway with regards to the single cluster assumption.

My use case actually requires both port forwards to be active simultaneously to target dependencies in different contexts as opposed to running different port-forwards dependent on context.

Currently we deploy an application locally for development and then independently set up different port-forwards using kubectl with the `--context` flag to avoid context switching.

**Comment by balopat** [comment]
> My use case actually requires both port forwards to be active simultaneously to target dependencies in different contexts as opposed to running different port-forwards dependent on context. 
> Currently we deploy an application locally for development and then independently set up different port-forwards using kubectl with the `--context` flag to avoid context switching.

Interesting!
Just to make sure that  understand correctly, is this your situation?
Run your app locally (let's say Service A) that depends on a  service (Service B) - for local development of Service A, you deploy service B to a cluster B, port forward it to localhost (let's say port 8080) and point Service A configuration to Service B as http://localhost:8080?

**Comment by ollieayre-oc** [comment]
Yes thats about the size of it, for compliance reasons we have to separate certain dependant applications into different contexts and so in the 'context' of your example we may have one or two services like service B that need to be port-forwarded.

**Comment by ollieayre-oc** [comment]
Hi @nkubala 

Thanks for dropping the update above, unfortunately i still don't think this addresses this use case unless i'm missing something.

From what i've seen/tried profiles and config-dependencies don't get us there because they still only run against one context whereas we basically need to be able to interact with two simultaneously from one skaffold configuration.

Just to give a full example of what we're currently doing and what we'd like to do to perhaps make things a bit clearer.

Currently for local dev we use this config deploy to a local k8s cluster:

`apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: <service-name>
  local:
    useDockerCLI: true
deploy:
  helm:
    releases:
    - name: <release-name>
      chartPath: <chart-path>
      setValueTemplates:
        image.repository: '{{.IMAGE_NAME}}'
        image.tag: '{{.IMAGE_TAG}}'`

This service has a dependency on a database on our main clusters as well as a number of other services so we run the following commands in different tabs:
`skaffold dev --port-forward --kubeContext docker-desktop` << Deploys the service being developed to a local docker-for-mac k8s cluster
`kubectl port-forward svc/database --context remote-cluster 8000:80` << Makes the database available to connect to from the local cluster
`kubectl port-forward svc/dependency-a --context remote-cluster 8001:80` << Makes another service dependency available to connect to from the local cluster

Ideally we could configure those port-forwards from the skaffold config as well so that anyone could pick up the project and start running it without worrying about getting all of the configuration right.

Ideal pseduo-config where a context other than the local one can be specified to replicate the commands we're currently running:

`apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: <service-name>
  local:
    useDockerCLI: true
deploy:
  helm:
    releases:
    - name: <release-name>
      chartPath: <chart-path>
      setValueTemplates:
        image.repository: '{{.IMAGE_NAME}}'
        image.tag: '{{.IMAGE_TAG}}'
portForward:
- resourceType: service
  resourceName: database
  namespace: <ns> 
  port: 8000
  context: remote-cluster
- resourceType: service
  resourceName: dependency-a
  namespace:<ns> 
  port: 8001
  context: remote-cluster
`

Appreciate any further assistance or ideas you could offer here.
Thanks

**Comment by tejal29** [comment]
Triage notes:
- This might work on master. @gsquared94 to test and see if this works.
-

**Comment by gsquared94** [comment]
@ollieayre-oc if you can build from source, can you try this PR https://github.com/GoogleContainerTools/skaffold/pull/6394 branch? Otherwise the latest bleeding edge build after that PR gets in?

You should be able to use [multi config support](https://skaffold.dev/docs/design/config/#multiple-configuration-support) now to define two skaffold modules that target deploy to different `kubeContext` values. The logs and portforwards should work from multiple clusters.

**Comment by ollieayre-oc** [comment]
Thanks for the heads up @gsquared94, i'll see about building it today and report back

**Comment by ollieayre-oc** [comment]
Hey @gsquared94 

I'm afraid that change still doesn't do what i'm after unless i'm doing something wrong because i need to deploy to my local cluster but only create a port-forward for a resource on my staging cluster that my local deployment needs as a dependency.

For reference this is the skaffold file I used to test with:
```
apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
    - image: <image-name>
  local:
    useDockerCLI: true
deploy:
  kubeContext: <local-context>
  helm:
    releases:
      - name: <release-name>
        chartPath: <chart-path>
        setValueTemplates:
          image.repository: '{{.IMAGE_NAME}}'
          image.tag: '{{.IMAGE_TAG}}'
        valuesFiles:
          - helm/overrides.yaml
          - helm/LOCALHOST.yaml
---
apiVersion: skaffold/v2beta19
kind: Config
portForward:
  - resourceType: service
    resourceName: <dependency-name>
    namespace: <namespace>
    port: <port>
    localPort: <port>
    kubeContext: <remote-context> <<<<<<< This is what i'm missing
```

Test command: `skaffold dev --port-forward`

**Comment by gsquared94** [comment]
Got it. Skaffold doesn't support not having any `deploy` stanza in a module. So your `skaffold.yaml` won't work.

We're working on a [hooks](https://skaffold-latest.firebaseapp.com/docs/pipeline-stages/lifecycle-hooks/#before-deploy-and-after-deploy-only-for-kubectl-deployer) feature that will be out for the `kubectl` deployer next release (you can use the `main` branch build). It's not yet implemented for `helm` deployer since we're also parallely reworking `helm` integration but it should be out soon.

Meanwhile, will this work as an ugly hack?
```yaml
apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
    - image: <image-name>
  local:
    useDockerCLI: true
deploy:
  kubeContext: <local-context>
  kubectl:
    manifests:
      - <some_dummy_manifest>
    hooks:
        before:
          - host:
              command: ["sh", "-c", "kubectl port-forward svc/database --context remote-cluster 8000:80"]
          - host:
              command: ["sh", "-c", "kubectl port-forward svc/dependency-a --context remote-cluster 8001:80"]
  helm:
    releases:
      - name: <release-name>
        chartPath: <chart-path>
        setValueTemplates:
          image.repository: '{{.IMAGE_NAME}}'
          image.tag: '{{.IMAGE_TAG}}'
        valuesFiles:
          - helm/overrides.yaml
          - helm/LOCALHOST.yaml
```
