### ISSUE TITLE
Graceful termination for custom builder

### ISSUE THREAD

**Issue by tbarrella** [GoogleContainerTools/skaffold#2656]
### Expected behavior
When cancelling skaffold build with a custom builder, it would be helpful if the build command process had time to clean up. For example, first sending SIGTERM, and then waiting before sending SIGKILL.

### Actual behavior
Cancelling CommandContext sends SIGKILL immediately, preventing the custom builder from cleaning up. An example of something that might need to be cleaned up is a pod from a cluster builder.

### Information

- Skaffold version: v0.34.1
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: ...
    custom:
      buildCommand: ./build.sh
```

### Steps to reproduce the behavior

1. `skaffold build` with any `build.sh`
2. Ctrl-C before `build.sh` completes
