### ISSUE TITLE
EnvVarMap indices are non-deterministic

### ISSUE THREAD

**Issue by aeneasr** [GoogleContainerTools/skaffold#2680]
### Expected behavior

When building multiple artifacts, the indices appended to `DIGEST(_*)` and `IMAGE_NAME` behave unexpectedly which makes it impossible to use multiple build artifacts in combination with e.g. `deploy.helm.releases.*.setValueTemplates`.

Unfortunately, I still have to rely on `setValueTemplates` because the `helm` imageStrategy seems to be broken (several issues open for it).

### Actual behavior

I would expect `DIGEST` and `DIGEST2` AND `DIGEST<n>` to always refer to the same build artifact. However output from `EnvVarMap`  is not deterministic and deployments fail after a couple of rebuilds. I'm guessing that the more images we have, the frequency of this will increase:

```
EnvVarMap: map[string]string{"DIGEST":"6a3fdeb-dirty@sha256:0c18f939bfc0ebf45ffb347257e0e1a53f7875b55785d08edfe64775217c7ee1", "DIGEST_ALGO":"6a3fdeb-dirty@sha256", "DIGEST_HEX":"0c18f939bfc0ebf45ffb347257e0e1a53f7875b55785d08edfe64775217c7ee1", "IMAGE_NAME":"gcr.io/ory-artifacts/console"}
EnvVarMap: map[string]string{"DIGEST":"6a3fdeb-dirty@sha256:0c18f939bfc0ebf45ffb347257e0e1a53f7875b55785d08edfe64775217c7ee1", "DIGEST2":"6a3fdeb-dirty@sha256:f40a6d87dac23fbb312ea494ea6e0c74ef03da7a6d15922131dc1bb71c8bf3de", "DIGEST_ALGO":"6a3fdeb-dirty@sha256", "DIGEST_ALGO2":"6a3fdeb-dirty@sha256", "DIGEST_HEX":"0c18f939bfc0ebf45ffb347257e0e1a53f7875b55785d08edfe64775217c7ee1", "DIGEST_HEX2":"f40a6d87dac23fbb312ea494ea6e0c74ef03da7a6d15922131dc1bb71c8bf3de", "IMAGE_NAME":"gcr.io/ory-artifacts/console", "IMAGE_NAME2":"gcr.io/ory-artifacts/oathkeeper"}
```

```
EnvVarMap: map[string]string{"DIGEST":"6a3fdeb-dirty@sha256:1f66e44f701eee9d5d1c56900f3b039b640973598987e1b9ffae2a3619db47ad", "DIGEST_ALGO":"6a3fdeb-dirty@sha256", "DIGEST_HEX":"1f66e44f701eee9d5d1c56900f3b039b640973598987e1b9ffae2a3619db47ad", "IMAGE_NAME":"gcr.io/ory-artifacts/oathkeeper"}
EnvVarMap: map[string]string{"DIGEST":"6a3fdeb-dirty@sha256:1f66e44f701eee9d5d1c56900f3b039b640973598987e1b9ffae2a3619db47ad", "DIGEST2":"6a3fdeb-dirty@sha256:0c18f939bfc0ebf45ffb347257e0e1a53f7875b55785d08edfe64775217c7ee1", "DIGEST_ALGO":"6a3fdeb-dirty@sha256", "DIGEST_ALGO2":"6a3fdeb-dirty@sha256", "DIGEST_HEX":"1f66e44f701eee9d5d1c56900f3b039b640973598987e1b9ffae2a3619db47ad", "DIGEST_HEX2":"0c18f939bfc0ebf45ffb347257e0e1a53f7875b55785d08edfe64775217c7ee1", "IMAGE_NAME":"gcr.io/ory-artifacts/oathkeeper", "IMAGE_NAME2":"gcr.io/ory-artifacts/console"}
```

So, as you can see above, `IMAGE_NAME<n>` switches around:

```
 "IMAGE_NAME":"gcr.io/ory-artifacts/oathkeeper", "IMAGE_NAME2":"gcr.io/ory-artifacts/console"
```

vs

```
"IMAGE_NAME":"gcr.io/ory-artifacts/console", "IMAGE_NAME2":"gcr.io/ory-artifacts/oathkeeper"
```

I think it's generally awkward that Skaffold uses a different naming strategy for helm than supported by probably 95% of helm projects out there. And there's very little documentation that helps with that.

### Information

- Skaffold version: v0.36.0
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    useDockerCLI: false
  artifacts:
    # The order of these needs to stay the same
    -
      image: gcr.io/ory-artifacts/console
      context: console
      docker:
        dockerfile: Dockerfile-skaffold
    -
      image: gcr.io/ory-artifacts/oathkeeper
      context: skaffold/oathkeeper
      docker:
        dockerfile: Dockerfile

deploy:
  helm:
    flags:
      global: ["--tiller-namespace","backoffice"]
    releases:
      -
        name: console
        chartPath: helm/charts/console
        namespace: backoffice
        recreatePods: true
        valuesFiles:
          - skaffold/console/values.yaml
        setValueTemplates:
          image.repository: gcr.io/ory-artifacts/console
          image.tag: "{{.DIGEST}}"
      -
        name: oathkeeper
        chartPath: ory/oathkeeper
        namespace: backoffice
        remote: true # required for remote charts
        skipBuildDependencies: true # required for remote charts
        recreatePods: true
        valuesFiles:
          - skaffold/oathkeeper/values.yaml
        setValueTemplates:
          image.repository: gcr.io/ory-artifacts/oathkeeper
          image.tag: "{{.DIGEST2}}"
```

### Steps to reproduce the behavior

Since all of these a private it's kinda tricky to reproduce this but I might be able to come up with something if required.
