### ISSUE TITLE
Setting Helm deployer `imageStrategy.helm` does not have any effect

### ISSUE THREAD

**Issue by aeneasr** [GoogleContainerTools/skaffold#2681]
### Expected behavior

Using `helm.ImageStrategy.helm: {}` should set the right repository name and tag for `image.repository` and `image.tag` when using the helm deployer

### Actual behavior

It appears that #826 should have closed #360 . However, using `helm.ImageStrategy.helm: {}` does not work at all because neither `image.repository` nor `image.tag` are being overwritten - they just keep their defaults from the original `values.yaml` file.

Seeing the skaffold.yaml file from below, I would expect:

- `console` to use `gcr.io/ory-artifacts/console:<some-hash>-dirty`
- `oathkeeper` to use `gcr.io/ory-artifacts/oathkeeper:<some-hash>-dirty`

However, that's not the case - the default values are being used instead:

- `console` uses `gcr.io/ory-artifacts/console:stable`
- `oathkeeper` uses `oryd/oathkeeper:v0.17.1-beta.1`

### Information

- Skaffold version: 0.36.0
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    useDockerCLI: false
  artifacts:
    # The order of these needs to stay the same
    -
      image: gcr.io/ory-artifacts/console
      context: console
      docker:
        dockerfile: Dockerfile-skaffold

    -
      image: gcr.io/ory-artifacts/oathkeeper
      context: skaffold/oathkeeper
      docker:
        dockerfile: Dockerfile

deploy:
  helm:
    flags:
      global: ["--tiller-namespace","backoffice"]
    releases:
      -
        name: console
        chartPath: helm/charts/console
        namespace: backoffice
        recreatePods: true
        valuesFiles:
          - skaffold/console/values.yaml
        imageStrategy:
          helm: {}
      -
        name: oathkeeper
        chartPath: ory/oathkeeper
        namespace: backoffice
        remote: true # required for remote charts
        skipBuildDependencies: true # required for remote charts
        recreatePods: true
        valuesFiles:
          - skaffold/oathkeeper/values.yaml
        imageStrategy:
          helm: {}
```

### Steps to reproduce the behavior

Not possible at the moment but happy to provide something if it speeds up the process.

**Comment by aeneasr** [comment]
Wow, what an odysee trying to figure out the right combination of config values to get this working. Apparently, **explicitly setting `values.image`** resolves this issue.

**works**
```

deploy:
  helm:
    flags:
      global: ["--tiller-namespace","backoffice"]
    releases:
      -
        name: console
        chartPath: helm/charts/console
        namespace: backoffice
        recreatePods: true
        valuesFiles:
          - skaffold/console/values.yaml
        values:
          image: gcr.io/ory-artifacts/console
        imageStrategy:
          helm: {}
```

**does not work**

```
deploy:
  helm:
    flags:
      global: ["--tiller-namespace","backoffice"]
    releases:
      -
        name: console
        chartPath: helm/charts/console
        namespace: backoffice
        recreatePods: true
        valuesFiles:
          - skaffold/console/values.yaml
# Without this repo and tag are not correct
#        values:
#          image: gcr.io/ory-artifacts/console
        imageStrategy:
          helm: {}
```

**Comment by balopat** [comment]
Thank you for filing this and sharing the working solution. I agree, this is not intuitive. At least we should document it more clearly but it looks like maybe we can get rid of the requirement to set `values.image`.

**Comment by aeneasr** [comment]
Yes, that sounds like a good idea :) And `imageStrategy.helm: {}` should also be documented as the not-nil/nil of yaml is not very obvious for non-go devs.

**Comment by oscar-martin** [comment]
I have similar situation to the one described here but when I try to apply the suggested workaround, the tag becomes the name of the image:

```
build:
  local:
    push: false
  artifacts:
  - image: myprivaterepo:5003/repo/controller
    custom:
      buildCommand: ./sk-build.sh
      dependencies:
        paths:
          - .
        ignore:
          - "*.md"
deploy:
  helm:
    releases:
    - name: skaffold-controller
      chartPath: charts/controller
      valuesFiles:
        - charts/controller/values.yaml
      values:
        image: myprivaterepo:5003/repo/controller
      imageStrategy:
        helm: {}
```

This is what helm is said to use:

```
$ helm get skaffold-controller

USER-SUPPLIED VALUES:
affinity: {}
...
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  repository: myprivaterepo:5003/repo/controller
  tag: controller
```

So tag is the name of the image instead of being the actual tag.

@aeneasr I am wondering why I get different behavior from yours.

```
$ skaffold version                        
v0.36.0
```
