### ISSUE TITLE
Custom cluster build is seen as invalid config?

### ISSUE THREAD

**Issue by tbarrella** [GoogleContainerTools/skaffold#2684]
### Expected behavior
Able to build in parallel while passing in environment variables by using `custom` with `cluster`

### Actual behavior
```
FATA[0000] creating runner: invalid skaffold config: only one element in set artifact can be set. got KanikoArtifact and CustomArtifact
```

### Information

- Skaffold version: v0.36.0
- Operating system: Ubuntu 16.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: <repo>
      custom:
        buildCommand: ./build.sh
  cluster: {}
```

### Steps to reproduce the behavior

1. Use any `build.sh`
2. `skaffold build`
