### ISSUE TITLE
Helm deployer should re-deploy only changed deployments, not all of them

### ISSUE THREAD

**Issue by aeneasr** [GoogleContainerTools/skaffold#2689]
### Expected behavior

When making a change that forces an image rebuild or a change that forces to update the deployment of a particular image, I would expect only that deployment to be triggered.

### Actual behavior

When an image is rebuilt and/or a deployment config changes, the helm deployer re-deploys **all** configured deployments.

This causes issues when e.g. a particular image was updated using `sync` and is being (unnecessarily) redeployed because another image changed. In that case, the sync image is being redeployed *without the changed files*, basically resetting the image state. To get back to the right state, I have to manually update a file under `sync` with a nonsensical change (e.g. add and remove newline).

From the skaffold config below:

1. I change some files in console/src/**/*. The changes are being synched to the container.
2. I change `skaffold/oathkeeper/values.yaml` (belongs to oathkeeper artifact) which causes the helm deployer to be triggered.
3. I would expect the helm deployer to only deploy the oathkeeper artifact. Right now however, all artifacts will be redeployed, essentially resetting the console deployment to the "base" console artifact which does not contain my changes.

### Information

- Skaffold version: v0.36.0
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    useDockerCLI: true # this is required for hive ocntext to work
  artifacts:
    # The order of these needs to stay the same
    -
      image: gcr.io/ory-artifacts/console
      context: console
      docker:
        dockerfile: Dockerfile-skaffold
      sync:
        manual:
          -
            src: "src/**/*"
            dest: .
          -
            src: "src/*"
            dest: .
          -
            src: "typings/*"
            dest: .
          -
            src: "public/*"
            dest: .

    -
      image: gcr.io/ory-artifacts/hive
      context: ../hive/
      docker:
        dockerfile: ../cloud/skaffold/hive/Dockerfile

    -
      image: gcr.io/ory-artifacts/backoffice
      context: src/backoffice
      docker:
        dockerfile: Dockerfile

    -
      image: gcr.io/ory-artifacts/oathkeeper
      context: skaffold/oathkeeper
      docker:
        dockerfile: Dockerfile

deploy:
  helm:
    flags:
      global: ["--tiller-namespace","backoffice"]
    releases:
      -
        name: hive
        chartPath: helm/charts/hive
        namespace: tenant-ory-cloud
        recreatePods: true
        valuesFiles:
          - skaffold/hive/values.yaml
        values:
          image: gcr.io/ory-artifacts/hive
        imageStrategy:
          helm: {}
      -
        name: backoffice
        chartPath: helm/charts/backoffice
        namespace: backoffice
        recreatePods: true
        valuesFiles:
          - skaffold/backoffice/values.yaml
        values:
          image: gcr.io/ory-artifacts/backoffice
        imageStrategy:
          helm: {}
      -
        name: console
        chartPath: helm/charts/console
        namespace: backoffice
        recreatePods: true
        valuesFiles:
          - skaffold/console/values.yaml
        values:
          image: gcr.io/ory-artifacts/console
        imageStrategy:
          helm: {}
      -
        name: oathkeeper
        chartPath: ory/oathkeeper
        namespace: backoffice
        version: v0.0.21
        remote: true # required for remote charts
        skipBuildDependencies: true # required for remote charts
        recreatePods: true
        valuesFiles:
          - skaffold/oathkeeper/values.yaml
        imageStrategy:
          helm: {}
        values:
          image: gcr.io/ory-artifacts/oathkeeper

```

### Steps to reproduce the behavior

If required I may be able to come up with an example repo.
