### ISSUE TITLE
skaffold not cleaning up resources on termination

### ISSUE THREAD

**Issue by samlevin** [GoogleContainerTools/skaffold#2690]
### Expected behavior

When pressing Ctrl+C, skaffold will terminate all k8s resources outlined in the spec (skaffold.yml). It used to in the past.

### Actual behavior

The following output appears:
```
^CCleaning up...
```
and the k8s object(s) remain.

### Information

- Skaffold version: version 0.36.0 (it happened in 0.35.0 as well)
- Operating system: Mac OSX
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: omitted/omitted
      context: .
      sync:
        manual:
        - src: 'src/**/*.js'
          dest: .
deploy:
  kubectl:
    manifests:
      - ./deploy/dev/omitted-pod.yaml

```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project - *n/a*
2. `skaffold dev`
