### ISSUE TITLE
Wrong image is tagged on subsequent skaffold build 

### ISSUE THREAD

**Issue by demisx** [GoogleContainerTools/skaffold#2694]
### Expected behavior

Subsequent `skaffold build` executions upon unchanged codebase do not tag wrong images.

### Actual behavior
The first time I run `skaffold build -p dev` command I get 3 images built and tagged as expected. When I run the same command for the second time, wrong image gets retagged with "init-db" tag. Later when my app pulls these images from local repo it fails to bootstrap because the wrong image is tagged with "init-db:..." tag now. This does not happen in v0.31

### Information

- Skaffold version: 0.36
- Operating system: MacOs 10.4.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kubectl:
        manifests:
          - api/app/k8s/dev/api.k8s-config.yaml
          ... 
    build:
      artifacts:
        # Logstash data ingestor service
        - image: dl-logstash
          context: .
          sync:
            manual:
              - src: 'api/app/logstash/config/dev/pipeline/*'
                dest: pipeline
          docker:
            dockerfile: api/app/logstash/Dockerfile
            target: dev-env
       # Bootstrapping DB
        - image: init-db
          context: .
          docker:
            dockerfile: api/Dockerfile
            target: init-db
            buildArgs:
              DL_ORG_DEV_NAMESPACE: '{{.DL_ORG_DEV_NAMESPACE}}'
        # API service
        - image: dl-api.dev
          context: .
          sync:
            manual:
              - src: 'api/app/src/**/*.ts'
                dest: .
                strip: 'api'
              - src: 'api/app/src/**/*.json'
                dest: .
                strip: 'api'
          docker:
            dockerfile: api/Dockerfile
            target: dev-env
            buildArgs:
              # These vars are different per each developer and cannot be part of ConfigMap in git
              DL_ORG_DEV_NAMESPACE: '{{.DL_ORG_DEV_NAMESPACE}}'
              DL_ORG_AWS_ACCOUNT_ID: '{{.DL_ORG_AWS_ACCOUNT_ID}}'
              DL_ORG_AWS_IAM_APP_USER_ACCESS_KEY_ID: '{{.DL_ORG_AWS_IAM_APP_USER_ACCESS_KEY_ID}}'
              DL_ORG_AWS_IAM_APP_USER_SECRET_ACCESS_KEY: '{{.DL_ORG_AWS_IAM_APP_USER_SECRET_ACCESS_KEY}}'
```

### Additional docs

![Screen Shot 2019-08-20 at 6 18 15 PM](https://user-images.githubusercontent.com/4452412/63395823-d7c54680-c379-11e9-8aa4-401d94bdc549.gif)

![Screen Shot 2019-08-20 at 6 10 24 PM](https://user-images.githubusercontent.com/4452412/63395843-ea3f8000-c379-11e9-9d84-b5ef97eff59a.gif)

### Skaffold Run log:

[double-skaffold-build-output.txt](https://github.com/GoogleContainerTools/skaffold/files/3523207/double-skaffold-build-output.txt)
