### ISSUE TITLE
Unexpected changes to helm.imageStrategy in 0.36.0

### ISSUE THREAD

**Issue by lsowen** [GoogleContainerTools/skaffold#2697]
### Expected behavior

In versions before v0.36.0, setting `deploy.helm.releases.imageStrategy.helm: {}` properly built and deployed the tag.

### Actual behavior

In v0.36.0, the same config generates an invalid image tag like `sftp-server:4d7ef00712b523d1e4236acb62b4f06eb2bc34efd05f5f4c2a02206ace8d5402`, so the image being deployed ends up being `sftp-server:sftp-server:4d7ef00712b523d1e4236acb62b4f06eb2bc34efd05f5f4c2a02206ace8d5402` (`<image>:<image>:<digest>`)

### Information

- Skaffold version: v0.36.0

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: sftp-server
    context: ./sshd/
  - image: sftp-server-watcher
    context: ./sftp-watch/
deploy:
  helm:
    releases:
    - name: sftp-server
      chartPath: charts/sftp-server
      values:
        server.image: sftp-server
        watcher.image: sftp-server-watcher
      imageStrategy:
        helm: {}
portForward:
  - resourceType: service
    resourceName: sftp-server
    port: 22

```

I believe it is related to https://github.com/GoogleContainerTools/skaffold/pull/2624

**Comment by lsowen** [comment]
Interestingly, if I update my skaffold.yaml to the following it works properly is 0.35.0:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: dummy/sftp-server
    context: ./sshd/
  - image: dummy/sftp-server-watcher
    context: ./sftp-watch/
deploy:
  helm:
    releases:
    - name: sftp-server
      chartPath: charts/sftp-server
      values:
        server.image: dummy/sftp-server
        watcher.image: dummy/sftp-server-watcher
      imageStrategy:
        helm: {}
portForward:
  - resourceType: service
    resourceName: sftp-server
    port: 22
```
