### ISSUE TITLE
Error parsing Dockerfile with multi-stage builds

### ISSUE THREAD

**Issue by asiragusa** [GoogleContainerTools/skaffold#2718]
### Expected behavior
`skaffold dev` runs normally

### Actual behavior
```
FATA[0002] watching files for artifact image1: listing files: listing files: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (package-common) for ONBUILD triggers: getting remote config: getting image: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/package-common Type:repository]] 
```

### Information

- Skaffold version: v0.36.0
- Operating system: Darwin 18.7.0 x86_64 i386
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config

build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: image1
      context: .
      docker:
        dockerfile: Dockerfile
        target: target1

    - image: image2
      context: .
      docker:
        dockerfile: Dockerfile
        target: target2

deploy:
  helm:
    releases:
      - name: release1
        chartPath: helm/chart1
        values:
          image: image1

      - name: release2
        chartPath: helm/chart2
        values:
          image: image2
```

Dockerfile:
```Dockerfile
FROM golang:1.12 AS build

RUN useradd -u 10001 user

# Go build

#################################
FROM scratch AS package-common

EXPOSE 8080

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/passwd /etc/passwd

FROM package-common AS target1

COPY --from=build /go/bin/bin1 /

USER user

ENTRYPOINT ["/bin1"]

FROM package-common AS target2

COPY --from=build /go/bin/bin2 /

USER user

ENTRYPOINT ["/bin2"]
```

### Steps to reproduce the behavior

1. the pasted skaffold.yaml + Dockerfile
2. `skaffold dev`

I use a single Dockerfile to build two images with a binary built in the `build` target. Such images have multiple steps in common and they are defined in the `package-common` target. This allows me to have a single `Dockerfile` for all the binaries produced by my repo and avoid a lot of copy/paste.

The very same Dockerfile worked a couple of months ago with skaffold (don't remember the exact version though), but after upgrading I can't anymore run `skaffold dev`.

If I take the contents of `package-common`, copy/paste them in `target1` and `target2` and remove the intermediate image, the build succeeds.
