### ISSUE TITLE
skaffold dev --port-forwarding with a profile does not forward specified ports

### ISSUE THREAD

**Issue by cthatcher-cb** [GoogleContainerTools/skaffold#2733]
### Issue
While attempting to create profiles for a local project where each profile would specify a specific port forwarding scheme, I found that while running `skaffold dev --port-forward -p p1` with a profile it wouldn't perform the port forwarding as it does when running `skaffold dev --port-forward`. Notice the example below using a modified version of the microservice example within master.

Is there something I'm misunderstanding or missing from my skaffold configuration? I was trying to follow the documentation for `skaffold.yaml` I found here: https://skaffold.dev/docs/references/yaml/

### Expected behavior

```
$ skaffold dev --port-forward -p p1
WARN[0000] Could not get minikube docker env, falling back to local docker daemon: getting minikube env: Running [minikube docker-env --shell none]: stdout , stderr: * 'none' driver does not support 'minikube docker-env' command
, err: exit status 64: exit status 64 
Generating tags...
 - gcr.io/k8s-skaffold/leeroy-web -> gcr.io/k8s-skaffold/leeroy-web:v0.36.0-76-gfb2107f3
 - gcr.io/k8s-skaffold/leeroy-app -> gcr.io/k8s-skaffold/leeroy-app:v0.36.0-76-gfb2107f3
Tags generated in 21.26246ms
Checking cache...
 - gcr.io/k8s-skaffold/leeroy-web: Found
 - gcr.io/k8s-skaffold/leeroy-app: Found
Cache check complete in 4.999515ms
Starting deploy...
kubectl client version: 1.15
service/leeroy-app created
deployment.apps/leeroy-app created
deployment.apps/leeroy-web created
Port forwarding deployment/leeroy-web in namespace default, remote port 8080 -> local port 9000
Port forwarding service/leeroy-app in namespace default, remote port 50051 -> local port 50053
Watching for changes...
[leeroy-app-65577d9b94-n869f leeroy-app] 2019/08/27 21:18:04 leeroy app server ready
[leeroy-web-78bb4db4c8-87t2k leeroy-web] 2019/08/27 21:18:04 leeroy web server ready
```

### Actual behavior
Notice that the resource `deployment/leeroy-web` isn't port forwarded below. Also not sure if its related but the output below is also displaying an additional warning about the profile overlay field type.

```
$ skaffold dev --port-forward -p p1
WARN[0000] unknown field type in profile overlay: int. falling back to original config values 
WARN[0000] Could not get minikube docker env, falling back to local docker daemon: getting minikube env: Running [minikube docker-env --shell none]: stdout , stderr: * 'none' driver does not support 'minikube docker-env' command
, err: exit status 64: exit status 64 
Generating tags...
 - gcr.io/k8s-skaffold/leeroy-web -> gcr.io/k8s-skaffold/leeroy-web:v0.36.0-76-gfb2107f3
 - gcr.io/k8s-skaffold/leeroy-app -> gcr.io/k8s-skaffold/leeroy-app:v0.36.0-76-gfb2107f3
Tags generated in 17.648357ms
Checking cache...
 - gcr.io/k8s-skaffold/leeroy-web: Found
 - gcr.io/k8s-skaffold/leeroy-app: Found
Cache check complete in 4.748209ms
Starting deploy...
kubectl client version: 1.15
service/leeroy-app created
deployment.apps/leeroy-app created
deployment.apps/leeroy-web created
Port forwarding service/leeroy-app in namespace default, remote port 50051 -> local port 50053
Watching for changes...
[leeroy-web-6578659889-nc7q6 leeroy-web] 2019/08/27 21:18:11 leeroy web server ready
[leeroy-app-68cfff77df-2krq4 leeroy-app] 2019/08/27 21:18:11 leeroy app server ready
```

### Information

- Skaffold version: 0.36.0
- Operating system: Ubuntu 18.04
- Contents of skaffold.yaml: 

```
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/leeroy-web
      context: ./leeroy-web/
    - image: gcr.io/k8s-skaffold/leeroy-app
      context: ./leeroy-app/
deploy:
  kubectl:
    manifests:
      - ./leeroy-web/kubernetes/*
      - ./leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
profiles:
  - name: p1
    portForward:
    - resourceType: deployment
      resourceName: leeroy-web
      port: 8080
      localPort: 9001
```

### Steps to reproduce the behavior

1. Replace `https://github.com/GoogleContainerTools/skaffold/blob/master/examples/microservices/skaffold.yaml` with the provided version above
2. `skaffold dev --port-forward -p p1`
3. Notice that `deployment/leeroy-web` port isn't forwarded when the profile is specified
