### ISSUE TITLE
Add support for k3d

### ISSUE THREAD

**Issue by strikeout** [GoogleContainerTools/skaffold#2753]
### Use case
Im trying to leverage `k3d` for efficient local k8s development. k3d requires an extra command to import the build images into the k3d containerd file-system (`k3d import-images $images`) so I need to use the custom build spec - but just on the local profile. The number of artifacts is quite large so it is unfeasible to patch every single one by itself. What would be the best approach here? 

### Actual behavior
Having n artifacts requires n patches inside each profile as the build specifics are set on an artifact level. Its not possible to "patch all artifacts at the same time" with json-patch (?) or apply the build spec to a level above the artifacts for inheritance.

### Expected behavior
Adding a `custom:` build spec to a profile should make all artifacts use said build spec.
Alternative: support local k3d cluster natively

```
build:
  artifacts:
    - image: app-one
      context: app/one
    - image: app-two
      context: app/two
    - image: app-three
      context: app/three

...

profiles:
  - name: local
    activation:
      - env: ENV=local
    build:
      custom: 
         # expected, but not possible
         buildCommand: ./build.sh
  - name: production
    activation:
      - env: ENV=prod
    ...

```
