### ISSUE TITLE
Logs from parallel custom builds are interleaved

### ISSUE THREAD

**Issue by tbarrella** [GoogleContainerTools/skaffold#2767]
### Actual behavior
When building in parallel with a custom builder (by specifying "cluster:"), the logs are interleaved

### Information

- Skaffold version: v0.37.0
- Operating system: Ubuntu 16.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: <repo>
    custom:
      buildCommand: ./build.sh
  - image: <repo>
    custom:
      buildCommand: ./build.sh
  cluster: {}
```

### Steps to reproduce the behavior

1. `build.sh`
```
#!/bin/bash
for i in $(seq 1 100); do
    echo "line $i"
done
```
2. `skaffold build`
