### ISSUE TITLE
Custom cluster builder tries to retrieve kaniko secret

### ISSUE THREAD

**Issue by tbarrella** [GoogleContainerTools/skaffold#2768]
### Expected behavior
Using a custom builder for in-cluster builds doesn't require a kaniko secret

### Actual behavior
If no kaniko secret exists, the build fails
```
Starting build...
Creating kaniko secret [kaniko-secret]...
FATA[0001] build failed: build failed: setting up pull secret: checking for existing kaniko secret: secrets "kaniko-secret" not found
```

### Information

- Skaffold version: v0.37.0
- Operating system: Ubuntu 16.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: <repo>
    custom:
      buildCommand: ./build.sh
  cluster: {}
```

### Steps to reproduce the behavior

1. Use any `build.sh`
2. `skaffold build`
