### ISSUE TITLE
Skaffold reports attempting to sync with wrong pods

### ISSUE THREAD

**Issue by demisx** [GoogleContainerTools/skaffold#2797]
### Expected behavior
Skaffold will sync only with pods that the file sync is enabled for and disregard everything else.

### Actual behavior
Though, Skaffold  seems to sync with the correct destination pod, it also reports not being able to sync with many other pods and a job which I didn't even ask it to sync with. This even includes pods from different namespace, e.g. "kube-system". This is what I'm seeing after modifying just one file `publish-ad.spec.ts` in default namespace. If I read the log correctly, it appears to sync in non-related pods, but skips them because they are not running at the moment.

```
INFO[1719] files modified: [api/test/request/ad/publish-ad.spec.ts] 
INFO[1720] files modified: [api/test/request/ad/publish-ad.spec.ts] 
Syncing 1 files for api.dev:fee6b6649a885c677f9ebd9b9329821ba5a6982ab97a2407f46ead41584c8ee4
INFO[1720] Copying files: map[api/test/request/ad/publish-ad.spec.ts:[/usr/src/dl/api/test/request/ad/publish-ad.spec.ts]] to api.dev:fee6b6649a885c677f9ebd9b9329821ba5a6982ab97a2407f46ead41584c8ee4 
INFO[1720] Skipping sync with pod init-db-s29wm because it's not running 
INFO[1720] Skipping sync with pod compose-6c67d745f6-tjnkb because it's not running 
INFO[1720] Skipping sync with pod compose-api-57ff65b8c7-lvtnb because it's not running 
INFO[1720] Skipping sync with pod coredns-fb8b8dccf-dbxtw because it's not running 
INFO[1720] Skipping sync with pod coredns-fb8b8dccf-pq226 because it's not running 
```

### Information

- Skaffold version: 81c50fe
- Operating system: MacOs Mojave 10.14.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kubectl:
        manifests:
          - api/app/k8s/dev/api.k8s-config.yaml
          - api/app/k8s/dev/db.k8s-config.yaml
          - api/app/k8s/dev/es.k8s-config.yaml
          - api/app/k8s/dev/postgres.k8s-deployment.yaml
          - api/app/k8s/dev/postgres.k8s-service.yaml
          - api/app/k8s/dev/init-db.k8s-job.yaml
          - api/app/k8s/dev/es.k8s-deployment.yaml
          - api/app/k8s/dev/es.k8s-service.yaml
          - api/app/k8s/dev/api.k8s-deployment.yaml
          - api/app/k8s/dev/api.k8s-service.yaml
          - web/k8s/dev/web.k8s-config.yaml
          - web/k8s/dev/web.k8s-deployment.yaml
          - web/k8s/dev/web.k8s-service.yaml
    build:
      local:
        useBuildkit: true
      artifacts:
        - image: init-db.dev
          context: .
          docker:
            dockerfile: api/Dockerfile
            target: init-db.dev
            buildArgs:
              # This namespace is developer specific
              DL_ORG_DEV_NAMESPACE: '{{.DL_ORG_DEV_NAMESPACE}}'
              DL_ORG_AWS_ACCOUNT_ID: '{{.DL_ORG_AWS_ACCOUNT_ID}}'
        # API service
        - image: api.dev
          context: .
          sync:
            manual:
              - src: 'api/test/**/*'
                dest: .
                strip: 'api'
              - src: 'api/app/src/**/*.ts'
                dest: .
                strip: 'api'
              - src: 'api/app/src/**/*.json'
                dest: .
                strip: 'api'
              - src: 'api/apidoc/**/*'
                dest: .
                strip: 'api'
          docker:
            dockerfile: api/Dockerfile
            target: api.dev
            buildArgs:
              # These vars are different per each developer and cannot be part of ConfigMap in git
              DL_ORG_DEV_NAMESPACE: '{{.DL_ORG_DEV_NAMESPACE}}'
              DL_ORG_AWS_ACCOUNT_ID: '{{.DL_ORG_AWS_ACCOUNT_ID}}'
        # Web client (Angular)
        - image: web.dev
          context: .
          sync:
            manual:
              - src: 'web/src/**/*'
                dest: .
                strip: 'web'
              - src: 'web/e2e/**/*'
                dest: .
                strip: 'web'
          docker:
            dockerfile: web/Dockerfile
            target: web.dev
    portForward:
      - resourceType: service
        resourceName: postgres
        port: 5432
      - resourceType: service
        resourceName: elasticsearch
        port: 9200
```
