### ISSUE TITLE
Add template for {{.IMAGE_REPO}} to allow substitution for init containers

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#2830]
I currently cannot get a handle for the repo used:
`skaffold deploy --default-repo=eu.gcr.io/my-project`
Could this be made available as a template so it can be used for substitution in the skaffold.yaml e.g. `{{.IMAGE_REPO}}`

I need access to it to use for main application container _but_ also for init containers.
e.g.

```
apiVersion: skaffold/v1beta13
kind: Config

build:
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_REPO}}{{.IMAGE_NAME}}:{{.USERNAME}}'
  artifacts:
    - image: app
      context: .

deploy:
  helm:
    releases:
      - name: app
        chartPath: ./helm/app
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO}}{{.IMAGE_NAME}}'          
          image.tag: '{{.USERNAME}}'
          image.repository.initcontainer1: '{{.IMAGE_REPO}}init-one'
          image.repository.initcontainer2: '{{.IMAGE_REPO}}init-two'
```

**Comment by balopat** [comment]
Thanks for detailing your use case. We've been looking at the frictions with `default-repo` and will add this to the list. As a workaround could you try to use `SKAFFOLD_DEFAULT_REPO` env var and use that in the env templates?

**Comment by dkirrane** [comment]
No joy with that unfortunately. 
I tried `skaffold deploy eu.gcr.io/my-project` but see `<no value>` for `SKAFFOLD_DEFAULT_REPO` when running the helm command. My skaffold file
```
apiVersion: skaffold/v1beta13
kind: Config

build:
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.USERNAME}}'
  artifacts:
    - image: app
      context: .
      jibMaven:

deploy:
  helm:
    releases:
      - name: app
        chartPath: ./helm/app
        setValueTemplates:
          image.repository: '{{.IMAGE_NAME}}'
          image.tag: '{{.USERNAME}}'
          image.repository.initcontainer1: '{{.SKAFFOLD_DEFAULT_REPO}}/init-one'
          image.repository.initcontainer2: '{{.SKAFFOLD_DEFAULT_REPO}}/init-two'
```
