### ISSUE TITLE
"skaffold init" should generate the new unified Jib config

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/skaffold#2843]
Once #2808 is merged, we should use the new unified Jib block. Currently, I get

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: ...
    jibMaven:
      module: demo
      args:
      - -Dimage=...
...
```

@GoogleContainerTools/java-tools-build
