### ISSUE TITLE
Make valuesFiles field on helm templatable

### ISSUE THREAD

**Issue by Markcial** [GoogleContainerTools/skaffold#2849]
### Expected behavior

When i try to deploy with my helm configuration loading files depending on environment variables.

```yaml
deploy:
  helm:
    releases:
    - name: <µs-name>
      chartPath: chart/path
      valuesFiles:
      - values/values-{{.ENVIRONMENT}}.yaml
      values:
        image: my-container
... snip... 
```

I expect the helm deployer to load the configuration file defined for that environment.

### Actual behavior

The templater doesn't apply environment variables to that field.

https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/helm.go#L262 The valuesFiles are sent to the `expandPaths` without replacing values.

The templating section https://skaffold.dev/docs/how-tos/templating/ explains that this field cannot be templated. But that field could easily be templated because the templater is declared on the same file. Thing is, there are no plans to make that field templatable?

**Comment by balopat** [comment]
Hi @Markcial, thank you for filing the issue! 

I would like to understand your use case more: 

Would the following work for you: use separate profiles per environment and override the `valuesFiles` field in the profiles? You can also activate profiles by env vars. I know this will come with some repetition, but it makes the possible environments explicit, which is typically preferred in case of environments - as users typically have env configs stored in a git repo as well. 

Templating skaffold.yaml is a highly requested feature in Skaffold and we still haven't made up our minds yet about it -  Some of the arguments against parametrization are layed down here https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/declarative-application-management.md#parameterization-pitfalls

**Comment by Markcial** [comment]
Hi @balopat, thanks for your quick reply.

For my specific case it comes with a lot of boilerplate.

I.E.:

```yaml
- name: daily
  deploy:
    helm:
      releases:
      - name: µservice
        chartPath: k8s/helm/µservice
        valuesFiles: [ k8s/helm/controller/values-daily.yaml ]
        values: { image: ecr.url/µservice }
# Profile for stage
- name: stage
  deploy:
    helm:
      releases:
      - name: µservice
        chartPath: k8s/helm/µservice
        valuesFiles: [ k8s/helm/controller/values-stage.yaml ]
        values: { image: ecr.url/µservice }
# Profile for prod
- name: prod
  deploy:
    helm:
      releases:
      - name: µservice
        chartPath: k8s/helm/µservice
        valuesFiles: [ k8s/helm/controller/values-prod.yaml ]
        values: { image: ecr.url/µservice }
```

vs

```yaml
deploy:
  helm:
    releases:
    - name: µservice
      chartPath: k8s/helm/µservice
      valuesFiles: [ k8s/helm/controller/values-{{.ENV}}.yaml ]
      values: { image: ecr.url/µservice }
```

Currently we have separated profiles but i was looking to trim down some lines for our several microservices.

In case the feature is approved i feel confident enough to make a PR with the changes to make this work.
