### ISSUE TITLE
Skaffold init uses incorrect image with single jib config + single k8s manifest

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/skaffold#2852]
I have a single-module maven project setup with a k8s yaml that points to `gcr.io/k8s-skaffold/project1`:
```
apiVersion: apps/v1
kind: Deployment
...
      containers:
      - name: web1
        image: gcr.io/k8s-skaffold/project1
        ports:
          - containerPort: 8080
...
```

I have Jib setup to point to a different image, `gcr.io/tcordle-test/abc`:
```
...
<configuration>
  <to><image>gcr.io/tcordle-test/abc</image></to>
</configuration>
...
```

When I run `skaffold init --XXenableJibInit`, the prompt is skipped because there's only one image and one builder. However, the output has Jib building to its own target image, instead of what's defined in the k8s manifest.

```
$ skaffold init --XXenableJibInit
apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: gcr.io/tcordle-test/abc
    jibMaven: {}
deploy:
  kubectl:
    manifests:
    - k8s/web.yaml
```

The expected behavior is that the `jibMaven` block will contain an arg (`-Dimage=gcr.io/k8s-skaffold/project1`) that will make sure it tags the image correctly.
