### ISSUE TITLE
Skaffold is not injecting the autogenerated dateTime tag into Helm values

### ISSUE THREAD

**Issue by none-da** [GoogleContainerTools/skaffold#2856]
### Expected behavior
Skaffold should inject the generated dateTime tag into Helm's values properly.

### Actual behavior
Skaffold is not injecting the generated dateTime tag into Helm's values, but instead taking the digest value always.

### Information

- Skaffold version: v0.37.1
- Operating system: MacOS Mojave 10.14.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: local/hello-universe
    context: hello-universe-flask-app
  tagPolicy:
    dateTime:
      timezone: "Local"
deploy:
  statusCheckDeadlineSeconds: 10
  helm:
    releases:
    - name: v1
      chartPath: "hello-universe-chart"
      wait: true
      recreatePods: true
      values:
        image: local/hello-universe
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project : https://github.com/none-da/test_skaffold_helm
2. `skaffold <command>` : skaffold run  --tail --skip-tests -v debug
3. Prints:

```
Generating tags...
 - local/hello-universe -> local/hello-universe:2019-09-11_17-23-19.057_IST
```

But the command that is fed to helm is:

```
DEBU[0000] Running command: [helm --kube-context docker-desktop install --name v1 hello-universe-chart --wait --set image=local/hello-universe:59268a9ef3ecf2e38590b917985bc0a75711a304615d9522b5cc3cab5ee4b8d4]
```
