### ISSUE TITLE
Error parsing YAML

### ISSUE THREAD

**Issue by alejandrox1** [GoogleContainerTools/skaffold#2858]
### Expected behavior
Have this bit of yaml:
```yaml
---                                                                             
# ServiceAccount for our app.                                                   
apiVersion: v1                                                                  
kind: ServiceAccount                                                            
metadata:                                                                       
  name: pod-manager                                                             
---                                                                             
apiVersion: rbac.authorization.k8s.io/v1                                        
kind: Role                                                                      
metadata:                                                                       
  name: pod-manager                                                             
  namespace: default                                                            
rules:                                                                          
 - apiGroups:                                                                   
   - ""                                                                         
   resources:                                                                   
   - "pods"                                                                     
   verbs:                                                                       
   - "get"                                                                      
   - "list"                                                                     
   - "watch"                                                                    
   - "create"                                                                   
   - "update"                                                                   
   - "patch"                                                                    
   - "delete"
---                                                                             
# Bind "pod-manager" Role to "pod-manager" ServiceAccount.                      
apiVersion: rbac.authorization.k8s.io/v1                                        
kind: RoleBinding                                                               
metadata:                                                                       
  name: pod-manager                                                             
  namespace: default # This only grants permissions within the "default" namespace.
subjects:                                                                       
- kind: ServiceAccount                                                          
  name: pod-manager                                                             
  apiGroup: ""                                                                  
roleRef:                                                                        
  kind: Role #this must be Role or ClusterRole                                  
  name: pod-manager # this must match the name of the Role or ClusterRole you wish to bind to.
  apiGroup: rbac.authorization.k8s.io                                           
---                                                                             
apiVersion: apps/v1                                                             
kind: Deployment                                                                
metadata:                                                                       
  name: pod-manager                                                             
  labels:                                                                       
    app: pod-manager                                                            
spec:                                                                           
  replicas: 1                                                                   
  selector:                                                                     
    matchLabels:                                                                
      app: pod-manager                                                          
  template:                                                                     
    metadata:                                                                   
      labels:                                                                   
        app: pod-manager                                                        
    spec:                                                                       
      containers:                                                               
      - name: pod-manager                                                       
        image: <image>
```

### Actual behavior
When I run skaffold (`skaffold dev -v debug`) it returns with the following error:
```
...
DEBU[0000] manifests apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: default
rules:
---
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-manager
subjects:
---
- apiGroup: ""
  kind: ServiceAccount
  name: pod-manager
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pod-manager
  name: pod-manager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-manager
  template:
    metadata:
      labels:
        app: pod-manager
    spec:
      containers:
      - image: alejandrox1
        name: pod-manager 
DEBU[0000] Running command: [kubectl --context kubernetes-admin@kind delete --ignore-not-found=true -f -] 
error parsing STDIN: error converting YAML to JSON: yaml: line 12: did not find expected '-' indicator
WARN[0000] deployer cleanup: delete: kubectl delete: exit status 1 
FATA[0000] exiting dev mode because first deploy failed: get images from manifests: reading kubernetes YAML: yaml: line 12: did not find expected '-' indicator
```

### Information

- Skaffold version: v0.37.1
- Operating system: Ubuntu 19.04
