### ISSUE TITLE
Error adding watch for files

### ISSUE THREAD

**Issue by garvincasimir** [GoogleContainerTools/skaffold#287]
### Expected behavior
Watch should be added for Dockerfile and other deps
### Actual behavior
Error:
adding watch for C:\Users\garvin\projects\kube-task\job\Dockerfile: The parameter is incorrect

### Information
I looked at the code and the error seems to be coming from here:
https://github.com/GoogleCloudPlatform/skaffold/blob/739a5048151dc610956fa7117075add73bff1795/pkg/skaffold/watch/watch.go#L202

Perhaps this is an issue with http://github.com/rjeczalik/notify and Windows?

Skaffold version: v0.2.0
Operating system: Windows 10 pro (build 16299)
Content of skaffold.yaml: 
```
apiVersion: skaffold/v1alpha1
kind: Config
build:
  artifacts:
  - imageName: localhost:5000/kube-task 
    workspace: C:\Users\garvin\projects\kube-task\job
  local: {}
deploy:
  kubectl:
    manifests:
    - paths:
      - k8s/*
      parameters:
        KUBE-TASK: localhost:5000/kube-task
```
### Steps to reproduce the behavior

  1. Run skaffold dev
  2. Error appears after pod deployment
