### ISSUE TITLE
Pods created by Helm hooks are not removed in dev mode

### ISSUE THREAD

**Issue by kvokka** [GoogleContainerTools/skaffold#2876]
The pods, which were created by Helm chart hooks are not deleted after termination of `skaffold dev`.

### Expected behavior

Everything, created by the chart in dev move should be deleted

### Actual behavior

The product of Helm

```
  annotations:
    "helm.sh/hook": post-install
```

hook is still in place.

### Information

- Skaffold version: version 0.38
- Operating system: MacOs 10.14.6
- Contents of skaffold.yaml: 

```yaml
apiVersion: skaffold/v1beta14
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: poker-core
      context: core
      docker:
        dockerfile: docker/development/Dockerfile
deploy:
  helm:
    releases:
      - name: poker-core
        chartPath: core/charts/poker-core
        recreatePods: true
        valuesFiles:
          - core/charts/poker-core/values.yaml
          - core/charts/poker-core/values.development.yaml
```
