### ISSUE TITLE
Can not push skaffold to re-create Helm hook resource

### ISSUE THREAD

**Issue by kvokka** [GoogleContainerTools/skaffold#2877]
### Expected behavior

With deploy helm option `recreatePods: true` expected, that all resources should be re-created. 

### Actual behavior

```bash
$ skaffold dev
...
Error: pods "poker-core-db-migrate" already exists
Cleaning up...
release "poker-core" deleted
Cleanup complete in 997.567658ms
FATA[0005] exiting dev mode because first deploy failed: deploying poker-core: exit status 1
```

### Information

```yaml
apiVersion: skaffold/v1beta14
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: poker-core
      context: core
      docker:
        dockerfile: docker/development/Dockerfile
deploy:
  helm:
    releases:
      - name: poker-core
        chartPath: core/charts/poker-core
        recreatePods: true
        valuesFiles:
          - core/charts/poker-core/values.yaml
          - core/charts/poker-core/values.development.yaml
```
