### ISSUE TITLE
Fix hardcoded config version in `generate-pipeline` testing.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#2889]
### Expected behavior
When generating a new skaffold version, all integration tests should pass as is.

### Actual behavior
On Pr #2881, the following integration test failed
```
--- FAIL: TestGeneratePipeline (0.27s)
    --- PASS: TestGeneratePipeline/no_profiles (0.06s)
    --- PASS: TestGeneratePipeline/existing_oncluster_profile (0.05s)
    --- PASS: TestGeneratePipeline/existing_other_profile (0.08s)
    --- PASS: TestGeneratePipeline/multiple_skaffold.yamls_to_create_pipeline_from (0.05s)
    --- FAIL: TestGeneratePipeline/user_example (0.03s)
        generate_pipeline_test.go:139: Contents of examples/generate-pipeline/skaffold.yaml did not match those of examples/generate-pipeline/expectedSkaffold.yaml
            got:apiVersion: skaffold/v1beta15
            kind: Config
            build:
              artifacts:
              - image: gcr.io/k8s-skaffold/pipeline-example
            deploy:
              kubectl:
                manifests:
                - k8s-*
            profiles:
            - name: oncluster
              build:
                artifacts:
                - image: gcr.io/k8s-skaffold/pipeline-example-pipeline
                  context: .
                  kaniko:
                    buildContext:
                      gcsBucket: skaffold-kaniko
                tagPolicy:
                  gitCommit: {}
                cluster:
                  pullSecretName: kaniko-secret
            want:apiVersion: skaffold/v1beta14
            kind: Config
            build:
              artifacts:
              - image: gcr.io/k8s-skaffold/pipeline-example
            deploy:
              kubectl:
                manifests:
                - k8s-*
            profiles:
            - name: oncluster
              build:
                artifacts:
                - image: gcr.io/k8s-skaffold/pipeline-example-pipeline
                  context: .
                  kaniko:
                    buildContext:
                      gcsBucket: skaffold-kaniko
                tagPolicy:
                  gitCommit: {}
                cluster:
```
We don't need to compare `skaffold.yaml` as there are other integration tests that do that.
### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...
