### ISSUE TITLE
Allow Absolute paths for file sync

### ISSUE THREAD

**Issue by grantstephens** [GoogleContainerTools/skaffold#2898]
It would be very useful to be able to use local absolute filepaths for sync, such as: 
```
    sync:
      manual:
        - src: "/home/user/.config/**"
          dest: "/config/"
```
This is not possible via the docker image and symlinks also do not work. Open to any other suggestions if there is another way around this.

**Comment by tstromberg** [comment]
I can see the use case - but I'm curious if anyone else is running into this? 

If someone wants to introduce it, I'd be happy to review a PR for it.

**Comment by grantstephens** [comment]
The one use case we have at the moment is using your local config from `~` for certain binaries for example. The other is for copying those binaries from where they live locally to the remote instance. At the moment we run a script before scaffold that copies all the needed config and binaries to a build directory which is then used by the dockerfile. 

I'd be happy to take a stab at it if there is more interest.

**Comment by nkubala** [comment]
@grantstephens I think that makes sense, would you mind submitting a small design proposal for this before you open a PR? I'm happy to review it when you do, I just want to make sure the design fits before you start writing a bunch of code that would be at risk of needing changes.

**Comment by grantstephens** [comment]
Sure, but I don't think I'm going to have time to do it anytime soon. Is there a template for the design proposal?

**Comment by nkubala** [comment]
https://github.com/GoogleContainerTools/skaffold/blob/master/docs/design_proposals/design-proposal-template.md

**Comment by glenbot** [comment]
@nkubala @tstromberg  I'm interested in this feature as well and am willing to submit a PR for this. After looking at the code I can see that the syncable paths are all compiled up front and it isn't until the filemon event is triggered that it matches the manual sync rules so I think it would make sense to add another key to the build artifact that allows extra paths to be injected up front and then match rules later. I wanted to run this yaml key by you all and see if it makes sense:

```
apiVersion: skaffold/v2betaXX
kind: Config
build:
  artifacts:
    - image: imageXX
      context: /path # paths get injected from here and Dockerfile commands
      extra_sync_paths: # extra paths to append to the context
        - /path2
        - /path3
      sync:
        manual:
          - src: '**/*.py'
            dest: /path
          - src: '/path2/**/*.py'
            dest: /path2
          - src: '/path3/**/*.py'
            dest: /path3
```

Adding the key `extra_sync_paths` will allow a person to add the paths they need to be monitored and then creates rules based on the extra paths.
