### ISSUE TITLE
imageStrategy Helm broken since v0.38, possibly v0.37

### ISSUE THREAD

**Issue by MisterTimn** [GoogleContainerTools/skaffold#2902]
### Expected behavior
Skaffold dev or run resulting in deployed and running pods

### Actual behavior
InvalidImageName errors on pods because the imageStrategy: helm option on skaffold config isnt respected
Actual image name becomes: `imageName:imageName` instead of `imageName:tag`

Tested on multiple of my projects. I then reverted to 0.36 because I knew this was the last version on which my deployments worked, and there I had no issues. (Yes I ran skaffold fix --overwrite true before I ran skaffold dev/run)

### Information

- Skaffold version: version 0.38
- Operating system: Manjaro Arch
- Contents of skaffold.yaml: 

```yaml
apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: gitlab.ilabt.imec.be:4567/dyversify/demo-controller
    context: .
    jib: {}
deploy:
  helm:
    releases:
    - name: skaffold-demo-controller
      chartPath: helm/demo-controller
      valuesFiles:
      - helm/dyversify-values.yaml
      values:
        image: gitlab.ilabt.imec.be:4567/dyversify/demo-controller
      namespace: default
      recreatePods: true
      imageStrategy:
        helm: {}
profiles:
- name: obelisk-staging
  patches:
  - op: replace
    path: /deploy/helm/releases/0/valuesFiles/0
    value: helm/obelisk-staging-values.yaml
  activation:
  - kubeContext: obelisk-staging
- name: dyversify
  patches:
  - op: replace
    path: /deploy/helm/releases/0/valuesFiles/0
    value: helm/dyversify-values.yaml
  activation:
  - kubeContext: dyversify
```

### Steps to reproduce the behavior

Cant expose my codebase, but basically run any project which uses the default Helm config 
```yaml
containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```

And use in your skaffold.yaml
```yaml
 deploy:
  helm:
      imageStrategy:
        helm: {}
```
and it will give you the double imageNames resulting in an error.
