### ISSUE TITLE
Hot reloading not working on Linux Mint 

### ISSUE THREAD

**Issue by timsayshey** [GoogleContainerTools/skaffold#2915]
### Expected behavior

Expected Skaffold to hot reload on file changes like it does on my Mac.

### Actual behavior

Skaffold not hot reloading when files are updated on Linux.

### Information

- Skaffold version: v0.38.0
- Operating system: Linux Mint 19.2
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
    - image: gcr.io/a-k8s-poc/api-gateway
      context: ./services/api-gateway
    - image: gcr.io/a-k8s-poc/member-service
      context: ./services/member

deploy:
  kubectl:
    manifests:
      - ./services/api-gateway/k8s/local/*
      - ./services/member/k8s/local/*
```

### Steps to reproduce the behavior

1. Install Linux and try updating a file in any application while Skaffold is running.
2. Get no response. No hot reloading.
