### ISSUE TITLE
Unable to use skaffold builder - archive/tar: invalid tar header 

### ISSUE THREAD

**Issue by Edke** [GoogleContainerTools/skaffold#2939]
### Expected behavior

`skaffold dev` uses `bazel` for image build, than image is re-tagged according to `skaffold.yaml`

### Actual behavior

It fails with message:  
```FATA[0002] exiting dev mode because first build failed: build failed: build failed: building [project-dev1]: build artifact: loading image into docker daemon: reading from image load response: Error processing tar file(exit status 1): archive/tar: invalid tar header `

### Information

- Skaffold version: v0.38.0
- bazel version: 0.29.1
- Operating system: Arch Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: project-dev1
    context: .
    bazel:
      target: //:app-img
      args:
        - --compilation_mode=dbg
        - --features=pure
  - image: project-dev2
    context: .
    bazel:
      target: //app:app-img
      args:
        - --compilation_mode=dbg
        - --features=pure
```

### Steps to reproduce the behavior

1. `git clone https://github.com/Edke/skaffold-bazel-bug.git`
2. `bazel build //:app-img`  -> works
3. `bazel build //app:app-img` -> works
4. `skaffold dev` -> fails with error msg above, complete output in [bug's repo README.md](https://github.com/Edke/skaffold-bazel-bug)

More notes:

- on Arch python is python3, therefore configured project calls python2 during `pip install`
- I prepared both in root BUILD target and in subfolder, `skaffold` is configured for both, as I found multiple issues where different behavior was reported depending on location of target. Both variations fail with same problem
