### ISSUE TITLE
skaffold deploy -p fails because of missing tag for build even with build: null

### ISSUE THREAD

**Issue by andreassiegel** [GoogleContainerTools/skaffold#2947]
I'm using a profile in my `skaffold.yaml` that is supposed to just deploy some general infrastructure components, like databases, nothing related to my application.
Therefore, I don't want to build anything.

As far as I remember, this used to work fine:
```yaml
profiles:
  - name: infra
    build: null
    deploy:
      helm:
        releases:
          - name: mysql
            chartPath: helm-charts/mysql
            namespace: infra
```

### Expected behavior

Nothing is built, regardless of what is defined in the main config.

### Actual behavior

`skaffold deploy -p infra` fails:
```
You either need to:
run [skaffold deploy] with [--images TAG] for each pre-built artifact
or [skaffold run] instead, to let Skaffold build, tag and deploy artifacts.
FATA[0000] no tag provided for image [myservice]
```

`skaffold run -p infra` works, but it will also build the service, although `build` is set to `null`.
I also tried to omit `build` or set it to `{}`. The outcome was always the same:

Everything is built but only what's defined in the profile is deployed.

### Information

- Skaffold version: 0.38.0
- Operating system: macOS 10.14.5 (Mojave)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config

build:
  artifacts:
    - image: myservice
      context: .
      sync:
        manual:
          - src: services/myservice/src/**
            dest: .
            strip: services/myservice/
          - src: services/myservice/package.json
            dest: .
            strip: services/myservice/
          - src: services/myservice/node_modules/**
            dest: .
            strip: services/myservice/
      custom:
        buildCommand: "scripts/dockerBuild.sh start:dev root"
        dependencies:
          paths:
            - services/myservice/Dockerfile
            - services/myservice/package.json
            - services/myservice/src
            - services/myservice/node_modules
  local: {}

deploy:
  helm:
    releases:
      - name: myservice
        chartPath: helm-charts/myservice
        valuesFiles:
          - environment/local/myservice/values.yaml
        values:
          image: myservice
        namespace: services

profiles:
  - name: infra
    build: null
    deploy:
      helm:
        releases:
          - name: mysql
            chartPath: helm-charts/mysql
            namespace: infra
```

### Steps to reproduce the behavior

FAILS:
```bash
$ skaffold deploy -p infra
You either need to:
run [skaffold deploy] with [--images TAG] for each pre-built artifact
or [skaffold run] instead, to let Skaffold build, tag and deploy artifacts.
FATA[0000] no tag provided for image [myservice] 
```

Does more than intended:
```yaml
$ skaffold run -p infra
Generating tags...
 - myservice -> myservice:...
Tags generated in 24.948377ms
Checking cache...
 - myservice: Found. Tagging

[...]

Starting deploy...

[...]

Deploy complete in 9.318812716s
You can also run [skaffold run --tail] to get the logs
```

**Comment by priyawadhwa** [comment]
Hey @andreassiegel would you be able to provide the project you are working on? I tried to reproduce this bug with the following skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta14
kind: Config
deploy:
  kubectl:
    manifests: 
    - pod.yaml
profiles:
- name: deploy
  deploy:
    helm:
      releases:
      - name: mychart
        chartPath: mychart
```

and a simple helm chart deploying a Pod with a busybox container. Both `skaffold run -p deploy` and `skaffold deploy -p deploy` worked as expected. Could you provide your project, or provide one with the same bug, so that we can reproduce this issue?

**Comment by andreassiegel** [comment]
Unfortunately, I can't share the actual project, but I'll try to reproduce the problem with a sample project I can share. I'll update the issue once I got the chance to set that up.

**Comment by DrDonk** [comment]
I am also having this same issue. Not using the profile switch but all my projects no longer deploy even if I specify the image tag. I can't share the project either as it is proprietary contract I am working on.

**Comment by tejal29** [comment]
I think this was introduced by #2784

**Comment by tejal29** [comment]
These `skaffold.yaml` works:

1.  no profiles and no build config
```
tejaldesai@@getting-started (reset-on-deploy)$ cat skaffold.yaml 
apiVersion: skaffold/v1beta14
kind: Config
build: null
deploy:
  kubectl:
    manifests:
      - k8s-*
```

2. profile with null build config. 
```
tejaldesai@@getting-started (reset-on-deploy)$ cat skaffold.yaml 
apiVersion: skaffold/v1beta14
kind: Config
build: null
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: infra
    build: null
    deploy:
      kubectl:
        manifests
```

Also, this deploy does not work anymore on this config which is expected
```
tejaldesai@@getting-started (reset-on-deploy)$ cat skaffold.yaml 
apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
```
```
tejaldesai@@getting-started (reset-on-deploy)$ ../../out/skaffold deploy
You either need to:
run [skaffold deploy] with [--images TAG] for each pre-built artifact
or [skaffold run] instead, to let Skaffold build, tag and deploy artifacts.
FATA[0000] no tag provided for image [gcr.io/k8s-skaffold/skaffold-example] 
tejaldesai@@getting-started (reset-on-deploy)$ ../../out/skaffold run

```

**Comment by andreassiegel** [comment]
Cool, I'm glad you were able to reproduce the issue.

I ran into it again when I was working with another machine that still had an older skaffold version installed yesterday, so I can confirm that the issue must have been introduced recently.

I also was about to set up a sample project I can share to help reproduce the problem. This doesn't seem necessary anymore. Otherwise, just let me know.

In any case, I'm happy to verify an upcoming fix as soon as it becomes available.

**Comment by dgageot** [comment]
The real issue here is that `build: null` doesn't clear the default build section out. `skaffold deploy` used to kinda work because, before #2784, we weren't testing for missing tag (which was introducing a whole set of errors).

You can check the final `skaffold.yaml` with `skaffold diagnose -o profile`. You should see that the default build section is still there.

One way to actually remove it is with:

```
apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/skaffold-example
profiles:
  - name: no-build
    patches:
    - op: replace
      path: /build
      value: null
```

**Comment by dgageot** [comment]
When #3045 is merged, you will also be able to use this shorter and clearer syntax:

```
apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/skaffold-example
profiles:
  - name: no-build
    patches:
    - op: remove
      path: /build
```
