### ISSUE TITLE
No logs being tailed (Helm deployment + skaffold v0.39)

### ISSUE THREAD

**Issue by MisterTimn** [GoogleContainerTools/skaffold#2962]
### Expected behavior
Logs get tailed after skaffold dev|run

### Actual behavior
No logs are tailed.
I reported the same issue a while ago in #2040 
Im now running v0.37b again (v0.38 had issue #2902 which made me already revert). 

### Information

- Skaffold version: version 0.39
- Operating system: Manjaro Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
  - image: gitlab.ilabt.imec.be:4567/ibcndevs/dyversify/scaling-demo-datagenerator
    context: .
    jib: {}
deploy:
  helm:
    releases:
    - name: skaffold-scaling-demo-datagenerator
      chartPath: helm/scaling-demo-datagenerator
      valuesFiles:
      - helm/dyversify-values.yaml
      values:
        image: gitlab.ilabt.imec.be:4567/ibcndevs/dyversify/scaling-demo-datagenerator
      namespace: default
      recreatePods: true
      imageStrategy:
        helm: {}
profiles:
- name: obelisk-staging
  patches:
  - op: replace
    path: /deploy/helm/releases/0/valuesFiles/0
    value: helm/obelisk-staging-values.yaml
  activation:
  - kubeContext: obelisk-staging
- name: dyversify
  patches:
  - op: replace
    path: /deploy/helm/releases/0/valuesFiles/0
    value: helm/dyversify-values.yaml
  activation:
  - kubeContext: dyversify
```

### Steps to reproduce the behavior

Run skaffold dev with a helm deployment.
