### ISSUE TITLE
Add includeTar/includeTools in sync block

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/skaffold#2979]
This would allow containers that otherwise do not have the necessary container side tooling to use the skaffold sync features.

```yaml
sync:
  includeTar: true
  # or 
  includeTools: true
```

more context: https://github.com/GoogleContainerTools/skaffold/pull/2901#discussion_r325428048
