### ISSUE TITLE
--tail No Longer Works in Deploy Mode

### ISSUE THREAD

**Issue by cliffburdick** [GoogleContainerTools/skaffold#2981]
I was previously running v0.20.0, and running the following command:

`skaffold-0.20.0 deploy --tail -f skaffold-96eb58.yaml  --images myimage:1.0`

This worked fine, and the logs would tail properly, except for this bug: #1753 

In that thread it was mentioned that 0.39.0 fixes this, so I tried it. Now, --tail no longer gives any output, even though I can see it in kubectl log. I'm also not sure if I should see a kubectl process showing the tailed logs, but I don't see those.

### Expected behavior

Logs are tailed

### Actual behavior

No logs visible

### Information

- Skaffold version: 0.39.0
- Operating system: Ubuntu 18.04
- Contents of skaffold.yaml:

```
apiVersion: skaffold/v1beta15
build:
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.SALT}}'
deploy:
  kubectl:
    manifests:
    - depman-96eb58.yaml*
kind: Config
```

### Steps to reproduce the behavior

1. Use skaffold deploy --tail with any image.
