### ISSUE TITLE
helm: overrides should override passed valuesFiles

### ISSUE THREAD

**Issue by theEndBeta** [GoogleContainerTools/skaffold#2994]
### Expected behavior

Values passed to `overrides` in the helm deployer should override values passed in via `valuesFiles`.

### Actual behavior

`valuesFiles` overrides `overrides`.

### Information

- Skaffold version: 0.38.0
- Operating system: macos 10.14.6
- Contents of skaffold.yaml:

```yaml
      helm:
        flags:
          global:
            - "--debug"
        releases:
          - name: dep-name
            namespace: default
            chartPath: ./deployment
            valuesFiles:
              - deployment/values.yaml
              - deployment/values.dev.yaml
            setValues:
              value1: "this"
            overrides:
              extrajs:
                overrideFile: "{{ .Files.Get \"extrajs/override.js\" }}"

```

As far as I can tell, adding `-f overrides.yaml` after the `valuesFiles` files (rather than before like it is now) should produce this behavior.

**Comment by balopat** [comment]
This makes sense to me. Mostly because overrides is finer grained but also because "overrides" as a term is more suggestive towards higher precedence. Yes, flipping the order of these two blocks should do the trick:

https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/helm.go#L244-L265

However, as Helm deployer is in beta, I would take care, because this might break people according to our [Deprecation policy](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/helm.go#L244-L265). 

If we can come up with a structure that is "auto-upgradable" that's the best of both worlds. 

One idea I had was to rename `overrides` to `content` under `values.files` - this way:

```
helm:
        flags:
          global:
            - "--debug"
        releases:
          - name: dep-name
            namespace: default
            chartPath: ./deployment
            values:
               set:
                  - value1: "this"
               files: 
                 - path: deployment/values.yaml
                 - path: deployment/values.dev.yaml
                 - content:
                      extrajs:
                         overrideFile: "{{ .Files.Get \"extrajs/override.js\" }}"               
```

This would match the [helm spec](https://github.com/helm/helm/blob/master/docs/using_helm.md#customizing-the-chart-before-installing) much better and we would document the precedence rules similarly according to that.
