### ISSUE TITLE
Improve support for registries with self-signed certs (x509: certificate signed by unknown authority)

### ISSUE THREAD

**Issue by balchua** [GoogleContainerTools/skaffold#3039]
### Expected behavior
Skaffold should allow the use of private registries using self signed certificates.

### Actual behavior
Skaffold complains about the certificate being signed by unknown authority.

### Information

- Skaffold version: tested with bleeding edge (the version with `skipTLS` option)
- Operating system: RedHat 7.5.
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta15
kind: Config
profiles:
 - name: sub
    build:
      artifacts:
      - image: my-private-registry.com/balchu/gonuts-sub
        context: sub
        kaniko:
          dockerfile: Dockerfile
          skipTLS: true
          buildContext:
            localDir: {}
          cache:
            repo: my-private-registry.com/balchu/gonuts-sub          
      cluster:
        dockerConfig: 
          secretName: regcred
        namespace: gonuts
      insecureRegistries: #Use this for local registry.  such as microk8s registry.
      - my-private-registry.com
    deploy:
      helm:
        releases:
          - name: gonuts-sub
            chartPath: k8s-manifest/sub
            namespace: gonuts
            wait: true
            values:
              image.repository: my-private-registry.com/balchu/gonuts-sub
```

### Steps to reproduce the behavior

1. Find a private registry with a self signed certificate
2. Make sure your Dockerfile's base images are also using the private registry.

For example:

```
# Use base golang image from Docker Hub
FROM my-private-registry.com/golang:1.12.10 as build

WORKDIR /src/github.com/balchua/gonuts

# Copy go.mod and go.sum 
ADD ./go.mod /src/github.com/balchua/gonuts/
ADD ./go.sum /src/github.com/balchua/gonuts/
# Install dependencies in go.mod and go.sum
RUN go mod download

# Copy application source code
COPY ./main.go /src/github.com/balchua/gonuts

# Compile the application to /app.
RUN go build -o /app -v .

# Now create separate deployment image
FROM my-private-registry.com/distroless/base
COPY --from=build /app /app
# Cause full tracebacks; also serves to identify this image as a Go image for `skaffold debug`
ENV GOTRACEBACK=all
ENTRYPOINT ["/app"]
```
Skaffold complains about the private registry's certificates and then it fails.  It does not even start the Kaniko pod.

Thanks!

**Comment by raul1991** [comment]
I am getting the same error as well. Is there any workaround yet ?

**Comment by balopat** [comment]
Hi, thanks for opening, can you share logs please?

**Comment by balchua** [comment]
@balopat its a bit tricky to provide the logs.  Company policy restricts it.  Maybe @raul1991 can help provide logs.

**Comment by raul1991** [comment]
Ill have a problem sharing the complste logs too. Let me clean them a little and I'll post it then.

**Comment by balopat** [comment]
@raul1991 I see that these are minikube docker daemon logs - can you try following https://minikube.sigs.k8s.io/docs/tasks/registry/insecure/ to setup the insecure registry for the daemon? Unfortunately this is not something Skaffold can do currently to reconfigure the daemon inside minikube. 

@balchua would you be able to send the exact error message at least? That can help identify which part of the process we are failing. Thanks!

**Comment by balchua** [comment]
Hi @balopat im taking some screenshot and upload it here.

But i got it working somehow.  Strangely enough if i have an environment variable `DOCKER_CERT_PATH` set to the same location where i keep certs needed to talk to docker daemon i get past the point where kaniko pods starts and builds successfully.
I digged through the code and it actually goes thru the code path where the docker api is used.  
It arrives to this line.
https://github.com/GoogleContainerTools/skaffold/blob/057c22a9e85ea7d5a4060f7ff8f552c524d70643/pkg/skaffold/docker/client.go#L57

The docker api actually gets all those environment variables it needs such as `DOCKER_HOST` and `DOCKER_CERT_PATH`.

Just right after kaniko completes the build it fails again somewhere here.

https://github.com/GoogleContainerTools/skaffold/blob/b7589881c2a9fff57aed951fae1261cd17543aa3/pkg/skaffold/docker/remote.go#L94

**Comment by balchua** [comment]
![before-kaniko-pod-starts](https://user-images.githubusercontent.com/28750768/67094954-670aa100-f1e7-11e9-98dd-8094ce95bcff.jpg) - This screenshot is the error i get before adding the `DOCKER_CERT_PATH` environment variable.  The kaniko pod was not started.

![after kaniko-build-completes](https://user-images.githubusercontent.com/28750768/67095065-9f11e400-f1e7-11e9-81ec-bbd1a1bf45cd.jpg) - This screenshot is the error i get if I do not set `SSL_CERT_FILE` environment variable.

**Comment by balchua** [comment]
Although this issue https://github.com/GoogleContainerTools/skaffold/issues/3116 is talking about jib, i think it could be related.

**Comment by balopat** [comment]
@balchua thanks for sharing the screenshots!!!
As a workaround - can you try if `--cache-artifacts=false` helps with the post-failure - I think that is code path that is trying to get the remote config from the registry and fails...

**Comment by balchua** [comment]
@balopat will give this a go. Thanks

**Comment by balchua** [comment]
@balopat, same error `x509: certificate signed by unknown authority`

**Comment by bframke** [comment]
Is there some progress on this problem? I've just started using skaffold and get the same problem with the certificate.

```
Generating tags...
 - registry.xxx/registry/go-operator-module -> registry.xxx/registry/go-operator-module:2e754c3-dirty
Building [registry.xxx/registry/go-operator-module]...
build ./src/go/go/main: cannot find module for path ./src/go/go/main
Sending build context to Docker daemon  87.56MB
Step 1/4 : FROM debian
 ---> 8e9f8546050d
Step 2/4 : COPY ./go-operator-module /go-operator-module
 ---> Using cache
 ---> 610911483e88
Step 3/4 : COPY ./deployment/crd.yaml /deployment/crd.yaml
 ---> Using cache
 ---> 90ff482e8478
Step 4/4 : ENTRYPOINT /go-operator-module
 ---> Using cache
 ---> 92744d03147b
Successfully built 92744d03147b
Successfully tagged registry.xxx/registry/go-operator-module:latest
The push refers to repository [registry.xxx/registry/go-operator-module]
c622176a9d88: Layer already exists 
29a9b55cfb86: Layer already exists 
831b66a484dc: Layer already exists 
latest: digest: sha256:4da361823cf991e69eab6fb2b43cba2a959b406400928510ea97576c9ffcaafb size: 949
FATA[0002] failed to build: build failed: building [registry.xxx/registry/go-operator-module]: build artifact: getting image: Get https://registry.xxx:443/v2/: x509: certificate signed by unknown authority 
```

```
apiVersion: skaffold/v1
kind: Config
metadata:
  name: go-operator-module
build:
  artifacts:
    - image: registry.xxx/registry/go-operator-module
      custom:
        buildCommand: ./build.sh
  insecureRegistries: ["registry.xxx"]
```
