### ISSUE TITLE
Unable to remove a section with a Profile using a `remove` patch

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#3044]
### Expected behavior

Profiles can be used to remove values in `skaffold.yaml`.
For example, this `no-build` profile can be used to remove the `build` section:

```
apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/skaffold-example
profiles:
  - name: no-build
    patches:
    - op: remove
      path: /build
```

### Actual behavior

`op: remove` never removes any value.
