### ISSUE TITLE
auth/oidc.(*oidcAuthProvider).idToken: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#3047]
Facing random error with .kubeconfig file, it goes on relogin to cluster

### Actual behavior
```
 - redactedpythonserver: Not found. Building                                                        [268/1876]
Cache check complete in 558.200049ms
Starting build...
DEBU[0000] getting client config for kubeContext: ``
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14b0d3f]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/oidc.(*oidcAuthProvider).idToken(0xc0007c92f0, 0x0, 0x0, 0x0, 0x0)
        vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go:281 +0x70f
k8s.io/client-go/plugin/pkg/client/auth/oidc.(*roundTripper).RoundTrip(0xc000782e20, 0xc000174800, 0x1a19dc7, 0xa, 0xc00057c200)
        vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go:199 +0x7d
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc000782e40, 0xc000174700, 0xc000782e40, 0x0, 0x0)
        vendor/k8s.io/client-go/transport/round_trippers.go:159 +0x1c2
net/http.send(0xc000174700, 0x1c9e140, 0xc000782e40, 0x0, 0x0, 0x0, 0xc0003b4790, 0xc0009eac18, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:250 +0x461
net/http.(*Client).send(0xc0007c9dd0, 0xc000174700, 0x0, 0x0, 0x0, 0xc0003b4790, 0x0, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:174 +0xfb
net/http.(*Client).do(0xc0007c9dd0, 0xc000174700, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:641 +0x279
net/http.(*Client).Do(0xc0007c9dd0, 0xc000174700, 0x0, 0x83, 0x0)
        /usr/local/go/src/net/http/client.go:509 +0x35
k8s.io/client-go/rest.(*Request).request(0xc000214900, 0xc0009eaec8, 0x0, 0x0)
        vendor/k8s.io/client-go/rest/request.go:754 +0x330
k8s.io/client-go/rest.(*Request).Do(0xc000214900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        vendor/k8s.io/client-go/rest/request.go:828 +0xd8
k8s.io/client-go/kubernetes/typed/core/v1.(*secrets).Get(0xc000770220, 0xc0005560f0, 0x2e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000cea80, ...)
        vendor/k8s.io/client-go/kubernetes/typed/core/v1/secret.go:73 +0x193
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cluster.(*Builder).setupDockerConfigSecret(0xc0003c20c0, 0x1c9e720, 0xc00000e018, 0x2, 0x1b, 0x0)
        pkg/skaffold/build/cluster/secret.go:110 +0x274
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cluster.(*Builder).Build(0xc0003c20c0, 0x1cd5280, 0xc00007c0c0, 0x1c9e720, 0xc00000e018, 0xc0005b
c300, 0xc0003b4538, 0x1, 0x1, 0x0, ...)
        pkg/skaffold/build/cluster/cluster.go:44 +0x1b7
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.withTimings.Build(0x1ce2000, 0xc0003c20c0, 0x1cb24c0, 0xc00053e240, 0x1ce2100, 0xc0005d60c0, 0x1
, 0x1cd5280, 0xc00007c0c0, 0x1c9e720, ...)
        pkg/skaffold/runner/timings.go:63 +0x169
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).BuildAndTest.func1(0x1cd5280, 0xc00007c0c0, 0x1c9e720, 0xc00000e018, 0xc0005bc
300, 0xc0003b4538, 0x1, 0x1, 0x0, 0x0, ...)
        pkg/skaffold/runner/build_deploy.go:46 +0xc4
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cache.(*cache).Build(0xc0003b6140, 0x1cd5280, 0xc00007c0c0, 0x1c9e720, 0xc00000e018, 0xc0005bc300
, 0xc00000e028, 0x1, 0x1, 0xc00079c080, ...)
        pkg/skaffold/build/cache/retrieve.go:115 +0x10f4
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).BuildAndTest(0xc0005e0120, 0x1cd5280, 0xc00007da80, 0x1c9e720, 0xc00000e018, 0
xc00000e028, 0x1, 0x1, 0x0, 0x7ffdb82166d2, ...)
        pkg/skaffold/runner/build_deploy.go:39 +0x178
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doBuild.func1(0x1cff980, 0xc0005e0120, 0xc000174600, 0x0, 0x10001000001)
        cmd/skaffold/app/cmd/build.go:67 +0x121
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner(0x1cd5280, 0xc00007da80, 0xc000593c48, 0xc00026ade0, 0xc00020c3f0)
        cmd/skaffold/app/cmd/runner.go:48 +0xa7
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doBuild(0x1cd5280, 0xc00007da80, 0x1c9e720, 0xc00000e018, 0xc00020c3f0, 0xc000192a00)
        cmd/skaffold/app/cmd/build.go:66 +0xb3
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.cancelWithCtrlC.func1(0x1c9e720, 0xc00000e018, 0x0, 0x0)
        cmd/skaffold/app/cmd/signals.go:33 +0xba
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc000193400, 0xc0002100f0, 0x0, 0x3, 0x0, 0x0)
        cmd/skaffold/app/cmd/commands.go:96 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000193400, 0xc000210060, 0x3, 0x3, 0xc000193400, 0xc000210060)
        vendor/github.com/spf13/cobra/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000192a00, 0xc00000e018, 0x1c9e720, 0xc00000e020)
        vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        vendor/github.com/spf13/cobra/command.go:864
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x1c9e720, 0xc00000e018, 0x1c9e720, 0xc00000e020, 0xc00053bf88, 0x40584f)
        cmd/skaffold/app/skaffold.go:27 +0x58
main.main()
        cmd/skaffold/skaffold.go:30 +0x4e

[redacted ~]# cp .kube/config old_config
[redacted ~]#
[redacted ~]# ./klogin -a https://api.redacted:6443 -u redacted
Authenticating with credentials to https://login.apps.redacted...
User: redacted
Password:
Successfully wrote kube config to /root/.kube/config


INFO[0000] update check failed: get latest and current Skaffold version: parsing current semver, skipping update check: parsing semver: No Major.Minor.Patch
elements found
DEBU[0001] Found dependencies for dockerfile: [{app.py / true}]
 - redactedpythonserver: Not found. Building
Cache check complete in 1.626643804s
Starting build...
DEBU[0001] getting client config for kubeContext: ``
Creating docker config secret [docker-cfgc92f3cd4-4c1e-4831-bdbb-fb2fbf1b62d9]...
Building [redactedpythonserver].


[redacted ~]# diff .kube/config old_config
29c29
<         id-token: redacted
---
>         id-token: redacted
31c31
<         refresh-token: redacted
---
>         refresh-token: redacted

```

### Information

- Skaffold version: 38
- Operating system: linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: redacted
    kaniko:
      buildContext:
        localDir: {}
      cache: {}
      image: redacted
  cluster:
    namespace: p1-dev
    dockerConfig:
      path: ~/.docker/config.json
deploy:
  kubectl:
    manifests:
    - deploy.yaml

```

### Steps to reproduce the behavior

Its a continous random error which goes after relogin. AuthToken expiry is not the reason coz it when token is valid.

**Comment by tejal29** [comment]
@prary Can you please verify if when you see this random error, you can connect to cluster using `kubectl`?

**Comment by prary** [comment]
@tejal29 I am able to use kubectl

**Comment by tejal29** [comment]
Tanks @prary. we need more information to re-produce it. We will probably start with a 
- invalid kubecontext.
- try skaffold
- see if we see the error.

**Comment by prary** [comment]
@tejal29  Great, meanwhile if I encounter this again I will try to share mine kubecontext as much as possible.

**Comment by prary** [comment]
hi @tejal, faced the issue again 

```
time="2019-10-21T16:46:02+05:30" level=debug msg="getting client config for kubeContext: ``"
time="2019-10-21T16:46:02+05:30" level=debug msg="No docker config specified. Checking for one in the cluster."
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x14c7e16]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/oidc.(*oidcAuthProvider).idToken(0xc000410bd0, 0x0, 0x0, 0x0, 0x0)
        vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go:281 +0x716
k8s.io/client-go/plugin/pkg/client/auth/oidc.(*roundTripper).RoundTrip(0xc0003cd0c0, 0xc00033e400, 0x1a2eb5f, 0xa, 0xc00040ea40)
        vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go:199 +0x84
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc0003cd0e0, 0xc00033e100, 0xc0003cd0e0, 0x0, 0x0)
        vendor/k8s.io/client-go/transport/round_trippers.go:159 +0x1c9
net/http.send(0xc00033e100, 0x1cabb40, 0xc0003cd0e0, 0x0, 0x0, 0x0, 0xc0003f0578, 0xc0004f2c18, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:250 +0x468
net/http.(*Client).send(0xc0004116b0, 0xc00033e100, 0x0, 0x0, 0x0, 0xc0003f0578, 0x0, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:174 +0x102
net/http.(*Client).do(0xc0004116b0, 0xc00033e100, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:641 +0x280
net/http.(*Client).Do(0xc0004116b0, 0xc00033e100, 0x0, 0x57, 0x0)
        /usr/local/go/src/net/http/client.go:509 +0x3c
k8s.io/client-go/rest.(*Request).request(0xc0004a0900, 0xc0005feec8, 0x0, 0x0)
        vendor/k8s.io/client-go/rest/request.go:754 +0x337
k8s.io/client-go/rest.(*Request).Do(0xc0004a0900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        vendor/k8s.io/client-go/rest/request.go:828 +0xdf
k8s.io/client-go/kubernetes/typed/core/v1.(*secrets).Get(0xc00059a460, 0x2bd7892, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000aa000, ...)
        vendor/k8s.io/client-go/kubernetes/typed/core/v1/secret.go:73 +0x19a
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cluster.(*Builder).setupDockerConfigSecret(0xc0003e6c90, 0x1cac0e0, 0xc000006018, 0x2, 0x1b, 0x0)
        pkg/skaffold/build/cluster/secret.go:103 +0x1a9
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cluster.(*Builder).Build(0xc0003e6c90, 0x1ce24c0, 0xc000473fc0, 0x1cac0e0, 0xc000006018, 0xc0003e7410, 0xc0003f0320, 0x1, 0x1, 0x0, ...)
        pkg/skaffold/build/cluster/cluster.go:44 +0x1be
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.withTimings.Build(0x1cef580, 0xc0003e6c90, 0x1cbf540, 0xc000473a80, 0x1cef680, 0xc00051e9c0, 0x1, 0x1ce24c0, 0xc000473fc0, 0x1cac0e0, ...)
        pkg/skaffold/runner/timings.go:63 +0x170
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).BuildAndTest.func1(0x1ce24c0, 0xc000473fc0, 0x1cac0e0, 0xc000006018, 0xc0003e7410, 0xc0003f0320, 0x1, 0x1, 0x0, 0x0, ...

        pkg/skaffold/runner/build_deploy.go:46 +0xcb
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cache.(*cache).Build(0xc00045ab90, 0x1ce24c0, 0xc000473fc0, 0x1cac0e0, 0xc000006018, 0xc0003e7410, 0xc00045c898, 0x1, 0x1, 0xc000469d60, ..
)
        pkg/skaffold/build/cache/retrieve.go:115 +0x10fb
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).BuildAndTest(0xc00019e240, 0x1ce24c0, 0xc00005da80, 0x1cac0e0, 0xc000006018, 0xc00045c898, 0x1, 0x1, 0x0, 0x0, ...)
        pkg/skaffold/runner/build_deploy.go:39 +0x17f
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doBuild.func1(0x1d0cf40, 0xc00019e240, 0xc00033e200, 0x0, 0x10001000001)
        cmd/skaffold/app/cmd/build.go:67 +0x128
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner(0x1ce24c0, 0xc00005da80, 0xc0004f3c48, 0xc000459c80, 0xc000090990)
        cmd/skaffold/app/cmd/runner.go:48 +0xae
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doBuild(0x1ce24c0, 0xc00005da80, 0x1cac0e0, 0xc000006018, 0xc000090990, 0xc000093b80)
        cmd/skaffold/app/cmd/build.go:66 +0xba
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.cancelWithCtrlC.func1(0x1cac0e0, 0xc000006018, 0x0, 0x0)
        cmd/skaffold/app/cmd/signals.go:33 +0xc1
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc00015ef00, 0xc0000907f0, 0x0, 0x1, 0x0, 0x0)
        cmd/skaffold/app/cmd/commands.go:96 +0x72
github.com/spf13/cobra.(*Command).execute(0xc00015ef00, 0xc0000907d0, 0x1, 0x1, 0xc00015ef00, 0xc0000907d0)
        vendor/github.com/spf13/cobra/command.go:826 +0x46c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000093b80, 0xc000006018, 0x1cac0e0, 0xc000006020)
        vendor/github.com/spf13/cobra/command.go:914 +0x303
github.com/spf13/cobra.(*Command).Execute(...)
        vendor/github.com/spf13/cobra/command.go:864
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x1cac0e0, 0xc000006018, 0x1cac0e0, 0xc000006020, 0xc0004f3f88, 0x405686)
        cmd/skaffold/app/skaffold.go:27 +0x5f
main.main()
        cmd/skaffold/skaffold.go:30 +0x55		
```

**Comment by prary** [comment]
./kube/config

```
apiVersion: v1
clusters:
- cluster:
    server: https://test-cluster:6443
  name: test-cluster
contexts:
- context:
    cluster: test-cluster
    user: test-cluster/something.com
  name: test-cluster/something.com
current-context: test-cluster/something.com
kind: Config
preferences: {}
users:
- name: test-cluster/something.com
  user:
    auth-provider:
      config:
        client-id: PC-103000-SID-23338-PROD
        client-secret: ""
        id-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkpKRmRuSURYTngtTERNUWIzR3V4eVpSaC1xZyIsImtpZCI6IkpKRmRuSURYTngtTERNUWIzR3V4eVpSaC1xZyJ9.eyJhdWQiOiJQQy0xMDMwMDAtU0lELTIzMzM4LVBST0QiLCJpc3MiOiJodHRwczovL2lkYS5qcG1vcmdhbmNoYXNlLmNvbS9hZGZzIiwiaWF0IjoxNTcwNjExMjA2LCJleHAiOjE1NzA2MTQ4MDYsImF1dGhfdGltZSI6MTU3MDYxMTIwNiwic3ViIjoiQUpyTHZ0R0RsemZHQW5KcVFuT0IxUmN2ZVM5QTkwUHArc0hJdDNwUGtGVT0iLCJ1cG4iOiJvNzA1ODU4QGFzaWFwYWMuYWQuanBtb3JnYW5jaGFzZS5jb20iLCJ1bmlxdWVfbmFtZSI6IkFTSUFQQUNcXE83MDU4NTgiLCJwd2RfZXhwIjoiNjE0Mjc1NCIsInNpZCI6IlMtMS01LTIxLTMyOTA2ODE1Mi0xODQ0ODIzODQ3LTE4MDE2NzQ1MzEtMTI2MDY4OCIsImFwcHR5cGUiOiJQdWJsaWMiLCJhcHBpZCI6IlBDLTEwMzAwMC1TSUQtMjMzMzgtUFJPRCIsImF1dGhtZXRob2QiOiJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvYXV0aGVudGljYXRpb25tZXRob2Qvd2luZG93cyIsInZlciI6IjEuMCIsInNjcCI6Im9wZW5pZCJ9.RDz4utxmfPwvbc4ApKwjU_dnstBo8Vxn8tHDfxX8VCUAbhwjjp6RiqXctwI481n8gkR7Wc38QAne4fHIAFNsSKSYFgTq4FcsW9wPvPUOOBfaQ9OECgZdeaH4RW4r4d0Q-_9E844jsMHWKwHITsPAV2UpOXIQLwHcR2SYcNvTbs1a2_OI1PObnnz2SodcnyJJiJc2AYlPCbVMMgd2U6QHJarM7NjQ9xuO1XQZNWrMaHq_pVR5aSShyQTpEjhEnjKyrCMgdLv59Ot0h9bG_pNv9hgaGvDysYxJH9dJ5D1XIu-8VMAm_2xPMoUsmFWgbooM3pHDS4DEskQEMITpCeqzlw
        idp-issuer-url: https://something.com/adfs
        refresh-token: 90k-0bUyPQ2KInSa-SvcBtEs0aCEl729XC59kaiG78QAAQAAGFBlEagK3dGOizjqG8MMFqA_VO4y9gi2h6dd_dEVCEs5yAvPXS6aTvRmjfxPnxXFhfnPu86dt_oV3LaKzLOecrPQovczhjVLAvvM6AYDKPsx51QZrljeH6Y4QJvQdLzJfxDuJK38KxPypv-_TvrkCUcf89P_yXsav3yS8TIn5G6n1ZOqpm0QhJt9lALyGge2ez-_8448kAbVnV1X_N4BAjRTjEZvduzvkQFCe7YSeI5e1TQc6jOXE2WL4BoGgQjJkMlMH0QZ2aA4GumcIQdbAlKyZJZhSmkqhqvcxgz_xQDCKdq7Zzx643eUNS_taUiKi7fXKMYRRsRMww_tzEO0-pAFAABBUfuc9FckmRyQILAoMeM5fA4-zPrPpkwBCAtW41rnsaJYN2_AaHT3N6DEHPXndCBFWJtSLcaORFfxDD1_1qd7Qpl8PH8kgcJzE_D5ns1hRIiGVYsGUJUGLBmFiBlili7uEec7FJywFkxrCZ5yuOX0jDNCvGX_7QqcU-u7SklASk0N_t0a2hJnIHWrgKZh7zPM-5FDfmd5tppNz59oPewd4aI37Ihl20haahnmBbZmQtDTbttNAtrTXFnlwKu__I-hNCBemy8GC8ZCj9ljVOgOEOuYV00fqbzXRswI-9Py2B91oRfMdLwoKbA391-Ux-8a0Vh5cfbtSntLu7kE3uJpQhbenI5BECc9_9OLAPSEKAQOEk4RsYmpFcRD9VVU4Q8mVjru93VIPByFKozzbZMUTeGCS0e0naXsHUWct0OZEpYKvQUx3UtnjBdu3qDydpZETkjrKwjrQVZm36TkVPiHi__bgCfo8ptU2t3x6T35ZQ9cDbwqS0Ogdt7uaEfyfY0QRUfM2A1gZIsyNn60kIjbkx1S6i-hOdZr1hfDm215rnwOlALQNz18C8xOCfuBPVwN_xBL43jnzKr7rvrCj2EVqpSt_UZ2flN4XfNBXtQIIrAP5PZLWxF45GBTG-Qq1tZdwBdItxDEfOLdULRcijZnitPqSoGFtznpqttq5YJ7jYhJZ5rjQSpyLQc4fkSdsuXNtSaG5LmW9MmvLVOSYtS3xB3rysD72n4eEPalBjDlrNrQne-lV8cK5WIHdWmdQKU4x1riljYuKHVN3L3ELkzxTASYByV3B3chxJzAM8i3RU0340jAXdopwPwVdGWiKmrhJ8xICqVpZ8Cj1a9NEeKDqzIBqmW2QTm7RV0oWIHEYPMV9KN4Y1doWZgyu5YoCdP2FDrfv6Auquc5Zb8eZyVINsFiGm9ADfRKlJRbjOV1mS-gahDP0JsfB_XHsa2DHRvdgiWIwyIf__siCoWr3PwE6aNW2cezrz5ri9N96tAm_XmFm8w3yLM2soXfP1a7pSZkQrtShWOE1WY-GjrGpyR7zMPKQXkTYgCYIDqC9HzBGnwUxbG3y_qiss5EcN7IHKHbXQTzcowSkV7V-RVUa8cKqTbXFDNgFcuPixcg5veuWJ-iklE9_CivNv0ccdx0L56_5QpVXgL7NJ98pxs4nTWRETuOc-z6N-2KK8uxvOBIiafA0SdUa0aBYZ1yxmDk9CC2PCchEKnz0fC-thoL2Tk1yTg2075rPXUB1CwDKg5U68A4UTB-6BuNKlvMZ-hlEnx7bkabOnkCcOH1fOai3mcijvJifPOvnRQsp_ZgMWxL7YFqHJbj_ax7qU2j4kkLRJSnog5dPM2fJzz-GHUaGvGUfuG6ky9DuT0levKYkUZuGi5HAajq258zz3XJFSWhzHoUk1Qc1YtmuGGpFSDV80c8hAsGZxtFQSRrnVvUgrGK79ywMHtPdbLFFsKcUZ8zh7kMMmRUElVOgobMrneK2ttJqZzSJufFWDeiXtrNE6o7fPW12W6cZLsrG6VorAd2PKo9H97tAq7cvrWbGxMUJDsvBXKv5wjf2UNhS9ddxhA9NJ8yrx0AcFYIlNTjXTh-QImvL78zQcBQwkctPDW-VgBhCjGFgsvNhZWHTsZnkfd9mVxyksRL7MkPlB81i_dbtWVYdyMdXayP_FTb21Gt8_o3CFXf8fp1ItIkAeYC8Wi2OhB2te7BjoQB6uUY5bfzF0sg8ORAhHLW9IaX8h5_eSCWIYvh58xQuPOHnU483Jm32tThXeuc_AtyCMO8NNi0cu2xvcpKBAN147nVustyGks9iZqoHDJlX199hCIimWw4YZbpMp_aZAREbR5Qoy5xyN9GwZRTipLf2pEQ3r3oqNVikZbeAOJxRJj2-kJCzN0rqA.AAcFXYJL-iNrvanzmCvRVdQRTDMQpiUS4dzSgULLxXgBg2XTQWGKgmlz1owNDcFaArBnXoX3yN2LBh5YWiR1sbSlPAI13STsed4ZI_wIdK1EQy1WvbAEWV-KcvvOToTNhWunaw14Cj7KmvItlCm3OVqjTi6oqVsi3Xq1Vity_5qc2QIx4sjzwmZcZPHruMgWQxrlZgfT5t67XfNXZICWOrNw44zNaxm_wWM6Txw7YLcbzIoGSJQ-0hPVg24HFhHw8icIkWkDSMw7ylu0yKXttkhqx5mU1yOtSHZiKHokMO_TRQIjwemcDzcCQm95WpKWRTfV3beXr9aBPfRXMkT3hA
      name: oidc
```

**Comment by prary** [comment]
./kube/config

```
apiVersion: v1
clusters:
- cluster:
    server: https://test-cluster:6443
  name: test-cluster
contexts:
- context:
    cluster: test-cluster
    user: test-cluster/something.com
  name: test-cluster/something.com
current-context: test-cluster/something.com
kind: Config
preferences: {}
users:
- name: test-cluster/something.com
  user:
    auth-provider:
      config:
        client-id: something
        client-secret: ""
        id-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkpKRmRuSURYTngtTERNUWIzR3V4eVpSaC1xZyIsImtpZCI6IkpKRmRuSURYTngtTERNUWIzR3V4eVpSaC1xZyJ9.eyJhdWQiOiJQQy0xMDMwMDAtU0lELTIzMzM4LVBST0QiLCJpc3MiOiJodHRwczovL2lkYS5qcG1vcmdhbmNoYXNlLmNvbS9hZGZzIiwiaWF0IjoxNTcwNjExMjA2LCJleHAiOjE1NzA2MTQ4MDYsImF1dGhfdGltZSI6MTU3MDYxMTIwNiwic3ViIjoiQUpyTHZ0R0RsemZHQW5KcVFuT0IxUmN2ZVM5QTkwUHArc0hJdDNwUGtGVT0iLCJ1cG4iOiJvNzA1ODU4QGFzaWFwYWMuYWQuanBtb3JnYW5jaGFzZS5jb20iLCJ1bmlxdWVfbmFtZSI6IkFTSUFQQUNcXE83MDU4NTgiLCJwd2RfZXhwIjoiNjE0Mjc1NCIsInNpZCI6IlMtMS01LTIxLTMyOTA2ODE1Mi0xODQ0ODIzODQ3LTE4MDE2NzQ1MzEtMTI2MDY4OCIsImFwcHR5cGUiOiJQdWJsaWMiLCJhcHBpZCI6IlBDLTEwMzAwMC1TSUQtMjMzMzgtUFJPRCIsImF1dGhtZXRob2QiOiJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvYXV0aGVudGljYXRpb25tZXRob2Qvd2luZG93cyIsInZlciI6IjEuMCIsInNjcCI6Im9wZW5pZCJ9.RDz4utxmfPwvbc4ApKwjU_dnstBo8Vxn8tHDfxX8VCUAbhwjjp6RiqXctwI481n8gkR7Wc38QAne4fHIAFNsSKSYFgTq4FcsW9wPvPUOOBfaQ9OECgZdeaH4RW4r4d0Q-_9E844jsMHWKwHITsPAV2UpOXIQLwHcR2SYcNvTbs1a2_OI1PObnnz2SodcnyJJiJc2AYlPCbVMMgd2U6QHJarM7NjQ9xuO1XQZNWrMaHq_pVR5aSShyQTpEjhEnjKyrCMgdLv59Ot0h9bG_pNv9hgaGvDysYxJH9dJ5D1XIu-8VMAm_2xPMoUsmFWgbooM3pHDS4DEskQEMITpCeqzlw
        idp-issuer-url: https://something.com/adfs
        refresh-token: 90k-0bUyPQ2KInSa-SvcBtEs0aCEl729XC59kaiG78QAAQAAGFBlEagK3dGOizjqG8MMFqA_VO4y9gi2h6dd_dEVCEs5yAvPXS6aTvRmjfxPnxXFhfnPu86dt_oV3LaKzLOecrPQovczhjVLAvvM6AYDKPsx51QZrljeH6Y4QJvQdLzJfxDuJK38KxPypv-_TvrkCUcf89P_yXsav3yS8TIn5G6n1ZOqpm0QhJt9lALyGge2ez-_8448kAbVnV1X_N4BAjRTjEZvduzvkQFCe7YSeI5e1TQc6jOXE2WL4BoGgQjJkMlMH0QZ2aA4GumcIQdbAlKyZJZhSmkqhqvcxgz_xQDCKdq7Zzx643eUNS_taUiKi7fXKMYRRsRMww_tzEO0-pAFAABBUfuc9FckmRyQILAoMeM5fA4-zPrPpkwBCAtW41rnsaJYN2_AaHT3N6DEHPXndCBFWJtSLcaORFfxDD1_1qd7Qpl8PH8kgcJzE_D5ns1hRIiGVYsGUJUGLBmFiBlili7uEec7FJywFkxrCZ5yuOX0jDNCvGX_7QqcU-u7SklASk0N_t0a2hJnIHWrgKZh7zPM-5FDfmd5tppNz59oPewd4aI37Ihl20haahnmBbZmQtDTbttNAtrTXFnlwKu__I-hNCBemy8GC8ZCj9ljVOgOEOuYV00fqbzXRswI-9Py2B91oRfMdLwoKbA391-Ux-8a0Vh5cfbtSntLu7kE3uJpQhbenI5BECc9_9OLAPSEKAQOEk4RsYmpFcRD9VVU4Q8mVjru93VIPByFKozzbZMUTeGCS0e0naXsHUWct0OZEpYKvQUx3UtnjBdu3qDydpZETkjrKwjrQVZm36TkVPiHi__bgCfo8ptU2t3x6T35ZQ9cDbwqS0Ogdt7uaEfyfY0QRUfM2A1gZIsyNn60kIjbkx1S6i-hOdZr1hfDm215rnwOlALQNz18C8xOCfuBPVwN_xBL43jnzKr7rvrCj2EVqpSt_UZ2flN4XfNBXtQIIrAP5PZLWxF45GBTG-Qq1tZdwBdItxDEfOLdULRcijZnitPqSoGFtznpqttq5YJ7jYhJZ5rjQSpyLQc4fkSdsuXNtSaG5LmW9MmvLVOSYtS3xB3rysD72n4eEPalBjDlrNrQne-lV8cK5WIHdWmdQKU4x1riljYuKHVN3L3ELkzxTASYByV3B3chxJzAM8i3RU0340jAXdopwPwVdGWiKmrhJ8xICqVpZ8Cj1a9NEeKDqzIBqmW2QTm7RV0oWIHEYPMV9KN4Y1doWZgyu5YoCdP2FDrfv6Auquc5Zb8eZyVINsFiGm9ADfRKlJRbjOV1mS-gahDP0JsfB_XHsa2DHRvdgiWIwyIf__siCoWr3PwE6aNW2cezrz5ri9N96tAm_XmFm8w3yLM2soXfP1a7pSZkQrtShWOE1WY-GjrGpyR7zMPKQXkTYgCYIDqC9HzBGnwUxbG3y_qiss5EcN7IHKHbXQTzcowSkV7V-RVUa8cKqTbXFDNgFcuPixcg5veuWJ-iklE9_CivNv0ccdx0L56_5QpVXgL7NJ98pxs4nTWRETuOc-z6N-2KK8uxvOBIiafA0SdUa0aBYZ1yxmDk9CC2PCchEKnz0fC-thoL2Tk1yTg2075rPXUB1CwDKg5U68A4UTB-6BuNKlvMZ-hlEnx7bkabOnkCcOH1fOai3mcijvJifPOvnRQsp_ZgMWxL7YFqHJbj_ax7qU2j4kkLRJSnog5dPM2fJzz-GHUaGvGUfuG6ky9DuT0levKYkUZuGi5HAajq258zz3XJFSWhzHoUk1Qc1YtmuGGpFSDV80c8hAsGZxtFQSRrnVvUgrGK79ywMHtPdbLFFsKcUZ8zh7kMMmRUElVOgobMrneK2ttJqZzSJufFWDeiXtrNE6o7fPW12W6cZLsrG6VorAd2PKo9H97tAq7cvrWbGxMUJDsvBXKv5wjf2UNhS9ddxhA9NJ8yrx0AcFYIlNTjXTh-QImvL78zQcBQwkctPDW-VgBhCjGFgsvNhZWHTsZnkfd9mVxyksRL7MkPlB81i_dbtWVYdyMdXayP_FTb21Gt8_o3CFXf8fp1ItIkAeYC8Wi2OhB2te7BjoQB6uUY5bfzF0sg8ORAhHLW9IaX8h5_eSCWIYvh58xQuPOHnU483Jm32tThXeuc_AtyCMO8NNi0cu2xvcpKBAN147nVustyGks9iZqoHDJlX199hCIimWw4YZbpMp_aZAREbR5Qoy5xyN9GwZRTipLf2pEQ3r3oqNVikZbeAOJxRJj2-kJCzN0rqA.AAcFXYJL-iNrvanzmCvRVdQRTDMQpiUS4dzSgULLxXgBg2XTQWGKgmlz1owNDcFaArBnXoX3yN2LBh5YWiR1sbSlPAI13STsed4ZI_wIdK1EQy1WvbAEWV-KcvvOToTNhWunaw14Cj7KmvItlCm3OVqjTi6oqVsi3Xq1Vity_5qc2QIx4sjzwmZcZPHruMgWQxrlZgfT5t67XfNXZICWOrNw44zNaxm_wWM6Txw7YLcbzIoGSJQ-0hPVg24HFhHw8icIkWkDSMw7ylu0yKXttkhqx5mU1yOtSHZiKHokMO_TRQIjwemcDzcCQm95WpKWRTfV3beXr9aBPfRXMkT3hA
      name: oidc
```
