### ISSUE TITLE
kaniko pod exist on cancelling skaffold

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#3048]
### Expected behavior
Kaniko pod is not killed it should be deleted from user namespace
### Actual behavior
Run skaffold build, cancel the build in middle.
### Information

- Skaffold version: 38
- Operating system: linux
- Contents of skaffold.yaml:

```
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: redacted
    kaniko:
      buildContext:
        localDir: {}
      image: redacted
  cluster:
    namespace: 103000-p1-dev
    dockerConfig:
      path: ~/.docker/config.json
deploy:
  kubectl:
    manifests:
    - deploy.yaml
```

### Steps to reproduce the behavior
Run a skaffold build
Kill the build after kaniko pod is scheduled and before pod has killed itself.
