### ISSUE TITLE
Add  cache-artifacts setting to skaffold.yaml

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#3050]
### Expected behavior
Skaffold should use caching when enabled in yaml by default it should be disabled
### Actual behavior
Skaffold is using cache
### Information

- Skaffold version: 38
- Operating system: linux
- Contents of skaffold.yaml:

```
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: redacted
    kaniko:
      buildContext:
        localDir: {}
      image: redacted
  cluster:
    namespace: p1-dev
    dockerConfig:
      path: ~/.docker/config.json
deploy:
  kubectl:
    manifests:
    - deploy.yaml
```

### Steps to reproduce the behavior
Run a skaffold build 
It looks for image in remote cache.

Logs

```
enerating tags...
 - redacted/pythonserver -> redacted/pythonserver:dd9f471
Tags generated in 59.679304ms
Checking cache...
 - redacted/pythonserver: Found
Cache check complete in 1.692961213s
Tags used in deployment:
 - redacted/pythonserver -> redacted/pythonserver:dd9f471@sha256:
```
