### ISSUE TITLE
Base Image name produced by envTemplate is ignored for local deployments

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#3088]
(I'm deploying to a local cluster, so images are not pushed)

Here's the configuration:

```
apiVersion: skaffold/v1beta16
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "base:tag"
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
```

When I run `skaffold run`, I can see that tags used in deployments ignore the image names produced by `envTemplate`:

```
Generating tags...
 - gcr.io/k8s-skaffold/skaffold-example -> base:tag
...
Tags used in deployment:
 - Since images are not pushed, they can't be referenced by digest
   They are tagged and referenced by a unique ID instead
 - gcr.io/k8s-skaffold/skaffold-example -> gcr.io/k8s-skaffold/skaffold-example:7f52d90c311cbb27cb6c447ac2739e55d2387f860174c86073fb4a898816550a
```

We should see:

```
 - gcr.io/k8s-skaffold/skaffold-example -> base:tag
...
Tags used in deployment:
 - Since images are not pushed, they can't be referenced by digest
   They are tagged and referenced by a unique ID instead
 - gcr.io/k8s-skaffold/skaffold-example -> base:7f52d90c311cbb27cb6c447ac2739e55d2387f860174c86073fb4a898816550a
```
