### ISSUE TITLE
Default namespace of port forwarding

### ISSUE THREAD

**Issue by feloy** [GoogleContainerTools/skaffold#3098]
### Expected behavior

When I define a port forward in my skaffold.yaml file without defining a namespace on which to find the resource to port forward, I expect that skaffold look in the *current* namespace.

### Actual behavior

If the namespace is not specified, the "default" namespace is used.

### Discussion

This behavior seems useless to me, because it is easy for the user to specify the "default" namespace if he wants to work on this namespace. Also, it is practically impossible that "default" is the expected namespace, as it is recommended not to use this "default" namespace.

In the other hand, it could be interesting that different users are able to use the same skaffold.yaml file in different namespaces. With the actual behavior, it is impossible without editing the skaffold.yaml file. It would be possible by letting skaffold select the current namespace by default.

### Information

- Skaffold version: master
- Operating system: Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta17
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/leeroy-web
      context: ./leeroy-web/
    - image: gcr.io/k8s-skaffold/leeroy-app
      context: ./leeroy-app/
deploy:
  kubectl:
    manifests:
      - ./leeroy-web/kubernetes/*
      - ./leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
```
