### ISSUE TITLE
skaffold example fails on start

### ISSUE THREAD

**Issue by arashbi** [GoogleContainerTools/skaffold#3117]
When I try to run the example, I get an error. The `skaffold dev` command doesn't work.

### Expected behavior
I expect the behavior to be like described in https://skaffold.dev/docs/getting-started/

### Actual behavior
~/s/s/e/getting-started ❯❯❯ skaffold dev                                        ✘ 127 master ◼
Listing files to watch...
 - gcr.io/k8s-skaffold/skaffold-example
FATA[0000] watching files for artifact gcr.io/k8s-skaffold/skaffold-example: listing files: listing files: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (golang:1.12.9-alpine3.10) for ONBUILD triggers: getting remote config: getting image: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fgolang%3Apull&service=registry.docker.io: invoking docker-credential-desktop: exit status 1; output: No stored credential for https://index.docker.io
### Information

- Skaffold version: v0.40.0
- Operating system: Mac OS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*

```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold dev`
3. ...
