### ISSUE TITLE
Document if a feature (e.g. sync) is only for 'skaffold dev'

### ISSUE THREAD

**Issue by igoooor** [GoogleContainerTools/skaffold#3125]
### Expected behavior

`skaffold run` watches for files changes defined in `build.artifacts[0].sync.manual` and sync them inside the container

### Actual behavior

Files are not sync. It only works if I run `skaffold dev`

### Information

- Skaffold version: v0.40.0
- Operating system: macOS Mojave
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta16
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: registry.../backend
      context: .
      docker:
        dockerfile: ops/.../Dockerfile
      sync:
        manual:
          - src: "**"
            dest: "/home/www-data/"
deploy:
  helm:
    releases:
      - name: sk-apollo
        chartPath: ops/helm
        values:
          php.image.repository: registry.../backend
```

Nowhere in the documentation is says that sync should be ran exclusively with `skaffold dev`, so I would expect it to work with `skaffold run` as well right?
