### ISSUE TITLE
Error decoding parsed error when deploying helm chart

### ISSUE THREAD

**Issue by demisx** [GoogleContainerTools/skaffold#3132]
I see an error message related to YAML parsing written to the log when I deploy a basic helm chart. The linter says YAML is valid. Am I missing something?

### Expected behavior
No error messages

### Actual behavior
```
INFO[0001] error decoding parsed yaml: yaml: line 7: could not find expected ':' 
```

### Information

- Skaffold version: v0.40.0
- Operating system: MacOS Mojave 10.14.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
deploy:
  helm:
    releases:
      - name: redis
        chartPath: stable/redis
        remote: true
        skipBuildDependencies: true
        namespace: default
```
