### ISSUE TITLE
Infer sync and locally built Docker artifacts targeting a stage do not sync

### ISSUE THREAD

**Issue by willmorgan** [GoogleContainerTools/skaffold#3136]
### Expected behavior

Using infer sync and Docker stages, I'd expect a file sync to happen and see this in the logs:

> Syncing 1 files for my.container.registry/api-demo:11799bb-dirty@sha256:756f960865f1382e4e04b7e2b31f1bae5a4c47338d6643ff87db718e751098b7

### Actual behavior

With this excerpt of a skaffold file, I'm seeing container rebuilds and restarts across all services, instead of syncing over the files as they change:

I tried disabling buildkit, changing the infer paths, and finally using manual syncing to check that my config wasn't entirely bad. Manually syncing as a workaround does seem to work, so we're using that in the interim - see commented section below.

My colleague @Sewci0 isolated this down to using Docker image stages.

### Information

- Skaffold version: v0.41.0
- Operating system: macOS 10.14.6
- Contents of skaffold.yaml:

```yaml
build:
  local:
    useBuildkit: true
  artifacts:
    - image: my.container.registry/api-demo
      context: ../../../demo-api
      docker:
        dockerfile: Dockerfile
        target: dev-stage
      sync:
#        manual:
#         - src: 'src/*.js'
#            dest: src
        infer:
          - src/**/*.js
          - ../../../demo-api/src/**/*.js
```

### Steps to reproduce the behavior

1. [a clonable repository with the sample skaffold project](https://github.com/willmorgan/skaffold-infer-repro)
1. push image somewhere
2. `skaffold dev`
3. change a file and watch it rebuild rather than sync over
