### ISSUE TITLE
Disable watching all artifact files except those specified in sync rules

### ISSUE THREAD

**Issue by petr-buchin** [GoogleContainerTools/skaffold#3148]
### Expected behavior
When I use manual file sync in `dev` mode, I expect Skaffold to watch **only** directories, specified in sync rules.
The obvious use case for that is **not** to watch heavy directories, like `node_modules` for Javascript projects, while being able to run `npm install` locally for whatever reason.
### Actual behavior
If I change or add some files **not** under paths, specified in sync rules, this triggers image rebuild.
### Information

- Skaffold version: 0.41.0
- Operating system: MacOs Mojave 10.14.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta16
kind: Config
metadata:
  name: example
build:
    local:
      push: false
    artifacts:
    - image: example/example
      context: example
      docker:
          dockerfile: Dockerfile
      sync:
          manual:
          - src: 'app/**/*.js'
            dest: '/data/example/app'
            strip: 'app/'
```

### Steps to reproduce the behavior

1. missing
2. `skaffold dev`
