### ISSUE TITLE
kaniko hostpath not correctly defined

### ISSUE THREAD

**Issue by golgoth31** [GoogleContainerTools/skaffold#3156]
### Expected behavior
kaniko argument "config-dir" is using the same value as the mount point

```yaml
containers:
  - args:
    ...
    - --cache-dir
    - /cache
    ...
    volumeMounts:
    - mountPath: /cache
      name: kaniko-cache
  ...
volumes:
  - hostPath:
      path: /data/docker/kaniko/cache
      type: ""
    name: kaniko-cache
```

### Actual behavior
"config-dir" is using the cache.hostpath value and not the mount point

```yaml
containers:
  - args:
    ...
    - --cache-dir
    - /data/docker/kaniko/cache
    ...
    volumeMounts:
    - mountPath: /cache
      name: kaniko-cache
  ...
volumes:
  - hostPath:
      path: /data/docker/kaniko/cache
      type: ""
    name: kaniko-cache
```

### Information

- Skaffold version: v0.41.0
- Operating system: fedora; kaniko runing into k3s
- Contents of skaffold.yaml:

```yaml
build:
      artifacts:
        - image: xxxx/yyyy
          context: .
          kaniko:
            dockerfile: build/package/Skaffold
            buildContext:
              localDir: {}
            cache:
              hostPath: /data/docker/kaniko/cache
```
This behaviour has been introduced by the commit 84b196baccac929bd2c758200582f11d2116abec
### Steps to reproduce the behavior

run "skaffold dev"
