### ISSUE TITLE
Profile buildArgs failing validation when profile is not active

### ISSUE THREAD

**Issue by ConnorGraham** [GoogleContainerTools/skaffold#3165]
I use a profile for my travis ci builds. This works well for configuring my build.tagPolicy. However, if I define a docker.buildArgs argument that uses one of travis' env vars, the skaffold parser fails even if the profile is not active

### Expected behavior
A profile's docker buildArgs are only evaluated when the profile its activated

### Actual behavior
skaffold yaml fails to parse
```
$ skaffold run
time="2019-11-04T12:01:36-05:00" level=fatal msg="creating runner: parsing skaffold config: unable to parse YAML: yaml: invalid map key: map[interface {}]interface {}{\".TRAVIS_BRANCH\":interface {}(nil)}"
```

### Information

- Skaffold version: v0.41.0
- Operating system: windows 10
- Contents of skaffold.yaml:

**Changing the value of the BRANCH buildArg in the travis profile (or removing it completely) allows parsing to pass**
```yaml
apiVersion: skaffold/v1beta15
kind: Config

build:
  artifacts:
  - image: <redacted>
    docker:
      buildArgs:
        BRANCH: local

deploy:
  helm:
    releases:
      - name: "ui-{{ .USERNAME }}"
        chartPath: ../.kubernetes/helm-chart
        values:
          image: <redacted>
        valuesFiles: 
          - values.yaml

profiles:
  - name: travis
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:travis-{{.TRAVIS_BRANCH}}-{{.TRAVIS_BUILD_NUMBER}}-{{.COMMIT}}"
      artifacts:
      - image: <redacted>
        docker:
          buildArgs:
            BRANCH: {{ .TRAVIS_BRANCH }}
```
