### ISSUE TITLE
No redeployment and no logs after changing files

### ISSUE THREAD

**Issue by aboullaite** [GoogleContainerTools/skaffold#3186]
I'm trying skaffold with a multimodule microservices app, mainly using micronaut framework and gradle! I'm using jib plugin for gradle to build my images! full project can be found [here](https://github.com/aboullaite/java-k8s-dev)

When first running skaffold dev, everything seems to be working perfectly. However, when I make the changes to one of the micronaut services the build is triggered, and it shows the app is deployed but nothing changes, no logs are shown and not deployments is done! 

### Expected behavior
Changing the code and skaffold redeploy my app and append the logs from the app
### Actual behavior
After changinf the code, no deployments is performed.
### Information

- Skaffold version: v0.41.0
- Operating system: MacOS catalina, version 10.15
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
    - image: gcr.io/containers-java/frontend
      context: ./frontend/react/
      sync:
        infer:
          - '**/*.js'
    - image: gcr.io/containers-java/storefront
      context: .
      jib:
        project: storefront
    - image: gcr.io/containers-java/comments
      context: .
      jib:
        project: comments
    - image: gcr.io/containers-java/offers
      context: .
      jib:
        project: offers
    - image: gcr.io/containers-java/pets
      context: .
      jib:
        project: pets
    - image: gcr.io/containers-java/vendors
      context: .
      jib:
        project: vendors
deploy:
  kustomize:
    path: k8s/overlays/local
```

### Steps to reproduce the behavior

1. clone https://github.com/aboullaite/java-k8s-dev/ 
2. move to `petstore` dir
2. `skaffold dev` and wait until all apps are deployed
3. make some groovy change on `storefront` app
