### ISSUE TITLE
`skaffold.yaml` produced by `skaffold init --XXenableJibInit` could be simpler

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#3190]
When I run `skaffold init --XXenableJibInit --force` in `examples/jib`, I get this `skaffold.yaml`.

```
...
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-jib
    jib:
      args:
      - -Dimage=gcr.io/k8s-skaffold/skaffold-jib
      type: maven
```

I expected to get this kind of output:

```
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-jib
    jib: {}
```

any reason why we duplicate the image name?
