### ISSUE TITLE
Cloud Code debug adds second definition of JAVA_TOOL_OPTIONS

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/skaffold#3192]
(issue, including original description, migrated from https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2669)

- Cloud Code for IntelliJ version: 19.0.1
- OS: macosx 

**What did you do?**

tried cloud code debug, noticed it added a second JAVA_TOOL_OPTIONS env variable.

We use JAVA_TOOL_OPTIONS to pass in memory settings and other JVM flags. Skaffold.yaml builds using jib-maven-plugin, and deploys plain yaml manifests for deployment and service. 

**What did you expect to see?**

jdwp agent config appended to existing JAVA_TOOL_OPTIONS

**What did you see instead?**

duplicate definition of JAVA_TOOL_OPTIONS env variable: 

snippet of output from `kubectl get deployment MYDEPLOYMENT -o yaml`

```
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -XX:TieredStopAtLevel=1 -XX:+UseSerialGC -Duser.timezone=America/New_York
            -Xms64m -Xmx128m
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y

```
