### ISSUE TITLE
`dev` not invalidating image cache on lib change to multi-project config

### ISSUE THREAD

**Issue by stevesea** [GoogleContainerTools/skaffold#3210]
### Expected behavior

on code change, skaffold cache should have been invalidated and not used.

### Actual behavior

cached docker images used and rebuild isn't triggered.

### Information

- Skaffold version: 1.0.0
- Operating system: macos mojave 10.14.6

skaffold (via cloud code plugin) in continuous deploy mode is intermittently not picking up source changes and rebuilding the docker images.

multi-module POM that's using jib to build containers. project includes two micronaut microservices in different submodules. Update source code (refactored method name), and maven/jib wasn't used to re-build containers. 

Same issue happens outside of Cloud Code if I just do `skaffold dev` from command line.

I can work-around it by deleting ~/.skaffold/cache , or running `skaffold dev --cache-artifacts=false`

**Comment by orkonano** [comment]
I have the same issue since I updated to the last version 1.0.0

**Comment by dgageot** [comment]
Hi @stevesea @orkonano do you have a small project that we can use to reproduce the issue?

**Comment by dgageot** [comment]
@stevesea @orkonano any news?

**Comment by orkonano** [comment]
Sorry. It's working again. I didn't know what happened.

**Comment by stevesea** [comment]
@dgageot  My use-case has changed a bit since I initially created the ticket, but I think I'm still seeing similar issues. I _think_ this is all due to my using a library shared by multiple apps within a multi-project build. 

created this test case: https://github.com/stevesea/test-micronaut-skaffold

There's a multi-project Gradle file and three subprojects -- myapp-a and myapp-b, and a library 'mylib' shared by each app

Skaffold builds and deploys myapp-a and myapp-b. On source changes to either myapp-a or myapp-b, skaffold rebuilds and redeploys.

If I change source code in mylib, neither service is rebuilt.  To force the apps to rebuild/redeploy, I've got to go in and change source code in myapp-a/myapp-b.

For example... say I change a log statement in mylib (edit #1). To see the new log message, I've got to edit a file in myapp-a -- I add some whitespace to a file. 

I change the log message in mylib again (edit #2). To attempt to get it to rebuild, I undo my previous whitespace change in myapp-a.   skaffold "finds" the build in the cache. 

However, it found its previous build of the `myapp-a` source that matched that hash... but, it's  deployed the version of myapp-a that was built using `mylib` prior to either of my edits 

In my Skaffold yaml, I've got 

```
      artifacts:
        - &artifactA
          context: .
          image: myapp-a
          jib:
            project: myapp-a
            args:
              - -DskipTests

        - &artifactB
          context: .
          image: myapp-b
          jib:
            project: myapp-b
            args:
              - -DskipTests
```

I'd expect all files under the context root to be included in the hash computed for the cached docker image, and not only the files under the jib.project for that artifact. 

To work-around the issue with this multi-project build, I can use `skaffold dev --no-prune=false --cache-artifacts=false --port-forward=true`
