### ISSUE TITLE
Reference images with only an image or only a tag to be cri-o/OCI compatible

### ISSUE THREAD

**Issue by maxandersen** [GoogleContainerTools/skaffold#3220]
### Expected behavior
skaffold should have option to only use tags (or digest) when referring to generated images. 
That is so it is compatible with the oci spec and will work in systems using cri-o (such as openshift/origin).

Today it references images like this:
`docker.io/maxandersen/skaffold-example2:v0.41.0-175-g448e4014-dirty@sha256:f3e4ce9a4d629b78aef104253d6233132853e1c355dbdd04b2a9d309f14f20d5`

That result in errors like this: 

```
rpc error: code = Unknown desc = Invalid image name "docker.io/maxandersen/skaffold-example2:v0.41.0-175-g448e4014-dirty@sha256:f3e4ce9a4d629b78aef104253d6233132853e1c355dbdd04b2a9d309f14f20d5", unknown transport "docker.io/maxandersen/skaffold-example2"
Back-off pulling image "docker.io/maxandersen/skaffold-example2:v0.41.0-175-g448e4014-dirty@sha256:f3e4ce9a4d629b78aef104253d6233132853e1c355dbdd04b2a9d309f14f20d5"
```

This have previously been discussed in https://github.com/GoogleContainerTools/skaffold/issues/2089
which was closed with the comment to reopen or create new issue if requests to cri-o based projects did not succeed in getting support for tag/digest. Both https://github.com/containers/buildah/issues/1407 and https://github.com/cri-o/cri-o/issues/2351 have been closed referencing the distribution [spec](https://github.com/opencontainers/distribution-spec/blob/676c17d569501fb54e3eab03fc4244a0af46df8a/spec.md#pulling-an-image-manifest): 

```
The name and reference parameter identify the image and are REQUIRED. The reference MAY include a tag or digest.
```

I understand why skaffold uses both as that in other systems are used to state, pull from the tag and if the sha does not match cause a failure as a double insurance.

But for now that "useful loophole" is not honored by cri-o and thus I suggest skaffold at least provide an option to only add the tag so skaffold can be used on these systems.

### Information

- Skaffold version: 1.0
- Operating system: Any

### Steps to reproduce the behavior

1.  `git clone https://github.com/GoogleContainerTools/skaffold`
2. `cd skaffold/examples/getting-started`
3. target an cri-o based system, i.e. openshift 4.2
4. `skaffold dev`
5. output will have the above error in it.

**Comment by maxandersen** [comment]
Note, I was hoping https://skaffold.dev/docs/pipeline-stages/taggers/ could be used to control this but it seems like skaffold always append `@<shadigest>` to whatever tag is generated.

**Comment by maxandersen** [comment]
I tried do a few changes to the codebase to strip the digest but turns out that since both gitcommit and sha256 taggers generates fully stable tags no matter the amount of changes you've made skaffold's logic relies on the digest to be present.

Then I tried to rewire the the manifest render which kinda worked but I'm not sure that would be the right level to fix it. Any guidance on where this would be fixed best would be appreciated and I'll happily try make a proper patch for this.

**Comment by dgageot** [comment]
@maxandersen We currently assume that the digest can safely be appended to the tag. This is unfortunately done in multiple places (look for `+ "@" + digest` in the codebase).

The solution would be to extract that code to a function that appends the digest only to the basename.

If it's possible to activate that behaviour only when the underlying engine is cri-o, that would be a plus.

**Comment by dgageot** [comment]
@maxandersen Can you share the output of `kubectl get nodes -oyaml`. I'd like to see if we can auto-detect the runtime.

**Comment by maxandersen** [comment]
@dgageot it’s a rather big cluster i'm testing on so a rather large file :) but I assume this section is what you would be looking for: 

```
nodeInfo:
      architecture: amd64
      bootID: 792d5736-a82e-4ef3-a9cf-aa0799558cac
      containerRuntimeVersion: cri-o://1.14.11-0.23.dev.rhaos4.2.gitc41de67.el8
      kernelVersion: 4.18.0-80.11.2.el8_0.x86_64
      kubeProxyVersion: v1.14.6+7e13ab9a7
      kubeletVersion: v1.14.6+7e13ab9a7
      machineID: 88a2ff55e9bd4363aa812e84c4b404dc
      operatingSystem: linux
      osImage: Red Hat Enterprise Linux CoreOS 42.80.20191022.0 (Ootpa)
      systemUUID: ec28902b-023d-9aa9-0026-0e76a938580a
```

particular `containerRuntimeVersion: cri-o://1.14.11-0.23.dev.rhaos4.2.gitc41de67.el8` ?
