### ISSUE TITLE
Mounting of secrets and config map to Kaniko Pod

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#3226]
### Actual behavior
At present there is no ability to mount config map and secret in kaniko pod. 
Presently Kaniko pod create docker_config secrets and mount it and this isn't extensible in nature( 
user cannot mount another secret/configMap)

### Expected behavior
```
build: 
  cluster: 
     secrets: 
        - dockerConfig: docker-config 
        - secretName: secret_a
          mountPath: "/app/mysecret"
        - configMap: config_map_a
          mountPath: "/app/mysecret2"
```

- Skaffold version: v1.0.0
