### ISSUE TITLE
Ability to set environment variable in kaniko pod

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#3227]
In continuation of #3226 
### Actual behavior
At present I guess its missing.
### Expected behavior
Provide the ability to set environment variable in kaniko pods
```
build: 
  cluster: 
     env: 
        - ENV_NAME: ENV_VALUE
```
### Information

- Skaffold version: v1.0.0
- Operating system: NA
