### ISSUE TITLE
Allow passing image tag to docker build in buildArgs

### ISSUE THREAD

**Issue by Awem** [GoogleContainerTools/skaffold#3229]
### Expected behavior
On `skaffold build` the tag of the docker image is immediately printed after `Generating tags...` and should therefore be available in the `buildArgs` template of the docker build configuration.

### Actual behavior
It is not available.
### Information

- Skaffold version: 1.0.0
- Operating system: Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: client
    docker:
      buildArgs:
        IMAGE_NAME: '{{.IMAGE_NAME}}'
  local:
    push: true
    useDockerCLI: true

```

### Steps to reproduce the behavior

1. have a Dockerfile with 
```
ARG IMAGE_NAME
ENV IMAGE_NAME ${IMAGE_NAME}
RUN echo "Building image $IMAGE_NAME
```

2. skaffold build
3. $IMAGE_NAME won't have a value unless you provide some like `IMAGE_NAME=name skaffold build
`

**Comment by tejal29** [comment]
@Awem, skaffold runs locally and uses the local environment for substituting the variables.
Skaffold docker builder, does not parse the dockerfile to get to variables set in the dockerfile.

Does that make sense?

Please re-open this if you need more information.

**Comment by Awem** [comment]
Not sure whether we mean the same thing here. The Dockerfile is just for demonstration of a possible build. I do not want Skaffold to parse the Dockerfile. I am only looking for a possibility to use the name of the image (printed by Skaffold after `Generating tags...` on `skaffold build `) in the buildArgs key of my `skaffold.yaml`.
Since the templating feature is supported for `buildArgs` this should be easy. The [docs](https://skaffold.dev/docs/environment/templating/) say `Skaffold allows for certain fields in the config to be templated with values either from environment variables, or certain special values computed by Skaffold.` The image name would be such a computed value which is already available at the time the `buildArgs` are passed.

**Comment by balopat** [comment]
Thank you for opening - this is a bug, the docs are confusing and a code is terribly inconsistent. 

It is supposed to work, as we do evaluate env vars there. However, our calculated values are handled inconsistently across the code base: 

`ExecuteEnvTemplate` takes an extra map where we should pass down the calculated fields. 
https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/util/env_template.go#L40

As I'm looking at references to this method - a bunch of places (including the docker builder) it is called with `nil`... this is inconsistent even within helm fields themselves. 

The solution will be to have _one way_ of evaluating templates in the code.

**Comment by javier-b-perez** [comment]
hi,
I have a similar use case, but I only need to pass the tag generated by skaffold.
I'm using SKAFFOLD_DEFAULT_REPO + SKAFFOLD_TAG as my workaround, but this prevent me from using tag generated by skaffold (I need to generate the tag myself, before calling skaffold).

```yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  local:
    push: false
  artifacts:
    # Builder images are used to build the other containers.
    # You need to specify the registry you want to use:
    # export SKAFFOLD_DEFAULT_REPO=gcr.io/my-gcp-project
    # export SKAFFOLD_TAG=latest
  - image: gobuilder
    context: build/gobuilder
    docker:
      dockerfile: Dockerfile
  # These containers are using builders + src.
  - image: my-app
    docker:
      dockerfile: my-app/Dockerfile
      buildArgs:
        GOBUILDER: "{{.SKAFFOLD_DEFAULT_REPO}}/gobuilder:{{.SKAFFOLD_TAG}}"
```

The `my-app` Dockerfile looks like
```Dockerfile
ARG GOBUILDER=gcr.io/my-gcp-project/gobuilder:latest
FROM ${GOBUILDER} as builder
...
RUN go build ...
```

is there a way we can make some skaffold variables available for buildArgs?
