### ISSUE TITLE
Fails when running in a git worktree directory

### ISSUE THREAD

**Issue by geniass** [GoogleContainerTools/skaffold#323]
### Expected behavior
Runs successfully

### Actual behavior
While tagging the first image:
```
Error: running skaffold steps: build: build step: generating tag: determining current git commit: reference not found
```
### Information

Skaffold version: v0.3.0 
Operating system: Fedora 27 64 bit
Content of skaffold.yaml:
```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-example
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

  1. `git clone https://github.com/GoogleCloudPlatform/skaffold.git && cd skaffold`
  2. `git worktree add /tmp/repo <branch> && cd /tmp/repo/examples/getting-started`
  3. `skaffold run`
