### ISSUE TITLE
Multi-stage build support/artifact dependencies

### ISSUE THREAD

**Issue by robertgates55** [GoogleContainerTools/skaffold#3247]
We currently have a multi-stage Dockerfile, that we use to build multiple artifacts from the same base. Eg (pseudo-code):

```
FROM ubuntu:16.04 AS build_base
RUN apt-get install build_dep_1 build_dep_1
ADD blah
RUN mvn build some stuff

FROM ubuntu:16.04 AS runtime_1
COPY --from=build_base /target/runtime_1.sh /runtime_1.sh
ENTRYPOINT /runtime_1

FROM ubuntu:16.04 AS runtime_2
COPY --from=build_base /target/runtime_2.sh /runtime_2.sh
ENTRYPOINT /runtime_2
```

I then created a skaffold.yaml file that looks like:
```
apiVersion: skaffold/v1
kind: Config

build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
    - image: runtime_1
      docker:
        target: runtime_1
    - image: runtime_2
      docker:
        target: runtime_1
```

The issue is that obviously once using a cluster build (using kaniko), the `build_base` target ends up running in multiple containers at the same time, which is a waste of time and resource. Is there any way to structure this better to make use of kaniko caching?

(In our current setup for this, I'm using a `docker-compose` yaml to describe the artifacts as services, and using the `dependencies` section to describe that the runtimes must wait for the `build_base` service to have been built first)

Any help on suggested patterns would be great.
