### ISSUE TITLE
Can skaffold accept https proxy for running kubectl command?

### ISSUE THREAD

**Issue by dshetty312** [GoogleContainerTools/skaffold#3254]
### Expected behavior

Sample app deployed to GKE cluster

### Actual behavior

1.FATA[0011] reading manifests: kubectl create: Running [kubectl --context <context-name> create --dry-run -oyaml -f k8s-pod.yaml]: stdout , stderr: Unable to connect to the server: net/http: TLS handshake timeout
, err: exit status 1: exit status 1 

### Information

- Skaffold version: v1.0.0
- Operating system: Mac
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: <image-registry>/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
```
### Steps to reproduce the behavior
1.skaffold run

### My analysis:
Due to security constraints i cannot directly run kubectl commands from my laptop.
But if i run  https_proxy=$K8API_PROXY_IP:PORT kubectl get all , i get back the output.

So i was wondering if there was a way for me to let skaffold know about this https_proxy before running kubectl command.

Regards,
DS
