### ISSUE TITLE
Sync permission error for buildpacks

### ISSUE THREAD

**Issue by danacr** [GoogleContainerTools/skaffold#3256]
### Expected behavior
Skaffold succeeds in synchronising  local files

### Actual behavior
Skaffold fails in synchronising  local files

### Information

- Skaffold version: version v1.0.0-70-ga045e9d7
- Operating system: Mac OS X Catalina 10.15.1 (19B88) Darwin Kernel Version 19.0.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-buildpacks
    buildpack:
      builder: "heroku/buildpacks"
profiles:
- name: dev
  build:
    artifacts:
    - image: gcr.io/k8s-skaffold/skaffold-buildpacks
      sync:
        manual:
        - src: "**/*"
          dest: .
      buildpack:
        builder: heroku/buildpacks:18
```

### Steps to reproduce the behavior

1. git clone https://github.com/danacr/skaffold-buildpack-example
2. `skaffold dev --port-forward --profile dev -vdebug`
3. Edit `main.go`: `Hello, World! 2`
4. Save file

### Result:
```
Watching for changes...
DEBU[0270] Change detected notify.Write: "/Users/taaacda3/Dev/buildpack-example/main.go" 
INFO[0271] files modified: [main.go]                    
DEBU[0271] Using default workdir '/' for gcr.io/k8s-skaffold/skaffold-buildpacks:226a27f252db89d52fae02a0411c6ce9b7f2ba1cf18498a2b05993651abbae1b 
Syncing 1 files for gcr.io/k8s-skaffold/skaffold-buildpacks:226a27f252db89d52fae02a0411c6ce9b7f2ba1cf18498a2b05993651abbae1b
INFO[0271] Copying files: map[main.go:[/main.go]] to gcr.io/k8s-skaffold/skaffold-buildpacks:226a27f252db89d52fae02a0411c6ce9b7f2ba1cf18498a2b05993651abbae1b 
DEBU[0271] getting client config for kubeContext: ``    
DEBU[0271] Running command: [kubectl --context docker-desktop exec web-6b57c89c7d-5zcv5 --namespace default -c web -i -- tar xmf - -C / --no-same-owner] 
WARN[0271] Skipping deploy due to sync error: copying files: Running [kubectl --context docker-desktop exec web-6b57c89c7d-5zcv5 --namespace default -c web -i -- tar xmf - -C / --no-same-owner]: stdout , stderr: tar: Removing leading `/' from member names
tar: main.go: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
command terminated with exit code 2
, err: exit status 2: exit status 2 
Watching for changes...
```
