### ISSUE TITLE
v1 release of skaffold broke existing apps

### ISSUE THREAD

**Issue by simonz130** [GoogleContainerTools/skaffold#3264]
### Expected behavior
I use skaffold.yaml that doesn't define full paths for container images but rather only image name.
For example, guestbook-frontend instead of gcr.io/{project_id}/guestbook-frontend.
When executing *skaffold run* we pass *--default-repo* parameter to specify gcr.io/project_id that is appended to the name of the image in skaffold.yaml.
This used to work before skaffold 1.0 was released.
After it was released and without changes to the skaffold.yaml I tried to build, I got this error:
```
extracting projectID from image name: unable to guess GCP projectID from image name
```

### Information

- Skaffold version: version... v1.0.0
- Operating system: ... Windows 10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta6
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: guestbook-backend
    context: src/backend
  - image: guestbook-frontend
    context: src/frontend
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}```
```

### Steps to reproduce the behavior

1. skaffold run --enable-rpc -v info --rpc-http-port 60285 --filename skaffold.yaml -p cloudbuild --default-repo gcr.io/my-project-id
