### ISSUE TITLE
kubectl profile not deployed, when activated with helm profile

### ISSUE THREAD

**Issue by kvokka** [GoogleContainerTools/skaffold#3292]
When I execute `skaffold dev -p minikube_pubsub_emulator` I get correct output:
(The same statement is correct for another profile)

```bash
$ skaffold dev -p minikube_pubsub_emulator
Listing files to watch...
 - us.gcr.io/replay-gaming/pubsub-emulator
Generating tags...
 - us.gcr.io/replay-gaming/pubsub-emulator -> us.gcr.io/replay-gaming/pubsub-emulator:841f767-dirty
Checking cache...
 - us.gcr.io/replay-gaming/pubsub-emulator: Found Locally
Tags used in deployment:
 - us.gcr.io/replay-gaming/pubsub-emulator -> us.gcr.io/replay-gaming/pubsub-emulator:3fbcbf4dc672ff75fbc65284f2134c12ce2ed80a4bd5383b6f19a801a3e1e734
   local images can't be referenced by digest. They are tagged and referenced by a unique ID instead
Starting deploy...
 - service/pubsub-emulator created
 - deployment.apps/pubsub-emulator created
Watching for changes...
[pubsub-emulator-669d6d77f7-pktdb pubsub-emulator] Executing: /google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=0.0.0.0 --port=8538
```

But when I mix it with profile, which contains helm deploy, the image was built but the kubectl deploy process is omitted. Skaffold deploy only helm chart:

```bash
$ skaffold dev -p minikube_pubsub_emulator,minikube_helm_dependencies
Listing files to watch...
 - us.gcr.io/replay-gaming/pubsub-emulator
Generating tags...
 - us.gcr.io/replay-gaming/pubsub-emulator -> us.gcr.io/replay-gaming/pubsub-emulator:841f767-dirty
Checking cache...
 - us.gcr.io/replay-gaming/pubsub-emulator: Found Locally
Tags used in deployment:
 - us.gcr.io/replay-gaming/pubsub-emulator -> us.gcr.io/replay-gaming/pubsub-emulator:3fbcbf4dc672ff75fbc65284f2134c12ce2ed80a4bd5383b6f19a801a3e1e734
   local images can't be referenced by digest. They are tagged and referenced by a unique ID instead
Starting deploy...
Helm release redis not installed. Installing...
WARN[0000] image [us.gcr.io/replay-gaming/pubsub-emulator:3fbcbf4dc672ff75fbc65284f2134c12ce2ed80a4bd5383b6f19a801a3e1e734] is not used.
WARN[0000] image [us.gcr.io/replay-gaming/pubsub-emulator] is used instead.
WARN[0000] See helm sample for how to replace image names with their actual tags: https://github.com/GoogleContainerTools/skaffold/blob/master/examples/helm-deployment/skaffold.yaml
NAME:   redis
LAST DEPLOYED: Mon Nov 25 18:03:38 2019
NAMESPACE: default
STATUS: DEPLOYED

```

skaffold version 1.0.1
OS MacOs 10.15.1

```yaml
# skaffold.yaml
apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    gitCommit: {}
profiles:
  - name: minikube_pubsub_emulator
    build:
      artifacts:
        - image: us.gcr.io/replay-gaming/pubsub-emulator
          docker:
            dockerfile: support/skaffold/pubsub_emulator/Dockerfile
    deploy:
      kubectl:
        manifests:
          - support/skaffold/pubsub_emulator/k8s.yaml
  - name: minikube_helm_dependencies
    deploy:
      helm:
        releases:
          - name: redis
            chartPath: stable/redis
            remote: true
            valuesFiles:
              - support/skaffold/minikube/redis.yaml
```
