### ISSUE TITLE
skaffold not using local docker images with latest kind cluster v0.6.0

### ISSUE THREAD

**Issue by ct-sweeney** [GoogleContainerTools/skaffold#3296]
### Expected behavior
skaffold config set -k $(kubectl config current-context) local-cluster true set config to use local kind cluster
Skaffold Dev --port-forward should deploy and run containers from local docker images. Skaffold is not using local environment as latest version of kind now does not add the @kind to the context. 

### Actual behavior
Skaffold looks public "docker.io/library/ location. 
### Information

- Skaffold version: v1.0.0-103-g2c03a11b
- Operating system: ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha1
kind: Config
build:
 artifacts:
  - image: cloudsolutions-nginx
    context: ../../../source
    docker: 
      dockerfile: docker/frontend/build/Dockerfile
  - image: cloudsolutions-mysql
    context: ../../../.devcontainer/database
    docker:
      dockerfile: Dockerfile
  - image: cloudsolutions-backend
    context: ../../../source
    docker: 
      dockerfile: docker/backend/Dockerfile

#Address defined in skaffold.yaml not available in v1
portForward:
- resourceType: deployment
  resourceName: craft
  namespace: default
  port: 80
  address: 0.0.0.0
  localPort: 80

deploy:
  kustomize: {}

profiles:
- name: local
  build: 
    local: 
      push: false
  activation:
    - kubeContext: kubernetes-admin@kind
      command: dev, run
```

### Steps to reproduce the behavior

1. use latest kind v0.6.0 start cluster
2. set skaffold to use local-cluster true
3. Run skaffold dev --port-forward
