### ISSUE TITLE
Kind context detection failure

### ISSUE THREAD

**Issue by mcrmonkey** [GoogleContainerTools/skaffold#3297]
### Expected behavior
Skaffold should be able to detect and then push the stated container images in to my local kind cluster where i'm running kind v0.6.0

### Actual behavior
Skaffold does not push the local container images in to kind where kind version is v0.6.0 and seems to skip over it.

### Information

- Skaffold version: 1.0.0
- Kind version is v0.6.0
- Operating system: linux ( ubuntu base )
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha1                                                      
kind: Config                                                                       
build:                                                                             
  artifacts:                                                                       
  - image: test-image                                                              
    context: context                                                               
    docker:                                                                        
      dockerfile: Dockerfile
```

### Steps to reproduce the behavior

1. Spin up a kind cluster: `kind create cluster --name kind`
2. Set skaffold kube context ( optional ): `skaffold config set -k $(kubectl config current-context) local-cluster true` 
3. `skaffold dev --port-forward`

The kind cluster will be unable to find the referenced images locally and will attempt to reach out to docker.io to retrieve them.

I believe this issue is down to kind now setting the config context different to that of what it used to be.

I think this is down to this function: https://github.com/GoogleContainerTools/skaffold/blob/decf9f76b69f3a23c102cfccf4c4dba8feba30d0/pkg/skaffold/config/util.go#L192-L194

Its looking for a context name ending with `@kind`  example: `pink@kind` but the config file kind now produces sets the context to be something along the lines of `kind-kind`

As the desired context name isn't present the image loading function for kind isn't triggered ( https://github.com/GoogleContainerTools/skaffold/blob/e42c6851737a0d480699c56dde2dc40bfb9e3402/pkg/skaffold/runner/kind.go#L35 )

I could go through the process of renaming the context ( basically create a new one ) via kubectl but I believe that skaffold should be able to work this out based on the `kube context` config setting.

Could the potential fix be to remove the `@` and look for any context suffixed with `kind` ?  eg:

```diff
diff --git a/pkg/skaffold/config/util.go b/pkg/skaffold/config/util.go
index 6c53e6fe..387fe966 100644
--- a/pkg/skaffold/config/util.go
+++ b/pkg/skaffold/config/util.go
@@ -190,7 +190,7 @@ func isDefaultLocal(kubeContext string) bool {
 }
 
 func IsKindCluster(kubeContext string) bool {
-       return strings.HasSuffix(kubeContext, "@kind")
+       return strings.HasSuffix(kubeContext, "kind")
 }
 
 func IsUpdateCheckEnabled(configfile string) bool {

```
