### ISSUE TITLE
provide a command deploy strategy?

### ISSUE THREAD

**Issue by jstrachan** [GoogleContainerTools/skaffold#330]
In [Jenkins X](http://jenkins-x.io/) we'd like to use different commands to deploy a skaffold built image, such as:
* [jx preview](http://jenkins-x.io/commands/jx_preview) for creating [Preview Environments for Pull Requests](http://jenkins-x.io/developing/preview/)
* [jx promote](http://jenkins-x.io/commands/jx_promote) for [Promoting across Environments via GitOps](http://jenkins-x.io/developing/promote/)

to make it easy for skaffold to trigger these more course grained operations than a `kubectl apply` or `helm upgrade` I wondered if we should have a `Command` based `Deploy` strategy. 

So folks could do something like this in their `skaffold.yaml`:
```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-example
    workspace: .
  local: {}
deploy:
  commands:
    - command: jx
       args:
       - promote 
       - --env
       - staging 
       - --app 
       - cheese 
       - --version 
       - $VERSION 
```

Then folks can easily extend skaffold with any particular higher order tools to do Previews, Promotion or GitOps etc

We could then just allow arbitrary commands to be invoked on a deploy (either when in incremental build mode for developing or inside CI / CD pipelines).

We may want to expose the image names + versions as environment variables for easy consumption by the commands - but other than that it should be easy to plugin any kind of command

**Comment by jstrachan** [comment]
another option is a 'noop' option for deploy I guess. 

For doing releases we can pass in the version used on the CLI so if a release pipeline wants to do deployments differently (e.g. via GitOps) then thats fine, we can use skaffold just for the docker build part.

**Comment by jstrachan** [comment]
ah - ignore me! I've found that an empty manifests list works without failing the build:.
```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.MY_REGISTRY}}/{{.MY_USER}}/myimage"
  artifacts:
  - imageName: myimage
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
```
