### ISSUE TITLE
 v1.0.1  `skaffold dev` immediately cleans up after deploying to cluster with minikube  v1.5.2

### ISSUE THREAD

**Issue by mloesch** [GoogleContainerTools/skaffold#3303]
### Expected behavior
`skaffold dev` will deploy and keep the pods running

### Actual behavior
`skaffold dev` deploys and cleans up immediately afterwards (like if you would run `skaffold delete`). 

Note: this behavior is reproducible with minikube but not when using e.g. *kind* to create the local cluster.

### Information

- Skaffold version: v1.0.1
- minikube version:  v1.5.2 (latest stable release)
- Operating system: Ubuntu 19.10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
metadata:
  name: skaffold-test
deploy:
  kubeContext: minikube
  kubectl:
    manifests:
    - mailhog.yaml
```

### Steps to reproduce the behavior

1. https://github.com/mloesch/skaffold-3021
2. `skaffold dev`
3. Will deploy and immediately clean up:

```
Listing files to watch...
Generating tags...
Checking cache...
Tags used in deployment:
Starting deploy...
 - service/mailhog created
 - deployment.apps/mailhog created
Cleaning up...
 - service "mailhog" deleted
 - deployment.apps "mailhog" deleted
FATA[0004] starting logger: initializing aggregate pod watcher: initializing pod watcher for : Get https://192.168.99.104:8443/api/v1/pods?timeout=876000h0m0s&timeoutSeconds=3153600000&watch=true: dial tcp 192.168.99.104:8443: connect: no route to host 
```
