### ISSUE TITLE
ImagePullBackOff for images on local environment

### ISSUE THREAD

**Issue by petr-buchin** [GoogleContainerTools/skaffold#3310]
### Expected behavior
We have a really big platform, created using SOA. 
It has many services, and all that services could not be launched on a single developer machine.
Therefore we use Skaffold profiles to launch separate projects.

We also have separate Skaffold profiles for all the artifacts, in order to be able to run local builds in parallel processes, something like that:

```
skaffold build -p=artifact-a --cache-artifacts=true
skaffold build -p=artifact-b --cache-artifacts=true
skaffold build -p=artifact-c --cache-artifacts=true
```

After all artifacts are built I include all needed profile names in skaffold command, like follows:

```
skaffold dev -p=artifact-a,artifact-b,artifact-c,service-a,service-b,service-c --cache-artifacts=true
```

We use Helm as our deployer, and command above works and creates needed `k8s` resources.

However, all our pods aren't running and have state `ImagePullBackOff`.
`kubectl describe pod` shows that pods are trying to pull images with `latest` tag instead of tag, generated by Skaffold. 
At the same time `docker image ls` shows that we have all image tags, created by Skaffold.

Thus, **expected behavior** is for pods to use skaffold-generated image tags.

### Actual behavior
Pods use `latest` image tags

### Information

- Skaffold version: 1.0.1
- MacOs Catalina
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta16
kind: Config
metadata:
  name: platform
build:
  local:
    push: false
  artifacts: []
deploy:
  helm:
    releases:
      - name: example-release
        chartPath: charts/example
        valuesFiles:
        - values-file-a.yaml
        - values-file-b.yaml
        values: {}
profiles:
- name: artifact-a
  patches:
  - op: add
    path: /build/artifacts
    value:
    - image: example/artifact-a
      context: artifact-a
      docker:
        dockerfile: Dockerfile
  - op: add
     path: /deploy/helm/releases/0/values
     value:
       subchart-a.image: example/artifact-a
- name: artifact-b
  patches:
  - op: add
    path: /build/artifacts
    value:
    - image: example/artifact-b
      context: artifact-b
      docker:
        dockerfile: Dockerfile
  - op: add
    path: /deploy/helm/releases/0/values
    value:
      subchart-b.image: example/artifact-b
- name: service-a
  patches:
  - op: add
    path: /deploy/helm/releases/0/valuesFiles/-
    value: charts/example/values/_services/service-a.yaml # enables some subchart
- name: service-b
  patches:
  - op: add
    path: /deploy/helm/releases/0/valuesFiles/-
    value: charts/example/values/_services/service-b.yaml # enables some subchart

```
