### ISSUE TITLE
kaniko.buildArgs does not accept environment variables via the go template syntax

### ISSUE THREAD

**Issue by zendril** [GoogleContainerTools/skaffold#3314]
### Expected behavior
The following should allow the value to be pulled from ENV var, according to the docs https://skaffold.dev/docs/references/yaml/
```
    kaniko
      buildArgs:
        key3: {{.ENV_VARIABLE}}
```

### Actual behavior
It throws the following error:
`time="2019-11-27T16:55:11-05:00" level=fatal msg="creating runner: parsing skaffold config: unable to parse YAML: yaml: invalid map key: map[interface {}]interface {}{\".ENV_VARIABLE\":interface {}(nil)}"`

### Information

- Skaffold version: 1.0.0
- Operating system: windows
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: sampleregistry/sample-image
    kaniko:
      buildContext:
        localDir: {}
      buildArgs:
        key3: {{.ENV_VARIABLE}}
  cluster:
    namespace: my-namespace
profiles:
- name: local
  patches:
  - op: add
    path: /build/cluster/dockerConfig
    value: {secretName: "kaniko-secret"}
```

### Steps to reproduce the behavior

1. A directory with the skaffold.yml above in it.
2. `skaffold build`
