### ISSUE TITLE
Helm deployer: "values" cannot be used for anything except image names 

### ISSUE THREAD

**Issue by petr-buchin** [GoogleContainerTools/skaffold#3316]
### Expected behavior
Skaffold documentation says that `values` field in Helm release is a map containing

> key-value pairs supplementing the Helm values file.

### Actual behavior

From what I see in the code and from skaffold behavior, at the moment `values` field can contain **only**  mapping from helm values to image names.

https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/helm.go#L274
```go
// Values
params, err := h.joinTagsToBuildResult(builds, r.Values)
if err != nil {
	return nil, errors.Wrap(err, "matching build results to chart values")
}
```

The code above shows that `*HelmDeployer.deployRelease()` method passes **all** values to method
`joinTagsToBuildResult()`, which uses it as parameter `params` as follows:

https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/helm.go#L482
```go
for param, imageName := range params {
	b, ok := imageToBuildResult[imageName]
	if !ok {
		return nil, fmt.Errorf("no build present for %s", imageName)
	}

	paramToBuildResult[param] = b
}
```

Thus, **every** value in `values` map must be an image name, otherwise deploy will fail.
Is this a bug or an expected behavior? If this is an expected behavior, I believe this should be included in docs.

### Information

- Skaffold version: `master`
- Operating system: any
- Contents of skaffold.yaml: any

Thanks in advance!

**Comment by balopat** [comment]
🤦‍♂  
Thanks for opening! Yes, this looks like a weird one. I see no reason why only accept image related values.

**Comment by TBBle** [comment]
In case it's not clear, there's `overrides` which can be used for non-image values.

The naming is unfortunate... `values` is the place Skaffold looks for image names to match `artifacts`, while `overrides` is used to build a _values.yaml_. And the [documentation of this is missing](https://skaffold.dev/docs/references/yaml/). (This was "tribal knowledge" for us. Someone told me that when I joined a project using skaffold, so I'd never checked what the docs say).

**Comment by nkubala** [comment]
ok, I'm moving this from a "bug" to an "enhancement" since it technically isn't a bug, but also isn't technically a docs issue either...we're just doing something silly in the code and also not documenting it well which is creating a seriously annoying user experience for helm users.

our helm implementation has some "quirks" which can sometimes result in some very strange behavior. we're working on collecting thoughts and issues around this to see how we can improve things on our side, so bear with us as we figure it out 🙏

**Comment by tete17** [comment]
Ok I want to tackle this problem and I think I have a plan but I want to get some discussion before I start coding.

Taking a look at the current definition of a HelmRelease I see a lot of duplication.
 * `Values` is right now only used for replacing images names with the ones with tags build by Skaffold, when in reality it sound more like a general way of passing arbitrary values instead. https://github.com/GoogleContainerTools/skaffold/blob/58e72a691b6b1b3a3c165436b5fb9dd7c06c7224/pkg/skaffold/schema/latest/config.go#L503
 * `SetValues` does the job of what we expect `Values` to do and serves as a general way of passing extra arguments to Helm. I propose to merge it into `Values` and let skaffold detect automatically when one is a image value and when is a simple key-value pair. https://github.com/GoogleContainerTools/skaffold/blob/58e72a691b6b1b3a3c165436b5fb9dd7c06c7224/pkg/skaffold/schema/latest/config.go#L513
 * `SetValueTemplates` is the same as `SetValues` expect enviroment values get expended before they get passed to the cli. I also propose it to merge it to the `Values` and just try to expand all values passed. https://github.com/GoogleContainerTools/skaffold/blob/58e72a691b6b1b3a3c165436b5fb9dd7c06c7224/pkg/skaffold/schema/latest/config.go#L519
 * `Overrides` This one intrigues me. Feels like just another way of exposing the same functionality of `SetValues`. It may be more useful to sort of inline a yaml file so maybe we should leave it, but encourage people to use the other more simple ones.https://github.com/GoogleContainerTools/skaffold/blob/58e72a691b6b1b3a3c165436b5fb9dd7c06c7224/pkg/skaffold/schema/latest/config.go#L547

I think this will solve the issue here, simplify code as well as stream-line the experience for users since their is less options to investigate and fiddle around.

**Comment by TBBle** [comment]
The difference between `setValues` and `overrides` is that the former uses the `--set` command-line flag for each values, and the latter uses the `--values` command-line flag for the whole block.

The two behave slightly differently in Helm, at least in stickiness across upgrades, and merging arrays. You can't modify an array default with `--values`, it ends up overwriting it.

Also, `setValues` keys need embedded quotes in order to set values for keys with `.` in them. I'm not sure that's possible in the skaffold config, off hand.

**Comment by TBBle** [comment]
How would Skaffold detect an image parameter? It's only by convention and documentation that _humans_ know which one is an image parameter, and what its structure is. And skaffold already does not cover several existing structures seen in the wild.

**Comment by tete17** [comment]
Thanks for the explanation @TBBle I didn't knew `--set` & and `--values` had slightly different behaviour.

I guess that is another argument for keeping `override` as it is. I only propose to merge the behaviour is `values`, `setValues` & `setValuesTemplated` into one.

You can take a look here on how the helm deployer detect image parameters. https://github.com/GoogleContainerTools/skaffold/blob/c261d1c07e7f2b2e44935d98a6a8896e41693111/pkg/skaffold/deploy/helm.go#L600
and it usage here https://github.com/GoogleContainerTools/skaffold/blob/c261d1c07e7f2b2e44935d98a6a8896e41693111/pkg/skaffold/deploy/helm.go#L403

The TLDR is that skaffold looks at all the values in the map of `Values` and if one matches with the name of the image build in the previous tage of the pipeline it adds a `--set-string` command with the original key present in the skaffold config and, instead of the name of the image, the image plus tag combination.

The current behaviour that this issue is about, as I understand it is that skaffold assumes all key-value pairs of the `Values` filed are image names. This leads to confusion because I in particular also want to use that value for general `--set` arguments and not separate it in a specific config `setValues`. 

Regarding your comment about having trouble with `setValues` and key elements that contain `.` (I think a good example could be annotations for ingresses such as `kubernetes.io/ingress.class: nginx`) I think skaffold does support such things. If you go to `integration/testdata/helm` and replace the skaffold config for this
```yaml
apiVersion: skaffold/v1beta10
kind: Config
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: skaffold-helm
      values:
        image: gcr.io/k8s-skaffold/skaffold-helm
      setValues:
        ingress.annotations.kubernetes\.io\/ingress\.class: nginx
```

you can try it by deploying it.

**Comment by TBBle** [comment]
Yeah, I had forgotten you could use `\.` to avoid needing to embed the quotes in the command-line.

That's a good example of where using `overrides` would make that easier to parse for the reader as well.

```
overrides:
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
```

----

The problem with applying the Helm image-detection logic to a block of values that are _not_ only images is that it'll match _any key_ that happens to match an image name as being an image parameter, and replace it with either the relevant full tagged image repository, the "fqn" strategy, or an object structured with details of the image registry, repository and tag, for the other strategies.

This is seems pretty clearly disruptive to me.

If we want to combine the image overrides with regular value overrides, it'd be better to use something like [`setValueTemplates`](https://skaffold.dev/docs/environment/templating/) to let you manually insert the desired parts of the values... Something like
```yaml
build:
  artifacts:
  - image: someartifact
setValueTempates:
  splitImage.registry: {{.ARTIFACTS.someartifact.registry}}
  splitImage.repository: {{.ARTIFACTS.someartifact.repository}}
  splitImage.tag: {{.ARTIFACTS.someartifact.tag}}
  subChart.lessSplitImage.registry: {{.ARTIFACTS.someartifact.repository}}/{{.ARTIFACTS.someartifact.registry}}
  subChart.lessSplitImage.tag: {{.ARTIFACTS.someartifact.tag}}
  oneLinerImage: {{.ARTIFACTS.someartifact.repository}}/{{.ARTIFACTS.someartifact.registry}}:{{.ARTIFACTS.someartifact.tag}}
```

And perhaps some appropriate shortcuts for automating some of that mess, e.g.
```yaml
[...]
setValueTempates:
  splitImage: {{.ARTIFACTS.someartifact.helmExplicitRegistry}}
  subChart.lessSplitImage: {{.ARTIFACTS.someartifact.helmCombinedRegistry}}
  oneLinerImage: {{.ARTIFACTS.someartifact.fqn}}
```
which would generate the same output as the preceding version.

This would also be an opportunity to fix one of the issues with the `helmStrategy` field, in that it's global to the Helm deployment, while the layout is actually local to each Helm chart. So you actually _cannot_ do what I described above in current Skaffold: every image reference in the Helm chart must either take a single string, or one of the two defined object layouts, which is a real pain when trying to use Skaffold to test builds or patches of external containers and also the local containers that interact with them.
