### ISSUE TITLE
Dependencies in kubectl deployments?

### ISSUE THREAD

**Issue by dirkevertz** [GoogleContainerTools/skaffold#3321]
Is there any possibility to take care of dependencies or to enforce that separate kubectl commands are launched (instead of a single one)? I am facing the issue, that the deployment fails due to an "unable to recognize"-error:

error: unable to recognize "c:\\\\daten\\\\projects\\\\kubernetes\\\\nodejsSkaffold\\\\kubernetes-manifests\\\\4_rate_limiting.yaml": no matches for kind "KongPlugin" in version "configuration.konghq.com/v1"

[log.txt](https://github.com/GoogleContainerTools/skaffold/files/3901697/log.txt)
[log.txt](https://github.com/GoogleContainerTools/skaffold/files/3901701/log.txt)

### Expected behavior
Enforce seperate execution of kubectl for certain files:
 
1st step: execute ./kubernetes-manifests/0_all-in-one-dbless.yaml 
2nd step: execute 
     - ./kubernetes-manifests/1_nodejs.deployment.yaml
    - ./kubernetes-manifests/2_nodejs.service.deployment.yaml
    - ./kubernetes-manifests/3_nodejs.ingress.deployment.yaml
    - ./kubernetes-manifests/4_rate_limiting.yaml

### Actual behavior
Currently a single kubectl is executed:

kubectl --context docker-desktop create --validate=false --dry-run -oyaml -f c:\\daten\\projects\\kubernetes\nodejsSkaffold\\kubernetes-manifests\\0_all-in-one-dbless.yaml -f c:\\daten\\projects\\kubernetes\\nodejsSkaffold\\kubernetes-manifests\\1_nodejs.deployment.yaml -f c:\\daten\\projects\\kubernetes\\nodejsSkaffold\\kubernetes-manifests\\2_nodejs.service.deployment.yaml -f c:\\daten\\projects\\kubernetes\\nodejsSkaffold\\kubernetes-manifests\\3_nodejs.ingress.deployment.yaml -f c:\\daten\\projects\\kubernetes\\nodejsSkaffold\\kubernetes-manifests\\4_rate_limiting.yaml

### Information

- Skaffold version: v1.0.1
- Operating system: Windows 10
- Contents of skaffold.yaml:

apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: nodejs
    context: .
    docker:
      noCache: true
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    flags:
      apply:
        - "--validate=false"
    manifests:
    # 0_all-in-one-dbless.yaml contents https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-dbless.yaml
    - ./kubernetes-manifests/0_all-in-one-dbless.yaml
    - ./kubernetes-manifests/1_nodejs.deployment.yaml
    - ./kubernetes-manifests/2_nodejs.service.deployment.yaml
    - ./kubernetes-manifests/3_nodejs.ingress.deployment.yaml
    - ./kubernetes-manifests/4_rate_limiting.yaml

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by tejal29** [comment]
@dirkevertz We are aware of this issue and the team is working on a plan to preserve 1* (numbering) for kubectl render support.

**Comment by tejal29** [comment]
Subtaks for #5857

**Comment by gsquared94** [comment]
I would recommend trying out [kpt](https://github.com/GoogleContainerTools/kpt) deployer that can handle a lot of these scenarios about the right order of deploys. Here's an example how: https://github.com/GoogleContainerTools/skaffold/tree/master/codelab/02_kpt-deploy

**Alternately,**

Since you know the exact order that the deploy needs to be applied you can also do:
_skaffold.yaml_:
```yaml
apiVersion: skaffold/v2beta18
kind: Config
deploy:
  kubectl: 
     - ./kubernetes-manifests/0_all-in-one-dbless.yaml
---
apiVersion: skaffold/v2beta18
kind: Config
deploy:
  kubectl: 
    - ./kubernetes-manifests/1_nodejs.deployment.yaml
    - ./kubernetes-manifests/2_nodejs.service.deployment.yaml
    - ./kubernetes-manifests/3_nodejs.ingress.deployment.yaml
    - ./kubernetes-manifests/4_rate_limiting.yaml
     
```
