### ISSUE TITLE
jib builder: support for adding arguments to Maven on command line

### ISSUE THREAD

**Issue by bjornmagnusson** [GoogleContainerTools/skaffold#3323]
Need a way to be able to pass arbitrary arguments to Maven on command line, e.g for overwriting certain build properties. The current implementation does only support static arguments in skaffold.yaml but this is a bit different.

E.g. one situation I have faced is overriding location of docker registry when building images. When in office close to the docker registry hosted we use that one, but when outside office we have a need to be able to easily override that and point to another one, e.g. one hosted on local machine.

### Expected behavior
Possible to add arbitrary arguments to jib builder when running skaffold dev/build/run

### Actual behavior
Not possible to pass arguments

### Information

- Skaffold version: version...1.0.0
- Operating system: ...Windows
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: startkit
    jib:
      project: :startkit-web-jar
      args:
      - -Pdocker
deploy:
  kubectl:
    manifests:
    - skaffold/k8s-*
portForward:
- resourceType: pod
  resourceName: startkit
  namespace: default
  port: 8080
  localPort: 8080
```

**Comment by tejal29** [comment]
@bjornmagnusson you can specify registry override with `--default-repo` flag.
That said, are there any other maven builder specific flag you need to pass to jib builder which are not part of the config?

**Comment by bjornmagnusson** [comment]
Thanks for that tips, but it doesn´t solve my use case.

Consider the following properties defined in pom.xml
`
<properties>
  <property1>value1</property1>
  <property2>value2</property2>
  <property3>value3</property3>
</properties>
`

I have a need to be able to override these (without manually editing skaffold.yaml) these in skaffold executions. The  properties are project specific and not tied directly to properties in jib.

For example, using skaffold run with "--maven-args="-Dproperty1=whatever-value" "

**Comment by zhuming** [comment]
work around... :)
use maven profile and specify profile in skaffold.yaml with
```
build:
  artifacts:
  - image: myartifactory.repo.com/hello/hw
    context: .
    jibMaven: {"profile":"your-favorite-profile"}
```
