### ISSUE TITLE
Proposal: Cleanup / Standardize value template / env vars around IMAGE

### ISSUE THREAD

**Issue by kylewolfe** [GoogleContainerTools/skaffold#3343]
At the moment, there are inconsistencies between [templating](https://skaffold.dev/docs/environment/templating/) and `build.artifacts[i].custom` at the least, specifically around `IMAGE` / `IMAGE_NAME`, and the lack of `IMAGE_TAG`. If these implementations were made consistent and expanded to support `IMAGE_NAME` and `IMAGE_TAG`, then I believe this proposal would potentially resolve: #500, increase possibilities of custom builds, and create continuity.

## Current State

| Operation                                   | Variable     | Value             |
|---------------------------------------------|--------------|-------------------|
| `build.artifacts[i].custom`                 | `IMAGE`      | api:d093763-dirty |
| `build.artifacts[i].custom`                 | `IMAGE_NAME` | `nil`             |
| `build.artifacts[i].custom`                 | `IMAGE_TAG`  | `nil`             |
| `build.artifacts[i].custom`                 | `IMAGES`     | api:d093763-dirty |
| `deploy.helm.releases[i].setValueTemplates` | `IMAGE`      | `nil`             |
| `deploy.helm.releases[i].setValueTemplates` | `IMAGE_NAME` | `nil`             |
| `deploy.helm.releases[i].setValueTemplates` | `IMAGE_TAG`  | `nil`             |
| `deploy.helm.releases[i].setValueTemplates` | `IMAGES`     | `nil`             |

### Reproduce
```yaml
apiVersion: skaffold/v1
kind: Config
metadata:
  name: my-app

build:
  artifacts:
    - image: my-api
      context: src/api
      custom:
        buildCommand: "sh -c 'env | grep IMAGE && docker build . -t ${IMAGE}'"

deploy:
  helm:
    releases:
      - name: my-api
        chartPath: my-chart
        imageStrategy:
          helm: {} # required to override image.repository
        values:
          image: my-api # required to override image.repository
        setValueTemplates:
          image: "{{.IMAGE}}"
          image.tag: "{{.IMAGE_TAG}}"
          images: "{{.IMAGES}}"
          username: "{{.USERNAME}}"
```

`skaffold build` excerpt:
```
IMAGES=my-api:d093763-dirty
PUSH_IMAGE=false
IMAGE=my-api:d093763-dirty
```

`skaffold dev -v debug` excerpt:
```
time="2019-12-03T10:48:20-05:00" level=debug msg="Running command: [helm --kube-context docker-for-desktop install --name my-api my-chart --set image.repository=my-api,image.tag=965ea09ff2ebd2b9eeec88cd822ce156f6674c7e99be082c7efac3c62f3ff652 --set image=<no value> --set image.tag=<no value> --set images=<no value> --set username=kyle]"
```

## Desired State

| Operation                                   | Variable     | Value         |
|---------------------------------------------|--------------|---------------|
| `build.artifacts[i].custom`                 | `IMAGE_NAME` | api           |
| `build.artifacts[i].custom`                 | `IMAGE_TAG`  | d093763-dirty |
| `deploy.helm.releases[i].setValueTemplates` | `IMAGE_NAME` | api           |
| `deploy.helm.releases[i].setValueTemplates` | `IMAGE_TAG`  | d093763-dirty |

This would allow for more control in custom builds, eg:

```yaml
build:
  artifacts:
    - image: my-api
      context: src/api
      custom:
        buildCommand: "build.sh && docker build . -t ${IMAGE} -t ${IMAGE_NAME}:${IMAGE_TAG}'" 
```
The above would allow build.sh to utilize the now separated variables (eg: injecting into go builds w/ ld flags).

As well as solve for #500:

```yaml
deploy:
  helm:
    releases:
      - name: my-api
        chartPath: my-chart
        values:
          image: my-api # still required to associate w/ build artifact?
        setValueTemplates:
          subchart.image.tag: "{{.IMAGE_TAG}}"
          sidecar.image.tag: "{{.IMAGE_TAG}}"
```

There is obvious run in with imageStrategy here, however this should not break v1. For helm at least, I would not see a need for imageStrategy in v2.
