### ISSUE TITLE
git tag contains "/" causes docker build failure

### ISSUE THREAD

**Issue by zhuming** [GoogleContainerTools/skaffold#3344]
### Expected behavior
- Any valid Dockerfile
- git tag name contains "/"
- run skaffold build 
--> expect the image is built and tagged properly

### Actual behavior
skaffold build fails with error message

```
Generating tags...
 - my-docker-repositories.com/helloworld/hw -> cxm-my-docker-repositories.com/helloworld/hw:ms/1.0.0-94-g93057a3
Checking cache...
 - my-docker-repositories.com/helloworld/hw: Not found. Building
Building [my-docker-repositories.com/helloworld/hw]...
FATA[0001] failed to build: build failed: build failed: building [my-docker-repositories.com/helloworld/hw]: build artifact: docker build: Error response from daemon: invalid reference format
```
### Information

- Skaffold version: version... 0.6.0 and 1.0.0
- Operating system: ... MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: my-docker-repositories.com/helloworld/hw
    context:
      .
deploy:
  kubectl:
    manifests:
    - k8s/hw-dev.yaml

```

### Steps to reproduce the behavior

1. clone any repo
2. git tag tag/slash
3. skaffold build
