### ISSUE TITLE
skaffold run is not detecting my current context

### ISSUE THREAD

**Issue by pisymbol** [GoogleContainerTools/skaffold#3353]
### Expected behavior

I would expect during a 'skaffold run' that --context is set.

### Actual behavior

--context is not set and skaffold wants to talk to a local cluster (e.g. minikube).

### Information

- Skaffold version: v1.0.1
- Operating system: 10.15.1 OSX
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    envTemplate:
        template: "{{.IMAGE_NAME}}:0.1"
  artifacts:
    - image: somerepo/someimage
  local: {}
deploy:
  kubectl:
    manifests:
     - k8s/*.yaml
```

### Steps to reproduce the behavior

Just running 'skaffold run' on my system.

```k config current-context```

Returns my context.

Any idea what I am doing run? I can set the conext by doing 'skaffold run --kube-context=blah' and that works. But why isn't skaffold autodetecting by current context?

I do have docker for desktop/minikube installed but am not currently using it.
