### ISSUE TITLE
[Bug] Build artifacts sync.infer does not work

### ISSUE THREAD

**Issue by kvokka** [GoogleContainerTools/skaffold#3376]
# Expected behavior

Full description [here](https://skaffold.dev/docs/pipeline-stages/filesync/)

### Actual behavior

With `infer` syntax i do not get the file sync, when with the same, using manual sync everything works.

for the testing purposes i used the file `app/views/profile/index.html.haml` (if it matters)

### Information

- Skaffold version: version 1.0.1
- Operating system: MacOs 10.15.1
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    gitCommit: {}
profiles:
  - name: rails_dev
    build:
      artifacts:
        - image: us.gcr.io/replay-gaming/rails
          docker:
            dockerfile: docker/development/Dockerfile
          context: rails
          sync:
            # but this commented syntax works
            # manual:
            #  - src: 'app/**/*'
            #   dest: '.'
            infer:
              - 'app/**/*'
    deploy:
      helm:
        releases:
          - name: rails
            chartPath: rails/charts/rails
            valuesFiles:
              - rails/charts/rails/values.development.yaml
            skipBuildDependencies: true
            values:
              image: us.gcr.io/replay-gaming/rails


```
