### ISSUE TITLE
Unable to see logs under microk8s or minikube - better documentation for running Skaffold on local Kubernetes needed

### ISSUE THREAD

**Issue by iirekm** [GoogleContainerTools/skaffold#3383]
### Expected behavior
`skaffold run --tail=true` or `skaffold dev --tail=true` should show command output. It isn't so in my case :-(

### Actual behavior

No output.

### Information

- Skaffold version: 1.0.1
- Operating system: Ubuntu 18.04 + microk8s Kubernetes installation
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
metadata:
  name: test
deploy:
  kubectl:
    manifests:
    - pod.yml
```

`pod.yml`:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: ubuntu:bionic
      command:
        - sh
        - -c
        - while true; do echo hello!; sleep 1; done
```

`kubectl logs -f pod/test` works normally. There's something wrong with Scaffold.

### Steps to reproduce the behavior

as above

**Comment by iirekm** [comment]
Tried with the official examples and with minikube - the same, so this is not an issue with microk8s or my .yml files

**Comment by iirekm** [comment]
The reason is the following line:
```go
if !a.podSelector.Select(pod) {
					continue
				}
```

When I comment it out it works. There's something wrong with `PodSelector`

For development I don't want to use remote Kubernetes (on Google Cloud for example), microk8s or minikube is enough. Please provide examples how to setup skaffold with microk8s or minikube.

**Comment by iirekm** [comment]
After hours and hours of debugging I made it working under microk8s:

`skaffold.yml`:
```yml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: localhost:32000/test
deploy:
  kubectl:
    manifests:
      - pod.yml
```

`Dockerfile`: (even this simple example needs one)
```dockerfile
FROM ubuntu:bionic
```
`pod.yml`:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: localhost:32000/test
      command:
        - echo
        - hello2!
```

Anyway, the documentation of Skaffold and how PodSelector works are completely counterintuitive, although I have prior experience with Kubernetes.
