### ISSUE TITLE
UPGRADE FAILED: "skaffold-helm" has no deployed releases still persists

### ISSUE THREAD

**Issue by iirekm** [GoogleContainerTools/skaffold#3386]
### Expected behavior

When I call `scaffold run` in the `examples/helm-deployemnt` directory it should deploy. 

### Actual behavior

`UPGRADE FAILED: "skaffold-helm" has no deployed releases`
This issue was already raised and marked as 'closed' - it still persists!

### Information

- Skaffold version: 1.0.1
- Helm version: 3.0.1

**Comment by iirekm** [comment]
Workaround: 
```yaml
deploy:
   ...
    flags:
      upgrade:
        - --install
```
