### ISSUE TITLE
Helm 3: `Error: unknown flag: --purge` during `skaffold delete`

### ISSUE THREAD

**Issue by iirekm** [GoogleContainerTools/skaffold#3387]
Workaround: `helm delete <release-name>`

**Comment by balopat** [comment]
related change in helm: https://github.com/helm/helm/pull/5283
cc @briandealwis

**Comment by tejal29** [comment]
Please use the following command
`skaffold dev --cleanup=false` or
`skaffold debug --cleanup=false`

You would also need to add the following configuration to `skaffold.yaml`
```
deploy:
      helm:
        flags:
          upgrade: ["-i"]
```
