### ISSUE TITLE
Helm deployment doesn't work for charts that are not already installed

### ISSUE THREAD

**Issue by SakrImpargo** [GoogleContainerTools/skaffold#3400]
### Expected behavior
Should deploy charts that we're installed beforehand without issues.

### Actual behavior
The following error happens when trying to `skaffold run` the `skaffold.yaml` attached below.
```
Error: UPGRADE FAILED: "rabbitmq-server" has no deployed releases
```

### Information

- Skaffold version: version 1.0.1
- Operating system: Ubuntu 19.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
deploy:
  helm:
    releases:
    - name: rabbitmq-server
      chartPath: stable/rabbitmq
      remote: true
```

### Steps to reproduce the behavior

1. Create a `skaffold.yaml` with the values pasted above
2. `skaffold run`
3. See error.
