### ISSUE TITLE
Same directory cannot be synced to two artifacts

### ISSUE THREAD

**Issue by petr-buchin** [GoogleContainerTools/skaffold#3403]
### Expected behavior
I want to sync the same directory to the two different artifacts/images.
I specify manual sync rule for that directory, and this rule is identical for the two artifacts.
I expect that when files in this directory are changed, they get synchronized to both containers, which are running from images, specified in build artifacts in `skaffold.yaml`
### Actual behavior
However, when files in this directory are changed, directory gets synchronized only to the one of the pods/artifacts, specified in `skaffold.yaml`.

Having the `skaffold.yaml` like below, files get synchronized to the container running `myrepo/php-fpm`, but not to container running `myrepo/nginx`.

Also, if this is important, this two containers are running in the same pod.

### Information

- Skaffold version: 1.0.1
- Operating system: MacOs Catalina
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
metadata:
  name: myproject
build:
  local:
    push: false
  artifacts:
  - image: myrepo/myimage
    context: ../mydir
    docker:
      dockerfile: my.Dockerfile

deploy:
  helm:
    releases:
      - name: my-release
        chartPath: charts/mychart
        valuesFiles:
        - some-file.yaml
        - some-other-file.yaml
        values:
          some.image: some-repo/some-image
profiles:
- name: myapp-nginx
  patches:
  - op: add
    path: /build/artifacts/-
    value:
      image: myrepo/nginx
      context: ../mydir
      docker:
        dockerfile: docker/prod/nginx/Dockerfile
      sync:
        manual:
        - dest: /data/myapp/public
          src: public/**/*
          strip: public
  - op: add
    path: /deploy/helm/releases/0/values/myapp.nginx.image
    value: myrepo/nginx
- name: myapp-php-fpm
  patches:
  - op: add
    path: /build/artifacts/-
    value:
      image: myrepo/php-fpm
      context: ../mydir
      docker:
        dockerfile: docker/prod/php-fpm/Dockerfile
      sync:
        manual:
        - dest: /data/myapp/public
          src: public/**/*
          strip: public
  - op: add
    path: /deploy/helm/releases/0/values/myapp.phpFpm.image
    value: myrepo/php-fpm
```
