### ISSUE TITLE
`skaffold init` can produce an erroneous config with non-default Dockerfile name

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#3405]
Run `skaffold init` on a folder that looks like this:
```
./front/main.go
./front/DockerfileProd
./k8s.yaml
```

It should produce this config:
```yaml
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: getting-started
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
    context: front
    docker:
      dockerfile: DockerfileProd
  tagPolicy:
    gitCommit: {}
  local: {}
deploy:
  kubectl:
    manifests:
    - k8s.yaml
```

It instead produces this config:
```yaml
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: getting-started
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
    context: front
    docker:
      dockerfile: front/DockerfileProd
  tagPolicy:
    gitCommit: {}
  local: {}
deploy:
  kubectl:
    manifests:
    - k8s.yaml
```
