### ISSUE TITLE
Sync does not sync all files from corresponding directory

### ISSUE THREAD

**Issue by petr-buchin** [GoogleContainerTools/skaffold#3411]
### Expected behavior
I use `gulp` to build my static files for frontend.
I also use `gulp.watch()` locally in dev mode to rebuild static files as code changes.
I configured Skaffold manual sync rule to propagate all changes from my local directory `public/dist` (rebuilt static files) to the container in k8s cluster. 
Expected behavior is to get all files from this directory synchronized to container. 
### Actual behavior
Skaffold does not sync files to container at all, if I use default sync mode (because `gulp.watch()` keeps files open), so after some googling I switched to `--trigger=polling` mode.
With this sync mode some files are synced to my container, but not all.
Somehow part of the files are synchronized, and part of the files are present on my local machine, but not in container.
But if I change one of files, that are present on local machine, but not in container, using some text redactor, that file is synchronized to container.
### Information

- Skaffold version: master
- Operating system: MacOs Catalina
- Contents of skaffold.yaml:
Below I provide part of `skaffold.yaml` that corresponds to that problem
```yaml
profiles:
- name: myapp-nginx
  patches:
  - op: add
    path: /build/artifacts/-
    value:
      image: myrepo/myapp-nginx
      context: myapp
      docker:
        dockerfile: docker/prod/nginx/Dockerfile
      sync:
        manual:
        - dest: /data/myapp/public
          src: public/**/*
          strip: public
```
