### ISSUE TITLE
Kaniko builds won't complete with ISTIO sidecar

### ISSUE THREAD

**Issue by jlewi** [GoogleContainerTools/skaffold#3442]
### Expected behavior

Running skaffold build will build the container using kaniko as configured in skaffold.yaml.

When the kaniko container is complete; skaffold will detect the container as finished and exit.

### Actual behavior

* I'm running Kaniko in a namespace with ISTIO side car injection turned on.
* The kaniko container completes but the ISTIO side car remains running
* kubectl get pods shows 1/2 of pods running confirming that kaniko container completed but istio
  side car is still running
* skaffold continues to wait and eventually prints out a fatal error message
  * (I forgot to copy the logs)
* Changing to a namespace with ISTIO side car injection disabled the build completes successfully

My conjecture is that Skaffold's kaniko code is assuming there is a single container running kaniko and thus fails in the presence of side cars like the ISTIO side car.

* It would be great if skaffold could be updated to support sidecars

   * Since kaniko is making network calls (e.g. to GCR) it seems reasonable to support running that with ISTIO to provide various security  controls

* It might also be nice if skaffold.yaml supported adding labels to the kaniko pod so the istio side
  car could be disabled on just the kaniko jobs

### Information

- Skaffold version: v1.1.0
- Contents of skaffold.yaml:

```yaml
 Reference: https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: label-microservice
build:
  artifacts:
  - image: gcr.io/issue-label-bot-dev/bot-worker
    # Set the context to the root directory. 
    # All paths in the Dockerfile should be relative to this one.
    context: ..
    kaniko:
      dockerfile: Label_Microservice/deployment/Dockerfile.worker
      buildContext:
        gcsBucket: issue-label-bot-dev_skaffold-kaniko
      env: 
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/user-gcp-sa.json
      cache: {}
  cluster:
    # pullSecret can be set to a local file from which the pull secret should be created.
    pullSecretName: user-gcp-sa
    # TODO(jlewi): This should be changed for each developer; or maybe we should create a reusable one?
    namespace: jlewi-dev
deploy:
  kustomize:
    path: deployment/overlays/dev
```

### Steps to reproduce the behavior

1. Setup a cluster with ISTIO
2. Try to run `skaffold build` using Kaniko in a namespace with ISTIO side car injection turned on
