### ISSUE TITLE
can not patch empty values

### ISSUE THREAD

**Issue by kvokka** [GoogleContainerTools/skaffold#3446]
if I leave the build section empty for further addition in the profiles with `patches`, like:

```yaml
apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts: []
deploy:
  helm:
    releases: []
```

and then apply any profile:

```yaml
profiles:
- name: pubsub_emulator
  patches:
  - op: add
    path: /build/artifacts/-
    value:
      image: us.gcr.io/replay-gaming/pubsub-emulator
      docker:
        dockerfile: support/skaffold/pubsub_emulator/Dockerfile
  - op: add
    path: /deploy/kubectl/manifests/-
    value: support/skaffold/pubsub_emulator/k8s.yaml
```

### Expected behavior

no error

### Actual behavior

I can not use patches

```bash
$ skaffold build -p api
FATA[0000] creating runner: applying profiles: applying profile api: invalid path: /build
```

### Information

- Skaffold version: version 1.1.0
- Operating system: MacOs 10.15.2

Connect #3277
