### ISSUE TITLE
Config parsing issue

### ISSUE THREAD

**Issue by forgo** [GoogleContainerTools/skaffold#3447]
### Expected behavior
Expect skaffold to run with a valid and simple `skaffold.yaml` Config

### Actual behavior
Error due to parsing/unmarshalling:
```
$ skaffold dev -f skaffold.yaml
FATA[0000] creating runner: parsing skaffold config: unable to parse config: yaml: unmarshal errors:
  line 17: cannot unmarshal !!seq into map[string]string
  line 24: cannot unmarshal !!seq into map[string]string
```

#### Versions
```
$ skaffold version
v1.1.0

$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

#### Operating System:
macOS Catalina 10.15.1

##### Contents of `skaffold.yaml`:
```yaml
apiVersion: skaffold/v2alpha1
kind: Config

build:
  artifacts:
  - image: forgo/forgo-client
    jib:
      project: client
  - image: forgo/forgo-user
    jib:
      project: user

deploy:
  helm:
    releases:
    - name: forgo-client
      chartPath: helm/forgo-client # --> line 17 in error
      values:
        image: forgo/forgo-client
      imageStrategy:
        helm: {}
      setValues: []
    - name: forgo-user
      chartPath: helm/forgo-user # --> line 24 in error
      values:
        image: forgo/forgo-user
      imageStrategy:
        helm: {}
      setValues: []
```

### Steps to reproduce the behavior

1. `skaffold dev -f skaffold.yaml`

I can't see anything wrong with my config at all. I've ran through YAML linters, and meticulously checked for formatting mistakes. For the most part this is set up the same as a previous project I was working on, with these exceptions:

1. I recently upgraded skaffold to 1.1.0
  - in so doing, I had to change `jibGradle` to simply `jib` in the build section.
2. I recently upgraded helm
