### ISSUE TITLE
User defined ports aren't forwarded

### ISSUE THREAD

**Issue by demisx** [GoogleContainerTools/skaffold#3449]
Hello. I have defined user port forwarding, but for some reason it looks like it's being completely ignored. None of those 3 ports get forwarded. If I do it with `kubectl port-forward` command then they are forwarded as expected. Can you please tell me what I am missing? 

### Information
- Skaffold version: 1.1.0
- Operating system: MacOs 10.15.2
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
deploy:
  kubeContext: docker-for-desktop
  kubectl:
    manifests:
      - tools/k8s/dev/db.k8s-config.yaml
      ...
build:
  local:
    useBuildkit: true
  artifacts:
    ...
portForward:
  - resourceType: service
    resourceName: elasticsearch-master
    port: 9200
  - resourceType: service
    resourceName: postgresql
    port: 5432
  - resourceType: service
    resourceName: api
    port: 3000
```

Skaffold started as:

```sh
skaffold dev -f skaffold.app.yaml -v=info --cache-artifacts=true
```
