### ISSUE TITLE
Building a base image artifact

### ISSUE THREAD

**Issue by KhaledSakr** [GoogleContainerTools/skaffold#3451]
I'm using skaffold to build and deploy multiple artifacts, but each of them are based on a base image that should be built and pushed first.

This is for example doable with docker-compose in the following way:
```yaml
services:
  base:
    build:
      context: ../base
    image: base
  users:
    build:
      context: ../users
```
And then the dockerfile for the `users` image:
```dockerfile
FROM base
...
```

This workflow is currently not supported in skaffold as far as I understand.

### Expected behavior
Should be able to build base artifacts and then pass the created tag to other artifacts.

### Actual behavior
Currently there's no way no pass the tags to other artifacts.

### Information

- Skaffold version: v1.1.0
- Operating system: Ubuntu 19.04
