### ISSUE TITLE
file sync not triggered after redeploy

### ISSUE THREAD

**Issue by jlewi** [GoogleContainerTools/skaffold#3454]
I believe I observed the following behavior.

1. Configured Skaffold to trigger file sync 

    * Here's my [skaffold.yaml](https://github.com/jlewi/code-intelligence/blob/multi_model/Label_Microservice/skaffold.yaml)

1. I started skaffold in dev mode

1. I modified my code
1. Skaffold triggered a file copy for the modified files
1. I modified my deployment 
1. Skaffold triggered an update of the deployment
    * However skaffold didn't retrigger the file sync so the files in my deployment were out of date. 

I believe I observed the above but I didn't try to specifically reproduce it and verify it.  

### Expected behavior

After an update to the deployment files should be resync'd so the filesystem in the deployment contains any changes since the image was built

### Actual behavior

File sync not triggered automatically after rebuild.

(I could work around this my modifying the file to retrigger)

### Information

- Skaffold version: v1.1.0
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
# Reference: https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: label-microservice
build:
  artifacts:
  - image: gcr.io/issue-label-bot-dev/bot-worker
    # Set the context to the root directory. 
    # All paths in the Dockerfile should be relative to this one.
    context: ..
    # Automatically sync python files to the container. This should avoid
    # the need to rebuild and redeploy when the files change.
    sync:
        infer:        
        - '**/*.py'
    kaniko:
      dockerfile: Label_Microservice/deployment/Dockerfile.worker
      buildContext:
        gcsBucket: issue-label-bot-dev_skaffold-kaniko
      env: 
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/user-gcp-sa.json
      cache: {}
  cluster:
    # pullSecret can be set to a local file from which the pull secret should be created.
    pullSecretName: user-gcp-sa
    # TODO(jlewi): This should be changed for each developer; or maybe we should create a reusable one?
    namespace: jlewi-dev
    resources:
      requests:
        cpu: 8
        memory: 16Gi

deploy:
  kustomize:
    path: deployment/overlays/dev
```

### Steps to reproduce the behavior

See above

1. a clonable repository with the sample skaffold project
https://github.com/jlewi/code-intelligence/blob/multi_model/Label_Microservice/skaffold.yaml
