### ISSUE TITLE
kaniko builds should work with GKE workload identity

### ISSUE THREAD

**Issue by jlewi** [GoogleContainerTools/skaffold#3468]
# Expected behavior

My expectation is that skaffold kaniko builds would work with GKE workload identity

### Actual behavior

skaffold kaniko pods end up setting the environment variable `GOOGLE_APPLICATION_CREDENTIALS`.

As a result, kaniko pods will not try to use workload identity but instead look for the GCP secret to be provided in the location specified by the secret.

### Information

- Skaffold version: v1.1.1
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: label-microservice
build:
  artifacts:
  - image: gcr.io/issue-label-bot-dev/bot-worker
    # Set the context to the root directory. 
    # All paths in the Dockerfile should be relative to this one.
    context: ..
    # Automatically sync python files to the container. This should avoid
    # the need to rebuild and redeploy when the files change.
    # TODO(https://github.com/GoogleContainerTools/skaffold/issues/3448): We use manual sync
    # because inferred sync doesn't work
    #
    # This only works if we autorestart the program on changes.
    sync:
        manual:
        - src: 'py/code_intelligence/*.py'
          dest: '/'
        - src: 'py/label_microservice/*.py'
          dest: '/'
    kaniko:
      dockerfile: Label_Microservice/deployment/Dockerfile.worker
      buildContext:
        gcsBucket: issue-label-bot-dev_skaffold-kaniko
      cache: {}
  cluster:    
    # TODO(jlewi): This should be changed for each developer; or maybe we should create a reusable one?
    namespace: kaniko
    resources:
      requests:
        cpu: 8
        memory: 16Gi

deploy:
  kustomize:
    path: deployment/overlays/dev
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...
