### ISSUE TITLE
Add label to specify debug tools container for debugging

### ISSUE THREAD

**Issue by panitaxx** [GoogleContainerTools/skaffold#3472]
I would like to submit a PR to be able to select a different image for the duct-tape (extra tools for debugging). Specifically in go if your image is built with alpine it does not work with skaffold debug.

### Expected behavior

Being able to specify my own debug tools init containers

### Actual behavior

Debug tools init containers are hard coded

### Information

I have thought some possible ways of doing this: 

1. via a flag. something like 

`skaffold debug --debug-tools-image='go=gcr.io/myownregistry/go-debug:xyz' 

Like this. It will affect all go images marked for debugging. 

2. via a label. 
```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: models
  template:
    metadata:
      labels:
        app: models
        debugTool: "gcr.io/myownregistry/go-debug:xyz"
    spec:
      containers:
      - name: models
        image: models
        command: ["/dbg/go/bin/dlv","debug","--headless","--api-version=2","--listen=:56268","--log"]
```

3. Just disable the automatically adding an init container witth a flag

`skaffold debug --no-init-container` 

In this case init-container is not added. User is responsible for creating the dbg volume, and adding an init container that contains the tools and that copies them into the dbg mountpoint.
