### ISSUE TITLE
custom-build-script-locally: ignores buildArgs

### ISSUE THREAD

**Issue by Andrei-Stepanov** [GoogleContainerTools/skaffold#3473]
skaffold version v1.1.0

Bug: **buildArgs** does nothing for **custom** build. Documentation has mention about it.

Let's take official example:

```
custom:
  buildCommand: ./build.sh
  dependencies:
    dockerfile:
      path: path/to/Dockerfile
      buildArgs:
        file: foo
```

As you can see you pass argument to build process: file == foo.
But, the argument **file** is not passed to **./build.sh**.

1. I checked ENV variables. No **file** in ENV variables.
2. I checked arguments to **./build.sh** command. No argument **file** in **./build.sh** command.

Reference:
https://skaffold.dev/docs/pipeline-stages/builders/custom/#custom-build-script-locally
https://skaffold.dev/docs/references/yaml/

P.S.

I am trying to do next:
I want to pass **Dockerfile** filename to **./build.sh**
Imagine that directory has a few Dockerfile's : Dockerfile.client Dockerfile.server
How do I pass Dockerfile name to **./build.sh** ?
