### ISSUE TITLE
Incorrect namespace selection

### ISSUE THREAD

**Issue by kvokka** [GoogleContainerTools/skaffold#3476]
### Expected behavior

Skaffold should treat all namespaces separately

### Actual behavior

When the service was already deployed to done namespace (call it `myns`), and I try to deploy the same service to another namespace, for example `myns2` it will be deployed again to `myns` instead of `myns2`. this makes impossible to deploy the 1 service to 2 different namespaces.

### Information

- Skaffold version: version 1.1.0
- Operating system: MacOS 10.15
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha1
kind: Config
profiles:
  - name: dependencies
    deploy:
      helm:
        releases:
          - name: memcached
            chartPath: stable/memcached
            remote: true
            valuesFiles:
              - support/skaffold/ondemand/memcached.yaml
```

UPD: Tried to add `namespace` option in skaffold.yaml file `profiles.0.deploy.helm.releases.0.namespace: myns2`. It gives the same bug, as described earlier

### Steps to reproduce the behavior

With this I execute
```bash
skaffold run -n myns -f skaffold.ondemand.yaml -p dependencies
skaffold run -n myns2 -f skaffold.ondemand.yaml -p dependencies
```

Having the service running only in `myns`.

In the output log I see:

```
Release "memcached" has been upgraded.
LAST DEPLOYED: Mon Jan  6 21:16:15 2020
NAMESPACE: myns
STATUS: DEPLOYED
```

Tried with Helm 2.16.1 && 3.0.2
Connect https://github.com/helm/helm/issues/2060

**Comment by kvokka** [comment]
Finally, killed a day i found the workaround for Helm2. Maybe it will be helpful for someone until this fix && Helm3 fix.

```yaml
# skaffold.yaml

apiVersion: skaffold/v2alpha1
kind: Config
profiles:
  - name: dependencies
    deploy:
      helm:
        releases:
          - name: redis-{{ .NS }}
            chartPath: stable/redis
            remote: true
            valuesFiles:
              - support/skaffold/redis.yaml
```


```bash
NS=myns && skaffold run -f skaffold.ondemand.yaml -p dependencies -n $NS
```
