### ISSUE TITLE
How can I build two images in one build artifact?

### ISSUE THREAD

**Issue by wwtg99** [GoogleContainerTools/skaffold#3485]
### Expected behavior

How can I build two images in one build artifact?
Now I just write two artifacts in build section like below. But it will build twice even if the images are same. How can I build the second image like docker tag?

```yaml
build:
  artifacts:
    - image: first
      custom:
        buildCommand: sh build.sh
        dependencies:
          paths:
            - .
    - image: second
      custom:
        buildCommand: sh build.sh
        dependencies:
          paths:
            - .
```
