### ISSUE TITLE
Clean up from remote repositories as well after skaffold-dev

### ISSUE THREAD

**Issue by tvvignesh** [GoogleContainerTools/skaffold#3487]
Hi. I have been using a remote GKE cluster as my development target since its difficult to run Minikube and test everything on my system. Everything works great with `skaffold dev` pushing images remotely during development and I am able to test it.

But, when terminating `skaffold dev` I would like the remote GCR images which were pushed to be cleaned up as well to avoid doing it manually later. Too many tags are getting pushed to GCR because of this.

Rather, all tags can be stored in the remote registry permanently only when running `skaffold run` but cleaned up when using `skaffold dev`

Is there any other way to avoid issues like these? Thanks. I hope the GCloud bill doesn't shoot up because of this.

**Comment by tejal29** [comment]
@tvvignesh `skaffold dev` cleanups all intermediate images locally. However, remote images and layers are not cleaned up.
This could be definitely added this as feature.

Our team also owns Minikube, and i would love to know why your Minikube isn't working for you.
Is it because of the nature of your application or minikube installation is difficult.

Thanks
Tejal

**Comment by tvvignesh** [comment]
@tejal29 Thanks for your quick reply. The main reason minikube does not work is that it eats up a lot of resource in my system along with other applications I am running. Also the fact that you have to end up exposing many of your local ports in the cluster through a tunnel if you are working on things like OAuth where services need a public url to be exposed.

Otherwise, its good to work with minikube.

**Comment by balopat** [comment]
FYI, the current [pricing of GCR](https://cloud.google.com/container-registry/pricing) tells me that $0.026 per GB per month is the price. So, regarding the bills it depends how big your images are and how frequently you are pushing. 

I agree with @tejal29  that this could be added as a feature. It is a relatively sizable (medium to large) one to implement though, as the cleanup logic for registries is very different from cleaning up locally. I don't think we'll have the bandwidth for this anytime soon. Community contributions are always welcome. :) This one should definitely start with a design doc first! 

In the meantime I would recommend separating out your production (`skaffold run`) and dev (`skaffold dev`) flows to two separate projects (hence GCR registries) or to two separate image names at least (with profiles maybe?) and setup a GCP Cloud Scheduler task to run a cleanup script daily on the dev project / images. 

What do you think?

**Comment by tvvignesh** [comment]
@balopat Thanks for your reply. I had the pricing concern since I was using `skaffold dev` which periodically hotreloads and pushes new images to the repo (not sure if that is in my control).

What I did to solve this issue right now, is to use skaffold for my CI/CD pipelines and to use telepresence for my dev workflows and that works great. Like, I swap the container which I am developing and do all changes and keep iterating (there is no image pushed to remote). And once the development is done, I commit it to the repo (which is GITLAB in my case) and the GITLAB CI takes care of the pipeline using skaffold.

My skaffold file looks something like this (removed sensitive details):

```
apiVersion: skaffold/v1
kind: Config
build:
    artifacts:
        - image: asia.gcr.io/project-dev/repo-name
deploy:
    kubeContext: cluster-dev
    kubectl:
        manifests:
            - kubernetes/dev/svc/*.yml
profiles:
    - name: dev-svc
      build:
          artifacts:
              - image: asia.gcr.io/project-dev/repo-name
      deploy:
          kubeContext: cluster-dev
          kubectl:
              manifests:
                  - kubernetes/dev/svc/*.yml
    - name: dev-db
      build:
          tagPolicy:
              envTemplate:
                  template: "{{.IMAGE_NAME}}:latest"
          artifacts:
              - image: asia.gcr.io/project-dev/postgres
                context: kubernetes/dev/db/
      deploy:
          kubeContext: cluster-dev
          kubectl:
              manifests:
                  - kubernetes/dev/db/*.yml
    - name: prod-svc
      build:
          artifacts:
              - image: asia.gcr.io/project-prod/repo-name
      deploy:
          kubeContext: cluster-prod
          kubectl:
              manifests:
                  - kubernetes/prod/svc/*.yml
    - name: prod-db
      build:
          artifacts:
              - image: asia.gcr.io/project-prod/postgres
                context: kubernetes/prod/db/
      deploy:
          kubeContext: cluster-prod
          kubectl:
              manifests:
                  - kubernetes/prod/db/*.yml
```
