### ISSUE TITLE
Skaffold dev will disconnect after few hours every time

### ISSUE THREAD

**Issue by thatguyjono94** [GoogleContainerTools/skaffold#3529]
### Expected behaviour
Skaffold only exits when instructed in dev mode
### Actual behaviour
After running `skaffold dev` and a few hours later I get the following error:

`deployer cleanup: reading manifests: kubectl create: Running [kubectl --context minikube create --dry-run -oyaml -f /Users/jonathan/projects/kludge/k8-dev/client/deployment-manifest.yaml -f /Users/jonathan/projects/kludge/k8-dev/api/deployment-manifest.yaml -f /Users/jonathan/projects/kludge/k8-dev/client/service-manifest.yaml -f /Users/jonathan/projects/kludge/k8-dev/api/service-manifest.yaml]`

`- stdout: - stderr: Unable to connect to the server: dial tcp 192.168.99.125:8443: connect: operation timed out: exit status 1`

### Information

- Skaffold version: v1.1.0
- Operating system: macOS Catalina 10.15.2
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: jonathang1994/kludge-client
      context: client
      sync:
        manual:
          - src: 'pages/*.js'
            dest: '/usr/src/app'
          - src: 'components/*.js'
            dest: '/usr/src/app'
          - src: 'reducers/*.js'
            dest: '/usr/src/app'
          - src: 'actions/*.js'
            dest: '/usr/src/app'
          - src: 'helpers/*.js'
            dest: '/usr/src/app'
          - src: 'hoc/*.js'
            dest: '/usr/src/app'  
      docker:
        dockerfile: Dockerfile
    - image: jonathang1994/kludge-api
      context: api
      sync:
        manual:
          - src: 'resources/views/*.php'
            dest: '/var/www/api'
          - src: 'app/Models/*.php'
            dest: '/var/www/api'
          - src: 'app/Http/Controllers/*.php'
            dest: '/var/www/api'
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8-dev/client/deployment-manifest.yaml
      - k8-dev/api/deployment-manifest.yaml
      - k8-dev/client/service-manifest.yaml
      - k8-dev/api/service-manifest.yaml
     
```

### Steps to reproduce the behaviour

Running `skaffold dev` and after a few hours of development or inactivity (like when my lap top goes in sleep mode for example), I get the `Unable to connect to the server: dial tcp 192.168.99.125:8443: connect: operation timed out: exit status 1` error.

I'm using docker for desktop on Mac, and I am running a Minikube cluster. 

Any ideas on why my connection keeps disconnecting? Thanks
