### ISSUE TITLE
Specifying the deployment order or dictating order

### ISSUE THREAD

**Issue by eox-dev** [GoogleContainerTools/skaffold#3541]
I'm just trying to find out if there is a way to dictate the order deployments are started up.

Basically, I need the database deployment to spin up before the API deployment. If the database isn't running, it throws an error in the API. 

I've messed with the order in:
```
artifacts:
  - image:
```
and also in:
```
deploy:
  kubectl:
    manifests:
      - manifests/ingress.yaml 
      - manifests/postgres.yaml      
      - manifests/client.yaml
      - manifests/api.yaml
```

But it doesn't seem to have any bearing on the order they startup.

The only thing I can think is that it is alphabetical. I used to not have an issue: the database would startup 49/50 before the api. Now it is about the opposite. The only thing I've changed is a new computer and  I renamed the `server` to `api` which puts it first alphabetically. 

So two questions:

1. How is the deployment order determined in Skaffold?
2. Is there a way to set the order such that one deployment does not start before another?
