### ISSUE TITLE
exec: "container-structure-test": executable file not found in $PATH

### ISSUE THREAD

**Issue by dalvizu** [GoogleContainerTools/skaffold#3543]
I'm trying to use container testing and am running into immediate error saying container-structure-test is not found on my PATH. I'm specifying `image` of `zemanlx/container-structure-test` which is a public image containing the `container-structure-test` binary at `/bin/container-structure-test` and on the $PATH of that container.

What's not clear to me from examples is what is needed of this container. It seems straightforward: some image with this on its PATH, but in all the examples this image is the same image as the image under test.

Only thing unique about my environment vs what's described in docs is i'm using `docker-desktop` as i'm using docker for mac and not minikube.

### Expected behavior
* Run skaffold build and see testing runs

### Actual behavior
Skaffold command errors saying container-structure-test is not found in the $PATH
```
FATA[0000] test failed: running structure tests: running container-structure-test: exec: "container-structure-test": executable file not found in $PATH
```
### Information

- Skaffold version: 1.2.0
- Operating system: OS X 10.14.6 Mojave
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: skaffold-issue
build:
  artifacts:
  - image: dalvizu/skaffold-issue
test:
  - image: zemanlx/container-structure-test:v1.8.0-alpine
    structureTests:
      - './structure-tests/*'
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
    - deployment.yml
```

### Steps to reproduce the behavior

Project with behavior:
https://github.com/dalvizu/skaffold-issue

1. `git clone git@github.com:dalvizu/skaffold-issue`
2. `skaffold build`
3. Behold, and despair
