### ISSUE TITLE
FR: Add .IMAGE_TAG template variable

### ISSUE THREAD

**Issue by InsOpDe** [GoogleContainerTools/skaffold#3549]
### Expected behavior
There should be a way to retrieve the `image-tag` somehow in order to correctly insert it into the `skaffold.yaml`

According to https://skaffold.dev/docs/environment/templating/ `{{.IMAGE_NAME}}` is usable but not `{{.IMAGE_TAG}}`

### Actual behavior
Kubernetes reports the Error `Back-off pulling image "example.azurecr.io/example/cloud/social/rating"`
Clearly here's missing the image-tag. 

### Information

- Skaffold version: v1.2.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: example-social-cloud-rating-service
build:
  artifacts:
  - image: example.azurecr.io/example/cloud/social/rating
    jib: {}
  local: {}
deploy:
  helm:
    flags:
      upgrade: ["-i"]
    releases:
    - name: example-social-cloud-rating-service
      chartPath: helm
      namespace: example-socialcloud-dev
      setValueTemplates:
        "web.image": example.azurecr.io/example/cloud/social/rating
        "web.imageTag": "{{ .IMAGE_TAG }}"
        "web.name": example-social-cloud-rating-service
        "web.host": rating.social.cloud.example.com
```

With the `deployment.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.web.name }}
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ .Values.web.name }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.web.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.web.name }}
        spec:
            containers:
                -
                    image: "{{ .Values.web.image }}"
                    imagePullPolicy: Always
                    name: {{ .Values.web.name }}
                    ports:
                        -
                            containerPort: 8080
                    livenessProbe:
                        httpGet:
                            path: /healthz/ready
                            port: 8080
                    readinessProbe:
                        httpGet:
                            path: /healthz/ready
                            port: 8080

```

**Comment by InsOpDe** [comment]
I believe this might be related to https://github.com/GoogleContainerTools/skaffold/issues/3497

**Comment by kylewolfe** [comment]
I opened #3343 for this reason as well.

**Comment by dkirrane** [comment]
+1 it looks like there is no way to get the image tag from the tagPolicy to use later in helm.

```
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05.999_MST"
      timezone: "Local"
```

There is no way to get the image and tag and pass it to helm
```
  helm:
    releases:
    - name: my-app
      chartPath: ./helm
      skipBuildDependencies: true
      setValueTemplates:
        image.repository: '{{.IMAGE_NAME}}'
        image.tag: '{{.IMAGE_TAG}}'
```
