### ISSUE TITLE
deploy profile without build artifacts failing with "no tag provided for image"

### ISSUE THREAD

**Issue by f84anton** [GoogleContainerTools/skaffold#3559]
### Expected behavior
Able to deploy 3rd party software with dedicated profile
`skaffold deploy -p stg-infra`

### Actual behavior
Skaffold asking to set image artifact from top level build section
```
# skaffold deploy -p stg-infra
You either need to:
run [skaffold deploy] with [--images TAG] for each pre-built artifact
or [skaffold run] instead, to let Skaffold build, tag and deploy artifacts.
FATA[0000] no tag provided for image [myreponame] 
```

### Information

- Skaffold version: version 1.2.0, 0.40
- Operating system: ubuntu 18.04
- Contents of skaffold.yaml:

```
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: myreponame
      context: ../.
      docker:
        dockerfile: ./Dockerfile
        noCache: true
  tagPolicy:
    gitCommit:
      variant: CommitSha
  local:
    push: true
deploy:
profiles:
  - name: stg-infra
    deploy:
      helm:
        releases:
          - name: redis-stg
            chartPath: stable/redis
            version: 8.0.17
            remote: true
            namespace: infra-stg
            setValues:
              image.pullPolicy: IfNotPresent
            wait: true
        flags:
          install:
            - --atomic
          upgrade:
            - --atomic
```

### Steps to reproduce the behavior

1. skaffold.yaml 
2. `skaffold deploy -p stg-infra`

I can deploy stg-infra profile if top level build section is empty.
I tried to set an empty build section in the stg-infra profile without success.
Also have no issues with this configuration on v0.37.1.

**Comment by balopat** [comment]
Hi @f84anton, I can see how this is unintuitive. 

We should figure out how to "remove all artifacts" from a profile - I'm surprised it was working at one point. 

In the meantime as a work around, you should be able to run it with `--images= myreponame:dummytag`. Does that work for you as a workaround?

**Comment by f84anton** [comment]
Thank you. I have tried to set images for stable/redis but not `myreponame`. I can now run deploy with `--images=myreponame:nonexistingtag` for profile stg-infra.

```
# skaffold deploy -p stg-infra --images=myreponame:dymmytag
Tags used in deployment:
 - myreponame -> myreponame:dymmytag
Starting deploy...
```

**Comment by shantanugadgil** [comment]
The above workaround doesn't work for me as I have `default-repo` set in the global config.
So the `AWS ECR + imagename + tag` is my complete "image name".

The cmdline I wish would work is like below:

```bash
skaffold deploy --namespace $NAMESPACE --profile my_app --images=xxxxx.dkr.ecr.myregion.amazonaws.com/my_app:working-master
```

The docker image `xxxxx.dkr.ecr.myregion.amazonaws.com/my_app:working-master` has been built and pushed to ECR in a separate "skaffold build" step, probably from a a different machine altogether.

**Comment by nkubala** [comment]
@shantanugadgil spot on, you're running into the issue in #3765 and it is a real issue, but a different one than this.

I'm gonna lower the priority for this one since there's a workaround.

**Comment by yolkov** [comment]
>I'm gonna lower the priority for this one since there's a workaround.
On the contrary, I would increase the priority, because we have to change our pipeline everywhere to specify the desired image. Without this bug, all pipelines will be universal skaffold deploy-p profilename. And because of the bug, we have to add -t myrepo/serviceA:fake for each service etc.
This is very inconvenient, breaks the flexibility.

**Comment by AmetPreply** [comment]
I also started to migrate our old 0.30 skaffold to the 1.12.0, everything works fine except this with images addition. Thank you for prioritizing.

**Comment by shantanugadgil** [comment]
In my opinion using Skaffold in the CICD pipeline was a mistake (hindsight 20/20).

One has to dance around Skaffold's config and missing cmd line paramater parsing capabilities waaay too much.

Using the `docker build`, `docker tag` commands get things done waaay quicker.

It seems (I could be wrong), that the `run` and `dev` seems to be the most used options, hence the other options don't get so much TLC.

Also, in hindsight, switching from `docker-compose` might have been an error, considering docker-compose now has "context" support and capability to talk to k8s

**Comment by tejal29** [comment]
Keeping the priority same as this added to our next milestone.

**Comment by Avi612** [comment]
I have updated skafflod version v1.20.0 to use skaffold deploy -p dev --image=sample-app-python

```
skaffold deploy  --images=samp-app-python  doesn't overwrite the image
 You either need to:
run [skaffold deploy] with [--images TAG] for each pre-built artifact
or [skaffold run] instead, to let Skaffold build, tag and deploy artifacts
```

should also be able to overwrite images even if overlays/deployment.yaml  is defined
This is very inconvenient, breaks the flexibility to overwrite the image and deploy image on different env's in CI/CD pipeline.

**Comment by Avi612** [comment]
We have been tracking this issue because we have similar use case and I have tested the following with Skaffold version v1.20.0 
Skaffold deploy -p dev --image=**image2**
 
we still get the same error:
```
`Skaffold deploy  --images=**image2**  doesn't overwrite the image`
 You either need to:
run [skaffold deploy] with [--images TAG] for each pre-built artifact
or [skaffold run] instead, to let Skaffold build, tag and deploy artifacts
```
 
**Expectations:**
It should overwrite  the images provided in skaffold.yaml with the image provided in  --images over the command line
 
On top of the above scenario we have following use case
we are using  Skaffold and kustomize for our deployments,currently we are unable to overwrite the image in **k8s/overlays/deployment.yaml** through **skaffold deploy --images=**image2**** command,looks like there is disconnect between Skaffold and kustomize functionality.we are looking for resolution if  skaffold can  overwrites existing image(**image1**) in skaffold.yaml,kustomization.yaml,deployment.yaml through skaffold deploy command line.
 
**skaffold deploy --images=**image2****
kustomize have overlay with **image1**,  --- skaffold have to overwrite the image1 with **image2**.
 

eg: Under k8s/overlays/deployment.yaml file image1 is specified.
skaffold deploy -p dev --images=**image2** --namespace-test-dev for deployment it has to take **image2**.

**Comment by tejal29** [comment]
@Avi612 please use
1) `skaffold build --output output.json`
2) `skaffold deploy -a output.json`

**Comment by wind57** [comment]
@tejal29 you sure about `--output`? isn't it `--file-output`?

**Comment by aaron-prindle** [comment]
@Avi612 were you able to attempt the suggestion by @tejal29?
```
skaffold build --file-output output.json
skaffold deploy -a output.json
```

I believe this should help for your use case

**Comment by mbeldman** [comment]
> > @Avi612 were you able to attempt the suggestion by @tejal29?
> > ```
> > skaffold build --file-output output.json
> > skaffold deploy -a output.json
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I believe this should help for your use case
> 
> I'm finding I get the same error, i.e. console output (with redacted image name):
> 
> ```
> + skaffold verify
> You either need to:
> run [skaffold deploy] with [--images TAG] for each pre-built artifact
> or [skaffold run] instead, to let Skaffold build, tag and deploy artifacts.
> no tag provided for image [xxxx/xxxxx] 
> ```
> 
> at the `skaffold apply` step, even though the -a flag was used on `skaffold render` preceeding `skaffold apply` and an image tag is named in the hydrated manifest consumed by `skaffold apply`, it still gives the error above.
> 
> e.g. order of operations:
> 
> ```
> #Build and push image
> skaffold build --file-output build-output.json
> 
> # Hydrate Kubernetes manifest
> skaffold render -a build-output.json --output rendered.yaml
> 
> # Deploy using hydrated manifest
> skaffold apply  rendered.yaml  --kubeconfig="/path/to/config.yaml"
> 
> #Verification Tests
> skaffold verify
> ```
> 
> Thoughts?

Ah - ignore this... have realized I can pass in the -a flag with the json file at the `skaffold verify` command.

**Comment by ericzzzzzzz** [comment]
this was opened for v0, and this issue should be fixed in v2 or has an workaround. Closing this issue, please feel free to re-open if this happens on skaffold v2.

**Comment by annepavan** [comment]
@ericzzzzzzz the issue mentioned by @Avi612 is still happening with version v2.7.1. Our goal is the same, skaffold should able overwrite the image1 that is present in deployment.yaml with image2 that is passed down via command line. 
`skaffold deploy  --image=image2`
I have tried what @aaron-prindle suggested, but no luck. I still see image1 is been used by deployment. 

```
/opt/app/tools/skaffold-v2.7.1/skaffold build --output build-output.json

build-output.json:
{"builds":[{"imageName":"registry/test-docker/**skaffold-kustomize-image2"**,"tag":"registry/test-docker/skaffold-kustomize-image2:0.0.1@sha256:9e0bc1c3447d34ac0bef210d107
21efc45eef570885e49195600c61863715dc7"}]}

 /opt/app/tools/skaffold-v2.7.1/skaffold render -a build-output.json --output rendered.yaml

rendered.yaml:
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skaffold-kustomize
    env: dev
  name: skaffold-kustomize
spec:
  selector:
    matchLabels:
      app: skaffold-kustomize
  template:
    metadata:
      labels:
        app: skaffold-kustomize
    spec:
      containers:
        - image: registry/test-docker/**skaffold-kustomize-image1**
          name: skaffold-kustomize
```

ability to overwrite the image via skaffold is very helpful and simply the process of maintaining the image patch section in kustomization.yaml. Appreciate if you can re-open this issue. 

Please feel free to let me know if you need to further information on this issue. I will be happy to hop to a quick working session as well.
