### ISSUE TITLE
Skaffold keeps rebuilding and redeploying a helm chart with dependencies 

### ISSUE THREAD

**Issue by petarManolov** [GoogleContainerTools/skaffold#3565]
### Expected behavior
After running ```skaffold dev``` and the initial build and deployment is done, it will only trigger a new build / deploy when I make a change to the source or helm charts.
### Actual behavior
After the initial build, the chart is continuously re-deployed in a loop.
### Information

- Skaffold version: v1.2.0
- Operating system: Ubuntu 19.10 / macOS 10.15
- Project Info : Java based project build with maven
- Possible regressions: [issues-931](https://github.com/GoogleContainerTools/skaffold/issues/931) and/or [issues-667](https://github.com/GoogleContainerTools/skaffold/issues/667)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: dps
      context: .
      docker:
        dockerfile: Dockerfile
  local:
    useDockerCLI: true
deploy:
  helm:
    releases:
      - name: dps
        chartPath: helm/dps
        namespace: sandbox-dataplatform
        setValueTemplates:
          val1: "{{ .ENV_VAL_1 }}"
          val2: "{{ .ENV_VAL_2 }}"
        values:
           container.image: dps
```
- Project Structure  
```yaml
.circleci
checkstyle
db
helm
  dps
    values.yml
    ....
src
  main
  test
pom.xml
Dockerfile
entrypoint.sh
pom.xml
skaffold.yaml
```
- Docker File 
```
FROM openjdk:11.0-jre

LABEL maintainer="petar.manolov@email.com"
LABEL maintainer_team='my_team@email.com'

ARG APP_LOCATION=/usr/local/myapp

ADD ./target/myapp.jar $APP_LOCATION/myapp.jar
ADD ./entrypoint.sh $APP_LOCATION/entrypoint.sh
RUN chmod u+x $APP_LOCATION/entrypoint.sh

EXPOSE 80/tcp

ENTRYPOINT ["/usr/local/myapp/entrypoint.sh"]


```

### Steps to reproduce the behavior
1. `skaffold dev --trigger notify`
