### ISSUE TITLE
Using private image repositories requires modifying the skaffold pipeline yaml

### ISSUE THREAD

**Issue by afrittoli** [GoogleContainerTools/skaffold#361]
This is more a feature request than a bug.
Since I use a private docker image registry, with namespaces and every developer uses their own namespace for development purposes, my skaffold file is actually a template (skaffold.yaml.tpl):

```
apiVersion: skaffold/v1alpha1
kind: Config
build:
  tagPolicy: sha256
  artifacts:
  - imageName: __IMAGE_REG__/my-image
    workspace: .
  local: {}
deploy:
  helm:
    releases:
    - name: dev
       chartPath: my-chart
       namespace: default
       valuesFilePath: skaffold/helm-values.yaml
       values:
         image: __IMAGE_REG__/my-image
```

And then I use a make target to produce the actual yaml file:

```
test-helm: ## Deploy via Helm to a test cluster
	@rm skaffold/helm.yaml || true
	@sed -e 's,__IMAGE_REG__,'$(IMAGE_REG)/$(IMAGE_REG_NS)',g' skaffold/helm.yaml.tpl > skaffold/helm.yaml
	skaffold run -f skaffold/helm.yaml -v debug
```

### Expected behavior

This is just an example of how a pipeline configuration could look like:

```
deploy:
  helm:
    releases:
    - name: dev
       chartPath: mychart
       namespace: default
       registry_ns: my_private_registry/my_namespace
       values:
          image: my_image:tag
```

### Actual behavior

This is just an example of my pipeline configuration looks like today:

```
deploy:
  helm:
    releases:
    - name: dev
       chartPath: mychart
       namespace: default
       registry_ns: my_private_registry/my_namespace
       values:
          image: my_image:tag
```

### Information

```
Skaffold version: v0.2.0 (built from source 10dd ago)
Operating system: macOS
Content of skaffold.yaml: see above
```

**Comment by r2d4** [comment]
Thanks for another descriptive issue. This is something we need to figure out soon. There are values that are going to differ within a developer's team and within a developer's organization. 

1. We definitely don't want users to have to template their own skaffold.yaml and add that kind of complexity. 
2. We also don't want skaffold.yaml to have environment variables and therefore be un-parsable YAML.

So how do we craft these skaffold.yamls so that they can be reused? 

1. runtime flags to skaffold run/dev
2. skaffold.yaml overlays, much like the work being done on kinflate. Developer maintains their own overlays that automatically get applied. Something like `skaffold run -f skaffold.yaml my-skaffold.yaml`
3. User overrides file `.skaffoldrc`.
4. `kubectl config use-context --namespace` to set default namespace for kubectl client. Doesn't cover the other methods of deploying.

Just a few early ideas here. I'd love to start a discussion on this, since I think its very important.

**Comment by r2d4** [comment]
cc @dgageot @dlorenc

**Comment by afrittoli** [comment]
Thanks for the quick reply on this.
I agree that skaffold.yaml should stay a plain parsable YAML. 

I like ideas (1) (2) and (3), with the caveat that skaffold.yaml should be structured so that development specific settings can be isolated. For instance, for (3) it can be handy to configure in .skaffoldrc my image registry namespace, but that's useful only as long as it can be mapped to a specific value in skaffold.yaml. Using the image repo, ns, name all in one like today would not work.

**Comment by afrittoli** [comment]
Thanks @jstrachan that looks interesting. 

Since that is defined globally in the build section, how would that work with multiple images? 
Also I'm using the helm deployer, which allows me to pass a values file to helm, but that means that I have to template the values file in a similar way to what I'm templating skaffold.yaml today.

Runtime flags in skaffold and/or user overrides + overlays like proposed by @r2d4 would help, so everyone could keep their MY_REGISTRY / MY_USER in a values file in their home, and what would be discovered by skaffold and used as a basis to build the final values file passed to helm.

**Comment by jstrachan** [comment]
The `envTemplate` avoids having to do the templating for the registry URL of the `skaffold.yaml` file; if you want you could template the user + image name too via env vars if you like?

Agreed that we'd need a way to get the helm skaffold deployer able to pass in environment variables on the CLI too. We maybe need a way to specify those...

```yaml
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: skaffold-helm
      namespace: skaffold
      values:
        image: skaffold-helm
      setValuesTemplates:
        image: "{{.MY_REGISTRY}}/{{.MY_USER}}/something
```

Note that `setValuesTemplates` is not yet supported but would a way to pass env vars into both the image string and into the chart

**Comment by afrittoli** [comment]
Something like this works for me know, and it saves me templating the skaffold configuration, which is great:

```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: my-image
    docker:
      dockerfilePath: image1/Dockerfile
  - imageName: my-other-image
    docker:
      dockerfilePath: image2/Dockerfile
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_REG}}/{{.IMAGE_REG_NS}}/{{.IMAGE_NAME}}:{{.DIGEST}}"
deploy:
  helm:
    releases:
    - name: development
      chartPath: my-chart
      valuesFilePath: skaffold/helm-values.yaml
      values:
        image1: my-image
        image2: my-other-image
      namespace: default
```

However I still have two issues:
- helm-values includes secrets which I would like to pass via CLI interactively or pull from an environment variable as opposed to store in a file.
- the helm release name is fixed, which is fine when deploying to a mini kube. When used in CI and deploying against a test cluster though limits this to one CI job at the time.
