### ISSUE TITLE
Shouldn't default-repo be applied to cacheFrom directives?

### ISSUE THREAD

**Issue by lucasmpr** [GoogleContainerTools/skaffold#3610]
I'm trying very hard to optimize my DotNet multi-stage build process. 

To do that I'm creating three profiles that I must execute in sequence.

Profile 1 - Base images
Profile 2 - Dependency Builder
Profile 3 - Final builder

The idea is to use caching and don't rebuild the whole system every time, and build in parallel things that are not dependent on others.

For each step, I want to use a previous image in cache or the image build in the latest profile.  So was trying to use cacheFrom when I stumbled into that. 

I use the --default-repo to set the image according to the branch, in runtime, and I expected the cache image to be pulled from my default repo, but It doesn't seem.

Additional 
========
+ I would like to be able to use templating in the cacheFrom directive, so I can use the previous image and not necessarly the one tagged as latest.

### Expected behavior

If default-repo is specified, cacheFrom images without full path should be rewriten if not fully qualified.

### Actual behavior

Skaffold says the image could not be found.

### Information

- Skaffold version: 1.2.0
- Operating system: Windows
- Contents of skaffold.yaml:

```yaml
profile:
- name: restore-stage
  build:
    local: 
      useBuildkit: false
    artifacts:
    - image: restore
      context: .
      docker:
        dockerfile: Dockerfile.default
        cacheFrom:
        - restore:latest
        target: pre_publish

```

**Comment by tejal29** [comment]
@lucasmpr, thank you filing this issue.

IIUC, `restore:latest` is one of the images built by skaffold in another profile?
You used the `--default-repo` flag when building `restore:latest` in previous `skaffold build` command.
e.g.
`skaffold build --default-repo=gcr.io/test -p build-restore`
The built image was `gcr.tio/test/restore:latest`

Now you want to use the built image as `cacheFrom` value?
Is that correct?

That would mean, skaffold have to see if images in `docker.cacheFrom` list is one of the build artifacts. Currently skaffold does not evaluate all possible artifacts (based on non active profiles).
Is it possible for you to share share entire your `skaffold.yaml` or other profiles?

**Comment by lucasmpr** [comment]
Hello tejal, let me explain a little bit more what I'm trying to do.

a) I have one big repo with multiple services. I have a global dockerfile that does the following:
   1) Builds the base image (base)
   2) Builds the remote dependencies image (restore) (it is the same for all images)
   3) Copy the local dependencies, if any of them have changed (dependency_builder)
   4) Builds the project

What I'm doing is a workaround for the "Dependent images" from  #889 
I want to build the base image without concurrency and fetch the remote dependencies after.

Then I want to build all the projects in parallel. 

So the idea is the following. I'm running skaffold 3 times.

1) Calls skaffold to Build base:latest image and restore:latest image and also use base:latest and restore:latest as cache.
(If the image is the same, nothing is built and the image doesnt' change)
2) Build the cache stage, for each project build an image called ${project}-cache:latest with the ${project}-cache:latest  (so if one of the projects is cached and didn't changed, nothing is done)
3) Builds the final stage and pushs it


``` yaml
piVersion: skaffold/v2alpha2
kind: Config
build:
  local: 
    useBuildkit: false
    concurrency:  0
  artifacts:
  - image: project1
    context: .
    docker:
      dockerfile: Dockerfile.default
      buildArgs:
        PROJECT: Project1
      cacheFrom:
      - default-repo/base:latest
      - default-repo/restore:latest
      - default-repo/project1-cache:latest
  - image: Project2
    context: .
    docker:
      dockerfile: Dockerfile.default
      buildArgs:
        PROJECT: Project2
      cacheFrom:
      - default/repo/base:latest
      - default-repo/restore:latest
      - default-repo/project2-cache:latest
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha    
profiles:
- name: restore-stage
  build:
    local: 
      useBuildkit: false
      concurrency: 0
    artifacts:
    - image: restore
      context: .
      docker:
        dockerfile: Dockerfile.default
        cacheFrom:
        - default-repo/restore:latest
        target: pre_publish
        buildArgs:
          BUILDKIT_INLINE_CACHE: 1
    - image: base
      context: .
      docker:
        dockerfile: Dockerfile.default
        cacheFrom:
        - gcr.io/livance-project/dev/build-speed/base:latest
        target: base
        buildArgs:
          BUILDKIT_INLINE_CACHE: 1

- name: cache-stage
  build:
    local: 
      useBuildkit: false
      concurrency:  0
    artifacts:
    - image: Project1
      context: .
      docker:
        dockerfile: Dockerfile.default
        target: dependency_builder
        buildArgs:
          PROJECT: 'Project1'
        cacheFrom:
        - default-repo/base:latest
        - default-repo/restore:latest
        - default-repo/web-cache:latest
    - image: Project2
      context: .
      docker:
        dockerfile: Dockerfile.default
        target: dependency_builder
        buildArgs:
          PROJECT: 'Project2'
        cacheFrom:
        - default-repo/base:latest
        - default-repo/restore:latest
        - default-repo/api-cache:latest
```

I'm running it on google cloud with the following command:
