### ISSUE TITLE
skaffold dev - deployment fails, but no events

### ISSUE THREAD

**Issue by bukowa** [GoogleContainerTools/skaffold#3621]
### Expected behavior
I can see following message after "skaffold dev"
````bash
0/3 nodes are available: 3 node(s) didn't find available persistent volumes to bind.
````
### Actual behavior
````bash
 - serviceaccount/commander-svc configured
 - role.rbac.authorization.k8s.io/commander-role configured
 - rolebinding.rbac.authorization.k8s.io/commander-role-binding configured
 - storageclass.storage.k8s.io/local-storage configured
 - persistentvolumeclaim/supplier-pvc configured
 - secret/x configured
 - deployment.apps/redis configured
Watching for changes...
````
### Information

- Skaffold version: v1.3.0
- Operating system: Windows 10
- Contents of skaffold.yaml:
````yaml
apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: myname
build:
  artifacts:
  - image: x/a
    context: commander
  - image: x/b
    context: supplier
deploy:
  kubectl:
    manifests:
    - deployment.yaml
````
### Steps to reproduce the behavior
````yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commander-svc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: commander-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: commander-role-binding
subjects:
  - kind: ServiceAccount
    name: commander-svc
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: commander-role
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supplier-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      serviceAccountName: commander-svc

      volumes:
        - name: supplier-pvc
          persistentVolumeClaim:
            claimName: supplier-pvc

      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379

        - name: supplier
          image: x/b
          envFrom:
            - secretRef:
                name: mysecret
          volumeMounts:
            - mountPath: /supplier/supplies
              name: supplier-pvc
              subPath: supplier/supplies

        - name: commander
          image: x/a
          envFrom:
            - secretRef:
                name: mysecret
          volumeMounts:
            - mountPath: /supplier/supplies
              name: supplier-pvc
              subPath: supplier/supplies
          env:
            - name: NAMESPACE
              value: "default"
````
2. `skaffold dev`
