### ISSUE TITLE
Cannot Prune Image, Being Used by Running Container

### ISSUE THREAD

**Issue by ToucanBran** [GoogleContainerTools/skaffold#3624]
### Expected behavior
Exiting out of skaffold dev with --no-prune=false --cache-artifacts=false options set should prune images

### Actual behavior
Received a warning message: 
```
Cleaning up...
 - deployment.apps "psat-deployment" deleted
Pruning images...
time="2020-01-31T08:10:05-08:00" level=warning msg="builder cleanup: pruning images: Error response from daemon: conflict: unable to delete 124b637fbfc0 (cannot be forced) - image is being used by running container 65234d99ad2d"
```
### Information

- Skaffold version: 1.3
- Operating system: Windows 10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts: 
    - image: private-repo.com/psat
      context: .
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
deploy:
  kubectl:
    manifests:
      - "c:/src/k8s/psat/psat-deployment.yaml"
```

### Steps to reproduce the behavior

1. Run a k8s cluster
2. For a given project. run `skaffold dev --no-prune=false --cache-artifacts=false `
3. Press ctrl+c
