### ISSUE TITLE
Can't run skaffold/getting-started example with skaffold/minikube: ERRO[0000] run: getting skaffold config

### ISSUE THREAD

**Issue by fexman** [GoogleContainerTools/skaffold#363]
I'm having troubles setting up skaffold on my Windows 10 machine. I'm using skaffold with minikube and I'm trying to run the getting-started example. The context of kubectl IS "minikube".

### Expected behavior

For the examples/getting-started example to run.

### Actual behavior

An error message is displayed:
```
ERRO[0000] run: getting skaffold config: parsing skaffold build config: Unknown builder for config &{Artifact
21c0] TagPolicy:{GitTagger:<nil> ShaTagger:0x20503a0} BuildType:{LocalBuild:<nil> GoogleCloudBuild:<nil>}}
```

### Information

Skaffold version: v0.3.0
minikube version: v0.25.2
Operating system: Windows 10
Content of skaffold.yaml:
``` 
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-example
    workspace: .
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: k8s-skaffold
```
kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa
63b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd
4"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d65
6", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

### Steps to reproduce the behavior

  1. Navigate into examples\gettings-started folder
  2. Run `skaffold dev`
