### ISSUE TITLE
helm: error decoding parsed yaml: Object 'Kind'...

### ISSUE THREAD

**Issue by GavinOsborn** [GoogleContainerTools/skaffold#3642]
### Expected behavior
When using the Helm deployer errors are only printed to the console if they break the deployment.
### Actual behavior
When using the Helm deployer we always have a YAML parser error printed to the console.
> error decoding parsed yaml: Object 'Kind' is missing in 'REVISION: 1\nRELEASED: Tue Feb  4
> 14:34:20 2020\nCHART: service-name-0.1.0\nUSER-SUPPLIED VALUES:\nconfigs:\n...
> ... truncated for brevity

### Information
This does not appear to affect the deployment but it does add an awful lot of noise to the console as it dumps out the entire Helm release definition.

Turning up the verbosity logs to debug I can see this error appears immediately after `helm --kube-context minikube get service-name`.

Running the command locally confirms that `Kind` does not exist in the YAML it returns.

- Skaffold version: 1.3.1
- Operating system: windows
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: quay.io/nintex/service-name
  local:
    push: false
deploy:
  helm:
    releases:
      - name: service-name
        chartPath: testchart
        valuesFiles: [service-name/values.yaml]
        namespace: core
        wait: true
        values:
          image: quay.io/nintex/service-name
        imageStrategy:
          helm: {}
```

Printing errors isn't always a big problem but the sheer size of this payload makes it very noticable and adds a lot of noise when trying to debug other problems.
