### ISSUE TITLE
"patches" report "invalid path" after update

### ISSUE THREAD

**Issue by loripino21** [GoogleContainerTools/skaffold#3644]
### Expected behavior
"patches" operation in profile working correctly as always

### Actual behavior
After updating Cloud Code for IntelliJ to 20.1.3 and skaffold to 1.2.0, "patches" reports error:
level=fatal msg="creating runner: applying profiles: applying profile tag-as-latest: invalid path: /build/tagPolicy"
 Tried with all possible combinations of trailing and leading slashes.

### Information

- Skaffold version: version: 1.2.0
- Operating system: Windows 10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1 //(tried also v2alpha2)
kind: Config
profiles:
  - name: tag-as-latest
    patches:
      - op: add
        path: /build/tagPolicy
        value:
          envTemplate:
            template: "{{ .IMAGE_NAME }}:latest"
    activation:
      - command: dev
  - name: ffmpeg-dev
    build:
      artifacts:
        - image: gcr.io/..../ffmpeg
          context: components/ffmpeg
          docker:
            dockerfile: Dockerfile
```

### Steps to reproduce the behavior

Use above yaml with skaffold dev --profile ffmpeg-dev
skaffold debug works fine and builds the image.
