### ISSUE TITLE
Skaffold dev - not streamed log to stdout

### ISSUE THREAD

**Issue by tuananh170489** [GoogleContainerTools/skaffold#3648]
### Expected behavior
Logs get tailed after skaffold dev|run
### Actual behavior
No logs are tailed
### Information

- Skaffold version: version 1.3.1
- Operating system: MacOS Mojave 10.14.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: skaffold
profiles:
- name: demo
  build:
    artifacts:
    - image: skaffold-demo
      docker:
        dockerfile: Dockerfile
    tagPolicy:
      envTemplate:
        template: "{{.IMAGE_NAME}}:latest"
  deploy:
    kubectl:
      manifests:
      - demo.yaml
```
- Contents of demo.yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-demo
spec:
  selector:
    matchLabels:
      app: skaffold-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: skaffold-demo
    spec:
      containers:
      - name: skaffold-demo
        image: registry.xxx/library/skaffold-demo
        imagePullPolicy: Always
```

### Steps to reproduce the behavior

1. clone [getting-started](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/getting-started) sample skaffold project
2. `skaffold -p demo dev --status-check`
3. skaffold log with `--status-check` flag
```
WARN[0000] image [skaffold-demo] is not used by the deployment 
 - deployment.apps/skaffold-demo configured
Waiting for deployments to stabilize
 - development:deployment/skaffold-demo Waiting for deployment "skaffold-demo" rollout to finish: 1 old replicas are pending termination...
 - development:deployment/skaffold-demo is ready.
Deployments stabilized in 3.092964101s
```
4. Pod ran but no log sent to stdout
