### ISSUE TITLE
[Feature Request] Support deploying image names without digest (or an arch specific digest)

### ISSUE THREAD

**Issue by jahredhope** [GoogleContainerTools/skaffold#3649]
### Expected behavior

Skaffold would be able to be configured to set the containers image to either the image name without a digest, or the correct digest for the architecture.

### Actual behavior

If a custom command is used to build a multi-architecture set of images and successfully deployed there will be multiple digests. Both local and deployed environments will work correctly as long as they have the correct image name, excluding the digest.

Skaffold will attempt to discern the digest of an image by pulling the image from the registry.
A digest will be returned based on the current architecture of the local machine which may not match the server.

The fully qualified image name, including the architecture specific digest will be deployed, if the server archecture differs from the original infrastructure the pod will likely have issues, often failing to start.

### Information

- Skaffold version: v1.3.1
- Operating system: MacOS + Ubuntu
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
    - image: "my-registry/image-name"
      context: projects/my-project
      custom:
        buildCommand: ../../custom-build.sh
deploy:
  kubectl:
    manifests:
      - projects/my-project/kube.config.yml
```

**custom-build.sh**
```
#!/usr/bin/env bash
set -e

docker buildx build \
  --platform linux/amd64,linux/arm64 \
  --tag $IMAGE \
  --push \
  $BUILD_CONTEXT
```
