### ISSUE TITLE
Helm deployment with image name not at top level of the values structure.

### ISSUE THREAD

**Issue by lboclboc** [GoogleContainerTools/skaffold#3652]
When trying to deploy jenkins via skaffold and helm I get this go-error:
```
Starting deploy...
panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 1 [running]:
helm.sh/helm/v3/pkg/strvals.(*parser).key(0xc0006b0ee0, 0xc0004fff20, 0xc00061f898, 0x6)
	/home/circleci/helm.sh/helm/pkg/strvals/parser.go:211 +0xdea
helm.sh/helm/v3/pkg/strvals.(*parser).key(0xc0006b0ee0, 0xc0006d61e0, 0x1535b1d, 0x17d2ce0)
	/home/circleci/helm.sh/helm/pkg/strvals/parser.go:215 +0x1ad
helm.sh/helm/v3/pkg/strvals.(*parser).parse(0xc0006b0ee0, 0xc0006d61e0, 0x1)
	/home/circleci/helm.sh/helm/pkg/strvals/parser.go:133 +0x38
helm.sh/helm/v3/pkg/strvals.ParseIntoString(0x7ffed9fd0eec, 0xc1, 0xc0006d61e0, 0x0, 0x0)
	/home/circleci/helm.sh/helm/pkg/strvals/parser.go:93 +0xbe
helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc000642ae0, 0xc0006b0840, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/circleci/helm.sh/helm/pkg/cli/values/options.go:69 +0x2ac
main.newUpgradeCmd.func1(0xc0004e6780, 0xc0005bac30, 0x2, 0xf, 0x0, 0x0)
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:81 +0x1f7
github.com/spf13/cobra.(*Command).execute(0xc0004e6780, 0xc0005bab40, 0xf, 0xf, 0xc0004e6780, 0xc0005bab40)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003ce280, 0x1bc61c0, 0xc00044c0b0, 0x7ffed9fd0ed4)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:74 +0x1e2
FATA[0000] deploying ssvjenkins-playground: exit status 2 
```

I am trying to deploy jenkins with helm and it has its image specified as key master.image, like:
```
      values:
        master.image: registry2:443/atlas-ssvjenkins
      imageStrategy:
        helm: {}
```
### Expected behavior
If should deploy helm with proper image tags.

### Actual behavior
It deploys the jenkins helm with double tags on the image.

### Information

- Skaffold version 7b4da99.
- Ubuntu 18.04
- Contents of skaffold.yaml:
```
apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: ssv-jenkins

build:
  artifacts:
  - image: registry2:443/atlas-ssvjenkins
    docker:
      dockerfile: Dockerfile

deploy:
  helm:
    releases:
    - name: ssvjenkins-playground
      chartPath: stable/jenkins
      version: 1.9.16
      remote: true
      valuesFiles: 
      - ssv_jenkins_values
      namespace: playground
      values:
        master.image: registry2:443/atlas-ssvjenkins
      imageStrategy:
        helm: {} 
      setValues:
        master.nodePort: "32334"
    flags: { upgrade: [--install] }

```
### Steps to reproduce the behavior

1.skaffold run
2. kubectl get pod -> Shows pods can not start due to illegal image.
