### ISSUE TITLE
Kubectl deployer should match only on image and ignore tag

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#366]
Right now we expect users to not specify a tag in their kubernetes manifests for the kubectl deployer. We should match on image and ignore any tags the user might have.

**Comment by dgageot** [comment]
@r2d4 Don't we do that?

**Comment by LibertyBeta** [comment]
Can confirm that's not how its working in 4.0. As of right now if you tag ether image(via a envTemplate or the manifest) it won't deployed the watched image and throws an error that its not used. 

The artifact image name and the manifest image name must match exactly. Which means branching for local/remote is rather tricky. It appears from the docs that tagPolicy should solve this, but it doesn't.

**Comment by jgriff** [comment]
This looks like it's been addressed for the kubectl and helm deployers, but I'm still experiencing this with the kustomize deployer.

I have to omit the tag in my base manifest in order for skaffold to match the image. 

I have a fairly standard `skaffold.yaml`, which is using jib to containerize my Spring Boot app:

```yaml
apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
    - image: my.registry.io/my-image
      jibGradle: {}
deploy:
  kustomize: {}
```

If my k8s manifest specifies a tag for the image, skaffold will _not_ replace it:
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - image: my.registry.io/my-image:0.3.0
```
and emits the warning
```
WARN[0009] image [my.registry.io/my-image] is not used by the deployment
```

However, if I omit the version everything works as expected:
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - image: my.registry.io/my-image
```

**Comment by jgriff** [comment]
I created my own workaround to this, by patching the target image from my skaffold `kustomization.yaml`.

My `kustomization.yaml` (that `skaffold.yaml` refers to):
```yaml
bases:
  - ../../overlays/dev

# this would be ideal for inlining, but not (yet) supported (see https://github.com/kubernetes-sigs/kustomize/issues/1157)
patchesStrategicMerge:
  - striptag.yaml
```

And my `striptag.yaml` that "patches" the image with no tag:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
        - image: my.registry.io/my-image
```

Now, skaffold is able to manage my image.

While less than ideal, it at least allows me to keep my tags in my base manifests, and still have skaffold manage it during `skaffold dev`. 😬

**Comment by dbachrach** [comment]
Running into the same issue and using a similar workaround to @jgriff. My skaffold.yaml is now:

```yaml
bases:
  - ../../overlays/dev

images:
  - name: image/name
    newTag: latest
```

This is slightly cleaner than the striptag method but still not ideal. Should we open this problem with kustomize-based image tagging as a new issue?
