### ISSUE TITLE
Port Forwarding does not work with Helm deployer on Windows.

### ISSUE THREAD

**Issue by GavinOsborn** [GoogleContainerTools/skaffold#3679]
### Expected behavior
Running `skaffold dev --portforward` or `skaffold debug --portforward` should open up ports to any deployed services then available over localhost.

### Actual behavior
The skaffold output claims that the port has been open.
Any attempt to interact with my service over localhost fails to connect.

### Information

- Skaffold version: version 1.3.1
- Operating system: Windows
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: node-example
    context: backend
deploy:
  helm:
      releases:
      - name: node
        chartPath: chart
        values:
          image: node-example
        imageStrategy:
          helm: {}
```

### Steps to reproduce the behavior

1. Clone my fork of skaffold and updated the nodejs sample
2. `cd examples/nodejs`
3. `skaffold dev --port-forward`
4. Observe how the console output suggests that port forwarding has been enabled and a local port assigned
5. `curl 127.0.0.1:[local-port]`
6. Notice how it fails to connect
