### ISSUE TITLE
Get build timeout on local concurrent build

### ISSUE THREAD

**Issue by kvokka** [GoogleContainerTools/skaffold#3695]
### Actual behavior

with `skaffold dev` i rarely get this sort of error:

```
Sending build context to Docker daemon  9.742MB
Step 1/10 : FROM node:10.15
FATA[1032] failed to build: build failed: building [us.gcr.io/replay-gaming/poker-api]: build artifact: unable to stream build output: Get https://registry-1.docker.io/v2/library/node/manifests/10.15: net/http: TLS handshake timeout
make[1]: *** [dependencies] Error 1
make: *** [init] Error 2
```

Keep in mind, that building of all images takes more than 15 minutes

### Information

- Skaffold version: 1.3.1
- Operating system: MacOs 10.15
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
build:
  local:
    concurrency: 0
  tagPolicy:
    sha256: {}
  artifacts:
  - image: us.gcr.io/replay-gaming/rails
    docker:
      dockerfile: docker/development/Dockerfile
    context: rails
    sync:
      infer:
      - 'app/**/*'
      - 'bin/**/*'
      - 'db/**/*'
      - 'lib/**/*'
      - 'public/**/*'
      - 'script/**/*'
      - 'spec/**/*'
  - image: us.gcr.io/replay-gaming/poker-core
    docker:
      dockerfile: docker/development/Dockerfile
    context: core
    sync:
      infer:
        - 'bin/**/*'
        - 'db/**/*'
        - 'lib/**/*'
        - 'system/**/*'
        - 'schemas/**/*'
        - 'spec/**/*'
  - image: us.gcr.io/replay-gaming/poker-api
    docker:
      dockerfile: docker/development/Dockerfile
    context: api
    sync:
      infer:
        - 'bin/**/*'
        - 'src/**/*'
        - 'tests/**/*'
  - image: us.gcr.io/replay-gaming/poker-client
    docker:
      dockerfile: docker/development/Dockerfile
    context: client
    sync:
      infer:
        - 'bin/**/*'
        - 'public/**/*'
        - 'src/**/*'
  - image: us.gcr.io/replay-gaming/poker-scheduler
    docker:
      dockerfile: docker/development/Dockerfile
    context: scheduler
    sync:
      infer:
        - 'src/**/*'
  - image: us.gcr.io/replay-gaming/go-eventsource
    context: es
```

I assume that the root of the problem is in `concurrency` setting.

### Steps to reproduce the behavior

`skaffold dev`

This is flaky!
