### ISSUE TITLE
{{.IMAGE_NAME}} has no value after successful build w/ buildCommand

### ISSUE THREAD

**Issue by bitsofinfo** [GoogleContainerTools/skaffold#3702]
Doing something like the below yields a helm release name w/ `<no value>` which is illegal for helm.

The image tag that is created/pushed successfully before helm is invoked is: `56a66ce-dirty`, so I would expect `{{.IMAGE_NAME}}` to have this value but it doesn't.

My `buildCommand` below generates a dockerfile, builds, tags and pushes to a private registry w/ a tag that is equal to the value generated by the declared `tagPolicy` of `AbbrevCommitSha`

```
apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: my-testapp
build:
  artifacts:
    - image: registry.mydomain.com/my/my-testapp
      custom: 
        buildCommand: ./gen-tag-push-image.sh -f dockerhub.mydomain.com/my/my-base-image:3.3.0-0--1-1 --tagwithgitcommitid --build --tagpush

  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha  # git describe --match=NeVeRmAtCh --always --abbrev=7 --dirty

deploy:
  helm:
    releases:
      - name: "{{.IMAGE_NAME}}"
        chartPath: bitsofinfo-appdeploy/appdeploy
        remote: true
        version: 1.1.14
        wait: true
        namespace: my-apps

        valuesFiles:
          - /path/to/values/defaults/values.yaml
          - /path/to/values/stage/values.yaml
       
        setValueTemplates:
          image.tag: "{{.IMAGE_NAME}}"
          replicaCount: 2

```

https://github.com/GoogleContainerTools/skaffold/issues/3549
