### ISSUE TITLE
spec.template.labels: Invalid value with Helm

### ISSUE THREAD

**Issue by MrLuje** [GoogleContainerTools/skaffold#3708]
Skaffold generates invalid k8s deployements' labels through helm.
The generated tag with image digest contains invalid characters
[@ is invalid in a k8s labels ](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)

### Information

- Skaffold version: 1.3.1
- Operating system: Windows 10 with WSL
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: registry/myimage
    docker:
      dockerfile: Dockerfile.build
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    useBuildkit: false
deploy:
  helm:
    releases:
    - name: later
      chartPath: helm/myimage
      namespace: dev
      values:
        image: registry/myimage
      imageStrategy:
        helm: {}
    flags:
      global:
      - --tiller-namespace=dev-tiller
```

### Steps to reproduce the behavior

skaffold run --kube-context srz-dev

```
Generating tags...
 - registry/myimage -> registry/myimage:c9ffd90-dirty
Checking cache...
 - registry/myimage: Found Remotely
Tags used in deployment:
 - registry/myimage -> registry/myimage:c9ffd90-dirty@sha256:de8e3a7448a6bbf1a0edf4a5e852601831b2e3bba248cd04bc8fa04cba7264a5
Starting deploy...
Helm release later not installed. Installing...
No requirements found in helm/myimage/charts.
Error: release later failed: Deployment.apps "myimage-service" is invalid: [spec.template.labels: Invalid value: "c9ffd90-dirty@sha256:de8e3a7448a6bbf1a0edf4a5e852601831b2e3bba248cd04bc8fa04cba7264a5": must be no more than 63 characters, spec.template.labels: Invalid value: "c9ffd90-dirty@sha256:de8e3a7448a6bbf1a0edf4a5e852601831b2e3bba248cd04bc8fa04cba7264a5": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
```
BTW, I'm not totally sure why the tag used during deploy contains the digest and this is probably the issue.

**Comment by tejal29** [comment]
@MrLuje Can you please provide your deployment template for failing service?

Thanks
Tejal

**Comment by MrLuje** [comment]
And here is is ! (most of it is from **helm init** and some additions)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myimage.service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "myimage.service.name" . }}
    helm.sh/chart: {{ include "myimage.service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "myimage.service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myimage.service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "myimage.service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ include "myimage.service.name" . }}
        stack: dotnet
        version: "{{ .Values.image.tag }}"
      annotations:
        co.elastic.logs/multiline.match: after
        co.elastic.logs/multiline.negate: "true"
        co.elastic.logs/multiline.pattern: "^\e"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status/liveness
              port: http
            initialDelaySeconds: 30
            failureThreshold: 4
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /status/readiness
              port: http
            initialDelaySeconds: 30
            failureThreshold: 4
            timeoutSeconds: 5

          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
          - name: gcp-service-account-credentials-volume
            mountPath: /etc/gcp
            readOnly: true

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}

      volumes:
      - name: gcp-service-account-credentials-volume
        secret:
          secretName: gcp-credentials
          items:
          - key: .googlecredentials
            path: gcp_credentials.json

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
```

**Comment by MrLuje** [comment]
From my understanding, sha256 hash are added to tags during deploy (#3269) which is then added as k8s label on my deployment.
Unfortunatly, k8s shouldn't contain the @ char (as stated in error message)

**Comment by nkubala** [comment]
@MrLuje the issue here is that you're trying to use the tag generated by skaffold as a label in your deployment, which k8s won't accept because skaffold's generated tag isn't a valid label:

```yaml
spec:
  templates:
    labels:
      version: "{{ .Values.image.tag }}"
```
skaffold needs to append the digest to the tag so that the newly built image is picked up by k8s when a redeploy happens - more on that [here](https://github.com/GoogleContainerTools/skaffold/issues/3269#issuecomment-555185124). so using a generated tag from skaffold as a k8s label unfortunately won't work :( 

I'd recommend removing the label for now. we could consider setting the generated tag without the appended digest as a template value in helm for use in a chart, though I don't think our team will be able to prioritize this right now.
