### ISSUE TITLE
`update Deployment` deployment strategy for development?

### ISSUE THREAD

**Issue by jstrachan** [GoogleContainerTools/skaffold#372]
with kubernetes there are lots of different ways to work with YAML/ksonnet/templating/helm/GitOPs and whatnot to get kubernetes resources updated into Kubernetes. Also sometimes images are built in git repositories separately from where thing are composed together into courser grained charts etc. (e.g. the kubernetes charts repository https://github.com/kubernetes/charts typically doesn't have the `Dockerfile`s to build the images that are used in the charts).

When in pre-commit development and you wanna test out a new image its sometimes simpler to just try editing the `Deployment` resources directly after the `kubectl apply / helm install` and updating the `image:` entry directly.

I wonder if it worth adding a simple strategy for development time which is configured with the name or label selector of the `Deployment` resource(s) to update:
```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: cheese:1234
    workspace: .
  local: {}
deploy:
  updateDeployment:
    labels:
      foo: bar
      cheese: abcd
```
Then given a test environment you could try out a new build of an image and it'd automatically modify the matching `Deployment` resources which have an image `cheese:*` in them.

This then lets folks rebuild images and update kubernetes - however the `Deployment` resources were created.
