### ISSUE TITLE
Permit custom buildCommand to export skaffold ENV vars that could be referenced in Helm releases

### ISSUE THREAD

**Issue by bitsofinfo** [GoogleContainerTools/skaffold#3737]
Permit custom buildCommand to export skaffold ENV vars that could be referenced in Helm releases

Would be great if this:
```
build:
  artifacts:
    - image: myreg.test.com/my/my-app
      custom: 
        buildCommand: ./builder.sh
...
```

Could (via STDOUT or other means) convey some variables that Skaffold could add to its execution environment whereby they could be referenced elsewhere in skaffold.yaml, i.e.

```
deploy:
  helm:
    releases:
      - name: my-app-{{.SOME_VAR_SET_BY_BUILD_CMD}}
        chartPath: bitsofinfo-appdeploy/appdeploy
        remote: true
        version: 1.1.14
...
```
