### ISSUE TITLE
Kaniko: ERROR: Dockerfile not found at ./Dockerfile

### ISSUE THREAD

**Issue by saurav-bhagat** [GoogleContainerTools/skaffold#3744]
I'm using kaniko to build my images and my Dockerfiles are located inside a directory which has multiple sub-directories. But Its failing to build. What's the right way to specify the path?
- Contents of skaffold.yaml:

```yaml
artifacts:
  - image: abc
    context: ./Dockerfiles/abcdirectory/
    kaniko:
      dockerfile: ./Dockerfiles/abc/Dockerfile
  - image: def
    context: ./Dockerfiles/defdirectory/
    kaniko:
      dockerfile: ./Dockerfiles/def/Dockerfile
```
