### ISSUE TITLE
--no-watch flag outputs "watching for changes"

### ISSUE THREAD

**Issue by redborian** [GoogleContainerTools/skaffold#3746]
### Expected behavior
Skaffold dev command with `--no-watch` flag should not output `"watching for changes"`

### Actual behavior
Skaffold dev does not have a `--no-watch` flag - it outputs `"watching for changes"`

![image](https://user-images.githubusercontent.com/6260897/75465426-78a24900-593d-11ea-809d-94b188297412.png)

### Information

- Skaffold version: v1.3.1
- Operating system: Windows
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: nodejs-hello-world
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
```

### Steps to reproduce the behavior

1. Clone new sample in Cloud Code IntelliJ extension
2. Use "Run on Kubernetes" to deploy to kubernetes cluster
3. In the output channel, as part of Skaffold commands output, `"Watching for changes..."` string is printed

FYI @nkubala @ivanporty
