### ISSUE TITLE
Fails to apply namespace to releases in Helm 3

### ISSUE THREAD

**Issue by BlenderDude** [GoogleContainerTools/skaffold#3762]
### Expected behavior

When deploying to helm and using the `namespace` tag on the release, the `--namespace` argument should be passed to the upgrade (install), delete and get calls. 

### Actual behavior

The namespace is properly applied to the upgrade (install) command, but not during `Cleanup` or `getArgs`. I believe this problem was introduced with #3738 because helm3's releases themselves are namespace'd. 

### Information

- Skaffold version: v1.4.0-73-ga9c7b3a47-dirty (pulled from master)
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: example
deploy:
  helm:
    releases:
      - name: example
        chartPath: helm
        namespace: example

```

### Steps to reproduce the behavior

Example Repo (requires a namespace "example") 
[https://github.com/BlenderDude/skaffold-helm3-namespaces](https://github.com/BlenderDude/skaffold-helm3-namespaces)

1. Create a helm deploy release that is scoped to a namespace
2. Run `skaffold dev` once
3. Quit to trigger a cleanup, it will fail because it cannot find the release in the namespace
4. Re-run `skaffold dev` and it will fail upon installing because there is already a release, this exposes the fact that the helm getter is not accessing  a namespace scoped release

I have already made some changes to the Go code and will be posting them as a PR, but I may need some help as I am not too familiar with Go.
