### ISSUE TITLE
Add IMAGE_REPOSITORY template variable (default-repo)

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#3763]
# Expected behavior
There should be a way to retrieve the `default-repo` somehow in order to correctly insert it into the skaffold.yaml

According to https://skaffold.dev/docs/environment/image-registries/ you can set the default repo. But there currently isn't a [Templated Field](https://skaffold.dev/docs/environment/templating/) to then use it in the skaffold.yaml.

This is needed for instance when passing image details as helm values.
When you create a new chart with `helm create my-app` this is exactly how helm expects the image repo, name and tag to be passed to using helm values.yaml

For example,
```bash
skaffold config set default-repo my-docker-repo.com
# Need access default-repo as {{.IMAGE_REPOSITORY}} in skaffold deploy helm phase
```
```yaml
  helm:
    releases:
    - name: my-app
      chartPath: ./helm
      skipBuildDependencies: true
      setValueTemplates:
        image.repository: '{{.IMAGE_REPOSITORY}}/{{.IMAGE_NAME}}'
        image.tag: '{{.IMAGE_TAG}}'
```

**NOTE**: I'm aware I could pass `SKAFFOLD_INSECURE_REGISTRY` environment variable to skaffold and then access that, BUT I find this more cumbersome than just setting it once for my kube-context via `skaffold config set default-repo` approach.

### Information

- Skaffold version: 1.4.0
- Operating system: Windows
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: my-app

build:

  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.USERNAME}}'

  artifacts:
    - image: my-app
      jib:
        type: maven

deploy:

  helm:
    releases:
    - name: my-app
      chartPath: ./helm
      skipBuildDependencies: true
      setValueTemplates:
        image.repository: '{{.IMAGE_REPOSITORY}}/{{.IMAGE_NAME}}'
        image.tag: '{{.USERNAME}}'    
```

### Steps to reproduce the behavior

1. `skaffold config set default-repo metam-docker-hosted.forge.avaya.com`
2. `skaffold dev -v debug 2>&1`
3. IMAGE_REPOSITORY = `<no value>`
