### ISSUE TITLE
Skaffold Deploy using -i for images doesn't respect default repository

### ISSUE THREAD

**Issue by simonjpartridge** [GoogleContainerTools/skaffold#3765]
# Expected behavior

Using `-i` in skaffold deploy uses default image repo. Or allows full path to image 

### Actual behavior
Repo path isn't added to image name

### Information

- Skaffold version: version 1.4.0
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
metadata:
  name: xxxx
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  local: {}
  artifacts:
    - image: api
      custom:
        buildCommand: docker/skaffold/build_script.sh
        dependencies:
          dockerfile:
            path: docker/go/Dockerfile
            buildArgs:
              service_to_build: api
profiles:
  - name: gke
    deploy:
      kustomize:
        path: .kubernetes/svc_kustomize/overlays/environments/gke

```

### Steps to reproduce the behavior

1. ensure image is built, and tagged and in image registry
2. skaffold deploy -p gke -d 'registry.gitlab.com/xxxx/xxxx' -i api:3c42eeeaba11a0df4b8b21682e02a4cb333452d3

just deploys an image of api:3c42eeeaba11a0df4b8b21682e02a4cb333452d3 not registry.gitlab.com/xxxx/xxxx/api:3c42eeeaba11a0df4b8b21682e02a4cb333452d3 as I expected.

Alternatively trying skaffold deploy -p gke -i registry.gitlab.com/xxxx/xxxx/api:3c42eeeaba11a0df4b8b21682e02a4cb333452d3

gives  
error `FATA[0000] no tag provided for image [api]`
