### ISSUE TITLE
Skaffold init shouild generate a skaffold.yaml with default section.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#3766]
See https://docs.google.com/document/d/1uAc619ljC_Fv-CfITNZkzf1c277gjhCAQeEmuc72wLE/edit#heading=h.h0sytgb7bsf5 for more details. 

Skaffold init does not set the context properly for certain repository configurations e.g. #3760 
```
kind: Config
metadata:
  name: kaniko
build:
  artifacts:
  - image: gcr.io/kaniko-project/executor
    context: app/deploy
```
In such case, user has to manually change the context dir from "app/deploy" to "app".
Only changing the context dir gives an error 
```
time="2019-11-20T19:09:02-08:00" level=fatal msg="watching files for artifact gcr.io/kaniko-project/executor: listing files: listing files: opening dockerfile: app/Dockerfile: open app/Dockerfile: no such file or directory"
```
To fix the config correctly users have to add the default `docker` stanza with the right `dockerfile` location.

```
kind: Config
metadata:
  name: kaniko
build:
  artifacts:
  - image: gcr.io/kaniko-project/executor
    context: app/
    docker:
      dockerfile: deploy/Dockerfile
```

It would be nice, if skaffold init when generation skaffold.yaml, adds the default docker config.
```
kind: Config
metadata:
  name: kaniko
build:
  artifacts:
  - image: gcr.io/kaniko-project/executor
    context: app/deploy
    docker:
      dockerfile: Dockerfile
```
so users, can change the context as well all the relative files instead of figuring what the error is.
