### ISSUE TITLE
support skaffold init for helm apps.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#3768]
This is a tracking issues to support `skaffold init` for helm apps.

Add a flag like `skaffold init --helm`. Try to parse the helm charts, and
1. Suggest the correct key for `image` value used in helm templates deployment.yaml. 
   e.g. in the skaffold helm example, the image key is `Values.image` [0](https://github.com/GoogleContainerTools/skaffold/blob/master/examples/helm-deployment/skaffold-helm/templates/deployment.yaml#L24)
   This should be set in skaffold.yaml
```

apiVersion: skaffold/v2alpha4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: skaffold-helm
      values:
        image: skaffold-helm
```

2. Retry cleaning using `--no-hooks` if `helm delete failed` for charts with hooks.
3. For all hooks, identify the artifacts and create a corresponding entry in `skaffold.build` config.
    - changes to hooks code should also re-install the chart by listing source code in hooks as source dependency. (not sure how to wire that up)
