### ISSUE TITLE
Add coherent examples for skaffold.yaml

### ISSUE THREAD

**Issue by mleonhard** [GoogleContainerTools/skaffold#3780]
https://skaffold.dev/docs/references/yaml/

Add working examples for:
- common use cases
- each feature supported by the tool

For example, the current docs show:
```
build:
  artifacts:
  - image: gcr.io/k8s-skaf
    context: .
    sync: infer: ["**/*"]
      manual:
      - src: "css/**/*.css"
        dest: "app/"
        strip: "css/"
      infer: []
```
This is mixing together three ways to use the `sync` section.  By presenting the documentation in this way, the reader must learn all styles to be able to sort out the values required for their case.  And there will be trial-and-error, which is a huge time sink.  Users come to documentation to accomplish specific goals.  Learning the myriad ways the tool can be used is rarely one of those goals.
