### ISSUE TITLE
library code change should trigger main app reload in multimodule project

### ISSUE THREAD

**Issue by Romeh** [GoogleContainerTools/skaffold#3784]
### Expected behavior
library code change should trigger main app reload in multimodule project 
### Actual behavior
library code DOES not change should trigger main app reload in multi-module project 
### Information

- Skaffold version: 1.4.0.
- Operating system:  mac os
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: test-app
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
  artifacts:
    - image: docker-registry.test.com/test/test-app
      jib:
        project: test-app
      context: .
deploy:
  kubeContext: docker-for-desktop
  helm:
    releases:
      - name: test-app
        chartPath: test-app/src/main/helm
        valuesFiles:
          - test-app/src/main/helm/values.yaml
        version: 1.0.0
        setValueTemplates:
          "test-graph.image.repository": '{{.IMAGE_NAME}}'
          "test-graph.image.tag": '{{.DIGEST_HEX}}'


```

### Steps to reproduce the behavior
It is more a question more than an issue. 

Project structure :
test-app -> where image i created and spring boot web runner start
test-library -> common code used by test-app module

1- you have gardle multi module project where one module produce the image and the second module is just common code library used by the first module
2- if i change the code in the library module , no way code change trigger reload except if i change something in the test-app module

is there a way to make the library code change trigger the reload of test-app without changing the test-app code ? fileSync maybe ?
