### ISSUE TITLE
Unexpected docker build dependency behavior: pulls the base image instead of building it

### ISSUE THREAD

**Issue by whitleykeith** [GoogleContainerTools/skaffold#3801]
When attempting to build an image that is built from another image in the skaffold on parallel builds, the dependent image tries to pull the base instead of building it first.

This is fine if the image isn't being pushed, but if it is I suspect that it'll pull the image in the registry instead of building it. 

### Expected behavior
Skaffold builds the base image first and doesnt try to pull the image
### Actual behavior
Skaffold attempts to pull the base image and gets a warning. 
### Information

- Skaffold version: version...
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: skaffoldtest
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
  - image: radix
    context: ./search/api
    docker:
      dockerfile: Dockerfile
      buildArgs:
        BUILDER: "api:{{.VERSION}}"
      noCache: false
  - image: radix
    context: ./search/api/radix-search
    docker:
      dockerfile: Dockerfile
      buildArgs:
        BUILDER: "api:{{.VERSION}}"
      noCache: false
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
```

### Steps to reproduce the behavior

1. Have a skaffold yaml with a image dependent on another image
2. `skaffold build`
3. See how the dependent image tries to pull instead of infering the dependency

**Comment by nkubala** [comment]
@whitleykeith would you mind providing a little more info to help reproduce this? a sample Dockerfile would be great, or some logs showing what's happening when you're running into this issue.

**Comment by whitleykeith** [comment]
So rewriting the above one to make it more clear:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: skaffoldtest
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
  - image: deployment_image
    context: PATH
    docker:
      dockerfile: Dockerfile
      buildArgs:
        BUILDER: "build_image:{{.VERSION}}"
      noCache: false
  - image: build_image
    context: BUILDPATH
    docker:
      dockerfile: Dockerfile
      noCache: false
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0

```

and the deployment_image dockerfile pulls from a base like this:

```
ARG BUILDER=build_image
FROM $BUILDER
```

**Comment by whitleykeith** [comment]
Any update on this?

**Comment by nkubala** [comment]
I think this would actually be solved through artifact modules: the idea would be that you could set the dependency image as a child module of the parent, and that would guarantee the build order and also guarantee that the base image is built first so it doesn't reach out to a registry. does that sound like it would solve your use case?

you can have a look at the design for this feature here: tinyurl.com/skaffold-modules. please feel free to leave comments!

**Comment by gsquared94** [comment]
Skaffold supports defining build dependencies between artifacts that enforces build order. Try:
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: skaffoldtest
build:
  artifacts:
  - image: deployment_image
    context: PATH
    requires:
      - image: build_image
        alias: BUILDER         //BUILDER is set as a build arg with the image tag as value.
  - image: build_image
    context: BUILDPATH
```
