### ISSUE TITLE
Getting Remote Config even for local Docker Image

### ISSUE THREAD

**Issue by no1melman** [GoogleContainerTools/skaffold#3808]
### Expected behavior
Skaffold run through the pipeline

### Actual behavior
Get error:

```
FATA[0002] watching files for artifact ncouk-client: listing files: listing files: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (builder-yarnbuilder) for ONBUILD triggers: getting remote config: getting image: GET https://index.docker.io/v2/library/builder-yarnbuilder/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/builder-yarnbuilder Type:repository]
```

### Information

- Skaffold version: v1.5
- Operating system: macOS 10.14.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ncouk-client
      context: containers/www/client/
      docker:
        dockerfile: Dockerfile.v2
 
deploy:
  helm:
    releases:
    - name: www-client
      chartPath: containers/www/k8s/client
      values:
        image.repository: ncouk-client
      setValues:
        env.graphEndpoint: http://graph.nwcouk.local
        env.layoutservice.endpoint: http://www-dclayout
      namespace: ncouk
```

The Dockerfile that this is relating to:

```dockerfile
FROM builder-yarnbuilder AS builder
```

### Steps to reproduce the behavior

`skaffold dev`
