### ISSUE TITLE
Unable to provide child Dockerfile to kaniko/executor

### ISSUE THREAD

**Issue by valdestron** [GoogleContainerTools/skaffold#3822]
Pipeline config:
```yaml
buildPack: typescript
pipelineConfig:
  pipelines:
    pullRequest:
      build:
        replace: true
        steps:
          - name: container-build
            sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml # this is the command that i am running for build
```

Skaffold config
``` yaml
apiVersion: skaffold/v2alpha4
kind: Config
build: 
  artifacts: 
    - 
      image: my-image
      kaniko:
        image: gcr.io/kaniko-project/executor
        buildArgs: 
          destination: XXX.dkr.ecr.eu-central-1.amazonaws.com/repo/xx/my-image:latest"
        dockerfile: /workspace/source/microservices/my-image/Dockerfile
        volumeMounts: 
          - mountPath: /kaniko/.docker/
            name: docker-config
  cluster: 
    volumes: 
      - secret: 
          name: docker-config
          volumeName: jenkins-docker-cfg
deploy: 
  kubectl: {}
```
### Expected behavior
Find and build image with provided dockerfile

### Actual behavior
No matter how i change build args, context, dockerfile destination getting error:
```
Error: error resolving dockerfile path: please provide a valid path to a Dockerfile within the build context with --dockerfile
Usage:
  executor [flags]
Flags:
      --build-arg multi-arg type                  This flag allows you to pass in ARG values at build time. Set it repeatedly for multiple values.
      --cache                                     Use cache when building image
      --cache-dir string                          Specify a local directory to use as a cache. (default "/cache")
      --cache-repo string                         Specify a repository to use as a cache, otherwise one will be inferred from the destination provided
      --cache-ttl duration                        Cache timeout in hours. Defaults to two weeks. (default 336h0m0s)
      --cleanup                                   Clean the filesystem at the end
  -c, --context string                            Path to the dockerfile build context. (default "/workspace/")
  -d, --destination multi-arg type                Registry the final image should be pushed to. Set it repeatedly for multiple destinations. (default )
  -f, --dockerfile string                         Path to the dockerfile to be built. (default "Dockerfile")
      --force                                     Force building outside of a container
  -h, --help                                      help for executor
      --insecure                                  Push to insecure registry using plain HTTP
      --insecure-pull                             Pull from insecure registry using plain HTTP
      --insecure-registry multi-arg type          Insecure registry using plain HTTP to push and pull. Set it repeatedly for multiple registries.
      --no-push                                   Do not push the image to the registry
      --reproducible                              Strip timestamps out of the image to make it reproducible
      --single-snapshot                           Take a single snapshot at the end of the build.
      --skip-tls-verify                           Push to insecure registry ignoring TLS verify
      --skip-tls-verify-pull                      Pull from insecure registry ignoring TLS verify
      --skip-tls-verify-registry multi-arg type   Insecure registry ignoring TLS verify to push and pull. Set it repeatedly for multiple registries. (default )
      --snapshotMode string                       Change the file attributes inspected during snapshotting (default "full")
      --tarPath string                            Path to save the image in as a tarball instead of pushing
      --target string                             Set the target build stage to build
  -v, --verbosity string                          Log level (debug, info, warn, error, fatal, panic (default "info")
```

### Information

- JenkinsX pipeline on kubernetes cluster

I am not sure what I am doing wrong, how can I provide Dockerfile that is nested in my monorepo microservice directory?

**Comment by valdestron** [comment]
The same happens with docker config like this:

```yaml
apiVersion: ...any
kind: Config
build:
  artifacts: 
    - image: my-service
      context: .
      docker:
        dockerfile: microservices/my-service/Dockerfile
  local:
      useDockerCLI: true
deploy: 
  kubectl: {}
```

skaffold debug result:
```
C02YN7GXLVCF:services name$ skaffold debug
Listing files to watch...
WARN[0000] k8s/*.yaml did not match any file            
Generating tags...
 - my-service-> my-service:0188bed-dirty
Checking cache...
 - my-service: Not found. Building
Building [my-service]...
Sending build context to Docker daemon  108.5kB
Step 1/12 : FROM alpine
 ---> c85b8f829d1f
Step 2/12 : LABEL authors="Valdas Mazrimas <valdas.mazrimas@gmail.com>"
 ---> Using cache
 ---> 822557564e88
Step 3/12 : RUN apk add --update nodejs yarn
 ---> Using cache
 ---> d6927e3bbc60
...
```

Pipeline result: the same in the original issue

**Comment by valdestron** [comment]
I upgraded skaffold cli to 1.6 in my builder image, and used v2beta1 api, and added tagPolicy, works perfectly.

```
apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: xxxx.dkr.ecr.eu-central-1.amazonaws.com/xxx/xx/api-gateway
    context: .
    kaniko: 
      dockerfile: microservices/api-gateway/Dockerfile
  - image: xxxx.dkr.ecr.eu-central-1.amazonaws.com/xxx/xx/api-gateway-deprecated
    context: .
    kaniko: 
      dockerfile: microservices/api-gateway-deprecated/Dockerfile
  cluster:
    dockerConfig:
      secretName: jenkins-docker-cfg
    namespace: jx
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.VERSION}}'
deploy:
  kubectl: {}
```
