### ISSUE TITLE
Custom/Buildpack builders should support glob patterns for dependencies

### ISSUE THREAD

**Issue by dsyer** [GoogleContainerTools/skaffold#3826]
Here's the example in the docs:

```yaml
custom:
  buildCommand: ./build.sh
  dependencies:
    paths:
    - pkg/**
    - src/*.go
    ignore:
    - vendor/**
```

When I do that I get "... stating file pkg/**: no such file or directory" and `skaffold` crashes. It works for me with just the directory. Is that expected? If so, maybe it should be reflected in the docs.
