### ISSUE TITLE
skaffold dev: "pyenv: python2: command not found" when running the docker build

### ISSUE THREAD

**Issue by docwhite** [GoogleContainerTools/skaffold#3829]
### Expected behavior
Should not print warnings when running `skaffold dev`

### Actual behavior
Warns complaining about `python2` somewhere:

```
➜  dreamdrugs git:(master) skaffold dev
Listing files to watch...
 - gcr.io/dreamdrugs/backend
 - gcr.io/dreamdrugs/frontend
Generating tags...
 - gcr.io/dreamdrugs/backend -> gcr.io/dreamdrugs/backend:latest
 - gcr.io/dreamdrugs/frontend -> gcr.io/dreamdrugs/frontend:latest
Checking cache...
 - gcr.io/dreamdrugs/backend: Not found. Building
 - gcr.io/dreamdrugs/frontend: Not found. Building
Found [minikube] context, using local docker daemon.
Building [gcr.io/dreamdrugs/backend]...
pyenv: python2: command not found

The `python2' command exists in these Python versions:
  2.7.17
  2.7.17/envs/fabric_python2
  2.7.17/envs/wct_streaming_farm
  fabric_python2
  wct_streaming_farm

Sending build context to Docker daemon  104.5MB
Step 1/7 : FROM tensorflow/tensorflow:1.13.2-py3
[...]
It continues fine
```

If I use debug verbosity I get:

```
[...]
Checking cache...
DEBU[0003] Found dependencies for dockerfile: [{package.json /dreamdrugs/frontend true} {yarn.lock /dreamdrugs/frontend true} {. /dreamdrugs/frontend true}]
DEBU[0003] Found dependencies for dockerfile: [{poetry.lock /dreamdrugs/backend true} {pyproject.toml /dreamdrugs/backend true} {. /dreamdrugs/backend true}]
DEBU[0003] Skipping excluded path: node_modules
 - gcr.io/dreamdrugs/backend: Not found. Building
 - gcr.io/dreamdrugs/frontend: Not found. Building
INFO[0003] Cache check complete in 193.697683ms
Found [minikube] context, using local docker daemon.
Building [gcr.io/dreamdrugs/backend]...
DEBU[0003] Running docker build: context: backend, dockerfile: Dockerfile
pyenv: python2: command not found

The `python2' command exists in these Python versions:
  2.7.17
  2.7.17/envs/fabric_python2
  2.7.17/envs/wct_streaming_farm
  fabric_python2
  wct_streaming_farm

DEBU[0003] Found dependencies for dockerfile: [{poetry.lock /dreamdrugs/backend true} {pyproject.toml /dreamdrugs/backend true} {. /dreamdrugs/backend true}]
Sending build context to Docker daemon  104.5MB
Step 1/7 : FROM tensorflow/tensorflow:1.13.2-py3
[...]
It continues fine :)
```

### Information
This is just my OCD getting triggered, please don't spend too much time on it, but I am super curious to know where is it coming from.

I use `pyenv` and I have globally set python to 3.8.0, so I don't know where does `python2` get picked up, I have to `.python-version` files anywhere in that repo.

At first I thought I would put that into Docker's support but... If I try to build the context manually it doesn't complain:

```
➜  backend git:(master) docker build -t gcr.io/dreamdrugs/backend .
Sending build context to Docker daemon  104.5MB
Step 1/7 : FROM tensorflow/tensorflow:1.13.2-py3
1.13.2-py3: Pulling from tensorflow/tensorflow
5b7339215d1d: Downloading [=================>                                 ]  9.436MB/26.68MB
14ca88e9f672: Download complete
```

Does skaffold do something like trying first python2 for some reason? I thought the extra debug logs might shed some light but it confirmed it happens in the build step?

- Skaffold version: 1.5.0
- Operating system: macOS 10.15.3
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
metadata:
  name: dreamdrugs
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/dreamdrugs/backend
    context: backend
    sync:
      infer:
      - 'app.py'
      - 'dreamdrugs/**/*.py'

  - image: gcr.io/dreamdrugs/frontend
    context: frontend
    sync:
      infer:
      - 'src/**/*'
      - 'server.js'
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: deploy/dreamdrugs
      values:
        backendImage: gcr.io/dreamdrugs/backend
        frontendImage: gcr.io/dreamdrugs/frontend
      setValues:
        development: true
      overrides:
        redis:
          password: pass1234
          master:
            persistence:
              enabled: false
          slave:
            persistence:
              enabled: false
```

### Steps to reproduce the behavior

1. Have `pyenv` installed with 3.x globally set.
2. Have minikube, docker and skaffold installed.
3. Have minikube running: `minikube start`
4. Clone my repo `git clone git@github.com:docwhite/dreamdrugs.git`
5. Change directory and run `skaffold dev`
