### ISSUE TITLE
Build using specified Dockerfile

### ISSUE THREAD

**Issue by vj319** [GoogleContainerTools/skaffold#3835]
### Expected behavior
There should be an option to specify the Dockerfile path for local build using where skaffold uses Docker Engine APIs to build docker images.
### Actual behavior
No options for specifying Dockerfile
### Information

- Skaffold version: v1.5.0
- Operating system: ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: config
build:
        artifacts:
                - image: skaffold-mon
        local:
                dockerfile: ../Dockerfile
deploy:
        kubectl:
                manifests:
                      - ../mon.yaml
```

### Steps to reproduce the behavior

1. Try skaffold dev with Dokerfile in different directory
2. skaffold dev
