### ISSUE TITLE
skaffold dev fails to sync files when Pod Security Policy (PSP) Run As User Policy config is enabled (feature request)

### ISSUE THREAD

**Issue by jturi** [GoogleContainerTools/skaffold#3839]
**Actual behavior**
`skaffold dev` fails to sync files to pod if `Pod Security Policy (PSP)`  `Run As User Policy:` `MustRunAs - Requires a range to be configured. Uses the first value of the range as the default. Validates against the configured range` security configuration is enabled.

**Expected behavior**
`skaffold dev` could have a flag to specify the user ID to overcome the Run As User Policy security restrictions.

**To Reproduce**
1. Download skaffold v1.5.0
2. Prepare project files, Dockerfile and skaffold.yaml
3. Docker login to a private repository, login successful
4. set regred secret and docker-config configmap
5. Get user ID for the user who will deploy ie: 26850
5. Change `Pod Security Policy (PSP)`  `Run As User Policy User ID:` from `RunAsAny` to -> `MustRunAs: 26850`
6. Run SKAFFOLD_UPDATE_CHECK=false skaffold -n webapp1 build --verbosity DEBUG

**Error message**
```
INFO[0073] files modified: [sample_api/src/sample_api.py]
DEBU[0073] Found dependencies for dockerfile: [{src/requirements.txt /code true} {src/sample_api.py /code true} {src/requirements.txt /code true}]
Syncing 1 files for private_registry/sample_psp_api:2020-03-18@sha256:25681e3671458d9bbf0320fb0ded4ecfc5244ff20109d168b9a3732093b7226b 
INFO[0073] Copying files: map[sample_api/src/sample_api.py:[/code/sample_api.py]] 
to private_registry/sample_psp_api:2020-03-18@sha256:25681e3671458d9bbf0320fb0ded4ecfc5244ff20109d168b9a3732093b7226b
DEBU[0073] getting client config for kubeContext: ``
DEBU[0073] Running command: [kubectl --context private-cluster02 
--namespace sample-psp exec sample-psp-api-deployment-79c4b948d-84jvn 
--namespace sample-psp -c sample-psp-api-container -i -- tar xmf - -C / --no-same-owner]
WARN[0075] Skipping deploy due to sync error: copying files: Running [kubectl --context private-cluster02 
--namespace sample-psp exec sample-psp-api-deployment-79c4b948d-84jvn 
--namespace sample-psp -c sample-psp-api-container -i -- tar xmf - -C / --no-same-owner]
 - stdout:
 - stderr: tar: removing leading '/' from member names
tar: can't remove old file code/sample_api.py: Permission denied
command terminated with exit code 1
: exit status 1
Watching for changes...
```

**Project files**
 - config.json
```
{
	"auths":{
		"private_repository_here":{
			"auth":"usrname:password | base64 details_here"
			}
		}
}
```
 - Dockerfile
```
FROM private_registry/python:latest
COPY src/requirements.txt ./code/
RUN pip3 install -r requirements.txt
COPY src/* ./code/
RUN addgroup --system user && adduser --system user
RUN chown -R user:user ./code/ && chmod -R 755 ./code/
USER user
CMD ["python", "code/sample_api.py"]

```
 - Project tree
```
sample_webapp/
├── docker-compose.yaml
├── webapp_main
│   ├── docker
│   │   ├── api
│   │   │   └── Dockerfile
│   │   └── worker
│   │       └── Dockerfile
│   └── src
│       ├── requirements.txt
│       ├── sample_api.py
│       ├── sample-api.yaml
│       ├── sample_worker.py
│       └── sample-worker.yaml
├── k8s
│   ├── k8s-sample-api.yaml
│   └── k8s-sample-worker.yaml
└── skaffold.yaml
```

- skaffold.yaml
```
apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: sample_webapp_kaniko
build:
  cluster:
    pullSecretName: kaniko-secret
    namespace: webapp1
  artifacts:
    - image: private_repository/sample_webapp_api_img
      context: ./webapp_main/
      kaniko:
        dockerfile: ./docker/api/Dockerfile
        image: private_repository/kaniko-project/executor:v0.16.0
        initImage: private_repository/busybox:1.31.1
  insecureRegistries: ["private_repository"]
deploy:
  kubectl:
    manifests:
      - ./k8s/*
```

- docker-compose.yaml runs successfully
```
version: '3'
services:
  webapp_api:
    image: " private_repository/sample_webapp_api_img:1"
    build:
      context: ./webapp_main/
      dockerfile: ./docker/api/Dockerfile
```
