### ISSUE TITLE
Images not found in remote registry

### ISSUE THREAD

**Issue by mabey01** [GoogleContainerTools/skaffold#3849]
Im trying to speed up build time for my project. I have a monorepo inlcuding frontend and backend and use the `TreeSha` tagger to detect changes made to each component individually. If i make frontend changed, backend is tagged with the same tag as before and therefore should skip the building process, but it doesnt.

### Expected behavior
After tagging, skaffold checks cache to see if the image (same tag) already exists and skips build.

### Actual behavior
skaffold doesnt find cached image in remote registry and builds it everytime (same tag). When i check in the google cloud registry i can find the image with the exact same tag

```
Generating tags...
 - api -> gcr.io/$PROJECT_ID/api:da9312ba3078e4020b8eaf8252793f3e3b26e9b9
 - frontend-client -> gcr.io/$PROJECT_ID/frontend-client:e9893689bc634abfcf7869d9f6de0bfa92f5fabe
 - chromecast -> gcr.io/$PROJECT_ID/chromecast:b982cd13d946e4b2dc0884104707540d7ba02a1e
Checking cache...
 - api: Not found. Building
 - frontend: Not found. Building
```

### Information

- Skaffold version: version 1.5
- Operating system: windows/google cloud build
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha4
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: TreeSha
  artifacts:
    - image: api
      context: ./backend
    - image: frontend
      context: ./frontend
profiles:
  - name: production
    build:
      googleCloudBuild: 
        projectId: $PROJECT_ID
```

### Steps to reproduce the behavior

`skaffold build -p production --default-repo=gcr.io/$PROJECT_ID`

**Comment by balopat** [comment]
Thanks for opening this @mabey01 - can you share your Dockerfiles? 
The way artifact caching works is that we calculate the source digest based of the source files that  are the dependencies for the Dockerfile `ADD/COPY` commands. 
Does a simple `skaffold build` twice (without any changes) also result in two rebuilds?

**Comment by valdestron** [comment]
Having the same issue:
```sh
            VERSION=$VERSION_TO_BUILD skaffold build -f skaffold.yaml $services
            VERSION=latest skaffold build -f skaffold.yaml $services
```

```yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: xxxx.dkr.ecr.xxx.amazonaws.com/sagahead-io/hector/api-gateway
    context: .
    kaniko: 
      dockerfile: microservices/api-gateway/Dockerfile
  - image: xxxx.dkr.ecr.xxx.amazonaws.com/sagahead-io/hector/api-gateway-deprecated
    context: .
    kaniko: 
      dockerfile: microservices/api-gateway-deprecated/Dockerfile
  - image: xxxx.dkr.ecr.xxx.amazonaws.com/sagahead-io/hector/api-gateway-reverse-proxy
    context: .
    kaniko: 
      dockerfile: microservices/api-gateway-reverse-proxy/Dockerfile
  cluster:
    dockerConfig:
      secretName: jenkins-docker-cfg
    namespace: jx
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.VERSION}}'
deploy:
  kubectl: {}
 
```

Skaffold builds 2 times, as I understand caching from remote is not working.
