### ISSUE TITLE
Option "cacheFrom" does not work for local builds

### ISSUE THREAD

**Issue by petr-buchin** [GoogleContainerTools/skaffold#3871]
### Expected behavior
I expect option `cacheFrom` to work with local Docker build.

### Actual behavior
Option `cacheFrom` does not use cache.
Image, specified in `cacheFrom` option is **already pulled**.
If I run `docker build` with `--cache-from` option - cache is used.
But if I run `skaffold build` with `cacheFrom` in `skaffold.yaml` - cache is not used.

### Information

- Skaffold version: v1.6.0-docs
- Operating system: MacOs Catalina
- Contents of skaffold.yaml:

```yaml
kind: Config
apiVersion: skaffold/v1
metadata:
  name: platform
build:
  artifacts:
  - context: .
    docker:
      dockerfile: skaffold/docker/dummy.Dockerfile
    image: myorgname/dummy
  local:
    push: false
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  helm:
    releases:
    - chartPath: charts/myorgname
      name: dyn
      values:
        dummy.image: myorgname/dummy
      valuesFiles:
      - charts/myorgname/values/file1.yaml
      - charts/myorgname/values/file2.yaml

profiles:
- name: frontend
  patches:
  - op: add
    path: /build/artifacts/-
    value:
      context: ../frontend
      docker:
        cacheFrom:
        - docker.pkg.github.com/myorgname/frontend/frontend:64c37411f8ec9956c50a4ef4368b07c88759866e
        dockerfile: build/Dockerfile
      image: docker.pkg.github.com/myorgname/frontend/frontend
  - op: add
    path: /deploy/helm/releases/0/values/frontend.image
    value: docker.pkg.github.com/myorgname/frontend/frontend

```

### Steps to reproduce the behavior
Command: `skaffold build -p frontend`
