### ISSUE TITLE
debug: spec.template.spec.containers[0].env[0].valueFrom: may not be specified when 'value' is not empty

### ISSUE THREAD

**Issue by robcanini** [GoogleContainerTools/skaffold#3872]
Executing `skaffold debug` causes the error below:

`spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when 'value' is not empty`

### Information

Skaffold: v1.5.0
OS: macOS Catalina 10.15.3
Docker desktop: 2.2.0.4
Docker engine: 19.03.8
Kubernetes: v.1.15.5

skaffold.yaml
```yaml
apiVersion: skaffold/v2alpha4
kind: Config

metadata:
  name: app

build:
  artifacts:
    - image: app-java
      jib:
        project: app
        type: maven

deploy:
  kustomize:
    paths: ["."]
```

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local

resources:
  - ./app-java.deployment.yaml
  - ./namespace.yaml

configMapGenerator:
  - name: app-java-config
    files:
      - application.properties

secretGenerator:
  - name: app-java-env
    envs:
      - jvm.env
```

app-java.deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-java
  template:
    metadata:
      labels:
        app: app-java
    spec:
      volumes:
        - name: app-config
          configMap:
            name: app-java-config
      containers:
        - name: server
          image: app-java
          env:
            - name: JAVA_TOOL_OPTIONS
              #value: -Xmx512m -Xms512m -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
              valueFrom:
                secretKeyRef:
                  name: app-java-env
                  key: jvm-args
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: app-config
              mountPath: /app/resources/application.properties
              subPath: application.properties
```

jvm.env
```
jvm-args=-Xmx512m -Xms512m -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
```

Using the pinpointed value in JAVA_TOOL_OPTIONS env value injection ( the commented line ) instead of secretKeyRef solves the problem. I think that skaffold debug command translate the yaml without taking some consideration about.
This is true because executing `skaffold run` does not give any error.
