### ISSUE TITLE
Allow deployment of specific artifacts with a flag list

### ISSUE THREAD

**Issue by giladsh1** [GoogleContainerTools/skaffold#3881]
It would be awesome, if you could add a flag to skaffold, which will filter the current deployed articfacts.
I have a couple of dozens of micro services.
when developing, I only wish to deploy a few at a time, not always all them.

I suggest adding a flag like `--deploy-artifacts` of type list, which will allow the user to specifically select which services will get deployed. 
skaffold should automatically figure out which artifacts are not relevant for this deployment, and automatically ignore their k8s manifest.  

I suggest the command - 
`skaffold dev -p=local --deploy-artifacts=service-1,service-3,service-6`

for the following yaml example file - 
```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    push: false
  artifacts:

    - image: eu.gcr.io/infinipoint/service-1
      docker:
        dockerfile: backend/service-1
    - image: eu.gcr.io/infinipoint/service-2
      docker:
        dockerfile: backend/service-2
    - image: eu.gcr.io/infinipoint/service-3
      docker:
        dockerfile: backend/service-3
    - image: eu.gcr.io/infinipoint/service-4
      docker:
        dockerfile: backend/service-4
    - image: eu.gcr.io/infinipoint/service-5
      docker:
        dockerfile: backend/service-5
    - image: eu.gcr.io/infinipoint/service-6
      docker:
        dockerfile: backend/service-6

profiles:
  - name: local
    build:
      local:
        push: false
    deploy:
      kubectl:
        manifests:
          - k8s/local/**
```

**Comment by briandealwis** [comment]
Thanks @giladsh1 — we have something like this on our radar, which we've been calling _modules_.  We're busy on other work at the moment, but hope to get to this sooner than later.

**Comment by balopat** [comment]
@giladsh1 do you mind commenting on the design doc for modules: http://tinyurl.com/skaffold-modules? Thank you!

**Comment by gsquared94** [comment]
This can be supported now by defining `multiple configs`. Take a look at these [tutorials](https://skaffold.dev/docs/tutorials/config-dependencies/)

It'll essentially involve splitting the above config into more granular service level configs.
```yaml
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: svc1
build:
  artifacts:
    - image: eu.gcr.io/infinipoint/service-1
      docker:
        dockerfile: backend/service-1
deploy:
   kubectl:
     manifests:
       - k8s/local/*.svc1.yaml

---

apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: svc2
build:
  artifacts:
    - image: eu.gcr.io/infinipoint/service-2
      docker:
        dockerfile: backend/service-2
deploy:
   kubectl:
     manifests:
       - k8s/local/*.svc2.yaml
```

Then you can selectively run `skaffold dev -m svc1` or `skaffold dev -m svc1 -m svc2`, etc.
