### ISSUE TITLE
GitLab deploy breaks in v1.6: “system:serviceaccount:default:default” cannot create deployments.apps in the namespace

### ISSUE THREAD

**Issue by OliJeffery** [GoogleContainerTools/skaffold#3884]
### Expected behavior

When pushing to gitlab master, Skaffold runs and installs our app. This is working correctly on 1.5

### Actual behavior

Most of the deployment goes fine, but once it gets to "waiting for deployments to stabilize", there's a permissions issue and the service account created doesn't have access to the deployments, getting the error `deployments.apps is forbidden: User “system:serviceaccount:default:default” cannot create deployments.apps in the namespace`

### Information

- Skaffold version: version 1.6.0
- Operating system: Via GitLab
- Contents of skaffold.yaml:

```yaml
<apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: watchdog-frontend
build:
  artifacts:
  - image: registry.gitlab.com/3whitehats/watchdog-frontend

deploy:
  kubeContext: minikube
  kubectl:
    manifests:
    - deployment/watchdog-secret.yaml
    - deployment/frontend-deployment.yaml
    - deployment/frontend-ingress.yaml
    - deployment/frontend-service.yaml

profiles:
  - name: prod
    deploy:
      kubeContext: gitlab-deploy
      kubectl:
        manifests:
        - deployment/watchdog-secret.yaml
        - deployment/frontend-deployment.yaml
        - deployment/frontend-ingress.yaml
        - deployment/frontend-service.yaml
  - name: staging
    deploy:
      kubeContext: gitlab-deploy
      kubectl:
        manifests:
          - deployment/watchdog-secret.yaml
          - deployment/frontend-deployment.yaml
          - deployment/frontend-staging-ingress.yaml
          - deployment/frontend-service.yaml
>
```
Downgrading to version 1.5.0 allowed us to deploy again.
