### ISSUE TITLE
Skaffold dev on a new machine does not download images from registry.

### ISSUE THREAD

**Issue by arlyon** [GoogleContainerTools/skaffold#3886]
### Expected behavior

I have some microservices. I run `skaffold build` on my machine (or in CI), the images are uploaded, and then when others who depend on them (ie. frontend team) rebases, they can run `skaffold dev`, it pulls the images I pushed, and they are able to keep working immediately.

### Actual behavior

Images are 'not found' and built instead. It appears that skaffold doesn't check docker hub and as such, everyone who rebases needs to either manually pull the updated images from docker or wait for it to build. This means rebases are quite expensive (taking around an hour if building).

### Information

- Skaffold version: 1.6.0
- Operating system: images built and pushed on macOS, other machines (that have to rebuild) are windows and centOS

<details><summary>skaffold.yaml</summary>
<p>

```yaml
apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: workout
deploy:
  kustomize:
    paths: 
    - kubernetes/overlays/development
build:
  artifacts:
  - image: arlyon/workout-server
    context: ./server/
  - image: arlyon/workout-learn
    context: ./learn/
  local:
    push: true
profiles:
- name: production
  deploy:
    kustomize:
      paths: 
      - kubernetes/overlays/production
  activation:
  - kubeContext: google-cloud
- name: traefik
  deploy:
    kustomize:
      paths:
      - kubernetes/overlays/development
      - kubernetes/overlays/traefik
portForward:
- resourceType: service
  resourceName: server
  address: 0.0.0.0
  port: 8080
```

</p>
</details>

### Steps to reproduce the behavior

I don't think this is unique to my project. I'm just not sure why this wouldn't happen. I would expect the cache first check locally, then to fall back and check docker hub, and finally resort to building but it seems like that step is being missed out. Note that after deleting the images on the machine that built them, they _are_ 'found remotely' from docker hub, but not on other machines
