### ISSUE TITLE
Skaffold dev doesnt not detect changes in subfolders for bazel targets

### ISSUE THREAD

**Issue by Caribosaurus** [GoogleContainerTools/skaffold#3896]
### Expected behavior
I expect skaffold dev to detect changes in subfolders.

### Actual behavior
Changes are only detected at the top level.

### Information

- Skaffold version: 1.6.0-docs
- Operating system: Ubuntu
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: api-image
      bazel:
        target: //backend/src:docker_image.tar
      context: backend/src

    - image: app1-image
      bazel:
        target: //app1:docker_image.tar
      context: app1/src

    - image: app2-image
      bazel:
        target: //app2:docker_image.tar
      context: app2/src

portForward:
  - resourceType: pod
    resourceName: api
    port: 3000
    localPort: 3000

  - resourceType: pod
    resourceName: app1
    port: 13771
    localPort: 13771

  - resourceType: pod
    resourceName: app2
    port: 8080
    localPort: 8080

```
