### ISSUE TITLE
comma in helm value causes it to be truncated

### ISSUE THREAD

**Issue by Mister101** [GoogleContainerTools/skaffold#3898]
### Expected behavior
If I have the following in my skaffold.yaml file:
```yaml
deploy:
  helm:
    releases:
    - name: my-app
      ...
      setValues:
        someKey: "myvalue,other"
```

I expect the value that gets sent to Helm is someKey: "myvalue,other"

### Actual behavior

The value that gets sent to Helm is someKey: "myvalue", with ",other" being cut off.

### Information

- Skaffold version: v1.6.0-docs
- Operating system: Windows 10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: myapp
      context: ./myapp
      docker:
        dockerfile: Dockerfile
        buildArgs:
          arg: "{{.SOME_ENV_VAL}}"
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: myapp
        chartPath: ./myapp/
        valuesFiles:
          - myapp//values-dev.yaml
        values:
          imageName: myapp
        setValues:
          someKey: "myvalue,other"
```

### Steps to reproduce the behavior

Run `skaffold run` that deploys a helm release using "setValues" to set a value with a comma in it.
