### ISSUE TITLE
Failed to build vs push image to GCR (failed to build: build failed - UNAUTHORIZED)

### ISSUE THREAD

**Issue by consokodev** [GoogleContainerTools/skaffold#3899]
### Expected behavior
Build and push image to private GCR

### Actual behavior
I want to build vs push docker image to private gcr on gitlab runner. I could run successfully with Minikube (I use the same service account). However, it show lack of permission:

```
time="2020-04-01T17:21:57Z" level=fatal msg="failed to build: build failed: building time="2020-04-01T17:21:57Z" level=fatal msg="failed to build: build failed: building [gcr.io/project/my-image]: getting image: GET https://gcr.io/v2/project/my-image/manifests/2c46f1d: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication"
```

### Information

- Skaffold version: v1.6.0
- Operating system: k8s gitlab runner 
- Contents of skaffold.yaml: v1.6.0

```
❯ kb get secret | grep kaniko-secret
kaniko-secret                      Opaque                                1      31h
```

```yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: gcr.io/project/my-image
    kaniko: {}
  cluster:
    pullSecretName: kaniko-secret
    namespace: gitlab-managed-apps
deploy:
  kubectl:
    manifests:
    - cronjob.yaml
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...
