### ISSUE TITLE
Kaniko + Container Structure Tests doesn't work

### ISSUE THREAD

**Issue by kevinleturc** [GoogleContainerTools/skaffold#3907]
### Expected behavior
container-structure-tests works as expected when image is built with Kaniko

### Actual behavior

container-structure-tests failed with the following log:
```bash
=====================================
====== Test file: non_root.yml ======
=====================================
=== RUN: root exist and has correct permission
--- FAIL
Error: error setting env vars: Error creating container: no such image
```

### Information

- Skaffold version: 1.5
- Operating system: Unix / Jenkins X
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/{{.ORG}}/{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: my-example
      context: docker/my-example
      kaniko:
        dockerfile: Dockerfile
        buildContext:
          localDir: {}
        buildArgs:
          VERSION: "{{.VERSION}}"
test:
  - image: my-example
    structureTests:
      - './docker/my-example/test/*'

```

Some clue: as Kaniko builds the Docker image without putting it in the local Docker daemon, and thus container-structure-tests don't find it.

Passing `--pull` to container-structure-tests command could do the work, but it's not working in my case due to this error:
```
FATA[0000] error pulling remote image docker.packages.nuxeo.com/nuxeo/nuxeo:11.x@sha256:924dde3e2eca1f41a78061d25dba6b11960dc30cc0b3694679926919788908a1: API error (500): Get https://docker.packages.nuxeo.com/v2/nuxeo/nuxeo/manifests/sha256:924dde3e2eca1f41a78061d25dba6b11960dc30cc0b3694679926919788908a1: no basic auth credentials
```
Which sounds like container-structure-tests doesn't handle authenticated docker registry.

### Steps to reproduce the behavior

The issue can be reproduced with any Dockerfile as the issue seems to be the non-existence of image in the Docker daemon.
