### ISSUE TITLE
Exclude subdirectories from being watched jib build

### ISSUE THREAD

**Issue by edh-31** [GoogleContainerTools/skaffold#3913]
Hello.

Currently I am triying to set up skaffold to deploy a multi module REST API (https://github.com/GoogleContainerTools/skaffold/tree/master/examples/jib-multimodule). This API consits of three modules:

commons module (models), services (implementation) module and api module (openapi documentation and controllers)

And they are related as follows: The services module use the commons module and the API module use the services module

commons <- services
services <- api

Everything is functioning correctly, however when skaffold detects a change on restapi-commons or restapi-services it automatically redeploys the project on Kubernetes. Is it possible to configure skaffold to only listen changes on the folder restapi-api? But at the same time build all three projects?

Folder structure:

```
k8s/
restapi-api/
restapi-commons/
restapi-services/
skaffold.yaml
pom.xml
```

- Skaffold version: v1.6.0-docs
- Operating system: elementary os
- Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: restapi
build:
  tagPolicy:
    dateTime:
      format: 20060102t150405
  artifacts:
  - image: gcr.io/myproject/rest-test-api
    jib:
      project: com.edh.platform:rest-api
deploy:
  kubectl:
    manifests:
    - k8s/rest-api.yaml
```

Thank you
