### ISSUE TITLE
jib-multimodule build failed manifest unknown

### ISSUE THREAD

**Issue by loveyang2012** [GoogleContainerTools/skaffold#3916]
I get a fata error about jib-multimodule  with skaffold build, like this:

![01](https://user-images.githubusercontent.com/24237714/78379700-5d45f000-7605-11ea-98c7-28db1cad35dd.png)

- Skaffold version: 1.6
- Operating system: centos7.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  tagPolicy:
    dateTime:
      format: "2006-01-02-15-04-05"
      timezone: "Local"
  artifacts:
  - image: 10.23.69.9:8080/cjxqswap/manage
    jib:
      project: ../push-center-manage
      args: ["-Dmaven.test.skip=true","-DsendCredentialsOverHttp=true"]
```
