### ISSUE TITLE
JsonPatch value should not be an object

### ISSUE THREAD

**Issue by tete17** [GoogleContainerTools/skaffold#3932]
### Information
According to this https://github.com/GoogleContainerTools/skaffold/blob/0a3254e252b7cadc907f75018088d78f48fb7ada/docs/content/en/schemas/v2beta1.json#L1342 a json patch value must always be an `object`.

This conflicts with the "official" definition of a json patch according to http://json.schemastore.org/json-patch. 

Sometime when adding into a map it just needs to be a string or any other json object.

```yaml
...
deploy:
  helm:
    releases:
      - name: foo
        chartPath: k8s/helm/bar
        values:
          foo: "bar"

profiles:
  - name: dev
    patches:
      - op: add
        path: /deploy/helm/releases/0/values/environmentName
        value: "dev"
```

My Clion editor complains because of this
![image](https://user-images.githubusercontent.com/13263011/78942786-ad67fb00-7aba-11ea-8690-4cda89594fdc.png)

I would change it myself but I am not familiar with the policy on how far back we can change the json schemas or if we need to generate a new version for this change
