### ISSUE TITLE
Debugging With Skaffold

### ISSUE THREAD

**Issue by coolyrat** [GoogleContainerTools/skaffold#3934]
How to set up a debug environment in Goland?

info:
I am using cloud code plugin in goland to play.
```bash
~ » skaffold version
v1.7.0
```

skaffold.yaml
```yaml
apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: app
build:
  local: {}
  artifacts:
    - image: app
      custom:
        buildCommand: "make dev_docker"
        dependencies:
          paths:
            - cmd/app
            - sdk
            - internal

deploy:
  kubectl:
    manifests:
      - ./k8s/k8s-deployment.yaml

```
makefile
```makefile
dev_docker:
	go build -gcflags='all=-N -l' -o ./tmp/app ./cmd/app/main.go
	docker build -t app -f Dockerfile ./tmp
```

```Dockerfile
FROM gcr.io/distroless/base
ENV GOTRACEBACK=all
COPY app /app
EXPOSE 3000 3001

CMD ["./app"]
```

I could start up the server, but I am expecting the output below when I  run the "develop on kubernetes" in the debug mode provided by the cloud code plugin.
```
[app-577bc59f76-n9w4w install-go-support] Installing runtime debugging support files in /dbg
[app-577bc59f76-n9w4w install-go-support] Installation complete
```
