### ISSUE TITLE
helm3: first deploy: matching build results to chart values: no build present for ...

### ISSUE THREAD

**Issue by abh** [GoogleContainerTools/skaffold#3948]
### Expected behavior

Application deploys

### Actual behavior

Errors out with 

```
Tags used in deployment:
 - ntppool-dev -> harbor.ntppool.org/ask/ntppool-dev:13159918-dirty@sha256:11fe228e960fc925a63a481cdf77beac2ee5e7aa9614ad9d560af67d42ff21eb
Starting deploy...
Helm release ntppool not installed. Installing...
FATA[0008] deploying "ntppool": release args: matching build results to chart values: no build present for harbor.ntppool.org/ask/ntppool-dev
```

### Information

- Skaffold version: v1.7.0
- Operating system: macOS 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ntppool-dev
      kaniko:
        cache: {}
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "lib/**"
          - "docs/**"
          - "bin/**"

  cluster:
    pullSecretName: "harbor-registry"
    dockerConfig:
      secretName: skaffold-cfg
    namespace: kntp

deploy:
  helm:
    releases:
      - name: ntppool
        remote: true
        chartPath: ntppool/ntppool
        wait: true
        valuesFiles:
          - /Users/ask/src/ntppool-k8s/dev-values-kind.yaml
        values:
          image.image: harbor.ntppool.org/ask/ntppool-dev
```

### Steps to reproduce the behavior

1.  https://github.com/abh/ntppool (skaffold branch)
2. helm chart in https://github.com/ntppool/charts/tree/master/charts/ntppool
2. `skaffold dev`

Or alternatively:

```
cat <<EOF > build-state.json
{
  "builds": [
    {
      "imageName": "ntppool-dev",
      "tag": "harbor.ntppool.org/ask/ntppool-dev:13159918-dirty@sha256:11fe228e960fc925a63a481cdf77beac2ee5e7aa9614ad9d560af67d42ff21eb"
    }
  ]
}
EOF

$ skaffold deploy -a build-state.json
Tags used in deployment:
 - ntppool-dev -> harbor.ntppool.org/ask/ntppool-dev:13159918-dirty@sha256:11fe228e960fc925a63a481cdf77beac2ee5e7aa9614ad9d560af67d42ff21eb
Starting deploy...
Helm release ntppool not installed. Installing...
FATA[0008] deploying "ntppool": release args: matching build results to chart values: no build present for harbor.ntppool.org/ask/ntppool-dev
```

**Comment by abh** [comment]
FWIW, I also tried with

```
        setValues:
          image.image: harbor.ntppool.org/ask/ntppool-dev
```

It's not obviously documented anywhere how skaffold passes the tag to helm.

In [the example](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/helm-deployment) the README uses `image: registry/image`, but as the [values.yaml](https://github.com/GoogleContainerTools/skaffold/blob/master/examples/helm-deployment/skaffold-helm/values.yaml) says (but doesn't use):

```
# This is the helm convention on declaring images
# image:
#   repository: nginx
#   tag: stable
#   pullPolicy: IfNotPresent
```

... is putting the image variable in "image: " at the top level a requirement to use skaffold?

**Comment by abh** [comment]
with `-v=debug`:

```
Tags used in deployment:
 - ntppool-dev -> harbor.ntppool.org/ask/ntppool-dev:13159918-dirty@sha256:2c966a62aa67aa240aeb829144438c1733a35ef65bb91c0e7898f1e8ddef156d
Starting deploy...
DEBU[0028] Running command: [helm version]
INFO[0029] Deploying with helm v3.1.2 ...
DEBU[0029] Executing template &{envTemplate 0xc000524100 0xc000536640  } with environment map[...]
DEBU[0029] Running command: [helm --kube-context dura get all ntppool]
DEBU[0030] Executing template &{envTemplate 0xc000628a00 0xc00004d140  } with environment map[...]
Cleaning up...
DEBU[0030] Executing template &{envTemplate 0xc000628b00 0xc00004d280  } with environment map[...]
DEBU[0030] Running command: [helm --kube-context dura delete ntppool]
release "ntppool" uninstalled
INFO[0084] Cleanup complete in 53.898523021s
FATA[0084] exiting dev mode because first deploy failed: deploying "ntppool": release args: matching build results to chart values: no build present for harbor.ntppool.org/ask/ntppool-dev
```

**Comment by aeneasr** [comment]
I get the same issue just defining a random value. This helm deploy config

```
      -
        name: kratos
        chartPath: ../k8s/helm/charts/kratos
        namespace: project-ory
        version: v0.2.0
        valuesFiles:
          - stack/projects/dist/ory/values.kratos.yaml
          - skaffold/kratos/override.values.yaml
        imageStrategy:
          helm: {}
        values:
          # has no function
          foobarbaz: "barbazbar"
```

causes

```
time="2020-04-21T18:48:07+02:00" level=warning msg="deployer cleanup: deleting \"kratos\": exit status 1"
time="2020-04-21T18:48:07+02:00" level=fatal msg="exiting dev mode because first deploy failed: deploying \"kratos\": release args: matching build results to chart values: no build present for barbazbar"
```

When I omit the `foobarbaz ` key it works just fine!
