### ISSUE TITLE
local insecure registry: http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by reggev** [GoogleContainerTools/skaffold#3951]
### Expected behavior
Running ```skaffold run```  should create the images according to the yaml files and push them to a local registry iv'e set up.
The registry is the one provided as an add-on on minikube.

### Actual behavior
I get an error 
```
Generating tags...
 - 192.168.64.3:5000/api -> 192.168.64.3:5000/api:7279b99-dirty
 - 192.168.64.3:5000/curator -> 192.168.64.3:5000/curator:7279b99-dirty
Checking cache...
 - 192.168.64.3:5000/api: Found. Pushing
The push refers to repository [192.168.64.3:5000/api]
FATA[0000] failed to build: pushing image: Get https://192.168.64.3:5000/v2/: http: server gave HTTP response to HTTPS client
```

### Information
This is a nodeJs project built as a monorepo, each package has it's own docker file and I set context for each to the root directory (I share packages between the different services.)

I can manually deploy to minikube using the exact same configuration files using Kubectl and everything runs as expected, I cannot get it to run using scaffold run

I tried shutting down useDockerCli, and tried running it with --cache-artifacts=false and it didn't help.

- Skaffold version: v1.7.0
- Operating system: MacOS Catalina
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: project-name
build:
  insecureRegistries:
    - 192.168.64.3:5000
  local:
    push: true
    useDockerCLI: false
  artifacts:
    - image: 192.168.64.3:5000/api
      context: ./
      docker:
        dockerfile: packages/api/Dockerfile
    - image: 192.168.64.3:5000/curator
      context: ./
      docker:
        dockerfile: packages/curator/Dockerfile
deploy:
  kubectl:
    manifests:
      - packages/services/api/deployment.yaml
      - packages/services/api/service.yaml
      - packages/services/curator/deployment.yaml
      - packages/services/curator/service.yaml
      - packages/services/postgres/deployment.yaml
      - packages/services/postgres/persistentVolume.yaml
      - packages/services/postgres/persistentVolumeClaim.yaml
      - packages/services/postgres/service.yaml
      - packages/services/zookeeper/claims.yaml
      - packages/services/zookeeper/deployment.yaml
      - packages/services/zookeeper/service.yaml
      - packages/services/zookeeper/volumes.yaml
```
