### ISSUE TITLE
dev: unable to hit port without --port-forward=true (v1.7.0 change?)

### ISSUE THREAD

**Issue by mhn10** [GoogleContainerTools/skaffold#3953]
Whenever I'm running skaffold dev, I'm not able to connect to the service. I was able to do this before updating skaffold to version 1.7.0
I'm also able to debug through Cloud Code for Intellij, Version 20.4.1 pointed to skaffold executable in plugin setting (usr/local/bin).
I was able to hit my endpoint previously, but now its not accessible when i try running the app through terminal, but only through cloud code plugin. 
I also tried explicitly giving port forward in skaffold.yaml but still was not able to reach the endpoint.

### Expected behavior

Able to hit localhost:10130/health

### Actual behavior

Page not found / Unable to connect

### Information

- Skaffold version: 1.7.0
- Operating system: MacOS Mojave ver 10.15.4
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: service-1
build:
  artifacts:
    - image: entity-im
      jib:
        project: com.company.app:service-1
        args:
          - -Dmaven.test.skip
deploy:
  kubectl:
    manifests:
      - service-1-service.yaml
      - config/QA/service-1-db-service.yaml
      - config/QA/service-1-service-config-map.yaml
      - config/QA/service-1-service-deployment.yaml
```

### Steps to reproduce the behavior
* skaffold dev
* hitting known endpoint

I'm able to manually perform `kubectl apply` and port forward to the node and access the endpoint.
