### ISSUE TITLE
Improve documentation around image handling for helm deployments

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#3959]
Skaffold has several quirks around how and where to declare your image name, for example currently skaffold requires users to declare their image name as a value in the deploy stanza in the skaffold.yaml:
```yaml
deploy:
  helm:
    releases:
    - name: release
      values:
        image: my_image
```

we should improve the helm documentation to detail the intricacies of using skaffold so there's less confusion.
