### ISSUE TITLE
profiles which patch helm values cause: matching build results to chart values: no build present for bar

### ISSUE THREAD

**Issue by antiBaconMachine** [GoogleContainerTools/skaffold#3963]
### Expected behavior

Profiles can patch a helm values object

### Actual behavior

Profiles which patch a helm values object cause deploy failures

### Information

- Skaffold version: 1.7.0
- Operating system: OSX
- Contents of skaffold.yaml:

https://github.com/antiBaconMachine/skaffold/blob/c9486f9d2b7519c408e49e06829cc5e31aec2d18/examples/profile-patches/skaffold.yaml
```yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  # only build and deploy "base-service" on main profile
  artifacts:
  - image: skaffold-base
    context: base-service
deploy:
  kubectl:
    manifests:
      - 'base-service/*.yaml'

profiles:
  - name: hello
    patches:
      - op: add
        path: /build/artifacts/1
        value:
          image: skaffold-hello
          context: hello-service
      - op: add
        path: /deploy/kubectl/manifests/1
        value: 'hello-service/*.yaml'

  - name: world
    patches:
      - op: add
        path: /build/artifacts/1
        value:
          image: skaffold-world
          context: world-service
      - op: add
        path: /deploy/helm
        value:
          releases:
            - name: world
              chartPath: world-service/helm
              values:
                foo: bar
                image: skaffold-world
```

### Steps to reproduce the behavior

1. https://github.com/antiBaconMachine/skaffold/pull/1
2. `skaffold dev -p hello -p world`
3. `FATA[0000] exiting dev mode because first deploy failed: deploying "world": release args: matching build results to chart values: no build present for bar`

Greetings, thanks for your work on this project, very useful tool. I've left some inline comments on the reproduction, but essentially my intent is to use skaffold profiles to alter helm values so if there is some other way I should be doing this please point me in that direction.

Many thanks

**Comment by briandealwis** [comment]
Hi @antiBaconMachine.  Your skaffold.yaml is attempting to add a node to `/deploy/helm`, which doesn't exist:

```yaml
- op: add
  path: /deploy/helm
  value:
    releases:
```

If you change it to:
```yaml
- op: add
  path: /deploy
  value:
    helm:
      releases:
```

then you should get your helm deployer moving.
