### ISSUE TITLE
JibArtifact & KanikoArtifact with kubernetes namespace cause invalid skaffold config

### ISSUE THREAD

**Issue by lotharschulz** [GoogleContainerTools/skaffold#3981]
### Expected behavior

Please respect Kubernetes namespace setting in combination with _jib_ in skaffold.yaml:
```yaml
...
build:
  artifacts:
...
  cluster:
    namespace: mynamespace
...
```

### Actual behavior

skaffold.yaml:
```yaml
apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
    - image: myimage
      jib: {}
  cluster:
    namespace: mynamespace
deploy:
  kubectl:
    manifests:
      - k8s-*
```

terminal:
```
$ skaffold dev 
FATA[0000] creating runner: invalid skaffold config: only one element in set artifact can be set. got JibArtifact and KanikoArtifact
```
### Information

- Skaffold version: 1.8.0
- Operating system: mac os 10.15.3
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
    - image: myimage
      jib: {}
  cluster:
    namespace: mynamespace
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. create a Kubernetes namespace `kubectl create namespace mynamespace` 
2. skaffold and jib setup as in _skaffold.yaml_ above (more details: [https://github.com/lotharschulz/ktorjib -- Skaffold -> EKS, ECR on AWS](https://github.com/lotharschulz/ktorjib/blob/update202004/README.md#skaffold---eks-ecr-on-aws))
3. `skaffold dev`
