### ISSUE TITLE
add NODEJS_VERSION on debug detection logic

### ISSUE THREAD

**Issue by csantanapr** [GoogleContainerTools/skaffold#4003]
### Expected behavior

The command `skaffold debug` to work with nodejs ubi images from redhat 

### Actual behavior

The command `skaffold debug` not detecting debugging runtime for nodejs

### Information

- Skaffold version: 1.8.0
- Operating system: MacOS Catalina
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta2
kind: Config

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}"
      artifacts:
        - image: csantanapr/nodejs-k8s-think2020
          context: ../1-containers
          docker:
            buildArgs:
              ENV: development
          sync:
            infer:
              - "sever/**/*.js"

build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}"
  artifacts:
    - image: csantanapr/nodejs-k8s-think2020
      context: ../1-containers
```

```Dockerfile
FROM registry.access.redhat.com/ubi8/nodejs-12
# Create app directory
WORKDIR /opt/app-root/src

COPY package*.json ./

RUN npm ci

COPY --chown=1001:0 src src
RUN chmod -R g=u src

EXPOSE 8080

ARG ENV=production
ENV NODE_ENV $ENV
CMD node src/app.js
```

### Steps to reproduce the behavior

1.   git clone https://github.com/csantanapr/think2020-nodejs
2. cd 2-kubernetes/
3. `skaffold debug`

workaround to add `ENV NODE_VERSION $NODEJS_VERSION` to Dockerfile

Would it be possible to add logic if `NODE_VERSION` is not found to check for `NODEJS_VERSION` ?
I think this is the code to update https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/debug/transform_nodejs.go#L59-L60
