### ISSUE TITLE
Skaffold fails to push to local private docker registry

### ISSUE THREAD

**Issue by raul1991** [GoogleContainerTools/skaffold#4011]
I ran a local docker registry and would want to use it with skaffold so it can push images to it but it fails.

### Expected behavior
It should be able to push to the local registry

### Actual behavior
This fails with the error

> Get http://localhost:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused

### Information

- Skaffold version: 1.8.0
- Operating system: macos 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:v1.0.0"
  artifacts:
  - image: rest-api
    context: ./rest-api
  - image: grafana
    context: ./grafana
  - image: prometheus
    context: ./prometheus
  local:
    push: true
deploy:
  kubectl:
    manifests:
     - kustomizer/minikube/deployments/*.yaml
     - kustomizer/minikube/services/*.yaml
     - kustomizer/minikube/configmaps/*.yaml
     - kustomizer/minikube/volumes/pvc/*.yaml
     - kustomizer/minikube/volumes/pv/*.yaml
profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
    deploy:
      kubectl:
        manifests:
          - kustomizer/minikube/deployments/*.yaml
          - kustomizer/minikube/services/*.yaml
          - kustomizer/minikube/configmaps/*.yaml
          - kustomizer/minikube/volumes/pvc/*.yaml
          - kustomizer/minikube/volumes/pv/*.yaml

```

### Steps to reproduce the behavior

1. Clone https://github.com/raul1991/whatsapptracker
2. `docker run -d -p 5000:5000 --restart=always --name registry registry:2`
2. `skaffold dev --port-forward --default-repo=localhost:5000`
