### ISSUE TITLE
jib build failed when there is no docker dameon

### ISSUE THREAD

**Issue by dwctua** [GoogleContainerTools/skaffold#4035]
### Expected behavior
jib build should not inspect image using local docker daemon if not using local docker build
### Actual behavior
jib build failed after image built and pushed to remote successfully 

### Information

- Skaffold version: version:1.8.0
- Operating system: ubuntu 18.04  (windwos wsl 2)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
  - image: skaffold-jib
    # jib: {}
    custom:
      buildCommand: mvn package jib:build -Dimage=xxx/test:v1 -Djib.to.auth.username=xxx -Djib.to.auth.password=xxx
```

### Steps to reproduce the behavior

1. make sure there is no docker running locally
2. a clonable repository with the sample skaffold project
https://github.com/GoogleContainerTools/skaffold/tree/master/examples/jib
3. update the skaffold.yaml using the sample yaml listed above
4.  run `skaffold build`
5.  image is built and pushed to the registry
[INFO] Built and pushed image as xxxtua/test:v1
6. But getting the following error and failed the build.
FATA[0011] build failed: building [skaffold-jib]: build artifact: inspecting image: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
