### ISSUE TITLE
Enhance git tagger to tag with latest git tag or other formats

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#407]
The git tagger currently doesnt take any parameters but should take some to configure how we resolve  image tags from git history. Some options I'd like to see, not sure if they should be exposed as bool parameters or a string enum.

```yaml
# tags with the full commit sha256 instead of short
type: longCommit

# uses the most recent tag
type: tag
```
