### ISSUE TITLE
Image not recognized in crd k8s manifest

### ISSUE THREAD

**Issue by simonfr** [GoogleContainerTools/skaffold#4081]
When I try to launch `skaffold dev` with custom crd image field in manifest is not found by skaffold.

### Expected behavior
Image should be found by skaffold

### Actual behavior
Image not found so --> Not used by the deployment error

### Information

- Skaffold version: v1.8.0
- Operating system: Ubuntu 18.04 LTS
- Contents of skaffold.yaml: 

```yaml
apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
    - image: localhost:5000/myimage
      context: .
      custom:
        buildCommand: faas-cli build -f api.yml
  local:
    push: true
deploy:
  kubectl:
    manifests:
      - "k8s/*.yaml"
portForward:
- resourceType: Service
  resourceName: gateway
  namespace: openfaas
  port: 8080
```

- Contents of k8s/function.yaml:
```yaml
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: myfunction
  namespace: openfaas-fn
spec:
  name: my-fn
  image: localhost:5000/myimage
```

- What I see :
```
WARN[0000] image [localhost:5000/myimage] is not used by the deployment
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold dev`

**Comment by balopat** [comment]
Thank you for opening @simonfr! 

We should think about how to whitelist CRDs in Skaffold. 
One dirty-quick fix would be to add `"Function": true` to this map: 
https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/kubectl/visitor.go#L33
However, I would like to see at least the kind to be qualified with the API group. There could be other `Function` CRDs out there, that users might not want to put through image replacement by skaffold.

**Comment by simonfr** [comment]
Thank you @balopat 
May be it's possible to add to current [skaffold.yaml](https://skaffold.dev/docs/references/yaml/) reference a new map in deploy.kubectl.transformableKinds where we can enable, disable and add parameters to existing recursivelyTransformableKinds map

**Comment by whyvez** [comment]
I've hit the same issue trying to use Skaffold to build and deploy an Argo WorkflowTemplate.

**Comment by foobarbecue** [comment]
@whyvez, I have exactly the same problem. Did you find a workaround?

**Comment by lukebond** [comment]
Perhaps an additional field in the skaffold yaml file, deploy section, that specifes some path in the YAML document where the image is referenced, e.g. for me it's spec/template/spec/containers[0].image, which happens to be the same as a deployment but given it's a CRD skaffold won't know that of course.

**Comment by whyvez** [comment]
I ran into a very similar problem in Kustomize. In Kustomize you pass in a configuration that lets you define a reference to specific features such as images using a JSON path for a custom Kind.

Here is an example of defining a reference for an Argo WorkflowTemplate.
```
images:
  - path: spec/templates/script/image
    kind: WorkflowTemplate
```

Kustomise example:
https://github.com/kubernetes-sigs/kustomize/blob/766500508c99815598cdf1a8899cedbbb7ee8c32/examples/transformerconfigs/crd/README.md

What if we could pass similar references to a configuration section of the `skaffold.yaml`.

**Comment by briandealwis** [comment]
#4249 brought in support for whitelisting based on group-kinds.  It's not extensible.

**Comment by lukebond** [comment]
Thanks @briandealwis; I think you're saying that there is already a feature that lists what gets substituted with a new image, and it isn't extensible so we can't use it.

What we're hoping for is a new feature that allows us to extend it. Does the project have any interest in implementing this? I wouldn't mind contributing a PR for it but without some input from the team on the desired approach it risks being rejected.

**Comment by briandealwis** [comment]
I apologize @lukebond, I fell behind on email and missed this.  

What I meant was … (trying to remember) … we have an implementation for whitelisting group-kinds that can be labelled/annotated with Skaffold-specific metadata and that can be image-substituted.  So providing your group-kind follows the convention of using an `image:` field  to reference container images, then adding the group-kind [to that list](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/kubectl/visitor.go#L27) should allow instances to be substituted against.  Both `openfaas.com/Function` and `argoproj.io/Workflow` both seem to follow this convention.

It makes sense to allow encoding configuration information like these group-kinds into the `skaffold.yaml`.  We have [a design proposal process](https://github.com/GoogleContainerTools/skaffold/tree/master/docs/design_proposals).  Would you mind creating a proposal and we'll get some discussion around this.  Just 2 or 3 quick sketches of ways to configure these whitelisted types in a `skaffold.yaml` would be great.

It may be worth keeping custom resources in mind that use a field name other than `image:`, even if we don't support configuring these CRs right way.

**Comment by CodeCutterUK** [comment]
Did this get submitted as a design proposal, or otherwise addressed?

**Comment by briandealwis** [comment]
No, not yet @CodeCutterUK.  Would you be interested?

**Comment by CodeCutterUK** [comment]
@briandealwis I'll certainly take a look and see if I can see a design that would work. My specific use case is being able to (re)deploy openfaas schemas

**Comment by shawnzhu** [comment]
@briandealwis I added a design proposal under #6236 to collect comments. (Although I can hack the `visitor.go` to support short term need w/ a few lines of change but realized this could be a general problem to fix)

**Comment by yhrn** [comment]
@tejal29 Can you explain how #7102 addresses this general issue? It looks like that is just about supporting a few more Argo resources.

**Comment by mm-e1** [comment]
#7102 does not address this general issue. It only addresses comment https://github.com/GoogleContainerTools/skaffold/issues/4081#issuecomment-632464048

**Comment by aaron-prindle** [comment]
Skaffold now has a way to add CRDs to it's yaml-rendering/image-replacing `allowlist`:
https://skaffold.dev/docs/tutorials/skaffold-resource-selector/

Example usage from the above docs:
```yaml
apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
    - image: my-image
      context: my-image
manifests:
  rawYaml:
  - my-manifests-*
resourceSelector:
  allow:
    - groupKind: "CustomDeployment.skaffold.dev"
      image: [".*"]
      labels: [".*"]
```

Closing as fixed, feel free to reopen if there is more to this issue or unaddressed parts of it.  Thanks
