### ISSUE TITLE
`--dry-run=client` must replace `--dry-run=true` with kubectl >= 1.18

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#4094]
See https://kubernetes.io/docs/setup/release/notes/#kubectl-1

**Comment by dgageot** [comment]
It seems to not fail yet, with kubectl 1.18. It however prints this warning:

```
DEBU[0000] Running command: [kubectl --context docker-desktop create --dry-run -oyaml -f /Users/dgageot/src/skaffold/examples/getting-started/k8s-pod.yaml]
DEBU[0001] Command output: [apiVersion: v1
kind: Pod
metadata:
  name: getting-started
  namespace: default
spec:
  containers:
  - image: skaffold-example
    name: getting-started
], stderr: W0504 16:20:18.488448   13213 helpers.go:535] --dry-run is deprecated and can be replaced with --dry-run=client.
```
