### ISSUE TITLE
regression: 'none' driver does not support 'minikube docker-env' command

### ISSUE THREAD

**Issue by foobarbecue** [GoogleContainerTools/skaffold#4115]
Looks like the fix for https://github.com/GoogleContainerTools/skaffold/issues/112 came unfixed in the update from Skaffold 1.8 to 1.9 .

### Expected behavior

Start minikube with `minikube  --vm-driver=none`
`skaffold run` works

### Actual behavior
Start minikube with `minikube  --vm-driver=none`
`skaffold run` fails with 
```
creating runner: creating builder: getting docker client: getting minikube env: running [minikube docker-env --shell none]
 - stdout:
 - stderr: "* 'none' driver does not support 'minikube docker-env' command\n": exit status 64
```
### Information

- Skaffold version: v1.9.0
- Operating system: Ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: lmmp-local/lmmp-container
deploy:
  kubectl:
    manifests:
    - https://raw.githubusercontent.com/argoproj/argo/master/manifests/install.yaml
```
