### ISSUE TITLE
[helm] regression: logs are not being tailed in 1.9.0

### ISSUE THREAD

**Issue by stanislav-zaprudskiy** [GoogleContainerTools/skaffold#4117]
### Expected behavior
`skaffold run --tail` tails containers logs

### Actual behavior
`skaffold run --tail` doesn't tail containers logs.

However! If I downgrade to 1.8.0, it tails just fine using the same command line and `skaffold.yaml`. With debug verbosity, the messages below just don't show up in 1.9.0 after port forwarding has been started:

```
INFO[0006] Streaming logs from pod: bpid-69d8988d46-k2p9d container: web
INFO[0006] Streaming logs from pod: bpid-69d8988d46-k2p9d container: init
INFO[0006] Streaming logs from pod: bpid-69d8988d46-k2p9d container: app
DEBU[0006] Running command: [kubectl --context docker-desktop logs --since=7s -f bpid-69d8988d46-k2p9d -c init --namespace default]
DEBU[0006] Running command: [kubectl --context docker-desktop logs --since=7s -f bpid-69d8988d46-k2p9d -c web --namespace default]
DEBU[0006] Running command: [kubectl --context docker-desktop logs --since=7s -f bpid-69d8988d46-k2p9d -c app --namespace default]
```

I also tried `skaffold dev --tail` without any luck.

### Information

- Skaffold version: 1.9.0
- Operating system: macOS Catalina
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha4
kind: Config
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
  artifacts:
    - image: bpid-app
      context: .
      custom:
        buildCommand: |-
          devops/skaffold/docker-build.bash devops/docker/app/Dockerfile devops/skaffold/.env.app
        dependencies:
          dockerfile:
            path: devops/docker/app/Dockerfile
            buildArgs:
              COMPOSER_AUTH: '{"gitlab-token": {"gitlab.com": "{{.GITLAB_PERSONAL_ACCESS_TOKEN}}"}}'
    - image: bpid-web
      context: .
      custom:
        buildCommand: |-
          devops/skaffold/docker-build.bash devops/docker/web/Dockerfile devops/skaffold/.env.web
        dependencies:
          dockerfile:
            path: devops/docker/app/Dockerfile

# https://skaffold.dev/docs/pipeline-stages/port-forwarding/
portForward:
  - resourceType: Service
    resourceName: bpid-mysql
    port: 3306
    localPort: 30336

profiles:
  - name: local-k8s
    activation:
      - kubeContext: microk8s
      - kubeContext: docker-desktop
      - kubeContext: docker-for-desktop
    deploy:
      helm:
        releases:
          - name: bpid
            chartPath: devops/helm-charts/laravel
            wait: true
            skipBuildDependencies: true
            imageStrategy:
              helm: {}
            values:
              image: bpid-app
              nginx.image: bpid-web
            valuesFiles:
              - devops/helm-values/local.yaml
              - devops/helm-values/local-secrets.yaml
              - devops/helm-values/local-personal.yaml
        flags:
          install:
            - --dep-up
            - --atomic
            - --timeout=120
          upgrade:
            - --install
            - --atomic
            - --cleanup-on-fail
            - --force
            - --timeout=60
```

### Steps to reproduce the behavior

Compare output of `skaffold run --tail` or `skaffold run --tail=true` in 1.9.0 and 1.8.0.
