### ISSUE TITLE
Latest docker-desktop for-mac broke skaffold

### ISSUE THREAD

**Issue by haf** [GoogleContainerTools/skaffold#4155]
### Expected behavior

For it to work, like before Docker Inc released their upgrade.

### Actual behavior

1. The latest update to docker-desktop broke the ability to use the API over the CLI

### Information

- Skaffold version: 1.9.1
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: docs
build:
  local:
    useDockerCLI: true # <<< CHANGE THIS
  artifacts:
  - image: logary/docs-web
    context: docs

deploy:
  kubeContext: docker-desktop
  kustomize:
    paths:
    - docs/k8s/test
    - examples/shared/k8s/test

portForward:
- resourceType: Service
```

### Steps to reproduce the behavior

Working

    git clone https://github.com/logary/logary
    cd logary
    skaffold dev

Non-working (`-i ''` for macOS, `-i` otherwise):

    git clone https://github.com/logary/logary
    cd logary
    sed -i '' 's/useDockerCLI[:] true/useDockerCLI: false/g' skaffold.yaml
    skaffold dev
