### ISSUE TITLE
Image for incorrect architecture being used

### ISSUE THREAD

**Issue by twss** [GoogleContainerTools/skaffold#4156]
- My development machine is a Mac. 
- My kubernetes cluster consists of 4x Raspberry Pi 4GB.
- I am using buildkit to make multi-architecture images.

I'm able to deploy the images manually with a `kubectl apply -f infra/k8s/hello-world-nginx.yaml`. Skaffold seems to be instructing the deployment to use the `linux/amd64` image, rather than the `linux/arm64` one.

### Expected behavior
Pods are started using the `linux/arm64` image.

### Actual behavior
Pods are started using the `linux/amd64` image instead.

### Information

- Skaffold version: 1.9.1
- Operating system: Mac OS X 10.15.4
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  artifacts:
    - image: twss/hello-world-nginx
      context: nginx
      custom:
        buildCommand: ../buildx.sh
```

buildx.sh
```shell
docker buildx build \
  --platform linux/amd64,linux/arm64 \
  --tag $IMAGE \
  --push \
  $BUILD_CONTEXT
```

### Steps to reproduce the behavior

1. https://github.com/twss/hello-world-nginx
2. `skaffold dev` from an `amd64` machine
3. Deploy never stabilizes
