### ISSUE TITLE
 undefined artifact type: {DockerArtifact:<nil> BazelArtifact:<nil> JibArtifact:<nil> KanikoArtifact:0xc0003150e0 BuildpackArtifact:<nil> CustomArtifact:<nil>}

### ISSUE THREAD

**Issue by tstromberg** [GoogleContainerTools/skaffold#4161]
Thanks @tejal29 I tried changing the kaniko-secret to match the hard-coded one and it works. 
However, I encountered a new issue. Here's the error code 
```bash
 - gcr.io/yuwen-cicd-demo2/ci-redisslave1: Not found. Building
Building [gcr.io/yuwen-cicd-demo2/ci-redisslave1]...
couldn't build "gcr.io/yuwen-cicd-demo2/ci-redisslave1": undefined artifact type: {DockerArtifact:<nil> BazelArtifact:<nil> JibArtifact:<nil> KanikoArtifact:0xc0003150e0 BuildpackArtifact:<nil> CustomArtifact:<nil>}
```

I did specified an artifact KainkoArtifact in my skaffold.yaml
```yaml
apiVersion: skaffold/v2beta3
kind: Config
metadata: 
  name: app-cicd-demo-
profiles:
  - name: oncluster
    build:
      artifacts:
        - image: gcr.io/yuwen-cicd-demo2/ci-redisslave1
          context: redis-slave
          kaniko: 
            dockerfile: /workspace/workspace/redis-slave/Dockerfile
```
Wondering it complains that the artiact type is not defined. @nkubala @tejal29

_Originally posted by @yuwenma in https://github.com/GoogleContainerTools/skaffold/issues/3828#issuecomment-627482534_
