### ISSUE TITLE
Skaffold Local Build says no space left on device

### ISSUE THREAD

**Issue by roccolangeweg** [GoogleContainerTools/skaffold#4177]
### Expected behavior
When running `skaffold dev` with a local builder to have the image built succesfully when there is enough space left in the docker disk (10GB free).

### Actual behavior

When building the following error occurs:

```
Found [minikube] context, using local docker daemon.
Building [project/golang]...

Sending build context to Docker daemon  201.7kB
exiting dev mode because first build failed: couldn't build "project/golang": docker build: Error response from daemon: Error processing tar file(exit status 1): write /.git/COMMIT_EDITMSG: no space left on device
```

When running `docker build .` the image is built succesfully.

There is plenty of disk space available (30GB+) and Docker also has 10GB free on the disk.

### Information

- Skaffold version: v1.9.1
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: passport-service
build:
  artifacts:
  - image: project/golang
    sync:
      manual:
        - src: "**/*.go"
          dest: .
deploy:
  kubectl:
    manifests:
    - .kube/**.yaml

```

**Comment by roccolangeweg** [comment]
Just did another test, and even after factory resetting Docker for Mac there is still the same error.

**Comment by tstromberg** [comment]
Hey @roccolangeweg - I'm pretty sure this is a minikube environment issue, which is fine because I work on that project too. Can you share the output of:

* `minikube version`
* `minikube profile list`
* `minikube ssh "df -k / /var /data"
* `kubectl get no -A`

Thanks!

**Comment by arvtiwar** [comment]
@roccolangeweg please try "minikube delete" and recreate will solve this issue or add more memory to your minikube VM. hope this will help

**Comment by gsquared94** [comment]
Closing this for now; can be reopened if recreating the minikube cluster did not do the trick.

**Comment by SebUndefined** [comment]
As a workaround, you could use Air (https://github.com/cosmtrek/air). Works pretty well with skaffold...

Dockerfile looks like follow

```Dockerfile
FROM golang:1.19-alpine as builder

EXPOSE 3000

# Enable go modules
ENV GO111MODULE=on

# Install git. (alpine image does not have git in it)
RUN apk update && apk add --no-cache git

# Set current working directory
WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

# Note here: To avoid downloading dependencies every time we
# build image. Here, we are caching all the dependencies by
# first copying go.mod and go.sum files and downloading them,
# to be used every time we build the image if the dependencies
# are not changed.

# Copy go mod and sum files
COPY go.mod ./go.mod
COPY go.sum ./go.sum

RUN go mod download

WORKDIR /app
COPY ./ ./

# Run executable
CMD ["air", "-c", ".air.toml"]
```
Skaffold declaration

```yaml
        - image: go_app
          context: go_app
          docker:
            dockerfile: Dockerfile_DEV
          sync:
            infer:
              - 'go_app/**/*.go'
```

the ```.air.toml```file

```toml
# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "CGO_ENABLED=0 GOOS=linux GOARCH=amd64  GO111MODULE=on go build -o ./tmp/main ./cmd/app/main.go"
# Binary file yields from `cmd`.
bin = "tmp/main"
# Customize binary, can setup environment variables when run your app.
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
# Watch these directories if you specified.
include_dir = []
# Watch these files.
include_file = []
# Exclude files.
exclude_file = []
# Exclude specific regular expressions.
exclude_regex = ["_test\\.go"]
# Exclude unchanged files.
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 0 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = 500 # ms
# Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
args_bin = ["hello", "world"]

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

```

I found this trick a week ago. It allows you to :
- not rebuilding the image on every change, the container/pod is still the same
- faster reloading
- avoid out of space problems

The sample config is not tested, we use it in a more complex scenario (with replace directive etc...).

WARNING

As I said we use this workaround since a week... That mean we do not have enough experience with it but so far, works pretty great...
