### ISSUE TITLE
skaffold cache check fails if :latest tag is not found

### ISSUE THREAD

**Issue by matti** [GoogleContainerTools/skaffold#4251]
```
Checking cache...
 - first: Found Remotely
 - second: Error checking cache.
failed to build: getting hash for artifact "second": getting dependencies for "second": parsing ONBUILD instructions: retrieving image "eu.gcr.io/myproject/second:latest": GET https://eu.gcr.io/v2/myproject/second/manifests/latest: MANIFEST_UNKNOWN: Failed to fetch "latest" from request "/v2/myproject/second/manifests/latest".
(exit)
```

skaffold: 1.10.1

**Comment by matti** [comment]
after I push any image as latest then it says:

```
 - second: Not found. Building
```

and builds the image

**Comment by pre** [comment]
Could be that the `latest` is a misleading message - it could be that the repository `eu.gcr.io/myproject/second` does not exist yet and pushing anything as `latest` creates the repository.

Is the error different if you create the repository by pushing any tag (eg `lolcat`)  into `second`?

**Comment by matti** [comment]
Nope, the repository has existed for months. After I pushed a random image as :latest it started to work

**Comment by briandealwis** [comment]
@matti could you please attach your `skaffold.yaml` here? Or do you have a small self-contained example?

**Comment by briandealwis** [comment]
I've been unable to reproduce this @matti.

**Comment by briandealwis** [comment]
@matti do your images use ONBUILD?  Could you provide any details on your project?

**Comment by briandealwis** [comment]
Closing, but happy to re-open if we can get an example to reproduce.  Running with `-v trace` and attaching the output would be very helpful.

**Comment by savitha-atg** [comment]
This happens when a sub-image depends on a base image whose tag doesn't exist. For example:

```
    build:
      tagPolicy:
        envTemplate:
          template: "{{ .IMAGE_TAG }}"
      googleCloudBuild:
        projectId: myproject
      artifacts:
        - image: us.gcr.io/myproject/base-image
          context: base-image
          kaniko:
            cache: {} 

        - image: us.gcr.io/myproject/sub-image
          context: sub-image
          kaniko:
            buildArgs:
              imagetag: "{{ .IMAGE_TAG }}"
            cache: {} 
          requires:
            - image: us.gcr.io/myproject/base-image
              alias: BASE_IMAGE
```

This will result in an error like this:

```
Checking cache...
 - us.gcr.io/myproject/base-image: Not found. Building
 - us.gcr.io/myproject/sub-image: Error checking cache.
getting hash for artifact "us.gcr.io/myproject/sub-image": getting dependencies for "us.gcr.io/myproject/sub-image": parsing ONBUILD instructions: retrieving image "us.gcr.io/myproject/base-image:latest": GET https://us.gcr.io/v2/myproject/base-image/manifests/latest: MANIFEST_UNKNOWN: Failed to fetch "latest" from request "/v2/myproject/base-image/manifests/latest".
```

When there is an image hierarchy where the base image and sub-image(s) are being built at the same time, `skaffold` should probably ignore cache errors for the base image when building the sub-image(s)?
