### ISSUE TITLE
KubeContext not aligned for kubectl and helm

### ISSUE THREAD

**Issue by MarcoSchaar** [GoogleContainerTools/skaffold#4274]
Hi,
I've read already similar issue #4140 but somehow observing such issue

### Expected behavior
works similar at windows with docker-desktop environment

skaffold run --profile <...> --kube-context "clustername" --kubeconfig config
skaffold run --profile <...> --kube-context clustername --kubeconfig config
skaffold run --profile <...> --kubeconfig config

### Actual behavior
kubectl or helm cannt connect to target server 

"helm version command failed"  when running with parameters
--kube-context "clustername" --kubeconfig config

### Information

- Skaffold version: version...1.10.1
- Operating system: debian 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: <repo name>
profiles:
  - name: <profile>
    deploy:
      kubeContext: "clustername"
      kubectl:
        manifests:
        - kubernetes-manifests/namespace.yaml
      helm:
        releases:
        - name: <release name>
          chartPath: https://<....>.tar.gz
          namespace: <namespace>
          valuesFiles: 
          - helm-values/values.yaml
          remote: true
```
