### ISSUE TITLE
`skaffold delete` ignoring namespace argument using Helm

### ISSUE THREAD

**Issue by MoogyG** [GoogleContainerTools/skaffold#4279]
I am using skaffold 1.8.0.

I want a default namespace for my helm chart in development, so I use 
```
deploy:
  helm:
    releases:
    - name: my-release
      namespace: my-namespace
```

Everything goes well, the chart is uninstalled if I exit `skaffold dev` or running `skaffold run` and then `skaffold delete`.

But in my CI, I need a namespace for every branch so I use `skaffold run -n my-namespace-ci-6gh81g` (the suffix is the commit sha), and the chart is created in this namespace `my-namespace-ci-6gh81g` succesfully, overriding the default `my-namespace` namespace.

But if I use `skaffold delete -n my-namespace-ci-6gh81g`, the namespace argument is ignored and I got this error : `Error: uninstall: Release not loaded: my-release: release: not found`.
It seems to be seeking the chart in the namespace `my-namespace`.
The same error appears when using `skaffold dev -n my-namespace-ci-6gh81g` and then exiting the command.

Here is my `skaffold.yaml`

```
apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name:	skaffold-test
deploy:
  helm:
    releases:
    - name: my-release
      chartPath: k8s
      namespace: my-namespace
      values:
        image: nginx
    flags:
      install:
        - "--create-namespace" 
```
