### ISSUE TITLE
remoteManifests doesn't seem to work

### ISSUE THREAD

**Issue by bs1** [GoogleContainerTools/skaffold#4286]
### Expected behavior
Use skaffold on a pre-existing manfiest

### Actual behavior
`skaffold run`, works the first time, but fails updating the image on subsequent runs. 

### Information

- Skaffold version: version...
v1.10.1

- Contents of skaffold.yaml:
(modified from the getting-started example)
```yaml
apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
  - image: gcr.io/my-project/getting-started
deploy:
  kubectl:
    remoteManifests:
    - default:pod/getting-started
```

### Steps to reproduce the behavior

1. apply a modified  `k8s-pod.yaml` with already built image
```
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
spec:
  containers:
  - name: getting-started
    image: gcr.io/my-proj/getting-started:v1.10.0-49-gdc44de4d4-dirty
```
2. run `skaffold run`. Notice that image has been updated, skaffold labels added to pod
3. modify main.go 
4. run `skaffold run` again. Notice that image hasn't been updated
