### ISSUE TITLE
skaffold run w/ kaniko can't get the image after it's been pushed on a private repo

### ISSUE THREAD

**Issue by polds** [GoogleContainerTools/skaffold#4287]
### Expected behavior

Skaffold run to be able work locally and from gitlab's ci.

### Actual behavior

Very similar to #3319. 

**Note**: This works locally! I think Gitlab is missing a docker config somehow that it's not logging.

Is there a magical location that Skaffold looks for docker credentials? I've tried `~/.docker/config.json` and `/kaniko/.docker/config.json`

I think the failure I'm seeing is on host for the gitlab ci runner and not in the kaniko builder.

---

I'm using Gitlab CI/CD and want to push _back_ to the Gitlab container registry. During a skaffold run it looks like the push succeeds, I can see the image and tags in the Gitlab registry but the skaffold process fails with an error:

> failed to build: couldn't build "registry.gitlab.com/polds/my-repo/my-image": getting image: GET https://gitlab.com/jwt/auth?scope=repository%3Apolds%2Fmy-repo%2Fmy-image%3Apull&service=container_registry: DENIED: access forbidden

I'm able to fetch from that registry throughout the whole build: the skaffold image comes from there and I can successfully pull/push from a Kaniko cache also there, it's just this last step that seems to fail.

While the build is running I can see on the Kaniko pod that the secrets are correctly mounted in the right places.

##### Possibly useful logs:

```
getting client config for kubeContext: ``
No pull secret specified. Checking for one in the cluster.
  - registry.gitlab.com/polds/my-repo/my-image: Not found. Building
 Creating kaniko secret [kaniko/gitlab-pull-token]...
getting client config for kubeContext: ``
 Creating docker config secret [gitlab-deploy-token]...
No docker config specified. Checking for one in the cluster.
getting client config for kubeContext: ``
 Building [registry.gitlab.com/polds/my-repo/my-image]...
```

### Information

- Skaffold version: skaffold-v1.10.1 (latest)
- Operating system: k3s. Ubuntu
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
metadata:
  name: my-app
build:
  cluster:
    pullSecretName: gitlab-pull-token
    dockerConfig:
      secretName: gitlab-deploy-token
  artifacts:
  - image: registry.gitlab.com/polds/my-repo/my-image
    context: .
    kaniko:
      dockerfile: build/package/my-app.Dockerfile
deploy:
  kubectl:
    manifests:
    - deployments/kubernetes/*.yaml
```

Sample of the secrets `gitlab-pull-token` and `gitlab-deploy-token`:

```
{"auths":{"registry.gitlab.com":{"username": "my-user", "password": "password"}}}
```

### Steps to reproduce the behavior

1. My skaffold process for `.gitlab-ci.yml`:

```yaml
skaffold run:
  image:
    name: registry.gitlab.com/polds/my-repo/skaffold:${SKAFFOLD_VERSION}
  stage: deploy
  script: |
    mkdir ~/.docker
    printf '{"auths":{"%s":{"username":"%s","password":"%s"}}}' $CI_REGISTRY $CI_REGISTRY_USER $CI_REGISTRY_PASSWORD > ~/.docker/config.json
    skaffold run \
      -f="${CI_PROJECT_DIR}/skaffold.yaml" \
      --kubeconfig="${KUBECONFIG}" \
      -v debug
```

2. My skaffold container is a clone of https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/skaffold just pushed to gitlabs registry
3. Use gitlab to run `skaffold run`, locally it works.
