### ISSUE TITLE
Make IMAGE_REPO, IMAGE_NAME, IMAGE_TAG available in build.artifacts[i].docker.buildArgs

### ISSUE THREAD

**Issue by javier-b-perez** [GoogleContainerTools/skaffold#4295]
### Expected behavior

```yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: gobuilder
    context: build/gobuilder
    docker:
      dockerfile: Dockerfile
  # These containers are using builders (like golang + tools) + src.
  - image: my-app
    docker:
      dockerfile: my-app/Dockerfile
      buildArgs:
        GOBUILDER: "{{.IMAGE_REPO}}/gobuilder:{{.IMAGE_TAG}}"
```

```shell
skaffold build --default-repo=gcr.io/my-project -t demo
```

### Actual behavior

```shell
- my-app: Error checking cache.
getting hash for artifact "my-app": getting dependencies for "my-app": parsing ONBUILD instructions: retrieving image "<no value>/gobuilder:<no value>": parsing reference [<no value>/gobuilder:<no value>]: could not parse reference: <no value>/gobuilder:<no value>
```

### Information

- Skaffold version: v1.10.1

### Steps to reproduce the behavior

1. `git clone https://github.com/javier-b-perez/skaffold-tags-demo.git`
2. `skaffold build --default-repo=gcr.io/my-project -t demo`

### Workaround

1. Update skaffold.yaml
```yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: basebuilder
    docker:
      dockerfile: Dockerfile.base
  # These containers are using builders (like golang + tools) + src.
  - image: my-app
    docker:
      dockerfile: Dockerfile
      buildArgs:
        BASEBUILDER: "gcr.io/my-project/basebuilder:demo"
```

2. Build builder
```shell
skaffold build --default-repo=gcr.io/my-project -t demo -b basebuilder
```

3. Build app
```shell
skaffold build --default-repo=gcr.io/my-project
```
