### ISSUE TITLE
Questions related to 'skaffold deploy'

### ISSUE THREAD

**Issue by sammym1982** [GoogleContainerTools/skaffold#4302]
I looked all over but didn't find any sample which explains how I should be passing the --images parameter to the `skaffold deploy` command. My service skaffold.yaml looks something like below and I have a scenario where I need to just execute the deploy stage with passing in the prebuilt images. What is the format for the --images parameter. 

Secondly, Is it possible to control only to deploy subset or all of the images (e.g. deploy svc1 OR svc2 OR svc1+svc2). I tried profiles for each image but that does not seem to be supported scenario as only the last profile in list gets preference.

deploy section of skaffold:

```
deploy:
  helm:
    releases:
    - name: svc1
      chartPath: svc1/deployment/chart
      values:
        image: svc1
    - name: svc2
      chartPath: svc2/deployment/chart
      values:
        image: svc2
```
