### ISSUE TITLE
Does "google cloud build" support pull and pushing the private Dockerhub repo

### ISSUE THREAD

**Issue by amitm02** [GoogleContainerTools/skaffold#4320]
Does "google cloud build" supports pull from and push to a private Dockerhub repo?
I did not find anything in the documentation regarding how to set it up..

**Comment by tejal29** [comment]
The GCB docs mentions detailed steps on this https://cloud.google.com/cloud-build/docs/interacting-with-dockerhub-images

I have not tried this but as far as i know, this is possible.

**Comment by tejal29** [comment]
Please re-open if you have additional questions.

**Comment by amitm02** [comment]
All the steps mentioned in  [link](https://cloud.google.com/cloud-build/docs/interacting-with-dockerhub-images) are for using cloud build manually. e.g consturcting manually a yaml/json config file for cloud build request.
Not something that can be used with Skaffold as far as I know.

**Comment by amitm02** [comment]
@tejal29 
I dont have premission to reopen the issue.

**Comment by tejal29** [comment]
> @tejal29, All the steps mentioned in [link](https://cloud.google.com/cloud-build/docs/interacting-with-dockerhub-images) are for using cloud build manually. e.g consturcting manually a yaml/json config file for cloud build request.
> Not something that can be used with Skaffold as far as I know.

Hey Amit, 
Thanks for clarifying you meant within skaffold a GCB build. 
Currently, with GCB builder, pushing to docker hub is not supported with the default docker builder. 
However, you can use [kaniko](https://github.com/GoogleContainerTools/kaniko/) which allows you to pass your [docker secret](https://skaffold.dev/docs/references/yaml/#build-cluster)

Here is an example of GCB kaniko cluster build. 

```
apiVersion: skaffold/v2beta5
kind: Config
build:
  googleCloudBuild:
    projectId: <your-project>
  artifacts:
    - image: skaffold-example
      kaniko:
        cache: {}
  cluster:
    dockerConfig:
       path: ~/.docker/config.json // Path to your docker config
       secretName: <your-secret-name-to-be-created> // note this secret will be deleted after build
deploy:
  kubectl:
    manifests:
      - k8s-*
```
