### ISSUE TITLE
New flag --repo-prefix to backfill --default-repo functionality 

### ISSUE THREAD

**Issue by deedubs** [GoogleContainerTools/skaffold#4321]
### Expected behavior

Previously I had been using `--default-repo` more like `--repo-prefix` this all came to a grinding halt when I attempted to use the below `skaffold.yaml`.  When I ran it with

> skaffold build --default-repo=abc.123.com

I expected to see:

```
building abc.123.com/bases/go/1.13

building abc.123.com/bases/go/1.14
```

### Actual behavior

```
building abc.123.com/bases_go_1.13

building abc.123.com/bases_go_1.14
```
### Information

- Skaffold version: v1.10.1
- Operating system: Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta15
kind: Config

build:
  artifacts:
    - image: bases/go/1.13
      context: bases/go/multi
      docker:
        buildArgs:
          GO_VERSION:     "1.13"
          ALPINE_VERSION: "3.12"
    - image: bases/go/1.14
      context: bases/go/multi
      docker:
        buildArgs:
          GO_VERSION:     "1.14"
          ALPINE_VERSION: "3.12"
```
### Proposal

We introduce a new flag `--repo-prefix` which doesn't mangle the image names for Docker Hub and simply applies the prefix.
