### ISSUE TITLE
Render does not fully overwrite output file if it already exists

### ISSUE THREAD

**Issue by alewis001** [GoogleContainerTools/skaffold#4322]
### Expected behavior
The contents of the file `<path>/<file>.yaml` reflects the exact output of the command `skaffold render --output <path>/<file>.yaml`. If the file already exists, the file's content is fully overwritten.

### Actual behavior
The `render` command is only overwriting the bytes inside the file, not the entire file. 

I.e. If the current file is bigger (X bytes) and the output from `render` results in less bytes (Y bytes); then Y bytes in the file are overwritten but the remaining X-Y bytes in the file are left untouched. 

This issue affects Kubectl, Kustomize and Helm deployers. 

I think the issue is with the use of `os.OpenFile` instead of `os.Create` but I could be way off the mark as I'm very new to Go.

Helm and Kubectl both use `outputRenderedManifests`, which in turn uses `dumpToFile`, which uses `os.OpenFile`.

Kustomize uses `os.OpenFile` but inside `kustomize.go` on line 215 rather than `util.go`.

I tried changing the affected lines above to use `os.Create` and that appears to fix the issue; however, whether that's the appropriate fix I wouldn't like to say. I'm happy to make that change and submit a PR if that's the way to go.

### Information

- Skaffold version: 1.11.0
- Operating system: macos
- Deployer: Kubectl, Kustomize, Helm

### Steps to reproduce the behavior

1. Get the `skaffold/examples/helm-deployment` example
1. Modify the skaffold.yaml to make it a local build only
1. Run: `skaffold render --output render.txt`
1. Edit render.txt, add some additional text/YAML to the end of the file.
1. Run: `skaffold render --output render.txt`
1. Check contents of render.txt; the additional text added above is not removed.

E.g. Edited render.txt I.e."before"
```
---
# Source: skaffold-helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-helm
  labels:
    app: skaffold-helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffold-helm
  replicas: 2
  template:
    metadata:
      labels:
        app: skaffold-helm
    spec:
      containers:
      - name: skaffold-helm
        image: skaffold-helm:2ffd66737879da07ff3de2326f8e8c9d82f8748b5333ee4ae37033952ea269b0
add:
  some:
    additional: yaml
```
After another render to the same file:
```
---
# Source: skaffold-helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-helm
  labels:
    app: skaffold-helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffold-helm
  replicas: 2
  template:
    metadata:
      labels:
        app: skaffold-helm
    spec:
      containers:
      - name: skaffold-helm
        image: skaffold-helm:2ffd66737879da07ff3de2326f8e8c9d82f8748b5333ee4ae37033952ea269b0

dd:
  some:
    additional: yaml
```
Note the remaining text:
```

dd:
  some:
    additional: yaml
```
