### ISSUE TITLE
Skaffold complains about the docker file being outside the docker build context

### ISSUE THREAD

**Issue by runefs** [GoogleContainerTools/skaffold#4328]
### Expected behavior
That skaffold has no more restrictions on the location of the dockerfile than docker build has
### Actual behavior
Skaffold complains that the dockerfile is outside the build context 
### Information

```yaml
apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: hobbes
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: az
      context: workers/az.worker/
      docker:
        dockerfile: ../../docker/Dockerfile.worker
```

### Steps to reproduce the behavior
any setup where the docker file is outside of the specified context

**Comment by tejal29** [comment]
Thanks for the issue @runefs. The issue here when skaffold creates a build context tar, it tars up the `Dockerfile` outside of context at path `../` and hence you see the following error from docker daemon
```
Building [skaffold-example]...
Sending build context to Docker daemon  3.072kB
couldn't build "skaffold-example": docker build: Error response from daemon: Forbidden path outside the build context: ../Dockerfile ()
```


https://github.com/GoogleContainerTools/skaffold/blob/d402799901c8c7b92fa670a38590e89bf2fd6de0/pkg/skaffold/docker/context.go#L29

The right thing to do here is if `Dockerfile` is not in context, the above function create it at path `./Dockerfile`
Probably need some relative path checks in https://github.com/GoogleContainerTools/skaffold/blob/d402799901c8c7b92fa670a38590e89bf2fd6de0/pkg/skaffold/docker/context.go#L37

**Comment by pipe01** [comment]
Any progress on this?

**Comment by briandealwis** [comment]
The implementation in #4425 was becoming fairly complex.  This isn't a high-priority item for the team at the moment.

**Comment by ynouri** [comment]
Not sure what's going on under the hood, but in our case enabling [BuildKit](https://docs.docker.com/develop/develop-images/build_enhancements/) with `useBuildkit: true` seems to help.

```
profiles:
  - name: local
    build:
      artifacts:
      - image: my-image
        context: ./path/to/my/sources/
        docker:
          dockerfile: ../../../../path/to/my/dockerfile/Dockerfile
      local:
        useBuildkit: true
```
