### ISSUE TITLE
Caching mechanism for NodeJS packages

### ISSUE THREAD

**Issue by mythio** [GoogleContainerTools/skaffold#4329]
Can we have a caching mechanism to cache the node packages?
Everytime we make changes to `package.json`, sakffold rebuilds the package and then installs the dependecies again. Instead of installing again, can we use a cache or something to fasten this step?

**Comment by tejal29** [comment]
Thanks for bringing this up @mythio.

Are you using `npm ci` or `npm install` in your Dockerfile?
When you say, "skaffold rebuilds the package and then installs dependencies again", does it also fetch the dependencies or used already fetched dependencies which are cached locally in ~/.cache folder?

Please describe your project setup, skaffold.yaml and minimal Dockefile,  we will be happy to assist you further.

**Comment by mythio** [comment]
This is my Dockerfile

```Dockerfile
FROM node:alpine

WORKDIR /app
COPY package.json .
RUN npm install --only=prod
COPY . .

CMD ["npm", "start"]
```

> When you say, "skaffold rebuilds the package and then installs dependencies again", does it also fetch the dependencies or used already fetched dependencies which are cached locally in ~/.cache folder?

When I disable my internet connection, and run skaffold, `npm` says `npm ERR cb() never called`.
This is my `skaffold.yaml` file
```yaml
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: mythio/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
```

**Comment by briandealwis** [comment]
@mythio I believe just a pain `docker build` will have the same problem unfortunately.

One approach that *might* work is to perform the [`npm install` at *run time* instead of at build time](https://itnext.io/npm-install-with-cache-in-docker-4bb85283fa12).  You'd need a persistent volume that you would mount to hold your NPM cache.  Your entrypoint would be something like `npm install && npm start`.

**Comment by mythio** [comment]
Hmmm... Even though it seems some extra steps, it works better than plain `docker build`

**Comment by briandealwis** [comment]
One other thing, since your Dockerfile is actually really simple, you might consider using Skaffold's Buildpacks builder.  `skaffold dev` in particular has some nice integration with GCP Buildpacks to allow syncing and in-container rebuilding.

**Comment by mythio** [comment]
I am already using `skaffold dev` here.

```yaml
apiVersion: skaffold/v2beta5
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*.yaml
      - ./auth/k8s/auth-pv.yaml
      - ./auth/k8s/auth-pv-claim.yaml
      - ./auth/k8s/auth-db.yaml
      - ./auth/k8s/auth.yaml
      - ./products/k8s/products-pv.yaml
      - ./products/k8s/products-pv-claim.yaml
      - ./products/k8s/products-db.yaml
      - ./products/k8s/products.yaml
      - ./orders/k8s/orders-pv.yaml
      - ./orders/k8s/orders-pv-claim.yaml
      - ./orders/k8s/orders-db.yaml
      - ./orders/k8s/orders.yaml
build:
  local:
    push: false
  artifacts:
    - image: mythio/auth
      context: auth
      docker:
        buildArgs:
          ENV: development
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: mythio/products
      context: products
      docker:
        buildArgs:
          ENV: development
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: mythio/orders
      context: orders
      docker:
        buildArgs:
          ENV: development
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
```
