### ISSUE TITLE
skaffold debug with nodejs duplicates ENV values

### ISSUE THREAD

**Issue by legopin** [GoogleContainerTools/skaffold#4351]
### Expected behavior
When running skaffold debug with NodeJS application deployed by kustomize, I expect the env variables from overlays will not be duplicated or overwritten

### Actual behavior
The resulting deployed pod template had duplicate ENV variables.

For `valueFrom: secretKeyRef` the additional blank ENV variable actually overwrites the previous value.

![Screen Shot 2020-06-19 at 10 32 21 AM](https://user-images.githubusercontent.com/15863509/85090726-6ca60400-b218-11ea-88b6-f9c509940a28.png)

### Information

- Skaffold version: v1.11.0
- Kustomize version {Version:3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T23:38:55+01:00 GoOs:darwin GoArch:amd64}
- OS: MacOS 10.14.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: skaffold-debug-nodejs
    context: nodejs
deploy:
  kustomize: {}
```

### Steps to reproduce the behavior
Based on the integration test data in repo: https://github.com/GoogleContainerTools/skaffold/tree/master/integration/testdata/debug

1. a clonable repository: https://github.com/legopin/skaffold-debug-nodejs-env-reproduction.git
2. `skaffold debug`
3. kubectl get deployment nodejs -o yaml
