### ISSUE TITLE
Skaffold should handle multi-build execution contexts(local vs cluster vs gcb)

### ISSUE THREAD

**Issue by nitkon** [GoogleContainerTools/skaffold#4354]
### Expected behavior
Skaffold supports multi-build execution contexts(local, cluster, gcb) in a single Skaffold.yaml.
For example, if there are two artifacts, one to be built with Kaniko in a cluster and another one to be built with jib locally, Skaffold should support it. 

### Actual behavior
Skaffold errors out.
```
[root@localhost jib]# skaffold dev
invalid skaffold config: only one element in set artifact can be set. got JibArtifact and KanikoArtifact
```
### Information

- Skaffold version: v1.11.0-39-gd32eec1b8
- Operating system: Fedora 30
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: skaffold-jib
      jib: {}
    - image: skaffold-example
      kaniko:
        cache: {}
  cluster:
    pullSecretName: e2esecret-with-path
    pullSecretPath:     kaniko-secret.json
    namespace: default
# optional profile to run the jib build on Google Cloud Build
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
```

### Steps to reproduce the behavior

1. Get to the path: github.com/GoogleContainerTools/skaffold/examples/jib
2. Update the skaffold.yaml as above. Run: `skaffold dev`
