### ISSUE TITLE
building artifacts multiple ways is hard to configure

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#4361]
Today, if you want to switch _all_ your builder types to kaniko from local docker, you'll have to repeat all your artifacts. This is cumbersome so people resort to using YamlAnchors. E.g. https://github.com/ForgeRock/forgeops/blob/master/skaffold.yaml

A smaller example: 

```
apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: skaffold-example
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: build-with-kaniko
    build:
      artifacts:
        - image: skaffold-example
          kaniko:
            image: gcr.io/kaniko-project/executor:v0.20.0
            flags:
              - '--single-snapshot'
      cluster: {}
```

Issues with our current config reflecting in repetition are: 
- `kaniko.image`, `kaniko.flags`, etc. are only available on the artifact level. **Recommendation:** If these would be available on the `build.cluster.kaniko` level, one wouldn't have to repeat them for each artifact 
- if I specify `artifacts.kaniko.image` and try to build with `local` docker, then skaffold fails with: 

```
invalid skaffold config: found a 'kaniko' artifact, which is incompatible with the 'local' builder:

image: skaffold-example
context: .
kaniko:
  flags:
  - --single-snapshot
  dockerfile: Dockerfile
  initImage: busybox
  image: gcr.io/kaniko-project/executor:v0.20.0

To use the 'kaniko' builder, add the 'cluster' stanza to the 'build' section of your configuration. For information, see https://skaffold.dev/docs/pipeline-stages/builders/
```
**Recommendation**: skaffold could ignore kaniko related settings on the artifacts, and artifacts could have at the same time settings for docker, kaniko and GCB (tho this last one doesn't exist). This means in go that an artifact could be simultaneously a KanikoArtifact and a DockerArtifact - not sure - but our abstraction here is messy.  

The final result would be something like this: 

```
apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: skaffold-example
    docker: {} # mentioned for explicitness
    kaniko: {} # mentioned for explicitness
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: build-with-kaniko
    build:
      cluster:
        kaniko:
          image: gcr.io/kaniko-project/executor:v0.20.0
          flags:
            - '--single-snapshot'
```

**Comment by wstrange** [comment]
Would something like this make sense:

```
builders:
- name: default # default is docker, unless otherwise specified
  type: docker
- name: kaniko
   type: kaniko
   options:
       image: gcr.io/kaniko-project/executor:v0.20.0
       flags: ....
   cluster:
        namespace: kaniko 
      pullSecretName: kaniko-secret

```

Then 
```
build:
  artifacts:
  # uses default builder
  - image:  my-image
    context: docker/my-image 
 - image: my-other-image
   context: docker/my-other-image
  builder: kaniko. # overeride default builder
```

Or at the profile level
```
profiles: 
- name: my-cool-profile
   builder:  kaniko # Use kaniko as the default builder for this profile
```



       

 
  



```
