### ISSUE TITLE
helm does not perform upgrade

### ISSUE THREAD

**Issue by MarcoSchaar** [GoogleContainerTools/skaffold#4399]
### Expected behavior
deploy and upgrade helm charts worked fine with version 1.10.1 and api v2beta4

### Actual behavior
helm does not perform an upgrade with version 1.11 / 1.12 and api v2beta5

### Information

- Skaffold version: 1.11 / 1.12
- Operating system: any
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: some-name
profiles:
  - name: dev
    deploy:
      kubeContext: clustername
      helm:
        releases:
        - name: dev-ingress
          chartPath: stable/nginx-ingress
          valuesFiles: 
          - helm-values/dev/nginx_values.yaml
          namespace: dev
          remote: true
          recreatePods: true
      kubectl:
        manifests:
        - kubernetes-manifests/dev/namespace.yaml
        - kubernetes-manifests/dev/secret.yaml
        - kubernetes-manifests/dev/deployment.yaml
        - kubernetes-manifests/dev/service.yaml
        - kubernetes-manifests/dev/ingress.yaml
```

### Steps to reproduce the behavior

1. compare with version 1.10.1
2. `skaffold run --profile <profile>`

related logs:
```bash
level=debug msg="Running command: [helm version --client]"
level=info msg="Deploying with helm v2.16.8 ..."
level=debug msg="Running command: [helm --kube-context clustername get dev-ingress]"
level=info msg="Release dev-ingress not upgraded as it is remote..."
```
