### ISSUE TITLE
Example with sharing library code between services? 

### ISSUE THREAD

**Issue by samstarling** [GoogleContainerTools/skaffold#4404]
I've been trying to work out how I can get skaffold to build several Go services in a monorepo which share some code between each other (proto definitions, and a couple of libraries).

[You can see the repo with my example code (described below) on GitHub](https://github.com/samstarling/monorepo-test). The repository looks like this:

```
├── Dockerfile.service
├── bin
│   └── client.go
├── docker
├── go.mod
├── go.sum
├── internal
│   ├── service.foo
│   │   ├── Dockerfile
│   │   ├── k8s.yaml
│   │   └── server.go
│   └── service.hello-world
│       ├── Dockerfile
│       ├── k8s.yaml
│       └── server.go
├── pkg
│   └── shared_code.go
├── rpc
│   ├── service.foo
│   │   ├── gen.go
│   │   ├── service.pb.go
│   │   ├── service.proto
│   │   └── ...
│   └── service.hello-world
│       ├── gen.go
│       ├── service.pb.go
│       ├── service.proto
│       └── ...
└── skaffold.yaml
```

In my Dockerfile, I have something like this:

```
FROM golang:alpine as builder
RUN mkdir /build 
ADD . /build/
WORKDIR /build/internal/service.hello-world
RUN go build -o /build/service.hello-world 

FROM alpine
COPY --from=builder /build/service.hello-world  /app/
WORKDIR /app
EXPOSE 8080
ENTRYPOINT ["/app/service.hello-world"]
```

Which I run from the root using:

```
docker build -f internal/service.hello-world/Dockerfile -t samstarling/s-hello-world .
```

This is so that the container, when it runs `ADD . /build/`, has access to all of the files in `rpc` so that it can import them. Is there any way of replicating this behaviour during `skaffold run`? My YAML is fairly simple (see below), but gives me the error seen below.

### Information

- Skaffold version: v1.12.0
- Operating system: macOS 10.15
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: twirp-test
build:
  artifacts:
  - image: s-addition
    context: internal/service.addition
  - image: s-hello-world
    context: internal/service.hello-world
deploy:
  kubectl:
    manifests:
    - internal/service.addition/k8s.yaml
    - internal/service.hello-world/k8s.yaml
```

### Steps to reproduce the behavior

1. `git clone git@github.com:samstarling/monorepo-test.git`
2. `skaffold run`
3. See the error:

```
can't load package: package .: no Go files in /build/internal/service.addition
failed to build: couldn't build "s-addition": unable to stream build output: The command '/bin/sh -c go build -o /build/service.addition' returned a non-zero code: 1
```
