### ISSUE TITLE
Cluster serviceaccount not changing

### ISSUE THREAD

**Issue by felixtran39** [GoogleContainerTools/skaffold#4412]
### Expected behavior
Successfully builds the desired image and pushes it to container registry.
### Actual behavior
Throws the following error:
`[build-and-push] Building [gcr.io/yuwenma-gke-playground/demo-backend]...
[build-and-push] couldn't build "gcr.io/yuwenma-gke-playground/demo-backend": creating kaniko pod: pods is forbidden: User "system:serviceaccount:pl:default" cannot create resource "pods" in API group "" in the namespace "pl"
`
### Information
I am trying to use in-cluster build in a tekton task. It seems that the service account I specified is not being used, and default is being used instead.

### skaffold.yaml
```
apiVersion: skaffold/v2beta4
build:
  artifacts:
  - image: gcr.io/yuwenma-gke-playground/demo-backend
    kaniko: {}
  cluster:
    namespace: pl
    serviceAccount: tranf-ksa
kind: Config
metadata:
  name: backend-config
```
### Task
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
  namespace: "pl" # {"type":"string","x-kustomize":{"setter":{"name":"namespace","value":"pl"}}}
spec:
  resources:
    inputs:
    - name: src-repo
      type: git
  steps:
  - name: build-and-push
    image: gcr.io/k8s-skaffold/skaffold:latest
    command:
    - skaffold
    args:
    - build
    - -f
    - /workspace/src-repo/skaffold.yaml
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/kaniko-secret.json
    volumeMounts:
    - name: kaniko-secret
      mountPath: /secret
  volumes:
  - name: kaniko-secret
    secret:
      secretName: kaniko-secret # {"type":"string","x-kustomize":{"setter":{"name":"gsa-key-file","value":"kaniko-secret"}}}
```
### Taskrun
```apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: run
  namespace: "pl"
spec:
  taskRef:
    name: build-and-push
  resources:
    inputs:
    - name: src-repo
      resourceRef:
        name: src-repo
```

- Skaffold version: version v2beta4 (also seems to happen on v2beta5)

### Steps to reproduce the behavior
1. Run the task.
2. Check the logs of the taskrun to see the error.
