### ISSUE TITLE
Run/Dev/Delete command not accepting multiple profiles correctly

### ISSUE THREAD

**Issue by craig-seeman** [GoogleContainerTools/skaffold#4429]
### Expected behavior
Using the run/dev/delete command with multiple profiles selected (Example:`skaffold delete --profile=foo,bar,baz`) should delete all 3 profiles entered in with the flag.

Expected simulated run:
```
# First run
$ skaffold delete --profile=foo,bar,baz
Cleaning up...
 - deployment.apps "foo" deleted
 - deployment.apps "bar" deleted
 - deployment.apps "baz" deleted
```
### Actual behavior
Skaffold delete while using the profile flag seems to only select the last listing in the string.

```
# First run
$ skaffold delete --profile=foo,bar,baz
Cleaning up...
 - deployment.apps "baz" deleted

# Second run
$ skaffold delete --profile=foo,bar,baz
Cleaning up...
```

### Information

- Skaffold version: v1.12.0
- Operating system: macOS 10.15.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta5
kind: Config

profiles:
  - name: foo
    deploy:
      kubectl:
        manifests:
          - foo.yml
  - name: bar
    deploy:
      kubectl:
        manifests:
          - bar.yml
  - name: baz
    deploy:
      kubectl:
        manifests:
          - baz.yml
```

### Steps to reproduce the behavior

1. Using above (or similar yaml with multiple profiles)
2. Issue `skaffold delete --profile=` with multiple comma separated  values
