### ISSUE TITLE
Remote helm charts should be upgraded by default

### ISSUE THREAD

**Issue by yolkov** [GoogleContainerTools/skaffold#4431]
We use Skaffold, not only for local development, but also for CI/CD.  
```bash
skaffold build --profile build --file-output build.json
skaffold deploy --profile "${ENV}-infra" --images=internal/app1:faketag #we have to use a workaround [https://github.com/GoogleContainerTools/skaffold/issues/3559#issuecomment-632330117]
skaffold deploy --profile ${ENV} --build-artifacts build.json
```

After [this issue](https://github.com/GoogleContainerTools/skaffold/issues/2245) Skaffold changed the behavior for remote Charts without the configuration option "upgradeOnChange: true" it will not deploy anything even if you change only values, and the Chart itself remains the same version.

### Expected behavior
1. Default behavior for remote Charts should be changed  to "upgradeOnChange: true" at least.
Otherwise it breaks backward compatibility. For CI/CD we use Skaffold with remote Helm Charts only for dozens of services in production. Skaffold updating with this change force us to update all these product and infrastructure services.
These changes are hard to test, because the problem occurs only when you change either a Chart version or values. I make changes to values of the Chart and expect them to apply, but I still need to enable some options.
I don't understand the purpose of this option. For example, I have several services that depend on a single remote chart. I need to update the chart and deploy all dependent services from this chart. With the current option, I will have to do the following:
- Change the chart
- Enable the true flag for the service we want to deploy
- Deploy
- And turn off the flag again, because it is intended not to update the helm chart entities during the next deployment.

Changing values should always start deployment and execute the intended Chart logic, regardless of whether option "upgradeOnChange" is enabled or not. We make changes of Chart values advisedly and there is no need to confirm this with an additional option.
If you decide to keep this option, please add ENV for it.

2. The right decision in my opinion, there is no need in this option "upgradeOnChange".
Helm supports version control https://helm.sh/docs/chart_best_practices/conventions/#version-numbers, https://helm.sh/docs/topics/charts/#charts-and-versioning (similar to python with requirements.txt, ruby with gemfile, php with composer.json, go modules with go. mod, etc). Correspondingly, if you don't change the version of the Chart, the Helm will do only what is inherent in the logic of the Chart. 
If there is no special logic for changes each time you deploy these changes, then Helm no deploy anything. Not need to intervene in the logic of the Charts, if it doesn't approach you then fork and modify Chart as you require or go to use another chart. Skaffold should not interfere in the logic of the Charts, except setting values that it is doing well. As a result, the fundamental error was made in [this issue](https://github.com/GoogleContainerTools/skaffold/issues/2245), they did not fix the Chart versions, and so the Chart version was updated when deployed, and Helm did what it was supposed to do. This is just the wrong use of the Helm.
You may need to add a check. if "remote: true", the Chart version field should be mandatory.

### Actual behavior
For remote Charts, and for local ones, too, if values change, the Chart must deployed and perform the logic laid down in the Chart(change configmaps, redeploy deployments, statefulsets, change ingress resources, etc.), but now Charts not deployed.

### Information

- Skaffold version: v1.11.0
- Helm version: v2.16.1
- Operating system: linux/macos

P.S. Please do not break backward compatibility if possible. For companies that use Skaffold in production for CI/CD for dozens, hundreds of services, broken backward compatibility leads to a lot of work, either blocking the transition to the new version, or incidents in production. 
(sorry for not good English)

**Comment by nkubala** [comment]
@yolkov thanks for the issue, and sorry we made your life harder with this change. this is a bit tough because for `skaffold dev`, I think we made the right choice here - upgrading remote charts by default seems a bit cumbersome, especially if you want to iterate on one piece of your application while keeping your remote dependencies like databases, etc. untouched. helm itself [doesn't actually do any change detection](https://github.com/helm/helm/issues/3177) when upgrading a release, and skaffold doesn't either, so our hands were tied here. this is what https://github.com/GoogleContainerTools/skaffold/pull/3274 addressed.

however, for using `skaffold deploy` for CI/CD, the use case is different, and most likely we'd actually **want** to redeploy remote charts, especially if the values file is local. so I think we missed this here when we made our original decision.

> if you don't change the version of the Chart, the Helm will do only what is inherent in the logic of the Chart.
can you explain this a bit more? my understanding is that on `helm upgrade`, helm will **always** create a new release (with a new revision version number), regardless of whether the chart changed. maybe i'm wrong though?

if this is true, then the main question here for me becomes: 
* do we want to simply change the default value of `upgradeOnChange` to `true` (and force people doing `skaffold dev` to change their `skaffold.yaml` to reflect this new default); **or**, 
* do we want to change the default behavior between `skaffold dev` and `skaffold deploy`, such that `dev` doesn't upgrade remote charts on redeploy but `deploy` does?

the first option is less confusing, but requires `dev` users to change their defaults which is not great, though arguably better than `deploy` users having to change their defaults across potentially dozens of `skaffold.yaml`s. the second option, while maybe giving both sets of users what they want, could lead to confusing behavior, and could also be making false assumptions about the "expected" behavior.

cc @dahovey if you have any opinions on this :) and cc @dgageot if you have any thoughts

**Comment by dahovey** [comment]
Hi @yolkov, I definitely agree with your `P.S.`.

@nkubala I don't have any hard opinions on this. I didn't use skaffold for CI/CD, so unfortunately, didn't work thru these scenarios. I guess I lean toward your second option. If `upgradeOnChange` is `nil`, and using `skaffold dev` then remote is used determine value of `upgradeOnChange` (as it is now), but if using `skaffold deploy` then when `upgradeOnChange` is `nil` the default value is `true`.

Since I only used part of the power of `skaffold`, your last statement is concerning:
> could lead to confusing behavior, and could also be making false assumptions about the "expected" behavior.

**Comment by yolkov** [comment]
@nkubala 
>my understanding is that on helm upgrade, helm will always create a new release (with a new revision version number), regardless of whether the chart changed. maybe i'm wrong though?

Yes, helm creates new releases every time, but this is only a change to the metadata (which is stored in helm's configmap). If the helm chart version does not change and the values do not change, the kubernetes entities created by the chart(deployment,statefullsets, services, ingress, configmap, etc) will not deploy again.

**Comment by yolkov** [comment]
For example:

```
apiVersion: skaffold/v2beta4
kind: Config
build:
deploy:
profiles:
- name: dev-local
  activation:
    - env: DEV_RUNTIME=local
    - kubeContext: docker-desktop
      command: dev
    - kubeContext: docker-desktop
      command: run
    - kubeContext: docker-for-desktop
      command: dev
    - kubeContext: kind-kind
      command: dev
    - kubeContext: kind-kind
      command: run
  build:
    artifacts:
    - image: internal/example-app
      context: ../.
      sync:
        manual:
        - src: '**'
          dest: /app
      docker:
        dockerfile: ./Dockerfile
    local:
      push: false

  deploy:
    helm:
      releases:
      - name: example-app-mysql
        chartPath: stable/mysql
        valuesFiles:
        - ./dev/values.yaml
        - ./dev/values.mysql.yaml
        - ./dev/secrets.yaml
        namespace: example-app
        version: 1.2.1
        remote: true
      - name: example-app-redis
        chartPath: stable/redis
        valuesFiles:
        - ./dev/values.yaml
        - ./dev/values.redis.yaml
        namespace: example-app
        version: 8.0.17
        setValues:
          image.pullPolicy: IfNotPresent
        remote: true
      - name: example-app-service
        chartPath: int/php-nginx
        valuesFiles:
        - ./dev/values.yaml
        - ./dev/values.service.yaml
        - ./dev/secrets.yaml
        artifactOverrides:
          image: internal/example-app
        namespace: example-app
        version: 0.9.1
        setValues:
          image.pullPolicy: IfNotPresent
        wait: true
        remote: true
        imageStrategy:
          helm: {}
```

run:
`skaffold dev -f skaffold-example.yaml`

in another console run:
`kubectl -n example-app get po -o wide -w`

```
NAME                                             READY   STATUS    RESTARTS   AGE   IP             NODE                 NOMINATED NODE   READINESS GATES
example-app-service-php-nginx-79f44d8c8f-v2rll   2/2     Running   0          55s   10.244.0.198   kind-control-plane   <none>           <none>
mysql-646746b55f-9gdqg                           1/1     Running   0          93s   10.244.0.196   kind-control-plane   <none>           <none>
redis-master-0                                   1/1     Running   0          74s   10.244.0.197   kind-control-plane   <none>           <none>`
```

then change skaffold-example.yaml
`echo >> skaffold-example.yaml`

Skaffold start re-deploy and for every release run helm upgrade ... , but all pods do not restarted
