### ISSUE TITLE
[feature request] json path support wildcard

### ISSUE THREAD

**Issue by jk2K** [GoogleContainerTools/skaffold#4438]
### Expected behavior
add build arg `REPO_FROM` to all artifact

like

```yaml
    patches:
      - op: add
        path: /build/artifacts[*]/docker/buildArgs
        value:
          REPO_FROM: 'registry.demo.com/avatar/internal/'
```

### Actual behavior
error

applying profiles: applying profile "development": invalid path: /build/artifacts[*]/docker/buildArgs

### Information

- Skaffold version: version... 5df17d6, 
- Operating system: ... macOS 10.14.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: erp
build:
  local:
    push: true
    useBuildkit: true
  artifacts:
    - image: registry.demo.com/avatar/mpaas/shipconsole
      context: ../
      docker:
        dockerfile: avatar/auto/ship/web.Dockerfile
    - image: registry.demo.com/avatar/mpaas/shipmobile
      context: ../
      docker:
        dockerfile: avatar/auto/ship/mobile.Dockerfile
    - image: registry.demo.com/avatar/mpaas/shipbackground
      context: ../
      docker:
        dockerfile: avatar/auto/ship/background.Dockerfile

profiles:
  - name: development
    build:
      tagPolicy:
        dateTime:
          format: "dev2006-01-02_15-04-05.999_MST"
          timezone: "Local"
    patches:
      - op: add
        path: /build/artifacts[*]/docker/buildArgs
        value:
          REPO_FROM: 'registry.demo.com/avatar/internal/'

  - name: nocache
    patches:
      - op: add
        path: /build/artifacts/0/docker/noCache
        value: true

```

### Steps to reproduce the behavior
```bash
skaffold build -p development --build-image=ship
```
