### ISSUE TITLE
'file name too long' error with configmap kustomize patch when running skaffold dev(only). 

### ISSUE THREAD

**Issue by lee-baines** [GoogleContainerTools/skaffold#4439]
### Expected behavior
Skaffold dev lists the files to watch then proceeds with deployment.

### Actual behavior
Skaffold dev actually throws a `file name too long` error, when listing the configmap file to watch, that includes the strategicPatchMerge config.  Reducing the amount in the patch will allow it to work.

### Information

- Skaffold version: 1.12.0
- Operating system: MacOS High Sierra 10.13.6
- Contents of skaffold.yaml:

```yaml
  commonArtifactSets:
    default-artifacts: &default-artifacts
    - *AM
    - *AMSTER
    - *IDM
    - *DS-CTS
    - *DS-IDREPO
    - *FORGEOPS-SECRETS
    - *IG
    - *LDIF-IMPORTER

build: &default-build
  artifacts: *default-artifacts
  tagPolicy:
    sha256: {}

- name: small
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/small
```
``` kustomize base
configMapGenerator:
- name: platform-config
  # The env vars below can be passed into a pod using the envFrom pod spec.
  # These global variables can be used to parameterize your deployments.
  # The FQDN and URLs here should match your ingress or istio gateway definitions
  literals:
  - SUBDOMAIN=iam
  - DOMAIN=example.com
  - FQDN=default.iam.example.com
  - AM_URL=https://$(FQDN)/am
  - AM_ADMIN_URL=https://$(FQDN)/am/ui-admin/
  - IDM_ADMIN_URL=https://$(FQDN)/admin
  - IDM_UPLOAD_URL=https://$(FQDN)/upload
  - IDM_EXPORT_URL=https://$(FQDN)/export
  - PLATFORM_ADMIN_URL=https://$(FQDN)/platform
  - IDM_REST_URL=https://$(FQDN)/openidm
  - ENDUSER_UI_URL=https://$(FQDN)/enduser
  - LOGIN_UI_URL=https://$(FQDN)/login/#/service/Login
  - ENDUSER_CLIENT_ID=end-user-ui
  - ADMIN_CLIENT_ID=idm-admin-ui
  - THEME=default
  - AM_STORES_CTS_SERVERS="ds-cts-0.ds-cts:1389"
  - AM_STORES_USER_SERVERS="ds-idrepo-0.ds-idrepo:1389"
  - AM_SERVER_FQDN="$(FQDN)"
  - AUTORESTORE_FROM_DSBACKUP="false" # Set to "true" to enable DS auto recovery. See documentation 
  - DSBACKUP_DIRECTORY="" # Ex. gs://bucket | s3://bucket | az://bucket
  - CERT_ISSUER="default-issuer" # cert manager issuer. Patch with letsencrypt-prod for LE SSL certs.
```
```kustomize overlay patch
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: platform-config
  data:
    # Some optional settings
    # Set the FQDN - includes the namespace prefix!
    # FQDN: prod.pit-test.forgeops.com
    # If you are using cert-manager and Let's Encrypt in your cluster and want real certs - set this
    # CERT_ISSUER: letsencrypt-prod
    AM_STORES_CTS_SERVERS: "ds-cts-0.ds-cts:1389,ds-cts-1.ds-cts:1389,ds-cts-2.ds-cts:1389"
    AM_STORES_USER_SERVERS: "ds-idrepo-0.ds-idrepo:1389,ds-idrepo-1.ds-idrepo:1389,ds-idrepo-2.ds-idrepo:1389"
```

### Steps to reproduce the behavior

1. https://github.com/ForgeRock/forgeops
2. `skaffold dev -p small`
