### ISSUE TITLE
how to define volumes and volumeMounts e.g. for kaniko

### ISSUE THREAD

**Issue by MarcoSchaar** [GoogleContainerTools/skaffold#4441]
Hi,

some Questions regarding documentation /examples:

based on Pod yaml definition, how to define volumes in Cluster section and volumeMounts for kaniko?

when "skipTLS: false", where to define the CA for successful verification?

**Comment by MarcoSchaar** [comment]
maybe related to https://github.com/GoogleContainerTools/skaffold/issues/4175

**Comment by MarcoSchaar** [comment]
as per #3883 and others 
found out that it should be lower case for volumeMounts like this 
```yaml
volumeMounts:
- name: kaniko-secret
   mountpath: /kaniko/.docker
...
  subpath: <...>
```

but for volumes it not clear
```yaml
cluster:

        namespace: <namespace>
        volumes:
        - name: kaniko-secret
          secret:
            secretName: kaniko-secret
        - name: <name>
          configMap:
            name: <name>
```

secret or configMap not known in "v1.Volume"
