### ISSUE TITLE
feature request: use different build image name

### ISSUE THREAD

**Issue by MarcoSchaar** [GoogleContainerTools/skaffold#4444]
Hi,

we use for kaniko in skaffold.yaml 
```yaml
build: 
artifacts: 
- image: <registry-push/imagename>
```

but in deployment.yaml
```yaml
containers:
      - name: containername
        image: registry/imagename
```
error in our case

```bash
getting image: GET https://registry-push.<domain>/v2/: unsupported status code 403; body: <html>
```

is it possible or would it make sense to support such approach?

kind regards
Marco
