### ISSUE TITLE
skaffold deploy to support -t for tags

### ISSUE THREAD

**Issue by matti** [GoogleContainerTools/skaffold#4455]
skaffold.yaml:

```
apiVersion: skaffold/v2alpha2
kind: Config
build:
  artifacts:
    - image: first
      context: components/first
    - image: second
      context: components/second
deploy:
  kustomize:
    path: kustomize
```

If I have already built the images I need to provide `--image` for every artifact:

```
skaffold deploy \
  -d my.registry.example.com \
  --images "first:mytag" \
  --images "second:mytag"
```

So if `skaffold deploy` supported `-t` like other commands, then this would become just:

```
skaffold deploy \
  -d my.registry.example.com \
  -t mytag
```

and the `skaffold deploy ...` command wouldn't need to know the artifacts.
