### ISSUE TITLE
Support parent/child "module" spec inlined in a single skaffold.yaml

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#4457]
We should add support for specifying child modules of a parent within one skaffold.yaml.

From https://tinyurl.com/skaffold-modules:

```yaml
apiVersion: skaffold/v2beta2
kind: Config
metadata:
 name: microservices
modules:
 - name: leeroy-web
   build:
     artifacts:
       - image: leeroy-web
         context: ./leeroy-web/
         requires:
           - alias: BASE
             image: simple-go-app
             module:
               name: base
   deploy:
     kubectl:
       manifests:
         - ./leeroy-web/kubernetes/*
   portForward:
     - resourceType: deployment
       resourceName: leeroy-web
       port: 8080
       localPort: 9000
 - name: leeroy-app
   build:
     artifacts:
       - image: leeroy-app
         context: ./leeroy-app/
         requires:
           - alias: BASE
             image: simple-go-app
             module:
               name: base
   deploy:
     kubectl:
       manifests:
         - ./leeroy-app/kubernetes/*
 - name: base
   build:
     artifacts:
       - image: simple-go-app
         context: base
```
