### ISSUE TITLE
DIGEST_HEX2 gets wrongly parsed with local docker registry

### ISSUE THREAD

**Issue by zepatrik** [GoogleContainerTools/skaffold#4459]
### Expected behavior

`DIGEST_HEX2` should contain the digest.

### Actual behavior

We're using a local docker registry and therefore tag the image with `localhost:5000/artifacts/backoffice`.
Skaffold seems to determine `DIGEST_HEX2` by splitting at the first colon, which in our case leads to the following `EnvVarMap`:

```
level=debug msg="EnvVarMap:
map[
  DIGEST:localhost:5000/artifcats/console:bc972475f5c50407e60289bfd2727454df7c8063c76b10cf03f045993d23329a
  DIGEST2:localhost:5000/artifcats/backoffice:5f508720264ab362d3496cdb55a7ea2821d49441eea917ae5ff8f12c36cf0c53
  DIGEST_ALGO:localhost
  DIGEST_ALGO2:localhost
  DIGEST_HEX:5000/artifcats/console:bc972475f5c50407e60289bfd2727454df7c8063c76b10cf03f045993d23329a
  DIGEST_HEX2:5000/artifcats/backoffice:5f508720264ab362d3496cdb55a7ea2821d49441eea917ae5ff8f12c36cf0c53
  IMAGE_NAME:localhost:5000/artifcats/console IMAGE_NAME2:localhost:5000/artifcats/backoffice
]"
```

Instead of splitting at the first colon, skaffold should probably split at the last one.

### Information

- Skaffold version: v1.12.0
- Operating system: Arch Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
    useDockerCLI: true
  artifacts:
   # ...
    -
      image: localhost:5000/artifcats/backoffice
      context: .
      docker:
        dockerfile: src/backoffice/Dockerfile

deploy:
  statusCheckDeadlineSeconds: 43200
  helm:
    releases:

      -
        name: backoffice
        chartPath: helm/charts/backoffice
        namespace: kernel
        valuesFiles:
          - skaffold/backoffice/values.yaml
        setValueTemplates:
          backoffice.config.executor.image.repository: "{{.IMAGE_NAME2}}"
          backoffice.config.executor.image.tag: "{{.DIGEST_HEX2}}"      # THIS VALUE IS NOT CORRECTLY DETERMINED
        values:
          image: localhost:5000/artifcats/backoffice
        imageStrategy:
          helm: {}

profiles:
  - name: prod
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Dockerfile
```

### Workaround

As a workaround I guess I can tag the image with alternative names as well, the local registry is mainly used for running tests in kind without skaffold.
