### ISSUE TITLE
Image rewriting fails

### ISSUE THREAD

**Issue by ashconnell** [GoogleContainerTools/skaffold#4486]
### Expected behavior

When using [Agones](https://agones.dev/site/docs/getting-started/create-fleet/) which introduces custom resource definitions (eg Fleet, Gameserver) the image specified should be rewritten the same as other pod specifications when using `skaffold dev` etc.

```yaml
apiVersion: 'agones.dev/v1'
kind: Fleet
metadata:
  name: gameserver-fleet
spec:
  replicas: 2
  template:
    spec:
      ports:
        - name: default
          containerPort: 3002
      template:
        spec:
          containers:
            - name: gameserver
              image: gcr.io/company/gameserver
              ports:
                - containerPort: 3002
```

### Actual behavior

Inspecting via minikube dashboard shows that the pod Agones creates moves into an `ImagePullBackOff` state and inspecting the manifest shows that the image value is still `gcr.io/company/gameserver` and has not been rewritten.

### Information

- Skaffold version: v1.9.1
- Operating system: OSX
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: company
build:
  local:
    useDockerCLI: true
  artifacts:
    - image: gcr.io/company/gameserver
      context: ./packages/gameserver
      docker:
        target: development
      sync:
        infer:
          - 'src/**/*'
          - 'lib/**/*'
deploy:
  kubeContext: minikube
  kubectl:
    manifests:
      - k8s/*.yaml
```

I might be misunderstanding the issue i'm seeing but if this is correct are there any known workarounds to this that will let us continue development?

Cheers :D
