### ISSUE TITLE
Rethink how to display pod prefix for container Logs for a microservice application.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#4504]
During Sean's demo during July chill, 
- Sean mentioned having pods prefix in the logs is unnecessary. 

We should re-think, what to do when
- only one  service is deployed and it contains only 1 container
- multi-service application with only 1 container

Thanks
Tejal

**Comment by dgageot** [comment]
For information:

Current output for a single pod
<img width="348" alt="Screenshot 2020-07-21 at 13 45 06" src="https://user-images.githubusercontent.com/153495/88051151-704ee280-cb58-11ea-88d7-b6cc22b2345f.png">

**Comment by dgageot** [comment]
And for the java-guestbook sample:
<img width="869" alt="Screenshot 2020-07-21 at 14 13 02" src="https://user-images.githubusercontent.com/153495/88053607-5911f400-cb5c-11ea-86c5-9b6775a122cb.png">

**Comment by dgageot** [comment]
Here's what I think could work:
+ Default to never showing the pod name
+ Add a `logs` section to the `skaffold.yaml` with a property to change that behaviour. Something like:

```
apiVersion: skaffold/v1beta15
kind: Config
deploy:
  logs:
    - headers: auto(current behaviour)|container|podAndContainer|none
```

This new `logs` section would hold additional config in the future.
