### ISSUE TITLE
Skaffold sometimes doesn't deploy all services

### ISSUE THREAD

**Issue by ChaseMor** [GoogleContainerTools/skaffold#4519]
### Expected behavior
All services should deploy all the time

### Actual behavior
A fraction of the time, a service gets lost and doesn't deploy

### Information

- Skaffold version: version v1.12.0
- Operating system: Mac 10.15.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: dotnet-guestbook-backend
    context: src/backend
  - image: dotnet-guestbook-frontend
    context: src/frontend
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.service.yaml
    - ./kubernetes-manifests/*.deployment.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
```

### Steps to reproduce the behavior

1. Use either the Cloud Code VS Code or IntelliJ extension
2. Create a new application using the Java guestbook sample
3. Select run on Kubernetes
4. Observe that about 5-10% of the time, the frontend service doesn't deploy

#### VS Code
![Screen Shot 2020-07-21 at 12 39 54 AM](https://user-images.githubusercontent.com/13285164/88106010-a5a80000-cb59-11ea-81f4-1429b74db723.png)

#### IntelliJ
![Screen Shot 2020-07-21 at 1 31 32 PM](https://user-images.githubusercontent.com/13285164/88106015-a771c380-cb59-11ea-81ab-8207c4f8b79a.png)
