### ISSUE TITLE
kaniko cache error

### ISSUE THREAD

**Issue by zoulux** [GoogleContainerTools/skaffold#4555]
### Expected behavior
I wan map the cache to volume in kaniko build.

### Actual behavior

but i fund this error `field persistentvolumeclaim not found in type v1.Volume`.

### Information

- Skaffold version: skaffold/v2beta5 / v1.12.1
- Operating system:  mac
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta5
kind: Config
build:
  tagPolicy:
    dateTime:
      format: "200601021504"
      timezone: "Local"
  artifacts:
    - image: polk
      kaniko:
        image: zoulux/kaniko-executor
        cache: {}
        skipTLS: true
        buildArgs:
          --cache-dir: /cache
        volumeMounts:
          - name: kaniko-cache
            mountpath: /cache
  cluster:
    dockerConfig:
      secretName: docker-secret-skaffold
    volumes:
      - name: kaniko-cache
        persistentvolumeclaim:
          claimName: kaniko-cache-claim

deploy:
  helm:
    releases:
      - name: polk
        chartPath: helm/polk
        artifactOverrides:
          image: polk
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by ssvinoth22** [comment]
I too have same issue.. could someone help on this issue on pvc

**Comment by briandealwis** [comment]
The volumes needs to reflect the `Volume` structure.  So something like:

```
    volumes:
      - name: kaniko-cache
        volumesource:
          persistentvolumeclaim: 
            claimname: kaniko-cache-claim
```

As mentioned in #4175, ``cluster.volumes` and `artifacts.kaniko.volumeMounts` are actually kubernetes objects that don't have `yaml` tags and so require lower-casing the names.  On the bright side, it means `skaffold fix` actually exports all of the entries (as there are no `omitempty` tags found).

```console
$ skaffold fix
apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
  - image: polk
    kaniko:
      buildArgs:
        --cache-dir: /cache
      image: zoulux/kaniko-executor
      cache: {}
      skipTLS: true
      volumeMounts:
      - name: kaniko-cache
        readonly: false
        mountpath: /cache
        subpath: ""
        mountpropagation: null
        subpathexpr: ""
  cluster:
    dockerConfig:
      secretName: docker-secret-skaffold
    volumes:
    - name: kaniko-cache
      volumesource:
        hostpath: null
        emptydir: null
        gcepersistentdisk: null
        awselasticblockstore: null
        gitrepo: null
        secret: null
        nfs: null
        iscsi: null
        glusterfs: null
        persistentvolumeclaim:
          claimname: kaniko-cache-claim
          readonly: false
        rbd: null
        flexvolume: null
        cinder: null
        cephfs: null
        flocker: null
        downwardapi: null
        fc: null
        azurefile: null
        configmap: null
        vspherevolume: null
        quobyte: null
        azuredisk: null
        photonpersistentdisk: null
        projected: null
        portworxvolume: null
        scaleio: null
        storageos: null
        csi: null
```

**Comment by zoulux** [comment]
@briandealwis 
the structure is ok，but the cache does not seem to take effect，It is still a remote cache rather than local

**Comment by briandealwis** [comment]
@zoulux the kaniko docs mention that [you must include `--cache=true` too](https://github.com/GoogleContainerTools/kaniko#additional-flags):
> **--cache**
> Set this flag as `--cache=true` to opt into caching with kaniko.
>
> **--cache-dir**
> Set this flag to specify a local directory cache for base images. Defaults to `/cache`.
>
> _This flag must be used in conjunction with the `--cache=true` flag_.

**Comment by zoulux** [comment]
@briandealwis 
```yaml
apiVersion: skaffold/v2beta5
kind: Config
build:
  tagPolicy:
    dateTime:
      format: "200601021504"
      timezone: "Local"
  artifacts:
    - image: polk
      kaniko:
        image: zoulux/kaniko-executor
        cache: {}
        skipTLS: true
        buildArgs:
          --cache-dir: /cache
          --cache: true
        volumeMounts:
          - name: kaniko-cache
            mountpath: /cache
            readonly: false
            subpath: ""
            mountpropagation: null
            subpathexpr: ""
  cluster:
    dockerConfig:
      secretName: docker-secret-skaffold
    volumes:
      - name: kaniko-cache
        volumesource:
          persistentvolumeclaim:
            claimname: kaniko-cache-claim

deploy:
  helm:
    releases:
      - name: polk
        chartPath: helm/polk
        artifactOverrides:
          image: polk
```

 kaniko-cache-claim like a nas , but the nas is empty

**Comment by nkubala** [comment]
cc @tejal29

**Comment by msgongora** [comment]
@zoulux as per [doc](https://skaffold.dev/docs/references/yaml/),

> buildArgs - > arguments passed to the docker build. It also accepts environment variables via the go template syntax.

so sounds to me like **buildArgs** is not what you are looking for. Try **flags** instead

```yaml
kaniko:
    image: zoulux/kaniko-executor
    cache: {}
flags:
- --cache-dir=/cache
```
