### ISSUE TITLE
Skaffold Jib build permission denied error on Mac

### ISSUE THREAD

**Issue by Imerlith** [GoogleContainerTools/skaffold#4623]
### Expected behavior
Skaffold build or Skaffold dev builds docker image using jib and proceeds with a normal execution
### Actual behavior
When using jib as build type error is thrown:
`watching files for artifact "main-rest": listing files: getting jib-maven dependencies: initial Jib dependency refresh failed: failed to get Jib dependencies: starting command /Users/john/Projects/test-kub/modules/main-rest/mvnw jib:_skaffold-fail-if-jib-out-of-date -Djib.requiredVersion=1.4.0 --non-recursive jib:_skaffold-files-v2 --quiet --batch-mode: fork/exec /Users/john/Projects/test-kub/modules/main-rest/mvnw: permission denied`
### Information

- Skaffold version: 1.13.0
- Operating system: MacOs  Catalina 10.15.6
- Jib version: 2.4.0
- Maven version: 3.6.3
- Docker version: 2.3.0.4
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: test-kub
build:
  artifacts:
  - image: my-postgres
    context: db
  - image: main-rest
    context: modules/main-rest
    jib: {}
  - image: spa
    context: modules/spa
deploy:
  kubectl:
    manifests:
    - ./k8s/my-postgres-deployment.yaml
    - ./k8s/my-postgres-service.yaml
    - ./k8s/main-rest-deployment.yaml
    - ./k8s/main-rest-service.yaml
    - ./k8s/spa-deployment.yaml
    - ./k8s/spa-service.yaml

```
### Additional information
- Both `mvn compile jib:build` and `mvn compile jib:dockerBuild` correctly build image for main-rest module
- Error hasn't occured on my Windows 10 pc with the same configuration
- Skaffold succesfully executes when jib build type is ommited in skaffold.yaml
- Extract from main-rest pom.xml:

```xml
     <build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>2.4.0</version>
				<configuration>
					<to>
						<image>docker.io/john/main-rest</image>
					</to>
				</configuration>
			</plugin>
		</plugins>
	</build>
```
### Steps to reproduce the behavior

1. Create simple spring boot app with maven and place it inside modules directory
2. Add jib plugin
3. Configure skaffold.yaml to build image with jib
4. `skaffold dev` or  `skaffold build`
