### ISSUE TITLE
remove skaffold image validation for custom build

### ISSUE THREAD

**Issue by dwctua** [GoogleContainerTools/skaffold#4624]
For customized build, user is responsible for build and publish the image. Skaffold do not need to do the extra validation, or user should be able to disable it. Otherwise, user have to make the extra configuration to allow skaffold to access the image, for example, we need to make the registry public accessible.

### Expected behavior
Skaffold skip the validation for customized build

### Actual behavior
Skaffold is validating the image and extra config is required. 
.
### Information

- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-custom
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
        - .

```
