### ISSUE TITLE
//./pipe/docker_engine: no such host

### ISSUE THREAD

**Issue by bukowa** [GoogleContainerTools/skaffold#4648]
### Expected behavior
Works
### Actual behavior
Does not.
### Information
Manually pushing built image works. This is private registry.

- Skaffold version: v1.13.1
- Operating system: Win10
- Contents of skaffold.yaml:
````yaml
apiVersion: skaffold/v2beta6
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/X/Y
deploy:
  kubectl:
    manifests:
      - deployment.yaml
````
OR
````yaml
apiVersion: skaffold/v2beta6
kind: Config
build:
  local:
    useDockerCLI: true
    push: true
  artifacts:
  - image: registry.gitlab.com/X/Y
deploy:
  kubectl:
    manifests:
      - deployment.yaml
````
### Steps to reproduce the behavior

1. `skaffold dev`
````
←[34mListing files to watch...←[0m
←[34m - registry.gitlab.com/X/Y
←[0m←[34mGenerating tags...←[0m
←[34m - registry.gitlab.com/X/Y -> ←[0mregistry.gitlab.com/X/Y:fresh-service-webapp-gitlab-project-details-14-g4aa3f13-dirty
←[34mChecking cache...←[0m
←[34m - registry.gitlab.com/X/Y: ←[0m←[33mNot found. Building←[0m
←[34mBuilding [registry.gitlab.com/X/Y]...
←[0m←[31mexiting dev mode because first build failed: couldn't build "registry.gitlab.com/X/Y": docker build: error during connect: Post "https://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=null&cachefrom=null&cg
roupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=null&memory=0&memswap=0&networkmode=&rm=0&shmsize=0&t=registry.gitlab.com%2FX%2FY%3Afresh-service-webapp-gitlab-project-d
etails-14-g4aa3f13-dirty&target=&ulimits=null&version=": dial tcp: lookup //./pipe/docker_engine: no such host←[0m
````

**Comment by gsquared94** [comment]
If you're only trying to deploy a pre-built image then run `skaffold deploy --images registry.gitlab.com/X/Y` with the following `skaffold.yaml`:
```
apiVersion: skaffold/v2beta6
kind: Config
deploy:
  kubectl:
    manifests:
      - deployment.yaml
```

If you also want to run `skaffold dev` then run `skaffold dev --default-repo=registry.gitlab.com/X` with the following `skaffold.yaml`:
 ```
apiVersion: skaffold/v2beta6
kind: Config
build:
  artifacts:
  #replace references to 'registry.gitlab.com/X/Y' in deployment.yaml with only 'Y'; skaffold will substitute the correct value while deploying
    - image: Y 
deploy:
  kubectl:
    manifests:
      - deployment.yaml
```
