### ISSUE TITLE
question to combined helm / kubectl deployment

### ISSUE THREAD

**Issue by MarcoSchaar** [GoogleContainerTools/skaffold#4665]
Hi
while switching from helm2 to helm3 I've noticed a change in deployment behavior

### Expected behavior (seen with helm2)
apply kubectl part first
deploy helm chart as 2nd 

### Actual behavior
start with helm deployment
followed by kubectl part

### Information

- Skaffold version: 1.13.1
- Operating system: any
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: k8s

profiles
name: local
    build:
      tagPolicy:
        gitCommit: {}
      artifacts:
        - image: httpd
          context: httpd
          docker:
            dockerfile: Dockerfile
            noCache: true
    deploy:
      statusCheckDeadlineSeconds: 300
      kubeContext: docker-desktop
      kubectl:
        manifests:
        - kubernetes-manifests/local/namespace.yaml
        - kubernetes-manifests/local/secret.yaml
        - kubernetes-manifests/local/deployment.yaml
        - kubernetes-manifests/local/service.yaml
        - kubernetes-manifests/local/ingress.yaml
      helm:
        releases:
        - name: dev-ingress
          wait: true
          chartPath: stable/nginx-ingress
          valuesFiles: 
          - helm-values/local/nginx_values.yaml
          namespace: skaffold
          remote: true
          upgradeOnChange: true
```

### Steps to reproduce the behavior

1. deploy with helm2 
2. deploy with helm3

Is there an given order to respect or could it be controlled?
kind regards
Marco

**Comment by MarcoSchaar** [comment]
could be related to https://github.com/GoogleContainerTools/skaffold/issues/4482
but found this work around
```yaml
flags:
          install: ["--create-namespace"]
          upgrade: ["--create-namespace"]
```
