### ISSUE TITLE
Local image not used when adding release as a patch

### ISSUE THREAD

**Issue by tygriffin** [GoogleContainerTools/skaffold#4710]
### Expected behavior
Pull local image

### Actual behavior
Attempts to pull remote image

### Information

- Skaffold version: v1.13.2
- Operating system: macOS Catalina 10.15.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: geo
build:
  artifacts:
    - image: forms-service
      context: ../forms-service
deploy:
  helm:
    flags:
      upgrade:
        - "--install"
    releases:
      - name: forms-service
        namespace: dev
        chartPath: ../forms-service/helm/forms-service
        values:
          image.repository: forms-service
        setValues:
          NODE_ENV: development
        setValueTemplates:
          MONGO_URI: "{{.MONGO_URI}}"
      - name: mongodb
        namespace: dev
        chartPath: bitnami/mongodb
        remote: true
        setValues:
          mongodbUsername: mongodb
      - name: postgresql
        namespace: dev
        chartPath: bitnami/postgresql
        remote: true
        valuesFiles:
          - postgresql.yaml
portForward:
  - resourceName: mongodb
    resourceType: deployment
    namespace: dev
    port: 27017
  - resourceName: postgresql-postgresql
    resourceType: statefulset
    namespace: dev
    port: 5432
profiles:
  - name: web-api
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: web-api-gateway
          context: ../web-api-gateway
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: web-api-gateway
          namespace: dev
          chartPath: ../web-api-gateway/helm/web-api-gateway
          values:
            image.repository: web-api-gateway
          setValues:
            NODE_ENV: development
      - op: add
        path: /portForward/-
        value:
          resourceName: web-api-gateway
          resourceType: deployment
          namespace: dev
          port: 3000
```

I receive this warning:
```
WARN[0003] image [web-api-gateway:a29c309c15878fadfa61acd1913af5e82d013885bb83f9a23838ea9855519db0] is not used. 
WARN[0003] image [web-api-gateway] is used instead.     
WARN[0003] See helm sample for how to replace image names with their actual tags: https://github.com/GoogleContainerTools/s
```

Running `kubectl describe pod` reveals that the image is pointing to the remote repository, instead of overridden by the values config in the patch.
```
Containers:
  web-api-gateway:
    Container ID:   
    Image:          xxxxxxxxxxxx.dkr.ecr.ap-southeast-2.amazonaws.com/web-api-gateway
    Image ID:       
    Port:           3000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
```

Please note: **If I move the web-api-gateway out of the patch and into the main releases, it works fine.**
