### ISSUE TITLE
Calls 'gcloud.auth.docker-helper' for local deploys

### ISSUE THREAD

**Issue by vincejo** [GoogleContainerTools/skaffold#4724]
### Expected behavior
When a Cloud Code VSCode K8s sample (with no `gcr.io` registry associations) is deployed to minikube with no `credHelpers` in Docker config defined, `gcloud.auth.docker-helper` isn't invoked. 

### Actual behavior
It is invoked. 

### Information

- Skaffold version: v1.13.1
- Operating system: macOS Catalina (Version 10.15.6) 
- Contents of skaffold.yaml: 

```yaml
apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: nodejs-hello-world
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
```

### Steps to reproduce the behavior

1. User creates a K8 sample application using Cloud Code VSCode (e.g. Go: Hello World)
2. User runs `minikube start` from the terminal
3. Minikube successfully starts
4. Ensure that current kubernetes context is set to minikube in Kubernetes Explorer:
![image](https://user-images.githubusercontent.com/13400593/91366956-05797280-e7ba-11ea-81b4-f6982517d5bc.png)
5. User runs `skaffold dev -v info --port-forward --rpc-http-port 45699 --filename <SAMPLE_DIRECTORY>/skaffold.yaml` from the terminal (equivalent to running `Cloud Code: Run on Kubernetes` from the command palette).
6. Switch to Run on Kubernetes - Detailed in the Output Panel and see:
```bash
Running: skaffold dev -v info --port-forward --rpc-http-port 45699 --filename /home/vincentjo/hello-world-10/skaffold.yaml
starting gRPC server on port 50051

...

ERROR: (gcloud.auth.docker-helper) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Sending build context to Docker daemon  111.1kB

...

**************URLs*****************
Resource deployment/go-hello-world status completed successfully

Forwarded URL from service go-hello-world-external: http://localhost:4503

DevInit Iteration 0 successful
***********************************
```

My Docker config:
```
> cat ~/.docker/config.json
{
  "credHelpers" : {
  }
}
```
