### ISSUE TITLE
Cannot define patches for properties that have been changed in newer versions

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#4725]
From a user report on slack, consider the patch:
```
  patches:
     - op: add
        path: /deploy/helm/releases/0
        value:
          name: docs
          namespace: documentation
          chartPath: ./documentation/helm
          remote: false
          values:
            image: docs
```
This is consistent for skaffold API version `skaffold/v1` but in newer versions `value` property of the helm deployer has been renamed to `artifactOverride`. This patch fails to get applied as it's not upgraded to the latest version properly unlike the regular `Pipeline` objects [do](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/util/upgrade_pipelines.go#L31).
