### ISSUE TITLE
Missing tag in output file when local.push is false

### ISSUE THREAD

**Issue by Djiit** [GoogleContainerTools/skaffold#4766]
## Expected behavior

When I set `local.push: false`, Skaffold should not push the image, and output complete tags in a file with file-ouput option.

### Actual behavior

When I set `local.push: false`, Skaffold does not write the image tag (only SHA) in the output file

### Information

- Skaffold version: 1.14.0
- Operating system: macOS / same in a Alpine container.
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: <redacted>
build:
  artifacts:
    - image: <redacted>
  local:
    push: false
```

### Steps to reproduce the behavior

1. Use the provided (above) skaffold.yaml
2. `skaffold build --file-output=tags.json`
3. `cat tags.json # no tag here`

**Comment by gsquared94** [comment]
adding some details:

<details>
  <summary>Dockerfile</summary>

```
FROM alpine:3.10
```
</details>
<details>
  <summary>skaffold1.yaml</summary>

```
apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
    - image: baseimage
      context: base-app
  local:
    push: true
```
</details>
produces:
<details>
  <summary>tags.json</summary>

```
{
    "builds": [
        {
            "imageName": "baseimage",
            "tag": "gcr.io/google.com/gaghosh-test/baseimage:1ce3e2f@sha256:c8474b4cef4f238a5d9201def7d943ff91b57f316f4b8418b3feb68885e9a369"
        }
    ]
}
```
</details>
<details>
  <summary>skaffold2.yaml</summary>

```
apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
    - image: baseimage
      context: base-app
  local:
    push: false
```
</details>
produces:
<details>
  <summary>tags.json</summary>

```
{
    "builds": [
        {
            "imageName": "baseimage",
            "tag": "gcr.io/google.com/gaghosh-test/baseimage:943ff855383314e5d13bf60b7eea9823ae72f16838b2c306dd94e7c7a0030735"
        }
    ]
}
```
</details>

**Comment by tejal29** [comment]
@IsaacPD this is good first issue to start looking into

**Comment by IsaacPD** [comment]
I began looking into this and did some local modifications to
```go
func (l *localDaemon) TagWithImageID(ctx context.Context, ref string, imageID string) (string, error)
```
to output the image tags as desired, however the subsequent call to 
```go
l.Tag(ctx, imageID, uniqueTag)
```
in ```TagWithImageID``` returns error with message "refusing to create a tag with a digest reference". Further investigation suggest the local docker daemon only accepts tags without digests (the SHA portion/imageID), so skaffold creates a tag out of the digest as seen here https://skaffold.dev/docs/pipeline-stages/taggers/#how-tagging-works and avoids using the tag that is output when ```local.build``` is ```true``` . 

I will continue investigating how the tag is used in ```skaffold deploy``` to see what kind of changes might be necessary to output the "original" tag when using ```skaffold build```.

**Comment by tejal29** [comment]
@IsaacPD sounds good. Thanks for the update. 
It would be great to look into debug or trace output and see what gets replaced in manifests when local build is true.

**Comment by IsaacPD** [comment]
@tejal29 When local build is true the manifest that is passed to kubectl is the same manifest as the one specified in the skaffold config but with the container image replaced by the result from ```skaffold build``` and some additional metadata labels, this goes the same if local build is false. There is no difference in how ```skaffold deploy``` behaves if local.build is true/false.

**Comment by IsaacPD** [comment]
Hey @Djiit,

I just want to clarify some things,
> When I set local.push: false, Skaffold does not write the image tag (only SHA) in the output file

From what I've gathered a tag is in fact output when ```local.push: false``` is set and ```skaffold build``` is run. If we look at the example Gaurav gave

<details>
<summary> example</summary>
<details>
  <summary>skaffold2.yaml</summary>

```
apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
    - image: baseimage
      context: base-app
  local:
    push: false
```
</details>
produces:
<details>
  <summary>tags.json</summary>

```
{
    "builds": [
        {
            "imageName": "baseimage",
            "tag": "gcr.io/google.com/gaghosh-test/baseimage:943ff855383314e5d13bf60b7eea9823ae72f16838b2c306dd94e7c7a0030735"
        }
    ]
}
```
</details>
</details>

the tag is ```943ff85538...``` which is intentionally also the image id that can be seen listed if running ```docker images```. This value is not the same as what is seen after ```@``` in the output when ```local.push: true``` is set, that is known as the digest and is only available when the image has been pushed and can be seen if running ```docker images --digests```.


It would help if you could give some more insight into your use case specifically. For instance, how exactly are you using the output from ```skaffold build``` when you have ```local.push: false```? What issues are presented with the current output and your use case?
