### ISSUE TITLE
Support multiple sync rules

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#4769]
Skaffold should allow configuring multiple sync blocks.  For example:
```yaml
  artifacts:
  - image: skaffold-buildpacks
    buildpacks: {}
    sync:
      auto: {}
      infer: ["**/*.hbs", "**/*.html", "**/*.css"]
```
