### ISSUE TITLE
Support containers that don't need rebuilding on each change

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#477]
Containers that serve static resources such as html, css or javascript shouldn't be built each time there's a change. It's too painful for the users.

With Docker for Desktop and docker-compose, I’d just bind mount the sources and that would be it. No rebuild involved and Live Reload could be setup to smooth the developer experience even more.
What we could do in Skaffold, un dev mode, is let the user bind mount the sources into the container running on the local Kubernetes. That’s not trivial because:
 + The user would have to know what they are doing.
 + Skaffold should at least make it possible to disable rebuild on some artifacts.
 + The bind mounting should be configured in the skaffold.yaml and injected into the kubectl manifests (do we know how to do that?)
 + Or we should support deploying a different list of manifests in dev mode and in run mode: one with the bind mounting (dev) and one without it (run).

**Comment by dgageot** [comment]
I've run some tests on platforms that support sharing files with the host: Docker for Desktop and minikube.

Let's say I'm developing a static website that runs with nginx. My original k8s manifest is:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: web
        image: nginx
```

We could have some kind of configuration at the artifact level in the `skaffold.yaml`:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-example
     watchChanges: false
     mount: ./html:/usr/share/nginx/html
deploy:
  kubectl:
    manifests:
      - k8s-*
```

On Docker for Desktop, Skaffold could then patch the yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: web
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
      volumes:
      - name: html
        hostPath:
          path: /Users/dgageot/[...]/html
```

On minikube, Skaffold could patch a different way:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: web
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
      volumes:
      - name: html
        hostPath:
          path: /skaffold/mount1
```

and make sure this command runs: `minikube mount /Users/dgageot/[...]/html:/skaffold/mount1`
