### ISSUE TITLE
The `profile.deploy` is overridden by the base `deploy`

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#4789]
My skaffold.yaml uses a mixed kustomize (as the basic deployer defined in `.deploy`) and kubectl (as a profile deployer defined in `.profiles.X.deploy`)  

### Expected behavior
`skaffold render -p X` should use the kubectl deployer defined in `.profiles.X.deploy`

### Actual behavior
`skaffold render -p X` uses the kustomize deployer defined in `.deploy`

### Information

- Skaffold version: skaffold/v2beta7
- Operating system: darwin
- Contents of skaffold.yaml:

```yaml
...
deploy:
  kustomize:
    paths:
    - base-config-dir/ # includes the kustomization.yaml files

profiles:
  - name: xxx
    deploy:
      kubectl:
        manifests:
        - config-dir/deployment.yaml # pointed to a specific file. the config-dir has a kustomization.yaml file but this deployer method is `kubectl`
        flags:
          disableValidation: true
```

### Steps to reproduce the behavior

run `skaffold render -p xxx`, the output is `kustomize build` output instead of the simple config-dir/deployment.yaml

**Comment by MarlonGamez** [comment]
When I try to recreate this in skaffold v1.14.0, running `skaffold render -p xxx` outputs the results of running render using both of the deployers, not just one. Here's my skaffold.yaml
```yaml
apiVersion: skaffold/v2beta7
kind: Config
deploy:
  kustomize:
    paths: 
    - ./kustomize/
profiles:
- name: xxx
  deploy:
    kubectl:
      manifests:
      - ./k8s/*
```

**Comment by yuwenma** [comment]
@MarlonGamez Correct! What shall I do if only the profile deployer is expected? (in my example, the expectation is no `kustomize build`)

**Comment by MarlonGamez** [comment]
I'm not completely sure if there is a workaround for that right now. My closest guess would be that you need to create a completely different skaffold.yaml file and specify that using `skaffold render -f other_skaffold.yaml`

This solution is really clunky :/ I'll try and see if there's a better way

**Comment by MarlonGamez** [comment]
@yuwenma I think you should be able to remove the kustomize stanza using profile patches https://skaffold.dev/docs/environment/profiles/#override-via-patches

Your skaffold.yaml would look something like this with a patch to remove the kustomize deploy
```yaml
deploy:
  kustomize:
    paths:
    - base-config-dir/ # includes the kustomization.yaml files

profiles:
  - name: xxx
    deploy:
      kubectl:
        manifests:
        - config-dir/deployment.yaml # pointed to a specific file. the config-dir has a kustomization.yaml file but this deployer method is `kubectl`
        flags:
          disableValidation: true
    patches:
    - op: remove
      path: /deploy/kustomize
```
