### ISSUE TITLE
Skaffold always builds a new image when no file has been changed!

### ISSUE THREAD

**Issue by oo00spy00oo** [GoogleContainerTools/skaffold#4793]
Listing files to watch...
 - [REDACT]
Generating tags...
 - [REDACT] -> [REDACT]:v1.0.3-44-ga3593b2-dirty
Checking cache...
 - [REDACT] Not found. Building

### Expected behavior
In case sync mode is enabled, we should have an option to disable auto-build mode when changing the content of any files!

### Actual behavior:
Skaffold always builds the new image while I didn't change anything in my project.

### Information

- Skaffold version: version: v1.14.0
- Operating system: MacOSX 10.16
- Contents of skaffold.yaml:

``` yaml
apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
    - image: [REDACT]
      sync:
        infer:
          - "**/*.go"
      kaniko:
        dockerfile: Dockerfile.kaniko
  cluster:
    namespace: [REDACT]
    dockerConfig:
      secretName: kaniko-secret
deploy:
  kustomize: {}
```
