### ISSUE TITLE
`skaffold build | skaffold deploy` with `SKAFFOLD_DEFAULT_REPO` rewrites image name twice

### ISSUE THREAD

**Issue by japsu** [GoogleContainerTools/skaffold#4809]
If I set the default repo using `SKAFFOLD_DEFAULT_REPO` and then build and deploy in separate `skaffold build` and `skaffold deploy` steps, then image name rewriting is applied twice, resulting in wrong tag in the deploy step.

This can be worked around by unsetting `SKAFFOLD_DEFAULT_REPO` between the steps or using `skaffold build --default-repo` instead of the env var, but still I think `skaffold deploy` shouldn't try to rewrite tags from `build.json`.

Sample repo illustrating the issue: [japsu/skaffold-image-name-rewriting-bug-example](https://github.com/japsu/skaffold-image-name-rewriting-bug-example)

### Expected behavior

1. `SKAFFOLD_DEFAULT_REPO=… skaffold deploy -a build.json` uses the image tags set in build.json without rewriting again

### Actual behavior

1. `SKAFFOLD_DEFAULT_REPO=… skaffold deploy -a build.json` applies image name rewriting again, resulting in wrong tag

### Information

- Skaffold version: v1.13.2, v1.14.0
- Operating system: macOS 10.15.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: skaffold-bug-example
build:
  artifacts:
  - image: my-hello-world
deploy:
  kubectl:
    manifests:
    - deployment.yaml
```

### Steps to reproduce the behavior

    git clone https://github.com/japsu/skaffold-image-name-rewriting-bug-example
    cd skaffold-image-name-rewriting-bug-example
    export SKAFFOLD_DEFAULT_REPO=myrepo
    skaffold build --file-output=build.json
    #  - my-hello-world -> myrepo/my-hello-world:53de203-dirty
    skaffold deploy -a build.json
    #  - my-hello-world -> myrepo/myrepo_my-hello-world:bf756fb1ae65adf866bd8c456593cd24beb6a0a061dedf42b26a993176745f6b
