### ISSUE TITLE
DIGEST cannot be used to tag images with envTemplate

### ISSUE THREAD

**Issue by afrittoli** [GoogleContainerTools/skaffold#481]
I try to use the envTemplate tag strategy, but it doesn't work as expected because DIGEST is in the form sha265:<digest>:

'''
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_REG}}/{{.IMAGE_REG_NS}}/{{.IMAGE_NAME}}:{{.MY_DIGEST}}"
'''

### Expected behavior

The image tag is `my-registry.me/my-namespace/my-image:<digest>`.

### Actual behavior

The image tag is `my-registry.me/my-namespace/my-image:sha256:<digest>`, which is not valid.

### Information

```
Skaffold version:0.4.0
Operating system: MacOS
Content of skaffold.yaml:

apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: my-image
    docker:
      dockerfilePath: image1/Dockerfile
  - imageName: my-other-image
    docker:
      dockerfilePath: image2/Dockerfile
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_REG}}/{{.IMAGE_REG_NS}}/{{.IMAGE_NAME}}:{{.MY_DIGEST}}"
deploy:
  helm:
    releases:
    - name: development
      chartPath: my-chart
      valuesFilePath: skaffold/helm-values.yaml
      values:
        image1: my-image
        image2: my-other-image
      namespace: default

```

### Steps to reproduce the behavior

  1. skaffold test
