### ISSUE TITLE
File sync & Port forward didn't work

### ISSUE THREAD

**Issue by oo00spy00oo** [GoogleContainerTools/skaffold#4814]
### Expected behavior
- Portforward working.
- Fie sync & hot reload feature work with MIcronaut and Jib.

### Actual behavior
- I am using Micronaut and Jib
- Feature port forward is not working for me.
- And when I made some change in my code all the file are sync already but the hot reload feature didn't work

### Information

- Skaffold version: v1.14.0
- Operating system: MacOSX 10.15.6
- Gradle: 6.6.1
- Jib: 2.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: <REDACTED>
build:
  artifacts:
    - image: <REDACTED>
      jib:
        type: gradle
        args:
          - -Psync
          - -Djib.from.image=adoptopenjdk:11-jre-openj9
      sync:
        auto: {}

deploy:
  kustomize: {}

portForward:
  - resourceType: deployment
    resourceName: <REDACTED>
    port: 8080
```

### Steps to reproduce the behavior
skaffold dev
