### ISSUE TITLE
`skaffold dev` doesn't clean up deployments on Windows

### ISSUE THREAD

**Issue by mattpodolak** [GoogleContainerTools/skaffold#4815]
### Expected behavior
Skaffold cleans up all deployments when dev mode is exited.

### Actual behavior
Skaffold doesn't clean up any deployments when dev mode is exited.

### Information
After pressing `Ctrl + c` in Git Bash to exit dev mode, I see "Cleaning up..." in the logs, which exits immediately. All my services and pods are still running afterwards. I have installed Skaffold using chocolatey.

- Skaffold version: v1.14.0
- Operating system: Windows 10 Education (1909)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false # disable default push to docker hub
  artifacts:
    - image: mattpodolak/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: mattpodolak/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: mattpodolak/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: mattpodolak/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: mattpodolak/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: mattpodolak/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
```

### Steps to reproduce the behavior

1. clone this repo: https://github.com/mattpodolak/mini-mern-ms
2. `skaffold dev` in Git Bash on Windows
3. `Ctrl + c`
4. `kubectl get pods` or `kubectl get services`
