### ISSUE TITLE
Local docker build fails when only the Docker CLI is available

### ISSUE THREAD

**Issue by achedeuzot** [GoogleContainerTools/skaffold#4820]
We’d like to use skaffold to build images in a setup where there is no Kubernetes cluster or docker socket available. 

A docker daemon is available but only works through the docker CLI as there is no local docker socket. We expose a `DOCKER_TLS_VERIFY=1` and `DOCKER_HOST=tcp://host.example.com:1234` environment variables which allows the docker CLI and docker-compose to spawn containers.

When I run `skaffold build`, the image is built but the last step tries to fetch the image tag from the local docker socket <sup>1</sup> which crashes with `couldn't build "some-image": Error response from daemon: Client sent an HTTP request to an HTTPS server.`

<sup>1</sup> see https://github.com/GoogleContainerTools/skaffold/blob/eb86b7f23abdd8d787dd61c8156a533ea9872279/pkg/skaffold/build/local/docker.go#L103

### Expected behavior
skaffold should be shelling out to the CLI to get the image ID rather than trying to use the local daemon client so the `skaffold build` succeeds in the context where only the docker CLI is available.

### Actual behavior
`skaffold build` crashes with `couldn't build "some-image": Error response from daemon: Client sent an HTTP request to an HTTPS server.`

### Information
- Skaffold version: version v1.14.0
- Operating system: Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: some-app
profiles:
  - name: "ci"
    build:
      local:
        useDockerCLI: true
      artifacts:
        - image: some-app-tests
          docker:
            target: "unit-tests"
        - image: some-app-release
          docker:
            target: "release"
```

### Steps to reproduce the behavior

1. have a machine with no local docker socket available but a working docker CLI
2. `skaffold build`
