### ISSUE TITLE
Can not set serviceAccount on kaniko pod

### ISSUE THREAD

**Issue by klingenm** [GoogleContainerTools/skaffold#4823]
### Expected behavior
According to 
https://skaffold.dev/docs/references/yaml/#build-cluster-serviceAccount
https://skaffold.dev/docs/pipeline-stages/builders/docker/#dockerfile-in-cluster-with-kaniko

setting the following:

```yaml    
build:
    cluster:
        serviceAccount: 'some-account'
```
to skaffold.yaml should set the service account for the kaniko pod.

### Actual behavior

    parsing skaffold config: unable to parse config: yaml: unmarshal errors:
      line 7: field serviceAccount not found in type v2beta2.ClusterDetails

### Information

- Skaffold version: v1.14.0
- Operating system: macOS 10.14.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: test
build:
  artifacts:
    - image: test
      kaniko: {}
  cluster:
    serviceAccount: some-account
```

### Steps to reproduce the behavior

1. Take the sample code above
2. `skaffold <any command>`
3. see the error
