### ISSUE TITLE
templated fields on helm "setValueTemplates" object keys

### ISSUE THREAD

**Issue by jearangoo** [GoogleContainerTools/skaffold#4824]
hello, sorry i could not find any examples or documentation so i write my question here, i was trying to set templated fields on the values of a helm chart via "skafold deploy", i looked at the example on the documentation https://skaffold.dev/docs/environment/templating 

then i created this profile with a simple interpolation

```yaml
- name: set-trigger-values
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates
        value:
          "test-subchart":
            image:
              tag: "{{.TRIGGER_COMMIT_SHA}}"
```

executed 

skaffold deploy -p set-trigger-values

and it worked as expected, skaffold interpolated the environment variable "TRIGGER_COMMIT_SHA" into "test-subchart.image.tag".

but then i tried to set the key "test-subchart" dinamically modifying the profile like this

```yaml
- name: set-trigger-values
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates
        value:
          "{{.TRIGGER_SUBCHART_NAME}}":
            image:
              tag: "{{.TRIGGER_COMMIT_SHA}}"
```

and in the generated yaml was not interpolated the key "{{.TRIGGER_SUBCHART_NAME}}", but only was interpolated the value "{{.TRIGGER_COMMIT_SHA}}"

### Expected behavior

i wanted to ask if it is possible to interpolate

"{{.TRIGGER_SUBCHART_NAME}}.image.tag": "{{.TRIGGER_COMMIT_SHA}}" 

as one would do via "helm upgrade"

helm upgrade stable /chart-path -n test --set "${TRIGGER_SUBCHART_NAME}.image.tag=${TRIGGER_COMMIT_SHA}"

### Actual behavior

in the generated yaml was only interpolateted object values but not object keys

### Information

- Skaffold version: v1.14.0
- Operating system: mac os 10.15.7
- Contents of skaffold.yaml:

```yaml
- name: set-trigger-values
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates
        value:
          "{{.TRIGGER_SUBCHART_NAME}}":
            image:
              tag: "{{.TRIGGER_COMMIT_SHA}}"
```

### Steps to reproduce the behavior
1. set environment variables TRIGGER_SUBCHART_NAME and TRIGGER_COMMIT_SHA
2. run skaffold deploy -p set-trigger-values
