### ISSUE TITLE
`skaffold render` doesn't respect `--build-artifacts` flag.

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#4825]
I ran into this when using skaffold image in gitlab-ci pipeline.

### Expected behavior
According to the doc https://skaffold.dev/docs/references/cli/#skaffold-render 
`skaffold render --build-artifacts=XXX` should use the previous build image info stored in XXX to render the manifest. 

### Actual behavior
`--build-artifacts` are ignored. `Skaffold render` uses another image.

### Information
- Skaffold version: gcr.io/k8s-skaffold/skaffold:v1.14.0

- Contents of skaffold-ci.yaml:

```yaml
apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: app-template
build:
  artifacts:
  - image: app
profiles:
  - name: ci
    build:
      cluster:
        dockerConfig:
          path: ~/.docker/config.json          
  - name: staging-west
    deploy:
      kubectl:
        manifests:
        - config/envs/staging-west/deployment.yaml
        flags:
          disableValidation: true
```

- Contents of gitlab-ci.yaml

```yaml
- cat image_name
- skaffold render --build-artifacts=image_name --filename=skaffold-ci.yaml --add-skaffold-labels=false --digest-source=remote -p staging-west
```
logs 
<img width="834" alt="Screen Shot 2020-09-25 at 6 36 54 PM" src="https://user-images.githubusercontent.com/5606098/94327251-78fbd480-ff5e-11ea-9725-7b3a27fe675c.png">

**Comment by nkubala** [comment]
i just tried this out on the getting-started example and it seems to be working fine:

```
➜  getting-started git:(master) skaffold build -d gcr.io/nkubala-demo --file-output=build.json
Generating tags...
 - skaffold-example -> gcr.io/nkubala-demo/skaffold-example:v1.15.0-1-g85bea9ccd
Checking cache...
 - skaffold-example: Found. Tagging
➜  getting-started git:(master) cat build.json 
{"builds":[{"imageName":"skaffold-example","tag":"gcr.io/nkubala-demo/skaffold-example:v1.15.0-1-g85bea9ccd@sha256:2d93ec52695c70a21e517c5132f0254fd15e6d50882e6b9c6e1712bd2aa9080d"}]}%              
➜  getting-started git:(master) skaffold render --build-artifacts=build.json
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 96ecc1c6-8613-4208-b3e2-7eeb611cae36
  name: getting-started
  namespace: default
spec:
  containers:
  - image: gcr.io/nkubala-demo/skaffold-example:v1.15.0-1-g85bea9ccd@sha256:2d93ec52695c70a21e517c5132f0254fd15e6d50882e6b9c6e1712bd2aa9080d
    name: getting-started
```

`"image <image> is not used by the deployment` is thrown when skaffold can't find an image name from a build artifact in your manifests, which often happens when either you didn't correctly set your default repo, or there's a typo in your image. can you double check these?
