### ISSUE TITLE
skaffold debug when using helm does not work when helm chart renders more than one manifest

### ISSUE THREAD

**Issue by doriandekoning** [GoogleContainerTools/skaffold#4826]
### Expected behavior
When running `skaffold debug` with a helm deployment (supported by https://github.com/GoogleContainerTools/skaffold/pull/4732)  which renders multiple manifests the deployment is modified and a debugging port is forwarded to my machine.
### Actual behavior
Debugging does not work, without any error or warning.
### Information

- Skaffold version: version: `v1.14.0-40-gf4bd6387c`
- Operating system: Darwin
- Contents of skaffold.yaml: 

```yaml
apiVersion: skaffold/v2beta5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: "[redacted]"
      custom:
        buildCommand: "make docker_build_service SERVICE={{.SERVICE}}"
  local: {}
deploy:
  helm:
    releases:
      - name: "{{.SERVICE}}"
        chartPath: "weave/service"
        remote: true
        namespace: [redacted]
        upgradeOnChange: true
        recreatePods: true
        valuesFiles:
          - "../[recacted]/default_svc_values.yaml"
          - "../[redacted[/services/{{.SERVICE}}.yaml"
        setValues:
          skaffold: "true"
        artifactOverrides:
          image: "[redacted]"
        setValueTemplates:
          name: "{{.SERVICE}}"
          fullnameOverride: "{{.SERVICE}}"
          hosts[0]: "{{.SERVICE}}.{{.CLUSTER_HOST}}"
          grpctranscoding.apidescriptor_b64: "{{.API_DESCRIPTOR}}"


```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold debug  -f skaffold.yaml --cache-artifacts=false --verbosity=info --port-forward`

I've fixed this issue and will open an MR with a (I believe trival) fix.
