### ISSUE TITLE
Skaffold fails to build an artifact when run in TravisCI.

### ISSUE THREAD

**Issue by nushkovg** [GoogleContainerTools/skaffold#4840]
When I am trying to run a pipeline in TravisCI to make sure that Skaffold is starting, I am getting the following error on the first image build: `exiting dev mode because first build failed: couldn't build "example-dnsutils": the custom script didn't produce an image with tag`.

I am emulating an ARM architecture, because the application runs on a Raspberry PI. The Skaffold binary that I am using is compiled by me with `GOARCH=arm make`. Travis does not support `armhf` architecture, therefore I have to emulate it. Everything before that runs without an issue, this error appears at the end of the build (which is created with BuildKit enabled). I have tried changing different distributions in Travis, but without luck. Here is the `travis.yml`:

```yaml
os: linux
dist: focal

env:
  global:
  - PATH=$TRAVIS_BUILD_DIR/bin:$PATH 

git:
  submodules: false

services:
  - docker

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name travis --driver docker-container --use
  - docker buildx inspect --bootstrap
install:
  - pip install kubepi
  - kubepi setup init
  - kubepi platform init
  - kubepi k3d create
before_script:
  - kubectl -n traefik create secret generic namesilo --from-literal='test'
  - kubectl -n monitoring create secret generic grafana --from-literal='GF_SECURITY_ADMIN_PASSWORD=test'
  - kubectl -n traefik create secret generic traefik-forward-auth --from-literal='PROVIDERS_GENERIC_OAUTH_CLIENT_ID=test' --from-literal='PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=test' --from-literal='SECRET=test'
script:
  - skaffold dev --port-forward --force=false --cleanup=true
```

### Expected behavior

Skaffold builds the image and the pipeline succeeds.

### Actual behavior

Skaffold fails with the following output: `exiting dev mode because first build failed: couldn't build "example-dnsutils": the custom script didn't produce an image with tag`. Also, check the pipeline result: https://travis-ci.org/github/nushkovg/k1s/builds/731737231

### Information

- Skaffold version: v1.15.0
- Operating system: Ubuntu Focal 20.04 in TravisCI
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta7
kind: Config
build:
  local:
    push: false
    useBuildkit: true
  artifacts:
  - context: platform/k1s-dnsutils
    image: k1s-dnsutils
  - context: platform/k1s-error-pages
    image: k1s-error-pages
  - context: platform/k1s-ui
    image: k1s-ui

profiles:
  - name: dev
    activation:
      - command: dev
    
    build:
      artifacts:
      - context: platform/k1s-dnsutils
        image: k1s-dnsutils
        custom:
          buildCommand: ./scripts/build.sh
        sync: {}
      - context: platform/k1s-error-pages
        image: k1s-error-pages
        custom:
          buildCommand: ./scripts/build.sh
        sync: {}
      - context: platform/k1s-ui
        image: k1s-ui
        custom:
          buildCommand: ./scripts/build.sh
        sync: {}

    deploy:
      statusCheckDeadlineSeconds: 1300
      helm:
        releases:
        - name: k1s-traefik
          namespace: k1s
          chartPath: infrastructure/k1s-traefik
          valuesFiles:
          - infrastructure/helm-values.yaml
          artifactOverrides:
            traefik.cron.image: k1s-dnsutils
        - name: k1s-error-pages
          namespace: k1s
          chartPath: infrastructure/k1s-error-pages
          valuesFiles:
          - infrastructure/helm-values.yaml
          artifactOverrides:
            pages.image: k1s-error-pages
        - name: k1s-oauth
          namespace: k1s
          chartPath: infrastructure/k1s-oauth
          valuesFiles:
          - infrastructure/helm-values.yaml
        - name: k1s-prometheus
          namespace: k1s
          chartPath: infrastructure/k1s-prometheus
          valuesFiles:
          - infrastructure/helm-values.yaml
        - name: k1s-grafana
          namespace: k1s
          chartPath: infrastructure/k1s-grafana
          valuesFiles:
          - infrastructure/helm-values.yaml
        - name: k1s-kube-dashboard
          namespace: k1s
          chartPath: infrastructure/k1s-kube-dashboard
          valuesFiles:
          - infrastructure/helm-values.yaml
        - name: k1s-ui
          namespace: k1s
          chartPath: infrastructure/k1s-ui
          valuesFiles:
          - infrastructure/helm-values.yaml
          artifactOverrides:
            ui.image: k1s-ui

```

### Steps to reproduce the behavior

1. Run a TravisCI pipeline like the one above
