### ISSUE TITLE
Skaffold will always return error adding artifacts to cache when builds are not local

### ISSUE THREAD

**Issue by ricardo-larosa** [GoogleContainerTools/skaffold#4848]
### Expected behavior
Cache is populated with built artifacts avoiding rebuilding images every time
Related to https://github.com/GoogleContainerTools/skaffold/issues/4842 and https://github.com/GoogleContainerTools/skaffold/issues/4753

### Actual behavior
```
WARN[0087] error adding artifacts to cache; caching may not work as expected: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? 
```
### Information

- Skaffold version: v1.14/v1.15
- Operating system: linux/macos
- Contents of skaffold.yaml: Any configuration with no local build
Example:
```yaml
profiles:
- name: oncluster
  build:
    artifacts:
    - image: registry.whatever/image-name
      kaniko:
        image: gcr.io/kaniko-project/executor:v1.0.0
        flags: 
          - --snapshotMode=redo
          - --verbosity=info
    cluster:
      annotations:
        sidecar.istio.io/inject: "false" # if you are not running istio comment it
      dockerConfig: 
        secretName: my-dockerconfigjson # is Opaque
      namespace: default
```

### Steps to reproduce the behavior

1. Use a profile oncluster that builds images remotely (kaniko, etc..)
2. Run `build -p oncluster --cache-file /a/local/path --verbosity trace`
3. Everything runs ok
4. Cache file is populated with latest build image
Now repeat, but before step 2 stop your local docker deamon
you will get this error:
```
WARN[0087] error adding artifacts to cache; caching may not work as expected: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? 
```
and the cache file is not populated
