### ISSUE TITLE
unable connect Kubernates minikube

### ISSUE THREAD

**Issue by erwanriou** [GoogleContainerTools/skaffold#4849]
```
Listing files to watch...
 - erwanriou/microapp_client
 - erwanriou/microapp_comments
 - erwanriou/microapp_event-bus
 - erwanriou/microapp_moderation
 - erwanriou/microapp_posts
 - erwanriou/microapp_query
Generating tags...
 - erwanriou/microapp_client -> erwanriou/microapp_client:5622724
 - erwanriou/microapp_comments -> erwanriou/microapp_comments:5622724
 - erwanriou/microapp_event-bus -> erwanriou/microapp_event-bus:5622724
 - erwanriou/microapp_moderation -> erwanriou/microapp_moderation:5622724
 - erwanriou/microapp_posts -> erwanriou/microapp_posts:5622724
 - erwanriou/microapp_query -> erwanriou/microapp_query:5622724
Checking cache...
 - erwanriou/microapp_client: Found Locally
 - erwanriou/microapp_comments: Found Locally
 - erwanriou/microapp_event-bus: Found Locally
 - erwanriou/microapp_moderation: Found Locally
 - erwanriou/microapp_posts: Found Locally
 - erwanriou/microapp_query: Found Locally
Tags used in deployment:
 - erwanriou/microapp_client -> erwanriou/microapp_client:a8c929eb832fc648dc82f6e66c1b5dabd78c10b2465bfe25e20f67a7a4198b91
 - erwanriou/microapp_comments -> erwanriou/microapp_comments:f8f40605c79ae68922b6b3c61032d71b7a4fcec3c79d44f5e16485ab34a17dfa
 - erwanriou/microapp_event-bus -> erwanriou/microapp_event-bus:fa2b38809f616619d7a880ab6c117252898c91b6401272bbd0ea9d530c567d15
 - erwanriou/microapp_moderation -> erwanriou/microapp_moderation:f48020e94cde138f31a6e7ebdf2b0c206bcb2e7edfaaefedf2f0abb4929d1cc1
 - erwanriou/microapp_posts -> erwanriou/microapp_posts:2ce82388474e27272ee63d0f7e93fee138a6a2ad8664062506c33099cb906a69
 - erwanriou/microapp_query -> erwanriou/microapp_query:042a9d1135cce9e630c31bc2321f2861804d934672ea9199861408dcdab02fb0
exiting dev mode because first deploy failed: unable to connect to Kubernetes: Get "https://192.168.99.100:8443/version?timeout=32s": dial tcp 192.168.99.100:8443: connect: connection refused
```

### Expected behavior
To run succefully the build
### Actual behavior
Failing on not been able to connect the minikube IP
### Information

- Skaffold version: v1.15.0
- Operating system: Ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: erwanriou/microapp_client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: erwanriou/microapp_comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: erwanriou/microapp_event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: erwanriou/microapp_moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: erwanriou/microapp_posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: erwanriou/microapp_query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
```

### Steps to reproduce the behavior

> git clone https://github.com/erwanriou/microappservices
> update ect/host with minikube Ip --> posts.com
> `skaffold dev`
