### ISSUE TITLE
STATUSCHECK_IMAGE_PULL_ERR for an image that was pushed to repo in build phase

### ISSUE THREAD

**Issue by go-nelango** [GoogleContainerTools/skaffold#4851]
In my skaffold dev session, build phase succeed and images were pushed to the repo, but deployment failed with STATUSCHECK_IMAGE_PULL_ERR.

### Expected behavior
Images should pulled successfully from the repo as they were just pushed to it in the build phase.

### Actual behavior
Deployment phase with STATUSCHECK_IMAGE_PULL_ERR.
**Logs (summary):**
```
Running "Run on Kubernetes" configuration (.vscode/launch.json) in Run mode

To view more detailed logs, go to Output channel : "Run on Kubernetes - Detailed"

Update initiated due to file change
Build started for artifact go-hello-world
Build completed for artifact go-hello-world

Deploy started
Deploy complete

Status check started
Resource pod/go-hello-world-554bbbbc57-csf5j status failed with container server is waiting to start: gcr.io/cloud-code-285423/go-hello-world:latest@sha256:9cbb767c622d87f5fef073c11101e8c5838f82d93d3e892c58d234129b08de60 can't be pulled
Resource deployment/go-hello-world status failed with waiting for rollout to finish: 0 of 1 updated replicas are available...

Status check failed

Update failed with error code STATUSCHECK_IMAGE_PULL_ERR
exiting dev mode because first deploy failed: 1/1 deployment(s) failed
Exited with code 1.
```

### Information

- Skaffold version: v1.14.0 
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: go-hello-world
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
```

### Steps to reproduce the behavior

Run Cloud Code sample K8 app - Go: Hello World on vscode - https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/golang/go-hello-world
