### ISSUE TITLE
Remove warning message  "The additionalFlags field in kaniko is deprecated"

### ISSUE THREAD

**Issue by ricardo-larosa** [GoogleContainerTools/skaffold#4852]
Recently kaniko v1.0.0 https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.0.0
Introduced flags like: `--snapshotMode=redo`, `--use-new-run` and `--snaphotMode=ful` which introduces significant optimizations that are not possible to be activated via environment variables

For this reason deprecating `additionalFlags` for kaniko builds should be put on hold and to avoid confusion the warning message should be removed.
That message have been there since https://github.com/GoogleContainerTools/skaffold/pull/1797

### Current Behaviour 
```
level=warning msg="The additionalFlags field in kaniko is deprecated, please consult the current schema at skaffold.dev to update your skaffold.yaml."
```

### Information

- Contents of skaffold.yaml:

```yaml
profiles:
- name: oncluster
  build:
    artifacts:
    - image: myregistry/myimage:mytag
      kaniko:
        image: gcr.io/kaniko-project/executor:v1.0.0
        flags: 
          - --snapshotMode=redo
          - --verbosity=info
```

### Steps to reproduce the behavior

1. Use the manifest above
2. `skaffold build -p oncluster`
