### ISSUE TITLE
Accept render output in `skaffold deploy`

### ISSUE THREAD

**Issue by ekupershlak** [GoogleContainerTools/skaffold#4856]
Using `skaffold render` to produce a static configuration that can later be deployed (and redeployed) is useful in delivery workflows. However, there is currently no way to provide a rendered manifest to `skaffold deploy`.

### Expected behavior
`skaffold deploy` can be run with a previously rendered manifest

**Comment by viglesiasce** [comment]
As a stop gap you could set up a re-deployment profile and use `skaffold deploy -p re-deploy`

```yaml
apiVersion: skaffold/v2beta8
kind: Config
deploy:
  kustomize:
    paths:
    - dev/
profiles:
- name: re-deploy
  deploy:
    kustomize:
      manifests:
      - manifest.yaml
```
