### ISSUE TITLE
cannot use environment variables in helm templates

### ISSUE THREAD

**Issue by jstrachan** [GoogleContainerTools/skaffold#486]
this came up here: 
https://github.com/GoogleContainerTools/skaffold/issues/361#issuecomment-380723998

I think we need a way to pass in template expressions to helm chart values, like we do for `envTemplates` so that we can pass in, say, the local docker registry ip/port or private registry via environment variables like we can do for building the docker image name.

**Comment by afrittoli** [comment]
Yeah, that would be handy.
The same could be used also to pull in secrets from environment variables securely set by the CI engine.

**Comment by jstrachan** [comment]
here's a little PR that implements this. 

e.g. I could use the following `skaffold.yaml` with the private local docker registry inside a pod in Jenkins X:
```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST}}:{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT}}/jenkinsx/demo100:{{.VERSION}}"
  artifacts:
  - workspace: .
    docker: {}
  local: {}
deploy:
  helm:
    releases:
    - name: demo100
      chartPath: charts/demo100
      namespace: jx
      setValueTemplates:
        image.repository: "{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST}}:{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT}}/jenkinsx/demo100"
        image.tag: "{{.VERSION}}"
```
