### ISSUE TITLE
`skaffold render` should accept tagged images

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#4874]
### Expected behavior
skaffold render should be able to update the new tag to the image. 

For example, if the old tag is 2020-09-28_0000 and the new tag is 2020-09-28_1111 , [this change](https://screenshot.googleplex.com/Bjvokr4Qikn4RfW.png) should happen in deployment.yaml files.

### Actual behavior
Skaffold does not update but attach the new tag (See [here](https://screenshot.googleplex.com/5jLAznJXNM3re2k.png)). This results in an increasing image tag and eventually hits the max length limitation.

### Information

- Skaffold version: v1.14
- Operating system: linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. Run "skaffold render", get the full image url from the stdout. 
2. Replace the full image url with the pod.yaml "image" field.
3. Run "skaffold render" again.

pod.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
spec:
  containers:
  - name: getting-started
    image: skaffold-example
```

### Proposal

Per offline discussion w/ @nkubala , we expect `skaffold render` to accept a new flag "--ignoreTag=<bool>". When enabled, "skaffold render" will replace the image tag with the new tag instead of appending the tag at the image tail.

**Comment by nkubala** [comment]
the reason we designed skaffold this way is so users wouldn't get themselves into an unpredictable situation when deploying with skaffold. if a user provided a manifest with an existing tag and ran `skaffold run`, skaffold might build and deploy a different image than the one they expected (with the provided tag before running), which could produce some unexpected and potentially dangerous results (e.g. deploying to prod).

technically speaking this is possible in skaffold, but we should make sure we don't enable users to do things they don't mean to do, and that the UX is intuitive. `--ignore-tags` should probably be an all-or-nothing flag (i.e. you can't pass a specific flag you want to ignore - either ignore all, or replace all). we'd also probably want to at the very least issue a warning or something clear to the user that any previously built images with skaffold are **not** being used by the deployment if that flag is provided. what happens if `--build-artifacts` is provided? does the provided tag on the image take precedence, or the one built by skaffold?

we should also consider how this factors into a few other FRs related to render/deploy:
* deploying previously rendered results (https://github.com/GoogleContainerTools/skaffold/issues/4856), since this would need to skip the build/tag replacement of the rendered manifests, and just deploy them as is
* deploying untagged/unbuilt resources (https://github.com/GoogleContainerTools/skaffold/issues/3559), since this would require the deployer to stop validating build artifacts against deploy resources

**Comment by tejal29** [comment]
This issue is approaching SLO. Any takers @marlon-gamez @nkubala @yuwenma @gsquared94 @IsaacPD

**Comment by IsaacPD** [comment]
I'll try and get a fix available

**Comment by IsaacPD** [comment]
I have not actually been able to reproduce the behavior as described here. I tried it on the examples/getting-started project

1. skaffold render
-- Outputs ```gcr.io/isaacpd-test/skaffold-example:1277ddcd3b1e840c76abe71d1d35fd1716a0cb87be41fa145a3e12ec0f2e2eb8``` for the image name
2. Copy the output for the image name into k8s-pod.yaml 
```yaml
containers: 
- name: getting-started 
  image: gcr.io/isaacpd-test/skaffold-example:1277ddcd3b1e840c76abe71d1d35fd1716a0cb87be41fa145a3e12ec0f2e2eb8
```
3. skaffold render again

All that I see in the output is the same image name that was output as the original "skaffold render". I'm not getting the scenario where the tag is appended onto the tag in the manifest.
