### ISSUE TITLE
`skaffold build` fails unpredictably with secret “docker-cfg” 

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#4875]
`skaffold build` uses [a hard-coded secret “docker-cfg”](https://github.com/GoogleContainerTools/skaffold/blob/b9bb604094b00c8824a4ea2359a975e15dfd9db6/pkg/skaffold/constants/constants.go#L50) as the default docker build. When  `.build.dockerConfig.secretName` is not provided, this default secret is supposed to be created. However, this fails unpredictably in either ways:
 
If `.build.dockerConfig.secretName` is not provided, `skaffold build` fails *sometimes* with errors  "setting up docker config secret: creating docker config secret "docker-cfg": secrets "docker-cfg" already exists".  
If `.build.dockerConfig.secretName` is provided (when above error happens, using secret docker-cfg),  `skaffold build` fails sometimes with errors "setting up docker config secret: checking for existing kaniko secret: secrets "docker-cfg" not found"

### Information

- Skaffold version: v1.14
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: app
profiles:
  - name: default-case
    build:
      cluster:
        dockerConfig:
          path: ~/.docker/config.json
  - name: failover-case
    build:
      cluster:
        dockerConfig:
          secretName: docker-cfg
```

### Steps to reproduce the behavior

1. Setup a gitlab env based on this [user manual](https://github.com/GoogleCloudPlatform/solutions-modern-cicd-anthos/blob/master/docs/index.md).
2. Use [this](https://github.com/GoogleCloudPlatform/solutions-modern-cicd-anthos/tree/app-delivery/starter-repos/app-template) as sample app (in app-delivery branch)  
3. Watch the skaffold-build step in gitlab CICD UI, corresponding skaffold config is [here](https://github.com/GoogleCloudPlatform/solutions-modern-cicd-anthos/blob/app-delivery/starter-repos/app-template/skaffold-ci.yaml#L11)
