### ISSUE TITLE
use profiles to allow separate configurations for `skaffold run` v `skaffold dev`

### ISSUE THREAD

**Issue by jstrachan** [GoogleContainerTools/skaffold#488]
so in [Jenkins X](http://jenkins-x.io/developing/promote/) we need quite different configurations for using `skaffold run` versus `skaffold dev`:

* `skaffold run` used inside CI/CD pipelines in Jenkins X. We pass in env vars for the registry + the `$VERSION` as an environment variable for the Preview or Release version. We typically disable the `deploy` part of skaffold using [an empty manifest section](https://github.com/jstrachan/demo100/blob/master/skaffold.yaml#L12-L14) as we want to deploy by publishing the newly built chart version to chartmuseum then using [GitOps promotion](http://jenkins-x.io/developing/promote/) to run it
* `skaffold dev` used inside a [DevPod](http://jenkins-x.io/developing/devpods/) to incrementally deploy each version directly via the helm chart; using the `{{.DIGEST}}` version (once [this](https://github.com/GoogleContainerTools/skaffold/issues/481) and [this](https://github.com/GoogleContainerTools/skaffold/issues/486) are fixed) 

The `skaffold run` is working great. What I'd like is that the same `skaffold.yaml` could be used for a simple CLI inside the CI/CD pipelines but also for `skaffold dev` - ideally without the user needing to know anything at all about skaffold or its CLI.

I stumbled over the profiles stuff a little while ago which looks like just the thing. 

If I'm understanding the code + idea, folks can specify extra profiles on the CLI which then if they are in the `skaffold.yaml` file they get activated right?

I wonder what folks thought of having a canonical profile name for `skaffold run` and `skaffold dev` so that if folks wanna configure specific stuff for `dev` or `run` modes they can?
 
i.e. if you wanted to add some, say, `skaffold dev` specific configuration you could just use a profile like:
```yaml 
apiVersion: skaffold/v1alpha2
kind: Config
profiles:
- name: run
  build:
    tagPolicy:
      envTemplate:
        template: "{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST}}:{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT}}/{{.ORG}}/{{.APP_NAME}}:{{.VERSION}}"
    artifacts:
    - imageName: changeme
      workspace: .
      docker: {}
    local: {}
  deploy:
    kubectl:
      manifests:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST}}:{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT}}/jenkinsx/demo100:{{.DIGEST}}"
    artifacts:
    - workspace: .
      docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: demo100
        chartPath: charts/demo100
        namespace: jx
        setValueTemplates:
          image.repository: "{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST}}:{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT}}/jenkinsx/demo100"
          image.tag: "{{.DIGEST}}"
```
So that `skaffold dev` would be kinda like `skaffold dev -p dev`
