### ISSUE TITLE
Update docs on behaviour of tryImportMissing

### ISSUE THREAD

**Issue by StarpTech** [GoogleContainerTools/skaffold#4889]
### Expected behavior

A code change in the docker image should produce a different hash and cause a rebuild of the image.

### Actual behavior

Skaffold reports that the image **could be found** remotely. I double-checked it.

### Information

- Skaffold version: v1.15.0
- Operating system: Windows

```yaml
apiVersion: skaffold/v2beta8
kind: Config
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    tryImportMissing: true

profiles:
  - name: web
    build:
      artifacts:
        - image: eu.gcr.io/x/webapp
          context: frontpage
          docker:
            buildArgs:
              API_HOST: https://x.de
```

Github workflow

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache skaffold image builds & config
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/
          key: fixed
```
