### ISSUE TITLE
Docker build commands

### ISSUE THREAD

**Issue by clanstyles** [GoogleContainerTools/skaffold#491]
I have the following folder structure:

```
/project/servicea/
/project/serviceb/
/project/library/
```

I need to build the docker containers with some command line arguments to include the parent directory. The command is as follows:

```docker build -f merchant-api/Dockerfile ../```

This works great. I don't know if I can get this working with Skaffold.

```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/xxx/merchant-api
    workspace: ./merchant-api
    docker:
      dockerfilePath: Dockerfile
```

How can I include the second param '../' to the docker build command?

**Comment by clanstyles** [comment]
I need to include two directories, the parent and the actual service. That's the only way I could find to build the project without having a Forbidden path error.

If I set the workspace as the parent, will that harm other artifacts using the same work space? I still am unsure how to provide two params to build the Dockerfile and the additional directory.

**Comment by clanstyles** [comment]
```
	args := append([]string{"build", "--tag", artifact.ImageName, "-f", artifact.DockerArtifact.DockerfilePath}, buildArgs...)
	args = append(args, ".")
```

I think I need to place them in buildArgs, after looking at the source buildArgs is a ```map[string]*string```. I don't need a value, so I don't think that additional path is supported?

**Comment by clanstyles** [comment]
Solution:

```
  - imageName: gcr.io/xxx/merchant-api
    workspace: ./merchant-api
    docker:
      dockerfilePath: Dockerfile
      buildArgs:
        '../': 0
```

This was the solution. After digging into the Docker client code, you can specify 0 to ignore the value.
