### ISSUE TITLE
default Dockerfile not applied for profiles

### ISSUE THREAD

**Issue by jstrachan** [GoogleContainerTools/skaffold#493]
### Expected behavior

Defining a `build` in a profile should inherit the default `Dockerfile` and workspace of `.` so that it behaves the same as a regular `build` in the root directory.

e.g. moving

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - workspace: .
    docker: {}
```

to be

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
profiles:
- name: run
  build:
    artifacts:
    - workspace: .
      docker: {}
```

should not change the behaviour. Whereas the latter barfs as it can't find the `Dockerfile`

### Actual behavior

Currently defaults of `.` on workspace and `Dockerfile` for the `dockerfilePath`  are only applied on the root `build` not when applying profiles.

Test case and fix on the way
