### ISSUE TITLE
Sync detects changes correctly but not restarting the container (locally)

### ISSUE THREAD

**Issue by ranihorev** [GoogleContainerTools/skaffold#4938]
I'm running Skaffold locally with minikube in dev mode, and I'd like the container to update once I make changes in my source code. Skaffold detects and syncs the changes as expected but for some reason, it doesn't rebuild and re-run the image.
I also tried using the polling trigger but there was no difference. 

Am I doing anything wrong?

Here is an example of the log I'm seeing:

```
INFO[0253] files modified: [src/logger.py]              
Syncing 1 files for web-server:2da9350316777e6987260f4c703b6c4a65c41b0c77e6508366cbce877f90daea
INFO[0254] Copying files: map[src/logger.py:[/usr/app/src/logger.py]] to web-server:2da9350316777e6987260f4c703b6c4a65c41b0c77e6508366cbce877f90daea 
Watching for changes every 1s...
```

Notes: 
- It used to work and I can't recall any changes that might have caused it to stop working.
- If I change the Dockerfile that lies outside of the sync folder skaffold rebuilds the container as expected

### Information

- Skaffold version: 1.15.0
- Operating system: OSX 10.15
- minikube version: v1.14.0

```yaml
apiVersion: skaffold/v2beta3
kind: Config

profiles:
  - name: dev
    activation:
      - kubeContext: minikube
        command: dev
    build:
      artifacts:
        - image: web-server
          context: .
          docker:
            dockerfile: Dockerfile
          sync:
            infer:
              - src/**/*
      local:
        push: false

```
