### ISSUE TITLE
Skaffold dev uses older deployment pod state as new deployment error

### ISSUE THREAD

**Issue by taisph** [GoogleContainerTools/skaffold#4947]
### Expected behavior

While `skaffold dev` is running, a new deployment should not be marked as failed if a previous deployment is in backoff state or exits with an error when terminated.

### Actual behavior

As seen below, `pod/my-service-v1-6d576c8f74-48qhc` is the new pod created by the new deployment cycle where the two previous attempts are in backoff mode. The older deployments are terminated by Kubernetes as soon as the new deployment enters the running state which can be seen in the kubectl output below.

```
Starting deploy...
 - deployment.apps/my-service-v1 configured
Waiting for deployments to stabilize...
 - deployment/my-service-mydb-v1 is ready. [1/2 deployment(s) still pending]
 - deployment/my-service-v1: container mycontainer is backing off waiting to restart
    - pod/my-service-v1-6bb8d85cd6-t527f: container mycontainer is backing off waiting to restart
      > Error retrieving logs for pod my-service-v1-6bb8d85cd6-t527f. Try `kubectl logs my-service-v1-6bb8d85cd6-t527f -n default -c mycontainer`
    - pod/my-service-v1-6d576c8f74-48qhc: creating container mycontainer
    - pod/my-service-v1-9d46d76b5-l6279: container mycontainer is backing off waiting to restart
      > Error retrieving logs for pod my-service-v1-9d46d76b5-l6279. Try `kubectl logs my-service-v1-9d46d76b5-l6279 -n default -c mycontainer`
 - deployment/my-service-v1 failed. Error: container mycontainer is backing off waiting to restart.
WARN[1832] Skipping deploy due to error: 1/2 deployment(s) failed 
Watching for changes...
```

```
# kubectl --context kind-project get pods
NAME                                 READY   STATUS        RESTARTS   AGE
my-service-mydb-v1-85554dc6b-zpxkr   1/1     Running       0          30m
my-service-v1-6bb8d85cd6-t527f       0/1     Terminating   6          6m13s
my-service-v1-6d576c8f74-48qhc       1/1     Running       0          5s
my-service-v1-9d46d76b5-l6279        0/1     Terminating   6          7m59s
```

### Information

- Skaffold version: v1.14.0
- Operating system: Ubuntu 20.04.1 LTS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta7
kind: Config

build:
  artifacts:
  - image: project-my-service
    context: .
    docker:
      dockerfile: build/Dockerfile

deploy:
  kustomize:
    paths:
    - deployments/my_service
  kubeContext: kind-project
  statusCheckDeadlineSeconds: 300

profiles:
- name: development
  activation:
  - command: dev
  deploy:
    kustomize:
      paths:
      - deployments/my_service
      - deployments/dev
    kubeContext: kind-project

portForward:
- resourceType: service
  resourceName: my-service
  port: 8080
```
