### ISSUE TITLE
User-defined port forwarding resources ignore the namespace flag

### ISSUE THREAD

**Issue by anshlykov** [GoogleContainerTools/skaffold#4950]
### Expected behavior

if the namespace is not explicitly set in the configuration file for the port forwarding resource and the `--namespace` flag is set then scaffold uses namespace from the flag
### Actual behavior

Skaffold uses `default` or current namespace

### Information

- Skaffold version: v1.15.0
- Operating system: macOS
- Contents of skaffold.yaml: `integration/examples/microservices/skaffold.yaml`

```yaml
apiVersion: skaffold/v2beta9
kind: Config
build:
  artifacts:
    - image: leeroy-web
      context: leeroy-web
    - image: leeroy-app
      context: leeroy-app
deploy:
  kubectl:
    manifests:
      - leeroy-web/kubernetes/*
      - leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
```

### Steps to reproduce the behavior

1. cd integration/examples/microservices
1. kubectl create ns test
1. skaffold run --namespace test --default-repo gcr.io/k8s-skaffold --port-forward

```
$ skaffold run --namespace test --default-repo gcr.io/k8s-skaffold --port-forward
Generating tags...
 - leeroy-web -> gcr.io/k8s-skaffold/leeroy-web:latest
 - leeroy-app -> gcr.io/k8s-skaffold/leeroy-app:latest
Some taggers failed. Rerun with -vdebug for errors.
Checking cache...
 - leeroy-web: Found Locally
 - leeroy-app: Found Locally
Tags used in deployment:
 - leeroy-web -> gcr.io/k8s-skaffold/leeroy-web:b524e280cc40c0599deea2c3fb17f5fc9c9ff9039328d4962e604759d8534d3d
 - leeroy-app -> gcr.io/k8s-skaffold/leeroy-app:a4a2cb79e2bc52adef5f98055d52fa367f86187d171648b5bba682c576d1ffed
Loading images into kind cluster nodes...
 - gcr.io/k8s-skaffold/leeroy-web:b524e280cc40c0599deea2c3fb17f5fc9c9ff9039328d4962e604759d8534d3d -> Found
 - gcr.io/k8s-skaffold/leeroy-app:a4a2cb79e2bc52adef5f98055d52fa367f86187d171648b5bba682c576d1ffed -> Found
Images loaded in 72.706614ms
Starting deploy...
 - deployment.apps/leeroy-web configured
 - service/leeroy-app configured
 - deployment.apps/leeroy-app configured
Waiting for deployments to stabilize...
 - test:deployment/leeroy-app is ready. [1/2 deployment(s) still pending]
 - test:deployment/leeroy-web is ready.
Deployments stabilized in 2.490996363s
Press Ctrl+C to exit
Port forwarding deployment/leeroy-web in namespace default, remote port 8080 -> address 127.0.0.1 port 9000
Port forwarding service/leeroy-app in namespace test, remote port 50051 -> address 127.0.0.1 port 50052
```

In the last two lines, you can see that the `test` namespace uses for `service/leeroy-app`, but the `default` namespace uses for `deployment/leeroy-web`.
