### ISSUE TITLE
Skaffold render --namespace not setting helm namespace in resulting manifests

### ISSUE THREAD

**Issue by maxhillaert** [GoogleContainerTools/skaffold#4951]
### Expected behavior

`skaffold render -a=images.json --namespace=foobar `

should result in 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
```
being expanded with namespace:  foobar

### Actual behavior

namespace: default

### Information

- Skaffold version: 1.15.0
- Operating system: windows
- Contents of skaffold.yaml:

```yaml

deploy:
  helm:
    releases:
      - name: anApp
        chartPath: ./chart
        artifactOverrides:
          image: <redacted>
```
