### ISSUE TITLE
skaffold should not watch all files in your workspace where custom dependency config is not set. 

### ISSUE THREAD

**Issue by joseret** [GoogleContainerTools/skaffold#4957]
### Expected behavior
Trying to use a custom script to run unit tests and then proceed to use jib to build the image.  I would not expect it to be looping forever.

### Actual behavior
build script is looping 
### Information

- Skaffold version: v1.15.0
- Operating system: Mac OSX 10.15.7
- Contents of skaffold.yaml:

```yaml

apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
  - image: gcr.io/jc-gkeop-2/jib/dog-spring-bld-custom
    custom:
      buildCommand: ./build.sh
  # - image: gcr.io/jc-gkeop-2/jib/dog-spring-jib
  #   context: ./dog
  #   jib: {}

# optional profile to run the jib build on Google Cloud Build
# profiles:
#   - name: gcb
#     build:
#       googleCloudBuild: {}
```
```bash
echo "Test"
./mvnw clean && ./mvnw test 
echo "Buid with Jib"
./mvnw compile com.google.cloud.tools:jib-maven-plugin:2.6.0:dockerBuild -Dimage=${IMAGE}
docker push ${IMAGE}
```
### Steps to reproduce the behavior

1.  just have a local standard maven spring boot project
2. `skaffold dev --filename=../skaffold.yaml `

Logs
https://gist.github.com/joseret/e0d41262d991c9e575b66381e1173997
