### ISSUE TITLE
Debug mode in a namespace with resource quota

### ISSUE THREAD

**Issue by efaure** [GoogleContainerTools/skaffold#4980]
### Expected behaviour

Expected: be able to use debug mode in a namespace with resource quota

### Actual behaviour

Skaffold log when running `skaffold debug`

```
[...]
Starting deploy...
 - service/node created
 - deployment.apps/node created
Waiting for deployments to stabilize...
 - mynamespace:deployment/node: waiting for rollout to finish: 0 out of 1 new replicas have been updated...
 - mynamespace:deployment/node: could not stabilize within 2m0s
 - mynamespace:deployment/node failed. Error: could not stabilize within 2m0s.
Cleaning up...
 - service "node" deleted
 - deployment.apps "node" deleted
```

The corresponding event with `kubectl get events`

```
0s          Warning   FailedCreate            replicaset/node-749b5b4d7                                            (combined from similar events): Error creating: pods "node-749b5b4d7-9m6fc" is forbidden: failed quota: test-quota: must specify requests.cpu,requests.memory
```

This error may be due to the fact that there is no resource request defined at the initContainers level.
```
        initContainers:
        - image: gcr.io/k8s-skaffold/skaffold-debug-support/nodejs
          imagePullPolicy: Always
          name: install-nodejs-debug-support
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /dbg
            name: debugging-support-files
```

In documentation, there is information on how to define resources request for kaniko https://skaffold.dev/docs/references/yaml/#build-cluster-resources-requests

Something similar for debug can be very useful!

I know debug is in beta, but if there is any workaround to be able to continue to use it with requests it will be very helpful.  

### Information

- Skaffold version: v1.16.0
- Operating system:  Ubuntu 20.04.1 LTS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta9
kind: Config

build:
  artifacts:
  - image: node-example
    context: backend

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: node-example
        context: backend
        docker:
          buildArgs:
            ENV: development
        sync:
          manual:
          # Sync all the javascript files that are in the src folder
          # with the container src folder
          - src: 'src/**/*.js'
            dest: .
```

### Steps to reproduce the behavior

1. Create resource quota in the namespace 

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-resource-quota
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
```

1. Use `examples/nodejs` from https://github.com/GoogleContainerTools/skaffold`

Deployment of the example is updated to include resources request

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: node-example
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
```

2. Run `skaffold debug`

**Comment by tejal29** [comment]
@efaure Thanks for opening this issue. The fact that the warning event `FailedCreate` did not show up as part of `status-check` phase is an issue.  This seems like a bug and we will look into it. 

For the feature request you mentioned, 
I am not very well aware of  `ResourceQuota`. If a `ResourceQuota` exists all containers need to declare in their spec the `resources.requests` which are within the limit mentioned?

```
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
```

**Comment by efaure** [comment]
@tejal29 Thank you for your response.

For `ResourceQuota`, from my understanding, if one is defined at the namespace level, before launching a  container, Kubernetes check that requests and limits of this container will not lead to exceed constraint at namespace level.  
In order to do this check, Kubernetes require to have requests (and limits if needed) for each containers.

For init containers, maybe it's a special case, but from my testing, I conclude we also need to define requests for it. For information, documentation on resource management on init containers : 
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources

Maybe there is another way to solve this issue that I'm not aware of.

**Comment by tejal29** [comment]
Thanks @efaure. Sorry for the delay. 
Looks like the solution here would be to copy the resource limit if the container def has a `ResourceQuota` to this interface. 
https://github.com/GoogleContainerTools/skaffold/blob/e91c8e68df0d81025622c7743a5cff6fc782e77b/pkg/skaffold/debug/transform.go#L111

Thanks
Tejal.

**Comment by tejal29** [comment]
Closing this due to inactivity. Please ping if this is still an issue.

**Comment by aldycool** [comment]
Hi @tejal29 ,

I'm still facing this issue, I'm trying to debug a .NET 6 app using Skaffold. The app is deployed inside a namespace named `devenv-user01` with pre-configured `ResourceQuota`:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-resource-quota
  namespace: devenv-user01
spec:
  hard:
    limits.cpu: "250m"
    limits.memory: "512Mi"
    requests.storage: "250Mi"    
```
And, when launching the skaffold debug, my Pod is successfully injected with the Skaffold's debug support container inside the `initContainers`. But, it cannot proceed because when a namespace is attached with a `ResourceQuota`, all containers that wants to be deployed (including the one inside the `initContainers`) must specify at least `limits.cpu` and `limits.memory` resources. This is the output of the `ReplicaSet` (other outputs such as from `Deployment` does not reflect the issue clearly):
```yaml
     spec:
        containers:
        - image: harbor.somedomain.xyz/devenv-user01/demoapp:latest@sha256:0566a1de85cf9d1159fdbe70f6de733ffb911fd6b4255cb40072f06a440869f9
          imagePullPolicy: Always
          name: demoapp
          ports:
          - containerPort: 80
            protocol: TCP
          resources: # <=== My deployment already define resources here 
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /dbg
            name: debugging-support-files
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: harbor-secret
        initContainers:
        - image: gcr.io/k8s-skaffold/skaffold-debug-support/netcore
          imagePullPolicy: Always
          name: install-netcore-debug-support
          resources: {} # <=== But the debug support container resource is empty
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /dbg
            name: debugging-support-files
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: debugging-support-files
  status:
    conditions:
    - lastTransitionTime: "2022-07-25T11:03:59Z"
      message: 'pods "demoapp-7ff4c86688-jbkqs" is forbidden: failed quota: default-resource-quota:
        must specify limits.cpu,limits.memory'
      reason: FailedCreate
      status: "True"
      type: ReplicaFailure
    observedGeneration: 1
    replicas: 0
```
How can I set the injected initContainers `resources`? Thanks.
