### ISSUE TITLE
helm values support nested structure

### ISSUE THREAD

**Issue by sstarcher** [GoogleContainerTools/skaffold#500]
Issues without logs and details are more complicated to fix.
Please help us!

### Expected behavior

Support for nested helm values.

### Actual behavior

Parse error

### Information

```
Skaffold version: 0.5.0
Operating system: osx
```

```
deploy:
  helm:
    releases:
    - name: chart
      chartPath: ./chart
      namespace: skaffold
      values:
        subchart:
          image:
            tag: "abc"
```

### Steps to reproduce the behavior

  1. . skaffold run with a value that is more than a single nesting deep

**Comment by balopat** [comment]
This issue received no attention for a long time - I'm wondering if people are still interested in having nested values?

**Comment by kylewolfe** [comment]
This is needed as it is currently impossible to use skaffold with any umbrella chart, custom or not.

I have referenced this issue in another proposal that would resolve this issue as well as enable injecting the image tag into custom builds.

**Comment by TBBle** [comment]
```
deploy:
  helm:
    releases:
    - name: chart
      chartPath: ./chart
      namespace: skaffold
      values:
        subchart.image.tag: "abc"
```

works for me.

**Comment by kylewolfe** [comment]
I originally viewed this issue as a request around being able to use templated fields in nested locations, but looking again, that's not mentioned here. 

For those looking for an issue about that: #3343

**Comment by bitsofinfo** [comment]
this is a deal breaker for me, I can't use my chart which needs nested values

```
deploy:
  helm:
    releases:
      - name: test-dog-4f205e7-dirty
        chartPath: bitsofinfo-appdeploy/appdeploy
        version: 1.1.14
        wait: true
        namespace: test-apps
        valuesFiles:
          - /my/values.yaml
        values:
          app:
            context: stage-test
            environment: stage
            name: dog
```

blows up with `cannot unmarshal !!map into string`

**Comment by TBBle** [comment]
@bitsofinfo try:
```yaml
deploy:
  helm:
    releases:
      - name: test-dog-4f205e7-dirty
        chartPath: bitsofinfo-appdeploy/appdeploy
        version: 1.1.14
        wait: true
        namespace: test-apps
        valuesFiles:
          - /my/values.yaml
        overrides:
          app.context: stage-test
          app.environment: stage
          app.name: dog
```

Unless those override values *are* used to select a Docker image, in which change change `overrides` back to `values`.

**Comment by TBBle** [comment]
According to [the docs](https://skaffold.dev/docs/environment/templating/) env-vars are only supported with ``setValueTemplates``, so you might want something like:

```yaml
deploy:
  helm:
    releases:
      - name: test-dog-4f205e7-dirty
        chartPath: bitsofinfo-appdeploy/appdeploy
        version: 1.1.14
        wait: true
        namespace: test-apps
        valuesFiles:
          - /my/values.yaml
        setValueTemplates:
          app.context: stage-{{.CURRENT_STAGE}}
        overrides:
          app.environment: stage
          app.name: dog
```
