### ISSUE TITLE
Skaffold deploy does not load images into local kind cluster

### ISSUE THREAD

**Issue by shaxbee** [GoogleContainerTools/skaffold#5007]
### Expected behavior

`skaffold deploy` should load images into local kind cluster.

### Actual behavior

`skaffold deploy` does not load images.
`skaffold run` and `skaffold dev` do load images.

### Information

- Skaffold version: 1.16.0
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: todo-app-skaffold
build:
  artifacts:
    - image: goose
      docker:
        dockerfile: cmd/goose/Dockerfile
    - image: todo
      docker:
        dockerfile: services/todo/Dockerfile
    - image: redoc
      docker:
        dockerfile: api/Dockerfile
deploy:
  statusCheckDeadlineSeconds: 300
profiles:
  - name: local
    activation:
      - kubeContext: kind-local
      - command: dev
      - command: run
    deploy:
      kubeContext: kind-local
      kustomize:
        paths:
          - ops/overlays/dev
    portForward:
      - resourceType: service
        resourceName: todo
        port: 80
        localPort: 8080
      - resourceType: service
        resourceName: redoc
        port: 80
        localPort: 9000
      - resourceType: service
        resourceName: postgres
        port: 5432
```

### Steps to reproduce the behavior

1. clone https://github.com/shaxbee/todo-app-skaffold
2. `make bootstrap`
3. `skaffold build -q | skaffold deploy --force --build-artifacts -`
