### ISSUE TITLE
Enabling buildkit in skaffold.yaml results in cache key error

### ISSUE THREAD

**Issue by askmeegs** [GoogleContainerTools/skaffold#5015]
### Expected behavior

Added `useBuildkit: true` to skaffold.yaml. Expected to not have to make any other changes / for `skaffold build` to run successfully, and faster than before.  

### Actual behavior

Builds fail with cache key errors: 

```
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: docker.io/library/node:8-alpine not found
```

```
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: docker.io/microsoft/dotnet:2.1-sdk-alpine not found
```

Reference: https://github.com/GoogleCloudPlatform/microservices-demo/issues/431 

### Information

- Skaffold version: `v1.14.0`
- Operating system: Mac and Linux 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  # image tags are relative; to specify an image repo (e.g. GCR), you
  # must provide a "default repo" using one of the methods described
  # here:
  # https://skaffold.dev/docs/concepts/#image-repository-handling
  - image: emailservice
    context: src/emailservice
  - image: productcatalogservice
    context: src/productcatalogservice
  - image: recommendationservice
    context: src/recommendationservice
  - image: shippingservice
    context: src/shippingservice
  - image: checkoutservice
    context: src/checkoutservice
  - image: paymentservice
    context: src/paymentservice
  - image: currencyservice
    context: src/currencyservice
  - image: cartservice
    context: src/cartservice
  - image: frontend
    context: src/frontend
  - image: loadgenerator
    context: src/loadgenerator
  - image: adservice
    context: src/adservice
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
- name: gcb
  build:
    googleCloudBuild:
      diskSizeGb: 300
      machineType: N1_HIGHCPU_32
      timeout: 4000s
```
