### ISSUE TITLE
Docker Buildx Integration

### ISSUE THREAD

**Issue by no1melman** [GoogleContainerTools/skaffold#5018]
Hi, I would like to propose we re-open this [issue](https://github.com/GoogleContainerTools/skaffold/issues/2475), or start again here.

`buildx` caching options are super powerful (because they do remote caching) and will massively cut down our build times, as the common thing you see in mono-repos is that not every area is changed in a PR

I've asked `buildx` if layer caching is remotely cached just for clarification, I've also confirmed this works - https://github.com/docker/buildx/issues/435

Looking at the skaffold yaml and the knowing the build commands, it wouldn't be too much work - unfortunately I'm not a Go dev, but happy to pair with someone on this.

Possible skaffold

```yaml
build:
  artifacts:
    - image: somerepo/someimage
      docker:
         buildx: true
         cacheTo: type=registry,ref=[THIS_WOULD_HAVE_TO_BE_THE_OUTPUT_IMAGE_TAG]
         # below can be repurposed if buildx set to true
         cacheFrom: type=registry,ref=[SAME_AS_ABOVE]
         output: type=registry
```

this would just run the command:

```bash
  $ docker buildx build --cache-to=[SAME_AS_ABOVE] --cache-from=[SAME_AS_ABOVE] --output=type=registry -t [FULL_IMAGE_TAG]
```
