### ISSUE TITLE
GitTagger generates an invalid tag if there are uncommitted changes

### ISSUE THREAD

**Issue by anshlykov** [GoogleContainerTools/skaffold#5033]
### Expected behavior

Skaffold generates a valid image tag, even if there are uncommitted changes.

### Actual behavior

Skaffold generates an invalid image tag.

```
$ skaffold build
Generating tags...
 - leeroy-web -> leeroy-web:b1-dev/1-dirty
 - leeroy-app -> leeroy-app:b1-dev/1-dirty
 - base -> base:b1-dev/1-dirty
Checking cache...
 - leeroy-web: Error checking cache.
getting imageID for leeroy-web:b1-dev/1-dirty: Error response from daemon: no such image: leeroy-web:b1-dev/1-dirty: invalid reference format
```

### Information

- Skaffold version: v1.16.0
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta9
kind: Config
build:
  local:
    push: false
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: leeroy-web
      context: leeroy-web
      requires:
        - image: base
          alias: BASE
    - image: leeroy-app
      context: leeroy-app
      requires:
        - image: base
          alias: BASE
    - image: base
      context: base
```
