### ISSUE TITLE
COPY not working when Dockerfile in subdirectory

### ISSUE THREAD

**Issue by bynare** [GoogleContainerTools/skaffold#5061]
### Expected behavior
`skaffold build` succeeds.

### Actual behavior
An error is encountered:
`getting hash for artifact "django": getting dependencies for "django": file pattern [requirements.txt] must match at least one file`
### Information

- Skaffold version: v1.17.0
- Operating system: ubuntu 20.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: django
    docker:
      dockerfile: subdir/Dockerfile
      target: base
```

### Steps to reproduce the behavior

`subdir/Dockerfile` looks like this:
```
 FROM python:3.9 AS base
 
 WORKDIR /usr/src/app
 
 ENV PYTHONDONTWRITEBYTECODE 1
 ENV PYTHONUNBUFFERED 1
 
 # install dependencies
 RUN pip install --upgrade pip
 COPY requirements.txt .
```
Run `skaffold build`.

Manually building the image by executing `docker build .` from `subdir` works as expected.

Thanks!

**Comment by bynare** [comment]
Apologies, I think I abused the `dockerfile` field, instead of using `context` to specify `subdir`, i.e
```yaml
apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: django
    context: subdir
...
``` 
:D
