### ISSUE TITLE
Unhelpful error: WARN[0001] run: build: build step: running push: denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#507]
- Skaffold v0.5.0.
- Docker for Mac (w/ Kubernetes) is currently running
- kubectl current-context pointing to a GKE cluster.
- docker config.json has `gcloud auth configure-docker` stuff

skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: vote
    workspace: voting-app/vote/
  - imageName: worker
    workspace: voting-app/worker/
  - imageName: result
    workspace: voting-app/result/
deploy:
  kubectl:
    manifests:
    - ./voting-app/k8s-specifications/*
```

My `image:` fields in the k8s Deployment.yamls are not maching this `imageName:` currently but I still 
 expect the image to be built but with a warning saying "image unused", example:

```yaml
    ...
    spec:
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/vote
        name: vote
```

I see:

- This log, after the first image is built:

```
f846841ed47f: Waiting
0198944a9875: Waiting
9dfa40a0da3b: Waiting
WARN[0001] run: build: build step: running push: denied: requested access to the resource is denied
```

- Full logs (-v=debug):  https://gist.github.com/ahmetb/f41f2868d928834535e377888cd89a07

- 2nd and 3rd images are not being built.

- Shows a misleading "Watching for changes..." while something is broken. Skaffold should exit in this case IMO, with a more helpful error message.
