### ISSUE TITLE
context directories with backslashes on Windows do not work

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5074]
From [StackOverflow](https://stackoverflow.com/q/65027759/600339) where a user was attempting to build a project from `skaffold init` on Windows

### Expected behavior
`skaffold init` generated a `skaffold.yaml` with paths containing backslashes.  Such paths should cause no problems as YAML does not interpret backslashes in an unquoted scalar, and Skaffold should accept backslash paths on Windows.

```yaml
build:
  artifacts:
  - image: testmicro
    context: src\Microservices
    docker:
      dockerfile: TestMicro\Dockerfile
```

### Actual behavior

> [`@penguinflip`](https://stackoverflow.com/questions/65027759/how-to-run-skaffold-with-a-bootstrapped-net-core-api-docker-project/65029009?noredirect=1#comment114966990_65029009): [...] Interestingly, the init script added the slashes the wrong way - `src\Microservices\TestMicro` (I guess because I'm on Windoze). Copying your code exactly worked, but it doesn't with the slashes reversed. This may be a bug with skaffold init...

### Information

`skaffold.yaml` was generated by `skaffold init`.

- Skaffold version: 1.15.0 (since generated `skaffold.yaml` has `v2beta8`)
- Operating system: Windows
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: microservices-investigation
build:
  artifacts:
  - image: testmicro
    context: src\Microservices
    docker:
      dockerfile: TestMicro\Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/TestMicro.yaml
```
