### ISSUE TITLE
Skaffold should provides a way to precise order of artifacts builds

### ISSUE THREAD

**Issue by fredleger** [GoogleContainerTools/skaffold#5075]
### Expected behavior

I thought i can build a thing like that with skaffold

```mermaid
base image
  ---> front image
  ---> back image
```

### Actual behavior

Seems at skaffold take the artifacts in the alphabeticaly order (so backend - base - frontend)

### Information

- Skaffold version: 1.16.1
- Operating system: linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta9
kind: Config
build:
  local:
    tryImportMissing: true
    useBuildkit: true
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: base
    docker:
      dockerfile: docker/Dockerfile.prod
      target: base
      cacheFrom:
      - node:lts-alpine
  - image: frontend
    docker:
      dockerfile: docker/Dockerfile.prod
      target: prod-frontend
      cacheFrom:
      - node:lts-alpine
      - base
  - image: backend
    docker:
      dockerfile: docker/Dockerfile.prod
      target: prod-backend
      cacheFrom:
      - node:lts-alpine
      - base
```

### Steps to reproduce the behavior

1. `skaffold build`
2. check logs

**Comment by gsquared94** [comment]
The way to do this in Skaffold is to add a `requires` section to each artifact to set the dependency order. This feature is available `v1.16.0` onwards.

```yaml
apiVersion: skaffold/v2beta9
kind: Config
build:
  local:
    tryImportMissing: true
    useBuildkit: true
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: base
    docker:
      dockerfile: docker/Dockerfile.prod
      target: base
      cacheFrom:
      - node:lts-alpine
  - image: frontend
    docker:
      dockerfile: docker/Dockerfile.prod
      target: prod-frontend
      cacheFrom:
      - node:lts-alpine
      - base
    requires:
      - image: base
  - image: backend
    docker:
      dockerfile: docker/Dockerfile.prod
      target: prod-backend
      cacheFrom:
      - node:lts-alpine
      - base
    requires:
      - image: base
```

Can you try this and let us know if it solves the issue for you?
