### ISSUE TITLE
Enabling using another container's network stack on build process

### ISSUE THREAD

**Issue by zedfmario** [GoogleContainerTools/skaffold#5087]
> No logs provided since there's no error to be fixed.

Building docker images in a Jenkins-like environment running on a AWS EKS cluster secured with `kube2iam` requires the running pod to include an annotation. In our particular case, we share the docker daemon from the node with the running pod by mounting the socket as a volume. When `skaffold` builds a new image within this pod, it creates containers at node level due to the shared socket. Therefore, to have a brand new container handled by `kube2iam`, this container should reuse the pod's network stack –ergo the "pause" container's stack–.

### Expected behavior
Enabling the use of `container:<name|id>` network mode from `docker run` command. It allows a build process to reuse another container's stack.
> Described in [here](https://docs.docker.com/engine/reference/run/#network-settings)

### Actual behavior
```
invalid skaffold config: artifact skaffold-example has invalid networkMode 'container:alpine'
```
### Information

- Skaffold version: v1.16.0
- Operating system: Darwin Kernel Version 19.6.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta9
kind: Config
build:
  artifacts:
  - image: skaffold-example
    docker:
      network: "container:alpine"
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior
1.  `skaffold -f skaffold.yaml build`
