### ISSUE TITLE
`panic: close of closed channel` with skaffold build since v1.16.0

### ISSUE THREAD

**Issue by robertgates55** [GoogleContainerTools/skaffold#5095]
We have a relatively complex skaffold.yaml that builds multiple docker images as artefacts. Some are multistage, some single; and they use a range of context levels.

Since 1.16.0 `skaffold build` fails with a panic error midway through building. Our devs have rolled back to 1.15.0 while this bug exists.

### Expected behavior
All artefacts are built and tagged as expected. This works with 1.15.0

### Actual behavior
`skaffold build` gives:
```
...
Successfully tagged harbor.dev.xxxx.services/xxxx/cube-rails:dc512f74042-dirty
Building [harbor.dev.xxxx.services/xxxx/cube-assets]...
panic: close of closed channel

goroutine 92 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.(*node).markComplete(...)
        /skaffold/pkg/skaffold/build/model.go:39
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.(*scheduler).build(0xc0001dc900, 0x5f118c0, 0xc00049ecc0, 0xc000c62e40, 0x1, 0x0, 0x0)
        /skaffold/pkg/skaffold/build/scheduler.go:105 +0x499
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.(*scheduler).run.func1(0x0, 0x0)
        /skaffold/pkg/skaffold/build/scheduler.go:65 +0x4e
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000eb2840, 0xc000eb28a0)
        /skaffold/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /skaffold/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

It successfully builds a number of images, and then throws this error as it's starting another. It's not always the build of the same image that throws the error.

I can see that this code (`/skaffold/pkg/skaffold/build/model.go`) is all new to support the DAG computation so suspect something about our layout is confusing something.

### Information

- Skaffold version: 1.16.0 & above
- Operating system: OSX
- Contents of skaffold.yaml:
(this is not the actual skaffold.yaml, but a dummy project I create that echoes the layout of it. We're building 12 images, from different depths in our repo, and with different levels of cross-dependency.
```yaml
apiVersion: skaffold/v2beta5
kind: Config

build:
  local:
    useBuildkit: true
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05.999_MST"
      timezone: "Local"
  artifacts:
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image1
      context: project1
      docker:
        dockerfile: image/Dockerfile
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image2
      docker:
        dockerfile: ./project2/image/Dockerfile
        target: target1
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image3
      docker:
        dockerfile: ./project2/image/Dockerfile
        target: target2
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image4
      docker:
        dockerfile: ./project3/image/Dockerfile
        target: target1
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image5
      docker:
        dockerfile: ./project3/image/Dockerfile
        target: target2
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image6
      docker:
        dockerfile: ./project3/image/Dockerfile
        target: target3
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image7
      docker:
        dockerfile: ./project3/image/Dockerfile
        target: target4
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image8
      docker:
        dockerfile: ./project2/image/Dockerfile
        target: target3
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image9
      docker:
        dockerfile: ./project2/image/Dockerfile
        target: target4
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image10
      docker:
        dockerfile: ./project2/image/Dockerfile
        target: target5
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image11
      docker:
        dockerfile: ./project2/image/Dockerfile
        target: target6
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image12
      context: project4
      docker:
        dockerfile: Dockerfile
    - image: harbor.dev.xxxx.services/xxxx/some/very/long/thing/image13
      context: project5
      docker:
        dockerfile: image/Dockerfile
```

**Comment by robertgates55** [comment]
This was _actually_ because of a duplicate artifact definition - which didn't used to error but now does!

**Comment by nkubala** [comment]
@robertgates55 thanks for filing! glad to see you found a resolution for your project config, but i'm going to reopen this because we should never be surfacing panics in skaffold!

**Comment by DGollings** [comment]
had the 'same' issue, although slightly different (and for reasons I don't entirely understand)

```
profiles:
(..)
  - name: dev
    activation:
      - kubeContext: microk8s
        command: dev
    deploy:
      statusCheckDeadlineSeconds: 300
      kustomize:
        paths:
          - deploy/skaffold/dev
    patches:
      # use test database in dev
      - op: add
        path: /build/artifacts/-
        value:
          image: docker.keana.io/testdata
          docker:
            dockerfile: docker/Dockerfile.standalone_test_cockroachdb
```
`skaffold dev --default-repo localhost:32000 -p dev` = error (the testdata image shows up twice to be built)
`skaffold dev --default-repo localhost:32000` = fine

I understand that dev (activation microk8s dev) -p dev is very, uhm, dev. But I've had various results over time/skaffold versions where it would and wouldn't trigger the correct dev profile. So I guess we're back to `skaffold dev --default-repo localhost:32000` :)

However, I'm not sure as to why `skaffold dev --default-repo localhost:32000 -p dev` would trigger dev 'twice'

Anyway, just to add a similar but different cause for this issue
