### ISSUE TITLE
Allow option to specify the kubectl context

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#511]
I just found myself did a build via `googleCloudBuild` but I forgot to switch my active kubectl context to the GKE cluster.

I think picking up the active kubectl context is not a great idea especially because users can be switch back and forth very frequently.

It appears like the `deploy.kubectl` does not currently let me specify a context name. If it did, I would do something like:

```
profiles:
- name: local
  deploy:
    kubectl:
      context: docker-for-desktop <---- new field
      manifests:
      - ./k8s-specifications/*
profiles:
- name: remote
  deploy:
    kubectl:
      context: my-gke-cluster <---- new field
      manifests:
      - ./k8s-specifications/*
```

then run `skaffold dev -p {local,remote}`.

If unspecified, this would still pick up the active context name from kubectl (backwards compatible).

(Skaffold v0.5.0)
