### ISSUE TITLE
New files are not synced to running container.

### ISSUE THREAD

**Issue by coldis** [GoogleContainerTools/skaffold#5110]
When a new file which matches the glob in sync.manual is created, it is not synced to the running container. Changes to existing files are synced as expected.

This behaviour first appears in 1.17

### Expected behavior
New files which match sync.manual are synced to the running container.

### Actual behavior
The new file is not picked up

### Information

- Skaffold version: >=1.17
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: rally-app
build:
  local:
    useDockerCLI: true
    useBuildkit: true
profiles:
  - name: dev
    build:
      artifacts:
        - image: my-image
          sync:
            manual:
              - src: frontend/src/**/*
                dest: .
                strip: frontend/
              - src: frontend/public/**/*
                dest: .
                strip: frontend/
          docker:
            dockerfile: frontend/Dockerfile
    deploy:
      kustomize:
        paths:
          - kubernetes/environments/dev
      kubeContext: docker-desktop

```
