### ISSUE TITLE
require on a k8 service with no artifact

### ISSUE THREAD

**Issue by newtoniumx3** [GoogleContainerTools/skaffold#5112]
I have an artifact several services with no artifacts and simply have k8s definitions.
The services are things such as postgres and mongodb. Naturally I need these to be up and running prior to my applications but right now I have no way to define this since the postgres and mongodb don't have an artifact.

Is there a way to specify dependency requirement with no artifacts and based on a k8 service name like can be done using docker-compose?

- Skaffold version: version: 1.17.1
- Operating system: Windows 10

```yaml
apiVersion: skaffold/v2beta10
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: nx2/my-server
      context: ./src/server
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
        - '**/*.py'  
deploy:
  kubectl:
    manifests:
      - k8/apps/my-server*
      - k8/services/postres*

```

**Comment by gsquared94** [comment]
Unfortunately none of the supported deployers in `skaffold` currently provide manifest ordering. You might try the `kpt` deployer, IMO it does some common sense ordering and also has a custom ordering feature in the works (https://github.com/GoogleContainerTools/kpt/issues/756)

**Comment by briandealwis** [comment]
Note that Skaffold is happy to deploy arbitrary workload objects as long as there's a single artifact.  You can use an [`initContainer` to delay your app container from starting](https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/master/python/python-guestbook/kubernetes-manifests/guestbook-backend.deployment.yaml#L20-L26), for example:
```yaml
      initContainers:
      - name: init-db-ready
        image: mongo:4
        command: ['/bin/sh', '-c']
        args:
          - echo "Waiting for mongodb at python-guestbook-mongodb:27017 to go live before the BE..."; 
          - until (mongo --host python-guestbook-mongodb:27017 >/dev/null) do echo "Waiting for connection for 2 sec."; sleep 2; done
```

**Comment by yuwenma** [comment]
> Unfortunately none of the supported deployers in `skaffold` currently provide manifest ordering. You might try the `kpt` deployer, AFAIK it does some common sense ordering and also has a custom ordering feature in the works ([GoogleContainerTools/kpt#756](https://github.com/GoogleContainerTools/kpt/issues/756))

**Comment by briandealwis** [comment]
@newtoniumx3 with [Skaffold's multi-config functionality](https://skaffold.dev/docs/design/config/#multiple-configuration-support), you can now have a config with just deployment.  But there is no status checks between each config.

**Comment by tejal29** [comment]
Thanks @newtoniumx3 
Deploy order is something skaffold will consider after https://github.com/GoogleContainerTools/skaffold/blob/master/docs/design_proposals/new-render-and-deploy.md lands.

**Comment by gsquared94** [comment]
> @newtoniumx3 with [Skaffold's multi-config functionality](https://skaffold.dev/docs/design/config/#multiple-configuration-support), you can now have a config with just deployment. But there is no status checks between each config.

Skaffold now can do status checks between configs, so this usecase should be solvable with [Skaffold's multi-config functionality](https://skaffold.dev/docs/design/config/#multiple-configuration-support)

you can define two configs and a dependency between them:
```yaml
apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: db
deploy:
  kubectl:
    manifests: ["k8/apps/my-server*", "k8/services/postres*"]
---
kind: Config
metadata:
  name: svc
requires:
  configs: ["db"]
build:
  ....
deploy:
  ...

```

and run skaffold with the `--iterative-status-check=true` flag
