### ISSUE TITLE
Templated fields, use generated tag for helm appVersion

### ISSUE THREAD

**Issue by msonnleitner** [GoogleContainerTools/skaffold#5113]
### Expected behavior

Support for using the generated tag to use in deployment, e.g. using that in the `appVersion`field of the helm deployment

### Actual behavior

Currently, the tag cannot (afaik) be used in that context.

### Information

- Skaffold version: v1.17.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: some-service
build:
  artifacts:
    - image: eu.gcr.io/tools-org/some-service
deploy:
  helm:
    releases:
      - name: some-service
        chartPath: helm/some-service
        artifactOverrides:
          image: eu.gcr.io/tools-org/some-service
        packaged:
          appVersion: {{.GENERATED_TAG}}
```
