### ISSUE TITLE
wrong deployment image url generated

### ISSUE THREAD

**Issue by tuananh** [GoogleContainerTools/skaffold#512]
I got this generated as image url in the deployment manifest.

```
map[pullPolicy:IfNotPresent repository:xxxxxxx.dkr.ecr.ap-southeast-1.amazonaws.com/ns/myapp tag:latest]
```

My helm deployment template is below, nothing fancy, just a copy paste from the helm deployment example with `command` and `args` commented out.

```
containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.pullPolicy }}
```

```
Failed to apply default image tag "map[pullPolicy:IfNotPresent repository:xxxxxxxx.dkr.ecr.ap-southeast-1.amazonaws.com/ns/myapp tag:latest]": couldn't parse image reference "map[pullPolicy:IfNotPresent repository:xxxxxxx.dkr.ecr.ap-southeast-1.amazonaws.com/ns/myapp tag:latest]": invalid reference format
```

Issues without logs and details are more complicated to fix.
Please help us!

### Expected behavior

deployment image url generated correctly

### Actual behavior

deployment image url generated incorrectly

### Information

```
Skaffold version: v0.5.0
Operating system: macOS 10.13.4
Content of skaffold.yaml: 
```

```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: xxxxxx.dkr.ecr.ap-southeast-1.amazonaws.com/ns/myapp
deploy:
  helm:
    releases:
    - name: v18
      chartPath: helm-chart
      namespace: skaffold
```

### Steps to reproduce the behavior

  1. skaffold run
