### ISSUE TITLE
Skaffold Quickstart cannot deploy onto OpenShift

### ISSUE THREAD

**Issue by keddyliu** [GoogleContainerTools/skaffold#5127]
Skaffold is still pretty new to me, so please bear with me. Please let me know what I am missing.

### Expected behavior
The Skaffold Quickstart detailed on https://skaffold.dev/docs/quickstart/ should deploy on OpenShift.

### Actual behavior
It does not deploy on OpenShift, and instead gives an error saying it cannot connect to the Docker daemon.

### Information

- Skaffold version: v1.17.1
- Operating system: Linux 3.10.0-1127.19.1.el7.x86_64 remotely connecting to OpenShift 4.6.4 running Kubernetes v1.19.0+9f84db3
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. oc login --token=[redacted_openshift_token] --server=[redacted_openshift_url]:6443
2. git clone https://github.com/GoogleContainerTools/skaffold.git
3. cd skaffold/examples/getting-started
4. skaffold dev
5. Then I get the following messages and error:
```
Listing files to watch...
 - skaffold-example
Generating tags...
 - skaffold-example -> skaffold-example:v1.17.1-9-g272f10443
Checking cache...
 - skaffold-example: Not found. Building
Building [skaffold-example]...
Build Failed. Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Check if docker is running.
```
