### ISSUE TITLE
skaffold cannot use docker buildkit

### ISSUE THREAD

**Issue by DesistDaydream** [GoogleContainerTools/skaffold#5130]
### Expected behavior
skaffold should understand the Dockerfile file correctly

### Actual behavior
After I added the `.build.local.useBuildkit: true` field, I still couldn't process the buildkid syntax and reported an error
```shell
root@lichenhao:~/projects/myapp# skaffold dev
Listing files to watch...
 - docker.io/myapp/myapp
watching files for artifact "docker.io/myapp/myapp": listing files: parsing dockerfile "/root/projects/myapp/Dockerfile": Dockerfile parse error line 9: Unknown flag: mount
```
### Information

- Skaffold version: v1.17.1
- Operating system: Ubuntu 20.04.1 LTS | Cetnos8
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: myapp
build:
  artifacts:
  - image: docker.io/myapp/myapp
    # docker:
    #   dockerfile: Dockerfile
  local:
    useDockerCLI: true
    useBuildkit: true
  tagPolicy:
      envTemplate:
        template: v0.2
deploy:
  kubectl:
  ......
```

Dockerfile:
```yaml
# syntax = docker/dockerfile:experimental

FROM golang:1.15 as builder
WORKDIR /myapp
COPY ./ ./
ENV CGO_ENABLED=0 \
    GO111MODULE=on \
    GOPROXY=https://goproxy.cn,https://mirrors.aliyun.com/goproxy/,https://goproxy.io,direct
RUN --mount=type=cache,target=/opt/gopath/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build .
# RUN go build .
FROM alpine
COPY --from=builder /myapp/myapp /myapp
EXPOSE 8080
CMD ["/myapp"]
```

### Steps to reproduce the behavior

1. Use the above file and execute the `skaffold dev` command
