### ISSUE TITLE
Skaffold debug mode inconsistency with helm deployment strategy

### ISSUE THREAD

**Issue by jycamier** [GoogleContainerTools/skaffold#5133]
In my project, I decide to have a `skaffold.yaml` file configuration which is not called like that. It's just `test.yaml`.
Thanks to `--filename` option, I can do it.

However, with the helm deployment strategy on debug mode, you add the helm's options `--post-renderer` which is 
`/usr/local/bin/skaffold` but without `--filename` option and you cannot.

### Expected behavior

I would like to use debug mode without a config file which is madatory called `skaffold.yaml`
Moreover, I use sometimes **kustomize** in helm `--post-renderer`. How I can do it with the debug mode ?

### Actual behavior

```
skaffold -f test.yaml debug                 
Listing files to watch...
 - foo/bar
Generating tags...
 - foo/bar -> foo/bar:a691cb3
Checking cache...
 - foo/bar: Found Locally
Tags used in deployment:
 - foo/bar -> foo/bar:d8c99c6022b5d5d1d3a44a6ba6d7953525139f00aeff9a90ae715f32f8bf8e15
Starting deploy...
Helm release foo not installed. Installing...
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "codecentric" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "elastic" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading postgresql from repo https://charts.bitnami.com/bitnami/
Deleting outdated charts
Error: error while running post render on files: error while running command /usr/local/bin/skaffold. error output:
skaffold config file skaffold.yaml not found - check your current working directory, or try running `skaffold init`
: exit status 1
exiting dev mode because first deploy failed: install: exit status 1

```

### Information

- Skaffold version: 1.17.1
- Operating system: Fedora
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: foo/bar
      context: services/client/app
      sync:
        auto: true
      jib:
        fromImage: gcr.io/distroless/java:11-debug
        args:
          - -Dmaven.test.skip
          - -Plocal
deploy:
  kubeContext: minikube
  helm:
    releases:
      - name: foo
        chartPath: services/client/helm/chart
        namespace: glad
        createNamespace: true
        valuesFiles:
          - k8s/helm/common/values_all.yaml
          - k8s/helm/common/values_local.yaml
          - services/client/helm/values.yaml
          - services/client/helm/values_local.yaml
        artifactOverrides:
          image: foo/bar
        setValues:
          imageConfig.tag: false
          spring.profiles.active: local
          imageConfig.pullPolicy: IfNotPresent
          app.auth.url: http://auth.foo.bar.192.168.39.121.nip.io
          app.api.path: foo.bar.192.168.39.121.nip.io


```
