### ISSUE TITLE
Skaffold dev with HPA setup in the cluster

### ISSUE THREAD

**Issue by tvvignesh** [GoogleContainerTools/skaffold#5136]
Originally filed here with all details: https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/350

I am not sure if this is a bug or an intended behavior, but when I use Cloud Code with Skaffold in my cluster with HPA enabled, I see that new replicas are created every time I do `Run on Kubernetes` even when `targetAverageUtilization` is not reached and takes close to 5-6 minutes to scale down back to 1 whereas this issue does not happen with HPA disabled.

All the screenshots and details showing the same have been attached in the linked issue.

### Information

- Skaffold version: v1.17.2
- Operating system: Ubuntu 20.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
profiles:
- name: development
  build:
    artifacts:
    - image: asia.gcr.io/<myproject>/<myimage>
      context: .
      sync:
        infer:
        - packages/**/src/**/*.*
        - packages/**/schema/**/*.gql
        - packages/**/*.md
        - packages/**/*.js
    local:
      push: true
      tryImportMissing: false
      useBuildkit: true
      concurrency: 0
  deploy:
    helm:
      releases:
      - name: <mysvc>
        chartPath: ./charts/<mysvc>
        valuesFiles:
        - ./deployment/dev/global/values.yaml
        - ./deployment/dev/global/secrets.yaml
        artifactOverrides:
          image: asia.gcr.io/<myproject>/<myimage>
        namespace: default
        skipBuildDependencies: true
        useHelmSecrets: true
        imageStrategy:
          helm: {}
      flags:
        upgrade:
        - --install
    statusCheckDeadlineSeconds: 500
```

### Steps to reproduce the behavior

- Setup a HPA in the cluster
- Do `Run on Kubernetes` with cleanUp disabled
- Stop it, and after sometime change something and do `Run on Kubernetes` again
- Replicas are scaled up and down till the max limit setup in HPA
