### ISSUE TITLE
Persistent volumes and skaffold

### ISSUE THREAD

**Issue by mvs24** [GoogleContainerTools/skaffold#5144]
This is my deployment with persistent volume:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-mongo-deployment
spec:
  selector:
    matchLabels:
      service: authentication-mongo
  template:
    metadata:
      labels:
        service: authentication-mongo
    spec:
      volumes:
        - name: authentication-mongo-storage
          persistentVolumeClaim:
            claimName: authentication-mongo-persistent-volume-claim
      containers:
        - name: authentication-mongo
          image: mongo
          volumeMounts:
            - name: authentication-mongo-storage
              mountPath: /data/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentication-mongo-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

```
### Expected behavior
I want after skaffold exits the data stored in PVC to come back

### Actual behavior
I have created a Persistent volume and persistent volume claim with mongodb, but after exit skaffold the data in the database is completely lost. What can we do to keep data after skaffold exits.

```
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: myDockerId/authentication-service
      context: authentication-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src"
            dest: .

```

**Comment by tejal29** [comment]
@mvs24 
Skaffold cleans-up all deployments after the dev loop ends. You can run `skaffold dev --cleanup=false`.  however that would mean your application also keeps running after you quit `skaffold dev`

**Comment by mvs24** [comment]
I tried --cleanup=false but didnt have success. I found another way running my databases locally, but hope you find a way of implementation for skaffold to not remove pvc after we exit skaffolf.
Thank you.

**Comment by nkubala** [comment]
this is an interesting use case, and one skaffold doesn't really have a great answer for. 

our support for [multiple configs](https://tinyurl.com/skaffold-multi-configs) might help here. you could configure your deployments in two separate deployment YAMLs, invoke the PVC one using `skaffold run --module skaffold-pvc.yaml`, and then iterate on the application one using `skaffold dev --module skaffold-app.yaml`.

long term though, it might be worth investigating potentially omitting some resource types from the cleanup phase that we know should be kept around, or at least making it configurable on a module level.

**Comment by mvs24** [comment]
Thank you for the response @nkubala. I will experiment with this in a later point of time.

**Comment by briandealwis** [comment]
We're working on providing Skaffold hooks (#1441) which would provide a way to install the claim outside of Skaffold's normal cleanup.

**Comment by briandealwis** [comment]
Duplicate of #4366

**Comment by mvs24** [comment]
Ok, great. Waiting for that

**Comment by Ammce** [comment]
Is there any solution to this issue? I am still unable to make it work? Each time I delete all pods/deployments/services, the data is gone forever? Also, where is Persistance Volume storing the data on my Windows Hard disk?

**Comment by mattbucci** [comment]
> Is there any solution to this issue? I am still unable to make it work? Each time I delete all pods/deployments/services, the data is gone forever? Also, where is Persistance Volume storing the data on my Windows Hard disk?

This is fairly straightforward now in 2023 thanks to merged support for hooks: https://github.com/GoogleContainerTools/skaffold/issues/1441

I needed a persistent volume claim to run my s3 mock service minio locally

I created a file with a claim

./deploy/local/volume.yaml
``` yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
 ```
 
 and I applied it using a pre-deploy hook:
 
 ``` yaml
 deploy:
  kubectl: 
    hooks:
      before:
        - host:
            command: ["sh", "-c", "kubectl apply -f ./deploy/local/volume.yaml"]
```
