### ISSUE TITLE
skaffold render does not support templates in helm valueFiles 

### ISSUE THREAD

**Issue by spingel** [GoogleContainerTools/skaffold#5163]
### Expected behavior

skaffold build and skaffold render use consistent command line arguments for helm.

### Actual behavior

```
% skaffold render
rendering manifests: std out err: Error: open {{.ENV}}.yaml: no such file or directory
```

### Information

- Skaffold version: 1.17.2 (brew installed)
- Operating system: Mac OS X 10.15.7
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta12
kind: Config
deploy:
  helm:
    releases:
    - name: postgres
      chartPath: bitnami/postgresql
      skipBuildDependencies: true
      valuesFiles:
      - "{{.ENV}}.yaml"
```

### Steps to reproduce the behavior

1. Run skaffold render with a skaffold.yaml that uses templates in deploy/helm/releases/valuesFiles

### Debug output

Render does not expand the template:

```
# ENV=production skaffold -v debug render
...
DEBU[0000] Running command: [helm --kube-context minikube template postgres bitnami/postgresql --values {{.ENV}}.yaml -f production.yaml]
rendering manifests: std out err: Error: open {{.ENV}}.yaml: no such file or directory
```

Whereas deploy expands the placeholder:

```
# ENV=production skaffold -v debug deploy
...
DEBU[0000] Running command: [helm --kube-context minikube upgrade postgres bitnami/postgresql -f production.yaml]
...
```
