### ISSUE TITLE
skaffold can't detect use of image in custom kuberenetes resource

### ISSUE THREAD

**Issue by sam46** [GoogleContainerTools/skaffold#5164]
I'm using the strimizi kafka operator to deploy a [KafkaConnect resource](https://strimzi.io/docs/operators/latest/using.html#proc-kafka-connect-config-str) with custom container image.

### Expected behavior
A kafka connect pod running (or at least successfully pulling the specified image).
Manually building the image then `kubectl apply`ing the resource works!

### Actual behavior
I get 
```
WARN[0002] image [my-project/my-kafka-connect] is not used by the deployment
```
during skaffold build, and an `ErrImagePull` on the KafkaConnect resource
### Information

- Skaffold version: v1.8.0
- Operating system: MacOS Mojave 10.14.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: my-project
build:
  artifacts:
  - image: my-project/my-kafka-connect
    context: k8s/kafka/build
    docker:
      dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
    - k8s/kafka/*.y*l
```

The KafkaConnect resource:
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  namespace: kafka
spec:
  image: my-project/my-kafka-connect
  version: 2.4.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
```
