### ISSUE TITLE
Can't access Database Pod using skaffold dev --port-foward in WSL2 from browser

### ISSUE THREAD

**Issue by cheslijones** [GoogleContainerTools/skaffold#5175]
### Expected behavior

The app is running in the `docker-desktop` cluster Docker Desktop for Windows ships with. The `ingress-nginx` controller is accepting traffic on `localhost`. I'm able to access and interact with the app at `localhost` normally.

The database is running on port `5432` so trying to connect to it using pgAdmin. Trying to access with `localhost:5432`. Also tested the API running on port `5000` and the Client running on `3000`.

### Actual behavior

 Not able to connect to any of the running deployments directly over `--port-forward` at `5432`, `5000`, `3000`.

### Information

- Skaffold version: `v1.17.2`
- Operating system: Windows 10 Pro 19042.685
- Contents of skaffold.yaml: 
```
apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: postgres
    context: postgres
    sync:
      manual:
      - src: "**/*.sql"
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  - image: app-client
    context: client
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
      - src: 'src/**/*.jsx'
        dest: .
      - src: '**/*.json'
        dest: .
      - src: 'public/**/*.html'
        dest: .
      - src: 'src/assets/sass/**/*.scss'
        dest: .
      - src: 'src/build/**/*.js'
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  - image: app-api
    context: api
    sync:
      manual:
      - src: "**/*.py"
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - manifests/dev/ingress.yaml 
      - manifests/dev/postgres.yaml
      - manifests/dev/client.yaml
      - manifests/dev/api.yaml
```
### Steps to reproduce the behavior

1. You can clone this repo: https://github.com/cheslijones/tls-dev-k8s.
2. Clone the repo into WSL2 not on the `/mnt/c/` file system.
3. `skaffold dev --port-forward`.
4. Run the following command to get the `ingress-nginx` running: 
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.41.2/deploy/static/provider/cloud/deploy.yaml
```
5. Wait until `kubetl get ing` has an external IP assigned (should be `localhost`).
6. Navigate to `localhost` in browser and should see the app running (`create-react-app` default screen).
7. Try to access it using over `--port-forward` with `localhost:3000` which is the default port where the CRA deployment is running.

Unable to access it directly over `--port-forward`. Really, this is only an issue if you are trying to access the database with something like pgAdmin or SQL Workbench, but trying to access the client at `3000` I think demonstrates the same issue.
