### ISSUE TITLE
Profiles with two activation criteria can cause patches to run twice

### ISSUE THREAD

**Issue by thalford185** [GoogleContainerTools/skaffold#5179]
### Expected behavior
Patches should run only once when the profile is activated.

### Actual behavior
Patches can run twice when the profile has two activation criteria.

In the example provided this causes a duplicate artifact definition.

### Information

- Skaffold version: v1.17.2
- Operating system: Ubuntu Server 16.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: img1
      context: .
profiles:
  - name: local
    activation:
      - command: dev
      - env: DEV=1
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: img2
          context: .
```

### Steps to reproduce the behavior

1. `git clone https://github.com/thalford185/skaffold-issue`
2. Set env var `DEV=1`
3. In repo directory run `skaffold dev`
