### ISSUE TITLE
Provide a way of disabling image building during dev profile

### ISSUE THREAD

**Issue by amirsamary** [GoogleContainerTools/skaffold#5180]
Hi! 

First of all: Great tool! I am evaluating it to use on an important project in my company and share it with our community of developers as a suggestion of tool for using our tech on Kubernetes.

### Expected behavior

Some technologies provide their own way of synching changes from the host machine into the container. For example, when using InterSystems IRIS and its VSCode plugin, one can save source code using VSCode and see it immediately applied to the running instance inside the cluster. Other features such as remote debugging are also available which make VSCode synch and debugging the most efficient way of developing with this backend.

I am using Angular as the frontend and Skaffold sync functionality is working great. 

The expected behavior is to be able to disable "watching for changes" for my backend image while leaving the normal behavior for my angular frontend.

Ideally, I should be able to have a patch under my **patches** section under my **dev** profile to set **sync.disabled=true** so that I could continue using skaffold run and build normally.

### Actual behavior

Skaffold will rebuild my backend image no matter what during the dev profile. This is very annoying since every time I am saving a file in VSCode a new build starts. 

### Information

- Skaffold version: v1.17.2
- Operating system: Mac
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config

# Standard build used by both "dev" and "run" profiles bellow
build:
  insecureRegistries: 
    - local-registry

  local:
    tryImportMissing: true
    push: true
    useBuildkit: true
    concurrency: 2
  
  tagPolicy:
    envTemplate:
      template: "latest"

  artifacts:
    - image: cp_frontend
      context: services/cp/cp_frontend
      docker:
        dockerfile: dev.Dockerfile
      sync:
        infer:
        - '**/*'
      requires:
        - image: base_angularcli
          alias: BASE_ANGULAR_IMAGE

    - image: base_angularcli
      context: base-images/base_angularcli

    # Right now, skaffold will rebuild this image during dev profile every time we save a file using VSCode.
    # There is no way to disable this. I have filing an enhancement request at https://github.com/GoogleContainerTools/skaffold/issues/new
    # to see if we can have a flag we could use here. Idealy, we should be able to use a patch operator to add a sync.disable=true here.
    - image: cp_backend
      context: services/cp/cp_backend
      requires:
        - image: base_iris
          alias: BASE_IRIS_IMAGE

    - image: base_iris
      context: base-images/base_iris


# Definitions of the "dev" and "run" profiles
profiles:
  
  # DEV Profile
  # Used when developping. 
  # We will just be using the standard build above without changes
  - name: dev
    activation:
      - command: dev

    deploy:

      kubectl:
        manifests:
          - ./services/cp/k8s/cp_frontend_deployment.yaml  
          - ./services/cp/k8s/cp_frontend_ingress.yaml  

          - ./services/cp/k8s/cp_backend_configmap_dev.yaml
          - ./services/cp/k8s/cp_backend_deployment.yaml

  # RUN Profile
  # Used when deploying (production). 
  # We will be patching "build" in order to remove synchronization of files 
  # and use production images where appropiate.
  - name: run
    activation:
      - command: run
    deploy:
      kubectl:
        manifests:
          - ./services/cp/k8s/cp_frontend_deployment.yaml
          - ./services/cp/k8s/cp_frontend_ingress.yaml  

          - ./services/cp/k8s/cp_backend_configmap_run.yaml
          - ./services/cp/k8s/cp_backend_deployment.yaml

    patches:
      # cp_frontend patches
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: run.Dockerfile
    
      - op: remove
        path: /build/artifacts/0/sync
```

### Steps to reproduce the behavior

I can't share this repository. But the behavior is easily reproducible. It is actually, so far, unavoidable. I am seeking for a way to stop reproducing it. I mean: stop building an image when files change. :)
