### ISSUE TITLE
Broken Check Cache Stage with Minikube and Buildkit

### ISSUE THREAD

**Issue by euriostigue** [GoogleContainerTools/skaffold#5183]
### Expected behavior
```bash
$ skaffold build
Generating tags...
 - wuher -> wuher:latest
 - raze -> raze:latest
 - sync-kinesis -> sync-kinesis:latest
Checking cache...
 - wuher: Not found. Building
 - raze: Not found. Building
 - sync-kinesis: Not found. Building
Found [minikube] context, using local docker daemon.
Building [sync-kinesis]...
```

### Actual behavior
```bash
$ skaffold build
Generating tags...
 - wuher -> wuher:latest
 - raze -> raze:latest
 - sync-kinesis -> sync-kinesis:latest
Checking cache...
 - wuher: Error checking cache.
getting hash for artifact "wuher": getting dependencies for "wuher": parsing dockerfile "/Users/eric/effx/effunctions/Dockerfile": Dockerfile parse error line 39: Unknown flag: mount
```

The Dockerfile:
```
# syntax=docker/dockerfile:experimental
# ubuntu:latest as of 11/30
FROM ubuntu@sha256:fff16eea1a8ae92867721d90c59a75652ea66d29c05294e6e2f898704bdb8cf1 AS base

...

COPY go.mod go.sum ./
RUN --mount=type=ssh go mod download && go mod verify # Line 37
...
RUN --mount=type=cache,target=/root/.cache/go-build make build

CMD ["npx", "sls", "offline","--stage", "dev"]
```

### Information

- minikube v1.16.0
- Skaffold version: v1.17.2
- Operating system: 
```bash
$ sw_vers
ProductName:    macOS
ProductVersion: 11.1
BuildVersion:   20C69
```
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: effunctions
build:
  local:
    useBuildkit: true
  tagPolicy:
    sha256: {}
  artifacts:
    - image: wuher
      custom:
        buildCommand: ./build.sh wuher
        dependencies:
          dockerfile:
            path: Dockerfile
            buildArgs:
              APP: wuher
    - image: raze
      custom:
        buildCommand: ./build.sh raze
        dependencies:
          dockerfile:
            path: Dockerfile
            buildArgs:
              APP: raze
    - image: sync-kinesis
      context: offline/sync-kinesis
deploy:
  kubectl:
    manifests:
      - "deploy/manifests/*.yaml"
    defaultNamespace: effunctions
```

### Steps to reproduce the behavior

After upgrading from skaffold v1.16 to v1.17.2, the hashing for cached images is broken. The same combination of Dockerfile, skaffold.yaml and build.sh works just fine with skaffold v1.16.

I'm guessing that the `useBuildkit` flag isn't getting passed properly during the "check cache" stage. If I removed all `mount` flags, the image will still build using buildkit.
