### ISSUE TITLE
Built image not showing when running "docker images"

### ISSUE THREAD

**Issue by cmamigonian** [GoogleContainerTools/skaffold#5185]
I am unable to prune an image built using skaffold on my local machine, as running `docker images` after building does not show the built image.

### Expected behavior

After running `skaffold build/run` I should be able to run `docker images` and see the resulting image.

### Actual behavior

I do not see the built image

### Information

- Skaffold version: 1.17.2
- Operating system: CentOS 7.4
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: skaffold-test
      kaniko:
        buildArgs:
          MY_ARG: "{{.MY_ARG}}"
  cluster:
    pullSecretName: tbd-secret
    pullSecretPath: kaniko-secret.json
    namespace: default
deploy:
  kubectl:
    manifests:
      - k8s-*

profiles:
  - name: minikube-profile
    # automatically activate this profile when current context is "minikube"
    activation:
      - kubeContext: minikube
    build:
      artifacts:
        - image: skaffold-test
          docker:
            target: final
            buildArgs:
              MY_ARG: "{{.MY_ARG}}"
      local: {}
```

`Dockerfile`:

```dockerfile
FROM alpine:3.12.0 AS first

ARG MY_ARG

COPY test.txt .

FROM first AS final

COPY --from=first /test.txt /

ARG MY_ARG

RUN echo ${MY_ARG}

CMD sleep 999
```

`k8s-pod.yaml`:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: skaffold-test
spec:
  containers:
    - name: skaffold-test-container
      image: skaffold-test
```

- minikube version: 1.16.0

### Steps to reproduce the behavior

1. `skaffold build`
2. `docker images`
