### ISSUE TITLE
Set kustomize cross-cutting options using skaffold

### ISSUE THREAD

**Issue by msonnleitner** [GoogleContainerTools/skaffold#5189]
I have created an issue in kustomize about setting `namePrefix` und `nameSuffix` using the CLI: https://github.com/kubernetes-sigs/kustomize/issues/3390 However, kustomize's philosophy is that everything should be specified in files and not in CLI switches or env variables.

When using kustomize with skaffold though, this assumption no longer holds since skaffold needs to overwrite the image at least. So I was wondering if skaffold is the right place for options like `namePrefix` and `nameSuffix`.

### Possible config

```yaml
deploy:
  kustomize:
    paths: ["path/to/kustomize"]
    namePrefix: somePrefix-
    nameSuffix: "{{.SOME_ENV_VARIABLE}}"
```

Does this make sense in a skaffold context?

**Comment by briandealwis** [comment]
Skaffold calls out to `kustomize` to perform the deployment.  I'm not a Kustomize expert but from what I understand these dev-settings would typically be done through a Kustomize overlay.  You can then map these overlays to corresponding Skaffold profiles.  @nkubala may have other ideas too.

**Comment by msonnleitner** [comment]
It is true that this is typically done with overlays, but some tools, such as ArgoCD still provide an option to override that:
https://argoproj.github.io/argo-cd/user-guide/kustomize/

**Comment by nkubala** [comment]
> When using kustomize with skaffold though, this assumption no longer holds since skaffold needs to overwrite the image at least.

i'm not sure this is true. we do overwrite the image, but only to substitute newly-built tags, or to apply a previously specified default repo value. everything about the image name is known before runtime.

i guess i'm not totally sure the difference between specifying these settings in a `skaffold.yaml` vs. a `kustomization.yaml`? you're still embedding the values in a config file somewhere in a declarative way. i actually think ArgoCD allowing that violates their principle of "declarative GitOps" :)

i'd probably recommend doing this through overlays invoked through skaffold profiles in the `skaffold.yaml`. you can specify different profiles, each with its own overlay, and then apply them additively through CLI switches:

```yaml
deploy:
  kustomize:
    paths:
    - overlays/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - overlays/prod
- name: staging
  deploy:
    kustomize:
      paths:
      - overlays/staging
```

and then something like `skaffold dev -p prod`.

i know its not exactly what you asked for, but does this solve your use case?
