### ISSUE TITLE
Log tailing shows chart name when using Helm

### ISSUE THREAD

**Issue by rubenhensen** [GoogleContainerTools/skaffold#5200]
### Expected behavior
When deploying a Helm chart the log tail should be [the pod name and container name if they’re not the same](https://skaffold.dev/docs/pipeline-stages/log-tailing/).
### Actual behavior
The log tail becomes the helm chart name, which makes different applications deployed with the same helm chart indistinguishable. e.g.:
```bash
[standard] info: Microsoft.Hosting.Lifetime[0]
[standard]       Now listening on: http://[::]:80
[standard] info: Microsoft.Hosting.Lifetime[0]
[standard]       Application started. Press Ctrl+C to shut down.
[standard] info: Microsoft.Hosting.Lifetime[0]
[standard]       Hosting environment: Development
[standard] info: Microsoft.Hosting.Lifetime[0]
[standard]       Content root path: /app
[standard] info: Microsoft.Hosting.Lifetime[0]
[standard]       Now listening on: http://[::]:80
[standard] info: Microsoft.Hosting.Lifetime[0]
[standard]       Application started. Press Ctrl+C to shut down.
[standard] info: Microsoft.Hosting.Lifetime[0]
[standard]       Hosting environment: Development
[standard] info: Microsoft.Hosting.Lifetime[0]
[standard]       Content root path: /app
```

### Information

- Skaffold version: version v1.17.2
- Operating system: Windows
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: tamf
build:
  artifacts:
  - image: console1
    context: .
    docker:
      dockerfile: ConsoleApp1/Dockerfile
  - image: console2
    context: .
    docker:
      dockerfile: ConsoleApp2/Dockerfile
deploy:
  helm:
    releases:
    - name: console1
      chartPath: standard
      artifactOverrides:
        image: console1

    - name: console2
      chartPath: standard
      artifactOverrides:
        image: console2
```

### Steps to reproduce the behavior
1. clone https://github.com/rubenhensen/log-tailing-example
2. `skaffold dev --status-check=false`
