### ISSUE TITLE
Building with Kaniko and private in-cluster registry fails to push: Authentication Required

### ISSUE THREAD

**Issue by john-terrell** [GoogleContainerTools/skaffold#5201]
### Expected behavior
Skaffold is able to successfully push to the private registry.

### Actual behavior
Attempting to run a Kaniko build with an in-cluster registry fails to push (our private in cluster registry URL changed to \<local registry\> in the below:

```code
Generating tags...
 - <local registry>/webservice -> <local registry>/webservice:v0.9.1-dirty
Checking cache...
 - <local registry>/webservice: Not found. Building
Building [<local registry>/webservice]...
E0104 18:00:27.104169       1 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "<local registry>/webservice:v0.9.1-dirty": POST https://r<local registry>/v2/webservice/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:webservice Type:repository] map[Action:push Class: Name:webservice Type:repository]]
pod has failed
```
### Information

- Skaffold version: v1.17.2
- Operating system: macOS Big Sur
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: webservice
build:
  cluster: {}
  artifacts:
  - image: <local registry>/webservice
    kaniko:
      cache: {}
deploy:
  kubectl:
    manifests:
    - deploy/deployment.yaml
```

Secrets:
```code
$ kubectl describe secret/regcred
Name:         regcred
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/dockerconfigjson

Data
====
.dockerconfigjson:  158 bytes

$ kubectl describe secret/kaniko-secret
Name:         kaniko-secret
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  generic

Data
====
kaniko-secret:  83 bytes
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold build`
3. ...
