### ISSUE TITLE
Artifact build order

### ISSUE THREAD

**Issue by jon-butterworth** [GoogleContainerTools/skaffold#5242]
I can't seem to find a definitive answer for the default build order of resources in a profile.

```
- name: dev1
  build:
    artifacts:
      - *BASE-IMAGE
      - *APP1
      - *APP2
    tagPolicy:
      sha256: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/dev1
```
I want to ensure that `BASE-IMAGE` is always built first, as it's used as `FROM` in the `Dockerfile` for `APP1` & `APP2`. 

I've tried using `requires` but am blocked by using v1 - there doesn't seem to be solid documentation surrounding what is available in v1 and more importantly, the changes needed to skaffold.yaml when switching from v1 to v2.
