### ISSUE TITLE
Is it possible to disable image push for a single image ?

### ISSUE THREAD

**Issue by robinbryce** [GoogleContainerTools/skaffold#5243]
Feature or guidance request

Is it possible to disable image push for a single image ?

We are trying to build an ephemeral base image using this new feature:

https://skaffold.dev/docs/tutorials/artifact-dependencies/

And then have most of the subsequent images in the build be FROM the alias.

But we do not want to take the (significant) hit of pushing that image to our repo

**Comment by robinbryce** [comment]
If it helps with the architecture, having tagged an image as "don't push" we would consider it an error for our kubernetes manifests to try and use that image. So "ephemeral" would be just as good for us.

**Comment by nkubala** [comment]
@robinbryce this isn't currently possible in our artifact model, but in theory wouldn't be so difficult to add, and definitely would be useful for building base images with skaffold. we likely won't be able to prioritize this right now though, but we would always be grateful for a contribution!

**Comment by gsquared94** [comment]
We recently released support for defining multiple configs. With this if you separate the `base` artifact into its own config then you can disable `build.push` setting for just this artifact. 

For example, run the `microservices` example project with this `skaffold.yaml`:
```yaml
apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: base
build:
  local:
    push: false
  artifacts:
  - image: base
    context: base
---
apiVersion: skaffold/v2beta14
kind: Config
requires:
  - configs: [base]
build:
  local:
    push: true
  artifacts:
    - image: gcr.io/google.com/gaghosh-test/leeroy-web
      context: leeroy-web
      requires:
        - image: base
          alias: BASE
    - image: gcr.io/google.com/gaghosh-test/leeroy-app
      context: leeroy-app
      requires:
        - image: base
          alias: BASE
deploy:
  kubectl:
    manifests:
      - leeroy-web/kubernetes/*
      - leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
  - resourceType: deployment
    resourceName: leeroy-app
    port: http
    localPort: 9001
```
where replace `gcr.io/google.com/gaghosh-test/` with your image registry.

To learn more: [tutorials](https://skaffold.dev/docs/tutorials/config-dependencies/), [docs](https://skaffold.dev/docs/design/config/#configuration-dependencies).
