### ISSUE TITLE
Error when running skaffold dev: docker build error invalid reference format

### ISSUE THREAD

**Issue by JovanShandro** [GoogleContainerTools/skaffold#5263]
I am trying to use skaffold for development and after running skaffold init, the following skaffold.yaml file was generated:

```yaml
apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: projectname
build:
  artifacts:
  - image: myusername/api
    docker:
      dockerfile: Dockerfile-api
  - image: myusername/client
    docker:
      dockerfile: Dockerfile-client
deploy:
  kubectl:
    manifests:
    - infrastructure/k8s/*

```

Whenever  I run skaffold dev I keep getting the following error:
```
exiting dev mode because first build failed: couldn't build "myusername/api": docker build: Error response from daemon: invalid reference format
```

I am using an ubuntu machine and minikube for creating the cluster.
Any idea what could be causing this error?

Thank you!
