### ISSUE TITLE
Use helm deploy next to kubectl

### ISSUE THREAD

**Issue by berstend** [GoogleContainerTools/skaffold#528]
### Expected behavior
```yaml

deploy:
  kubectl:
    manifests:
    - ./api/kubernetes/*
  helm:
    releases:
    - name: backend
      chartPath: umbrella-chart/
```
Both helm and kubectl deploy is being run

### Actual behavior

Only one deploy pipleline is executed

### Information

I really enjoy using skaffold as it simplifies development with local docker containers as no (external) docker registry is required.

When I add all my dependencies to helm and only issue helm deploys through skaffold I'm forced to use a docker registry as it doesn't seem to support pushing the containers directly.

When trying to mix helm with kubectl deploys (the latter to push docker containers directly) only one of them is executed, it doesn't seem like skaffold supports mixed deploy directives currently.

I'm currently using two different skaffold yamls and runs, one for helm and one for kubectl, which is a little cumbersome.

Is it possible to either mix kubectl/helm deploys or have helm deploys and still make use of the container-pushing-no-registry-needed part? :-)

Thanks!
