### ISSUE TITLE
 Enabling Kaniko on the included nodejs example project appears to break hot reload

### ISSUE THREAD

**Issue by onpaws** [GoogleContainerTools/skaffold#5285]
Not sure if what I'm seeing is a bug, please redirect me to the right place as appropriate.

I'm trying to track down why introducing Kaniko[1] to the example [nodejs] project appears to break hot reload.

### Steps to repro

1. Edit the [example]'s skaffold.yaml: under the `build` section [add] a `cluster:` stanza (I found I had to make a few add'l edits - complete **skaffold.yaml** below)
2. With your newly modified skaffold.yaml, run `skaffold dev`.
3. After things settle down, you should see
    ```
    Starting deploy...
     - service/node created
     - deployment.apps/node created
    Waiting for deployments to stabilize...
     - deployment/node: creating container node
        - pod/node-7874558fc5-8bqtr: creating container node
     - deployment/node is ready.
    Deployments stabilized in 8.213 seconds
    Press Ctrl+C to exit
    Watching for changes...
    [node] 
    [node] > backend@1.0.0 production /home/node/app
    [node] > node src/index.js
    [node] 
    [node] Example app listening on port 3000!
    [node] whats up
    Syncing 1 files for node-example:v1.18.0-3-gcc1fe7eea-dirty@sha256:8da4e046d74af499d6c17fbc781b5bab8ac6026dd890d30bd31185d3987c062b
    Watching for changes...
    ```

4. Run `curl http://example.com:3000/`, (obviously swap your real URL) you should see:

   `Hello World!`

3. Make some change to `index.js`, e.g. change 'Hello World' to 'Hi World'
4. Hit save. You should see something like:
    ```
    Syncing 1 files for node-example:v1.18.0-3-gcc1fe7eea-dirty@sha256:8da4e046d74af499d6c17fbc781b5bab8ac6026dd890d30bd31185d3987c062b
    Watching for changes...
    ```
5. Run `curl http://example.com:3000/` again

### Expected behavior
App should return 'Hi World'.

### Actual behavior
App still returns 'Hello World'.

### Curious detail
I noticed the vanilla example's output includes nodemon output. Kaniko's doesn't.

Vanilla example:
```
Syncing 1 files for node-example:v1.18.0-3-gcc1fe7eea-dirty@sha256:3de2c41eadf5352826f3e4b2118c1ebfa14de83ade9d88402223e0136f49ef0e
[node] [nodemon] restarting due to changes...
Watching for changes...
[node] [nodemon] starting `node src/index.js`
[node] [nodemon] starting `node src/index.js`
```
Kaniko example:
```
Syncing 1 files fornode-example:v1.18.0-3-gcc1fe7eea-dirty@sha256:8da4e046d74af499d6c17fbc781b5bab8ac6026dd890d30bd31185d3987c062b
Watching for changes...
```

Guess I have to figure out why `nodemon` isn't getting whatever signal it needs...
Any insight would be appreciated, if I figure it out I'll try to share/PR the solution.
Thanks for reading!

### Information

- Skaffold version: v1.18.0
- Operating system: macOS 11.1 20C69
- Editor: Visual Studio Code 1.53.0-insider
- Contents of skaffold.yaml: (adapted from [example])

### skaffold.yaml
```yaml
apiVersion: skaffold/v2beta11
kind: Config

build:
  artifacts:
  - image: node-example
    context: backend
  cluster: 
    dockerConfig:
      path: config.json

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: node-example
        context: backend
        # docker:
        #   buildArgs:
        #     ENV: development
        sync:
          manual:
          # Sync all the javascript files that are in the src folder
          # with the container src folder
          - src: 'src/**/*.js'
            dest: .
```

[1] I prefer to build in-cluster which is why I'm trying to use Kaniko in the first place. If there is some other non-Kaniko route to do this, ideally with example code I could check out, I'd be curious!

[add]: https://skaffold.dev/docs/pipeline-stages/builders/#in-cluster-build
[nodejs]: https://github.com/GoogleContainerTools/skaffold/tree/2dc06b2bcf2496204bf897fde690e5a44b4920b5/examples/nodejs "doesnt work"
[title]: https://github.com/GoogleContainerTools/skaffold/tree/v1.18.0/examples/nodejs#example-nodejs-with-hot-reload
[example]: https://github.com/GoogleContainerTools/skaffold/blob/v1.18.0/examples/nodejs/skaffold.yaml
