### ISSUE TITLE
use minikube context annotations in ~/.kube/config

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5293]
[minikube 1.17.0](https://github.com/kubernetes/minikube/releases/tag/v1.17.0) now includes [annotations on the context and cluster elements](https://github.com/kubernetes/minikube/pull/10126) in the `~/.kube/config` that identify it as minikube:

```
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Thu, 21 Jan 2021 16:30:12 PST
        provider: minikube.sigs.k8s.io
        version: v1.16.0
      name: context_info
```

We should use these details in our is-minikube test and eventually can cut out the old-style `minikube profile list`.
