### ISSUE TITLE
[1.17+] Build does not push images to remote repository

### ISSUE THREAD

**Issue by othercorey** [GoogleContainerTools/skaffold#5334]
### Expected behavior
Check for tag in remote repository and push images.

### Actual behavior
Builds and tags images but does not push. Helm upgrade fails trying to pull image that doesn't exist.

### Information

- Skaffold version: 1.17+
- Operating system: Windows 10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta7
kind: Config

profiles:
- name: test
  build:
    local:
        push:
    tagPolicy:
      gitCommit:
        prefix: test-
    artifacts:
    - image: <account>.dkr.ecr.us-east-1.amazonaws.com/main-web-nginx
      context: .
      docker:
        dockerfile: deploy/docker/nginx.Dockerfile
    - image: <account>.dkr.ecr.us-east-1.amazonaws.com/main-web-phpfpm
      context: .
      docker:
        dockerfile: deploy/docker/php.Dockerfile
  deploy:
    kubeContext: prod-main
    helm:
      releases:
      - name: main-web
        chartPath: ./deploy/helm/main-web
        namespace: test
        artifactOverrides:
          nginx.image: <account>.dkr.ecr.us-east-1.amazonaws.com/main-web-nginx
          phpfpm.image: <account>.dkr.ecr.us-east-1.amazonaws.com/main-web-phpfpm
```

### Steps to reproduce the behavior

1. skaffold run -p test

This has been working up to version 1.17. I'm not sure of any missing configuration requirements.
