### ISSUE TITLE
Skaffold not using specified namespace

### ISSUE THREAD

**Issue by TheYkk** [GoogleContainerTools/skaffold#5338]
### Expected behavior
Skaffold should deploy helm chart to specified namespace.

### Actual behavior
Skaffold gets namespace from my kubeconfig and its trying to deploy that namespace not my specified namespace.
I was using skaffold v1.17.2 and I upgraded v1.19.0 then skaffold is not worked.
I used `skaffold fix`
### Information

- Skaffold version: v1.19.0
- Operating system: ubuntu:20.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: project
build:
  artifacts:
    - image: myimage
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: project-dev
        chartPath: project
        artifactOverrides:
          image: myimage
        namespace: "mynamespace"
        wait: true
    flags:
      install:
        - --timeout=3m
        - --debug
      upgrade:
        - --timeout=3m
        - --install
        - --debug
```

### Steps to reproduce the behavior

1. skaffold fix
2. skaffold dev
