### ISSUE TITLE
Skaffold namespace from environment

### ISSUE THREAD

**Issue by TheYkk** [GoogleContainerTools/skaffold#5339]
### Expected behavior
Skaffold should get namespace from environment

### Actual behavior
```log
exiting dev mode because first deploy failed: could not fetch deployments: could not fetch deployments: deployments.apps is forbidden: User "system:serviceaccount:kaank:kaank" cannot list resource "deployments" in API group "apps" in the namespace "{{.NAMESPACE}}"
```

I was using skaffold v1.17.2 and I upgraded v1.19.0 then skaffold is not worked.
I used `skaffold fix`
### Information

- Skaffold version: v1.19.0
- Operating system: ubuntu:20.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: project
build:
  artifacts:
    - image: myimage
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: project-dev
        chartPath: project
        artifactOverrides:
          image: myimage
        namespace: "{{ .NAMESPACE}}"
        wait: true
    flags:
      install:
        - --timeout=3m
        - --debug
      upgrade:
        - --timeout=3m
        - --install
        - --debug
```

### Steps to reproduce the behavior

1. skaffold fix
2. skaffold dev
