### ISSUE TITLE
Using helm with `skaffold -f path/to/skaffold.yaml` throws error expecting skaffold.yaml in cwd

### ISSUE THREAD

**Issue by j-windsor** [GoogleContainerTools/skaffold#5355]
From https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/379
Creating on behalf of Cloud Code user @dsaydon90
### Expected behavior
When running `skaffold -f path/to/skaffold.yaml`, the command knows where to find the skaffold yaml file because it is specified in the args.

### Actual behavior
User gets error searching for skaffold in the cwd: `skaffold config file skaffold.yaml not found - check your current working directory, or try running skaffold init`

### Information

- Skaffold version: 1.19.0
- Operating system: Ubuntu 20 WSL
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
build:
  tagPolicy:
    sha256: {}
  local:
    useDockerCLI: true
    useBuildkit: true
    push: false
  artifacts:
  - image: project
    context: "../Application"
    docker:
      dockerfile: "Dockerfile"
      buildArgs:
        FOO: "{{.BAR}}"
    sync:
      infer:
      - '**/*'
deploy:
  kubeContext: minikube
  helm:
    flags:
      upgrade: ['--install']  
    releases:
    - name: project
      chartPath: project
      namespace: local
      valuesFiles:
      - "project/dev-values.yaml"
      wait: true
      upgradeOnChange: true
      artifactOverrides:
        image: project
      setValues:
        image.pullPolicy: "IfNotPresent"
```
