### ISSUE TITLE
helm deploys before kubectl

### ISSUE THREAD

**Issue by imerkle** [GoogleContainerTools/skaffold#5362]
### Expected behavior

```
  deploy:
    kubectl:
      manifests:
        - ./namespace.yaml   
    helm:
      releases:
      - name: drone
        chartPath: drone/drone
        remote: true
        valuesFiles: 
          - drone-values.yaml
        namespace: mynamespace 
```
`kubectl` should run first then `helm`. i.e whichever is first and not alphabetically asc
### Actual behavior
`helm` runs first so `mynamespace` doesn't exists therefore fails

### Information

- Skaffold version: 1.19.x
- Operating system: ubuntu
- Contents of skaffold.yaml:

above

### Steps to reproduce the behavior

above
