### ISSUE TITLE
invalid skaffold.yaml causes skaffold to crash

### ISSUE THREAD

**Issue by msonnleitner** [GoogleContainerTools/skaffold#5363]
`skaffold dev`

### Actual behavior
>panic: runtime error: invalid memory address or nil pointer dereference
>[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x19969cd]

### Information

- Skaffold version: 1.19.0
- Operating system: tried with MacOS, Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: bug
portForward:
 -
```
