### ISSUE TITLE
How to process "replace" in go.mod files ?

### ISSUE THREAD

**Issue by ngodzik** [GoogleContainerTools/skaffold#5365]
I am struggling to use replace in go.mod files with Skaffold and Golang, to work easily with local module changes (without tagging)

could it work with Skaffold files sync ?

or should I look more into Kubernetes volumes so that I can run the "skaffold dev" command again each time I change such an external file ?

are there good practices to work with go modules local replacements and Skaffold ?

**Comment by nkubala** [comment]
@ngodzik not sure I quite understand your question. are you trying to develop on a library and use that as a local dependency to another project? if you can provide more information about your project we might be able to better help you.

**Comment by ngodzik** [comment]
Thank you for your answer, and sorry for the delay

Let's imagine that I am developing on the skaffold repository, and I want to make some changes on the **uuid** package (or whatever package) to help me debugging something on skaffold 

go.mod:
>module github.com/GoogleContainerTools/skaffold
>
> go 1.15
> 
> ...
> 
> require (
> ...
> 	github.com/go-git/go-git/v5 v5.0.0
> 	github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
> 	github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
> 	github.com/golang/protobuf v1.4.3
> 	github.com/google/go-cmp v0.5.5
> 	github.com/google/go-containerregistry v0.4.1-0.20210128200529-19c2b639fab1
> 	github.com/google/go-containerregistry/pkg/authn/k8schain v0.0.0-20210216200643-d81088d9983e // indirect
> 	github.com/google/go-github v17.0.0+incompatible
> 	github.com/google/uuid v1.1.2
> 	github.com/grpc-ecosystem/grpc-gateway v1.14.8
> 	github.com/heroku/color v0.0.6
> ...
> )
> 

I would add this line to the **go.mod** file from skaffold (or set it in the replace block)
 
> replace github.com/google/uuid => ../../google/uuid

when I run **skaffold dev** I would have an error like that:

_go: github.com/google/uuid v1.1.2 (replaced by ../../google/uuid): reading /uuid/go.mod: open /uuid/go.mod: no such file or directory_

this works pretty well using a docker-compose local way, but I don't know how to make it work with skaffold

**Comment by nkubala** [comment]
@ngodzik sorry for the super late reply here. did you ever try using a [custom builder](https://skaffold.dev/docs/pipeline-stages/builders/custom/) to run something like `go vet` or something similar? you should be able to use this to run some go validation before doing your `go build`.

**Comment by ThomasP1988** [comment]
Hi everyone,
Somehow i succeed to do it like this
```
build:
  artifacts:
  - image: apis/market
    context: ../apis/market
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
    hooks:
      before:
        - command: ["make", "-C", "../apis/market", "pre-build"]
          os: [darwin, linux, windows]
      after:
        - command: ["make", "-C", "../apis/market", "post-build"]
          os: [darwin, linux, windows]
```
          
and my makefile being like this

```
pre-build:
	go mod vendor
post-build:
	rm -rf ./vendor
```

I've tried to do it with a dockerfile but it didn't work, the pre-build correctly set the vendor folder but when i ls in the dockerfile it's not there.
