### ISSUE TITLE
Artifact workspace and other `filepath` type fields not being set correctly in configs imported as dependencies

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#5388]
Consider the directory:
```
.
├── foo
│   └── skaffold.yaml
└── skaffold.yaml
```
where `./skaffold.yaml` is:
```yaml
apiVersion: skaffold/v2beta12
kind: Config
requires:
  - path: foo
```
and `./foo/skaffold.yaml` is:
```yaml
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: cfg1
requires:
  - configs: [cfg2]

---

apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: cfg2
build:
  artifacts:
  - image: foo
```
### Expected behavior
If I run `skaffold diagnose --yaml-only`, I expect:

```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: cfg2
build:
  artifacts:
  - image: foo
    context: /Users/gaghosh/Code/Hack/foobar/foo
...
```

### Actual behavior
I actually get:

```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: cfg2
build:
  artifacts:
  - image: foo
    context: .
...
```

The `build.context` isn't resolved to the absolute path for the config `cfg2` that's imported as a dependency in `./skaffold.yaml`
