### ISSUE TITLE
Unexpected base-path for required skaffold's helm.setValues

### ISSUE THREAD

**Issue by arash16** [GoogleContainerTools/skaffold#5396]
### Expected behavior
From a root ```skaffold.yaml``` file, I have imported (requires section) another ```skaffold.yaml``` file inside a deeper directory. Within that child ```skaffold.yaml```, I have used helm to describe my deployments. within helm's release configuration, I tried to set ```valuesFiles``` property to a file alongside this ```skaffold.yaml```.

Here I expected file-path to be relative to this child ```skaffold.yaml```, so that I will be able run it separately too.

### Actual behavior
When I set values file relative to child ```skaffold.yaml```, cli errors that it cannot find that file. I have to set file-path relative to root ```skaffold.yaml```.

### Information

- Skaffold version: 1.20
- Operating system: Linux Mint
- Contents of skaffold.yaml:

#### /skaffold.yaml
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: hikingo

requires:
- path: ./frontend/web-app
```

#### frontend/web-app/skaffold.yaml
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: web-app
build:
  artifacts:
  - image: xyz
deploy:
  helm:
    releases:
    - name: web-app
      chartPath: ../../infra/charts/microservice
      artifactOverrides:
        image: xyz
      valuesFiles:
      - ./helm-values.yaml # <<<< I expect this path to be relative to current skaffold.yaml's file
```

#### frontend/web-app/helm-values.yaml
```yaml
name: web-app
image: xyz
```
