### ISSUE TITLE
Regression: Skaffold Restricts Buildkit to Dockerfile Frontend on PR 4943

### ISSUE THREAD

**Issue by MateusAmin** [GoogleContainerTools/skaffold#5398]
### Expected behavior

Skaffold builds [cargo-wharf](https://github.com/denzp/cargo-wharf) as it works fine with:
```sh
  DOCKER_BUILDKIT=1 docker build -f Cargo.toml .
```

### Actual behavior

Skaffold throws the error that I get with Docker without buildkit.

### Information

- Skaffold version: apiVersion: skaffold/v2beta12
- Operating system: Ubuntu
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: 5398
build:
  artifacts:
  - image: 5398
    docker:
      dockerfile: Cargo.toml
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 1
```

### Steps to reproduce the behavior

You will need Rust installed.

1. https://github.com/MateusAmin/skaffold-issues-5398
2. skaffold build

**Comment by MateusAmin** [comment]
This is a regression. I had another project that *was* working with the following yaml:

```yaml
apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
  - image: db-test
    docker:
      dockerfile: Cargo.toml
      # dependencies:
      #   paths: ["src/*.rs"]
  local:
    useBuildkit: true

deploy:
  kubectl:
    manifests:
      - k8s.test.yml
```
