### ISSUE TITLE
Tagger fails when building artifact with multiple tags 

### ISSUE THREAD

**Issue by johanjk** [GoogleContainerTools/skaffold#5411]
Using the new [multiple config](http://tinyurl.com/skaffold-multi-configs), building two different tags of one artifact is now semantically possible, _as suggested by @nkubala in https://github.com/GoogleContainerTools/skaffold/issues/1269#issuecomment-767212603_.

Issue is, the tagger overrides each tag of artifacts with the same name, with the last seen tagPolicy.

### Expected behavior
```console
Listing files to watch...
 - foo/bar
 - foo/bar
Generating tags...
 - foo/bar -> foo/bar:a-latest
 - foo/bar -> foo/bar:b-latest
```

### Actual behavior
```console
Listing files to watch...
 - foo/bar
 - foo/bar
Generating tags...
 - foo/bar -> foo/bar:b-latest
 - foo/bar -> foo/bar:b-latest
```

### Information

- Skaffold version: v1.20.0
- Operating system: linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: a-config

build:
  tagPolicy:
    customTemplate:
      template: 'a-{{.SHA}}'
  artifacts:
    - image: foo/bar
      docker:
        dockerfile: a.dockerfile

---

apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: b-config

requires:
  - configs:
    - a-config

build:
  tagPolicy:
    customTemplate:
      template: 'b-{{.SHA}}'
  artifacts:
    - image: foo/bar
      docker:
        dockerfile: b.dockerfile
```
- Contents of a.dockerfile and b.dockerfile:
```dockerfile
FROM alpine:latest
```
### Steps to reproduce the behavior

`skaffold dev`
