### ISSUE TITLE
kaniko - in cluster - pull initImage and Image from a private registry

### ISSUE THREAD

**Issue by fdruillennec** [GoogleContainerTools/skaffold#5419]
### Expected behavior

The initContainer and executor images are pulled well from a private registry.

### Actual behavior

At work, I cannot pull docker images directly from gcr.io. A internal remote registry is required with authentication.
In the file skaffold.yaml, I set the 2 fields image and initImage with the internal registry prefix to pull the executor and busybox images.

When Kubernetes tries to start the pod kaniko, pulling the busybox is getting to the error:
```
Failed to pull image "private-gcr-remote-registry/k8s-skaffold-skaffold-helpers/busybox" rpc error: code = Unknown desc = Error response from daemon: Get https://private-gcr-remote-registry/k8s-skaffold-skaffold-helpers/busybox/manifests/latest: no basic auth credentials
```

In the manifest of the pod, there is no imagePullSecrets reference in the spec. (that could be the root cause)

In the skaffold reference, section cluster, I found 2 properties:
- pullSecretName (which seems to be related to a Google Cloud service account secret key, which is not my usecase)
- dockerConfig: is set to my registry credentials

When I create a kaniko pod from the generated one by skaffold and I add imagePullSecrets to the spec, pulling the initImage works.

Am I missing a configuration to use private registries to pull kaniko images?

### Information

- Skaffold version: 1.20
- apiVersion: skaffold/v2beta12
- Operating system: ubuntu 16.04
- Contents of skaffold.yaml: 

```yaml
...
artifacts:
  - image: imageToBuild
    context: path to the code source of the image
    kaniko:
      image: private-gcr-remote-registry/kaniko-project/executor:latest
      initImage: private-gcr-remote-registry/k8s-skaffold-skaffold-helpers/busybox
      target: dev
```

**Comment by tejal29** [comment]
The initImage just runs the kaniko container to mount local source code into the pod. 
It expects a `tar` to be there which `busybox` has.
you want to use the `dockerConfig` which points to a docker config file like this 
```
build:
  cluster:
    dockerConfig:
      path: ~/.docker/config.json
```
