### ISSUE TITLE
Status Check misleading error

### ISSUE THREAD

**Issue by glouischandra** [GoogleContainerTools/skaffold#5424]
### Expected behavior
Clear error message from status check about image access instead of user cancelled

### Actual behavior
Received STATUSCHECK_USER_CANCELLED

### Information

- Skaffold version: v1.19.0
- Operating system: Linux Goobuntu
![image](https://user-images.githubusercontent.com/3677364/108579574-6783e200-72dc-11eb-914e-b2eed1918fc7.png)

- Contents of skaffold.yaml:

```yaml
# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: nodejs-guestbook-backend
    context: src/backend
  - image: nodejs-guestbook-frontend
    context: src/frontend
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.service.yaml
    - ./kubernetes-manifests/*.deployment.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: buildpacks
  build:
    artifacts:
    - image: nodejs-guestbook-backend
      context: src/backend
      buildpack:
        builder: "gcr.io/buildpacks/builder:v1"
    - image: nodejs-guestbook-frontend
      context: src/frontend
      buildpack:
        builder: "gcr.io/buildpacks/builder:v1"

Launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run on Kubernetes",
            "type": "cloudcode.kubernetes",
            "request": "launch",
            "skaffoldConfig": "${workspaceFolder}/skaffold.yaml",
            "watch": true,
            "cleanUp": true,
            "portForward": true,
            "imageRegistry": "gcr.io/glouischandra-test",
            "debug": [
                {
                    "image": "nodejs-guestbook-frontend",
                    "sourceFileMap": {
                        "${workspaceFolder}/src/frontend": "/frontend"
                    }
                },
                {
                    "image": "nodejs-guestbook-backend",
                    "sourceFileMap": {
                        "${workspaceFolder}/src/backend": "/backend"
                    }
                }
            ]
        }
    ]
}

```

### Steps to reproduce the behavior
I am using Cloud Code AutoGKE run/debug functionality and deploying the sample guestbook nodejs application. 
Created auto-gke clusters and deploying there yields this error:
![image](https://user-images.githubusercontent.com/3677364/108579474-d1e85280-72db-11eb-8cd8-5662708a3495.png)

I can see the warning of image can't be pulled but the final error code seems confusing as it says user_cancelled.
