### ISSUE TITLE
Debug docs should warn about re-entrancy with probes

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5425]
We encountered a situation where ~a breakpoint was placed on the calling path of~ a user was stopped in a breakpoint.  This pod had a liveness probe that called back into the app. Because the server was blocked due to the debug session in progress, and liveness probes have a timeout of 1 second, the probe was deemed to have failed and k8s restarted the container.
```
  containers:
  - name: example
    image: example-image
    ports:
    - containerPort: 8080
    # connect to the app port
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 2
      periodSeconds: 10
```

it makes sense that a developer might want to debug a liveness or readiness or startup probe. Debug could rewrite such probes to set/increase the timeout period of 5 minutes (ideally configurable in some way).

cc: @VeerMuchandi
