### ISSUE TITLE
if git is not installed skaffold silently falls back to sha256 tagPolicy

### ISSUE THREAD

**Issue by sev3ryn** [GoogleContainerTools/skaffold#5439]
When git is not installed skaffold silently falls back to sha256 tagPolicy ignoring gitCommit tagPolicy

### Expected behavior

FAILURE: git not installed. Can't use specified tagPolicy

### Actual behavior

Silent fallback to sha256 tagPolicy. Images tagged with IMAGE_TAG is set to latest

### Information

- Skaffold version: 1.20.0
- Operating system: all
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: best
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    push: true
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: best
        chartPath: helm/best
```

### Steps to reproduce the behavior

1. uninstall git
2. `skaffold render`
3. no errors present, image tag set to latest
