### ISSUE TITLE
Cannot parse configuration files with multi line strings using literal style

### ISSUE THREAD

**Issue by uvegla** [GoogleContainerTools/skaffold#5440]
### Expected behavior
Skaffold can parse yaml files that contain multi line stings using the [literal style](https://yaml.org/spec/1.2/spec.html#id2795688) with empty lines in them. (Or see [this](https://yaml-multiline.info/) for a nicer explanation.)

### Actual behavior
Skaffold fails to parse yaml files with multi line strings using literal style with empty lines in them.

### Information

- Skaffold version: v1.20.0
- Operating system: macOS Big Sur 11.1
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
  - image: skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      artifactOverrides:
        image: skaffold-helm
      setValues:
        configuration: |
          [section_one]
          first_value = first

          [section_two]
          second_value = second
```

### Steps to reproduce the behavior

I modified the `examples/helm-deployment/skaffold.yaml` file for this example. By setting a multi line override that contains empty line(s) Skaffold fails to parse the file with the following error.

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/yamltags.GetYamlTags(0x5ad04c0, 0xc0003deb40, 0x5ad04c0, 0xc0003deb40, 0xc0006ba228)
	/skaffold/pkg/skaffold/yamltags/tags.go:105 +0x3d2
github.com/GoogleContainerTools/skaffold/pkg/skaffold/instrumentation.InitMeterFromConfig(0xc0006a8ae0, 0x1, 0x1)
	/skaffold/pkg/skaffold/instrumentation/meter.go:88 +0x251
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.createNewRunner(0x60860e0, 0xc000468b00, 0x7ffeefbff160, 0xd, 0x7279760, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/skaffold/cmd/skaffold/app/cmd/runner.go:66 +0xdc
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner(0x60d8560, 0xc0003e7ac0, 0x60860e0, 0xc000468b00, 0xc0009bdbc0, 0x0, 0x3)
	/skaffold/cmd/skaffold/app/cmd/runner.go:48 +0x76
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runDev(0x60d8560, 0xc0003e7ac0, 0x60860e0, 0xc000468b00, 0x0, 0x0)
	/skaffold/cmd/skaffold/app/cmd/dev.go:63 +0x178
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc0005d0580, 0xc0007700a0, 0x0, 0x2, 0x0, 0x0)
	/skaffold/cmd/skaffold/app/cmd/commands.go:124 +0x98
github.com/spf13/cobra.(*Command).execute(0xc0005d0580, 0xc000770080, 0x2, 0x2, 0xc0005d0580, 0xc000770080)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005d0000, 0x10, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:888
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x6085440, 0xc00019e008, 0x6085440, 0xc00019e010, 0x0, 0x0)
	/skaffold/cmd/skaffold/app/skaffold.go:47 +0x13d
main.main()
	/skaffold/cmd/skaffold/skaffold.go:37 +0x5c
```

A possible workaround is to replace the multi line indicator from `|` (literal style) to `>` (folded style), [source](https://yaml.org/spec/1.2/spec.html#id2795688). Although I am sure it was working back in Skaffold `v1.14.0` and previously.
