### ISSUE TITLE
skaffold render does not render helm secrets

### ISSUE THREAD

**Issue by rccrdpccl** [GoogleContainerTools/skaffold#5454]
### Expected behavior
When running `skaffold render` with the option `useHelmSecrets: true` we should see decrypted secrets.

### Actual behavior
Secrets are rendered as crypted values (as helm secrets plugin is not executed)

### Information

- Skaffold version: 1.20.0
- Operating system: Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: test
deploy:
  helm:
    releases:
      - name: test-v2
        chartPath: ./charts/test
        valuesFiles:
          - ./charts/test/values.yaml
          - ./charts/test/secrets.values.yaml
        createNamespace: true
        namespace: test-v2
        useHelmSecrets: true

```

### Steps to reproduce the behavior

1. https://github.com/rccrdpccl/skaffold-debug/tree/helm-secrets
2. gpg --import pgp/sops_functional_tests_key.asc
3. `skaffold render` (or `skaffold render | grep -A1 PASSWORD`)

Expected:
```yaml
- name: PASSWORD
  value: mysecretpassword
```

Actual:
```yaml
- name: PASSWORD
  value: ENC[AES256_GCM,data:BAyN6ZdiPG/c/roDuNr89w==,iv:kqj/6F+T1yozfFIu7Y6gMCFv08Fy19aBtU4nraF+JEQ=,tag:VF1p4Eq4DuR1FSLL/J0TNw==,type:str]
```
