### ISSUE TITLE
Multi-Skaffold project warns about helm problem not replacing image names

### ISSUE THREAD

**Issue by arash16** [GoogleContainerTools/skaffold#5455]
I have a root skaffold that ```requires``` multiple other ```skaffold.yaml``` files. If I comment out all ```requires``` except one of them, everything works fine. But when I ```requires``` multiple ```skaffold.yaml``` files, skaffold gives following warnings:

```
WARN[0266] image [xyz:635e1d16cc34642aa45bac89df9ed7366eb79d1e78aa4f237141aa5145d4918a] is not used. 
WARN[0266] image [xyz] is used instead. 
WARN[0266] See helm sample for how to replace image names with their actual tags: https://github.com/GoogleContainerTools/skaffold/blob/master/examples/helm-deployment/skaffold.yaml
```

### Information

- Skaffold version: 1.20.0
- Operating system: Linux Mint 19
- Contents of skaffold.yaml:

#### skaffold.yaml
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: root
requires:
- path: ./backend
- path: ./frontend
```

#### backend/skaffold.yaml
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: backend
build:
  artifacts:
  - image: backend
    sync:
      infer:
      - "*/**/*.js"

deploy:
  helm:
    releases:
    - name: backend
      chartPath: ../infra/charts/microservice
      artifactOverrides:
        image: backend
      valuesFiles:
      - backend/service-values.yaml

profiles:
  - name: dev
    activation:
      - command: dev
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          ingress.tld: localhost
          env.NODE_ENV: development
          env.LOGLEVEL: debug

```
#### frontend/skaffold.yaml
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: frontend
build:
  artifacts:
  - image: frontend
    sync:
      infer:
      - "*/**/*.js"

deploy:
  helm:
    releases:
    - name: frontend
      chartPath: ../infra/charts/microservice
      artifactOverrides:
        image: frontend
      valuesFiles:
      - frontend/service-values.yaml

profiles:
  - name: dev
    activation:
      - command: dev
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          ingress.tld: localhost
          env.NODE_ENV: development
          env.LOGLEVEL: debug
```
