### ISSUE TITLE
Provide context when reporting required config errors

### ISSUE THREAD

**Issue by omninonsense** [GoogleContainerTools/skaffold#5456]
### Expected behavior

Give more context when reporting errors inside required modules.

An example of what the message might look like for the `path` option:

```
parsing skaffold config: unable to parse config: yaml: unmarshal errors:
  context: /home/nino/projects/derp/apps/smtp/skaffold.yaml
  line 11: field imago not found in type latest.Artifact
```

When using the Git option it could be

```
parsing skaffold config: unable to parse config: yaml: unmarshal errors:
  context: git@github.com:GoogleContainerTools/skaffold.git:path/to/skaffold.yaml
  line 11: field imago not found in type latest.Artifact
```

And so on, you get the idea.

I'm not sure if it makes sense to also provide a list of named parent configs (ie dependants) so people know where the dependency comes from, but I've not looked at the Skaffold code yet, so I don't know how difficult it would be to add that.

### Actual behavior

Only the line is reported, which isn't super useful when there are many modules included with Skaffold. This then leads to having to manually comment configs in the top-level skaffold.

An example with a typo:

```
parsing skaffold config: unable to parse config: yaml: unmarshal errors:
  line 11: field imago not found in type latest.Artifact
```

### Information

- Skaffold version: v1.20.0
- Operating system: Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: platform-ns
requires:
  - path: apps/database/skaffold.yaml
  - path: apps/redis/skaffold.yaml
  - path: apps/smtp/skaffold.yaml
# ... many more
  - path: apps/web/skaffold.yaml
deploy:
  kubeContext: minikube
---
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: tools-ns
requires:
  - path: apps/tools/c10r/skaffold.yaml
  - path: apps/tools/tools/skaffold.yaml
deploy:
  kubeContext: minikube
```

### Steps to reproduce the behavior

No specific steps, just require an invalid config in a top-level skaffold.yaml file (this issue also applies to "nested" required configs, which further exacerbates the issue).
