### ISSUE TITLE
helm remote deploy fails when "required" by another config

### ISSUE THREAD

**Issue by m1o1** [GoogleContainerTools/skaffold#5459]
- Skaffold version: version: **v1.20.0**
- Operating system: **Windows 10**

Scenario 1:

If I skaffold run with this, it successfully installs the ingress-nginx helm chart:
`skaffold.yaml`:
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: myapp
deploy:
  helm:
    releases:
      - name: nginx
        namespace: nginx
        createNamespace: true
        chartPath: ingress-nginx/ingress-nginx
        remote: true
        setValues:
          controller.service.type: NodePort
```
---
Scenario 2:

If I want to put this nginx config in a different skaffold config like so:
`skaffold.yaml`:
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: myapp
requires:
- path: ./skaffold/nginx.yaml
```
`skaffold/nginx.yaml`:
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: nginx
deploy:
  helm:
    releases:
      - name: nginx
        namespace: nginx
        createNamespace: true
        chartPath: ingress-nginx/ingress-nginx
        remote: true
        setValues:
          controller.service.type: NodePort
```
then it fails with this error:
```
$ skaffold run
Generating tags...
Checking cache...
Tags used in deployment:
Starting deploy...
Helm release nginx not installed. Installing...
Error: path "D:\\dev\\myapp\\skaffold\\ingress-nginx\\ingress-nginx" not found
install: exit status 1
```
It seems like in this configuration, it's ignoring the `remote: true` in the helm deploy configuration.

**Comment by m1o1** [comment]
I'm guessing this is related to the [Multiple working directories](https://docs.google.com/document/d/1dA1549Rj9xfAt5sHh-wHng1MQT1A9SOylLt4xEjctGk/edit#) of the design doc for multi-config skaffold. 

Also, in the `chartPath` and `valuesFiles` below, the path is somewhat unintuitive since it's relative to the top-level skaffold file (or maybe where I'm running skaffold from), not the config that it's parsing at that time. Maybe this is what the design doc is planning to fix though (I assumed it was merged in already though, since the `requires` field is in).

With the "top-level" skaffold in `$workspaceDir/.local-dev/skaffold.yaml`, and the following skaffold.yaml for myapp2:

`$workspaceDir/myapp2/skaffold.yaml`:
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: myapp2
build:
  # ...
deploy:
  helm:
    releases:
      - name: myapp2
        namespace: imodeljs
        chartPath: ../myapp2/deployment/helm-chart
        valuesFiles:
          - ../myapp2/deployment/helm-chart/values-dev.yaml
```
It was a bit unintuitive that I couldn't do `chartPath: ./deployment/helm-chart` and `valuesFiles: ./deployment/helm-chart`.

**Comment by gsquared94** [comment]
@m1o1 I believe you've run into  #5396. We've fixed it via #5452. Is it possible to try out against our unreleased binary here and let us know if that worked for you?

For windows:
```
https://storage.googleapis.com/skaffold/build/latest/skaffold-windows-amd64.exe
```

**Comment by m1o1** [comment]
Oh yeah that might be the same issue. I tried to download that exe but got:
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: skaffold/build/latest/skaffold-windows-amd64.exe</Details></Error>
```
I tried `gsutil cp gs://skaffold/builds/latest/skaffold-windows-amd64 ./skaffold.exe` which got an exe but when running `skaffold run` I got: `parsing skaffold config: unknown api version: "skaffold/v2beta12"`

skaffold version (of the one I downloaded): 3a09ff2

**Comment by m1o1** [comment]
Hmm no luck with the latest (827139d):

`$workingDir/skaffold.yaml`:
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: myapp
requires:
- path: ./skaffold/infra.yaml
```

`$workingDir/skaffold/infra.yaml`:
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: nginx
deploy:
  helm:
    releases:
      - name: nginx
        namespace: nginx
        createNamespace: true
        chartPath: ingress-nginx/ingress-nginx
        remote: true
        setValues:
          controller.service.type: NodePort
```
