### ISSUE TITLE
`skaffold dev` cannot watch source code for non-multistage builds

### ISSUE THREAD

**Issue by jstrachan** [GoogleContainerTools/skaffold#546]
so we can't use multistage builds OOTB on Jenkins X as GKE's docker nodes are kinda old ;).

So when [demoing incremental development of go based apps](https://www.youtube.com/watch?v=uHe7R_iZSLU&feature=youtu.be&list=PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo) we have to use single stage `Dockerfile`s like this one: https://github.com/jenkins-x/draft-packs/blob/master/packs/go/Dockerfile which led to us [adding this hack script](https://github.com/jenkins-x-quickstarts/golang-http/blob/master/watch.sh) to workaround that `skaffold dev` cannot watch for source changes to `*.go` and then rebuild the binary then rebuild and deploy the docker image.

I wonder if we should add some kind of optional `compile` stage we could add into the `skaffold.yaml` so for folks using single-stage docker images we could get `skaffold dev` to watch, say, `*.go` (or whatever pattern/glob is configured), then on change, run some CLI, like `make / npm` and then a `skaffold run` using some profile?

Then `skaffold dev` could work for any project; however the `Dockerfile` works?

**Comment by dlorenc** [comment]
What are you thinking the `compile` stage would look like in the yaml itself?

**Comment by jstrachan** [comment]
something like...
```
apiVersion: skaffold/v1alpha2
kind: Config
compile:
- watch: 
  - *.go
  - *.html
  action: make
  args:
  - someTarget
build:
  tagPolicy:
  - imageName: foo
  local: {}
deploy:
  kubectl:
    manifests:
```
