### ISSUE TITLE
[1.20.0] Skaffold deploy command incorrectly replaces artifacts (docker images)

### ISSUE THREAD

**Issue by artemkoru** [GoogleContainerTools/skaffold#5463]
### Expected behavior

I have set the environment variable `SKAFFOLD_DEFAULT_REPO` to `cr.yandex/crpjbnso4f901c9oq7rp` and when I run the command: `skaffold deploy -i nginx-image -t sometag`, I expect to get the docker-image name `cr.yandex/crpjbnso4f901c9oq7rp/nginx-image:sometag` in my kubernetes resources.

It works fine in skaffold v1.17.2, but in v1.20.0 I have the problem described below.

### Actual behavior

In skaffold v1.20.0 I get the docker-image name: `nginx-image:sometag` (without docker-repo!) and getting the following error in the pod in kubernetes: `Failed to pull image "nginx-image:sometag": rpc error: code = Unknown desc = Error response from daemon: pull access denied for nginx-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

### Information

- Skaffold version: v1.20.0
- Operating system: macOS 11.2.1 (20D74)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: Deployment nginx-image
build:
  artifacts:
    - image: "nginx-image"
      context: .
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_IMAGE_TAG}}"
deploy:
  kubeContext: minikube
  helm:
    releases:
      - name: "test-nginx"
        chartPath: ./charts/web-app
        remote: false
        wait: true
        upgradeOnChange: true
        artifactOverrides:
          image.name: nginx-image
        valuesFiles:
          - helm.values.yaml
```

### Steps to reproduce the behavior

1. clone this repo `git@github.com:artemkoru/skaffold-deploy-bug-report.git`
2. execute the command `export DOCKER_IMAGE_TAG=sometag; \
export SKAFFOLD_DEFAULT_REPO=cr.yandex/crpjbnso4f901c9oq7rp; \
skaffold deploy -i nginx-image -t $DOCKER_IMAGE_TAG`
3. and watch...

### Additional info

In skaffold v1.17.2 all works as expected:

```
➜  skaffold version
v1.17.2
➜  skaffold-deploy-bug ./deploy.sh           
+ export DOCKER_IMAGE_TAG=sometag
+ DOCKER_IMAGE_TAG=sometag
+ export SKAFFOLD_DEFAULT_REPO=cr.yandex/crpjbnso4f901c9oq7rp
+ SKAFFOLD_DEFAULT_REPO=cr.yandex/crpjbnso4f901c9oq7rp
+ skaffold deploy -i nginx-image -t sometag
Tags used in deployment:
 - nginx-image -> cr.yandex/crpjbnso4f901c9oq7rp/nginx-image:sometag
Starting deploy...
Helm release test-nginx not installed. Installing...
NAME: test-nginx
LAST DEPLOYED: Fri Feb 26 10:38:42 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=test-nginx,app.kubernetes.io/instance=test-nginx" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:80
Waiting for deployments to stabilize...
 - default:deployment/test-nginx is ready.
Deployments stabilized in 1.9307442s
```

But in skaffold v1.20.0 I have this issue:
```
➜  skaffold version
v1.20.0
➜  skaffold-deploy-bug ./deploy.sh                      
+ export DOCKER_IMAGE_TAG=sometag
+ DOCKER_IMAGE_TAG=sometag
+ export SKAFFOLD_DEFAULT_REPO=cr.yandex/crpjbnso4f901c9oq7rp
+ SKAFFOLD_DEFAULT_REPO=cr.yandex/crpjbnso4f901c9oq7rp
+ skaffold deploy -i nginx-image -t sometag
Tags used in deployment:
 - nginx-image -> nginx-image:sometag
Starting deploy...
Helm release test-nginx not installed. Installing...
Error: timed out waiting for the condition
install: exit status 1
```

If I try run the command like this: `skaffold deploy -i cr.yandex/crpjbnso4f901c9oq7rp/nginx-image -t sometag` (added docker-repo), I have the same problem:

```
➜  skaffold version
v1.20.0
➜  skaffold-deploy-bug ./deploy.sh           
+ export DOCKER_IMAGE_TAG=sometag
+ DOCKER_IMAGE_TAG=sometag
+ export SKAFFOLD_DEFAULT_REPO=cr.yandex/crpjbnso4f901c9oq7rp
+ SKAFFOLD_DEFAULT_REPO=cr.yandex/crpjbnso4f901c9oq7rp
+ skaffold deploy -i cr.yandex/crpjbnso4f901c9oq7rp/nginx-image -t sometag
Tags used in deployment:
 - nginx-image -> nginx-image:sometag
 - cr.yandex/crpjbnso4f901c9oq7rp/nginx-image -> cr.yandex/crpjbnso4f901c9oq7rp/nginx-image:sometag
Starting deploy...
Helm release test-nginx not installed. Installing...
...
```
P.S. I have the same problem in skaffold 1.18.0 and 1.19.0

Thanks!
