### ISSUE TITLE
Templated Fields - image

### ISSUE THREAD

**Issue by fdruillennec** [GoogleContainerTools/skaffold#5469]
In the schema version v1, we were able to template the whole name of the artifact as:
```
build:
  tagPolicy:
    envTemplate:
       template: "{{.REGISTRY}}/{{.PATH}}/{{.IMAGE_NAME}}:{{.TAG}}"
```

In the schema version v2beta12, the template is only used for the docker tag.

Is there still a way to template the name of the artifact and not just the tag after ":" ?
