### ISSUE TITLE
Logs not tailing from spring boot & buildpack

### ISSUE THREAD

**Issue by piotrblasiak** [GoogleContainerTools/skaffold#5480]
### Expected behavior

The spring boot app should tail logs.

### Actual behavior

Logs do not get tailed.

### Information

- Skaffold version: v1.20.0
- Operating system: macOS 11.2.1 (Big Sur)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: backend
build:
  artifacts:
  - image: testimage
    buildpacks:
      builder: paketobuildpacks/builder:base
deploy:
  kubectl:
    manifests:
    - kubernetes/main.yaml

```

### Steps to reproduce the behavior

1. Clone https://github.com/piotrblasiak/skaffold-test
2. skaffold dev
