### ISSUE TITLE
Attempting to push to non-existing image results in panic

### ISSUE THREAD

**Issue by errordeveloper** [GoogleContainerTools/skaffold#551]
### Expected behavior

A meaningful error message

### Actual behavior

A panic.

### Information

- Skaffold version: f5422a69e4cbc8ff19f75dac8db36053454ed03a
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config

build:

  artifacts:
  - imageName: podinfo
    docker:
      dockerfilePath: ./Dockerfile.ci

deploy:

  kubectl: { manifests: [ deploy/skaffold/* ] }

profiles:

  - name: production

    build: 

      local: { skipPush: false }
      artifacts:
      - imageName: foo/podinfo
        docker:
          dockerfilePath: ./Dockerfile.ci

    deploy: {}
```

### Steps to reproduce the behavior

1. Create skaffold config similar to above and reference a non-existing image (e.g. `podinfo` or `foo/podinfo`)
2. Run `skaffold build`
