### ISSUE TITLE
panic with two artifacts with same name

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5518]
In fiddling with github.com/GoogleContainerTools/container-debug-support I managed to create a situation where Skaffold panic'd:
```  
Successfully built e449a4fefe93 
Successfully tagged nodejs12app:latest
panic: close of closed channel

goroutine 88 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.(*node).markComplete(...)
	/skaffold/pkg/skaffold/build/model.go:39
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.(*scheduler).build(0x14000708f00, 0x102500238, 0x140008ccbc0, 0x14000a8d4d0, 0x1, 0x0, 0x0)
	/skaffold/pkg/skaffold/build/scheduler.go:105 +0x3b8
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.(*scheduler).run.func1(0x0, 0x0)
	/skaffold/pkg/skaffold/build/scheduler.go:65 +0x48
golang.org/x/sync/errgroup.(*Group).Go.func1(0x1400034cbd0, 0x1400034cc30)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x60
```

I have a profile for running tests.  In the `skaffold.yaml` [I duplicated a JSONpatch stanza](https://github.com/GoogleContainerTools/container-debug-support/blob/duct-tape/skaffold.yaml#L63-L70) but failed to change the image name, so I ended up with:
```
      - op: add
        path: /build/artifacts/-
        value:
          image: nodejs12app
          context: integration/nodejsapp
          docker:
            buildArgs:
              NODEVERSION: 12.21.0
      - op: add
        path: /build/artifacts/-
        value:
          image: nodejs12app
          context: integration/nodejsapp
          docker:
            buildArgs:
              NODEVERSION: 14.16.0
```

Note the duplicate `nodejs12app` reference.

### Information

- Skaffold version: v1.20.0
- Operating system: darwin/arm64
- Installed via: Google Cloud SDK
- Contents of skaffold.yaml:
