### ISSUE TITLE
Skaffold errors on createNamespace

### ISSUE THREAD

**Issue by ralucas** [GoogleContainerTools/skaffold#5528]
### Expected behavior
Skaffold creates the namespace

### Actual behavior
Errors with the following:
```
parsing skaffold config: unable to parse config: yaml: unmarshal errors:
  line xx: field createNamespace not found in type v2beta7.HelmRelease
````

### Information

- Skaffold version: 1.20.0
- Operating system: MacOS
- Installed via: brew
- Helm version: 3.5.3
- Contents of skaffold.yaml:

```yaml
deploy:
  kubeContext: docker-desktop
  helm:
    releases:
      - name: fluentd
        chartPath: stable/fluentd-elasticsearch
        remote: true
        valuesFiles:
          - fluentd-values.yaml
        createNamespace: true
        namespace: logging
      - name: elasticsearch
        chartPath: stable/elasticsearch
        remote: true
        valuesFiles:
          - elasticsearch-values.yaml
        createNamespace: true
        namespace: logging
      - name: kibana
        chartPath: stable/kibana
        remote: true
        valuesFiles:
          - kibana-values.yaml
        createNamespace: true
        namespace: logging
```

### Steps to reproduce the behavior

1. `skaffold dev --port-forward`
