### ISSUE TITLE
Consider not adding Skaffold labels by default in `render`

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#5542]
With the addition of `skaffold apply`, we will be applying the `skaffold.dev/run-id` and `kubernetes.io/managed-by` labels by default when resources are actuated to the cluster, meaning they're not required in the hydrated manifests provided for functionality like status check to work.

These labels are added by default to all manifests rendered through `skaffold render`, but given that `skaffold apply` can consume `skaffold render`'s output and adds these labels, we might want to just default to not adding them in render to clean up the hydrated manifests we output. The labels themselves are an implementation detail for our status check and don't provide any value to users.

```
➜  (getting-started) skaffold render
apiVersion: v1
kind: Pod
metadata:
  labels: <-- these labels provide no value to users
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: bd0e8bf3-dc76-40c6-900c-dc2754eb883c
  name: getting-started
  namespace: default
spec:
  containers:
  - image: skaffold-example:99e5f4d45e86d2aa180ebb6d382015d43383fef1ed7efcfff1a61fd205421479
    name: getting-started


➜  (getting-started) skaffold render --add-skaffold-labels=false
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
  namespace: default
spec:
  containers:
  - image: skaffold-example:99e5f4d45e86d2aa180ebb6d382015d43383fef1ed7efcfff1a61fd205421479
    name: getting-started
```
