### ISSUE TITLE
[BUG] When used "kaniko build" + "helm deploy" we don't have to try use local docker credentials

### ISSUE THREAD

**Issue by netaskd** [GoogleContainerTools/skaffold#5571]
### Expected behavior
We have a pipeline that:
- do build/push a docker image with Kaniko (has own a dockercfg secret in a namespace)
- do pull/deploy an image with Helm (has own a dockercfg secret in the namespace)
So, no docker daemon on the local machine (developer machine) at all.
The problem is:
For now, we have to have ${HOME}/.docker/config.json with creds for `registry.example.com`, while it's actually not used in the pipeline. Otherwise a build down with `exiting dev mode because first build failed: getting image: GET https://registry.example.com/v2/dev-01/app/manifests/0.0.1: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:dev-01/frontend-renderer Type:repository]]`

Looks like a `getting image:` is not need in this case, because all requests to registry makes from containers that already have dockercfg.

### Actual behavior
```bash
...
time="2021-03-18T15:45:50Z" level=debug msg="build: cache key for command CMD [\"sh\", \"start.sh\"] 0772721f0f41abd80bfce47e7e69c8c0ee4de60e8fffe342c213f98e41db9794"
time="2021-03-18T15:45:50Z" level=debug msg="mapping stage idx 0 to digest sha256:4f60b3064364173cf16d95b04888f7586fbea288eab5b04f72f647046394c6a9"
time="2021-03-18T15:45:50Z" level=debug msg="mapping digest sha256:4f60b3064364173cf16d95b04888f7586fbea288eab5b04f72f647046394c6a9 to cachekey 0772721f0f41abd80bfce47e7e69c8c0ee4de60e8fffe342c213f98e41db9794"
exiting dev mode because first build failed: getting image: GET https://registry.example.com/v2/dev-01/app/manifests/0.0.1: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:dev-01/frontend-renderer Type:repository]]
time="2021-03-18T18:45:52+03:00" level=debug msg="exporting metrics"
time="2021-03-18T18:45:52+03:00" level=debug msg="metrics uploading complete in 612.091ms"
```
### Information

- Skaffold version: 1.20+
- Operating system: Windows10, Centos 7
- Installed via: binary
- Contents of skaffold.yaml:

```yaml
---
kind: Config
apiVersion: skaffold/v2beta12
metadata:
  name: example
profiles:
#...
- name: kaniko
  build:
    tagPolicy: *tagPolicy
    artifacts:
      - context: *context
        image: *image
        kaniko:
          buildArgs: *buildArgs
          snapshotMode: redo
          skipUnusedStages: true
          useNewRun: true
          whitelistVarRun: true
    cluster:
      namespace: *namespace
      serviceAccount: builder-kaniko
      pullSecretName: builder-kaniko-dockercfg # <------ here we set secret, that already have in the namespace
      pullSecretPath: config.json
      pullSecretMountPath: /kaniko/.docker
- name: deploy
  deploy:
    helm:
      releases:
      - name: app
        artifactOverrides:
          image: app
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        wait: false
        setValueTemplates:
          namespace: *namespace
          imagePullSecrets: deployer-helm-dockercfg # <------ here we set secret, that already have in the namespace
```

### Steps to reproduce the behavior

1. apply the yaml before and adjust apps arguments
2. skaffold dev -p kaniko
