### ISSUE TITLE
support for architechtures other than x86_64 on googleCloudBuild

### ISSUE THREAD

**Issue by j-windsor** [GoogleContainerTools/skaffold#5583]
Feature request!

Google Cloud Build support in Skaffold currently only supports building x86_64 images, but Cloud Build can support building cross arch images using `buildx`. [Here's an example](https://github.com/GoogleCloudPlatform/solutions-build-multi-architecture-images-tutorial/blob/master/terraform/cloud-build/build-docker-image-trigger.yaml) of a cloudbuild.yaml file doing this.

It would be great to add an `arch` field underneath `googleCloudBuild` in the skaffold.yaml. The field would default to the architecture of the current context.

**Comment by nkubala** [comment]
if `buildx` is supported through the official cloud builder Docker image, then this shouldn't be too difficult for us to support. we'll just need to construct a different set of build args for alternative architectures.

**Comment by renzodavid9** [comment]
Hi @j-windsor. With Skaffold v2 feature to do [Cross-platform and Multi-platform builds](https://skaffold.dev/docs/pipeline-stages/builders/#cross-platform-and-multi-platform-build-support), now you should be able to do a multi/cross platform build. An example of a `skaffold.yaml` file using this with `googleCloudBuild` looks like this:

```
apiVersion: skaffold/v4beta1
kind: Config
build:
  platforms: ["linux/arm64", "linux/amd64"]
  googleCloudBuild:
    projectId: your-gcp-project-id
  artifacts:
  - image: skaffold-example
...
```
This will generate a multiplatform image. Please let us know if this solves your request. Thanks!
