### ISSUE TITLE
[FR] Add `--tag` flag for `render` when using sha256 tagPolicy

### ISSUE THREAD

**Issue by halvards** [GoogleContainerTools/skaffold#5587]
### Expected behavior

I can set the image tag with `skaffold render`, similar to `run`, `build`, and more. E.g.:

```sh
skaffold render --tag v0.1.0
```

This allows me to add a tag to my image even when the `tagPolicy` is `sha256`.

### Actual behavior

`--tag` is not a supported flag for `skaffold render`. If the `tagPolicy` is set to `sha256`, the image tag will always be `latest`.

### Information

- Skaffold version: v1.21.0
- Operating system: macOS 11.2.3
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
  - image: skaffold-example
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - k8s-*
```
