### ISSUE TITLE
global default-repo is not respected

### ISSUE THREAD

**Issue by usr42** [GoogleContainerTools/skaffold#5588]
Since version `1.21.0` a globaly set default-repo is not respected anymore. This was still working with version `1.20.0`.

Steps to reproduce:
```
# set skaffold default-repo globally to example.com/skaffold
skaffold config set --global default-repo example.com/skaffold
# run skaffold run without --default-repo parameter
skaffold run
```

Maybe this is related to the PR https://github.com/GoogleContainerTools/skaffold/pull/5397

### Expected behavior

```
Using credentials from Docker config (/Users/foo/.docker/config.json) for example.com/skaffold/bar:v1.0-dirty
```

### Actual behavior

```
The credential helper (docker-credential-desktop) has nothing for server URL: registry-1.docker.io

Got output:

credentials not found in native keychain

The credential helper (docker-credential-desktop) has nothing for server URL: registry.hub.docker.com

Got output:

credentials not found in native keychain

Using credentials from Docker config (/Users/foo/.docker/config.json) for bar:v1.0-dirty
Using base image with digest: sha256:SHA256SUM
I/O error for image [registry-1.docker.io/library/bar]:
I/O error for image [registry-1.docker.io/library/bar]:
I/O error for image [registry-1.docker.io/library/bar]:
I/O error for image [registry-1.docker.io/library/bar]:
```

### Information

- Skaffold version: v1.21.0
- Operating system: macOS Catalina 10.15.7
- Installed via: brew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
  - image: bar
    context: .
    jib: {}
deploy:
  helm:
    releases:
    - name: bar
      chartPath: chart/bar
      valuesFiles:
      - values-skaffold.yaml
      artifactOverrides:
        imageOverride: bar
      packaged:
        version: 0.0.1-{{.USER}}
        appVersion: 0.0.1-{{.USER}}
  statusCheckDeadlineSeconds: 300
```

### Steps to reproduce the behavior

```
# set skaffold default-repo globally to example.com/skaffold
skaffold config set --global default-repo example.com/skaffold
# run skaffold run without --default-repo parameter
skaffold run
```
