### ISSUE TITLE
should be able to run `skaffold build` without creating a Kubernetes client

### ISSUE THREAD

**Issue by errordeveloper** [GoogleContainerTools/skaffold#559]
### Expected behavior

Build runs.

### Actual behavior

Build fails.

```
Error: getting skaffold config: getting k8s client: Error creating kubeConfig: invalid configuration: no configuration has been provided
```

### Information

- Skaffold version: 3246ef8e2028611460aaf911bd38781d9f19764b
- Operating system: macOS
- Contents of `skaffold.yaml`:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config

build:

  artifacts:
  - imageName: podinfo
    docker:
      dockerfilePath: ./Dockerfile.ci

deploy:

  kubectl: { manifests: [ deploy/skaffold/* ] }

profiles:

  - name: production

    build:

      local: { skipPush: false }
      artifacts:
      - imageName: quay.io/stefanprodan/podinfo
        docker:
          dockerfilePath: ./Dockerfile.ci

    deploy: {}
```

### Steps to reproduce the behavior

1. `mv ~/.kube ~/.kube-`
2. `skaffold build`
