### ISSUE TITLE
[windows] Multiconfig skaffold bug with `helm.setFiles`

### ISSUE THREAD

**Issue by ReneWerner87** [GoogleContainerTools/skaffold#5595]
### Actual behavior
In the multi configuration repository with linked skaffold.yaml's + helm an error is currently thrown under windows that a file used in helm.setFiles is not known because the slashes are missing.

### Expected behavior
It should work like under macOS/linux or if you go directly into the skaffold.yaml directory and let skaffold build the environment i.e. without errors and with the correct file path links.

Is currently only a problem under windows in combination with the multiconfig feature and (helm.setFiles)functionality
Currently don't know if it occurs with the values files as well, you could check this when solving the issue

### Information

- Skaffold version: 1.21.0
- Operating system: Windows

- Contents of skaffold.yaml:

this is the path:
https://github.com/ReneWerner87/skaffoldHelmMultiRepo/blob/master/repositories/firstService/skaffold.yaml#L34
```yaml
            setFiles:
              envFile: ".env.development"
```

### Steps to reproduce the behavior

1. checkout my example repository
https://github.com/ReneWerner87/skaffoldHelmMultiRepo

2. run in powershell
`skaffold run -p dev`

Screens with the working and not working operation systems:
Mac:
https://raw.githubusercontent.com/ReneWerner87/skaffoldHelmMultiRepo/master/macosWorking.png

Windows:
https://raw.githubusercontent.com/ReneWerner87/skaffoldHelmMultiRepo/master/windowsIssue.png

Example of the ERROR Message:
```shell
Error: failed parsing --set-file data: open C:UsersdeveloperDesktopreposgco.clusterrepositoriesgco-serviceconfigproduct.env: The system cannot find the file specified.
exiting dev mode because first deploy failed: install: exit status 1
```

**Comment by gsquared94** [comment]
I tried this on my Windows machine with skaffold-v1.21 but couldn't repro it:
```
PS C:\Users\gaura\code\skaffoldHelmMultiRepo> .\skaffold-windows-amd64.exe diagnose --yaml-only -p dev
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: first-service
build:
  artifacts:
  - image: golang/application
    context: C:\Users\gaura\code\skaffoldHelmMultiRepo\repositories\firstService
    docker:
      dockerfile: docker/Dockerfile-dev
  tagPolicy:
    gitCommit: {}
  local:
    push: false
    useBuildkit: true
    concurrency: 0
deploy:
  helm:
    releases:
    - name: first-service
      chartPath: C:\Users\gaura\code\skaffoldHelmMultiRepo\repositories\firstService\helm
      valuesFiles:
      - C:\Users\gaura\code\skaffoldHelmMultiRepo\repositories\firstService\helm\values.yaml
      - C:\Users\gaura\code\skaffoldHelmMultiRepo\repositories\firstService\helm\values-dev.yaml
      artifactOverrides:
        app.image: golang/application
      namespace: test
      setFiles:
        envFile: C:\Users\gaura\code\skaffoldHelmMultiRepo\repositories\firstService\.env.development
      createNamespace: true
      upgradeOnChange: true
  kubeContext: docker-desktop
  logs:
    prefix: container
---
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: gco.cluster
build:
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 1
deploy:
  kubeContext: docker-desktop
  logs:
    prefix: container
PS C:\Users\gaura\code\skaffoldHelmMultiRepo> 
```

you can see above that `envFile: C:\Users\gaura\code\skaffoldHelmMultiRepo\repositories\firstService\.env.development` is being resolved correctly.
