### ISSUE TITLE
No push access to specified image repository - Azure Container Registry

### ISSUE THREAD

**Issue by dgoldssfo** [GoogleContainerTools/skaffold#5601]
### Information

- Skaffold version: 1.21.0
- Operating system: macOS Big Sur
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
# For creating your own custom skaffold profiles we recommend making a copy of this
# file to skaffold-dev.yaml (which is in .gitignore).
# You can "mix and match" diferent services together by creating skaffold profiles
# and by creating a new kustomize profile in kustomize/overlay/
# The default below for skaffold dev is to deploy all services in one shot:
# Note: Upgrade to skaffold/v2alpha3 for skaffold 1.4
apiVersion: skaffold/v1
kind: Config

## Common YAML anchors
## The yaml anchors are used to make it easier to compose skaffold profiles.
## You should not need to edit this section
.YamlAnchors:

  artifactDefinitions:
    - &AM
      image: am
      context: docker/7.0/am
    - &AMSTER
      image: amster
      context: docker/7.0/amster
    - &IDM
      image: idm
      context: docker/7.0/idm
    - &DS-CTS_BASE
      image: ds-cts
      context: docker/7.0/ds
    - &DS-CTS
      <<: *DS-CTS_BASE
      docker:
        dockerfile: cts/Dockerfile
    - &DS-IDREPO_BASE
      image: ds-idrepo
      context: docker/7.0/ds/
    - &DS-IDREPO
      <<: *DS-IDREPO_BASE
      docker:
        dockerfile: idrepo/Dockerfile
    - &DS-PROXY_BASE
      image: ds-proxy
      context: docker/7.0/ds
    - &DS-PROXY
      <<: *DS-PROXY_BASE
      docker:
        dockerfile: proxy/Dockerfile
    - &LDIF-IMPORTER
      image: ldif-importer
      context: docker/7.0/ldif-importer
    - &IG
      image: ig
      context: docker/7.0/ig
    - &AM_CONFIG_UPGRADER
      image: am-config-upgrader
      context: docker/7.0/am-config-upgrader

  commonArtifactSets:
    default-artifacts: &default-artifacts
    - *AM
    - *AMSTER
    - *IDM
    - *DS-CTS
    - *DS-IDREPO
    - *DS-PROXY
    - *IG
    - *LDIF-IMPORTER

## End YAML Anchors

#---------------------
# Skaffold profiles
#---------------------

# Default profile
build: &default-build
  artifacts: *default-artifacts
  tagPolicy:
    sha256: {}
deploy: &default-deploy
  statusCheckDeadlineSeconds: 600
  kustomize:
    path: ./kustomize/overlay/7.0/all


# default.iam.forgeops.com
profiles:
- name: forgeops
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/forgeops

# Images tagged as environment variable in a dockerd or dockerd like environment
- name: docker-image-tag
  build:
    tagPolicy:
      envTemplate:
        template: "{{.IMAGE_TAG}}"
    artifacts: *default-artifacts
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/all


# CDM s/m/l profiles. (For cdm-mini, use default profile.)
- name: small
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/small
- name: medium
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/medium
- name: large
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/large
- name: dev
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/dev

# Platform deployment without default UI projects. UI to be installed separately, for development
- name: no-ui
  build: *default-build
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/noui

# Sample profiles to launch / test just a specific product
- name: ig-only
  build:
    artifacts:
    - *IG
    tagPolicy:
      sha256: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/ig-only

- name: am-only
  build:
    artifacts:
    - *AM
    - *AMSTER
    - *DS-CTS
    - *DS-IDREPO
    - *LDIF-IMPORTER
    tagPolicy:
      gitCommit:
        variant: AbbrevCommitSha
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/am-only

- name: idm-only
  build:
    artifacts:
    - *IDM
    - *DS-IDREPO
    tagPolicy:
      sha256: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/idm-only

- name: ds-only
  build:
    artifacts:
    - *DS-CTS
    - *DS-IDREPO
    tagPolicy:
      sha256: {}
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/ds-only

# Deploy only ds and secrets.
- name: persistence
  build:
    artifacts:
    - *DS-CTS
    - *DS-IDREPO
    - *LDIF-IMPORTER
    tagPolicy:
      gitCommit:
        variant: AbbrevCommitSha
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/persistence

# deploy only AM/IDM - for iterative testing
- name: am-idm-only
  build:
    artifacts:
    - *AM
    - *IDM
    - *AMSTER
    tagPolicy:
      gitCommit:
        variant: AbbrevCommitSha
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/am-idm-only

- name: amster-export
  build:
    artifacts:
    - *AMSTER
    tagPolicy:
      gitCommit:
        variant: AbbrevCommitSha
  deploy:
    kustomize:
      path: ./kustomize/overlay/7.0/amster-export

- name: amster-import
  build:
    artifacts:
    - *AMSTER
    tagPolicy:
      gitCommit:
        variant: AbbrevCommitSha
  deploy:
    kustomize:
      path: ./kustomize/base/amster

- name: config-upgrader
  build:
    artifacts:
      - *AM_CONFIG_UPGRADER
    tagPolicy:
      gitCommit:
        variant: AbbrevCommitSha
  deploy:
    kustomize:
      path: ./kustomize/base/am-config-upgrader

- name: fr-config-exporter
  build:
    artifacts:
      - *AM_CONFIG_UPGRADER
    tagPolicy:
      gitCommit:
        variant: AbbrevCommitSha
  deploy:
    kustomize:
      path: ./kustomize/dev/fr-config-exporter

```

### Steps to reproduce the behavior

1. az login
2. az acr login --name registry-name
3. skaffold config set default-repo my-container-registry.azurecr.io/cdm -k my-context
4. skaffold run --profile small
5. Reinstall Skaffold 1.20.0
6. /path/to/skaffold-1.20.0/skaffold run --profile small - works, is able to write to my ACR registry.
