### ISSUE TITLE
Use local environment variables as arguments to docker build

### ISSUE THREAD

**Issue by akawalsky** [GoogleContainerTools/skaffold#562]
I would like to be able to inject a local environment variable which is a secret as a build argument via skaffold. In my case, this is a password to access a shared private artifactory server in order to build a mvn project. This is trivial via command line, as I can just do: 
`docker build --build-arg artifactory_password=$ARTIFACTORY_PASSWORD -t NAME_OF_IMAGE .`

It would be great if skaffold had functionality to allow below:
```
build:
  artifacts:
  - imageName: my_image
    workspace: .
    docker:
      buildArgs:
        artifactory_password: $ARTIFACTORY_PASSWORD
```

This would allow me to safely share my skaffold config via source control, and would make adoption by other developers extremely trivial. Is this functionality currently supported? If not, am I thinking about this incorrectly?

Happy to contribute to the source if needed!
