### ISSUE TITLE
Microservices example has incorrect config

### ISSUE THREAD

**Issue by iandanforth-alation** [GoogleContainerTools/skaffold#5629]
### Expected behavior

After `skaffold dev` according to the docs this command should work

`curl $(minikube service leeroy-web --url)`

### Actual behavior

`Exiting due to SVC_NOT_FOUND: Service 'leeroy-web' was not found in 'default' namespace.`

### Information

- Skaffold version: 1.21.0
- Operating system: OSX 10.14.6
- Installed via: homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
    - image: leeroy-web
      context: leeroy-web
      requires:
        - image: base
          alias: BASE
    - image: leeroy-app
      context: leeroy-app
      requires:
        - image: base
          alias: BASE
    - image: base
      context: base
deploy:
  kubectl:
    manifests:
      - leeroy-web/kubernetes/*
      - leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
  - resourceType: deployment
    resourceName: leeroy-app
    port: http
    localPort: 9001
```

### Steps to reproduce the behavior

1. Clone skaffold and navigate to the examples/microservices dir
2. `skaffold dev`
3. `curl $(minikube service leeroy-web --url)`

### Cause

leeroy-web is not exposed as a service
