### ISSUE TITLE
Custom test dependencies are listed for every artifact

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5664]
In https://github.com/GoogleContainerTools/container-debug-support/pull/65 I'm trying to reorganize the `skaffold debug` helper images to use a Skaffold multi-config setup.  I have a custom test definition that specifies dependencies using a pattern:
```
test:
  - image: skaffold-debug-nodejs
    structureTests: [structure-tests-nodejs.yaml]
    custom:
      - command: "cd helper-image; go test ."
        dependencies:
          paths: ["helper-image/*.go", "helper-image/go.*"]
```

But my build is failing ([logs](https://api.travis-ci.org/v3/job/766487297/log.txt)):

```
Generating tags...
 - skaffold-debug-go -> skaffold-debug-go:be78dcf
 - skaffold-debug-netcore -> skaffold-debug-netcore:be78dcf
 - skaffold-debug-nodejs -> skaffold-debug-nodejs:be78dcf
 - skaffold-debug-python -> skaffold-debug-python:be78dcf
Checking cache...
 - skaffold-debug-go: Error checking cache.
getting hash for artifact "skaffold-debug-go": getting dependencies for "skaffold-debug-go": pattern "/home/travis/build/GoogleContainerTools/container-debug-support/nodejs/helper-image/*.go" did not match any file
```

It's unexpected to see that the `skaffold-debug-go` image is pulling in dependencies from the `skaffold-debug-nodejs` artifact as they should be completely independent.  It turns out that our dependency lister returns *all* test dependencies for each artifact:
https://github.com/GoogleContainerTools/skaffold/blob/f280aa8325283a0f080989acef120c5597ebc4b7/pkg/skaffold/runner/new.go#L88-L94

As a result, a change to a test dependency will cause all images to be re-evaluated, instead of just the specific image (`skaffold-debug-nodejs` in this case).

### Steps to reproduce the behavior

1. Clone https://github.com/briandealwis/container-debug-support/tree/modules at commit https://github.com/briandealwis/container-debug-support/commit/91c712b77b6a44b0ff9bc5d4c4a2b664f78da423
2. `skaffold build`
