### ISSUE TITLE
Custom test fails in multi-config as working directory is top-level directory

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5666]
In https://github.com/GoogleContainerTools/container-debug-support/pull/65 I'm trying to reorganize the `skaffold debug` helper images to use a Skaffold multi-config setup.  

    .
    ├── nodejs/
    │   └── helper-image/
    └── go/
        └── helper-image/
 
I have a custom test definition in a child `nodejs/skaffold.yaml` that specifies dependencies using a pattern:
```
test:
  - image: skaffold-debug-nodejs
    structureTests: [structure-tests-nodejs.yaml]
    custom:
      - command: "cd helper-image; go test ."
        #dependencies:
        #  paths: ["helper-image/*.go", "helper-image/go.*"]
```

### Expected behavior

`skaffold test` from the top-level directory should succeed.

### Actual behavior

`skaffold test` fails as the custom test is run relative to the top-level directory rather than the directory in which the skaffold.yaml was defined.

```
...
Running custom test command: "cd helper-image; go test ."
sh: line 0: cd: helper-image: No such file or directory
package .: no Go files in /Users/bdealwis/Projects/Skaffold/repo-sk4j
Command finished with non-0 exit code.
running tests: command cd helper-image; go test . finished with non-0 exit code: exit status 1. Check the custom command contents: "cd helper-image; go test .".
```

### Steps to repeat

1. Clone https://github.com/briandealwis/container-debug-support/tree/modules at commit https://github.com/briandealwis/container-debug-support/commit/91c712b77b6a44b0ff9bc5d4c4a2b664f78da423
2. `skaffold test`

----

Perhaps we should define a field for working-directory on the custom test.
