### ISSUE TITLE
`skaffold render` does not respect templating `deploy.helm.releases.name`

### ISSUE THREAD

**Issue by netaskd** [GoogleContainerTools/skaffold#5671]
### Actual behavior

In the doc (https://skaffold.dev/docs/environment/templating/):
```
List of fields that support templating:

build.artifacts.[].docker.buildArgs (see builders)
build.tagPolicy.envTemplate.template (see envTemplate tagger)
deploy.helm.releases.setValueTemplates (see Deploying with helm)
deploy.helm.releases.name (see Deploying with helm)    <-----------------------------------------------
deploy.helm.releases.namespace (see Deploying with helm)
deploy.kubectl.defaultNamespace
deploy.kustomize.defaultNamespace
```

My skaffold.yaml contains:
```
profiles:
- name: deploy
  deploy:
    helm:
      releases:
      - name: "app-{{.PROJECT_VERSION}}"
        artifactOverrides:
          image: app
...
```
where `PROJECT_VERSION` is "0.0.1" (sourced from `dev-env` file to the current shell env)

So, when I run `skaffold render` it does not fill variable and shows it as is in the `skaffold.yaml`. For example, `ConfigMap` contains:
```
$ skaffold render
---
# Source: app/templates/configmap/env.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-{{.PROJECT_VERSION}}-env
  namespace: dev-01
data:
...
```
This behavior affects all points where I use `{{ .Release.Name }}` in helm chart. Source `ConfigMap` looks like this:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-env
  namespace: {{ .Values.stand }}
data:
...
```

### Information
- Skaffold version: 1.21
- Operating system: Centos7
- Installed via:  skaffold.dev
