### ISSUE TITLE
Unable to use modules with common base image artifact dependencies

### ISSUE THREAD

**Issue by viglesiasce** [GoogleContainerTools/skaffold#5683]
### Expected behavior

Use a single base image (as per [this example](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/simple-artifact-dependency)) between two modules and have a requires between one module and the other.

In this case I have a frontend and backend that share mostly the same build environment so I have a base Dockerfile shared between them. 

### Actual behavior

`skaffold build` throws an error due to duplicate artifacts:

```shell
❯ skaffold build
invalid skaffold config: found duplicate images "base": artifact image names must be unique across all configurations
```

### Information

- Skaffold version: `v1.21.0`
- Operating system: MacOS arm64
- Installed via: Cloud Code
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: frontend
requires:
  - path: ../backend
build:
  artifacts:
  - image: base
    context: ../../base
  - image: sample-app-frontend-dev
    requires:
      - alias: BASE
        image: base
deploy:
  kustomize:
    paths:
    - k8s/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/prod
---
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: backend
build:
  artifacts:
  - image: base
    context: ../../base
  - image: sample-app-backend-dev
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - k8s/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/prod

```

### Steps to reproduce the behavior

1. Branch with setup available here: 
https://github.com/viglesiasce/sample-app/tree/base-pattern

**Comment by gsquared94** [comment]
how about:

```yaml
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: base
build:
  artifacts:
  - image: base
    context: ../../base
---
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: frontend
requires:
  - configs: [base, backend]
build:
  artifacts:
  - image: sample-app-frontend-dev
    requires:
      - alias: BASE
        image: base
deploy:
  kustomize:
    paths:
    - k8s/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/prod
---
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: backend
requires:
  - configs: [base]
build:
  artifacts:
  - image: sample-app-backend-dev
    docker:
      dockerfile: Dockerfile
    requires:
    - alias: BASE
      image: base
deploy:
  kustomize:
    paths:
    - k8s/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/prod
```

The issue you're facing is that the artifact `image` property needs to be unique across. Also to declare a reusable `base` artifact it needs to be a _single_ artifact.
