### ISSUE TITLE
Set user port-foward context differently to deploy context

### ISSUE THREAD

**Issue by ollieayre-oc** [GoogleContainerTools/skaffold#5687]
Hi,

I raised this before in #2646 but it got closed without a successful resolution and i wasn't able to re-open it so i'm happy for this to closed if the previous one can be re-opened.

There's a full description of the problem with examples in #2646 but to give a short summary again:
I'm trying to understand if it's possible when using the dev command to deploy a service to a local context (docker-desktop) but also have skaffold maintain a port-forward to a database pod running on a different remote context for use by the service under development. It was suggested that i could use profiles or config dependencies however throughout my experimentation i have not been able to get a working result with either approach using the latest versions of skaffold.

Any help would be much appreciated.

**Comment by gsquared94** [comment]
The suggestions made in #2646 around using profiles is something like launching two separate `skaffold` processes with `skaffold dev -p context1` and `skaffold dev -p context2` where `context1` and `context2` are profiles overriding the `kubecontext` property in `skaffold.yaml`
```yaml
apiVersion: skaffold/v2beta14
kind: Config
build:
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
  kubeContext: context
profiles:
  - name: context1
    patches:
      - op: replace
        path: /deploy/kubeContext
        value: context1
  - name: context2
    patches:
      - op: replace
        path: /deploy/kubeContext
        value: context2
```

However I'm not sure if that would solve your problem since you probably want the service deployed in one cluster to be able to communicate with services in the other. Skaffold currently can't do that. Have you looked at [telepresence](https://blog.getambassador.io/super-fast-inner-development-loops-for-kubernetes-with-skaffold-and-telepresence-1cd3e42ba665), that seems to be related to what you want to do
