### ISSUE TITLE
Skaffold test should be run with the Docker socket of minikube when available.

### ISSUE THREAD

**Issue by viglesiasce** [GoogleContainerTools/skaffold#5696]
### Expected behavior
When a user has minikube, we do some trickery to ensure that their images are built with minikube's docker daemon by using the values from `minikube docker-env`. We should do the same when running custom command tests as it will be common for images from the build phase to be used for testing.

### Actual behavior
The hosts docker socket is used for any docker run commands in a custom test causing dependent images to be missing.

### Information

- Skaffold version:  v1.21.0
- Operating system: MacOS arm64
- Installed via: Cloud Code
- Contents of skaffold.yaml:

```yaml
  
apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
    - image: test-image
      context: .
      docker:
        dockerfile: hack/test-image/Dockerfile
test:
  # Unit tests, remotely vis Cloud Build
  - image: sample-app-backend-dev
    custom:
    - command: docker run $IMAGE go test
  - image: test-image
    custom:
    - command: docker run $IMAGE ./hack/validate.sh
```

### Steps to reproduce the behavior

1. Clone https://github.com/viglesiasce/sample-app/tree/base-pattern
2. `minikube start`
3. `skaffold dev`
4. Tests will fail because they cant find the images
