### ISSUE TITLE
skaffold diagnose breaks when minikube is paused and docker is force quit

### ISSUE THREAD

**Issue by ChaseMor** [GoogleContainerTools/skaffold#5701]
### Steps to reproduce the behavior

1. Start a minikube cluster
2. Set the cluster as the active context
3. Pause the cluster
4. Force quit Docker (The minikube cluster should then stop)
5. run `skaffold diagnose`
6. Get one of 2 minikube errors

```
invalid skaffold config: getting minikube env: running [/usr/local/bin/minikube docker-env --shell none -p minikube]
 - stdout: "\n\n"
 - stderr: "X Exiting due to GUEST_STATUS: state: unknown state \"minikube\": docker container inspect minikube --format=: exit status 1\nstdout:\n\n\nstderr:\nError response from daemon: dial unix docker.raw.sock: connect: connection refused\n\n* \n* If the above advice does not help, please let us know: \n  - https://github.com/kubernetes/minikube/issues/new/choose\n"
 - cause: exit status 80
```
```
invalid skaffold config: getting minikube env: running [/usr/local/bin/minikube docker-env --shell none -p cloud-code-minikube]
 - stdout: "* There is no local cluster named \"cloud-code-minikube\"\n  - To fix this, run: \"minikube start -p cloud-code-minikube\"\n"
 - stderr: ""
 - cause: exit status 85
```

### Expected behavior

`skaffold diagnose` shouldn't say that the config is invalid and should output the config

### Actual behavior

Command errors out when analyzing the valid config saying it is invalid. Should behave just as it would if minikube was stopped normally and correctly analyze the config.

### Information

- Skaffold version: v1.21.0
- Operating system: Mac version 11.2.1
- Installed via: Cloud Code
- Contents of skaffold.yaml:

```yaml
# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta4
kind: Config
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
# use the dockerfile profile to build images using Docker instead of Jib
- name: dockerfile
  build:
    artifacts:
      - image: java-hello-world
- name: jib
  build:
    tagPolicy:
      sha256: {}
    # defines where to find the code at build time and where to push the resulting image
    artifacts:
      - image: java-hello-world
        # To learn more about how Jib builds Java containers visit
        # https://github.com/GoogleContainerTools/jib
        jib:
          args:
          - -Dmaven.test.skip=true
```

#### Notes
Was working on implementing `skaffold diagnose` into Cloud Code for VS Code when the command kept erroring out. Is likely a minikube bug that is being propagated into skaffold.

**Comment by MarlonGamez** [comment]
hi @ChaseMor , is `skaffold diagnose` being called with the `--minikube-profile` flag here?

**Comment by ChaseMor** [comment]
@MarlonGamez No it wasn't.

**Comment by MarlonGamez** [comment]
@ChaseMor ah, okay, would you be able to reproduce this and run skaffold with -v=debug? I'm trying to pin the code path down and I think I have it, but the output will help for sure

**Comment by ChaseMor** [comment]
@MarlonGamez 
<details>
<summary>Here's the output from the first error. I was able to consistently reproduce this by running the command while docker was in the process of stopping or starting.</summary>

```
INFO[0000] Skaffold &{Version:v1.21.0 ConfigVersion:skaffold/v2beta13 GitVersion: GitCommit:4830337932d53185445812d29f078667b3b74fa5 BuildDate:2021-03-19T01:50:34Z GoVersion:go1.14.14 Compiler:gc Platform:darwin/amd64} 
DEBU[0000] Disable housekeeping messages for command explicitly 
DEBU[0000] config version out of date: upgrading to latest "skaffold/v2beta13" 
DEBU[0000] parsed 1 configs from configuration file /Users/chasemor/Downloads/hello-world-21/skaffold.yaml 
DEBU[0000] Defaulting build type to local build         
INFO[0000] Using kubectl context: minikube              
INFO[0000] Loaded Skaffold defaults from "/Users/chasemor/.skaffold/config" 
DEBU[0000] Running command: [/usr/local/bin/minikube docker-env --shell none -p minikube] 
invalid skaffold config: getting minikube env: running [/usr/local/bin/minikube docker-env --shell none -p minikube]
 - stdout: "\n\n"
 - stderr: "X Exiting due to GUEST_STATUS: state: unknown state \"minikube\": docker container inspect minikube --format=: exit status 1\nstdout:\n\n\nstderr:\nError response from daemon: dial unix docker.raw.sock: connect: connection refused\n\n* \n* If the above advice does not help, please let us know: \n  - https://github.com/kubernetes/minikube/issues/new/choose\n"
 - cause: exit status 80
```

</details>

I did also notice that the minikube binary that this is using is not the one in the Cloud Code dependencies folder that I meant to use, but rather the global one. Upon inspection, that binaries version was v1.13.1 which is much older than the version of skaffold being used. So it might be possible that it's trying to load the configuration of a minikube cluster that has newer properties than what were in v1.13.1 since all the cluster management is done with Cloud Code with v1.18.1

<details>
<summary>When looking at the output while doing this in entirely in Cloud Code (the scenario that prompted the investigation, but the previous command outputs were all from running skaffold via the command line), I got this output.</summary>

```
time="2021-04-26T16:44:34-07:00" level=info msg="applying profile: someProfile"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field Build"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field artifacts"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field insecureRegistries"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field tagPolicy"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field BuildType"
time="2021-04-26T16:44:34-07:00" level=info msg="no values found in profile for field BuildType, using original config values"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field Test"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field Deploy"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field DeployType"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field helm"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field kpt"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field kubectl"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field kustomize"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field statusCheckDeadlineSeconds"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field kubeContext"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field logs"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field prefix"
time="2021-04-26T16:44:34-07:00" level=debug msg="overlaying profile on config for field PortForward"
time="2021-04-26T16:44:34-07:00" level=debug msg="Defaulting build type to local build"
time="2021-04-26T16:44:34-07:00" level=info msg="Using kubectl context: minikube"
time="2021-04-26T16:44:34-07:00" level=info msg="Loaded Skaffold defaults from \"/Users/chasemor/.skaffold/config\""
time="2021-04-26T16:44:34-07:00" level=debug msg="Running command: [/Users/chasemor/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/minikube docker-env --shell none -p minikube]"
invalid skaffold config: getting minikube env: running [/Users/chasemor/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/minikube docker-env --shell none -p minikube]
 - stdout: "false exit code 89\n"
 - stderr: ""
 - cause: exit status 89
'skaffold diagnose --yaml-only --filename /Users/chasemor/Downloads/hello-world-21/skaffold.yaml --profile someProfile -v=debug' exited with code 1 took 529ms (managed)
```
</details>

This case does seem to use the correct minikube binary.

**Comment by tejal29** [comment]
On master, I was able to verify:
 
1) `skaffold diagnose --yaml-only` does not run `minikube docker env`
2) we do run a couple of minikube command but they are not affected by paused state of minikube cluster.
```
➜  profiles git:(fix_diagnose) minikube pause                                   
⏸️  Pausing node minikube ... 
⏯️  Paused 0 containers in: kube-system, kubernetes-dashboard, storage-gluster, istio-operator
➜  profiles git:(fix_diagnose) ../../out/skaffold  diagnose  --yaml-only
apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
  - image: skaffold-world
    context: world-service
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 1
deploy:
  kubectl:
    manifests:
    - world-service/*.yaml
  logs:
    prefix: container
➜  profiles git:(fix_diagnose) 
```

The debug output confirms, we don't run `minikube docker env` in yaml-only
<details>

```
../../out/skaffold  diagnose --yaml-only -v=debug
INFO[0000] Skaffold &{Version:v1.21.0-83-g789d0581f ConfigVersion:skaffold/v2beta16 GitVersion: GitCommit:789d0581f6415de2ef2cc9a68fe27201fe252a48 BuildDate:2021-04-29T15:46:44Z GoVersion:go1.16.3 Compiler:gc Platform:darwin/amd64} 
DEBU[0000] Disable housekeeping messages for command explicitly 
DEBU[0000] config version out of date: upgrading to latest "skaffold/v2beta16" 
DEBU[0000] parsed 1 configs from configuration file /Users/tejaldesai/workspace/skaffold/examples/getting-started/skaffold.yaml 
DEBU[0000] Defaulting build type to local build         
INFO[0000] Using kubectl context: gke_tejal-gke1_us-central1-c_dump 
INFO[0000] Loaded Skaffold defaults from "/Users/tejaldesai/.skaffold/config" 
DEBU[0000] Running command: [minikube version --output=json] 
DEBU[0000] Command output: [{"commit":"ec61815d60f66a6e4f6353030a40b12362557caa-dirty","minikubeVersion":"v1.18.0"}
] 
DEBU[0000] Running command: [/usr/local/bin/minikube profile list -o json --user=skaffold] 
DEBU[0001] Command output: [{"invalid":[],"valid":[{"Name":"minikube","Status":"Running","Config":{"Name":"minikube","KeepContext":false,"EmbedCerts":false,"MinikubeISO":"","KicBaseImage":"gcr.io/k8s-minikube/kicbase:v0.0.18@sha256:ddd0c02d289e3a6fb4bba9a94435840666f4eb81484ff3e707b69c1c484aa45e","Memory":8100,"CPUs":2,"DiskSize":20000,"VMDriver":"","Driver":"docker","HyperkitVpnKitSock":"","HyperkitVSockPorts":[],"DockerEnv":null,"ContainerVolumeMounts":null,"InsecureRegistry":null,"RegistryMirror":null,"HostOnlyCIDR":"192.168.99.1/24","HypervVirtualSwitch":"","HypervUseExternalSwitch":false,"HypervExternalAdapter":"","KVMNetwork":"default","KVMQemuURI":"qemu:///system","KVMGPU":false,"KVMHidden":false,"DockerOpt":null,"DisableDriverMounts":false,"NFSShare":[],"NFSSharesRoot":"/nfsshares","UUID":"","NoVTXCheck":false,"DNSProxy":false,"HostDNSResolver":true,"HostOnlyNicType":"virtio","NatNicType":"virtio","SSHIPAddress":"","SSHUser":"root","SSHKey":"","SSHPort":22,"KubernetesConfig":{"KubernetesVersion":"v1.20.2","ClusterName":"minikube","Namespace":"default","APIServerName":"minikubeCA","APIServerNames":null,"APIServerIPs":null,"DNSDomain":"cluster.local","ContainerRuntime":"docker","CRISocket":"","NetworkPlugin":"","FeatureGates":"","ServiceCIDR":"10.96.0.0/12","ImageRepository":"","LoadBalancerStartIP":"","LoadBalancerEndIP":"","CustomIngressCert":"","ExtraOptions":null,"ShouldLoadCachedImages":true,"EnableDefaultCNI":false,"CNI":"","NodeIP":"","NodePort":8443,"NodeName":""},"Nodes":[{"Name":"","IP":"192.168.49.2","Port":8443,"KubernetesVersion":"v1.20.2","ControlPlane":true,"Worker":true}],"Addons":null,"VerifyComponents":{"apiserver":true,"system_pods":true},"StartHostTimeout":360000000000,"ScheduledStop":null,"ExposedPorts":[],"Network":"","MultiNodeRequested":false}}]}] 
DEBU[0001] Running command: [/usr/local/bin/minikube profile list -o json --user=skaffold] 
DEBU[0001] Command output: [{"invalid":[],"valid":[{"Name":"minikube","Status":"Running","Config":{"Name":"minikube","KeepContext":false,"EmbedCerts":false,"MinikubeISO":"","KicBaseImage":"gcr.io/k8s-minikube/kicbase:v0.0.18@sha256:ddd0c02d289e3a6fb4bba9a94435840666f4eb81484ff3e707b69c1c484aa45e","Memory":8100,"CPUs":2,"DiskSize":20000,"VMDriver":"","Driver":"docker","HyperkitVpnKitSock":"","HyperkitVSockPorts":[],"DockerEnv":null,"ContainerVolumeMounts":null,"InsecureRegistry":null,"RegistryMirror":null,"HostOnlyCIDR":"192.168.99.1/24","HypervVirtualSwitch":"","HypervUseExternalSwitch":false,"HypervExternalAdapter":"","KVMNetwork":"default","KVMQemuURI":"qemu:///system","KVMGPU":false,"KVMHidden":false,"DockerOpt":null,"DisableDriverMounts":false,"NFSShare":[],"NFSSharesRoot":"/nfsshares","UUID":"","NoVTXCheck":false,"DNSProxy":false,"HostDNSResolver":true,"HostOnlyNicType":"virtio","NatNicType":"virtio","SSHIPAddress":"","SSHUser":"root","SSHKey":"","SSHPort":22,"KubernetesConfig":{"KubernetesVersion":"v1.20.2","ClusterName":"minikube","Namespace":"default","APIServerName":"minikubeCA","APIServerNames":null,"APIServerIPs":null,"DNSDomain":"cluster.local","ContainerRuntime":"docker","CRISocket":"","NetworkPlugin":"","FeatureGates":"","ServiceCIDR":"10.96.0.0/12","ImageRepository":"","LoadBalancerStartIP":"","LoadBalancerEndIP":"","CustomIngressCert":"","ExtraOptions":null,"ShouldLoadCachedImages":true,"EnableDefaultCNI":false,"CNI":"","NodeIP":"","NodePort":8443,"NodeName":""},"Nodes":[{"Name":"","IP":"192.168.49.2","Port":8443,"KubernetesVersion":"v1.20.2","ControlPlane":true,"Worker":true}],"Addons":null,"VerifyComponents":{"apiserver":true,"system_pods":true},"StartHostTimeout":360000000000,"ScheduledStop":null,"ExposedPorts":[],"Network":"","MultiNodeRequested":false}}]}] 
DEBU[0001] setting Docker user agent to skaffold-v1.21.0-83-g789d0581f 
apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
  - image: skaffold-example
    context: .
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 1
deploy:
  kubectl:
    manifests:
    - k8s-*
  logs:
    prefix: container

```
</details>
