### ISSUE TITLE
Skaffold incompatible with multi-node minikube clusters

### ISSUE THREAD

**Issue by aasmall** [GoogleContainerTools/skaffold#5702]
1) create a multi-node minikube cluster
```bash
minikube start --vm-driver=kvm2 --cpus=2 --nodes 3 \
--addons registry --insecure-registry "10.0.0.0/24" --insecure-registry "192.168.39.0/24" 
```
2) use kaniko builder, to remove docker dependency

```yaml
#skaffold.yaml

apiVersion:  skaffold/v2beta14
kind: Config
metadata:
  name: dicemagic
build:
  cluster: {}
  insecureRegistries: 
  - "192.168.39.0/24"
  - "10.0.0.0/24"
  artifacts:
  - image: registry.gitlab.com/dicemagic/dicemagic/chat-clients
    kaniko:
      dockerfile: dockerfiles/chat-clients.dockerfile
      insecure: true
deploy:
  kubeContext: minikube
  kustomize:
    paths:
    - config/minikube
```
2) start skaffold
```bash
skaffold dev --default-repo $(minikube ip):5000
```

### Expected behavior
```
Listing files to watch...
etc.
```

### Actual behavior

```
WARN[0000] Could not get minikube docker env, falling back to local docker daemon: getting minikube env: running [/usr/local/bin/minikube docker-env --shell none -p minikube]
 - stdout: "false exit code 81\n"
 - stderr: "X Exiting due to ENV_MULTINODE_CONFLICT: The docker-env command is incompatible with multi-node clusters. Use the 'registry' add-on: https://minikube.sigs.k8s.io/docs/handbook/registry/\n"
 - cause: exit status 81 
```

### Information

- Skaffold version: v1.22.0-2-ge947844e5-dirty (I only made one change, I promise)
- Operating system: Linux 5.10.26-1-MANJARO
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion:  skaffold/v2beta14
kind: Config
metadata:
  name: dicemagic
build:
  cluster: {}
  insecureRegistries: 
  - "192.168.39.0/24"
  - "10.0.0.0/24"
  artifacts:
  - image: registry.gitlab.com/dicemagic/dicemagic/chat-clients
    kaniko:
      dockerfile: dockerfiles/chat-clients.dockerfile
      insecure: true
  - image: registry.gitlab.com/dicemagic/dicemagic/dice-server
    kaniko:
      dockerfile: dockerfiles/dice-server.dockerfile
      insecure: true
  - image: registry.gitlab.com/dicemagic/dicemagic/www
    kaniko:
      dockerfile: dockerfiles/www.dockerfile
      insecure: true
  - image: registry.gitlab.com/dicemagic/dicemagic/mock-datastore
    kaniko:
      dockerfile: dockerfiles/mock-datastore.dockerfile
      insecure: true
  - image: registry.gitlab.com/dicemagic/dicemagic/mock-kms
    kaniko:
      dockerfile: dockerfiles/mock-kms.dockerfile
      insecure: true
  - image: registry.gitlab.com/dicemagic/dicemagic/mock-slack-server
    kaniko:
      dockerfile: dockerfiles/mock-slack-server.dockerfile
      insecure: true
deploy:
  kubeContext: minikube
  kustomize:
    paths:
    - config/minikube
```

### Steps to reproduce the behavior

I haven't pushed my commit which reproduces this yet, local only. If you have trouble reproducing let me know.

## How I fixed it locally

1) cloned at e947844e558b9181911906399cb5e3df7fdb28ef

2) edited line 114 of pkg/skaffold/docker/client.go from:
```go
if errors.As(err, &exitError) && (exitError.ExitCode() == minikubeDriverConfictExitCode || exitError.ExitCode() == oldMinikubeBadUsageExitCode) {
```
to
```go
if errors.As(err, &exitError) && (exitError.ExitCode() == minikubeDriverConfictExitCode || exitError.ExitCode() == oldMinikubeBadUsageExitCode || exitError.ExitCode() == 81) {
```
### Why this isn't a pull request

Because I believe this should key off the --detect-minikube CLI flag, and I don't know how you'd want to plumb that all the way down. Also, I don't know your code base well enough to try.

**Comment by briandealwis** [comment]
I'll address this as part of #4347.  You could also set `build.local.push = true` so that Skaffold would always push images.

Duplicate of #5494

**Comment by aasmall** [comment]
Sorry for the dupe, GitHub search failed me. In response to your suggested work around, I'm afraid that doesn't work with the kaniko builder

```bash
To use the 'kaniko' builder, add the 'cluster' stanza to the 'build' section of your configuration. For information, see https://skaffold.dev/docs/pipeline-stages/builders/ | found a 'kaniko' artifact, which is incompatible with the 'local' builder:
```

and if I switch to the docker builder, it still doesn't work:
```yaml
apiVersion:  skaffold/v2beta14
kind: Config
metadata:
  name: dicemagic
build:
  local:
    push: true
  insecureRegistries: 
  - "192.168.39.0/24"
  - "10.0.0.0/24"
  artifacts:
  - image: registry.gitlab.com/dicemagic/dicemagic/chat-clients
    docker:
      dockerfile: dockerfiles/chat-clients.dockerfile
  - image: registry.gitlab.com/dicemagic/dicemagic/dice-server
    docker:
      dockerfile: dockerfiles/dice-server.dockerfile
  - image: registry.gitlab.com/dicemagic/dicemagic/www
    docker:
      dockerfile: dockerfiles/www.dockerfile
  - image: registry.gitlab.com/dicemagic/dicemagic/mock-datastore
    docker:
      dockerfile: dockerfiles/mock-datastore.dockerfile
  - image: registry.gitlab.com/dicemagic/dicemagic/mock-kms
    docker:
      dockerfile: dockerfiles/mock-kms.dockerfile
  - image: registry.gitlab.com/dicemagic/dicemagic/mock-slack-server
    docker:
      dockerfile: dockerfiles/mock-slack-server.dockerfile
deploy:
  kubeContext: minikube
  kustomize:
    paths:
    - config/minikube
```
```bash
WARN[0000] Could not get minikube docker env, falling back to local docker daemon: getting minikube env: running [/usr/local/bin/minikube docker-env --shell none -p minikube]
 - stdout: "false exit code 81\n"
 - stderr: "X Exiting due to ENV_MULTINODE_CONFLICT: The docker-env command is incompatible with multi-node clusters. Use the 'registry' add-on: https://minikube.sigs.k8s.io/docs/handbook/registry/\n"
 - cause: exit status 81 
```
