### ISSUE TITLE
Config Imports Should be default pass through the current profile(s)

### ISSUE THREAD

**Issue by dhodun** [GoogleContainerTools/skaffold#5707]
By default Importing a config (I think) is just running the default profile unless otherwise specified. We have multiple nestings of skaffold.yaml configs (for microservices and groups of microservices) and were expecting that profiles were inherited on the way down.

We would much prefer and expect that skaffold applies the current profile(s) unless otherwise specified.

Our root skaffold.yaml has gotten pretty messy, and is 50% profile activation code. We ultimately fixed with yaml anchors. But when we add a profile, we basically have to track down every single 'requires' section in all our skaffold yamls (not just root) to make sure we add the appropriate profiles.

This would be breaking change for anyone importing a config and just using the default profile (not many use cases for this I'm thinking?)

```yaml
# Master Skaffold
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: backends
requires:
- path: ./microservices/authentication
  configs: [authentication]
  activeProfiles:
  - name: custom
    activatedBy: [custom]
  - name: dev
    activatedBy: [dev]

- path: ./common
  configs: [common]
  activeProfiles: 
  - name: custom
    activatedBy: [custom] 
  - name: dev
    activatedBy: [dev] 

- path: ./microservices/dashboard
  configs: [dashboard]
  activeProfiles:
  - name: custom
    activatedBy: [custom]
  - name: dev
    activatedBy: [dev]

- path: ./microservices/messages
  configs: [messages]
  activeProfiles:
  - name: custom
    activatedBy: [custom]
  - name: dev
    activatedBy: [dev]
```
