### ISSUE TITLE
Unable to use environment variable for helm release version

### ISSUE THREAD

**Issue by derek126** [GoogleContainerTools/skaffold#5709]
### Expected behavior

To be able to use an environment variable for helm->releases->version

### Actual behavior

Environment variable for helm->releases->version is not substituted.

### Information

- Skaffold version: 1.22.0
- Operating system: Windows 10
- Installed via: chocolatey
- Contents of skaffold.yaml:

**NOTE: Using a remote chart from a Helm repository**
```yaml
deploy:
  helm:
    releases:
      - name:  ... Env var works fine for these values
        repo: ...
        remoteChart: ...
        namespace:  ... Env var works fine for these values
        createNamespace: true
        version: "{{.CHART_VERSION}}" <- This does not work
        setValueTemplates:  ... Env var works fine for these values
        artifactOverrides: ... Env var works fine for these values
```

### Steps to reproduce the behavior

1. Try to use an environment variable in the helm release version.
