### ISSUE TITLE
[Feature request] Allow using environment variables for the `deploy.helm.releases[].repo` field

### ISSUE THREAD

**Issue by artemkoru** [GoogleContainerTools/skaffold#5716]
Hi,

We are using private helm repos and it will be very helpfull to allow using Go templates for the `deploy.helm.releases[].repo` field.

### Expected behavior

We want to replace `CHARTUSER` и `CHARTPASS` from env vars.

```yaml
...
deploy:
  helm:
    releases:
      - name: release-name
        repo: https://{{.CHARTUSER}}:{{.CHARTPASS}}@charts.site.com/
        remoteChart: my-private-chart
...
```

But it returns the error:
```
Error: invalid chart URL format: https://{{.CHARTUSER}}:{{.CHARTPASS}}@charts.site.com/
```

### Actual behavior

But this configuration works fine.

```yaml
...
deploy:
  helm:
    releases:
      - name: release-name
        repo: https://myrepouser:myrepopass@charts.site.com/
        remoteChart: my-private-chart
...
```

### Information

- Skaffold version: 1.22
- Operating system: macOS
- Installed via: skaffold.dev
