### ISSUE TITLE
skaffold doesn't work from gitlab-runner user

### ISSUE THREAD

**Issue by FreddieMcHeart** [GoogleContainerTools/skaffold#5719]
### Information

- Skaffold version:  v1.22.0
- Operating system:  ubuntu 20.04
- Installed via:  skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: cryptobot
profiles:
  - name: stage
    build:
      artifacts:
        - image: my-repo/bot
          docker:
            dockerfile: Dockerfile
            noCache: false
      local: {}
      tagPolicy:
        gitCommit:
          variant: AbbrevTreeSha
          prefix: v.alfa.2.
    deploy:
      kubectl:
        manifests:
          - yamles/*.yaml
```

### Steps to reproduce the behavior

1. Using a gitlab CI
2. .gitlab-ci.yml 
```
stages:
  - build
#  - deploy

Build and Publish to Stage:
  stage: build
  tags: [skaffold]
  script:
    - ls -al
    - skaffold run -p stage
  only:
    - RC
```
3. After starting, this pipeline had an error:

`parsing skaffold config: failed to apply profiles to config "cryptobot" defined in file "/home/gitlab-runner/builds/ZqTVFjA1/0/high-school-prod/cryptobot/skaffold.yaml". There's an issue with one of the profiles defined in config "cryptobot" in file "/home/gitlab-runner/builds/ZqTVFjA1/0/high-school-prod/cryptobot/skaffold.yaml"; refer to the documentation on how to author valid profiles: https://skaffold.dev/docs/environment/profiles/.`

`root@Skaffold:~# groups gitlab-runner
gitlab-runner : gitlab-runner sudo docker
`
users permissions 

If I go to the gitlab-runner home dir and then to project dir `~/builds/ZqTVFjA1/0/high-school-prod/cryptobot` and start any skaffold command like `skaffold run -p stage` or `skaffold build -p stage` I have the error that i wrote above. 

dir contents
```
-rw-rw-r--  1 gitlab-runner gitlab-runner   81 Apr 22 22:56 .dockerignore
drwxrwxr-x  5 gitlab-runner gitlab-runner 4096 Apr 23 14:51 .git
-rw-rw-r--  1 gitlab-runner gitlab-runner  301 Apr 21 21:53 .gitignore
-rw-rw-r--  1 gitlab-runner gitlab-runner  160 Apr 22 22:16 .gitlab-ci.yml
-rw-rw-r--  1 gitlab-runner gitlab-runner  455 Apr 23 14:51 Dockerfile
-rw-rw-r--  1 gitlab-runner gitlab-runner  156 Apr 21 21:53 README.md
drwxrwxr-x  2 gitlab-runner gitlab-runner 4096 Apr 21 21:53 aggregation
drwxrwxr-x  2 gitlab-runner gitlab-runner 4096 Apr 21 21:53 bot
-rw-rw-r--  1 gitlab-runner gitlab-runner   10 Apr 21 21:53 change-generator.md
drwxrwxr-x  2 gitlab-runner gitlab-runner 4096 Apr 22 22:00 elastic
drwxrwxr-x  2 gitlab-runner gitlab-runner 4096 Apr 21 21:53 fetchers
-rw-rw-r--  1 gitlab-runner gitlab-runner  143 Apr 21 21:53 go.mod
-rw-rw-r--  1 gitlab-runner gitlab-runner 1044 Apr 21 21:53 go.sum
drwxrwxr-x  2 gitlab-runner gitlab-runner 4096 Apr 21 21:53 logic
-rw-rw-r--  1 gitlab-runner gitlab-runner  351 Apr 21 21:53 main.go
drwxrwxr-x  2 gitlab-runner gitlab-runner 4096 Apr 21 21:53 model
-rw-rw-r--  1 gitlab-runner gitlab-runner  459 Apr 22 22:16 skaffold.yaml
drwxrwxr-x  2 gitlab-runner gitlab-runner 4096 Apr 21 21:53 utils
drwxrwxr-x  2 gitlab-runner gitlab-runner 4096 Apr 23 14:51 yamles

```
