### ISSUE TITLE
Feature Request: ReversePortForward

### ISSUE THREAD

**Issue by Richard87** [GoogleContainerTools/skaffold#5745]
For debugging PHP applications xdebug expects a client ip and port to connect back to when a session starts. Without reverse port forwarding this is very tricky to handle in a skaffold workflow.

I understand debugging have a lot of edgecases, but reverse port forwarding and some custom configuration would atleast make it possible when the skaffold supplied variants is not covered...

It has been requested here before, and Devspace.io seems to already include it, so there should be a "market" for the feature :) 
https://devspace.sh/cli/docs/configuration/development/reverse-port-forwarding https://github.com/GoogleContainerTools/skaffold/issues/4419

### Expected behavior
a reversePortforward configuration option

### Actual behavior
...
### Information

- Skaffold version: 1.23
- Operating system: Fedora 34
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
profiles:
  - name: debug
    activation:
      - command: debug
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: debug # dockerfile target with xdebug configuration
```
