### ISSUE TITLE
Support configuring status check independently between modules

### ISSUE THREAD

**Issue by maggieneterval** [GoogleContainerTools/skaffold#5746]
### Expected behavior

For a `skaffold.yaml` containing multiple pipelines, it is valid to configure the `Deploy.StatusCheck` value for each independently.

### Actual behavior

For a `skaffold.yaml` containing multiple pipelines, it is invalid to set the `Deploy.StatusCheck` value to `true` for one pipeline and `false` for another. (See discussion on https://github.com/GoogleContainerTools/skaffold/pull/5706 for details.)

### Information

- Example invalid skaffold.yaml

```yaml
apiVersion: skaffold/v2beta14
kind: Config
build:
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
  statusCheck: true 
---
apiVersion: skaffold/v2beta14
kind: Config
build:
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
  statusCheck: false
```

### Steps to reproduce the behavior

1. Run `skaffold dev` using a `skaffold.yaml` similar to the example above.
