### ISSUE TITLE
Add `skaffold mutate` command to support minimum features required for CC 

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#5758]
In this task

- [ ] P0 Support the use case to add a profile with new build env `gcb`  
- [ ] P1 Expose if a particular Dockerfile Artifact can be run via Kaniko. Maybe use a Metadata API maybe in `BuildMetadata`
      Not all DockerArtifacts can be run with kaniko. Some features are not supported in kaniko.
       See notes here https://github.com/tejal29/skaffold/pull/7/files#diff-c3bed1e9b531e926022ffef7a604e2045e899afe03ca1be23de8a3be568c9f8cR398
- [ ] P1 Support the use case to add a profile with new build env cluster and artifact type kaniko like this.
   ```
  artifacts:
    - image: skaffold-example
      kaniko:
        cache: {}
  cluster:
    namespace: default
```
- [ ] P1 Automatically plumb through gcloud auth if image push is true & registry is GCR.
   sample [code](https://github.com/tejal29/skaffold/pull/7/files#diff-122dbdbd5378fcfe71d3253fc132095e1756a908d4cfb406c4da5cba7b944edaR191)
