### ISSUE TITLE
Skaffold `status-check` should happen after individual `deploy` actions

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#5774]
Skaffold `status-check` currently runs after all deploy operations have completed. This could mean that in a multi-config project defining hierarchical (like `database`, `svc A` using `database`, `svc B` using `svc A`, and so on) deploy stanzas, skaffold doesn't wait for a resource deployment to become stable before moving on to the next deployment. 

As a result there's no real benefit to the topological ordered deployments for real-world services that take time to stabilize.

To fix this, status check should be run after each `deploy.<deployer_type>` execution. For instance, for the deploy stanza:
```yaml
metadata:
   name: cfg1
...
deploy:
  kubectl:
    ...
---
metadata:
   name: cfg2
requires:
  - configs: [cfg1]
...
deploy:
  helm:
    ...```
```
There should be a status-check after the `cfg1.deploy.kubectl` deployment and again after `cfg2.deploy.helm` deployment.
