### ISSUE TITLE
GCP Service Account key unable to retrieve token

### ISSUE THREAD

**Issue by LukeeeeBennett** [GoogleContainerTools/skaffold#5794]
### Expected behavior

Using only a GCP service account key, build using cloud build.

### Actual behavior

Never able to auth service account key, always tries to fallback to gcloud application default credentials

### Information

I am using skaffold in GitLab CI. Running in debug mode, I see that when skaffold starts the cloud build, it tries to auth after grabbing the gcloud credentials from `gcloud auth print-access-token`.

Unfortunately, no matter the permissions of the service account, my debug log shows 
 `unable to retrieve token: oauth2: token expired and refresh token is not set`.

It then continues, tried to request information about the logging bucket, which times out.

Related PR: https://github.com/GoogleContainerTools/skaffold/pull/2731

- Skaffold version: v1.7.1 (and latest from gcloud components on CI)
- Operating system: Mac (and Debian on CI using gcloud docker image)
- Installed via:  gcloud sdk
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: aaaa
build:
  googleCloudBuild:
    projectId: aaaa-bbbb
    machineType: E2_HIGHCPU_8
  artifacts:
    - image: gcr.io/aaaa-bbbb/cccc
      sync:
        infer:
          - '**/*.json'
      kaniko:
        cache: {}
  tagPolicy:
    sha256: {}
deploy:
  kustomize:
    paths:
      - k8s/overlays/lb-dev
profiles:
  - name: lb-dev
    patches:
      - op: replace
        path: /deploy/kustomize/paths/0
        value: k8s/overlays/lb-dev
      - op: replace
        path: /build/tagPolicy
        value:
          sha256: {}
  - name: development
    patches:
      - op: replace
        path: /deploy/kustomize/paths/0
        value: k8s/overlays/development
      - op: replace
        path: /build/tagPolicy
        value:
          gitCommit: {}
```

### Steps to reproduce the behavior

1. create GCP service account, assign "Owner" perms
1. `gcloud auth activate-service-account .... &&  gcloud container clusters get-credentials ....`
1. `skaffold run -pdevelopment -vdebug`

```
 - gcr.io/xxxx/xxxxx: Not found. Building
time="2021-05-06T02:05:58Z" level=info msg="Cache check completed in 1.244 second"
Starting build...
Building [gcr.io/xxxx/xxxx]...
time="2021-05-06T02:05:58Z" level=debug msg="Running command: [gcloud auth print-access-token --format=json]"
time="2021-05-06T02:05:59Z" level=debug msg="Command output: [{\n  \"token\": \"xxxx\"\n}\n]"
time="2021-05-06T02:05:59Z" level=info msg="unable to retrieve token: oauth2: token expired and refresh token is not set"
time="2021-05-06T02:05:59Z" level=info msg="falling back to application default credentials"
creating bucket if not exists: getting bucket "xxxx_cloudbuild": Get "https://storage.googleapis.com/storage/v1/b/xxxx?alt=json&prettyPrint=false&projection=full": Get "http://xxx.xxx.xxx.xxx/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control": dial tcp xxx.xxx.xxx.xxx:80: i/o timeout
```
