### ISSUE TITLE
Should `skaffold fix -version` abort or do no-op?

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#5798]
### Description
In `skaffolx fix --version VERSION`, if VERSION is older than in use version, skaffold aborts the attempts with message. e.g. 
```shell
skaffold fix --version v2beta12
config version v2beta14 is more recent than target version v2beta13: upgrade Skaffold
```
[Here](https://github.com/GoogleContainerTools/skaffold/blob/789d0581f6415de2ef2cc9a68fe27201fe252a48/pkg/skaffold/schema/versions.go#L202) is the source code.

As a consequence, in multi-config mode, users have no chance to use `skaffold fix --version` to upgrade their older versions if they also have some newer versions in use. Is this expected? Should `skaffold fix --version` do no-op if the in-use versions is equal or newer than the VERSION?   
 

### Information

- Skaffold version: v2beta15

**Comment by gsquared94** [comment]
Can you provide an example of how this fails in multi-config mode?
I think `skaffold fix` only updates configs in the current `skaffold.yaml` file.

**Comment by yuwenma** [comment]
@gsquared94 You are right, I guess I'm confused by this code:
The `skaffold fix` has a [returned config slices](https://github.com/GoogleContainerTools/skaffold/blob/master/cmd/skaffold/app/cmd/fix.go#L59)  which iterate the current `skaffold.yaml` and try to [find all APIVersion](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/versions.go#L234) from the skaffold.yaml. But it looks like the APISchema actully only have [one single APIVersion field](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/v2beta15/config.go#L39). Why does configFactoryFromAPIVersion assumes the parsing file have a list of APIVersions?

**Comment by yuwenma** [comment]
@gsquared94 Another question: Why does `skaffold fix` only upgrade the current `skaffold.yaml`, rather than upgrade all its dependency skaffold.yaml files? Seems nicer for users to have a single cmd upgrading all files (especially if the root `skaffold.yaml` is older than the expected, it is more likely its sub-dir `skaffold.yaml` files also need an update).

**Comment by gsquared94** [comment]
There can be a slice of config definitions in a single file with different versions, like rewriting `examples/microservices` `skaffold.yaml`:

```yaml
apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
    - image: base
      context: base
---
apiVersion: skaffold/v2beta13
kind: Config
requires:
  - configs: [base]
build:
  artifacts:
    - image: leeroy-web
      context: leeroy-web
      requires:
        - image: base
          alias: BASE
    - image: leeroy-app
      context: leeroy-app
      requires:
        - image: base
          alias: BASE

```
