### ISSUE TITLE
Port forwarding is not working with namespaces with Templated Fields

### ISSUE THREAD

**Issue by itaischw** [GoogleContainerTools/skaffold#5802]
Hi, 
I'm working with Skaffold and helm deploy.
The issue I see is that when you specify under deploy.helm.releases.namespace with a templated field,
and you want to do a user port forwarding, i.e. map port 22 to 5022, you can't use a templated field to set the 
portForward.namespace since it's not supporting templated field.
If you don't set the namespace under the portForward.namespace you will get a warning:
"Skipping the port forwarding resource ... because namespace is not specified"

### Expected behavior
The expected behaviour here is to either make the port forwarding use the custom namespace under the resource it is forwarding.
OR support templated fields for the portForward.namespace as well.

### Actual behaviour
Getting a warning "Skipping the port forwarding resource ... because namespace is not specified"
or if you set it with the templated field you will get an error for not finding the resource in the namespace without the templated field extraction 
i.e. my-namespace-{{ .USER }}

### Information

- Skaffold version: v1.19.0
- Operating system: MacOS
- Installed via: skaffold.dev |  Cloud Code 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta8
kind: Config
build: 
  artifacts:
    - image: my-image    
deploy:  
  helm:
    releases:
      - name: my-deployment
        chartPath: helm
        version: v2        
        valuesFiles:
          - helm/values/values.yaml
        artifactOverrides:
          image: my-image
        namespace: "my-namespace-{{ .USER }}"
        createNamespace: true
        upgradeOnChange: true

portForward:
  - resourceType: StatefulSet
    resourceName: tps-monitoring
    namespace: "my-namespace-{{ .USER }}"
    port: 22
    localPort: 5022

```

### Steps to reproduce the behavior

1. Deploy any helm you want to a namespace with a templated field.
2. Try to port forward  any port and set the namespace under the portForward with the same namespace as your deployment with a templated field.
