### ISSUE TITLE
Skaffold stuck at waiting for rollout to finish when rollout is already completed

### ISSUE THREAD

**Issue by Blackclaws** [GoogleContainerTools/skaffold#5810]
### Expected behavior

```skaffold dev``` starts the rollout and checks whether it has converged

### Actual behavior
``` skaffold dev ``` starts the rollout (which finishes in about a second) and continues waiting for the deployment to change which it never does, because it already converged. Deleting the existing pod manually will cause skaffold to notice the changes and finish the rollout

### Information

- Skaffold version: v 1.23.0
- Operating system: Archlinux
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
  - image: bff
    context: .
    kaniko: 
      registryMirror: https://registry.services.internal.company
      useNewRun: true
      
  cluster:
    dockerConfig:
      path: /home/felix/.docker/config.json
    namespace: default    
deploy:
  kubeContext: test-cluster
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
portForward:
  - resourceType: service
    resourceName: bff
    localPort: 8080
    port: 80


```

### Steps to reproduce the behavior

1. If you need a test repo I can provide that (skaffold-kustomize example already shows this behaviour)
2. ```skaffold dev```
```
DEBU[0139] getting client config for kubeContext: `test-cluster` 
DEBU[0139] checking status deployment/bff               
DEBU[0140] Running command: [kubectl --context test-cluster rollout status deployment bff --namespace default --watch=false] 
DEBU[0143] Command output: [Waiting for deployment "bff" rollout to finish: 0 of 1 updated replicas are available...
] 
DEBU[0143] Pod "bff-fd6f6d6f7-5v8zf" scheduled: checking container statuses 
DEBU[0143] Fetching events for pod "bff-fd6f6d6f7-5v8zf" 
DEBU[0144] Running command: [kubectl --context test-cluster rollout status deployment bff --namespace default --watch=false] 
 - deployment/bff: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/bff: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/bff: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/bff: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/bff: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/bff: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/bff: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/bff: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/bff: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/bff: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/bff: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/bff: waiting for rollout to finish: 0 of 1 updated replicas are available...
```
Running ```kubectl --context test-cluster rollout status deployment bff --namespace default --watch=false``` manually returns:
```
deployment "bff" successfully rolled out
```

EDIT: This seems to be related to ranchers proxying of kubectl. For some reason it behaves differently in regards to how skaffold interacts with it, though manual interaction with kubectl gives different results. Direct access to the cluster works api server works, though this is of course rather suboptimal.
