### ISSUE TITLE
Test stage does not support selecting a profile

### ISSUE THREAD

**Issue by jordivilaseca** [GoogleContainerTools/skaffold#5811]
### Expected behavior
Running `skaffold test -p test` command should run tests in the test profile.

### Actual behavior
`skaffold test` command does not support setting a specific profile (-p flag does not exist). In older versions of skaffold those could be run using `skaffold build -p dev` command, but that does not seem to work either.

### Information

- Skaffold version: v1.23.0
- Operating system: macos 11.3.1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
profiles:
- name: test
  build:
    artifacts:
    - image: service-test
      docker:
        target: builder
        dockerfile: Dockerfile
    local:
      push: false
      useBuildkit: true
  test:
  - image: service-test
    structureTests:
    - './test/structure-test.yaml'
```
