### ISSUE TITLE
Spurious warning when using only remote manifests

### ISSUE THREAD

**Issue by ekuefler** [GoogleContainerTools/skaffold#5818]
### Expected behavior

I should be able to define a kubectl deploy using only `remoteManifests` without any issues.

### Actual behavior

If I only define `remoteManifests`, I get a warning like this when running `skaffold run`:

```
Starting deploy...
WARN[0001] k8s/*.yaml did not match any file            
 - deployment.apps/manager configured
Waiting for deployments to stabilize...
Deployments stabilized in 13.710431ms
```

### Information

- Skaffold version: v1.23.0
- Operating system: Linux
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: environments
build:
  ...
deploy:
  kubectl:
    remoteManifests:
    - environments-system:deployment/manager
```

### Notes

I get the same warning if I explicitly set `manifests` to an empty array. I think there just needs to be a check against `remoteManifests` here: https://github.com/GoogleContainerTools/skaffold/blob/fb9c352200be6e02f61ed746e694b7093bc7c75e/pkg/skaffold/schema/defaults/defaults.go#L199.
