### ISSUE TITLE
Docs need an example of how to use .build.docker.buildArgs

### ISSUE THREAD

**Issue by torenware** [GoogleContainerTools/skaffold#5841]
### Expected behavior
Based on [the docs on the site](https://skaffold.dev/docs/references/yaml/#build-artifacts-docker-buildArgs) I'd expect the following fragment to be legal. It isn't.

```yaml
    - image: my-repo/ticketer-client
      context: client
      docker:
        dockerfile: Dockerfile-production
        buildArgs:
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: {{ .NEXT_PUBLIC_STRIPE_PUBLIC_KEY }} 
          NEXT_PUBLIC_BASE_URI: ingress-nginx-controller.ingress-nginx
```

### Actual behavior
I get a parsing error:

```
parsing skaffold config: error parsing skaffold configuration file: unable to re-marshal YAML without dotted keys: unable to parse YAML: yaml: invalid map key: map[string]interface {}{".NEXT_PUBLIC_STRIPE_PUBLIC_KEY":interface {}(nil)}
```
Native English speaker I am, but that golang err, well, is not English.

### Information

- Skaffold version: 1.22 and also 1.24
- Operating system: MacOS Mojave 10.14.6
- Installed via: curl from website.
- Contents of skaffold.yaml:

relevant section included; removing the lines

```
        buildArgs:
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: {{ .NEXT_PUBLIC_STRIPE_PUBLIC_KEY }} 
          NEXT_PUBLIC_BASE_URI: ingress-nginx-controller.ingress-nginx
```

restores the file to working order, but does not pass on the buildArgs to my Dockerfile.

### Steps to reproduce the behavior

Original version of the repo (w/o the buildArg related lines) is at https://github.com/torenware/grider-micro-services.
skaffold.yaml is at the top level.

I have a .env.local file that looks like this:

```
NEXT_PUBLIC_STRIPE_PUBLIC_KEY=pk_test_51ImnsGKlT5z4...
NEXT_PUBLIC_BASE_URI=ingress-nginx-controller.ingress-nginx
NEXT_TELEMETRY_DISABLED=1
```
which is passed to skaffold as

``` bash
source client/.env.local && skaffold dev
```
