### ISSUE TITLE
skaffold dev does not pickup the latest image when deployed through helm

### ISSUE THREAD

**Issue by manjiler** [GoogleContainerTools/skaffold#5852]
### Expected behavior
the watch loop build & deploy workflow to always pickup the latest image when deploying through helm

### Actual behavior
It pickup a stale image tag. Gives a warning that
```
Starting deploy...
WARN[0000] image [my-image:72ed4ce7a42de0d0af93c7d349ecbdf82b1796d9911a4bad5716e92f8f2a3f1a] is not used. 
WARN[0000] See helm documentation on how to replace image names with their actual tags: https://skaffold.dev/docs/pipeline-stages/deployers/helm/#image-configuration 
```

### Information

- Skaffold version: v1.24.0
- Operating system: MacOS - 10.12.6
- Installed via:  Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta16
kind: Config

build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
  - image: my-image
    context: .
    docker:
      dockerfile: "build/service1/Dockerfile"

deploy:
  helm:
    releases:
    - name: yggdrasill
      chartPath: ./deploy/helm/release
      namespace: stestcour
      upgradeOnChange: false
      skipBuildDependencies: true
      recreatePods: true
      artifactOverrides:
        image: my-image # no tag present!
        # Skaffold continuously tags your image, so no need to put one here.

portForward:
- resourceType: Service
  resourceName:  service1
  namespace: test
  port:  8000
  address: 127.0.0.1
  localPort:  8002

- resourceType: Service
  resourceName: service2
  namespace: test
  port: 4566
  address: 127.0.0.1
  localPort: 4566

- resourceType: Service
  resourceName: service3
  namespace: test
  port: 8998
  address: 127.0.0.1
  localPort: 8998

```

### Steps to reproduce the behavior

1. A simple python based FastAPI server.
2. `skaffold dev`
3. ...

**Comment by manjiler** [comment]
Content of deployment.yaml that is being used by helm
```yaml
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
```
