### ISSUE TITLE
Kustomize support

### ISSUE THREAD

**Issue by dlorenc** [GoogleContainerTools/skaffold#587]
Kustomize is ready in it's official home under kubernetes-sigs: https://github.com/kubernetes-sigs/kustomize

This issue tracks adding support for it as a deployer.

**Comment by dlorenc** [comment]
Strawman proposal for config syntax:

```
deploy:
  kustomize:
    kustomization: <path to kustomization.yaml>
```

The implementation could call `kustomize build` on the specified path, then parse the resulting yaml that comes through stdout and treat it as a `kubectl` deploy.

**Comment by dlorenc** [comment]
cc @pwittrock @monopole does this seem reasonable?

**Comment by shanna** [comment]
@dlorenc I haven't really tested it yet but what about a general command executor for kubectl manifests? That way you can use kustomize, make or whatever to generate manifests.

https://github.com/GoogleContainerTools/skaffold/compare/master...shanna:manifest-commands

```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: foo
    workspace: .
deploy:
  kubectl:
    commands:
      - kustomize build ./k8s
```
