### ISSUE TITLE
Is there or can there be support for helm plugins?

### ISSUE THREAD

**Issue by jbresciani** [GoogleContainerTools/skaffold#5873]
### Expected behavior

Helm supports plugins, we're currently using a plugin that assists in automatic recovery of secrets from vault, it's a fork of this plugin:

https://github.com/Just-Insane/helm-vault

Once a plugin is installed an extra subcommand is injected into helm and the plugin is activated by calling helm with, in this case, vault as a subcommand. i.e.

`helm vault template helm/myChart -f myValuesFile.yaml`

### Actual behavior

I have the plugin installed but I'm unsure how to have skaffold ustilize it. Is there current functionality to call a plugin when using helm?

### Information

- Skaffold version: v1.23.0
- Operating system: OSx 11.3.1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta13
kind: Config
build:
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - context: .
    image: gcr.io/myProject/myApi
  tagPolicy:
    gitCommit:
      variant: CommitSha
deploy:
  helm:
    releases:
    - name: "myApi-{{.USER}}"
      wait: true
      recreatePods: true
      artifactOverrides:
        image: gcr.io/myProject/myApi
      chartPath: helm/myApi
      valuesFiles:
        - "helm/vars/local.yaml"
profiles: []
```

For extra information, here's the helm plugin design guide
https://helm.sh/docs/topics/plugins/
