### ISSUE TITLE
Feature Request: Have Skaffold diagnose render transformed image

### ISSUE THREAD

**Issue by grmoon** [GoogleContainerTools/skaffold#5875]
Currently, `skaffold diagnose` renders the effective skaffold yaml configuration that skaffold will use during its execution. However, it does not render the final image location for artifacts, even if a default registry is set. Since skaffold transforms the image location as described [here](https://skaffold.dev/docs/environment/image-registries/), it would be nice to see the value skaffold will ultimately use in the output of `diagnose`.

### Command

`skaffold config set default-repo gcr.io/myproject`
`skaffold diagnose -f skaffold.yaml --yaml-only`

### Input Yaml

```yaml
apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: java-hello-world
      jib:
        args:
        - -Dmaven.test.skip=true
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: dockerfile
  build:
    artifacts:
      - image: java-hello-world
```

### Current Output Yaml

```yaml
apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
  - image: java-hello-world
    context: .
    
  ...
```

### Proposed Output Yaml

```yaml
apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
  - image: gcr.io/myproject/java-hello-world
    context: .
  ...
```
