### ISSUE TITLE
Feature request: --format flag for skaffold diagnose

### ISSUE THREAD

**Issue by grmoon** [GoogleContainerTools/skaffold#5878]
`skaffold diagnose --yaml-only` is extremely useful for identifying issues with potentially complicated skaffold configurations. It would be fantastic if there were a way to get the errors in json format for easy consumption.

### Input Yaml

```yaml
apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: java-hello-world
    context: .
    docker:
      target: mm
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
- name: cloudbuild
  some-invalid-yaml
  build:
    googleCloudBuild: {}
- name: dockerfile
  build:
    artifacts:
    - image: java-hello-world
```

### Current output

![Screen Shot 2021-05-20 at 2 55 40 PM](https://user-images.githubusercontent.com/8933338/119033687-82b5ca80-b97b-11eb-98fe-3dd53b312c1d.png)

### Proposed Output

`skaffold diagnose -f skaffold.yaml --yaml-only --format json` might output the following json

```json
{
  "errors": [{
      "line": 18,
      "message": "could not fine expected ':'"
  }]
}
```
