### ISSUE TITLE
Google Cloud Build - cacheFrom to support dynamic images and tags

### ISSUE THREAD

**Issue by dhodun** [GoogleContainerTools/skaffold#5879]
### Expected behavior
Skaffold should allow dynamic image naming and tagging for the 'cacheFrom' field in Docker (particularly for Google Cloud Build use cases where there is no Docker cache to hit unless you use this field).

Dynamic tagging is particularly needed here, though the image may need to be dynamic as well. A couple options:
1) Tag it the same as the Cloud Build push image/tag combo (works pretty well with gitCommit tagger, less so with dateTime)
2) Tag it with the "last" full SHA and tag that was built using skaffold (I think preferred)

### Actual behavior
Skaffold doesn't treat the 'cacheFrom' field in Cloud Build as an image name or dynamic in any way.

In general, this makes the cacheFrom field only useful for "latest" tag, which needs to be added to your build artifacts manually. Or you are stuck using SHA256 tagger which is generally not recommended.

We have many devs working on the same cluster and GCR repo using their own namespaces, so we need cacheFrom to be as close to the last container that dev built as possible. The only time using their last build isn't ideal is when they change branches, which will be small percentage of the time.

### Information

- Skaffold version: 1.24.1
- Contents of skaffold.yaml:

```yaml
kind: Config
build:
    tagPolicy:
        gitCommit: {}
  artifacts:
  - image: eu.gcr.io/my-project-id/my-image
    context: .
    docker:
      dockerfile: Dockerfile
      cacheFrom:
      - eu.gcr.io/my-project-id/my-image
  googleCloudBuild:
    projectId: my-project-id
```

Similar to: https://github.com/GoogleContainerTools/skaffold/issues/2536
