### ISSUE TITLE
Tests are ignoring profile when try to configure tests using profiles

### ISSUE THREAD

**Issue by bpvcode** [GoogleContainerTools/skaffold#5904]
### Expected behavior
Should accept flag `-p` as i am configuring tests using profiles, like says in - `skaffold/examples/custom-tests/README.md`

### Actual behavior
Command: 
skaffold test -p test --build-artifacts=tags.json

ERROR:
unknown shorthand flag: 'p' in -p
See 'skaffold test --help' for usage

### Information

- Skaffold version: 1.24.1
- Operating system: Pop!_OS 20.04
- Installed via: 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
  - image: custom-test-example

profiles:
  - name: test
    test:
    - image: custom-test-example
      custom:
        - command: ./test.sh
          timeoutSeconds: 60
          dependencies:
            paths:
            -  "*_test.go"
            -  "test.sh"
                      
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. Inside of this project, in this yaml file - `skaffold/examples/custom-tests/skaffold.yaml`
2. Try to "configure tests using profiles so that they can be automatically enabled or disabled" (See this file  `skaffold/examples/custom-tests/README.md` to know how to do it)
3. Run the command `skaffold test -p test --build-artifacts=tags.json` in your terminal
3. The response will be : `unknown shorthand flag: 'p' in -p`
