### ISSUE TITLE
Kaniko artifact build fails when image is pushed to an insecure container registry

### ISSUE THREAD

**Issue by quater** [GoogleContainerTools/skaffold#5923]
This problem was previously reported to the Kaniko project with GitHub issue https://github.com/GoogleContainerTools/kaniko/issues/1191. As of the feedback received with the aforementioned issue, this problem is caused by Skaffold.

### Expected behavior

The Docker image build with Kaniko completes without error when pushing to an insecure Docker registry that got deployed to the Minikube instance with the `minikube addons enable registry` command.

### Actual behavior

The Kaniko build and push works **BUT** before the build step finishes, Skaffold then tries to connect to the Docker registry to obtain the digest of the newly pushed Docker image. This fails due to Skaffold making the assumption that the Docker Registry URL should be resolvable from the Skaffold host machine and that it is accessible via HTTPS (i.e. port 443).

```
INFO[0053] GET KEYCHAIN                                 
INFO[0053] Pushing image to registry.kube-system/web:v1.6 
INFO[0054] Pushed image to 1 destinations               
getting image: Get "https://registry.kube-system/v2/": dial tcp: lookup registry.kube-system on 127.0.0.53:53: no such host
```

### Information

The `minikube addons enable registry` command creates an insecure Docker registry in the "kube-system" namespace. When Kaniko builds the Docker image, it can correctly resolve the DNS `registry.kube-system` K8s internally and can successfully access and push to the Docker Registry on port 80. However, this Docker Registry is only accessible from the Skaffold host via HTTP (i.e. port 5000) and not HTTPS (i.e. port 443). Furthermore, unless the `/etc/hosts` file was configured to resolve `registry.kube-system` to the Minikube IP, it does also fail to resolve the domain name.

- Skaffold version:
  ```
  $ ~/.cache/cloud-code/installer/google-cloud-sdk/bin/skaffold version
  v1.24.1
  ```
- Operating system: Ubuntu 21.04
- Installed via: Cloud Code
- Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v2beta16
kind: Config

build:
  artifacts:
    - image: registry.kube-system/web
      context: ./apps/web
      kaniko:
        dockerfile: Dockerfile
        insecure: true
        insecurePull: true
        insecureRegistry: ["registry.kube-system"]
        verbosity: Debug
  tagPolicy:
    gitCommit:
      ignoreChanges: false
```

### Steps to reproduce the behavior

1. Start Minikube `minikube start`
2. Install Minikube Docker registry `minikube addons enable registry` 
3. Run Cloud Code that uses Skaffold or run `skaffold build`

**At present, I don't see that Skaffold exposes a property that allows configuring an alternative Docker Registry URL.**
