### ISSUE TITLE
`skaffold dev` stuck in infinite build loop

### ISSUE THREAD

**Issue by misterikkit** [GoogleContainerTools/skaffold#5933]
TL;DR I think `.build.artifacts.custom.dependencies.ignore` is not working as intended, causing extraneous rebuilds.

### Expected behavior
Running `skaffold dev` should only rebuild + redeploy when I make code changes.

### Actual behavior
`skaffold dev` is triggering on unexpected fsnotify events generated by the build process.

### Information

- Skaffold version: 
  v1.25.0
- Operating system: 
  Ubuntu 16.04.3 LTS
- Installed via: 
  Cloud Code
- Contents of skaffold.yaml:

```yaml
# edited for brevity. I have a dozen artifacts that are built & deployed the same way.
apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: hm
build:
  local:
    concurrency: 10
  artifacts:
    - image: protection
      context: ./protection/
      custom:
        buildCommand: ../build/go-build.sh make package PROJECT_VERSION="${IMAGE##*:}"
        dependencies:
          paths: ["."]
          ignore: ["bin/*", "deploy/chart/charts/*", "deploy/chart/crds/*", "*.pb.go", "gomock*/*", "mock/*", "pkg/agent/mock/*", "api/policy/v1/zz*"]
 
deploy:
  helm:
    releases:
      - name: protection
        skipBuildDependencies: true
        chartPath: ./protection/deploy/chart/
        artifactOverrides:
          hmlibrary.image.skaffoldOverride: protection

```

My makefile runs `mockgen`, `protoc`, and `controller-gen` as part of the build. I don't want any generated files to trigger a rebuild, since (A) that is what causes the endless rebuild loop, and (B) any inputs to the generated files _are_ part of the watched source tree. 

I see two potential problems here.
1. The dependency list is built once at the beginning, so it doesn't check the `ignore` patterns for newly created files (mockgen temp files)
2. Generated files which do exist at start time, and are matched by my `ignore` patterns (🤞) seem to make it into the file monitor event queue in an unpredictable manner.

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

Skaffold logs snippet
```
Watching for changes...
time="2021-06-02T17:50:33-06:00" level=debug msg="Change detected notify.Create: \"/home/jbasseri/dev/hm/.git/index.lock\""
time="2021-06-02T17:50:33-06:00" level=debug msg="Change detected notify.Remove: \"/home/jbasseri/dev/hm/.git/index.lock\""
time="2021-06-02T17:50:44-06:00" level=debug msg="Change detected notify.Create: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605\""
time="2021-06-02T17:50:44-06:00" level=debug msg="Change detected notify.Create: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Create: \"/home/jbasseri/dev/hm/.git/index.lock\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Remove: \"/home/jbasseri/dev/hm/.git/index.lock\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Create: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605/prog.bin\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Create: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605/prog.bin\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Create: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605/prog.bin-go-tmp-umask\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Create: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605/prog.bin-go-tmp-umask\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Remove: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605/prog.bin-go-tmp-umask\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Remove: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605/prog.bin-go-tmp-umask\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Write: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605/prog.bin\""
<snip ~480 identical lines>
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Remove: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605/prog.bin\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Remove: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605/prog.bin\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Remove: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Remove: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Remove: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Remove: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Remove: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605/prog.go\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Remove: \"/home/jbasseri/dev/hm/protection/gomock_reflect_484316605/prog.go\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Write: \"/home/jbasseri/dev/hm/protection/mock/mock_policy_client.go\""
time="2021-06-02T17:50:45-06:00" level=debug msg="Change detected notify.Write: \"/home/jbasseri/dev/hm/protection/mock/mock_policy_client.go\""
time="2021-06-02T17:50:46-06:00" level=debug msg="Change detected notify.Write: \"/home/jbasseri/dev/hm/protection/mock/mock_policy_client.go\""
time="2021-06-02T17:50:46-06:00" level=debug msg="Change detected notify.Write: \"/home/jbasseri/dev/hm/protection/mock/mock_policy_client.go\""
time="2021-06-02T17:50:46-06:00" level=debug msg="Change detected notify.Create: \"/home/jbasseri/dev/hm/protection/pkg/agent/gomock_reflect_428381803\""
time="2021-06-02T17:50:46-06:00" level=debug msg="Change detected notify.Create: \"/home/jbasseri/dev/hm/protection/pkg/agent/gomock_reflect_428381803\""
time="2021-06-02T17:50:47-06:00" level=info msg="files added: [protection/pkg/agent/gomock_reflect_428381803/prog.go]"
time="2021-06-02T17:50:47-06:00" level=info msg="files modified: [protection/mock/mock_policy_client.go]"
Generating tags...
```

The behavior seems inconsistent, as sometimes `changes.go` will log my CRD manifests as modified. e.g.
```
time="2021-06-02T18:14:03-06:00" level=info msg="files modified: [protection/deploy/chart/charts/hmlibrary-0.1.0.tgz protection/deploy/chart/crds/policy.hm.com_policies.yaml protection/deploy/chart/crds/policy.hm.com_policybindings.yaml]"
```

I believe we are hitting the default case here
https://github.com/GoogleContainerTools/skaffold/blob/fafdcd73c51cf7f95c86855c60474c50dffd7835/pkg/skaffold/sync/sync.go#L77-L78

which causes us to hit the default case here
https://github.com/GoogleContainerTools/skaffold/blob/fafdcd73c51cf7f95c86855c60474c50dffd7835/pkg/skaffold/runner/v1/dev.go#L237-L238
