### ISSUE TITLE
skaffold ist not able to DEBUG from IntelliJ with a Java Project which is deployed with Helm

### ISSUE THREAD

**Issue by mehmetsalgar** [GoogleContainerTools/skaffold#5946]
### Expected behavior
I am using Google Cloud Code Plugin with IntelliJ to deploy and debug my Spring Boot  application in kubernetes (docker-desktop/kubernetes) with skaffold/JiB/Helm.

Project correctly deploys to Kubernetes/Docker Desktop but not able to DEBUG over IntelliJ.

I started a discussion about it in Stackoverflow 

[Stackoverflow Diskussion](https://stackoverflow.com/questions/67687071/skaffold-debug-and-missing-java-tool-options)

which we decided there, for some reason Skaffold does not understand this is a Java project and does not set JAVA_TOOL_OPTIONS as it is mentioned in 

[Skaffold Debug](https://skaffold.dev/docs/workflows/debug/#java-and-other-jvm-languages-runtime-jvm-protocols-jdwp)

If I set the JAVA_TOOL_OPTIONS as environment variables in Helm Chart and set Ports/Services for jdwp I can debug, but for some reason Skaffold is not doing for me.

It is alsoe mentioned in the Stackoverflow discussion additional variables such as SKAFFOLD_CMDLINE and SKAFFOLD_FILENAME are also not set.

I followed advice there and created a reproduceable Project which you can find as attachement.

Only thing you have to change in the project (while you can't use my Dcoker Registry) JiB Image Upload location in.

'poc-helm-gc\pom.xml'

`          <to>
            <image>xxxxxx/${project.artifactId}:latest</image>
          </to>`

xxxxxx with your docker registry...

After skaffold deploys the file to kubernetes, when you invoke 'curl http://localhost:8480/doSomething' and placed a Breakpoinf at 'poc-helm-gc\src\main\java\org\test\gc\poc\rest\PoCRestController.java'

`    @GetMapping("/doSomething")
    public ResponseEntity<String> doSomething() {
        return ResponseEntity.status(HttpStatus.OK).body("We received: " + LocalDateTime.now());
    }`

you should hit the breakpoint, which is not happening...

### Actual behavior
IntelliJ/skaffold does not react to the Break Point...

### Information

- Skaffold version: Version:v1.25.0 ConfigVersion:skaffold/v2beta16 GitVersion: GitCommit:c788c2b15fc3b3a002edcff25b5ef33563d5bb9c BuildDate:2021-05-26T03:32:23Z GoVersion:go1.14.14 Compiler:gc Platform:windows/amd64
- Operating system: Windows 10
- Installed via: Cloud Code
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
    - image: poc-helm-gc
      context: .
      jib: {}
  tagPolicy:
    sha256: {}
deploy:
  helm:
    flags:
      upgrade:
        [ "--timeout=30m", "--install","--dependency-update", "--force", "--debug"]
      install:
        [ "--timeout=30m","--debug","--dependency-update"]
    releases:
      - name: poc-helm-gc
        chartPath: "./helm/poc-helm-gc"
        artifactOverrides:
          image: poc-helm-gc
        namespace: poc-gc
        valuesFiles:
        useHelmSecrets: false
        createNamespace: true
```

[poc-helm-gc.zip](https://github.com/GoogleContainerTools/skaffold/files/6599222/poc-helm-gc.zip)

### Steps to reproduce the behavior

1. Explode zip containing the reproduceable Project
2. correct 'Docker Registry' at 'poc-helm-gc\pom.xml'
3. Set a Breakpoint at  'poc-helm-gc\src\main\java\org\test\gc\poc\rest\PoCRestController.java'
4. Select Develop on Kubernetes at IntelliJ and Click Debug
5. Wait IntelliJ/skaffold report ready to Debug
6. invoke curl statement 'curl http://localhost:8480/doSomething'
7. No breakpoints are reached
