### ISSUE TITLE
Skaffold.yaml is not being parsed correctly

### ISSUE THREAD

**Issue by hamza-lahlou** [GoogleContainerTools/skaffold#5954]
### Actual behavior
parsing skaffold config: error parsing skaffold configuration file: unable to parse config: yaml: unmarshal errors:
  line 16: field manifest not found in type v2alpha3.KubectlDeploy
### Information

- Skaffold version: e6711d8-dirty
- Operating system: Ubuntu 20.04.02 LTS
- Installed via: skaffold.dev 
- Contents of skaffold.yaml:
- 

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifest:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: hamza9899/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...
