### ISSUE TITLE
Sync only monitors pre-configured namespaces

### ISSUE THREAD

**Issue by jt-helsinki** [GoogleContainerTools/skaffold#5968]
### Expected behavior

When a file in a watched directory changes the file is built into an image, the image is deployed into the cluster. 

### Actual behavior

Running `skaffold run` works. As does the initial build/deploy of the `skaffold dev` command. The cluster is all up and running and it looks good. The correct image versions (as generated by Skaffold) are being used.

The problem happens when a file changes. 

1. File change is detected which kicks off a build
2. Skaffold tries to sync the changes, this looks ok until a sync error is shown. 
    ```
    DEBU[0328] getting client config for kubeContext: `minikube` 
    WARN[0328] Skipping deploy due to sync error: copying files: didn't sync any files 
    Watching for changes...
    ```
This seems to be a recurring issue based on similar issues posted in the tracker. However the solution is not clear. 

A more useful error message would be helpful. 

### Information

- Skaffold version: v1.25.0

- Operating system: Mac OS 11.3.1 Big Sur
- Installed via: Homebrew

- Multi module maven project. Java, Spring boot. Actuator

Jib plugin in `pom.xml`

```
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>jib-maven-plugin</artifactId>
    <version>3.0.0</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>dockerBuild</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

- Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
  - image: base-java-image
    context: ./docker/base-images/java-spring
    docker:
      dockerfile: Dockerfile

  - image: authentication-service
    context: ./service
    docker:
    jib:
      project: authentication-service
      args:
        - -Pspring-devtools
        - -Pskip-tests
        - -Pbuild-docker-images-jib
    sync:
      auto: true
    requires:
      - image: base-java-image

  - image: data-manager-service
    context: ./service
    jib:
      project: data-manager-service
      args:
        - -Pspring-devtools
        - -Pskip-tests
        - -Pbuild-docker-images-jib
    sync:
      auto: true
    requires:
      - image: base-java-image

  - image: router-service
    context: ./service
    jib:
      project: router-service
      args:
      - -Pspring-devtools
      - -Pskip-tests
      - -Pbuild-docker-images-jib
    sync:
      auto: true
    requires:
      - image: base-java-image

deploy:
  kubeContext: minikube
  helm:
    flags:
      upgrade:
        - --install
    releases:
      - name: mychart
        chartPath: ./docker/k8s/helm/mychart
        valuesFiles:
          - "docker/k8s/helm/mychart/values.yaml"
        artifactOverrides:
          deployments.authenticationService.image: authentication-service
          deployments.dataManagerService.image: data-manager-service
          deployments.routerService.image: router-service



```

**Comment by jt-helsinki** [comment]
I did some more digging and this appears to be am issue with the way Skaffold handles namespaces. If helm creates teha namespace, skaffold does not handle this well. 

For example, if I take the Skaffold `jib-sync` example and change the `pod.yaml` to:

```
apiVersion: v1
kind: Namespace
metadata:
  name: test

---

apiVersion: v1
kind: Pod
metadata:
  name: test-file-sync
  namespace: test
spec:
  containers:
  - name: test-file-sync
    image: test-file-sync
    ports:
      - containerPort: 8080

```
and try to run `skaffold dev` the same sync error is shown. 

under the `deploy` section of the skaffold.yaml, if I specify the helm namesapce skaffold won't work with a helm created namespace. The only way I could find to do this was to get skaffold to create the namespace and putting a conditional switch into the values.yaml which switches on/off the namespace creation in helm (by using the `setValues` section of the `deplpyment.helm` section.

This namespace handling probably needs some work as it's not quite right.
