### ISSUE TITLE
Skaffold ignores Dockerfile if it's in .dockerignore

### ISSUE THREAD

**Issue by Rishka** [GoogleContainerTools/skaffold#597]
### Expected behavior
`skaffold dev` should find a `Dockerfile` even when it is in the `.dockerignore` 

### Actual behavior
`skaffold dev` does not find the docker file, logs `WARN[0005] Skipping Deploy due to build error: running build for artifact: running build: docker build: Error response from daemon: Cannot locate specified Dockerfile: Dockerfile`

### Information

- Skaffold version: version 0.6.1
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: app
deploy:
  kubectl:
    remoteManifests:
      - deployment/app

```

### Steps to reproduce the behavior

1. Have a docker ignore that includes the dockerfile
2. try `scaffold dev`
