### ISSUE TITLE
Profile deploy field doesn't replace default deploy field

### ISSUE THREAD

**Issue by yhrn** [GoogleContainerTools/skaffold#5970]
### Expected behavior
Given a `skaffold.yaml` similar to the one below, minus the profile patch, I would expect `skaffold render -p my-profile` to use Kustomize to render manifests from `yet-another-dir` because the [documentation](https://skaffold.dev/docs/environment/profiles/#override-via-replacement) states:

> The build, test and deploy sections defined in the profile will completely replace the main configuration. The default values are the same in profiles as in the main config.

### Actual behavior
`skaffold render -p my-profile` tries to render using `kpt fn run` and fails because `some-other-dir` doesn't exist. If the patch removing `/deploy/kpt` is included then it works as expected. Looking at [the code](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/profiles.go#L282-L353) though it seems like a deep merging behavior is intended so it might be that the documentation that is wrong.

### Information

- Skaffold version: 1.25.0
- Operating system: Linux
- Installed via: built from source
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: gabito-streaming
build: ...
deploy:
  kpt:
    dir: some-dir
    fn:
      fnPath: some-other-dir
profiles:
- name: my-profile
  deploy:
    kustomize:
      paths:
      - yet-another-dir
  # This shouldn't be needed according to the docs.
  patches:
  - op: remove
    path: /deploy/kpt
```
