### ISSUE TITLE
Adding cluster profiles to existing skaffold files not working

### ISSUE THREAD

**Issue by grmoon** [GoogleContainerTools/skaffold#5985]
### Expected behavior

Profile with `cluster` build environment is added to skaffold file.

### Actual behavior

Profile with `cluster` build environment is not added to skaffold file.

### Information

```yaml
apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: untitled-
build:
  artifacts:
  - image: java-hello-world
    context: .
    docker: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/hello.deployment.yaml
    - kubernetes-manifests/hello.service.yaml
profiles:
- name: test
  build:
    googleCloudBuild: {}
```

### Steps to reproduce the behavior

1. clone java hello world sample in cloud code
2. run `skaffold inspect build-env add cluster -f skaffold.yaml --profile test2`
