### ISSUE TITLE
Environment variable templated valuesFile using relative path to files

### ISSUE THREAD

**Issue by davidcunningham** [GoogleContainerTools/skaffold#5997]
### Expected behavior
Expect to use absolute or relative path based on the set environment variable.

### Actual behavior
Any environment variable passed into valuesFile is being appended onto current working directory.

### Information

This is working as expected on v1.20.0 but is not working in v1.26.0. This is in a multi-config / modules setup. The base skaffold.yaml calls 10+ module skaffold files. When the module skaffold file is being called in 1.26.0 the environment variable is being appended to the current working directory path instead of using the absolute path.

Example: 

Assume
base - /path/test/skaffold.yaml
```
...
requires:
  - path: ./mymodule
...
```

mymodule - /path/test/mymodule/skaffold.yaml
```
...
deploy:
  helm:
    releases:
      - name: mymodule
        chartPath: ./k8s/
        valuesFiles:
          -  "./k8s/values.yaml"
          - "{{ .VALUES_FILE }}"
....
```

If I set an environment variable VALUES_FILE to `/a/b/values.yaml` I would expect `/a/b/values.yaml` to be used in mymodule. However, what it is attempting to use is `/path/test/mymodule//a/b/values.yaml`. This was working in 1.20.0. 

Note - if I hardcode `/a/b/values.yaml` instead of `"{{.VALUES_FILE}}"` it works as expected.
