### ISSUE TITLE
skaffold custom test does not run before pushing the image

### ISSUE THREAD

**Issue by yazbekhe** [GoogleContainerTools/skaffold#6018]
### Expected behavior
the skaffold custom test run before pushing the image to registry

### Actual behavior
the skaffold custom test run after pushing the image to registry

### Information
as stated by the doc that the difference between custom test and the structure test, is that custom test run in the testing phase which is before tagging and pushing. but my test does not return the expected result

- Skaffold version: 1.26.1
- Operating system: centos:7
- Installed via: curl
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta17
kind: Config
profiles:
  - name: testdev
    test:
    - image: rgregistrytest.azurecr.io/testreg/cache
      custom:
      - command: ./test.sh
        timeoutSeconds: 60
        dependencies:
          paths:
          - .
    build:
      artifacts:
        - image: rgregistrytest.azurecr.io/testreg/cache
          context: ..
          docker:
            dockerfile: Dockerfile
      tagPolicy:
        envTemplate:
          template: '{{ .TAGNAME }}'
    deploy:
      helm:
        releases:
          - name: '{{ .RELEASENAME }}'
            remoteChart: rcmn/rcmndeploy
            valuesFiles:
              - values.yaml
            artifactOverrides:
              services.cache.containers.envoyproxy.image: rgregistrytest.azurecr.io/testreg/cache
            version: ~0.3.0
            setValueTemplates:
              buildID: '{{ .BUILD_SOURCEVERSION }}'
              ingresses.cache.hostnames: '{ {{- .HOSTNAMES -}} }'
              pullPolicy: Always
              services.cache.replicaCount: '{{ .REPLICAS }}'
            wait: true
            upgradeOnChange: true
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold dev  -p testdev --namespace default --skip-tests=false`
3. also i have tried skaffold run
