### ISSUE TITLE
Recently started getting "Too many open files..." spinning up cluster on Apple M1

### ISSUE THREAD

**Issue by cheslijones** [GoogleContainerTools/skaffold#6072]
### Expected behavior

That my project would be deployed and spin-up without any issues.

### Actual behavior

It is safe to say, I think, that this is isolated to Apple Silicon.

I get all of these "Too many open files..." warnings, the deployment slows down to snails crawl, other messages related to "failed to port forward <service> is taken, retrying..." and then eventually it acts like it starts trying to rebuild the images again. Basically it is a mess...

Interestingly you can access the services, but none of the communication between them is working.

Without `-vdebug`:

https://user-images.githubusercontent.com/59094233/123156973-d2762e80-d41e-11eb-8e55-f91cba88a532.mov

With `-vdebug`:

https://user-images.githubusercontent.com/59094233/123155811-68a95500-d41d-11eb-8b5f-b680ba2d7f76.mov

I've only tested it is still working on AMD and Intel Linux and Windows (WSL2) machines. Works perfectly fine, the application spins up quickly and without issues. 

I don't have an Intel Mac around me at this point in time to test it, but I'd imagine it works fine there as well. At least that is what I was working on for two years up until about a month ago. 

Pretty sure this was working perfectly about a month ago on an M1 Mac that has since been reformatted... but I could be mistaken. I reinstalled everything following the exact same steps, however.

### Information

- Skaffold version: `1.26.1`
- Operating system: macOS 11.4
- Installed via: `skaffold.dev`, but did also try `brew` with the same results... using the `darwin-arm64` version
- Contents of skaffold.yaml:

You can comment out the individual `artifacts`, or the `manifests`, to just deploy one service at a time. The results are the same... a ton of errors about "Too many open files..." and eventually it becomes unresponsive.
```
apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
  - image: admin
    context: admin
    sync:
      manual:
      - src: "src/**/*.php"
        dest: .
      - src: "conf/**/*.conf"
        dest: .
      - src: "src/Templates/**/*.tbs"
        dest: .
      - src: "src/css/**/*.css"
        dest: .
      - src: "src/js/**/*.js"
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: admin-v2
    context: admin-v2
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
      - src: 'src/**/*.tsx'
        dest: .
      - src: '**/*.json'
        dest: .
      - src: 'public/**/*.html'
        dest: .
      - src: 'src/assets/sass/**/*.scss'
        dest: .
      - src: 'src/build/**/*.js'
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  - image: api
    context: api
    sync:
      manual:
      - src: "**/*.py"
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  - image: api-v2
    context: api-v2
    sync:
      manual:
      - src: "**/*.py"
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  - image: client
    context: client
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
      - src: 'src/**/*.jsx'
        dest: .
      - src: '**/*.json'
        dest: .
      - src: 'public/**/*.html'
        dest: .
      - src: 'src/assets/sass/**/*.scss'
        dest: .
      - src: 'src/build/**/*.js'
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  - image: postgres
    context: postgres
    sync:
      manual:
      - src: "**/*.sql"
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/dev/ingress.yaml
      - k8s/dev/postgres.yaml
      - k8s/dev/client.yaml
      - k8s/dev/admin.yaml
      - k8s/dev/admin-v2.yaml
      - k8s/dev/api.yaml
      - k8s/dev/api-v2.yaml
    defaultNamespace: dev
```

### Steps to reproduce the behavior

1. Unfortunately I can't post the project due to it being proprietary. I'd suspect anyone with not even a moderate size or complex project will also run into the issue.
2. `skaffold dev --port-forward -n dev`

These are other dependencies:
- Docker Desktop for Apple Silicon 3.4.0 (65384)
- Kubernetes v1.21.1 (enabled via Docker Desktop)
- Minikube v1.21.0 (arm64)
- Skaffold v1.26.1 (arm64)
- Homebrew 3.2.0

Pretty sure can't install anything but `arm64` for these and haven't tried the non-`arm`  versions.

This is what I've tried:
- Several reformats of the system.
- Using `virtualization.framework` and `hypervisor.framework`.
- Installing all in `terminal` under as "Universal" or "Apple Silicon".
- Running with VS Code as "Universal" or "Apple Silicon".
- Running with VS Code as "Intel".
- Installing all in VS Code as "Intel" and running in VS Code as "Intel".
- 8GB and 16GB M1 models.
- 4 CPU cores and 6GB RAM in Docker Desktop.
- Minikube has 2 CPU cores and 4GB RAM.
- Using Docker driver in Minikube.

**Comment by cheslijones** [comment]
Actually did manage to get all of those messages to go away, but now I'm getting these errors:

```
[postgres] COPY 5733
[client] error: unexpected EOF
[postgres] error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
[admin-v2] error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
[api-v2] error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
WARN[0664] exit status 1                                
WARN[0664] exit status 1                                
WARN[0664] exit status 1                                
WARN[0664] exit status 1                                
[admin] error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
WARN[0664] exit status 1                                
[api] error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
WARN[0664] exit status 1                                
^CCleaning up...
WARN[0714] could not map pods to service dev/postgres-cluster-ip-service-dev/5432: getting service dev/postgres-cluster-ip-service-dev: context canceled 
WARN[0714] could not map pods to service dev/api-v2-cluster-ip-service-dev/5001: getting service dev/api-v2-cluster-ip-service-dev: context canceled 
WARN[0714] could not map pods to service dev/client-cluster-ip-service-dev/3000: getting service dev/client-cluster-ip-service-dev: context canceled 
WARN[0714] could not map pods to service dev/api-cluster-ip-service-dev/5000: getting service dev/api-cluster-ip-service-dev: context canceled 
WARN[0714] could not map pods to service dev/admin-cluster-ip-service-dev/4000: getting service dev/admin-cluster-ip-service-dev: context canceled 
WARN[0714] could not map pods to service dev/admin-v2-cluster-ip-service-dev/4001: getting service dev/admin-v2-cluster-ip-service-dev: context canceled 
```
Looks like I'm actually getting this on Linux and WSL2 as well, so maybe some other issue.

I did the following and the messages went away on the M1:
- Docker Desktop arm64 (required can't use amd64)
- Enabled `kubectl` in Docker desktop
- VS Code - Intel
- Installed `brew` while in VS Code -Intel
- Installed `minikube arm64` via the website instructions (required can't user amd64)
- `skaffold` installed via `brew in VS Code - Intel... pretty sure this is the `amd64` version
- Spun up the cluster in VS Code - Intel

Didn't get the "Too many open files..." warning by doing this, but now getting the `http2` errors.

**Comment by briandealwis** [comment]
I don't think this is a Skaffold problem: I run Skaffold on an M1, admittedly with fewer containers, and I don't see this issue.  

It's worth poking around with `lsof` and try to find out which processes have an inordinate number of open files. 
```
$ lsof -n | awk '{ counts[$1]++} END { for(c in counts) { print counts[c], c}}' | sort -n | tail
104 Terminal
124 AppleSpell
170 Google\x20Chrome\x20Helper
243 UserEventAgent
243 app_mode_loader
253 corespotlightd
381 eclipse
472 Google\x20Chrome
884 zsh
2684 Google\x20Chrome\x20Helper\x20(Renderer)
```

And check your `sysctl` values too:
```
$ sysctl -a | grep files
kern.maxfiles: 49152
kern.maxfilesperproc: 24576
kern.filesetuuid: FB10CC0A-B8BA-C020-BC47-A50D64476F11
kern.num_files: 5191
```

Ah, now that I'm writing this, I do remember having this problem with my older MBP.  For some reason, my default ulimits for the maximum open files was set really low (`ulimit -n`).  This doc describes a way to bump the settings:

https://gist.github.com/tombigel/d503800a282fcadbee14b537735d202c

**Comment by cheslijones** [comment]
What version of `skaffold` are you using on your M1? `arm64` or `amd64`?

I found that installing the `skaffold-darwin-amd64` version inside either the `i386` or `arm64` terminal does get it working and I'm actually able to work. It is really slow to spin up though. Installing `skaffold-darwin-arm64` in either `i386` or `arm64`... yeah, just isn't working for me for some reason.

It looks like my `ulimit -n` is at 8192. Maybe I'll increase that and give the `arm64` version a try again.

**Comment by cheslijones** [comment]
OK, gave [the link you provided](https://gist.github.com/tombigel/d503800a282fcadbee14b537735d202c) a shot.

At `20000`, I got the same errors though less frequent and ultimately the cluster failed to load due to:

```
unable to stat file "admin/Dockerfile": stat admin/Dockerfile: too many open files in system
```

So I increased it to `524288` that caused my computer to crash the first time. The second time Terminal crashed. So maybe there is a value somewhere in the middle that might clear up the issue without causing crashes.

But given the `skaffold-darwin-amd64` version works OK, though be it slow, I might have to stick with that for now.

**Comment by tejal29** [comment]
Thanks @cheslijones for bringing this issue.  I am going to keep this open for now.

**Comment by MaxVale46** [comment]
Hi all.
Hoping it will help, i have the same problem on a MacBook Air (M1, 2020).

### Information

Skaffold version: `1.28.0`
Operating system: `maxOS Big Sur (Version 11.4)`
Installed via: `skaffold.dev`

Contents of skaffold.yaml:

        apiVersion: skaffold/v2beta16
        kind: Config
        deploy:
          kubectl:
            manifests:
              - ./infra/k8s/*
        build:
          local:
            push: false
          artifacts:
            - image: ADMIN/auth
              context: auth
              docker:
                dockerfile: Dockerfile
              sync:
                manual:
                  - src: 'src/**/*.ts'
                    dest: .

Some logs with -vdebug

        DEBU[0000] 2 manifests to deploy. 2 are updated or new  
        DEBU[0000] Running command: [kubectl --context docker-desktop apply -f -] 
         - deployment.apps/auth-depl configured
         - service/auth-srv configured
        INFO[0000] Deploy completed in 417.480333ms             
        Waiting for deployments to stabilize...
        DEBU[0000] getting client config for kubeContext: ``    
        DEBU[0000] checking status deployment/auth-depl         
        DEBU[0001] Running command: [kubectl --context docker-desktop rollout status deployment auth-depl --namespace default --watch=false] 
        DEBU[0002] Command output: [deployment "auth-depl" successfully rolled out
        ] 
        DEBU[0002] Fetching events for pod "auth-depl-55968bd7fb-tqmk4" 
         - deployment/auth-depl is ready.
        Deployments stabilized in 1.093 second
        DEBU[0002] getting client config for kubeContext: ``    
        Press Ctrl+C to exit
        INFO[0002] Streaming logs from pod: auth-depl-55968bd7fb-tqmk4 container: auth 
        INFO[0002] Streaming logs from pod: auth-depl-6f9c955cbf-hlv46 container: auth 
        DEBU[0002] Running command: [kubectl --context docker-desktop logs --since=2s -f auth-depl-55968bd7fb-tqmk4 -c auth --namespace default] 
        DEBU[0002] Running command: [kubectl --context docker-desktop logs --since=2s -f auth-depl-6f9c955cbf-hlv46 -c auth --namespace default] 
        DEBU[0002] Couldn't start notify trigger. Falling back to a polling trigger 
        WARN[0002] ./infra/k8s/* did not match any file         
        INFO[0002] files deleted: [/ticketing/infra/k8s/auth-depl.yaml] 
        Watching for changes...
        [auth] 
        [auth] > auth@1.0.0 start
        [auth] > ts-node-dev src/index.ts
        [auth] 
        [auth] [INFO] 12:17:36 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.3.5)
        DEBU[0003] Found dependencies for dockerfile: [{package.json /app true} {. /app true}] 
        DEBU[0003] Skipping excluded path: node_modules         
        INFO[0003] files deleted: [auth/src/index.ts]           
        INFO[0003] files added: [/ticketing/infra/k8s/auth-depl.yaml] 
        Syncing 1 files for ADMIN/auth:1c8c6c62510e86130d2c73973ebee34f6998c3ac7b845eefbcc533a13d8abe7d
        INFO[0003] Deleting files: map[auth/src/index.ts:[/app/src/index.ts]] from ADMIN/auth:1c8c6c62510e86130d2c73973ebee34f6998c3ac7b845eefbcc533a13d8abe7d 
        DEBU[0003] getting client config for kubeContext: ``    
        DEBU[0003] Running command: [kubectl --context docker-desktop exec auth-depl-6f9c955cbf-hlv46 --namespace default -c auth -- rm -rf -- /app/src/index.ts] 
        DEBU[0003] Running command: [kubectl --context docker-desktop exec auth-depl-55968bd7fb-tqmk4 --namespace default -c auth -- rm -rf -- /app/src/index.ts] 
        WARN[0003] Skipping deploy due to sync error: deleting files: starting command /usr/local/bin/kubectl --context docker-desktop exec auth-depl-6f9c955cbf-hlv46 --namespace default -c auth -- rm -rf -- /app/src/index.ts: pipe: too many open files 
        Watching for changes...
        DEBU[0004] Found dependencies for dockerfile: [{package.json /app true} {. /app true}] 
        DEBU[0004] Skipping excluded path: node_modules         
        DEBU[0004] stopping accessor                            
        DEBU[0004] stopping debugger                            
        Tags used in deployment:
         - ADMIN/auth -> ADMIN/auth:1c8c6c62510e86130d2c73973ebee34f6998c3ac7b845eefbcc533a13d8abe7d
        DEBU[0004] Local images can't be referenced by digest.
        They are tagged and referenced by a unique, local only, tag instead.
        See https://skaffold.dev/docs/pipeline-stages/taggers/#how-tagging-works 
        Starting deploy...
        DEBU[0004] getting client config for kubeContext: ``    
        DEBU[0004] Running command: [kubectl --context docker-desktop create --dry-run=client -oyaml -f /ticketing/infra/k8s/auth-depl.yaml] 
        WARN[0004] Skipping deploy due to error: kubectl create: starting command /usr/local/bin/kubectl --context docker-desktop create --dry-run=client -oyaml -f /ticketing/infra/k8s/auth-depl.yaml: pipe: too many open files 
        Watching for changes...
        DEBU[0005] Found dependencies for dockerfile: [{package.json /app true} {. /app true}] 
        DEBU[0005] Skipping excluded path: node_modules         
        DEBU[0006] Found dependencies for dockerfile: [{package.json /app true} {. /app true}] 
        DEBU[0006] Skipping excluded path: node_modules         
        DEBU[0007] Found dependencies for dockerfile: [{package.json /app true} {. /app true}] 
        DEBU[0007] Skipping excluded path: node_modules

I tried to increase file limit but error persists.

(If I delete folder node_modules everything works well and I have no errors, but is not a solution).

**Comment by demisx** [comment]
We've also ran into this issue where my colleague on Apple M1 laptop sees this error and I, who is on MacBook Pro (15-inch, 2018)/2.2 GHz 6-Core Intel Core i7, does not. This is what he sees after starting skaffold on  Apple M1:

```sh
WARN[3018] Ignoring changes: listing files: unable to evaluate build args: 
reading dockerfile: open /ismedia-nx-scaffold/choi/apps/api/Dockerfile: too many open files

# And predictably the re-depoy fails:

WARN[3091] Skipping deploy due to sync error: copying files: starting 
command /usr/local/bin/kubectl --context docker-desktop exec api-74bc656856-gxb48 
--namespace default -c api -i -- tar xmf - -C / --no-same-owner: fork/exec /usr/local/bin/kubectl: too many open files
```

```sh
$ lsof -n | awk '{ counts[$1]++} END { for(c in counts) { print counts[c], c}}' | sort -n | tail
...
2921 Google
24570 skaffold # <-- I don't even have skaffold reported on my Intel chip MacBook Pro.
```

The issue seems to go away if my colleague deletes the `node_modules/` directory. It's like skaffold is trying to watch the entire `node_modules/` on M1, but ignores it on the older Intel Chip version.

I've created a [sample repo](https://github.com/ChoiHoldings/6072-too-many-files-open-apple-m1) to recreate this issue. Please follow the instructions in `choi/README.md` to start the  project.

**Comment by demisx** [comment]
This is what we have to do on the M1 laptops to be able to use skaffold:

```sh
npm install
npm run skaffold # generate images
# ^C to exit skaffold
rm -rf node_modules
npm run skaffold
```

On non-M1 laptops, we can run skaffold with one command.

**Comment by sampullman** [comment]
I tried to look in to the sync/dockerignore code involved here, but didn't find anything obvious that would cause things to behave differently on my M1.

While poking around, I did notice that the issue resolves itself by using a local skaffold build instead of the official release.

**Comment by briandealwis** [comment]
> @sampullman: While poking around, I did notice that the issue resolves itself by using a local skaffold build instead of the official release.

Ah! 💡 We're currently cross-compiling Skaffold for darwin/arm64 but have to disable cgo (#5286) as we don't have the required headers and libraries available.  I've been meaning to retool our release process and this provides the impetus.

**Comment by resumerise** [comment]
> skaffold-darwin-amd64

With skaffold-darwin-amd64 it works like a charm. The error has gone. I would be great if arm64 version could be fixed.

**Comment by ryan-efendy** [comment]
@resumerise @cheslijones I inititally installed skaffold via homebrew. So I did `brew uninstall skaffold` and installed `skaffold-darwin-amd64` from https://skaffold.dev/docs/install/#managed-ide

```
# For macOS on x86_64 (amd64)
curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-darwin-amd64 && \
sudo install skaffold /usr/local/bin/
```

But I'm still getting the same error.
```
deployer cleanup:open /dev/null: too many open files
Cleaning up...
[wait-for-postgres]waiting for postgres
[wait-for-postgres]waiting for postgres
[wait-for-postgres]waiting for postgres
[wait-for-postgres]waiting for postgres
[wait-for-postgres]waiting for postgres
[wait-for-postgres]waiting for postgres
[wait-for-postgres]waiting for postgres
listing files: issue walking releases: open charts/my-app: too many open files
Skaffold exited with code 1.
```

How do I verify I have skaffold amd64 and nor arm64?
And any other suggestion/recommendation here?

**Comment by erulabs** [comment]
@ryan-efendy you can find out which build of skaffold you have with: `file $(which skaffold) && skaffold version`

Also, @briandealwis - I can confirm the issue goes away if I use a locally compiled version! (`v1.34.0-54-gbfc43b09a` works great while `v1.34.0` from the releases page does not).

For now I'll start recommending folks build their own copy of skaffold to get around this issue.

**Comment by ryan-efendy** [comment]
@erulabs what do you mean by
>  use a locally compiled version

I installed `skaffold` via brew
```
> file $(which skaffold) && skaffold version                                                                                              
/opt/homebrew/bin/skaffold: Mach-O 64-bit executable arm64
v1.34.0
```

Can you elaborate below. As in download the standalone binary vs. using package managers?
> For now I'll start recommending folks build their own copy of skaffold to get around this issue.

**Comment by erulabs** [comment]
@ryan-efendy - by "locally compiled version" I mean literally cloning the `https://github.com/GoogleContainerTools/skaffold` repository on an M1 Mac and running `make && make install` and using that skaffold binary directly, rather than using a downloaded one.  The bug seems to only exist in the cross-compiled version that is available for download from brew and/or the releases page here on github.

**Comment by iyosayi** [comment]
> @ryan-efendy - by "locally compiled version" I mean literally cloning the `https://github.com/GoogleContainerTools/skaffold` repository on an M1 Mac and running `make && make install` and using that skaffold binary directly, rather than using a downloaded one. The bug seems to only exist in the cross-compiled version that is available for download from brew and/or the releases page here on github.

This did the trick! After compiling the binaries myself, I just copied it over to `/usr/local/bin/skaffold` from my GOPATH binary location, and I can use it around from anywhere in my system by typing `skaffold` and it works! Thank you very much

**Comment by Mrhoho** [comment]
This is my workaround

`node-setup-daemon-set.yaml`
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-setup
  namespace: kube-system
  labels:
    k8s-app: node-setup
spec:
  selector:
    matchLabels:
      name: node-setup
  template:
    metadata:
      labels:
        name: node-setup
    spec:
      containers:
        - name: node-setup
          image: ubuntu
          command: ["/bin/sh", "-c"]
          args:
            [
              "/script/node-setup.sh; while true; do echo Sleeping && sleep 3600; done",
            ]
          volumeMounts:
            - name: node-setup-script
              mountPath: /script
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
      volumes:
        - name: node-setup-script
          configMap:
            name: node-setup-script
            defaultMode: 0755
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-setup-script
  namespace: kube-system
data:
  node-setup.sh: |
    #!/bin/bash
    # change the file-watcher max-count on each node to 524288

    # insert the new value into the system config
    sysctl -w fs.inotify.max_user_watches=524288
    sysctl -w fs.inotify.max_user_instances=512

    # check that the new value was applied
    cat /proc/sys/fs/inotify/max_user_watches
    cat /proc/sys/fs/inotify/max_user_instances
```
