### ISSUE TITLE
Buildkit secret references to credential files in developer home directory

### ISSUE THREAD

**Issue by alanjcastonguay** [GoogleContainerTools/skaffold#6079]
### Expected behavior

I am using BuildKit's fancy secret feature to build a docker container for a python app depending on a private python package. My local `pip.conf` contains credentials to a private registry holding that python package. Natively I can `pip install ...`. Or when building a docker container I can do something like this in a build script:

```sh
docker build --secret id=pipconf,src=$HOME/.pip/pip.conf .
```

I have not figured out how to port this to Skaffold.

### Actual behavior

I do not see a way to reference a path like `$HOME/.pip/pip.conf` in `skaffold.yaml` such that building the image picks up the secret.

### Information

- Skaffold version: v1.26.1
- Operating system: MacOS
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: example-dev-app
build:
  local:
    useBuildkit: true
    push: false
  artifacts:
  - image: example_dev_app
    docker:
      dockerfile: Dockerfile
      secret:
        id: pipconf
        src: "$HOME/.pip/pip.conf"
```

### Steps to reproduce the behavior

1. clone https://github.com/alanjcastonguay/skaffold-project-with-private-python-repo
2. `skaffold dev`
3. comment/alter docker secret reference in `skaffold.yaml`

```
could not parse secrets: [id=pipconf,src=$HOME/.pip/pip.conf]: failed to stat $HOME/.pip/pip.conf: stat $HOME/.pip/pip.conf: no such file or directory
```

**Comment by alanjcastonguay** [comment]
I see in https://skaffold.dev/docs/pipeline-stages/builders/docker/ and https://skaffold.dev/docs/environment/templating/ that passing in `buildArgs` works, though I think this is usage is discouraged, to avoid shipping credentials.

**Comment by alanjcastonguay** [comment]
I am not sure what the equivalent would be for the other builders (eg Kaniko). Create a kubernetes secret holding the credentials? How is this supposed to work in general?

**Comment by briandealwis** [comment]
Skaffold doesn't support expanding environment variables like `$HOME` in the `skaffold.yaml`.

For now you can use the [`custom` builder](https://skaffold.dev/docs/pipeline-stages/builders/custom/) and invoke docker directly.  Something like the following should do the trick:
```
build:
  artifacts:
  - image: skaffold-examples-buildx
    custom:
      buildCommand: docker build --secret id=pipconf,src=$HOME/.pip/pip.conf -t $IMAGE $BUILD_CONTEXT
      dependencies:
        dockerfile:
          path: Dockerfile
```

**Comment by briandealwis** [comment]
Maybe Skaffold could support expanding `~` notation for pathnames.

**Comment by alanjcastonguay** [comment]
> For now you can use the [`custom` builder](https://skaffold.dev/docs/pipeline-stages/builders/custom/) and invoke docker directly.

That's a good option, thanks.

**Comment by cm-trityum** [comment]
@briandealwis could you kindly help me to convert this skaffold cfg file to use the custom builder as you suggested?

```
apiVersion: skaffold/v2beta18
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    useBuildkit: true
    push: false
  artifacts:
    - image: test/comp1
      context: comp1
      docker:
        dockerfile: Dockerfile
        secret:
          id:   npmrc
          src: ~/.npmrc
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

```

I tried myself but I couldn't figure out a proper way to do it  :(
Thanks in advance
C.

**Comment by nkubala** [comment]
@cm-trityum the idea is to replace the `docker` builder with a `custom` builder that invokes `docker` directly. change your `build.artifacts` section to look like this:

```yaml
  artifacts:
  - image: test/comp1
    context: comp1
    custom:
      buildCommand: docker build --secret id=npmrc,src=~/.npmrc -t $IMAGE $BUILD_CONTEXT
      dependencies:
        dockerfile:
          path: Dockerfile
```
