### ISSUE TITLE
`skaffold render` sometimes exits early

### ISSUE THREAD

**Issue by ekuefler** [GoogleContainerTools/skaffold#6126]
### Expected behavior

`skaffold render` should finish its build and write its output file before exiting.

### Actual behavior

Rarely, the `skaffold` process appears to exit (with a 0 status code) while the build is still in progress, without writing any output.

### Information

- Skaffold version: v1.25.0
- Operating system: Linux (via Google Cloud Build)
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: environments

build:
  local:
    tryImportMissing: true
    push: true
  tagPolicy:
    inputDigest: {}
  artifacts:
  - image: gcr.io/devops-environments/manager
    docker:
      dockerfile: cmd/manager/Dockerfile
deploy:
  kubectl:
    remoteManifests:
    - environments-system:deployment/manager

profiles:
- name: release
  activation:
  - command: render
  build:
    local:
      push: true
      concurrency: 0
    tagPolicy:
      customTemplate:
        template: "{{.DATE}}-{{.GIT}}"
        components:
          - name: DATE
            dateTime:
              format: 20060102-150405
              timezone: America/Los_Angeles
          - name: GIT
            gitCommit:
              variant: AbbrevCommitSha
    artifacts:
    - image: gcr.io/devops-environments/clustergateway
      docker:
        dockerfile: cmd/clustergateway/Dockerfile
    - image: gcr.io/devops-environments/clusterreporter
      docker:
        dockerfile: cmd/clusterreporter/Dockerfile
    - image: gcr.io/devops-environments/manager
      docker:
        dockerfile: cmd/manager/Dockerfile
    - image: gcr.io/devops-environments/resourcebackup
      docker:
        dockerfile: cmd/resourcebackup/Dockerfile
    - image: gcr.io/devops-environments/sshpasswordchecker
      docker:
        dockerfile: cmd/sshpasswordchecker/Dockerfile
    - image: gcr.io/devops-environments/volumereclaimer
      docker:
        dockerfile: cmd/volumereclaimer/Dockerfile
    - image: gcr.io/devops-environments/webhookserver
      docker:
        dockerfile: cmd/webhookserver/Dockerfile
  deploy:
    kubectl: {}
    kustomize:
      paths:
      - config/release
```

### Notes

We're observing this behavior on Google Cloud Build. It's also possible that GCB is doing something wrong, but I've only ever seen this issue when running Skaffold, so Skaffold seems like the most likely culprit. We run render with this command:

```
skaffold render --digest-source=local --loud --output=release.yaml
```

Here are output logs from a failed and a successful build (internal links):

* Failure: https://paste.googleplex.com/6400242380439552
* Success: https://paste.googleplex.com/6585540255154176

Note that in the failure case, the process cuts off in the middle of building one of the containers. Maybe an issue with `concurrency: 0`?
