### ISSUE TITLE
kubectl URL manifests aren't working on dependencies

### ISSUE THREAD

**Issue by levtomer66** [GoogleContainerTools/skaffold#6142]
### Expected behavior
Successfully deploy URL manifests

### Actual behavior
invalid skaffold config: skaffold config named "/Users/USERNAME/dep1/skaffold.yaml" referenced file "/Users/USERNAME/dep1/https:/exmaple.com/deployer.yaml" that could not be found. Verify that file "/Users/USERNAME/dep1/https:/exmaple.com/deployer.yaml" referenced in config "/Users/USERNAME/dep1/skaffold.yaml" exists and the path and naming are correct.
### Information

- Skaffold version: v.1.27.0
- Operating system: OSx
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta19
kind: Config
requires:
- path: ../dep1/skaffold.yaml
build:
  artifacts:
  - image: myimage
    kaniko:
      cache: {}
      verbosity: info
  - image: helm-deployer-myimage
    custom:
      buildCommand: ./build.sh
    requires:
    - image: myimage
      alias: BUILT_IMAGE
  tagPolicy:
    gitCommit: {}
  cluster:
    dockerConfig:
      secretName: mysecret
deploy:
  kubectl:
    manifests:
    - https://exmaple.com/deployer.yaml

```

### Steps to reproduce the behavior

1. Create 2 skaffold yaml manifests
2. In first manifest specify a requirement (dependency) to the seconds one 
3. on seconds manifest specify deploy.kubectl.manifests to URL manifest

invalid skaffold config: skaffold config named "/Users/USERNAME/dep1/skaffold.yaml" referenced file "/Users/USERNAME/dep1/https:/exmaple.com/deployer.yaml" that could not be found. Verify that file "/Users/USERNAME/dep1/https:/exmaple.com/deployer.yaml" referenced in config "/Users/USERNAME/dep1/skaffold.yaml" exists and the path and naming are correct.
