### ISSUE TITLE
Trying to use pipeline line but the same image is being deployed to each pod (two app project, different images)

### ISSUE THREAD

**Issue by martyphee** [GoogleContainerTools/skaffold#6173]
### Expected behaviour
Each app is started with the correct image

### Actual behaviour
Apps are started with the same image

### Information

- Skaffold version: 1.27
- Operating system: macOS, 10.15.7
- Installed via: brew

From the kubernetes UI
![image](https://user-images.githubusercontent.com/754870/125059737-9213e300-e0a3-11eb-8899-7f3c97ae539d.png)

Root skaffold file
```yaml
apiVersion: skaffold/v2beta12
kind: Config
requires:
  - path: ./blog-api/skaffold.yaml
  - path: ./blog-web/skaffold.yaml
```

./blog-api/skaffold.yaml
```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: blog-api
build:
  tagPolicy:
    envTemplate: 
      template: "{{.IMAGE_NAME}}:{{.DIGEST}}"
  local:
    useBuildkit: true
  artifacts:
    - image: blog-api
      docker:
        dockerfile: docker/Dockerfile
        target: dev
        buildArgs:
          CODEARTIFACT_AUTH_TOKEN: "{{.CODEARTIFACT_AUTH_TOKEN}}"

deploy:
  helm:
    releases:
    - name: blog-api
      chartPath: charts/blog-api
      setValueTemplates:
        dockerImageOverride: "{{.DIGEST}}"
        image.pullPolicy: IfNotPresent
      valuesFiles:
        - charts/blog-api/values/local.yaml
portForward:
  - resourceType: Service
    resourceName: blog-api
    namespace: default
    port: 8000
    localPort: 8000
```

./blog-web/skaffold.yaml
````yaml
apiVersion: skaffold/v2beta12
kind: Config
build:
  tagPolicy:
    envTemplate: 
      template: "{{.IMAGE_NAME}}:{{.DIGEST}}"
  local:
    useBuildkit: true
  artifacts:
    - image: blog-web
      docker:
        dockerfile: docker/Dockerfile
        target: blog
deploy:
  helm:
    releases:
    - name: blog-web
      chartPath: charts/blog-web
      setValueTemplates:
        dockerImageOverride: "{{.DIGEST}}"
        image.pullPolicy: IfNotPresent
      valuesFiles:
        - charts/blog-web/values/local.yaml
portForward:
  - resourceType: Service
    resourceName: blog-web
    namespace: default
    port: 3000
    localPort: 3000
```

### Steps to reproduce the behavior
If nothing is obvious I'll try a reproducible repo.

I can provide the full logs but if you look at this deployment under containers you can see the wrong image being used. We're using templates for our charts and it seems to be using the image from the first include in the skaffold pipeline
```
# Source: blog-web/templates/web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-web-web
  labels:
    helm.sh/chart: blog-web-0.1.0
    app.kubernetes.io/name: blog-web
    app.kubernetes.io/instance: blog-web
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
    tags.datadoghq.com/environment: development
    tags.datadoghq.com/version: "latest"
    tags.datadoghq.com/service: blog-web.web
    app.kubernetes.io/component: web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: blog-web
      app.kubernetes.io/instance: blog-web
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blog-web
        app.kubernetes.io/instance: blog-web
        tags.datadoghq.com/environment: development
        tags.datadoghq.com/version: "latest"
        tags.datadoghq.com/service: blog-web.web
        app.kubernetes.io/component: web
      annotations:
    spec:
      serviceAccountName: blog-web
      securityContext:
        fsGroup: 65534
      containers:
        **- name: blog-web
          image: blog-api:52c324df9fcebe98734ffcf0aee2a6b98f6e64ec252a549d3280e8142088dff2**
          imagePullPolicy: IfNotPresent
          env:
          # This is so we can explicitly order the spinning up of the pods
          # post IAM role creation via the IRSA Crossplane composition
```

**Comment by briandealwis** [comment]
Please try running with `-vdebug` and attach the output log after removing any identifiable information.  This will show the `helm` command-lines being run with the various variable substitutions.  Note that as you're not specifying `artifactOverrides`, _Skaffold will not be providing the image names to Helm_.  The `blog-api` image name is coming from either your values file, is embedded within your template, or is coming from your environment.

Is it possible you have an environment variable IMAGE_NAME?  

Note that the use of `{{.IMAGE_NAME}}` in the `envTemplate` is deprecated and should be avoided — and is unnecessary in your case.

If you can't figure it out from the above, we'll need a reproducible example.

**Comment by wizardels** [comment]
So I think the problem here is if we have it in one file like so:
```
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: blog-app
build:
  local:
    useBuildkit: true
  artifacts:
    - image: blog-api
      context: blog-api/
      docker:
        dockerfile: docker/Dockerfile
        target: dev
        buildArgs:
          CODEARTIFACT_AUTH_TOKEN: "{{.CODEARTIFACT_AUTH_TOKEN}}"

deploy:
  helm:
    releases:
      - name: blog-api
        chartPath: blog-api/charts/blog-api
        setValueTemplates:
          dockerImageOverride: "{{.DIGEST}}"
          image.pullPolicy: IfNotPresent
        valuesFiles:
          - blog-api/charts/blog-api/values/local.yaml

portForward:
  - resourceType: Service
    resourceName: blog-api
    namespace: default
    port: 8000
    localPort: 8000

---
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: blog-web
build:
  local:
    useBuildkit: true
  artifacts:
    - image: blog-web
      context: blog-web/
      docker:
        dockerfile: docker/Dockerfile
        target: blog

deploy:
  helm:
    releases:
      - name: blog-web
        chartPath: blog-web/charts/blog-web
        setValueTemplates:
          dockerImageOverride: "{{.DIGEST}}"
          image.pullPolicy: IfNotPresent
        valuesFiles:
          - blog-web/charts/blog-web/values/local.yaml

portForward:
  - resourceType: Service
    resourceName: blog-web
    namespace: default
    port: 3000
    localPort: 3000

```

The `{{.DIGEST}}` gets used for both deployments. Is there any workaround for this?

**Comment by gsquared94** [comment]
If there are multiple images being built then the variables become  `{{.IMAGE}}`, `{{.IMAGE2}}`,`{{.DIGEST}}`, `{{.DIGEST2}}`, etc. 
I think this is unintuitive and the order of artifacts to figure out the numbering isn't stable either. I'll create another bug for that.

The correct way to do this would be to follow the approach suggested in the [documentation](https://skaffold.dev/docs/pipeline-stages/deployers/helm/)

**Comment by briandealwis** [comment]
From the evidence presented so far, the most plausible explanation is that your charts are misconfigured and your `blog-web-web` deployment is mistakenly referencing the `blob-api` container:

- Your `skaffold.yaml` does not specify a tag-policy.  Skaffold will build images and tag them using a tag derived from the gitCommit tag, which is unlikely to match what you're specifying with `{{.DIGEST}}`.  
- Your `skaffold.yaml` is not using `artifactOverrides`.  This is the mechanism by which Skaffold feeds in details on built images to Helm, such as the image tags.

Your configuration might work if you were using Skaffold's `--tag $DIGEST` command-line flag to override the tag to be used.  That is a very unconventional setup, and given that you're encountering issues I'm guessing this isn't the case.

Next steps:
1. Please review the docs on [configuring Skaffold for Helm](https://skaffold.dev/docs/pipeline-stages/deployers/helm/#configuring-your-helm-project-with-skaffold) to understand about `artifactOverrides`.
2. Please look at the output of running `skaffold xxx -vdebug` and look at the `helm` command-lines being called and the rendered manifests.

If you're still having issues, please attach your logs, and optionally your charts, so that we can see what's going on.

**Comment by SuperCipher** [comment]
In my case, I solved it by splitting an application into multiple charts, multiple releases, and multiple skaffold files
by using skaffold multi config feature
``` yaml
apiVersion: skaffold/v2beta21
kind: Config
requires:
- path: ./skaffold1.yaml
- path: ./skaffold2.yaml
```
