### ISSUE TITLE
Env param is not passed to kaniko pod.

### ISSUE THREAD

**Issue by dimovnike** [GoogleContainerTools/skaffold#6174]
Env param is not passed to kaniko pod.
To debug this i used a modified kaniko image that prints env vars before the build. The image is working otherwise when used directly with a cloudbuild.yaml

### Expected behavior

The vars must be passed to the pod.

### Actual behavior

The vars are not passed to the pod.

### Information

- Skaffold version: v1.27.0
- Operating system: ubuntu 20.04
- Installed via: github releases
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: service1
build:
  googleCloudBuild:
    kanikoImage: custom kaniko image that prints env vars before the build
  artifacts:
    - image: service1
      context: service1
      kaniko: 
        env:
          - name: VAR1
            value: VAL1
        buildArgs:
          GIT_USER: git-user
```
I tested directly with the following cloudbuild.yaml and it works as expected:

```yaml
steps:
- name: custom kaniko image that prints env vars before the build
  args:
  - --destination=...
  - --build-arg 
  - GIT_USER=git-user
  env:
    - VAR1=VAL1

```

The buildArgs are working correctly but env vars are not passed.
