### ISSUE TITLE
Passing availableSecrets and secretEnv to kaniko in GCB

### ISSUE THREAD

**Issue by dimovnike** [GoogleContainerTools/skaffold#6199]
When building with GCB directly we can instrruct GCB to mount a secret in the kaniko pod. This is achieved by using availableSecrets and secretEnv keys in yaml. Is there a way to pass these directly from skaffold?

below is an example of an buildconfig.yaml:

```yaml
steps:
- name: 'gcr.io/kaniko/kaniko-executor:latest'
  args:
  - --destination=...
  secretEnv: ['SSH_PRIVATE_KEY']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/private-key-secret-name/versions/latest
    env: 'SSH_PRIVATE_KEY'
```
