### ISSUE TITLE
Skaffold not respecting Kustomize patchesStrategicMerge even though it appears fine in straight kustomize build

### ISSUE THREAD

**Issue by HariSekhon** [GoogleContainerTools/skaffold#6200]
### Expected behavior

Apply Kubernetes manifests as `kustomize build` shows, including the service account annotation added via patchesStrategicMerge in `kustomization.yaml` and visible in `kustomize build` output.

### Actual behavior

Doesn't respect `kustomization.yaml` patchesStrategicMerge on the serviceaccount annotation for GKE workload identity integration.

If I put the annotation in the `../base/` yaml then Skaffold does apply it correctly, but if it's in a patchesStrategicMerge in the `overlay/dev/kustomization.yaml` (which shows up in a straight `kustomize build` output) then for some reason Skaffold misses it.

If I'd applied the k8s manifest directly from the dev overlay directory with `kustomize build | kubectl apply -f -` then it works.

If I then run `skaffold dev` again from the dev overlay directory, it wipes out the annotation!

### Information

- Skaffold version: v1.27.0
- Operating system: macOS
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: www
deploy:
  statusCheckDeadlineSeconds: 500  # webapp takes ages to pre-load cache and pass healthcheck
  kubeContext: my-k8s-context
  kustomize:
    paths:
      - .
      - ../base
```

overlay/dev/kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp
bases:
- ../base
...
patchesStrategicMerge:
- ./www-serviceaccount.patch.yaml
```

www-serviceaccount.patch.yaml:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: www
  namespace: myapp
  annotations:
    iam.gke.io/gcp-service-account: www-blah@myproject.iam.gserviceaccount.com
```

### Steps to reproduce the behavior

`kustomize build` shows the annotation correctly, and if you pipe to `kubectl apply -f -` the service account gets the annotation.

```
$ kustomize build
...
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: www-blah@myproject.iam.gserviceaccount.com
  name: www
  namespace: myapp
...
```

```
$ kustomize build | kubectl apply -f -
serviceaccount/www-php configured
configmap/www configured
deployment.apps/www configured

$ kubectl describe sa www
Name:                www
Namespace:           myapp
Labels:              <none>
Annotations:         iam.gke.io/gcp-service-account: www-blah@myproject.iam.gserviceaccount.com
...
```

Skaffold applies it but somehow misses the patch the `kustomize build` uses:
```
$ skaffold dev  --cleanup=false
Listing files to watch...
Generating tags...
Checking cache...
Starting test...
Tags used in deployment:
Starting deploy...
 - serviceaccount/www configured
 - configmap/www configured
 - deployment.apps/www configured
 - serviceaccount/www unchanged
 - deployment.apps/www unchanged
Waiting for deployments to stabilize...
...
```

Here the annotation is stripped out to `<none>`, even though it was clearly in the `kustomize build` output and applied correctly using a standard `kubectl apply`!
```
$ kubectl describe sa www
Name:                www
Namespace:           myapp
Labels:              app.kubernetes.io/managed-by=skaffold
                     skaffold.dev/run-id=d74be138-ee1e-42bb-b475-925cee6d37bc
Annotations:         <none>
...
```

I don't really understand how Skaffold can miss this as I thought it just called `kustomize build` the same as I do locally...

**Comment by HariSekhon** [comment]
I think this works if I switch the paths in `skaffold.yaml`, as I need to watch both directories for changes, if I change the base, I was `skaffold dev` to re-apply it:

skaffold.yaml:
```
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: www
deploy:
  statusCheckDeadlineSeconds: 500  # webapp takes ages to pre-load cache and pass healthcheck
  kubeContext: my-k8s-context
  kustomize:
    paths:
      - ../base # swapped paths to allow local overlay to take precedence, although this is not documented?
      - .
```
