### ISSUE TITLE
Helm template variable naming strategy neither intuitive nor stable

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#6207]
Related: https://github.com/GoogleContainerTools/skaffold/issues/6173
Skaffold creates environment variables `IMAGE_NAME`, `IMAGE_TAG`, `IMAGE_REPO`, `DIGEST`, and `IMAGE` that can be templated in various places in the `helm` deploy stanza.

If there are multiple images being built then it names them `IMAGE_NAME`, `IMAGE_NAME2`, `IMAGE_NAME3`, etc.
These numbers are not assigned stably from one run to the next. Also it becomes quickly unintuitive for projects using multiple configs which artifact corresponds to which number.

**Comment by gsquared94** [comment]
One approach could be to prefix template variables with the `artifact name`.
For the `skaffold.yaml` file:

```yaml
apiVersion: skaffold/vX
kind: Config
build:
  artifacts:
    - image: foo
    - image: bar
deploy:
  helm:
    releases:
    - name:bar
      setValueTemplates:
        tag: "{{foo.IMAGE_TAG}}"
        tag: "{{foo.DIGEST}}"
        tag: "{{foo.IMAGE_TAG}}"
```

This change for `helm` would need to be made here:
https://github.com/GoogleContainerTools/skaffold/blob/27271dfcaab56c38ecf41f4b7158101d44c454b6/pkg/skaffold/deploy/helm/args.go#L67-L76
