### ISSUE TITLE
Skaffold releases - `.sha256` files contain `out/` prefix

### ISSUE THREAD

**Issue by headcr4sh** [GoogleContainerTools/skaffold#6217]
### Expected behavior

When downloading a Skaffold release from and the corresponding `SHA256` checksum file from [GitHub](https://github.com/GoogleContainerTools/skaffold/releases), I expect no `out/` prefix in the checksum files.

### Actual behavior

The `SHA256` checksum files on the release page assume that the file to be checked is located in a (relative) sub-folder called `out`.

### Information

The contents of a current checksum file (e.g. [`skaffold-darwin-amd64.sha256`](https://github.com/GoogleContainerTools/skaffold/releases/download/v1.28.0/skaffold-darwin-amd64.sha256)) looks like this:

```
d5271f04c0ebcabbbb24a5ee7e34986abcbea13156cb84b7e3faa3285a59d296  out/skaffold-darwin-amd64
```

### Steps to reproduce the behavior

I am using `Ansible` to automate my Skaffold installation. The following step in my role fails:

```yaml
- name: Download skaffold release
  ansible.builtin.get_url:
    url: https://github.com/GoogleContainerTools/skaffold/releases/download/v{{ skaffold_version }}/skaffold-{{ skaffold_os }}-{{ skaffold_architecture }}
    dest: "{{ skaffold_artifact_cache_dir.path }}"
    # TODO The checksum of the artifacts contains an out/-prefix for all filenames, which causes the check to fail.
    # Therefore, the remote checksum cannot be used at the moment. :-(
    checksum: sha256:https://github.com/GoogleContainerTools/skaffold/releases/download/v{{ skaffold_version }}/skaffold-{{ skaffold_os }}-{{ skaffold_architecture }}.sha256
    mode: '0644'
  register: skaffold_release_download
```

### Suggested fix

Strip the `out/` prefix in the checksum files to make it easier to automate Skaffold installations with Ansible or other tools that use the checksum file to determine if a cached download can be reused.
