### ISSUE TITLE
Skaffold Dev Mode sync appears broken in v1.28.0

### ISSUE THREAD

**Issue by DGollings** [GoogleContainerTools/skaffold#6219]
### Expected behavior

Edit a file, file gets synced

### Actual behavior

Very little, simply doesnt sync. Verbose didn't help
`Skipping deploy due to sync error: copying files: didn't sync any files `
(nothing to do with namespaces as mentioned in other issues)

(a hint, although I assume DEVMODE should handle that: manual kubectl cp fails with a permission denied as buildpacks are afaik read only)

### Information

- Skaffold version:v1.28.0
- Operating system: PopOS 21.04
- Installed via: curl

### Steps to reproduce the behavior

I assume try using devmode in v1.28.0 vs v1.27.0

### Workound
Downgrade to v1.27.0

**Comment by erulabs** [comment]
Same situation - both sync and log tailing appears broken in 1.28.0

For example, the config:
```
apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
    - image: erulabs/example
      context: .
      sync:
        manual:
          - src: "**/*"
            dest: .
      docker:
        target: development
deploy:
  kustomize:
    paths:
      - k8s/dev
portForward:
  - resourceType: Service
    resourceName: api
    port: 443
    localPort: 4000
    address: 0.0.0.0
```

works fine in 1.27, but broken in 1.28 (same config except schema version changed to skaffold/v2beta19 when using 1.28). Both log tailing and file synching.
