### ISSUE TITLE
Handling multi-folder namespace creation (+ easy reproduction)

### ISSUE THREAD

**Issue by michielswaanen** [GoogleContainerTools/skaffold#6259]
### Expected behavior

Once I run `skaffold dev` all resources should be created and added to the custom namespace `application-local`.

### Actual behavior

Like you can see on the screenshot, the namespace gets created but not recognized by some other resources.

> ❗  Note that the resource who are in the same directory as the namespace resource file (`namespace.yml`) do get created.

![image](https://user-images.githubusercontent.com/32015956/126435795-6534dbc1-2580-4a1d-8eea-5c6ef349499d.png)

Now I must run `skaffol dev` for a second time to correctly start all other resources, because the namespace was successfully created during the first run:
![image](https://user-images.githubusercontent.com/32015956/126442238-1b698b8d-722d-4f0f-a2b9-cc92ef42aed8.png)

### Information

My folder structure
```
📦application
 ┣ 📂.infrastructure
 ┃ ┣ 📂local
 ┃ ┃ ┣ 📂networking
 ┃ ┃ ┃ ┣ 📜client-ingress.yml
 ┃ ┃ ┃ ┗ 📜server-ingress.yml
 ┃ ┃ ┗ 📜namespace.yml
 ┣ 📂client
 ┃ ┣ 📂.infrastructure
 ┃ ┃ ┣ 📂local
 ┃ ┃ ┃ ┗ 📂client
 ┃ ┃ ┃ ┃ ┣ 📜client-deployment.yml
 ┃ ┃ ┃ ┃ ┗ 📜client-service.yml
 ┣ 📂server
 ┃ ┣ 📂.infrastructure
 ┃ ┃ ┣ 📂local
 ┃ ┃ ┃ ┣ 📂database
 ┃ ┃ ┃ ┃ ┣ 📜postgres-config.yml
 ┃ ┃ ┃ ┃ ┣ 📜postgres-deployment.yml
 ┃ ┃ ┃ ┃ ┣ 📜postgres-service.yml
 ┃ ┃ ┃ ┃ ┗ 📜postgres-volume.yml
 ┃ ┃ ┃ ┗ 📂server
 ┃ ┃ ┃ ┃ ┣ 📜server-deployment.yml
 ┃ ┃ ┃ ┃ ┗ 📜server-service.yml
 ┗ 📜skaffold.yaml

```

- Skaffold version: v1.27.0
- Operating system: Windows 10 Pro (20H2)
- Installed via: Chocolatey 
- Contents:

skaffold.yml
```yaml
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: xxxx-local
build:
  local:
    push: false
  artifacts:
  - image: ghcr.io/xxxx/server
    context: server
    docker:
      dockerfile: Dockerfile.localhost
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  - image: ghcr.io/xxxx/client
    context: client
    docker:
      dockerfile: Dockerfile.local
    sync:
      infer: ["**/*"] # Instant updates
deploy:
  kubectl:
    manifests:
    - server/.infrastructure/local/*
    - client/.infrastructure/local/*
    - .infrastructure/local/*
```

.infrastructure/local/namespace.yml
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: application-local
```

.infrastructure/local/networking/client-ingress.yml
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service-client
  namespace: application-local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: app.xxxx.localhost
      http:
        paths:
          - path: '/'
            pathType: 'Prefix'
            backend:
              service:
                name: client-service
                port:
                  name: client-port
```
.infrastructure/local/networking/server-ingress.yml
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service-server
  namespace: application-local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: api.xxxx.localhost
      http:
        paths:
          - path: '/'
            pathType: 'Prefix'
            backend:
              service:
                name: server-service
                port:
                  name: server-port
```
.infrastructure/client/local/client-deployment.yml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: application-local
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: xxxx-client-local
  template:
    metadata:
      labels:
        app: xxxx-client-local
    spec:
      containers:
        - name: client-local
          image: ghcr.io/xxxx/client:development
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: github-registry-credentials # Kubernetes Secret
```
.infrastructure/client/local/client-service.yml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: application-local
spec:
  type: ClusterIP
  selector:
    app: xxxx-client-local
  ports:
    - name: client-port
      protocol: TCP
      port: 80
      targetPort: 80
```
.infrastructure/client/local/server-service.yml & .infrastructure/client/local/server-deployment.yml
```
Almost identical to the resource files above
```

### Steps to reproduce the behavior

My guess is that Skaffold isn't able to handle the start-up of a multi-folder resource file setup when the creation of a namespace is involved.

Clonable repository:
```bash
# Make sure to read the README first
# Once cloned run skaffold dev
https://github.com/michielswaanen/skaffold-debug
```

**Comment by briandealwis** [comment]
Try ordering your resources so that `.infrastructure/local/namespace.yml` comes first: see #2645 for details.
```
deploy:
  kubectl:
    manifests:
    - .infrastructure/local/*
    - server/.infrastructure/local/*
    - client/.infrastructure/local/*
```
