### ISSUE TITLE
How to deploy before the requirements

### ISSUE THREAD

**Issue by vk496** [GoogleContainerTools/skaffold#6260]
Hello, I would like to know if I could deploy helm releases before the requirements. My problem is that my multiple requirements depends on a running Traefik pod to auto configure themselves.

### Expected behavior
Deploy helm chart (traefik) before the requirements

### Actual behavior
Requirement are deployed first

### Information

- Skaffold version: v1.25.0
- Operating system: Linux 5.10
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta13
kind: Config
requires:
  - configs: ["service-A"]
    path: ./service-A/skaffold.yaml
  - configs: ["service-B"]
    path: ./service-B/skaffold.yaml
  - configs: ["frontend"]
    path: ./frontend/skaffold.yaml
deploy:
  helm:
    releases:
      - name: traefik
        namespace: traefik-v2
        createNamespace: true
        remoteChart: traefik
        repo: https://helm.traefik.io/traefik
    flags:
      upgrade:
        - --install
```
