### ISSUE TITLE
ContainerHook  can not be resolved error

### ISSUE THREAD

**Issue by demisx** [GoogleContainerTools/skaffold#6271]
I've noticed that `skaffold.yaml` throws this error now in VS Code on the first line `apiVersion: skaffold/v2beta19`: 

```
$ref '/definitions/ContainerHook' in 'https://raw.githubusercontent.com/GoogleContainerTools/skaffold/master/docs/content/en/schemas/v2beta19.json' 
can not be resolved.
```

- Skaffold version: v1.28.1
- Operating system: MacOs Big Sur 11.4
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta19
kind: Config
build:
  local:
    useBuildkit: true
    push: false
deploy:
  kubeContext: docker-desktop
  helm:
    releases:
      - name: nginx-ingress
        chartPath: stable/nginx-ingress
        remote: true
        version: 1.37.0
        overrides:
          controller:
            replicaCount: 1
            publishService:
              enabled: true
            service:
              type: LoadBalancer
              externalTrafficPolicy: Local
    flags:
      install:
        - '--create-namespace'
profiles:
  - name: lead-api
    deploy:
      kubeContext: docker-desktop
      kubectl:
        manifests:
          - tools/k8s/dev/ws/ws.k8s-namespace.yaml
          - tools/k8s/dev/ws/lead-api.k8s-config.yaml
          - tools/k8s/dev/ws/lead-api.k8s-deployment.yaml
          - tools/k8s/dev/ws/lead-api.k8s-service.yaml
          - tools/k8s/dev/ws/lead-api.k8s-ingress.yaml
    build:
      # local:
      #   useBuildkit: true
      artifacts:
        - image: lead-api.dev
          context: .
          sync:
            manual:
              - src: 'apps/lead-api/src/**/*'
                dest: '/usr/src'
              - src: 'libs/lead-api/*/src/**/*'
                dest: '/usr/src'
              - src: 'libs/shared/*/src/**/*'
                dest: '/usr/src'
              - src: '**/README.md'
                dest: '/usr/src'
          docker:
            dockerfile: apps/lead-api/Dockerfile
            target: dev
```
