### ISSUE TITLE
logs are not printed with --tail when kubeContext is set and its different from current-context 

### ISSUE THREAD

**Issue by weltonrodrigo** [GoogleContainerTools/skaffold#6336]
### Expected behavior

Running ```skaffold run --tail``` with `deploy.kubeContext` set should print logs after deployment stabilization. 

### Actual behavior
No log is printed.

```shell
skaffold run --tail -v debug
```

```
Starting deploy...
DEBU[0008] getting client config for kubeContext: ``    
DEBU[0009] Running command: [kubectl version --client -ojson] 
DEBU[0009] Command output: [{
  "clientVersion": {
    "major": "1",
    "minor": "21",
    "gitVersion": "v1.21.2",
    "gitCommit": "092fbfbf53427de67cac1e9fa54aaa09a28371d7",
    "gitTreeState": "clean",
    "buildDate": "2021-06-16T12:52:14Z",
    "goVersion": "go1.16.5",
    "compiler": "gc",
    "platform": "darwin/amd64"
  }
}
] 
DEBU[0009] Running command: [kustomize build kubernetes] 
DEBU[0010] Command output: [REDACTED] 
DEBU[0010] manifests with tagged images: apiVersion: v1
[REDACTED]
DEBU[0010] manifests with labels apiVersion: v1
  [REDACTED]
DEBU[0010] Running command: [kubectl --context foobar --namespace my_namespace get -f - --ignore-not-found -ojson] 
DEBU[0010] Command output: [REDACTED]
DEBU[0010] 2 manifests to deploy. 2 are updated or new  
DEBU[0010] Running command: [kubectl --context foobar --namespace my_namespace apply -f -] 
 - configmap/ajeitadin-config-d8k4696hch configured
 - deployment.apps/nifi-ajeitadin configured
INFO[0011] Deploy completed in 2.993 seconds            
Waiting for deployments to stabilize...
DEBU[0011] getting client config for kubeContext: ``    
Deployments stabilized in 95.335945ms
DEBU[0011] getting client config for kubeContext: ``    
Press Ctrl+C to exit
```
### Information

- Skaffold version:  v1.28.1
- Operating system: Macos 11.4
- Installed via: homebrew
- Contents of skaffold.yaml: v1.28.1

```yaml
apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: redacted
build:
  artifacts:
  - image: image:tag
    docker:
      dockerfile: Dockerfile
deploy:
  kubeContext: foobar
  kustomize:
    paths:
    - kubernetes
    defaultNamespace: my_namespace

```

### Steps to reproduce the behavior

```shell
kubectl config current-context
# bar
```

```shell
skaffold run --tail -v debug
```

# Note

`skaffold run --tail --kube-context foobar` works.
