### ISSUE TITLE
`dependencies.ignore` should support ** globs

### ISSUE THREAD

**Issue by misterikkit** [GoogleContainerTools/skaffold#6350]
### Expected behavior
Specifying an ignore pattern like `"**/zz_generated*"` should ignore any files whose name begins with `zz_generated` anywhere in my source tree.

### Actual behavior
Skaffold uses `filepath.Match` which supports single-segment globs `*` but not `**` globs that would match any number of segments. The result is that I must write ignore rules that look like this:

```yaml
build:
  artifacts:
    - image: foo
      context: "."
      custom:
        buildCommand: make package PROJECT_VERSION="${IMAGE##*:}"
        dependencies:
          paths: ["."]
          ignore:
            # protobuf generated code
            - "*/*.pb.go"
            - "*/*/*.pb.go"
            - "*/*/*/*.pb.go"
            # gomock generated code
            - "*/mock"
            - "*/*/mock"
            # gomock temporary files
            - "*/gomock*"
            - "*/*/gomock*"
            # controller-gen generated code
            - "*/*/zz_generated*"
            - "*/*/*/zz_generated*"
            - "*/*/*/*/zz_generated*"
```

### Information

- Skaffold version: 1.27.0
- Operating system: Ubuntu 16.04
- Installed via: Cloud Code 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta15
kind: Config
build:
  artifacts:
    - image: foo
      context: "."
      custom:
        buildCommand: make package PROJECT_VERSION="${IMAGE##*:}"
        dependencies:
          paths: ["."]
          ignore:
            # protobuf generated code
            - "*/*.pb.go"
            - "*/*/*.pb.go"
            - "*/*/*/*.pb.go"
            # gomock generated code
            - "*/mock"
            - "*/*/mock"
            # gomock temporary files
            - "*/gomock*"
            - "*/*/gomock*"
            # controller-gen generated code
            - "*/*/zz_generated*"
            - "*/*/*/zz_generated*"
            - "*/*/*/*/zz_generated*"
```
