### ISSUE TITLE
`skaffold deploy` does not work with dockerhub library images

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#637]
If a DockerHub library image is used without the prefix (index.docker.io/library), then it won't correctly be matched and replaced by `skaffold deploy`, since the YAML will still read `busybox` rather than `index.docker.io/library/busybox`.

```
apps/v1
kind: Deployment
metadata:
  labels:
    app: kustomize-test
  name: kustomize-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-test
  template:
    metadata:
      labels:
        app: kustomize-test
    spec:
      containers:
      - image: busybox
        name: kustomize-test
```

`skaffold deploy --image busybox:v1`
