### ISSUE TITLE
two way binding not work

### ISSUE THREAD

**Issue by Spartaques** [GoogleContainerTools/skaffold#6400]
I'm using skaffold for local development. 

![image](https://user-images.githubusercontent.com/29341175/128921154-246cda0e-9c7e-4213-892d-90d550d657d1.png)

I expect that vendor files will be synced into local filesystem. 

### Expected behavior

I expect that it works the same as with docker-compose and mount functionality.

### Actual behavior

It works only one way, from local filesystem to Docker container.  When i change smth in docker container in not reflect into local filesystem.

### Information

skaffold version v1.29.0

```yaml
apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
    - image: riup-core
      context: ./services/riup_core
      docker:
        dockerfile: Dockerfile.local
      sync:
        infer: ["**/*"]
#    - image: notificator
#      context: ./services/riup_notificator
#      docker:
#        dockerfile: Dockerfile.local
#      sync:
#        infer: ["**/*"]
#    - image: riup-core-jobs
#      context: ./services/riup_core
#      docker:
#        dockerfile: Dockerfile.local.jobs
#      sync:
#        infer: ["**/*"]
#    - image: events
#      context: ./services/riup_events
#      docker:
#        dockerfile: Dockerfile.local
#      sync:
#        infer: ["**/*"]
#    - image: tracker
#      context: ./services/riup_tracker
#      docker:
#        dockerfile: Dockerfile.local
#      sync:
#        infer: ["**/*"]
    - image: vuecabinet
      context: ./services/riup_vuecabinet
      docker:
        dockerfile: Dockerfile.local
      sync:
        infer: ["**/*"]
deploy:
  helm:
    releases:
#      - name: db
#        chartPath: helm/charts/db
      - name: core-api
        chartPath: helm/charts/core-api
        artifactOverrides:
          image: riup-core
#      - name: notificator
#        chartPath: helm/charts/notificator
#        artifactOverrides:
#          image: notificator
#      - name: core-jobs
#        chartPath: helm/charts/core-jobs
#        artifactOverrides:
#          image: riup-core-jobs
#      - name: events
#        chartPath: helm/charts/events
#        artifactOverrides:
#          image: events
#      - name: tracker
#        chartPath: helm/charts/tracker
#        artifactOverrides:
#          image: tracker
#      - name: redis
#        chartPath: helm/charts/redis
#      - name: kafka
#        chartPath: helm/charts/kafka
#      - name: mongodb
#        chartPath: helm/charts/mongo
#      - name: vuecabinet
#        chartPath: helm/charts/vuecabinet
#        artifactOverrides:
#          image: vuecabinet

```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...
