### ISSUE TITLE
Skaffold labels cause incompatibility with subsequent standard kubectl commands

### ISSUE THREAD

**Issue by HariSekhon** [GoogleContainerTools/skaffold#6416]
### Expected behavior

In between a `skaffold dev/run/deploy` or similar, other `kubectl` commands should be able to `kubectl diff` / `kubectl apply`.

### Actual behavior

Running a `kustomize build | kubectl diff -` (or `apply`) receives this error as the labels can't be updated:

The StatefulSet "blah" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

### Information

- Skaffold version: v1.28.1
- Operating system: macOS
- Installed via: binary download
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: myapp
deploy:
  statusCheckDeadlineSeconds: 500
  kubeContext: gke_<context>
  kustomize:
    paths:
      - ../base
      - .

```

### Steps to reproduce the behavior

```
$ skaffold run
```
```
$ kustomize build | kubectl apply -f -
...
The StatefulSet "blah" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

Further details are in this ticket:

#3219

Do these labels affect the ability of something like `skaffold dev` to know which version it has rolled out yet compared to the last change?

Is there a way to prevent Skaffold from adding labels to kubernetes objects?
