### ISSUE TITLE
profile deploy.kubeContext not used in run

### ISSUE THREAD

**Issue by dthomastx** [GoogleContainerTools/skaffold#6434]
### Expected behavior
context provided in deploy.kubeContext should be observed

### Actual behavior
kubectl current-context is used

### Information

- Skaffold version: 1.29.0
- Operating system: Win 10
- Installed via: Chocolatey
- Contents of skaffold.yaml:

```yaml
- name: qa-kaniko
  build:
    tagPolicy: *tagPolicy
    artifacts:
    - image: *image
      kaniko:
    cluster:
  deploy:
    kubeContext: qa
    kustomize: 
      paths:
      - ./kustomize/overlays/qa
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

`time="2021-08-13T09:54:59-05:00" level=info msg="Using kubectl context: admin"`

```
CURRENT   NAME      CLUSTER   AUTHINFO        NAMESPACE
*         admin     dev   dev-admin
           qa          qa     qa-admin
```

switching kubectl current config switches config used

using --kube-context=qa works correctly
