### ISSUE TITLE
Skaffold fix should output the changed json to a file

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#6456]
from @chairy's discussion from v3 config upgrade, 

Right now `skaffold fix`  outputs the new config on to StdOut. 

Add a flag to store the updated config to a a file `--output` so IDES can specify the updated skaffold config file and show it the diff to users.

```
../../../skaffold/out/skaffold fix
apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: java-guestbook
build:
  artifacts:
  - image: backend
    context: backend
    docker:
      dockerfile: Dockerfile
  - image: frontend
    context: frontend
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - backend/deployment.yaml
    - frontend/deployment.yaml
portForward:
- resourceType: service
  resourceName: backend
  port: 8080
- resourceType: service
  resourceName: frontend
  port: 8080

```
