### ISSUE TITLE
Running `skaffold debug` exposes debug ports only to deployments from the first module

### ISSUE THREAD

**Issue by zodo** [GoogleContainerTools/skaffold#6485]
### Expected behavior

Running `skaffold debug` exposes debug ports for all deployments

### Actual behavior

Running `skaffold debug` exposes debug ports only to deployments from the first module

### Information

- Skaffold version: v1.30.0
- Operating system: Ubuntu 20.04.2 LTS
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta19
kind: Config
requires:
- path: ./leeroy-app
- path: ./leeroy-web
```
- Contents of leeroy-app/skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: app-config
requires:
- path: ../base
build:
  artifacts:
  - image: leeroy-app
    requires:
    - image: base
      alias: BASE
deploy:
  kubectl:
    manifests:
    - kubernetes/*
portForward:
- resourceType: deployment
  resourceName: leeroy-app
  port: http
  localPort: 9001
```

- Contents of leeroy-web/skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: web-config
requires:
- path: ../base
build:
  artifacts:
  - image: leeroy-web
    requires:
    - image: base
      alias: BASE
deploy:
  kubectl:
    manifests:
    - kubernetes/*
portForward:
- resourceType: deployment
  resourceName: leeroy-web
  port: 8080
  localPort: 9000
```

### Steps to reproduce the behavior

1. `git clone git@github.com:GoogleContainerTools/skaffold.git`
2. cd examples/multi-config-microservices
3. `skaffold debug`

Output, no debug port forwarding for leeroy-web:
```

Port forwarding deployment/leeroy-web in namespace default, remote port 8080 -> http://127.0.0.1:9000
Port forwarding deployment/leeroy-app in namespace default, remote port http -> http://127.0.0.1:9001
Press Ctrl+C to exit
Not watching for changes...
[install-go-debug-support] Installing runtime debugging support files in /dbg
[install-go-debug-support] Installation complete
[leeroy-app] API server listening at: [::]:56268
[leeroy-app] 2021/08/22 13:15:44 leeroy app server ready
[leeroy-web] API server listening at: [::]:56268
[leeroy-web] 2021/08/22 13:15:50 leeroy web server ready
[install-go-debug-support] Installing runtime debugging support files in /dbg
[install-go-debug-support] Installation complete
Port forwarding pod/leeroy-app-8d5d57c5b-b8dbd in namespace default, remote port 56268 -> http://127.0.0.1:56268
```
The piece of the trace logs, please note the duplicate "selecting debug port" lines
```
time="2021-08-22T19:53:05+07:00" level=debug msg="selecting debug port for pod/leeroy-app-c49bdc978-dtjs7/leeroy-app: {dlv 0 56268 TCP }"
time="2021-08-22T19:53:05+07:00" level=trace msg="looking for port: 127.0.0.1:56268"
time="2021-08-22T19:53:05+07:00" level=trace msg="was able to obtain INADDR_ANY:56268"
time="2021-08-22T19:53:05+07:00" level=trace msg="was able to obtain 127.0.0.1:56268"
time="2021-08-22T19:53:05+07:00" level=debug msg="found open port: 56268"
time="2021-08-22T19:53:05+07:00" level=trace msg="was able to obtain INADDR_ANY:56268"
time="2021-08-22T19:53:05+07:00" level=trace msg="was able to obtain 127.0.0.1:56268"
time="2021-08-22T19:53:05+07:00" level=debug msg="Running command: [kubectl --context minikube port-forward --pod-running-timeout 1s --namespace default pod/leeroy-app-c49bdc978-dtjs7 56268:56268]"
time="2021-08-22T19:53:05+07:00" level=debug msg="selecting debug port for pod/leeroy-app-c49bdc978-dtjs7/leeroy-app: {dlv 0 56268 TCP }"
```
