### ISSUE TITLE
No sync on rerun

### ISSUE THREAD

**Issue by pblkt** [GoogleContainerTools/skaffold#6486]
### Expected behavior
Sync runs when `skaffold` is started. The code in the container reflects the code on host, including all changes from last build.

### Actual behavior
Sync runs only when a write event occurs on a file if the image is present in Minikube. Furthermore, the sync happens on a per-file basis, so 

### Information

- Skaffold version: `v1.30.0`
- Operating system: Ubuntu 20.04
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta20
kind: Config

build:
  local:
    push: false
    tryImportMissing: false
  artifacts:
  - image: MyImage
    context: ../..
    docker:
      dockerfile: ./SomePath/Dockerfile
    sync:
      manual:
      - src: '/**'
        dest: '/opt/my-code'

deploy:
  kubeContext:
    minikube
  kubectl:
    manifests:
    - ./k8s/deployment.yaml
```

### Steps to reproduce the behavior

-  A docker image that was built with `COPY ./src /opt/my-code/` 
-  `src` was updated from when the image was built
-  `skaffold` was started on Minkube. The changes were synced to the container, some dev cycles took place
- `skaffold` was then stopped...
- ...and restarted
