### ISSUE TITLE
Skaffold config API forbids passing multiple secrets to docker build

### ISSUE THREAD

**Issue by marcin-ptaszynski** [GoogleContainerTools/skaffold#6498]
### Expected behavior

Ability to pass multiple secrets into `docker build` context, like:

```yaml
<snip>
    docker:
      buildArgs:
        BUILD_ARG1: value1
        BUILD_ARG2: value2
      secrets:
        gitconfig:
          src: .gitconfig
        signingkey:
          src: signingkey.pem
        ...
```

or some other variant, like a list:

```yaml
      secrets:
      - id: gitconfig
        src: .gitconfig
      - id: signingkey
        src: signingkey.pem

```

### Actual behavior

Latest [(v2beta21) Config API](https://skaffold.dev/docs/references/yaml/?version=v2beta21#build-artifacts-docker-secret) limits allowed numer of secrets to up to one. I believe this to be purely accidental and not intended limitation.
```yaml
<snip>
    docker:
      buildArgs:
        BUILD_ARG1: value1
        BUILD_ARG2: value2
      secret:
        id: gitconfig
        src: .gitconfig
      ...
```
### Information

- Skaffold version: v1.30.0
- Operating system: MacOS 11.5.2
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta21
kind: Config
build:
  artifacts:
  - image: example
    docker:
      dockerfile: example.dockerfile
      buildArgs:
        BUILD_ARG1: value1
        BUILD_ARG2: value2
      secret:
        id: gitconfig
        src: .gitconfig
        # no more?
  build:
    local:
      push: true
      useBuildkit: true
```

### Steps to reproduce the behavior
Take above yaml
