### ISSUE TITLE
[1.27.0+] Deployment ignores kubeContext from skaffold.yaml for some operations

### ISSUE THREAD

**Issue by mutineer** [GoogleContainerTools/skaffold#6510]
### Expected behavior

During deployment using `skaffold run` context for `kubectl` is taken from `skaffold.yaml` `kubeContext` for all operations

### Actual behavior

For objects deployment context from `skaffold.yaml` is used, but afterwards for adding labels `skaffold` uses default context from kubeconfig, ignoring one set in `skaffold.yaml`

### Information

- Skaffold version: 1.27.0+
- Operating system: MacOS 11.5.1
- Installed via: skaffold.dev | Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
metadata:
  name: project_name

build:
  local:
    useBuildkit: true
    useDockerCLI: true
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
    - image: static_collector
      context: ./src
      docker:
        dockerfile: Dockerfile
        target: static_collector

deploy:
  kubeContext: staging
  statusCheckDeadlineSeconds: 600
  helm:
    releases:
      - name: project
        chartPath: helm
        values:
          collector_image: "static_collector"
        valuesFiles:
          - helm/values.yaml
        setValueTemplates:
          global.hash: "{{.IMAGE_TAG}}"
```

### Steps to reproduce the behavior

1. `current-context` in `.kube/config` have to be different from `staging`
2. `skaffold run`
3. objects are deployed, but later on error occurs:
```
DEBU[0009] getting client config for kubeContext: `staging`
DEBU[0009] getting client config for kubeContext: `staging`
DEBU[0009] Patching statics-uploader in namespace default
DEBU[0010] Patching statics-uploader in namespace default
DEBU[0011] Patching statics-uploader in namespace default
WARN[0011] error adding label to runtime object: patching resource default/"statics-uploader": jobs.batch "statics-uploader" is forbidden: User "mutineer" cannot patch resource "jobs" in API group "batch" in the namespace "default"
INFO[0011] Deploy completed in 8.526 seconds
Waiting for deployments to stabilize...
DEBU[0011] getting client config for kubeContext: `staging`
Deployments stabilized in 154.482625ms
DEBU[0011] getting client config for kubeContext: `staging`
You can also run [skaffold run --tail] to get the logs
WARN[0011] got unexpected event of type ERROR
```

Notice the `default` namespace – this is the namespace from my default kubectl context, context `staging` uses namespace `staging`

P.S. This env works correctly on versions before 1.27.0. Most probably behaviour was changed in this PR: https://github.com/GoogleContainerTools/skaffold/pull/6024
