### ISSUE TITLE
docs: Using a Custom OpenAPI schema for Kustomize build

### ISSUE THREAD

**Issue by irvifa** [GoogleContainerTools/skaffold#6511]
### Information

- Skaffold version: 
```
$ skaffold version
v1.28.1
```

- Operating system: 
```
$ uname -a
Darwin lin 20.6.0 Darwin Kernel Version 20.6.0
```

- Installed via:  
skaffold.dev

- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: my-resource-definition
build:
  local:
    push: true
  tagPolicy:
    customTemplate:
      template: dev-{{.INPUT_DIGEST}}
      components:
        - name: INPUT_DIGEST
          inputDigest: {}
  artifacts:
    - image: <some-image>
deploy:
  kubeContext: my-k8s-context
  kustomize:
    paths:
      - kubernetes
```

Step:
```
DEMO_HOME=$(mktemp -d)
```

```
cat <<EOF >$DEMO_HOME/my_resource.yaml
apiVersion: example.com/v1alpha1
kind: MyResource
metadata:
  name: service
spec:
  template:
    spec:
      containers:
      - name: server
        image: server
        command: example
        ports:
        - name: grpc
          protocol: TCP
          containerPort: 8080
EOF
```
```
cat <<EOF >>$DEMO_HOME/mycr_schema.json
{
  "definitions": {
    "v1alpha1.MyResource": {
      "properties": {
        "apiVersion": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "metadata": {
          "type": "object"
        },
        "spec": {
          "properties": {
            "template": {
              "\$ref": "#/definitions/io.k8s.api.core.v1.PodTemplateSpec"
            }
          },
          "type": "object"
        },
        "status": {
           "properties": {
            "success": {
              "type": "boolean"
            }
          },
          "type": "object"
        }
      },
      "type": "object",
      "x-kubernetes-group-version-kind": [
        {
          "group": "example.com",
          "kind": "MyResource",
          "version": "v1alpha1"
        }
      ]
    },
    "io.k8s.api.core.v1.PodTemplateSpec": {
      "properties": {
        "metadata": {
          "\$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
        },
        "spec": {
          "\$ref": "#/definitions/io.k8s.api.core.v1.PodSpec"
        }
      },
      "type": "object"
    },
    "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta": {
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "io.k8s.api.core.v1.PodSpec": {
      "properties": {
        "containers": {
          "items": {
            "\$ref": "#/definitions/io.k8s.api.core.v1.Container"
          },
          "type": "array",
          "x-kubernetes-patch-merge-key": "name",
          "x-kubernetes-patch-strategy": "merge"
        }
      },
      "type": "object"
    },
    "io.k8s.api.core.v1.Container": {
      "properties": {
        "command": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "image": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "ports": {
          "items": {
            "\$ref": "#/definitions/io.k8s.api.core.v1.ContainerPort"
          },
          "type": "array",
          "x-kubernetes-list-map-keys": [
            "containerPort",
            "protocol"
          ],
          "x-kubernetes-list-type": "map",
          "x-kubernetes-patch-merge-key": "containerPort",
          "x-kubernetes-patch-strategy": "merge"
        }
      },
      "type": "object"
    },
    "io.k8s.api.core.v1.ContainerPort": {
      "properties": {
        "containerPort": {
          "format": "int32",
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "protocol": {
          "type": "string"
        }
      },
      "type": "object"
    }
  }
}

EOF
```

```
cat <<EOF >$DEMO_HOME/kustomization.yaml
resources:
- my_resource.yaml

openapi:
  path: mycr_schema.json
EOF
```

```
cat <<EOF >$DEMO_HOME/out_expected.yaml
apiVersion: example.com/v1alpha1
kind: MyResource
metadata:
  name: service
spec:
  template:
    spec:
      containers:
      - command: example
        image: <some-image>
        name: server
        ports:
        - containerPort: 8080
          name: grpc
          protocol: TCP
EOF
```

```
skaffold render >$DEMO_HOME/out_actual.yaml
```

```
diff $DEMO_HOME/out_actual.yaml $DEMO_HOME/out_expected.yaml
```

### Expected behavior

Question is: does Skaffold support kustomize build with custom OpenAPI schema for CustomResource?
This is how kustomize provide more [information](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/customOpenAPIschema.md) regarding custom open API schema.
