### ISSUE TITLE
Cannot push an images to the local repository

### ISSUE THREAD

**Issue by acelot** [GoogleContainerTools/skaffold#6518]
### Expected behavior

Skaffold should upload the newly built images to the local repository

### Actual behavior

Skaffold builds the image successfully, but cannot load it due to an error:

```
could not push image "localhost:5000/xxx:mytag-g567e04fa9a-dirty": An image does not exist locally with the tag: localhost:5000/xxx:mytag-g567e04fa9a-dirty
```

### Information

- Skaffold version: v1.30.0
- Podman version: 3.3.0
- k3s version: v1.21.3+k3s1
- Operating system: `Arch Linux 5.13.12-arch1-1 #1 SMP PREEMPT Wed, 18 Aug 2021 20:49:03 +0000 x86_64 GNU/Linux`
- Installed via: Downloaded from the official site
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta7
kind: Config
build:
deploy:

.sync_folders: &sync_folders
  - src: app/**
    dest: /app

- name: dev-local
  build:
    artifacts:
      - image: xxx/xxx
        context: ../.
        sync:
          manual: *sync_folders
        docker:
          dockerfile: Dockerfile
    local:
      push: true
  deploy:
    helm:
      releases:
        - name: xxx-service
          chartPath: yyy/yyy
          upgradeOnChange: true
          version: ~3.0.1
          remote: true
          namespace: xxx
          valuesFiles:
            - ./values.yaml
          artifactOverrides:
            image.fullname: xxx/xxx
          setValues:
            image.pullPolicy: IfNotPresent
          wait: true
      flags:
        install:
          - --atomic
          - --create-namespace
        upgrade:
          - --atomic
```

### Steps to reproduce the behavior

I'm trying to use skaffold with **podman** and **k3s**.

- To store the built images, I deployed a local repository via command:
```
podman run -d --name registry -p 5000:5000 -v $HOME/podman/library:/var/lib/registry --restart=always registry:2
```
- Then I have added my local registry to the podman `/etc/containers/registries.conf`:
```
# # An array of host[:port] registries to try when pulling an unqualified image, in order.
unqualified-search-registries = ["localhost:5000", "docker.io", "registry.fedoraproject.org", "registry.access.redhat.com", "quay.io"]
``` 
- Also I added my registry to the k3s mirrors `/etc/rancher/k3s/registries.yaml` and restarted k3s service:
```
mirrors:
  localhost:5000:
    endpoint:
      - "http://localhost:5000"
```
- Made my registry the default registry for the skaffold in `~/.skaffold/config`
```
global:
  default-repo: localhost:5000
  insecure-registries:
  - localhost:5000
  survey:
    last-prompted: "2021-08-23T14:30:04+07:00"
  collect-metrics: true
  update:
    last-prompted: "2021-08-25T22:38:14+07:00"
```
- Now I'm trying to build my image and deploy to k3s:
```
→ skaffold dev -p dev-local

Listing files to watch...
 - xxx/xxx
Generating tags...
 - xxx/xxx -> localhost:5000/xxx_xxx:mytag-g567e04fa9a-dirty
Checking cache...
 - xxx/xxx: Not found. Building
Starting build...
Building [xxx/xxx]...
Sending build context to Docker daemon  434.6MB
STEP 1/20: <...many steps here...>
COMMIT localhost:5000/xxx_xxx:mytag-g567e04fa9a-dirty
Getting image source signatures
Copying blob sha256:814bff7343242acfd20a2c841e041dd57c50f0cf844d4abd2329f78b992197f4
<...many blobs here...>
Copying config sha256:2f7066935df60b7d95176f90582ffe1907be0c48df6bcaf0c45445f5eac8ac10
Writing manifest to image destination
Storing signatures
--> 2f7066935df
Successfully tagged localhost:5000/xxx_xxx:mytag-g567e04fa9a-dirty
2f7066935df60b7d95176f90582ffe1907be0c48df6bcaf0c45445f5eac8ac10
Successfully built 2f7066935df6
The push refers to repository [localhost:5000/xxx_xxx:mytag-g567e04fa9a-dirty]
Building [xxx/xxx]...
Canceled build for xxx/xxx
could not push image "localhost:5000/xxx_xxx:mytag-g567e04fa9a-dirty": An image does not exist locally with the tag: localhost:5000/xxx_xxx:mytag-g567e04fa9a-dirty
```

### My comments
It's very strange that the error says that the image was not found locally, although the built image exists, if you check through the `podman images`:
```
→ podman images
REPOSITORY              TAG                      IMAGE ID      CREATED         SIZE
localhost:5000/xxx_xxx  mytag-g567e04fa9a-dirty  2f7066935df6  22 minutes ago  1.78 GB
```

And doubly strange that I can push the image manually:
```
→ podman push localhost:5000/xxx_xxx:mytag-g567e04fa9a-dirty --tls-verify=false
Getting image source signatures
Copying blob <...many blobs here...>
Copying blob 5753b2c5db63 done  
Copying config 2f7066935d done  
Writing manifest to image destination
Storing signatures
```

Additionally, I would like to say that my local repository is available from the k3s and images that are pushed by hands are successfully pulled from there.
