### ISSUE TITLE
skaffold deploy should respect tagPolicy

### ISSUE THREAD

**Issue by mxey** [GoogleContainerTools/skaffold#653]
David Gageot on Slack asked me to file this is as a feature request.

When using the new `skaffold deploy` command, I have to specify the image tags I want to deploy. I'd like Skaffold to generate the image tag in the same way as `skaffold build` and deploy those images. This obviously would not work for all `tagPolicy` settings, but would apply to `gitCommit` and `envTemplate`

**Comment by r2d4** [comment]
This is a great idea. We aren't able to do it until we remove the `checksum` tagger (which is the default for `skaffold dev`) since that requires us to build the image to calculate the tag. The other taggers can be determined independently of the build.

**Comment by dgageot** [comment]
@r2d4 In fact envTemplate and datetime taggers have the same issue

**Comment by Miyurz** [comment]
@r2d4 Not sure how I could use git short tag in deploy. Can you throw more light on this ?
This is how my skaffold.yaml looks like


```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    #sha256: {}
    gitCommit: {}
  artifacts:
  - imageName: org/backend
deploy:
  helm:
    releases:
    - name: org-backend
      chartPath: infra/charts/beam
      #wait: false
      #valuesFilePath: infra/charts/org/values.yaml
      #values:
      #  image: org/backend
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.  
      setValues:
        image.tag: e290211
```
