### ISSUE TITLE
Build loops for skaffold dev with `sync` and `hooks`

### ISSUE THREAD

**Issue by Shabirmean** [GoogleContainerTools/skaffold#6532]
### Information / Actual behavior / Expected behavior
I have springboot app that bundles the built js ui bits inside. So before building and deploying the spring boot app I need to build the ui project and copy over the files into the project. I have setup a **pre-build hook** for this with a custom script that builds the ui. There are two issues in the options available to get this working.

_**Important:** There are two other artifacts that depend on the main artifact_

**Case 1**
The **pre-build hook custom script** copies over files from the ui project - skaffold notices changes to the _artifact_ and re-triggers a build. Then the same loop continues. 
```sh
pre-build custom script -> copies files into the artifact directory -> artifact has file chages -> so rebuild
```
**Case 2:**
Another thing I tried was to point the springboot app to fetch static files from an external file path. So for this, I avoided copying over the ui static files into the project during the pre-build phase and set up a file sync to that external path. But seems like this also is triggering an infinite loop of re-building. But in this case it only happens when the **2 extra** dependant artifacts are kept. If they are removed then no issues.

- Skaffold version: **v1.30.0**
- Operating system: **MacOS BigSur 11.5.1**
- Installed via: **Homebrew**
- Contents of **skaffold.yaml**:

#### (pre-build script **copies** files into artifact dir)
```yaml
apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: backend # module defining backend services
build:
  artifacts:
  - image: gcr.io/gcp-project/api-server
    jib:
      project: api-server
    hooks:
      before:
      - command: [ "sh", "-c", "./build.sh" ]  # <- this will copy static js into the 'api-server' project resources
        os: [ darwin, linux ]
  - image: gcr.io/gcp-project/inventory
    requires:
    - image: gcr.io/gcp-project/api-server
    jib:
      project: inventory
  - image: gcr.io/gcp-project/payments
    requires:
    - image: gcr.io/gcp-project/api-server
    jib:
      project: payments
  tagPolicy:
    gitCommit: { }
  local:
    concurrency: 0
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/service-configs.yaml
    - kubernetes-manifests/api-server.yaml
    - kubernetes-manifests/inventory.yaml
    - kubernetes-manifests/payments.yaml
```

#### (pre-build script **does not copy** files into artifact dir; fails only when there are dependant aritfacts)
```yaml

apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: backend # module defining backend services
build:
  artifacts:
  - image: gcr.io/gcp-project/api-server
    jib:
      project: api-server
    hooks:
      before:
      - command: [ "sh", "-c", "./build.sh" ] # <- this will NOT copy static js into the 'api-server' project resources
        os: [ darwin, linux ]
    sync:
      manual:
      - src: '../ui/target/dist/**'
        dest: '/app/resources/'
        strip: '../ui/target/dist/'
  - image: gcr.io/gcp-project/inventory
    requires:
    - image: gcr.io/gcp-project/api-server
    jib:
      project: inventory
  - image: gcr.io/gcp-project/payments
    requires:
    - image: gcr.io/gcp-project/api-server
    jib:
      project: payments
  tagPolicy:
    gitCommit: { }
  local:
    concurrency: 0
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/service-configs.yaml
    - kubernetes-manifests/api-server.yaml
    - kubernetes-manifests/inventory.yaml
    - kubernetes-manifests/payments.yaml
```

### Steps to reproduce the behavior

N/A
