### ISSUE TITLE
"got unexpected event of type ERROR" on CTRL + C

### ISSUE THREAD

**Issue by rstoermer** [GoogleContainerTools/skaffold#6551]
### Expected behavior

Skaffold exits the container without an error message

### Actual behavior

Error message "got unexpected event of type ERROR" shows up in terminal:
![image](https://user-images.githubusercontent.com/5518072/131624309-1b33f168-e0a0-4bf1-90dd-d5c331ab584d.png)

### Information

- Skaffold version: v1.30.0
- Operating system: OSX Big Sur 11.5.2
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta21
kind: Config
build:
    local:
        push: false
        useDockerCLI: false
        useBuildkit: true
    artifacts:
        - image: projectreg/orchestrator
          context: .
          docker:
              dockerfile: Dockerfile
              target: local
              buildArgs:
                  NPM_TOKEN: "{{ .NPM_TOKEN }}"
          sync:
              manual:
                  # Sync all folders relevant for application development
                  - src: "src/**"
                    dest: .
deploy:
    kubeContext: docker-desktop
    helm:
        releases:
          - name: project-local-orchestrator
            chartPath: ../project-infrastructure/helm/project/charts/orchestrator/
            valuesFiles: ["../project-infrastructure/helm/project/values.yaml"]
            namespace: project-local
            artifactOverrides:
                image: nextor.azurecr.io/orchestrator
portForward:
  - resourceType: deployment
    resourceName: orchestrator-deployment
    namespace: project-local
    port: 6557
    localPort: 6557
```
