### ISSUE TITLE
Push images into local registry instead of load into local cluster

### ISSUE THREAD

**Issue by piotrminkina** [GoogleContainerTools/skaffold#6558]
Pushing images in my experience is much faster than load them directly into local cluster. For example in my project with 16 images, loading directly into cluster consumes about 2–3 minutes. When I force send images into the local k3d registry, the time reduces to 1.5 minutes (on initial deployment), but each subsequent change is sent to the cluster expressly (in a few seconds).

### Expected behavior

For local clusters I think Skaffold should support images registries in a same way as Tilt doing. See [Discovering the Registry](https://docs.tilt.dev/choosing_clusters.html#discovering-the-registry) for details.

In short:
1. k3d, kind etc. applies the following ConfigMap on local cluster:
    ```yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: local-registry-hosting
      namespace: kube-public
    data:
      localRegistryHosting.v1: |
        host: localhost:35879
        hostFromContainerRuntime: k3d-k3s-local-registry:5000
        help: https://k3d.io/usage/guides/registries/#using-a-local-registry
    ```
2. Skaffold should push images into `localhost:35879`, but k8s manifests should map to `k3d-k3s-local-registry:5000`.

### Actual behavior

Skaffold loads built images directly into cluster.

### Information

- Skaffold version: v1.28.0
- Operating system: Alpine Linux v3.13
- Installed via: `wget -O skaffold https://github.com/GoogleContainerTools/skaffold/releases/download/v${SKAFFOLD_VERSION}/skaffold-linux-amd64`

**Comment by KhaledSakr** [comment]
This is already supported although - in my opinion- not very well documented. You can check it out here: https://github.com/GoogleContainerTools/skaffold/pull/5012

**Comment by piotrminkina** [comment]
@KhaledSakr thanks for #5012. It not works exactly as I described, because Docker Registry is not automatically detected from ConfigMap `local-registry-hosting`. See that the port number for published registry is dynamic.

I tried below config without success for local k3d cluster:
```
global:
  default-repo: localhost:40893
  local-cluster: true
  insecure-registries:
  - http://localhost:40893
  kind-disable-load: true
  k3d-disable-load: true
  collect-metrics: true
kubeContexts: []
```

In my case skaffold hangs on:
```
Generating tags...
 - busybox -> localhost:40893/busybox:local-16a3362
 - docker.io/bitnami/kafka -> localhost:40893/docker_io_bitnami_kafka:local-16a3362
 - docker.io/bitnami/nginx -> localhost:40893/docker_io_bitnami_nginx:local-16a3362
 - docker.io/bitnami/postgresql -> localhost:40893/docker_io_bitnami_postgresql:local-16a3362
 - docker.io/bitnami/rabbitmq -> localhost:40893/docker_io_bitnami_rabbitmq:local-16a3362
 - docker.io/bitnami/redis -> localhost:40893/docker_io_bitnami_redis:local-16a3362
 - docker.io/bitnami/zookeeper -> localhost:40893/docker_io_bitnami_zookeeper:local-16a3362
 - getsentry/relay -> localhost:40893/getsentry_relay:local-16a3362
 - getsentry/sentry -> localhost:40893/getsentry_sentry:local-16a3362
 - getsentry/snuba -> localhost:40893/getsentry_snuba:local-16a3362
 - prom/statsd-exporter -> localhost:40893/prom_statsd-exporter:local-16a3362
 - subfuzion/netcat -> localhost:40893/subfuzion_netcat:local-16a3362
 - yandex/clickhouse-server -> localhost:40893/yandex_clickhouse-server:local-16a3362
INFO[0000] Tags generated in 45.227019ms                
Checking cache...
```
