### ISSUE TITLE
Custom static labels

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#657]
I'd like to expose a way for users to label their objects with custom static labels. This might look something like 

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold
deploy:
  kubectl:
    manifests:
    - deploy/skaffold/*
labels:
  my-app: some-value
  another-key: another-value
```
