### ISSUE TITLE
Build hooks sometimes don't work

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#6572]
### Expected behavior

I tried `examples/lifecycle-hooks` and tried to apply the same to `examples/getting-started`.

So modify the examples/getting-started/skaffold.yaml like this:
```diff
diff --git a/examples/getting-started/skaffold.yaml b/examples/getting-started/skaffold.yaml
index c0b13239a..038c7258d 100644
--- a/examples/getting-started/skaffold.yaml
+++ b/examples/getting-started/skaffold.yaml
@@ -3,6 +3,13 @@ kind: Config
 build:
   artifacts:
   - image: skaffold-example
+    hooks:
+      before:
+      - command: ["env"]
+        os: [darwin, linux]
+      after:
+      - command: ["env"]
+        os: [darwin, linux]
 deploy:
   kubectl:
     manifests:
```

I expect `skaffold build -v debug` logs to show stuff like:

```
Starting pre-build hooks...
DEBU[0000] Running command: [env]
```

### Actual behavior

The hook is not being executed according to logs.

### Information

- Skaffold version: v1.31.0
- Operating system: macOS
- Installed via: Brew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta22
kind: Config
build:
  artifacts:
  - image: skaffold-example
    hooks:
      before:
      - command: ["env"]
        os: [darwin, linux]
      after:
      - command: ["env"]
        os: [darwin, linux]
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. apply the diff above
2. `skaffold build -v debug`
3. output doesn't show any hooks being executed
