### ISSUE TITLE
Logs from same Helm charts have the same log label

### ISSUE THREAD

**Issue by ric-sapasap** [GoogleContainerTools/skaffold#6576]
### Expected behavior
Helm releases from same charts with different `nameOverride` should display different log labels

### Actual behavior
Actual screenshot on minikube:
![image](https://user-images.githubusercontent.com/52158902/132532505-be068c3b-7f97-46b7-b070-18096267e534.png)

I'll have more than 10 services that will share the same helm chart. This issue makes reading logs difficult.

### Information

- Skaffold version: 1.31.0
- Operating system: Ubuntu 18.04
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta17
kind: Config
build:
  artifacts:
    - image: mbs-configurations
      context: ../ewallet-configuration-microservice

deploy:
  helm:
    releases:
      - name: mbs-configurations
        chartPath: ../helm-charts/mbs-services
        artifactOverrides:
          image: mbs-configurations
        valuesFiles:
          - ../helm-overrides/local/common.yaml
          - ../helm-overrides/local/secrets.yaml
          - ../helm-overrides/local/configurations.yaml
        imageStrategy:
          helm: {}
```

```yaml
apiVersion: skaffold/v2beta17
kind: Config
build:
  artifacts:
    - image: mbs-sms
      context: ../ewallet-sms-microservice

deploy:
  helm:
    releases:
      - name: mbs-sms
        chartPath: ../helm-charts/mbs-services
        artifactOverrides:
          image: mbs-sms
        valuesFiles:
          - ../helm-overrides/local/common.yaml
          - ../helm-overrides/local/secrets.yaml
          - ../helm-overrides/local/sms.yaml
        imageStrategy:
          helm: {}
```

### Steps to reproduce the behavior

1. Create 2 releases from same helm chart
2. `skaffold dev`

If you need any more details, don't hesitate to tell me. Thanks!
