### ISSUE TITLE
Skaffold setValueTemplates not setting a map value to null

### ISSUE THREAD

**Issue by itzmanish** [GoogleContainerTools/skaffold#6594]
I am trying to override a map value in helm to null. But when I use with setValueTemplates it is not overriding the value to null.

### Expected behavior

Should override and set the map value to null/nil/empty
### Actual behavior

Does nothing to the override key.
### Information

- Skaffold version: v1.29.0
- Operating system: Arch Linux, Kernel -  5.10.56-1-lts
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: demo
build:
  local:
    useDockerCLI: true
profiles:
  - name: production
    build:
      artifacts:
        - image: <<sensitive>>
          context: .
          docker:
            buildArgs:
              ENV: production
              NPM_TOKEN: "{{.NPM_TOKEN}}"
            cacheFrom:
              - <<sensitive>>
      tagPolicy:
        gitCommit:
          variant: AbbrevCommitSha
          ignoreChanges: true
  - name: dev
    build:
      artifacts:
        - image: <<sensitive>>
          context: .
          sync:
            infer:
              - dist/**/*
          docker:
            buildArgs:
              NPM_TOKEN: "{{.NPM_TOKEN}}"
            cacheFrom:
              - <<sensitive>>
    deploy:
      helm:
        releases:
          - name: demo
            remoteChart: <<sensitive>>
            artifactOverrides:
              image: <<sensitive>>
            upgradeOnChange: true
            setValueTemplates:
              baseDomain: <<sensitive>>
              nodeId: "{{.NODE_ID}}"
              nodeSelector: {}
            imageStrategy:
              helm: {}
```
