### ISSUE TITLE
kpt deploy failing

### ISSUE THREAD

**Issue by rochana-atapattu** [GoogleContainerTools/skaffold#6602]
### Expected behavior
Deploy from vscode to cluster

### Actual behavior
Deploy step fail

### Information

- in kpt it check to see if the sink dir is already there if so the command gives an error.

[here](https://github.com/GoogleContainerTools/kpt/blob/651aa79a54d0dbeea11aca6f6dc1c0e45b2ddeb0/thirdparty/cmdconfig/commands/cmdsink/cmdsink.go#L42)
```
func (r *SinkRunner) runE(c *cobra.Command, args []string) error {
	if err := cmdutil.CheckDirectoryNotPresent(args[0]); err != nil {
		return err
	}
	return cmdutil.WriteToOutput(c.InOrStdin(), nil, args[0])
}
```

- in skaffold deploy sink func creates a dir before executing the command

[here](https://github.com/GoogleContainerTools/skaffold/blob/e7ab8c9435fcd2c7f9ec6695d5bd76ce8ea26159/pkg/skaffold/deploy/kpt/kpt.go#L497)
```
func sink(ctx context.Context, buf []byte, sinkDir string) error {
	if err := os.RemoveAll(sinkDir); err != nil {
		return fmt.Errorf("deleting sink directory %s: %w", sinkDir, err)
	}

	if err := os.MkdirAll(sinkDir, os.ModePerm); err != nil {
		return fmt.Errorf("creating sink directory %s: %w", sinkDir, err)
	}

	cmd := exec.CommandContext(ctx, "kpt", kptCommandArgs(sinkDir, []string{"fn", "sink"}, nil, nil)...)
	cmd.Stdin = bytes.NewBuffer(buf)
	if _, err := util.RunCmdOut(ctx, cmd); err != nil {
		return fmt.Errorf("sinking to directory %s: %w", sinkDir, err)
	}
	return nil
}

```

- Skaffold version: v1.31.0
- Kpt vsersion: 1.0.0-beta.4
- Operating system: darwin arm64
- Installed via: Cloud Code
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta21
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - context: .
    image: gcr.io/reg/app
  googleCloudBuild:
    projectId: project_id
# defines the Kubernetes manifests to deploy on each run
deploy:
  kpt:
    dir: krm
    fn:
      sinkDir: "sink"
# use the cloudbuild profile to build images using Google Cloud Build
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
```

### Steps to reproduce the behavior

Run On Kubernetes on vscode 

> Starting deploy...
> sinking to directory .kustomize: running [kpt fn sink .kustomize]
>  - stdout: ""
>  - stderr: "error: directory \".kustomize\" already exists, please delete the directory and retry\n"
>  - cause: exit status 1
>
