### ISSUE TITLE
Friction Log: Docker deploy nil pointer exception

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#6623]
Edit skaffold.yaml in examples/microservices like to this

skaffold.yaml
```
apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: leeroy-web
      context: leeroy-web
      requires:
        - image: base
          alias: BASE
    - image: leeroy-app
      context: leeroy-app
      requires:
        - image: base
          alias: BASE
    - image: base
      context: base
deploy:
  docker:
      images: [ leeroy-web, leeroy-app ]
portForward:
  - resourceType: Container
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
  - resourceType: Container
    resourceName: leeroy-app
    port: http
    localPort: 9001

```

Error:

```
➜  microservices git:(main) ✗ ../../out/skaffold dev --rpc-http-port=50052
Listing files to watch...
 - leeroy-web
 - leeroy-app
 - base
Generating tags...
 - leeroy-web -> leeroy-web:v1.29.0-136-gcc643471c
 - leeroy-app -> leeroy-app:v1.29.0-136-gcc643471c
 - base -> base:v1.29.0-136-gcc643471c
Checking cache...
 - leeroy-web: Found Locally
 - leeroy-app: Found Locally
 - base: Found Locally
Tags used in deployment:
 - leeroy-web -> leeroy-web:05ce72a3f0b7f197a920663dc71d021eaca56082b3ed01ffb347094d30ddac40
 - leeroy-app -> leeroy-app:0f2d5e66678d59ee59471543f42c7aa9928661f4aee8bfa4dd909a29bac2e9f3
 - base -> base:96c1b5563b0f75820828837b63788f998b80db57297cb2f1ea8c4a2ca589aeed
Starting deploy...
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/docker.(*PortManager).getPorts(0xc000a40980, {0xc000a3e330, 0xa}, {0xc000488b90, 0x2, 0x2}, 0xc000a24780)
	/Users/tejaldesai/workspace/skaffold/pkg/skaffold/deploy/docker/port.go:94 +0x5f8
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/docker.(*Deployer).deploy(0xc000635810, {0x6f14e18, 0xc000402840}, {0x6ed3940, 0xc0001183c0}, {{0xc000a3e330, 0xa}, {0xc0006da0f0, 0x4b}})
	/Users/tejaldesai/workspace/skaffold/pkg/skaffold/deploy/docker/deploy.go:157 +0x6e5
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/docker.(*Deployer).Deploy(0xc000635810, {0x6f14e18, 0xc000402840}, {0x6ed3940, 0xc0001183c0}, {0xc000652480, 0x3, 0x4})
	/Users/tejaldesai/workspace/skaffold/pkg/skaffold/deploy/docker/deploy.go:124 +0x3d2
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.DeployerMux.Deploy({0x0, {0xc000488bc0, 0x1, 0x1}}, {0x6f14e18, 0xc000402840}, {0x6ed3940, 0xc0001183c0}, {0xc000652480, 0x3, ...})
	/Users/tejaldesai/workspace/skaffold/pkg/skaffold/deploy/deploy_mux.go:123 +0x3e3
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.withTimings.Deploy({{0x6ef0990, 0xc000a409c0}, {0x6ef7998, 0xc00012e300}, {0x6f55e48, 0xc0003e6380}, 0x1}, {0x6f14e18, 0xc00032fad0}, {0x6ed3940, ...}, ...)
	/Users/tejaldesai/workspace/skaffold/pkg/skaffold/runner/timings.go:85 +0x162
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner/v1.(*SkaffoldRunner).Deploy(0xc000b86000, {0x6f14e18, 0xc00032fad0}, {0x6ed3940, 0xc000b321e0}, {0xc000652480, 0x3, 0x4})
	/Users/tejaldesai/workspace/skaffold/pkg/skaffold/runner/v1/deploy.go:114 +0xa47
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner/v1.(*SkaffoldRunner).Dev(0xc000b86000, {0x6f14d70, 0xc000578080}, {0x6ed3940, 0xc000b5e280}, {0xc00012e360, 0x3, 0x3})
	/Users/tejaldesai/workspace/skaffold/pkg/skaffold/runner/v1/dev.go:329 +0x1d7c
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runDev.func5({0x6f58720, 0xc000b86000}, {0xc000a51a90, 0x1, 0x1})
	/Users/tejaldesai/workspace/skaffold/cmd/skaffold/app/cmd/dev.go:71 +0x16f
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner({0x6f14d70, 0xc000578080}, {0x6ed3940, 0xc000b5e280}, 0xc000e11548)
	/Users/tejaldesai/workspace/skaffold/cmd/skaffold/app/cmd/runner.go:55 +0x20d
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runDev({0x6f14d70, 0xc000578080}, {0x6ed3940, 0xc000b5e280})
	/Users/tejaldesai/workspace/skaffold/cmd/skaffold/app/cmd/dev.go:66 +0x345
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0x0, {0x1, 0xc00064f680, 0xc000b320a0})
	/Users/tejaldesai/workspace/skaffold/cmd/skaffold/app/cmd/commands.go:135 +0x9a
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.applyPostRunHooks.func1(0xc000b1ab00, {0xc0003b3460, 0x0, 0x1})
	/Users/tejaldesai/workspace/skaffold/cmd/skaffold/app/cmd/commands.go:164 +0x6e
github.com/spf13/cobra.(*Command).execute(0xc000b1ab00, {0xc0003b3450, 0x1, 0x1})
	/Users/tejaldesai/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0xaf0
github.com/spf13/cobra.(*Command).ExecuteC(0xc000b2b900)
	/Users/tejaldesai/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x8b3
github.com/spf13/cobra.(*Command).Execute(0xc000b2b900)
	/Users/tejaldesai/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902 +0x2f
github.com/spf13/cobra.(*Command).ExecuteContext(0xc000b2b900, {0x6f14d70, 0xc000578080})
	/Users/tejaldesai/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:895 +0x73
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run({0x6ed2b60, 0xc000010018}, {0x6ed2b60, 0xc000010020})
	/Users/tejaldesai/workspace/skaffold/cmd/skaffold/app/skaffold.go:47 +0x492
main.main()
	/Users/tejaldesai/workspace/skaffold/cmd/skaffold/skaffold.go:50 +0x2bd
➜  microservices git:(main) ✗ 
````
