### ISSUE TITLE
Remote chart from private repo not being fetched

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [GoogleContainerTools/skaffold#6624]
### Expected behavior

Skaffold running when pointed to a private GitHub repo that holds `helm` charts

(note: not talking about a `helm` repo, but a plain GH repo holding the chart files, `templates`, `Chart.yaml` etc)

### Actual behavior

Skaffold not fetching the helm chart

### Information

- Skaffold version: 
```
▶ skaffold version
v1.32.0
```

- Operating system: 
```
MacOS BigSur
```

- Installed via: 

```
brew install skaffold
```

- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: something
deploy:
  helm:
    releases:
    - name: ingestion-server
      # remote: true
      chartPath: path/to/the-specific-helm-chart-I-want-to-deploy
      remoteChart: git@github.com:myorg/myhelmcharts.git?ref=master```
```

Note that

- I have `ssh`- based access to `git@github.com:myorg/myhelmcharts.git`
- The repo holds various charts, that's why I am attempting to deploy

```
chartPath: path/to/the-specific-helm-chart-I-want-to-deploy
```
