### ISSUE TITLE
Add `imageStrategy.tag`: for charts requiring a separate tag field

### ISSUE THREAD

**Issue by snickell** [GoogleContainerTools/skaffold#6646]
The JupyterHub helm chart (aka Z2JH) specifies chart images using only the `name` and `tag` values, with a strict schema preventing the use of a `repository` field. 

I've encountered a number of large charts that similarly do not support the repository field (though of course, most do) on one or more image values. As JSON schema validation becomes more common with helm3, this may become an increasing obstacle to using skaffold to properly version the artifacts output for derived sub-charts that don't permit the repository field in their image schemas.

```
build:
  artifacts:
    - image: gcr.io/my-project/my-image
deploy:
  helm:
    releases:
      - name: my-chart
        chartPath: helm
        artifactOverrides:
          image.tag: gcr.io/my-project/my-image
        imageStrategy:
          tag: {}
```

might output `values.yaml` like:
```
image:
    tag: latest
    
```

As an alternative, perhaps it would be possible to support a helm imageStrategy option similar to `explicitRegistry`, but supressing output of the `repository` attribute on image values from skaffold/helm, such as `imageStrategy.helm.includeRepository: false`
