### ISSUE TITLE
Use `gcr.io/kaniko-project/executor` from within a cloudbuild.yaml `gcr.io/k8s-skaffold/skaffold` step?

### ISSUE THREAD

**Issue by snickell** [GoogleContainerTools/skaffold#6653]
We currently use `skaffold` from within a `cloudbuild.yaml` step (using `gcr.io/k8s-skaffold/skaffold`) to build a complex image, that would benefit immensely from kaniko's layer caching.

- `cloudbuild.yaml` is triggered by pushing to GitHub branches on the git repo
- the git repo is a couple gigabytes, i.e. we do NOT want to do a `gsutil cp`, so we can't use skaffold's built-in googleCloudBuild which transfers the current docker context from the local dev machine.

As far as I can tell, skaffold's kaniko implementation is only k8s cluster based. Is there any provision for running a kaniko build in the local container host using `gcr.io/kaniko-project/executor`? Or is there a better way to trigger a cloudbuild.yaml that in turn uses the local cloudbuild context to run an image build using kaniko?

For example, our current `skaffold.yaml` is like so:
```
build:
  artifacts:
    - image: gcr.io/my-org/my-giant-image
       docker: {}
```

And is triggered from a `cloudbuild.yaml` by github pushes like so:
```
  - name: gcr.io/k8s-skaffold/skaffold
    args: ["skaffold", "build"]
```

We'd like to transition to kaniko from skaffold, but this doesn't currently seem possible?
```
build:
  artifacts:
    - image: gcr.io/my-org/my-giant-image
       kaniko: {}
   cluster:
      noClusterJustUseLocalExecutor: true # how do I do this??
```
