### ISSUE TITLE
`apply` and `deploy` are not checking deployment health

### ISSUE THREAD

**Issue by ekupershlak** [GoogleContainerTools/skaffold#6657]
### Expected behavior
Running `skaffold apply` on the output of `skaffold render` or `skaffold deploy` without building should check deployment health. If the resulting pods fail to come up (i.e. because the images don't exist) the command should fail.

### Actual behavior
The command succeeds and indicates that the deployments have stabilized.

### Information

- Skaffold version: v1.32.0
- Operating system: Linux
- Installed via: curl from skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
  - image: hooks-example
deploy:
  kubectl:
    manifests:
      - deployment.yaml
```

- deployment.yaml contents

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooks-example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooks
  template:
    metadata:
      labels:
        app: hooks
    spec:
      containers:
      - name: hooks-example
        image: hooks-example
```

### Steps to reproduce the behavior

1. Edit the `skaffold/examples/lifecycle-hooks` example skaffold.yaml to match the above yaml
2. `skaffold render --offline --digest-source=none --output=manifest.yaml` 
3. `skaffold apply manifest.yaml` 

Alternatively:

2. `skaffold deploy --images hooks-example:foo`

Logs attached
[ex2.txt](https://github.com/GoogleContainerTools/skaffold/files/7262309/ex2.txt)
[ex1.txt](https://github.com/GoogleContainerTools/skaffold/files/7262310/ex1.txt)
