### ISSUE TITLE
Combined logger pod selector.

### ISSUE THREAD

**Issue by shanna** [GoogleContainerTools/skaffold#666]
In my project I have pods that are started with skaffold but don't have build artifacts such as my traefik ingress controller I'd love to be able to see the logging for in the combined logs. It would be helpful if you could configure skaffold with selectors to log an entire application label or namespace not just the build artifact pods.

Prior art:
* https://github.com/bakins/kube-log-tail takes a selector though it suffers issues when pods are replaced/restarted.

**Comment by r2d4** [comment]
+1

Not sure how the UX on this looks - possibly another top level `log` map?


```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
log:
  labels:
    app: redis
```
