### ISSUE TITLE
A dive into file sync performance

### ISSUE THREAD

**Issue by RasmusWernerLarsen** [GoogleContainerTools/skaffold#6660]
I've been looking into optimizing skaffold performance wise for our scenario, specifically the file sync mechanism.

First a bit of background, the application is mostly PHP and JS, meaning that for most assets we can just do filesyncs for our changes, so we're heavily relying on that. Skaffold is doing a good job, but there is a significant delay on the file sync mechanism.

I've done some debugging into Skaffold and even after some behavior specific optimizations (Creating a separate development docker image to avoid using multistage images), we're seeing file sync times of ~3 seconds. This is probably really good for most projects, but is suboptimal for the development behavior of many php developers.

Now after digging into skaffold I found that the long sync time is caused by reparsing of the image build resources (dockerfile and .dockerignore in our case), which is done before a file sync is triggered. This happens inside the listener (part of the runner), where it triggers the l.sourceDependenciesCache.Reset() function, which causes all this extra work for each sync.

After removing this in a test build, sync times go from ~3 seconds, to nearly instant or atleast close to 1 second which is sufficient for our usecase. Not doing the dependency reset is fine, since changes that affect the build dependencies are rare enough that we can reasonably ask people to restart skaffold when they do change it.

Ofcourse this change should never go into your tree, but I'm looking for ideas for a patch that would be accepted. I have a few thoughts on some ideas, and I'm happy to do some work to implement it if it's something that could be accepted.

1: Current the build dependency class is disabled unconditionally, but for most modules it should be possible to detect whether the build dependencies have actually changed. Eg. the decision should be pushed to the module, if possible.

2: Perhaps just add a flag. I considered whether the current "AutoDeploy" option should actually disable this cache clear, but I don't understand skaffold well enough to know whether that would be correct, but if we're not going to redeploy, ever, why would we clear the cache on changes?

Any perspective you could provide would be appreciated.

### Information

- Skaffold version: v.1.32.0-18
- Operating system: macOS 11.5.2
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta21
kind: Config
deploy:
  helm:
    releases:
      - name: webshop
        chartPath: ci/helm/webshop
        valuesFiles:
        - skaffold.webshop.values.yml
        setValues:
          deploymentName: local
        artifactOverrides:
          imageOverride: docker.jysk.com/webdev-aws/webshop-drupal
          ssrImageOverride: docker.jysk.com/webdev-aws/webshop-ssr
        imageStrategy:
          fqn: {}
build:
  local:
    concurrency: 2
  artifacts:
    - image: docker.jysk.com/webdev-aws/webshop-drupal
      context: .
      docker:
        dockerfile: Dockerfile-dev
        target: dev
        buildArgs:
          BASEREPOSITORY: docker.jysk.com/webdev-aws/webshop-drupal
      sync:
        manual:
        - src: '**/*'
          dest: /data/www/webshop
    - image: docker.jysk.com/webdev-aws/webshop-ssr
      context: ssr
      docker:
        dockerfile: Dockerfile-dev
        target: dev
        buildArgs:
          BASEREPOSITORY: docker.jysk.com/dockerhub/library/node
      sync:
        manual:
        - src: 'build/*'
          dest: /usr/src/app
portForward:
- resourceType: service
  resourceName: webshop
  port: 8080
  localPort: 8080
- resourceType: service
  resourceName: varnish
  port: 8080
  localPort: 8081

profiles:
- name: disable_synchronization
  patches:
    - op: remove
      path: /build/artifacts/0/sync
    - op: remove
      path: /build/artifacts/1/sync
```
