### ISSUE TITLE
skaffold dev immediately rebuilds after deploying when two artifacts have the same workspace

### ISSUE THREAD

**Issue by louis-murray** [GoogleContainerTools/skaffold#667]
I'm helping a coworker setup skaffold on their repo and they have two dockerfiles setup at the root of their project one named the standard `Dockerfile` and one named `Dockerfile.acceptance`. When I setup `artifacts` with an entry for each `skaffold dev` restarts the process of building the images and deploying as soon as it finished deploying from the previous pass. 

### Expected behavior
`skaffold dev` runs once then waits for changes
### Actual behavior
`skaffold dev` runs, then immediately starts running again when no changes were made
### Information

- Skaffold version: checked on 0.6.0, 0.7.0 and HEAD
- Operating system: OSX 10.13
- Contents of skaffold.yaml:

```yaml
kind: Config
build:
  tagPolicy:
    sha256: {}
    gitCommit: {}
  artifacts:
  - imageName: <private docker registry>/image1
    workspace: .
    docker: {}
  - imageName: <private docker registry>/image2
    workspace: .
    docker:
      dockerfilePath: Dockerfile.acceptance
  local: {}
deploy:
  helm:
    releases:
      # the name your chart will be installed as
    - name: example
      chartPath: k8s/example
      namespace: dev
      values:
        image: <private docker registry>/image1
        test.image: <private docker registry>/image2
```

### Steps to reproduce the behavior

1. have `skaffold.yaml` with artifacts that both point to the same workspace
2. run `skaffold dev`
