### ISSUE TITLE
[EPIC] Skaffold Cloud Deploy support

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#6686]
This is a tracker issue for supporting  Cloud deploy. 
See -> https://cloud.google.com/deploy/docs/skaffold

**Comment by tejal29** [comment]
this is closed now. All dependencies have been implemented and tested!!!

**Comment by kotapeter** [comment]
Should the `lifecycle-hooks` also work in cloud deploy? I have the following `skaffold.yaml` but it does not trigger the hooks 🤔 

```
apiVersion: skaffold/v2beta25
kind: Config
profiles:
  - name: dev
    deploy:
      kubectl:
        manifests:
          - "kubernetes/*.yaml"
        hooks:
          before:
            - container:
                command: ['npx', 'prisma', 'migrate', 'deploy']
                containerName: mycontainer*
                podName: mypod*
            - container:
                command: ["sh", "-c", "echo pre-deploy container hook running on $(hostname)!"]
                containerName: mycontainer*
                podName: mypod*
          after:
            - container:
                command: [ "sh", "-c", "echo post-deploy container hook running on $(hostname)!" ]
                containerName: mycontainer*
                podName: mypod*
```
