### ISSUE TITLE
Local cluster detection should depend on activated profile.

### ISSUE THREAD

**Issue by maingoh** [GoogleContainerTools/skaffold#6699]
### Expected behavior

Base the local detection on the `profile.kubeContext` first, then fallback to `kubectl config current-context` if no profile are activated.

### Actual behavior

I have a skaffold manifest containing the following profiles:
```
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kubeContext: kind-foo

  - name: prod
    activation:
      - command: run
    deploy:
      kubeContext: remote
```

If my current kubectl config point to kind, and I run `skaffold run`, the images won't be pushed and the deployment on my remote cluster will fail.
If my current kubectl config point to the remote context, and I run `skaffold dev`, the images won't be loaded into kind and the local deployment will also fail.
