### ISSUE TITLE
[proposal] Support for multiple values files for a helm release

### ISSUE THREAD

**Issue by stevenbarragan** [GoogleContainerTools/skaffold#672]
I'm trying to use skaffold with [helm secrets](https://github.com/futuresimple/helm-secrets) and besides other things it generates a decrypted yaml file to pass to helm, for example to do an upgrade.

```bash
helm upgrade -f values-file.yaml -f decrypted-values-file.yaml.dec ...
```

### Actual behavior

```yaml
...
deploy:
  helm:
    releases:
      - chartPath: chart
        valuesFilePath: chart/values-qa.yaml
...
```

### Proposed behavior
```yaml
...
deploy:
  helm:
    releases:
      - chartPath: chart
        valuesFilePath:
          - chart/values-qa.yaml
          - chart/other-values.yaml
...
```

Each file under the `valuesFilePath` will be passed to helm.

I dig into the code, it seems kind of straight forward but I'm not too familiar with go, it seems that the part that needs to be updated will be [helm.go#L146](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/helm.go#L146), is there a way to set this key to either an string or an array and make it work both ways? if not, should we add a valuesFilePath**s** to support an array since it'd a breaking change?
