### ISSUE TITLE
Skaffold deploy loads kubecontext before hooks

### ISSUE THREAD

**Issue by okgolove** [GoogleContainerTools/skaffold#6726]
If you want to set hook to generate kubeconfig file you won't be able to deploy via Skaffold because it loads kubecontext on start. I'm not sure this is a bug but I'd like to discuss this behaviour a bit.

### Expected behavior
Hook has been run, kubeconfig has been generated by the hook, Skaffold works with generated kubeconfig

### Actual behavior
Skaffold tries to use in-cluster servicetoken because context was loaded before hooks

### Information

- Skaffold version: v1.33.0
- Operating system: Debian GNU/Linux 10 (buster)
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta24
kind: Config
build:
  artifacts:
    - image: gcr.io/example/example
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: example
        chartPath: chart/example
        artifactOverrides:
          image: gcr.io/example/example
        wait: true
        imageStrategy:
          helm: {}
    hooks:
      before:
        - host:
            command:
              - /bin/sh
              - -c
              - gcloud container clusters get-credentials example --project example --region us-central1
            os:
              - linux
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold deploy --tag latest`
