### ISSUE TITLE
Permission denied when getting image from Artifact Registry using Cloud Build

### ISSUE THREAD

**Issue by ChaseMor** [GoogleContainerTools/skaffold#6743]
### Expected behavior
Deployment shouldn't error out.

### Actual behavior
Get the following error after pushing to image repo
```
getting image id from finished build: getting image: GET https://REGION-docker.pkg.dev/v2/token?scope=repository%3APROJECT-NAME%2FREPO-NAME%2Fnodejs-hello-world%3Apull&service=REGION-docker.pkg.dev: DENIED: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/PROJECT-NAME/locations/REGION/repositories/REPO-NAME" (or it may not exist)
Skaffold exited with code 1.
```
### Information

- Skaffold version: v1.32.0
- Operating system: Linux
- Installed via: Cloud Code 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: nodejs-hello-world
  googleCloudBuild: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
```

### Steps to reproduce the behavior

1. Open Cloud Code for VS Code
2. Clone the Kubernetes sample nodejs HelloWorld
3. Add `googleCloudBuild` to the `skaffold.yaml` to use Cloud Build
4. Add the path to an Artifact Registry repo to the value of the `imageRegistry` field in the `.vscode/launch.json`
5. Try to `Run on Kubernetes`

Could also repro using `skaffold run` with `skaffold.yaml` configured for Cloud Build and `--default-repo` set to an Artifact Registry repo. Using Cloud Code was just how I encountered this bug.
