### ISSUE TITLE
bug: --iterative-status-check flag seems to be ignored

### ISSUE THREAD

**Issue by souravdasslg** [GoogleContainerTools/skaffold#6746]
### Expected behavior
As the docs says, if `--iterative-status-check=true` is passed, deployment should be configured one by one and wait before the next deployment till the last one is stabilised.
### Actual behavior
Seems like this option has no effect on deployment behaviour. All the deployments are being done at once.
### Information
We are passing the flag simply through cli
`skaffold run --iterative-status-check=true`
- Skaffold version: 
- v1.33.0
- Operating system: 
- Ubuntu  20.04.3
- Installed via:  Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: skaffold-api
build:
  googleCloudBuild: {}
  artifacts:
    - image: gcr.io/sample-org/auth-api
      context: .
      docker:
        dockerfile: build/auth-service/Dockerfile.api
deploy:
  kubectl:
    manifests:
      - build/auth-service/api-deployment.yaml

```
