### ISSUE TITLE
SyncMap is not supported by this builder - sync infer - custom script

### ISSUE THREAD

**Issue by itzmanish** [GoogleContainerTools/skaffold#6772]
### Expected behavior
Should sync the local files to remote after changes on local file.

### Actual behavior
showing error - `SyncMap is not supported by this builder`

### Information

- Skaffold version: v1.29.0
- Operating system: Arch LInux  5.10.73-1-lts
- Installed via: skaffold dev
- Contents of skaffold.yaml:

```yaml
build:
      artifacts:
        - image: registry-image-url
          context: .
          custom:
            buildCommand: sh buildx.sh -f Dockerfile.dev
            dependencies:
              paths:
                - dist/**/*
          sync:
            infer:
              - dist/**/*
```

buildx.sh -
```shell
#!/bin/sh
# This script demonstrates how to use `docker buildx` to build container
# images for the linux/amd64 and linux/arm64 platforms.  It creates a
# `docker buildx` builder instance when required.
#
# If you change the platforms, be sure to
#
#  (1) delete the buildx builder named `skaffold-builder`, and
#  (2) update the corresponding node-affinities in k8s/pod.yaml.

# The platforms to build.
platforms="linux/amd64,linux/arm64" 

# `buildx` uses named _builder_ instances configured for specific platforms.
# This script creates a `skaffold-builder` as required.
if ! docker buildx inspect skaffold-builder >/dev/null 2>&1; then
  docker buildx create --name skaffold-builder --platform $platforms
fi

# Building for multiple platforms requires pushing to a registry
# as the Docker Daemon cannot load multi-platform images. 
if [ "$PUSH_IMAGE" = true ]; then
  args="--platform $platforms --push"
else
  args="--load"
fi

set -x      # show the command-line
docker buildx build --builder skaffold-builder --tag $IMAGE $args "$BUILD_CONTEXT"
```

### Steps to reproduce the behavior

1. clone https://github.com/GoogleContainerTools/skaffold/tree/main/examples/custom-buildx
2. add sync infer in skaffold.yaml with a dummy file in current working folder
3. add a line `COPY dummy-file .` in Dockerfile
3. do skaffold dev
4. Edit the file that you added on sync block of skaffold.yaml
5. You will get a error `WARN[0198] error adding dirty artifact to changeset: inferring syncmap for image "sensitive-image-url": SyncMap is not supported by this builder `

**Comment by nkubala** [comment]
@itzmanish thanks for the issue. this error is happening because you need to explicitly declare your `Dockerfile` as part of your dependencies in the `custom` stanza in your skaffold.yaml:

```yaml
build:
  custom:
    dependencies:
      dockerfile: Dockerfile
```

this was not very clear from the error message being surfaced, so i opened a PR to improve it. let me know if you're still seeing this error after updating your skaffold.yaml, otherwise i'll close this issue when that PR gets merged.

**Comment by briandealwis** [comment]
The inferred sync needs the dockerfile to determine where to copy the files, such as a `COPY . /some/path`.  Without a dockerfile, the sync can't infer where to copy matching files.  If you don't have a dockerfile, you can specify manual sync rules instead.

**Comment by itzmanish** [comment]
Thanks @nkubala . Let me try your suggestions and will update here.

**Comment by itzmanish** [comment]
There is slight change in the skaffold.yaml 
```yaml
build:
  custom:
    dependencies:
      dockerfile: 
        path: Dockerfile
```
And yes this works.
