### ISSUE TITLE
Use Docker Base Image Without Pushing to Registry

### ISSUE THREAD

**Issue by jklaw90** [GoogleContainerTools/skaffold#6816]
### Expected behavior
I'd expect to be able to use base images without pushing them up to the registry.
ideally we could define that like we can with `noPush: false` like we can with kaniko
My base image really just adds the source go code and gets the dependencies shared between multiple of my artifacts. 
```
  - image: registry123xyz/cc-cli
    docker:
      dockerfile: cmd/cli/Dockerfile
    requires:
      - image: registry123xyz/base-builder
        alias: BASE_BUILDER
  - image: registry123xyz/base-builder
    docker:
      dockerfile: cmd/Dockerfile
```
### Actual behavior
I have to push the base image to the registry.

### Information

- Skaffold version: v1.33.0
- Operating system: linux
- Installed via: 
- Contents of skaffold.yaml:
