### ISSUE TITLE
Templated Fields do not honour the UID environment variable

### ISSUE THREAD

**Issue by hammady** [GoogleContainerTools/skaffold#6848]
### Expected behavior

Evaluating the environment variable `{{.UID}}` in the templated fields and generating the user id running the skaffold process.

### Actual behavior

The value is always empty, although the terminal running the `skaffold run` command outputs the correct value (`echo $UID`).
Bridging the value into another variable called `USER_ID` does work (`USER_ID=$UID skaffold run`).

### Information

- Skaffold version: v1.34.0
- Operating system: Ubuntu 20.04.3 LTS
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta7
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: dev
    docker: {}
deploy:
  helm:
    releases:
    - name: dev
      namespace: dev
      chartPath: helm/dev
      artifactOverrides:
        workers.dev.image: dev
      setValueTemplates:
        workers.dev.volumes.source.hostPath: "{{.PWD}}" # this works
        #workers.dev.securityContext.runAsUser: "{{.USER_ID}}" # this works
        workers.dev.securityContext.runAsUser: "{{.UID}}" # does NOT work
```

The above assumes the templates read the overriden values and sets them in the pod security context.
 
### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold run`
3. Inspect the security context of the pod: empty
