### ISSUE TITLE
skaffold returns x509 while using buildx script, while buildx works without skaffold

### ISSUE THREAD

**Issue by ianbuilds** [GoogleContainerTools/skaffold#6857]
### Expected behavior

`skaffold dev` with custom build script to build and push to secured private repo like `docker buildx` does independently of skaffold.

### Actual behavior

1. buildx cmd successfully pushes to secured private repo
2. skaffold dev returns error: x509 certificate signed by unknown authority

### Information

- Skaffold version: v1.34.0
- Operating system: macOS Big Sur 11.4
- Installed via: homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
  - image: skaffold-example
    context: .
    custom:
      buildCommand: ./build.sh
deploy:
  kubectl:
    manifests:
      - k8s-*
```

- Contents of build.sh:

```
#!/usr/bin/env bash

docker buildx build \
  --platform linux/amd64 \
  --tag $IMAGE \
  --push \
  $BUILD_CONTEXT
```

### Steps to reproduce the behavior

1. skaffold/examples/getting-started
2. `skaffold dev --default-repo my-secured-private-repo`

### Additionally

1. I've attempted the same with the skaffold/examples/custom-buildx and received the same results
2. The cmd:

`docker buildx build --platform linux/amd64 --tag my-secured-private-repo/skaffold-example --push .`

successfully pushes to the private repo.

3. skaffold dev without the custom build script also pushes to the repo successfully. Suspect it has something to do with how skaffold checks for certs with a custom build cmd.
