### ISSUE TITLE
Skaffold apply deployments never stabilize on Skaffold 1.35  

### ISSUE THREAD

**Issue by edwardthiele** [GoogleContainerTools/skaffold#6870]
Using the manifest file "manifest.xml"
```
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
spec:
  containers:
  - image: k8s.gcr.io/echoserver:1.4
    name: echoserver
```

with the command:
```
/usr/local/bin/skaffold apply 'manifest.yaml'
```

skaffold apply 'manifest.yaml'
Starting deploy...
 - pod/getting-started configured
Waiting for deployments to stabilize...
 - pods: could not stabilize within 10m0s
 - pods failed. Error: could not stabilize within 10m0s.

The actual deployment appears to work as expected

### Expected behavior

The deployment reports success 

### Actual behavior

The command times out

### Information

- Skaffold version: 1.35
- Operating system: Linux
- Installed via: skaffold.dev
