### ISSUE TITLE
`setValueTemplates` doesn't support nested arrays of objects

### ISSUE THREAD

**Issue by samgomena** [GoogleContainerTools/skaffold#6883]
### Actual behavior

Using `setValueTemplates` to override values that are an array of objects produces incorrect CLI flags for helm.

For instance, given the following yaml:

```yaml
setValueTemplates:
  users:
    username1:
      - type: topic
        name: "topic-{{ .USER }}"
        operation: Write
      - type: group
        name: "group-{{ .USER }}"
        operation: Read
    username2:
      - type: transactionalId
        name: "transactional-id-{{ .USER }}"
        operation: Read
```

The `--set` flags passed to helm are:

```sh
--set users.username1=[map[name:topic-sgomena operation:Write type:topic] map[name:group-sgomena operation:Read type:group]] 
--set users.username2=[map[name:transactional-id-sgomena operation:Read type:transactionalId]]]
```

### Expected behavior

I would expect that Skaffold should be able to handle this but I'm also curious if there was a decision to specifically _not_ handle this scenario due to the arbitrary complexity one can craft up with yaml.

However, ideally, I would like to see Skaffold generate this:

```sh
--set users.username1[0].type=topic
--set users.username1[0].name="topic-sgomena"
--set users.username1[0].operation=Write
--set users.username1[1].type=group
--set users.username1[1].name="topic-sgomena"
--set users.username1[1].operation=Read
--set users.username2[0].type=transactionalId
--set users.username2[0].name="transactional-id-sgomena"
--set users.username2[0].operation=Read
```

And, looking at the source, I _think_ [this is the function](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/schema/util/util.go#L102-L125) ultimately responsible for creating the map of values that the helm deployer uses, which doesn't appear to support arrays.

FWIW, I worked out a fix for this specific case [here](https://github.com/samgomena/skaffold/commit/ad63e09e426739a40fc3d46df01318d804754618). If this is a bug with Skaffold (and not just something unsupported), I'd be happy to open up a PR!

### Information

- Skaffold version: `v1.34.0` and `v1.35.0`
- Operating system: macOs 11.6 (Big Sur)
- Installed via: `brew install skaffold`
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: samgomena/set-value-templates-error-repro
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: set-value-templates-error-repro
        chartPath: ./repro-chart
        artifactOverrides:
          image.repository: samgomena/set-value-templates-error-repro
        setValueTemplates:
          users:
            username1:
              - type: topic
                name: "topic-{{ .USER }}"
                operation: Write
              - type: group
                name: "group-{{ .USER }}"
                operation: Read
            username2:
              - type: transactionalId
                name: "transactional-id-{{ .USER }}"
                operation: Read

```

### Steps to reproduce the behavior

1. Clone the repo [here](https://github.com/samgomena/skaffold-set-value-templates-errors-repro).
2. Run `skaffold render`

`skaffold render -v debug` logs:

<summary>
<details>
<pre>
skaffold render -vdebug
DEBU[0000] skaffold API not starting as it's not requested  subtask=-1 task=DevLoop
INFO[0000] Skaffold &{Version:v1.34.0 ConfigVersion:skaffold/v2beta25 GitVersion: GitCommit:22cfab75ffb305e7af220910af2f48d0a5c0e6af BuildDate:2021-10-27T00:20:49Z GoVersion:go1.17.2 Compiler:gc Platform:darwin/amd64 User:}  subtask=-1 task=DevLoop
DEBU[0000] Disable housekeeping messages for command explicitly  subtask=-1 task=DevLoop
DEBU[0000] parsed 1 configs from configuration file /Users/sgomena/Documents/repos/dev/skaffold-set-value-templates-errors-repro/skaffold.yaml  subtask=-1 task=DevLoop
DEBU[0000] Defaulting build type to local build          subtask=-1 task=DevLoop
INFO[0000] Using kubectl context: testing                subtask=-1 task=DevLoop
INFO[0000] Loaded Skaffold defaults from "/Users/sgomena/.skaffold/config"  subtask=-1 task=DevLoop
DEBU[0000] Running command: [minikube version --output=json]  subtask=-1 task=DevLoop
DEBU[0000] Command output: [{"commit":"76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b","minikubeVersion":"v1.24.0"}]  subtask=-1 task=DevLoop
DEBU[0000] Running command: [/usr/local/bin/minikube profile list -o json --user=skaffold]  subtask=-1 task=DevLoop
DEBU[0001] Command output: [<elided>]  subtask=-1 task=DevLoop
DEBU[0001] Running command: [/usr/local/bin/minikube profile list -o json --user=skaffold]  subtask=-1 task=DevLoop
DEBU[0001] Command output: [<elided>]  subtask=-1 task=DevLoop
DEBU[0001] setting Docker user agent to skaffold-v1.34.0  subtask=-1 task=DevLoop
DEBU[0001] Running command: [helm version --client]      subtask=-1 task=DevLoop
DEBU[0001] Command output: [version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}]  subtask=-1 task=DevLoop
DEBU[0001] Using builder: local                          subtask=-1 task=DevLoop
DEBU[0001] push value not present in NewBuilder, defaulting to true because cluster.PushImages is true  subtask=-1 task=DevLoop
INFO[0001] build concurrency first set to 1 parsed from *local.Builder[0]  subtask=-1 task=DevLoop
INFO[0001] final build concurrency value is 1            subtask=-1 task=DevLoop
DEBU[0001] Running command: [git describe --tags --always]  subtask=-1 task=Build
DEBU[0001] Command output: [146de0f]                    subtask=-1 task=Build
DEBU[0001] Running command: [git status . --porcelain]   subtask=-1 task=Build
DEBU[0001] Command output: [?? Dockerfile?? repro-chart/?? skaffold.yaml]  subtask=-1 task=Build
INFO[0001] Tags generated in 24.805035ms                 subtask=-1 task=Build
DEBU[0003] Executing template &{envTemplate 0xc0002f9200 0xc00010e5f0  } with environment map[<elided>]  subtask=-1 task=DevLoop
DEBU[0003] EnvVarMap: map[DIGEST:samgomena/set-value-templates-error-repro:146de0f-dirty@sha256:0b1643a38d4869c002b5cbb5e8506f129982212d5df7745f9491a8f838e7374e DIGEST_ALGO:samgomena/set-value-templates-error-repro DIGEST_HEX:146de0f-dirty@sha256:0b1643a38d4869c002b5cbb5e8506f129982212d5df7745f9491a8f838e7374e IMAGE_DIGEST:sha256:0b1643a38d4869c002b5cbb5e8506f129982212d5df7745f9491a8f838e7374e IMAGE_NAME:samgomena/set-value-templates-error-repro IMAGE_REPO:samgomena/set-value-templates-error-repro IMAGE_TAG:146de0f-dirty]  subtask=-1 task=DevLoop
DEBU[0003] Executing template &{envTemplate 0xc0002f9e60 0xc00010e640  } with environment map[<elided>]  subtask=-1 task=DevLoop
DEBU[0003] Executing template &{envTemplate 0xc000b26b40 0xc00010e690  } with environment map[<elided>]  subtask=-1 task=DevLoop
DEBU[0003] Executing template &{envTemplate 0xc000b27680 0xc00010e6e0  } with environment map[<elided>]  subtask=-1 task=DevLoop
DEBU[0003] Executing template &{envTemplate 0xc000662120 0xc00010e780  } with environment map[<elided>]  subtask=-1 task=DevLoop
DEBU[0003] Running command: [helm --kube-context testing template set-value-templates-error-repro ./repro-chart --set-string image.repository=samgomena/set-value-templates-error-repro:146de0f-dirty@sha256:0b1643a38d4869c002b5cbb5e8506f129982212d5df7745f9491a8f838e7374e --set users.username1=[map[name:topic-sgomena operation:Write type:topic] map[name:group-sgomena operation:Read type:group]] --set users.username2=[map[name:transactional-id-sgomena operation:Read type:transactionalId]]]  subtask=-1 task=DevLoop
DEBU[0003] Running command: [tput colors]                subtask=-1 task=DevLoop
DEBU[0003] Command output: [256]                        subtask=-1 task=DevLoop
std out err: Error: template: test-chart/templates/kafkausers.yaml:10:24: executing "test-chart/templates/kafkausers.yaml" at <$userAcls>: range can't iterate over [map[name:topic-sgomena operation:Write type:topic] map[name:group-sgomena operation:Read type:group]]

Use --debug flag to render out invalid YAML
</pre>
</details>
</summary>
