### ISSUE TITLE
Conditional requires

### ISSUE THREAD

**Issue by bdudelsack** [GoogleContainerTools/skaffold#6884]
I would like to add `requires` depending on a selected profile. As I understand at the moment it's only possible to patch the main pipeline stages but not the `requires` section. 

Example: 
```yaml
profiles:
  - name: monitoring
requires:
  - path: skaffold.base.yaml
  - path: skaffold.monitoring.yaml
```
I would like to include `skaffold.monitoring.yaml` only if i activated the `monitoring` profile. 

Is this somehow possible?

**Comment by gsquared94** [comment]
It isn't possible to add a conditional requires or override the `requires` stanza in a profile. A way to do this could be to have the main pipeline be empty in `skaffold.monitoring.yaml` and have a `monitoring` profile, and conditionally activate that:

In _skaffold.monitoring.yaml_ file:
```yaml
apiVersion: v2beta22
profiles:
  - name: monitoring
     deploy: 
       kubectl:
        - monitoring.yaml
```

and in you main _skaffold.yaml_ file:
```yaml
...
requires:
  - path: skaffold.monitoring.yaml
    activeProfiles:
      - name: monitoring
        activatedBy:
         - monitoring
```
