### ISSUE TITLE
stderr: "ERROR: no nodes found for cluster 

### ISSUE THREAD

**Issue by JCzz** [GoogleContainerTools/skaffold#6907]
### Goland Cloud Code: Kubernetes

Note: I can deploy anything else using kubectl. It look like it is missing sometig in the name of the context, as the context name is "kind-kind-internet", and the error is "ERROR: no nodes found for cluster \"kind-internet\"\n"

### Error
```
Cleaning up...
loading images into kind nodes: unable to load image "go-hello-world:c57d404bd28fbee71266d45debb822dd57215b585c2e16f5b1b21b5632ee0904" into cluster: running [kind load docker-image --name kind-internet go-hello-world:c57d404bd28fbee71266d45debb822dd57215b585c2e16f5b1b21b5632ee0904]
 - stdout: ""
 - stderr: "ERROR: no nodes found for cluster \"kind-internet\"\n"
 - cause: exit status 1, 
```

### Information

skaffold version
v1.35.1
brew install skaffold

kind version
kind v0.11.1 go1.16.4 darwin/amd64

- Contents of skaffold.yaml:

```yaml
# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: go-hello-world
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
# profiles:
# - name: cloudbuild
#  build:
#    googleCloudBuild: {}

```

### Steps to reproduce the behavior
1. Run sample app from Goland "Cloud Code: Kubernetes"

Run in terminal or from Goland ui "Debug" or "Run": skaffold dev
