### ISSUE TITLE
Skaffold Profile doesn't allow to patch /deploy/helm/releases/0/setValues/global/namespace 

### ISSUE THREAD

**Issue by rstoermer** [GoogleContainerTools/skaffold#6908]
### Expected behavior

Skaffold id patching the path

### Actual behavior

I get the following error:

parsing skaffold config: failed to apply profiles to config "" defined in file "/Users/rene/repos/project/service/skaffold.yaml": applying profile "remote": invalid path: /deploy/helm/releases/0/setValues/global/namespace. There's an issue with one of the profiles defined in config "" in file "/Users/rene/repos/project/service/skaffold.yaml"; refer to the documentation on how to author valid profiles: https://skaffold.dev/docs/environment/profiles/.

### Information

- Skaffold version: v1.35.1
- Operating system: OSX 11.6.1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
build:
    local:
        push: false
        useDockerCLI: false
        useBuildkit: true
    artifacts:
        - image: registry/service
          context: .
          docker:
              dockerfile: Dockerfile
              target: local
              buildArgs:
                  NPM_TOKEN: "{{ .NPM_TOKEN }}"
          sync:
              manual:
                  # Sync all folders relevant for application development
                  - src: "src/**"
                    dest: .
deploy:
    kubeContext: docker-desktop
    helm:
      releases:
        - name: service-local
          chartPath: ../infrastructure/helm/project/localcharts/service/
          valuesFiles: ["../infrastructure/helm/project/values.yaml"]
          namespace: project-local
          setValues:
            global:
              namespace: project-local
          artifactOverrides:
              image: registry/service
portForward:
  - resourceType: deployment
    resourceName: service-deployment
    namespace: project-local
    port: 1234
    localPort: 1234
profiles:
  - name: remote
    patches:
      - op: replace
        path: /deploy/kubeContext
        value: remote-cluster
      - op: replace
        path: /deploy/helm/releases/0/setValues/global/namespace
        value: new-namespace
      - op: replace
        path: /portForward/0/namespace
        value: new-namespace
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by briandealwis** [comment]
I've hit this situation before myself, and it is difficult to diagnose. The problem is that `setValues` is actually a flat map, a set of key-value pairs where both the key and value are strings.  Skaffold represents this with a helpful helper `FlatMap` which will rewrite your  nested object:
https://github.com/GoogleContainerTools/skaffold/blob/524a6b3914101af15fadf2eb3489e578a9c71f78/pkg/skaffold/schema/util/util.go#L40-L41

So if you use `skaffold diagnose --yaml-only` you'll see your re-rendered YAML transformed as:

```yaml
setValues:
  global.namespace: project-local
```

So your example will work if you replace your JSON Patch path with
```
 - op: replace
        path: /deploy/helm/releases/0/setValues/global.namespace
        value: new-namespace
```

**Comment by kurczynski** [comment]
Not exactly what this question is asking, but similar. If you try to patch an array value from `setValues` you'll need to quote the path. So if you have:
```
deploy:
  helm:
    releasess:
      - setValues:
          someValue[0]: someValue
```

You would need to patch like this:
```
- op: replace
    path: "/deploy/helm/releasess/0/setValues/someValue[0]"
    value: someValue
```
