### ISSUE TITLE
Skaffold File Sync - Subsequent Pod Deploy

### ISSUE THREAD

**Issue by SizZiKe** [GoogleContainerTools/skaffold#6924]
### Expected behavior
Skaffold resyncs files after a breaking change causes a pod to redeploy
### Actual behavior
Skaffold doesn't do anything - it will continue to sync files to the new pod when changes are made but previous changes are ignored.
### Information

- Skaffold version: v1.33.0
- Operating system: MacOS 11.6
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
  - image: myapp
    context: myapp
    docker:
      dockerfile: myapp.Dockerfile
    sync:
      infer:
      - '**'
```

### Steps to reproduce the behavior

1. setup skaffold with file sync
2. once stable, make a change to trigger the file sync
3. delete the pod that the file was synced to
4. examine the new pod, the content isn't synced on pod standup
