### ISSUE TITLE
Can't build the dockerfile correctly on macOS M1

### ISSUE THREAD

**Issue by uynap** [GoogleContainerTools/skaffold#6927]
I have a dockerfile like below. I can build and run it by using `docker build -t spanner-emulator -f spanner.Dockerfile .` without any issue. I can also build and run it by using Skaffold on a non-M1 macOS(removing the `--platform=linux/amd64`) .
However, when I do skaffold build on macOS M1, it was successful, but when I try to use `docker run` to run the container, it gives me the following errors:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: no such file or directory
```
When I use `docker build` & `docker run` the image, it also has the warning message, but the container is running correctly. 

It seems the `Skaffold build` doesn't seriously intake the `--platform=linux/amd64` in the dockerfile. Does anyone know how to fix it?

```
ARG BUILDER_IMAGE=golang:1.17.2-buster
ARG EMULATOR_IMAGE=gcr.io/cloud-spanner-emulator/emulator:1.3.0
FROM --platform=linux/amd64 ${BUILDER_IMAGE} AS builder

WORKDIR /src
COPY go.mod go.sum ./
COPY cmd cmd
COPY internal internal
RUN go build -o /go/bin/spanner ./cmd/spanner

FROM --platform=linux/amd64 ${EMULATOR_IMAGE}
COPY --from=builder /go/bin/spanner /
ENTRYPOINT ["/spanner"]
```

- Skaffold version: v1.35.1
- Operating system: mac M1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: spanner-emulator
    docker:
      dockerfile: "spanner.Dockerfile"
```

**Comment by briandealwis** [comment]
I tried to reproduce your setup with a simple "hello world" program, the resulting container runs fine for me on my M1.  (I did encounter a lot of segfaults from the `go build` as your Dockerfile as defined causes `go build` to run under emulation, and amd64-emulated `go build` frequently breaks qemu in my experience.)

So I suspect that your app is causing `go build` to link in some additional shared libraries that exist in the `golang` image but that do not exist in the `gcr.io/cloud-spanner-emulator/emulator:1.3.0` image.  You might be able to see what's missing by running:
```
docker run --rm --env LD_TRACE_LOADED_OBJECTS=1 <your-image>
```

That should be the equivalent of running `ldd /spanner`, required since the emulator image doesn't include a shell.

Because the Go toolchain supports cross-compilation, I think you can improve your build by using Buildkit, which includes better support for cross-architecture builds.  First modify your `skaffold.yaml` to use the `docker` CLI with Buildkit:
```
apiVersion: skaffold/v2beta24
kind: Config
build:
  tagPolicy:
    sha256: {}
  local:
    useDockerCLI: true
    useBuildkit: true
  artifacts:
  - image: spanner-emulator
    docker:
      dockerfile: "Dockerfile"
      cliFlags: ["--platform", "linux/amd64"]
```

Then change your Dockerfile to use Buildkit-defined `$BUILD{PLATFORM,OS,ARCH}` and `$TARGET{PLATFORM,OS,ARCH}` build-args.  The target build-args are taken from the `--platform` flag.
```
ARG BUILDER_IMAGE=golang:1.17.2-buster
ARG EMULATOR_IMAGE=gcr.io/cloud-spanner-emulator/emulator:1.3.0
FROM --platform=$BUILDPLATFORM ${BUILDER_IMAGE} AS builder

WORKDIR /src
COPY go.mod go.sum ./
COPY cmd cmd
COPY internal internal
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o /go/bin/spanner ./cmd/spanner

FROM --platform=$TARGETPLATFORM ${EMULATOR_IMAGE}
COPY --from=builder /go/bin/spanner /
ENTRYPOINT ["/spanner"]
```
