### ISSUE TITLE
Docker builds with cliFlags should be build with docker CLI

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6929]
### Expected behavior

A skaffold.yaml with a docker build artifact specifying `cliFlags` should always use the `docker` CLI, overriding the `useDockerCLI` setting.
```
kind: Config
apiVersion: skaffold/v2beta24
build:
  artifacts:
  - image: example
    docker:
      cliFlags: ["--platform", "linux/amd64"]
```

### Actual behavior
```
$ skaffold build -v debug
...
Starting build...
Found [minikube] context, using local docker daemon.
Building [example]...
DEBU[0001] Running docker build: context: ., dockerfile: Dockerfile  subtask=example task=Build
DEBU[0003] Found dependencies for dockerfile: []         subtask=-1 task=DevLoop
Sending build context to Docker daemon  2.048kB
```

### Information

- Skaffold version: v1.34.0 (and still in HEAD)
