### ISSUE TITLE
skaffold config subcommands don't use SKAFFOLD_CONFIG

### ISSUE THREAD

**Issue by seankhliao** [GoogleContainerTools/skaffold#6932]
### Expected behavior

skaffold uses the same config file for `skaffold config` and `skaffold build`

### Actual behavior

`skaffold config` uses `~/.skaffold/config` while `skaffold build` uses the path set in the `SKAFFOLD_CONFIG` file

### Information

- Skaffold version: v1.35.0
- Operating system: `Linux eevee 5.15.5-arch1-1 #1 SMP PREEMPT Thu, 25 Nov 2021 22:09:33 +0000 x86_64 GNU/Linux`
- Installed via: Arch Linux communtiy repo
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: authd
build:
  artifacts:
    - image: ko://go.seankhliao.com/testrepo-705/cmd/p
      ko:
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
  local:
    concurrency: 0
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - deploy/*

```

### Steps to reproduce the behavior

1. `export SKAFFOLD_CONFIG=/tmp/config.yaml`
2. `skaffold config set default-repo index.docker.io/example`
3. `cat /tmp/config.yaml`
