### ISSUE TITLE
Watch changes for a specific config in multiple configs setup

### ISSUE THREAD

**Issue by dnguyenzd** [GoogleContainerTools/skaffold#6935]
### Expected behavior

I have a skaffold setup like following:

- `skaffold.yaml` contains setup for main application
```
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: my-application
requires:
- path: skaffold.dependencies.yaml
build:
  artifacts:
  - image: my-application-image
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - local/minikube.yaml
```
- `skaffold.dependencies.yaml` contains dependencies for the application like mysql, vault etc:
```
apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests:
    - local/dependencies.yaml
    hooks:
      after:
      - host:
          command:
          - ./local/scripts/setup.sh
```

When something's changed in my main application, I expect only the main application image is rebuilt and re-deployed. I understand that this behavior is desirable for some scenarios, but it would be great if skaffold can provide an option to watch and re-deploy changes in a specific config file only

### Actual behavior

Dependencies are re-deployed and post-deploy hook is re-run before main application is redeployed

### Information

- Skaffold version: 1.35.0
- Operating system: MacOS Big Sur
- Installed via: asdf
- Contents of skaffold.yaml: see above

### Steps to reproduce the behavior

see above
