### ISSUE TITLE
skaffold dev log tailing problem: doesn't output to terminal in real time

### ISSUE THREAD

**Issue by manocormen** [GoogleContainerTools/skaffold#6936]
### Expected behavior

Logs are streamed to the terminal line by line in real time.

### Actual behavior.

Logs are are streamed to the terminal all at once every ~4 minutes.

### Information

- Skaffold version: v1.35.0
- Operating system: macOS Big Sur 11.6 and Linux Ubuntu 20.04 (identical problem on both)
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hello-app
build:
  artifacts:
  - image: hello
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s.yaml
```

### Steps to reproduce the behavior

1. Clone: https://github.com/manocormen/hello-app
2. Install skaffold, kubectl, and minikube, and run `minikube start`.
3. Run `skaffold dev`

### More details

[Stack Overflow --- skaffold dev: no output to terminal (or delayed output)
](https://stackoverflow.com/questions/70229970/skaffold-dev-no-output-to-terminal-or-delayed-output)
