### ISSUE TITLE
Examples: microservices and other. 'skaffold render' not working

### ISSUE THREAD

**Issue by JCzz** [GoogleContainerTools/skaffold#6941]
Running the example: `example/microservices`

skaffold render
`failed to resolve the digest of leeroy-web:6b3fc6f-dirty: does the image exist remotely?`

Tried using local builder:
```
profiles:
  - name: kind
    build:
      local: {}
```

Still same issue
