### ISSUE TITLE
Helm 2 rebuild on requirements.lock change

### ISSUE THREAD

**Issue by charlesg99** [GoogleContainerTools/skaffold#6943]
On Skaffold v1.35.0, when a Helm 2 deploy is used, as soon as the dependency's requirements.lock file is added or changes, a rebuild is launched. Seems like #4181 was aimed at fixing this but somehow this only prevents the rebuild for the tmpcharts folder and its content, not the requirements.lock file.

### Expected behavior
No rebuild on requirements.lock change

### Actual behavior
Rebuild on requirements.lock change

### Information

- Skaffold version: v1.35.0
- Operating system: Linux, on a local KIND cluster
- Installed via: https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
- Contents of skaffold.yaml:

```
deploy:
  helm:
    releases:
    - name: project
      chartPath: helm
      artifactOverrides:
        backendImage: backend-image
        frontendImage: frontend-image
        databaseImage: database-image
      valuesFiles:
      - helm/values.yaml
      - helm/values.yaml.override
    flags:
      upgrade:
        - '--cleanup-on-fail'
```

### Steps to reproduce the behavior
Use a Helm 2 chart having a dependency, on first install the project builds twice because of the creation of the requirements.lock file
