### ISSUE TITLE
Buildpack default launch type is no longer correct

### ISSUE THREAD

**Issue by djcass44** [GoogleContainerTools/skaffold#6948]
### Expected behavior

Buildpacks will set the correct launch type.

Using a custom build method that directly calls the Pack CLI:
```
pack build "$IMAGE" \
	--builder paketobuildpacks/builder:tiny \
	--run-image paketobuildpacks/run:tiny-cnb
```
```
Setting default process type 'myapp'
Saving dev.local/myapp:2303623-dirty...
*** Images (1952faebeb1a):
      dev.local/myapp:2303623-dirty
Reusing cache layer 'paketo-buildpacks/go-dist:go'
Adding cache layer 'paketo-buildpacks/go-build:gocache'
Successfully built image 'dev.local/myapp:2303623-dirty'
```

As you can see it correctly sets the default process type to 'myapp' and the application starts up normally.

### Actual behavior

Buildpacks use the `web` launch type which is no longer set as of [Platform API 0.6](https://github.com/buildpacks/lifecycle/releases/tag/v0.11.0).

```
[exporter] Warning: default process type 'web' not present in list [myapp]
[exporter] Saving dev.local/myapp:latest...
[exporter] *** Images (5b1a84af1b52):
[exporter]       dev.local/myapp:latest
[exporter] Reusing cache layer 'paketo-buildpacks/go-dist:go'
[exporter] Adding cache layer 'paketo-buildpacks/go-build:gocache'
```

Using the Skaffold `buildpacks` config (shown in full below), Skaffold incorrectly sets the default process type to `web` which is no longer valid. This causes the application to start with error and requires manually overriding the `ENTRYPOINT`.

### Information

- Skaffold version: `v1.35.0`
- Operating system: `Amazon Linux 2`
- Installed via: GitHub Releases
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: foobar
build:
  artifacts:
    - image: dev.local/myapp
      buildpacks:
        builder: paketobuildpacks/builder:tiny
        runImage: paketobuildpacks/run:tiny-cnb
  local:
    push: false
```

### Steps to reproduce the behavior

1. Create a simple Go app
2. Add the above `skaffold.yaml`
2. `skaffold build`
3. `docker run` or deploy the app (in my environment it's to Minikube) without modifying the entrypoint
4. Notice the `failed to launch: determine start command: when there is no default process a command is required` error
