### ISSUE TITLE
re-build image after code change

### ISSUE THREAD

**Issue by JCzz** [GoogleContainerTools/skaffold#6958]
skaffold version
`v1.35.1`

Why is Skaffold not re-building image after code change?

I run `Skaffold build` after code changes. The best would be it it automatically started rebuilding when code changes is made in source code folder.

skaffold.yaml
```
build:
  artifacts:
    - image: gcr.io/<projectid>/dockerfile-micro-depend
      custom:
        buildCommand: sh buildx.sh
        dependencies:
          paths:
            - buildx.sh
  tagPolicy:
    sha256: {}
  local:
    push: true
```
