### ISSUE TITLE
Support FederatedDeployment manifest type

### ISSUE THREAD

**Issue by afoninsky** [GoogleContainerTools/skaffold#6968]
When application is deployed to federated clusters (with help of [kubefed](https://github.com/kubernetes-sigs/kubefed)) - deployment manifest should be wrapped with `FederatedDeployments`. Currently, skaffold is not aware about such deployment type.

### Expected behavior
Skaffold should update images for `FederatedDeployments `in the same way as it does with `Deployments` when using kustomize/kubectl deployment menthods

### Actual behavior
Skaffold doesn't change image tag for the following deployment after `skaffold run` as not aware about it:
```
apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
spec:
  template:
    spec:
      template:
        spec:
          containers:
            image: xxx
```
