### ISSUE TITLE
SKIP_TEST env variable in custom build not set by skip-tests

### ISSUE THREAD

**Issue by honeyAndSw** [GoogleContainerTools/skaffold#6971]
### Expected behavior
$SKIP_TEST updated along with --skip-tests flag in build.

* `skaffold build --skip-tests=true` sets $SKIP_TEST = true
* `skaffold build --skip-tests=false` sets $SKIP_TEST = false
* otherwise empty value.

This function introduced in https://github.com/GoogleContainerTools/skaffold/pull/6455

### Actual behavior
It seems like $SKIP_TEST is always true.

### Information

- Skaffold version: v1.34.0
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
  - image: ko://github.com/GoogleContainerTools/skaffold/examples/custom
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
        - "**/*.go"
        - go.mod
        - .ko.yaml
  tagPolicy:
    sha256: {}
```

### Steps to reproduce the behavior
Used examples/custom in the cloud shell.

Added `echo "$SKIP_TEST"` as a part of custom build command. [example custom build.sh](https://github.com/GoogleContainerTools/skaffold/blob/main/examples/custom/build.sh)

In the log below, _echo true_ is printing $SKIP_TEST value.

```
naheonk@cloudshell:~/cloudshell_open/skaffold-0/examples/custom$ skaffold build --skip-tests=false
Generating tags...
 - ko://github.com/GoogleContainerTools/skaffold/examples/custom -> ko://github.com/GoogleContainerTools/skaffold/examples/custom:latest
Checking cache...
 - ko://github.com/GoogleContainerTools/skaffold/examples/custom: Not found. Building
Starting build...
Building [ko://github.com/GoogleContainerTools/skaffold/examples/custom]...
+ echo true
true
++ go env GOPATH
+ '[' -x /home/naheonk/gopath:/google/gopath/bin/ko ']'
```
