### ISSUE TITLE
skaffold does not handle tilde sign under kubectl > manifests

### ISSUE THREAD

**Issue by mm-e1** [GoogleContainerTools/skaffold#6983]
Related to: https://github.com/GoogleContainerTools/skaffold/issues/2123 and https://github.com/GoogleContainerTools/skaffold/pull/2233

### Expected behavior

skaffold run should be able to use manifests from file in the home directory

### Actual behavior

skaffold fails with:

invalid skaffold config: skaffold config file "skaffold.yml" referenced file "~/.secrets/timescaledb/timescaledb-secrets.yml" that could not be found. 

Verify that file "~/.secrets/timescaledb/timescaledb-secrets.yml" referenced in config "skaffold.yml" exists and the path and naming are correct.

### Information

- Skaffold version: v1.35.1
- Operating system: mac
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: timescaledb

deploy:
  helm:
    releases:
      - name: timescaledb
        namespace: timescaledb
        createNamespace: true
        chartPath: ../../../shared/charts/timescaledb/charts/timescaledb-single
        valuesFiles:
          - ./services/timescaledb/default_values.yml
        setValues: {}

  kubectl:
    manifests:
      - ./.secrets/timescaledb/timescaledb-secrets.yml
    defaultNamespace: timescaledb

```
