### ISSUE TITLE
maven local dependency

### ISSUE THREAD

**Issue by jeusdi** [GoogleContainerTools/skaffold#6986]
### Expected behavior

Currently, this is my project structure:

```
.
├── hes-mpi-fhir-mongodb
│  ├── deployment.yaml
│  ├── pom.xml
│  ├── skaffold.yaml
│  └──  src
└── hes-spring-boot-core     <<< dependency requiered by hes-mpi-fhir-mongodb
   ├── pom.xml
   └── src

```

As you can see, I managing two maven projects.

My host building steps are:

```
$ hes-spring-boot-core > mvn clean install
$ hes-mpi-fhir-mongodb > mvn clean package
```

I mean, I first install `hes-spring-boot-core` into local repository and then I build `hes-mpi-fhir-mongodb`:

My `skaffold.yml` file is:

```lang-yaml
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hes-mpi-fhir-mongodb
build:
  artifacts:
  - image: pom-xml-image
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - deployment.yaml
```

I'm getting this message, when I'm trying to build image:

```
...
[builder] Running "/layers/google.java.maven/maven/bin/mvn clean package --batch-mode -DskipTests -Dhttp.keepAlive=false --quiet"
[builder] [ERROR] Failed to execute goal on project hes-mpi-fhir-mongodb-service: Could not resolve dependencies for project cat.gencat.catsalut.hes.mpi.fhir:hes-mpi-fhir-mongodb-service:jar:0.0.1-SNAPSHOT: Could not find artifact cat.gencat.catsalut.hes:hes-spring-boot-core:jar:1.0.6 in central (https://repo.maven.apache.org/maven2)
```

It's getting me that maven builder is not able to find artifact `cat.gencat.catsalut.hes:hes-spring-boot-core:jar:1.0.6`.

How can I add this project a dependency?

I'm using skaffold `v1.35.1`

### Information

- Skaffold version: 1.35.1
- Operating system: 
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hes-mpi-fhir-mongodb
build:
  artifacts:
  - image: pom-xml-image
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - deployment.yaml

```
