### ISSUE TITLE
avoid to push image

### ISSUE THREAD

**Issue by jeusdi** [GoogleContainerTools/skaffold#6997]
Here my `skaffold.yaml`:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hes-mpi-fhir-mongodb
build:
  artifacts:
  - image: fhir-mongo
    custom:
      buildCommand: |-
        mvn clean package spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$IMAGE
        echo $PUSH_IMAGE
        if [ $PUSH_IMAGE ]; then
          docker push $IMAGE
        fi
      dependencies:
        paths:
          - src
          - pom.xml
  local:
    push: false
```

I'm facing two problems:

1. I'm setting that image have to not be push up to registry.
2. I don't quite figure out why is trying to push up to docker.io. Shouldn't it be created on local repository as `fhir-mongo:tag`?
