### ISSUE TITLE
Question: How to handle immutable tags?

### ISSUE THREAD

**Issue by afirth** [GoogleContainerTools/skaffold#6998]
## Use case
One time `Job` in same repo as code
## Question
How can I force skaffold to not modify an image tag?

## Details
Rails service runs and is deployed with skaffold. A rake task exists for bulk import. This rake task should only be run once (without further manual intervention). Manifests look like:

```yaml
kind: Job
spec: [...]
      image: myservice:v1.0.0 #do not want to update
---
kind: Deployment
spec: [...]
      image: myservice # skaffold updates as expected
```

## Options considered
1. Use a cronjob - doesn't support setting a year = will run yearly
2. Publish the image under two names - we use skaffold to publish all images
3. **Figure out how to make skaffold respect an existing tag**
4. Your idea here

## Related
It seems this is how it used to work, before the "fix" for #366

**Comment by aaron-prindle** [comment]
Unfortunately there is no good solution currently for making skaffold respect an existing tag in this case.  Currently skaffold overwrites all subsequent "image" and "label" fields in nested spec objects.  The code where this is done is here:
- https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/kubernetes/manifest/images.go#L41

There is hardcoded allowlist currently which says which top level GroupVersion+Kind values skaffold should replace the "image" and "labels" field on, code here:
- https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/kubernetes/manifest/visitor.go#L28

There was a draft design made on how this could be extended here - https://github.com/GoogleContainerTools/skaffold/pull/6236 and the solution will likely rely on giving users the extend this internal `transformableAllowList` (from `visitor.go`) and add the ability to to set this allowlist/denylist directly by the user (CLI flag or config) and to make the allowlist/denylist support JSONPath fields directly, something like this sample from the design doc:
```YAML
deploy:
This conversation was marked as resolved by shawnzhu
  config:
    transformableAllowList:
    - type: pod # no group, implicitly all versions
    - type: batch/Job # group, implicitly all versions
    - type: openfaas.com/v1/Function
      image: [spec.image]
      labels: [spec.metadata.labels, spec.labels]    # https://www.openfaas.com/blog/manage-functions-with-kubectl/
    - type: apps/v1beta1/Deployment
      image: [spec.template.spec.initContainers.*.image, spec.template.spec.containers.*.image]
      labels: [spec.metadata.labels, spec.template.metadata.labels]
```

Related issues:
#6416

**Comment by aaron-prindle** [comment]
@briandealwis can you think of any workaround for this case?

**Comment by aaron-prindle** [comment]
@afirth there is now a way to do this in the next release of skaffold (v1.37.0) using the `resourceSelector`

```
apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: my-image
      context: my-image
deploy:
  kubectl:
    manifests:
      - k8-*
resourceSelector:
  allow:
    - groupKind: "StatefulSet.apps"
      image: [".*"]
      labels: [".*"]
  deny:
    - groupKind: "StatefulSet.apps"
      labels: [".spec.volumeClaimTemplates.*.metadata.labels"] 
```

I will update this thread with the official docs once that release is out.
