### ISSUE TITLE
Feature Request - Allow Branch Name in customTemplate

### ISSUE THREAD

**Issue by vikas027** [GoogleContainerTools/skaffold#7001]
### Environment
Skaffold Version: 1.35.1
OS: Linux (Ubuntu)

### Problem
As of now, there is no easy way of getting the branch name which looks like a popular request in the [slack](https://kubernetes.slack.com/archives/CABQMSZA6) community

### Proposed
It would be good to have something like this

```yaml
    customTemplate:
      template: "{{.BRANCH}}_{{.FOO}}_{{.BAR}}"
      components:
      - name: FOO
        dateTime:
          format: "2006-01-02"
          timezone: "UTC"
      - name: BAR
        gitCommit:
          variant: AbbrevCommitSha
      - name: BRANCH
        gitBranch:
          variant: AbsoluteName  # This can be optional something which translates refs/heads/feature/xyz to xyz 
```

### Workaround
Use envTemplate as suggested [here](https://kubernetes.slack.com/archives/CABQMSZA6/p1567812874081400?thread_ts=1567796082.081300&cid=CABQMSZA6) but then we cannot use the goodness of `customTemplate` components like `dateTime` and `gitCommit` (as shown in the official [documentation](https://skaffold.dev/docs/pipeline-stages/taggers/#example-4))
