### ISSUE TITLE
Skaffold + Kaniko - Avoid pushing the image

### ISSUE THREAD

**Issue by vikas027** [GoogleContainerTools/skaffold#7007]
### Expected behavior
skaffold with kaniko to only build image, not push it

### Actual behavior
skaffold build and pushes the image

### Information

- Skaffold version: 
```
$ skaffold version
v1.35.1
```
- Operating system: 
```
Ubuntu 20.04.3 LTS (Focal Fossa)"
```

- Installed via: 
GitHub Releases

- Contents of skaffold.yaml:

```yaml
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: build-image
build:
  cluster:
<redacted>
  artifacts:
  - image: 1111111.dkr.ecr.ap-southeast-2.amazonaws.com/my-image
    kaniko:
      dockerfile: ./Dockerfile_vikas027
```

### Steps to reproduce the behavior

1. skaffold build --push=false
