### ISSUE TITLE
skaffold run some time stop unexpected

### ISSUE THREAD

**Issue by nvcnvn** [GoogleContainerTools/skaffold#7015]
### Expected behavior
`skaffold run --kube-context=$MINIKUBE_PROFILE` successfully deploy to my local cluster.
### Actual behavior
Image build canceled and nothing else.
```
#10 [gandalf-stub 2/3] RUN apk --no-cache add ca-certificates netcat-openbsd...
#10 0.595 fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
#10 1.082 fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
#10 1.227 (1/6) Installing ca-certificates (20191127-r4)
#10 1.247 (2/6) Installing nghttp2-libs (1.41.0-r0)
#10 1.251 (3/6) Installing libcurl (7.79.1-r0)
#10 1.258 (4/6) Installing curl (7.79.1-r0)
#10 1.263 (5/6) Installing libbsd (0.10.0-r0)
#10 1.266 (6/6) Installing netcat-openbsd (1.130-r1)
#10 1.270 Executing busybox-1.31.1-r21.trigger
#10 1.275 Executing ca-certificates-20191127-r4.trigger
#10 1.327 OK: 7 MiB in 20 packages
#10 DONE 1.5s

Canceled build for asia.gcr.io/xxxx/xxxx

Help improve Skaffold with our 2-minute anonymous survey: run 'skaffold survey'
To help improve the quality of this product, we collect anonymized usage data for details on what is tracked and how we use this data visit <https://skaffold.dev/docs/resources/telemetry/>. This data is handled in accordance with our privacy policy <https://policies.google.com/privacy>

You may choose to opt out of this collection by running the following command:
	skaffold config set --global collect-metrics false
```
### Information

- Skaffold version: v1.35.1
- Operating system: Linux 5.11.0-46-generic
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
profiles:
  - name: ci
    activation:
      - kubeContext: local-scaffold-profile
    build:
      local:
        tryImportMissing: false
        useDockerCLI: true
        useBuildkit: true
      artifacts:
      - image: asia.gcr.io/xxxxxx/backend
        context: .
        docker:
          dockerfile: ./developments/release.Dockerfile
          target: runner
      - image: asia.gcr.io/xxxxxx/gandalf-ci
        context: .
        docker:
          dockerfile: ./developments/release.Dockerfile
          target: gandalf-ci
      - image: asia.gcr.io/xxxxxx/gandalf-stub
        context: .
        docker:
          dockerfile: ./developments/release.Dockerfile
          target: gandalf-stub
    deploy:
      helm:
        releases:
          - name: nats-jetstream
            wait: false
            chartPath: deployments/helm/platforms/nats-jetstream
            namespace: local-xxxxxx-nats-jetstream
            createNamespace: true
            valuesFiles:
              - "deployments/helm/platforms/nats-jetstream/values.yaml"
            setValueTemplates:
              vendor: '{{.ORG}}'
              environment: '{{.ENV}}'
              serviceAccountEmailSuffix: '{{.SERVICE_ACCOUNT_EMAIL_SUFFIX}}'
              configs.kmsPath: '{{.KMS_PATH}}'
              secrets.serviceCredential: '{{.SVC_CRED}}'
          - name: elastic
            wait: false
            chartPath: deployments/helm/platforms/elastic
            namespace: elastic
            createNamespace: true
            valuesFiles:
              - "deployments/helm/platforms/elastic/values.yaml"
            setValueTemplates:
              vendor: '{{.ORG}}'
              environment: '{{.ENV}}'
              serviceAccountEmailSuffix: '{{.SERVICE_ACCOUNT_EMAIL_SUFFIX}}'
              configs.kmsPath: '{{.KMS_PATH}}'
              secrets.serviceCredential: '{{.SVC_CRED}}'
              elasticsearch:
                replicas: 1
                storage.storageClass: standard
          - name: istio-base
            repo: https://istio-release.storage.googleapis.com/charts
            remoteChart: base
            namespace: istio-system
            createNamespace: true
          - name: istiod
            repo: https://istio-release.storage.googleapis.com/charts
            remoteChart: istiod
            namespace: istio-system
            createNamespace: true
          - name: infras
            chartPath: ./deployments/helm/emulators/infras
            namespace: emulator
            createNamespace: true
            recreatePods: false
            skipBuildDependencies: false
            useHelmSecrets: false
            wait: false
          - name: firebase
            chartPath: ./deployments/helm/emulators/firebase
            namespace: emulator
            createNamespace: true
            recreatePods: false
            skipBuildDependencies: false
            useHelmSecrets: false
            wait: false
          - name: letsencrypt
            chartPath: ./deployments/helm/emulators/letsencrypt
            namespace: emulator
            createNamespace: true
            recreatePods: false
            skipBuildDependencies: false
            useHelmSecrets: false
            wait: false
          - name: xxxxxx-all-in-one
            wait: true
            chartPath: deployments/helm/xxxxxx-all-in-one
            namespace: "backend"
            createNamespace: true
            artifactOverrides:
              global:
                image: asia.gcr.io/xxxxxx/backend
              gandalf:
                stubImage: asia.gcr.io/xxxxxx/gandalf-stub
                ciImage: asia.gcr.io/xxxxxx/gandalf-ci
            imageStrategy:
              helm: {}
            valuesFiles:
              - "./deployments/helm/platforms/gateway/local-xxxx-values.yaml"
            setValueTemplates:
              svc1.replicaCount: 1
              svc2.replicaCount: 1
              svc3.replicaCount: 1
              svc4.replicaCount: 1
              svc5.replicaCount: 1
              svc6.replicaCount: 1
              svc7.replicaCount: 2
              svc8.replicaCount: 1
              svc9.replicaCount: 1
              global:
                localLogLevel: error
                draft.enabled: false
                configs.kmsPath: '{{.KMS_PATH}}'
                hasura.replicaCount: 1
                secrets.serviceCredential: '{{.SVC_CRED}}'
                project: '{{.PROJECT_ID}}'
                environment: '{{.ENV}}'
                vendor: '{{.ORG}}'
                appVersion: '{{.IMAGE_TAG}}'
                sqlProxy:
                  enabled: false
                  connName: '{{.SQL_PROXY_CONN_NAME}}'
                serviceAccountEmailSuffix: '{{.SERVICE_ACCOUNT_EMAIL_SUFFIX}}'
```

### Steps to reproduce the behavior
Actually I cannot reproduce this easily, here is some vtrace log https://gist.github.com/nvcnvn/f3124f016d05b3196e99149129a0dda4
