### ISSUE TITLE
Required configs in git repositories cannot be referenced by commit or tag

### ISSUE THREAD

**Issue by lsoica** [GoogleContainerTools/skaffold#7018]
Note: this is not a bug but an improvement afaict as it is not documented as supported. My use case is: I have multiple git repositories, multiple support branches for each, so I would like to freeze the dependencies to a specific point in time than to have them on the tip of a "main" branch which is a moving target.

### Expected behavior
A required config like:
```
requires:
- git:
    repo: ssh://user@server/repo.git
    path: .
    ref: 89bc120c
```
or
```
requires:
- git:
    repo: ssh://user@server/repo.git
    path: .
    ref: 10.1.0
```
should checkout the corresponding commit or tag.

### Actual behavior
Using a commit sha or a tag as a ref results in:
```
parsing skaffold config: error parsing skaffold configuration file: caching remote dependency <repo>: failed to clone repo: running [/usr/bin/git clone <repo> ./ZGnVKPr8TP2fMzjOc4h_-hO02AIa-KFf --branch 00876cbcfb8624d212447a2a08ce65fd3d70a70c --depth 1]
 - stdout: ""
 - stderr: "Cloning into './ZGnVKPr8TP2fMzjOc4h_-hO02AIa-KFf'...\nwarning: Could not find remote branch 00876cbcfb8624d212447a2a08ce65fd3d70a70c to clone.\nfatal: Remote branch 00876cbcfb8624d212447a2a08ce65fd3d70a70c not found in upstream origin\nfatal: the remote end hung up unexpectedly\n"
 - cause: exit status 128
```

### Information

- Skaffold version: v1.35.0-48-g8cd8b69dc

### Steps to reproduce the behavior

1. just provide a commit sha or a tag as a ref for a required config in a remote git repository
