### ISSUE TITLE
Building Artifacts with a Custom Build Script

### ISSUE THREAD

**Issue by palladius** [GoogleContainerTools/skaffold#7039]
Following these instructions: https://skaffold.dev/docs/tutorials/custom-builder/

Then, configure artifacts in your skaffold.yaml to build with build.sh:

### Expected behavior

build
### Actual behavior

doesnt build:

```Starting build...
Found [custom] context, using local docker daemon.
Building [gcr.io/k8s-skaffold/skaffold-custom]...
flag provided but not defined: -mod
usage: go get [-d] [-t] [-u] [-v] [-insecure] [build flags] [packages]
Run 'go help get' for details.
exit status 2
```

### Information

- Skaffold version: $ skaffold version
v1.35.1
- Operating system: Mac OS
- Installed via: $ which skaffold
/usr/local/bin/skaffold # so probably homebrew?
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta26
kind: Config

# this works!
# build:
#   artifacts:
#   - image: skaffold-example
#     # aggiunta da ric
#     context: app/
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-custom
    custom:
      buildCommand: ./custom_go_build_DONTCOMMIT.sh # conaints your scirpt
      dependencies:
        paths:
        - .


deploy:
  kubectl:
    manifests:
      - kubernetes/k8s-*

```

### Steps to reproduce the behavior

followed these instructions: https://skaffold.dev/docs/tutorials/custom-builder/ 

then 

    $ skaffold build -f skaffold-DONT-COMMIT.yaml 
```
Generating tags...
 - gcr.io/k8s-skaffold/skaffold-custom -> gcr.io/k8s-skaffold/skaffold-custom:c4f99ca-dirty
Checking cache...
 - gcr.io/k8s-skaffold/skaffold-custom: Not found. Building
Starting build...
Found [custom] context, using local docker daemon.
Building [gcr.io/k8s-skaffold/skaffold-custom]...
flag provided but not defined: -mod
usage: go get [-d] [-t] [-u] [-v] [-insecure] [build flags] [packages]
Run 'go help get' for details.
exit status 2
```
