### ISSUE TITLE
Prevent rebuilds when using a global context

### ISSUE THREAD

**Issue by ashconnell** [GoogleContainerTools/skaffold#7046]
We have an npm package that is used as a library in two separate pods. To use this with Skaffold we need to set the docker context to the root directory and then in each Dockerfile we copy in all the packages it needs and build them.

The issue is that while files sync correctly, because all artifacts have the same context the other images trigger a rebuild.

```yml
apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: hyperfy-api
      context: .
      docker:
        dockerfile: packages/hyperfy-api/Dockerfile
      sync:
        manual:
          - src: 'packages/hyperfy-api/**/*'
            dest: .
    - image: hyperfy-server
      context: .
      docker:
        dockerfile: packages/hyperfy-server/Dockerfile
      sync:
        manual:
          - src: 'packages/hyperfy-engine/**/*'
            dest: .
          - src: 'packages/hyperfy-server/**/*'
            dest: .
          - src: 'packages/hyperfy-ses/**/*'
            dest: .
    - image: hyperfy-client
      context: .
      docker:
        dockerfile: packages/hyperfy-client/Dockerfile
      sync:
        manual:
          - src: 'packages/hyperfy-engine/**/*'
            dest: .
          - src: 'packages/hyperfy-client/**/*'
            dest: .
          - src: 'packages/hyperfy-ses/**/*'
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/*.yml
portForward:
  - resourceType: Service
    resourceName: hyperfy-api
    port: 80
    localPort: 3001
  - resourceType: Service
    resourceName: hyperfy-client
    port: 80
    localPort: 3000
```

And here is one of the Dockerfiles (hyperfy-server):

```Dockerfile
FROM node:14.18.3-alpine

WORKDIR /app

COPY package.json .
COPY yarn.lock .
COPY packages/hyperfy-engine/package.json ./packages/hyperfy-engine/
COPY packages/hyperfy-server/package.json ./packages/hyperfy-server/
COPY packages/hyperfy-ses/package.json ./packages/hyperfy-ses/

RUN yarn

COPY . .

RUN yarn build --packages=hyperfy-engine,hyperfy-server

WORKDIR /app/packages/hyperfy-server

EXPOSE 3002
CMD yarn start
```

Is there a way to define what triggers a rebuild for each artifact or is this locked to any files inside the context?

**Comment by ashconnell** [comment]
I may have been thinking about this the wrong way. I can probably just use:

```yml
sync:
  manual:
    - src: '**/*'
      dest: .
```

This would then sync ALL changes to ALL pods and never trigger a rebuild, but this might be okay.
