### ISSUE TITLE
Skaffold last-prompted updated despite update-check is false

### ISSUE THREAD

**Issue by Guillaume-Mayer** [GoogleContainerTools/skaffold#7051]
Hi,

I turned update-check off, in Skaffold global settings, because I use my package manager to update.
I try to track my dot files with git and I added ~/.skaffold/config to them.

### Expected behavior

When update-check is false, update.last-prompted should not be updated (I think)

### Actual behavior

update.last-prompted is updated, I think each time I use Skaffold

### Information

- Skaffold version: v1.35.2
- Operating system: Linux 5.16
- Installed via: pacman
- Contents of ~/.skaffold/config:

```yaml
global:
  local-cluster: true
  update-check: false
  survey:
    last-prompted: "2022-01-19T17:56:58-03:00"
  collect-metrics: false
  update:
    last-prompted: "2022-01-24T20:29:00-03:00"
kubeContexts: []
```

### Steps to reproduce the behavior

1. `skaffold config set -g update-check false`
2. Backup ~/.skaffold/config
3. Run a skaffold run  o skaffold build
4. Check ~/.skaffodl/config diffs with backup
