### ISSUE TITLE
Skaffold image filter with -build-image does not work properly with requires.

### ISSUE THREAD

**Issue by gaurav0107** [GoogleContainerTools/skaffold#7053]
Here is a sample skaffold in which, I only want to build IMAGE2, thus I use 
`skaffold build -p test -b IMAGE2` but since image2 is dependent on image 1 this filter stops build 2 as well since it cannot find build 1 throwing an error 

`FATA[0034] failed to resolve build result for required artifact "IMAGE1"  subtask=-1 task=DevLoop`

```
apiVersion: skaffold/v2beta26
kind: Config
profiles:
- name: test
  build:
    tagPolicy:
      envTemplate:
        template: latest
    artifacts:
    - image: IMAGE1
      custom:
        buildCommand: echo "Bulding image 1"
    - image: IMAGE2
      custom:
        buildCommand: echo "Building image 2"
      requires:
      - image: IMAGE1
    - image: IMAGE3
      custom:
        buildCommand: echo "Building image 3"
```

**Comment by tejal29** [comment]
@gaurav0107 Please take a look at https://skaffold.dev/docs/tutorials/artifact-dependencies/ to see how to specify artifact dependencies.
Looking at your config, it does not look like you are using the `requires` stanza.

/cc Adding @gsquared94

**Comment by gaurav0107** [comment]
@tejal29 even if I use the exact same example and build via 

`skaffold build -b app` since app requires base but its not in -b filter, it gives error as

`FATA[0005] failed to resolve build result for required artifact "base"  subtask=-1 task=DevLoop`

```
apiVersion: skaffold/v2beta9
kind: Config
build:
  artifacts:
  - image: app
    context: app
    requires:
    - image: base
      alias: BASE
  - image: base
    context: base
```
