### ISSUE TITLE
Skaffold dev seems not to be picking up kubeContext

### ISSUE THREAD

**Issue by fcrbe** [GoogleContainerTools/skaffold#7064]
When using kubeContext in my skaffold.yml, it does not seem to take this into account. I specified to use the kubeContext minikube (minikube running on my system), but while starting up `skaffold dev`, it says:

```
Listing files to watch...
 - name-of-img
Generating tags...
 - name-of-img -> name-of-img:v1.1-4-g3c1b65a-dirty
Checking cache...
 - name-of-img: Not found. Building
Starting build...
Found [do-ams3-personal] context, using local docker daemon.
Building [name-of-img]...
```

It seems to load my kube context of Digital Ocean (which is defaulted at that time). 

After building it fails because it can't pull the image:

```
name-of-img-deployment/name-of-img-deployment: container name-of-img is waiting to start:name-of-img:928784e4e37a0e175e3d50e922dbd8fb84ac2a1298d72811ba93c336b6c56544 can't be pulled
```

When running `skaffold dev --kube-context minikube`, everything works wonderfully well.

Do I misunderstand something, or should having the kubeContext parameter in the skaffold.yml have the same result as using the --kube-context in the CLI command?

### Information

- Skaffold version: v1.35.0
- Operating system: MacOS Big Sur 11.4
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: name-of-img
      context: ./app
deploy:
  kubectl:
    manifests:
      - ./k8s/generic/*
      - ./k8s/env-specific/dev/*
  kubeContext: minikube
```
