### ISSUE TITLE
skaffold dev deployments never stabilize on Skaffold 1.35.2

### ISSUE THREAD

**Issue by artur-jablonski** [GoogleContainerTools/skaffold#7073]
Using the manifest file `manifest.yaml`

```
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
spec:
  containers:
  - image: k8s.gcr.io/echoserver:1.4
    name: echoserver
```

`kustomization.yaml`:
```
resources:
  - manifest.yaml
```

and `skaffold.yaml`:

```
apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: test
deploy:
  kustomize:
    paths: [ "." ]
```

when executing:

`skaffold dev`

```
Listing files to watch...
Generating tags...
Checking cache...
Tags used in deployment:
Starting deploy...
Loading images into kind cluster nodes...
Images loaded in 214ns
 - pod/getting-started created
Waiting for deployments to stabilize...
 - pods: could not stabilize within 10m0s
 - pods failed. Error: could not stabilize within 10m0s.
Cleaning up...
 - pod "getting-started" deleted
1/1 deployment(s) failed
```

The pod is running fine: 

```
kubectl get pods

NAME              READY   STATUS    RESTARTS   AGE
getting-started   1/1     Running   0          8m26s
```

Expected behavior
The deployment reports success

Actual behavior
The command times out

Information
Skaffold version: v1.35.2
Operating system: Linux
Installed via: skaffold.dev

This seems to be related to ticket #6870 that I used as a template to create this one.
