### ISSUE TITLE
The --default-repo flag no longer seems to be respected in 1.36.0

### ISSUE THREAD

**Issue by todd-andrew-procore** [GoogleContainerTools/skaffold#7125]
### Expected behavior

On 1.35.0, 1.35.2, and previous versions; `skaffold run --default-repo localhost:5999` is able to push docker images to the local Docker registry running at `localhost:5999`

### Actual behavior

On 1.36.0, the `--default-repo` flag and the `SKAFFOLD_DEFAULT_REPO` environment variable seem to be ignored in favor of the global config.

`skaffold run --default-repo localhost:5999`

results in:

```
build [docker-registry/my-app] failed: could not push image "localhost:5000/docker-registry/my-app:0.158.000-4-ge8bafc2-dirty": Get "http://localhost:5000/v2/": dial tcp [::1]:5000: connect: connection refused
error Command failed with exit code 1.
```

### Information

- Skaffold version: 1.36.0
- Operating system: MacOs Big Sur 11.6.3
- Installed via: asdf
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta27
kind: Config
build:
  artifacts:
  - image: docker-repo/my-app
    docker:
      buildArgs:
        APP_ENV: ${APP_ENV}
      cliFlags:
      - --progress
      - plain
  insecureRegistries:
  - localhost:{{.REGISTRY_PORT:-5999}}
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: my-app
      chartPath: .chart/
      artifactOverrides:
        image: docker-repo/my-app
      namespace: my-app
      createNamespace: true
      imageStrategy:
        helm: {}
```

### Steps to reproduce the behavior

1. Local KinD cluster
2. Local Docker registry running at localhost:5999
3. Run `skaffold fix --overwrite` to update our config
4. `skaffold run --default-repo localhost:5999`

I don't think logs are needed as the error should be easily reproducible. If logs are needed, I can provide snippets.
