### ISSUE TITLE
Download tar artifact from kaniko pod

### ISSUE THREAD

**Issue by okgolove** [GoogleContainerTools/skaffold#7133]
### Expected behavior
I am able to get built docker image archived to tar from in cluster kaniko pod (to test it via container-structure-test and then push via crane)

### Actual behavior
Tar artifact is built but I am not able to get it

### Information

- Skaffold version: v1.36.0
- Operating system: Ubuntu 20.04
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta27
kind: Config
build:
  artifacts:
    - image: 1111111111.dkr.ecr.us-east-1.amazonaws.com/example/deployer
      kaniko:
        noPush: true
        tarPath: image.tar
        logFormat: text
  tagPolicy:
    envTemplate:
      template: "{{.SKAFFOLD_IMAGE_TAG}}"
  cluster:
    concurrency: 0
    namespace: my-namespace
    serviceAccount: skaffold-kaniko
    dockerConfig:
      secretName: jenkins-agent-docker-config-json
    resources:
      requests:
        memory: 128Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 1
```

### Steps to reproduce the behavior

1. `skaffold build`
2. Tar is built successfully
