### ISSUE TITLE
Use environment variables in the path of external helm repos

### ISSUE THREAD

**Issue by Samuel-Schober-USU** [GoogleContainerTools/skaffold#7162]
### Expected behavior
I would like to use environment variables in the path of external helm repos, so I can add the authorization there without commiting the credentials.

### Actual behavior
There is an error:
```
Helm release um not installed. Installing...
Error: INSTALLATION FAILED: invalid chart URL format: https://{{.USERNAME}}:{{.PASSWORD}}@helm.example.com/repository/helm/
```

### Information

- Skaffold version: v1.34.0
- Operating system: Windows 10
- Installed via: Chocolatey | Snap | Homebrew | ...-->
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta25
kind: Config
deploy:
  helm:
    releases:
      - name: example
        namespace: example
        createNamespace: true
        repo: "https://{{.USERNAME}}:{{.PASSWORD}}@helm.example.com/repository/helm/"
        remoteChart: foo
```
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

<!--
The logs from `skaffold ... -vdebug` can be very helpful.
Please remove or elide any confidential information.
-->
