### ISSUE TITLE
skaffold run ignore kustomize flag timeout for deploy

### ISSUE THREAD

**Issue by alanreynosov** [GoogleContainerTools/skaffold#7171]
### Expected behavior

do not throw timeout errors before timeout seconds especified in deploy.kustomize.flags.apply

### Actual behavior

throw timeout error of 32s

### Information

- Skaffold version: v1.35.1
- Operating system: ubuntu
- Installed via: ```
curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
     install skaffold /usr/local/bin/

Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: test

build:
  artifacts:
    - image: gcr.io/**********/**********
      context: /**********
      docker:
        dockerfile: containers/Dockerfile.sftp
        squash: true
    - image: gcr.io/**********/**********
      context: /**********/**********/**********/**********
      docker:
        dockerfile: containers/Dockerfile.app
        squash: true
        target: **********
        buildArgs:
          ENV: "{{.BUILD_ENV}}"
          REPOSITORY: gcr.io
  tagPolicy:
    envTemplate:
      template: "{{.TAG_BRANCH}}-{{.BUILD_ENV}}"
  local:
    push: false 
    useDockerCLI: true
    useBuildkit: true
    concurrency: 1

deploy:
  statusCheckDeadlineSeconds: 600 # 10mins
  kustomize:
    flags:
      apply: ['--timeout', '10m']
      delete: ['--timeout', '10m']

    paths: ["/**********/**********/**********/**********/k8s/overlays/dev"]

profiles:
  - name: mydevprofile
    patches:
      - op: replace
        path: /deploy/kustomize/paths
        value: ["/**********/**********/**********/**********/k8s/overlays/dev"]

```

### Steps to reproduce the behavior

`skaffold run --filename=/skaffold_man.yaml --kube-context=gke --namespace=testtimeout1 --profile=dev   --cache-artifacts=false --no-prune=false --no-prune-children=false --status-check --wait-for-connection=true --wait-for-deletions=true --wait-for-deletions-max=10m -v error`

logs 

`Deploy Failed. Could not connect to cluster due to "https://x.x.x.x/version?timeout=32s": dial tcp x.x.x.x:x: i/o timeout. Check your connection for the cluster.`
