### ISSUE TITLE
statusCheck in the skaffold.yaml is not used without --status-check= flag

### ISSUE THREAD

**Issue by johnmanjiro13** [GoogleContainerTools/skaffold#7178]
### Expected behavior

`skaffold run` runs without status check only setting the `statusCheck` field of the deployment config stanza in the skaffold.yaml to false.

### Actual behavior

The statusCheck field in the skaffold.yaml is used only when value of the `--status-check` flag is nil.
https://github.com/GoogleContainerTools/skaffold/blob/v1.36.1/pkg/skaffold/runner/deployer.go#L53-L60

However, the default value of the flag is true. So we have to use `--status-check=`.
This seems like a strange behavior.

### Information

- Skaffold version: v1.36.1
- Operating system: MacOS Big Sur (11.6)
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: deployment
build:
  artifacts:
    - image: eu.gcr.io/example/push-events
      docker:
        dockerfile: backend/push-events-svc/Dockerfile
deploy:
  helm:
    releases:
      - name: example
        chartPath: ./k8s/chart
        valuesFiles:
          - ./k8s/values/dev.yaml
  statusCheck: false
```

### Steps to reproduce the behavior

1. use the skaffold.yaml
2. skaffold run # run with status check
3. skaffold run --status-check= # run without status check
