### ISSUE TITLE
Add ability to disable watch-rebuild with custom builder

### ISSUE THREAD

**Issue by mruzekw** [GoogleContainerTools/skaffold#7185]
I'm currently configuring a `skaffold dev` setup for a Clojure server, mainly to integrate easily with the VSCode CloudCode extension.

My current setup is using a custom build script using the `custom` config in skaffold.yml.

In the Clojure world, it's common to hot-reload code on demand via a REPL. Thus in the dev case, we sometimes explicitly don't want to rebuild the image when a dependency changes, but we'd still like to sync the changed file.

Would it be possible to use `build > artifacts > - image > custom > dependencies > command` and enable and disable watch-rebuild and file syncing independently?

**skaffold.yml**
```
apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: mynewapp

build:
  artifacts:
  - image: mruzekw-mynewapp
    custom:
      buildCommand: clj -X:skaffold
      dependencies:
        command: clj -X:skaffold-deps

deploy:
  kubectl:
    manifests:
    - deployment.yaml

portForward:
- resourceType: service
  resourceName: mruzekw-mynewapp
  port: 8080
```

**Comment by mruzekw** [comment]
Looks like this is possible with `skaffold dev --auto-build=false`, though it still would be nice to configure in `skaffold.yml`.

**Comment by tejal29** [comment]
Currently, we dont plan to support this feature in skaffold.yaml. 
We have some cool integration with Cloud Code IDEs to iteratively watch for changes.
https://cloud.google.com/code/docs/intellij/watch-modes

**Comment by tejal29** [comment]
Please re-open if you have any more suggestions

**Comment by mruzekw** [comment]
Okay, thanks for considering and for the doc.

`--auto-build=false` should work for the use-case I'm targeting along with the "On demand" feature in Cloud Code.

**Comment by emmanuelbaah** [comment]
For other instances where Skaffold integrates with Cloud Code to provide watch mode you can also visit the following docs.
https://cloud.google.com/code/docs/shell/deploying-a-cloud-run-service
https://cloud.google.com/code/docs/vscode/deploying-a-cloud-run-service
(Step 12 for both, at the bottom of the docs)

**Comment by kalaracey** [comment]
I found I was able to selectively disable auto-build of an artifact configured via `custom` and `buildCommand` by using `dependencies.ignore`, as in

```
build:
  artifacts:
    - image: foo
      context: bar/
      custom:
        buildCommand: docker build -t=$IMAGE $BUILD_CONTEXT
        dependencies:
          ignore:
            - "bar/**"
```

This let me use Quarkus's [Remote Development Mode](https://quarkus.io/guides/maven-tooling#remote-development-mode), though AFAICT it ended up not having much of an advantage over just having Skaffold rebuild the image.
