### ISSUE TITLE
Skaffold dev creates duplicate pods

### ISSUE THREAD

**Issue by d11wtq** [GoogleContainerTools/skaffold#719]
I haven't figured out when this happens, but sometimes I see two or three of every pod when I expect to only see one. I think it's either:

  1. When I continue making and saving changes to my project while skaffold is still building images.
  2. After `skaffold dev` crashes due to a bug and I start it back up again (the default in `skaffold dev` is to attempt to clean up deployed resources... which may possibly be going wrong here).

The interesting thing is that `kubectl get deployments` shows the right number of deployments and those deployments believe they have the right number of pods, but `kubectl get pods` can see all the extra pods that shouldn't be there. The extra pods appear to somehow be orphaned.

I'm observing this when using minikube + kubernetes 1.9.0.

### Expected behavior

Pods should not be duplicated.

### Actual behavior

Pods sometimes get duplicated and orphaned, which requires manual intervention to clean up.

### Information

- Skaffold version: 0.7.0 (via master build - will check if present in released 0.7.0)
- Operating system: MacOS 10.12.16
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
    - imageName: projectname/api
      workspace: .
      docker:
        dockerfilePath: Dockerfile
  local:
    skipPush: true
deploy:
  kubectl:
    manifests:
      - manifests/*.yaml
```

### Steps to reproduce the behavior

Unsure how to reproduce just yet. I just notice it happens a lot.
