### ISSUE TITLE
 [Umbrella Tracking Issue] Skaffold Verify planning/H1-2022 priority/p1

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7191]
Tracking issue for all work items related to adding a post deployment verification phase to skaffold.  Currently this will be a a `verify` phase and related command with a schema like the following:
```
apiVersion: skaffold/v2beta29
kind: Config
# …
verify:
- name: smoke test
  script:
    args: ["./load_test.sh", "localhost:3000"]
- name: integration-test
  container:
    name: integration-test
    image: integration-test
    command:
    - ["./test-all.sh"]
- name: metrics-check
  container:m
    name: metrics-check
    image: metrics-check
    command:
    - ["./promql_metrics_check.sh", "localhost:9000"]
```
