### ISSUE TITLE
Error checking cache.

### ISSUE THREAD

**Issue by sendev1** [GoogleContainerTools/skaffold#7223]
### Expected behavior
Our gradlew build takes longer. So for local development we run gradlew build  only if there is change in the code that produces the war file then we start the skaffold deployment. But skaffold says 

```
Checking cache...
push value not present in isImageLocal(), defaulting to false because cluster.PushImages is false

- driverapp: Error checking cache.
getting imageID for Driver/driverapp:1.223.1.27-dirty: Error response from daemon: no such image: Driver/driverapp:1.223.1.27-dirty: invalid reference format: repository name must be lowercase
```
 2 issues
1. Why `Driver/` is appended infront of image name - could not figure it out.
2. Eventhough I set `docker: { noCache: true }` it still checks for cache and gets above error
### Information
skaffold dev --filename skaffold.yaml --label ide=idea --label ideVersion=2021.2.3.0.0 --label ijPluginVersion=22.2.1-212 --auto-build=false --auto-deploy=false --auto-sync=false --default-repo Driver --rpc-port 50057 --port-forward=true --wait-for-deletions-max=2m0s --status-check=true --verbosity trace

- Skaffold version: skaffold/v2beta19
- Operating system: Mac Os Catalina 10.5
- Installed via:  Cloud Code 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: driverapp
build:
  artifacts:
    - image: driverapp
      context: ../../
      docker: { noCache: true }
deploy:
  kubectl:
    manifests:
      - driver.deployment.yaml
      - ../driver.service.yaml
```
