### ISSUE TITLE
Some taggers failed. Rerun with -vdebug for errors.

### ISSUE THREAD

**Issue by emon-gain** [GoogleContainerTools/skaffold#7234]
My Skaffold.yml is given below

```
apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: learningproject-345013
    logStreamingOption: STREAM_ON
  artifacts:
    - image: gcr.io/learningproject-345013/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'


```
