### ISSUE TITLE
cannot create new manifest with cmd "--generate-manifests"

### ISSUE THREAD

**Issue by Fdslk** [GoogleContainerTools/skaffold#7237]
### Information

- Skaffold version: v1.37.0
- Operating system: 12.0.1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    # - image: skaffold-example
    #   docker:
    #     dockerfile: Dockerfile
    - image: skaffold-spring-boot-example
      jib: {}
  # local: {}

deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold init --generate-manifests -vdebug`

```
skaffold init --generate-manifests -vdebug
DEBU[0000] skaffold API not starting as it's not requested  subtask=-1 task=DevLoop
INFO[0000] Skaffold &{Version:v1.37.0 ConfigVersion:skaffold/v2beta28 GitVersion: GitCommit:db0414e6646f54ce7d22a7eba65182c12284f162 BuildDate:2022-03-17T03:07:48Z GoVersion:go1.17.8 Compiler:gc Platform:darwin/amd64 User:}  subtask=-1 task=DevLoop
DEBU[0000] Disable housekeeping messages for command explicitly  subtask=-1 task=DevLoop
DEBU[0000] Running command: [java -version]              subtask=-1 task=DevLoop
DEBU[0000] Running command: [/Users/zengqiangfang/Documents/code/ops/skaffoldDemo/demo/mvnw jib:_skaffold-init -q --batch-mode]  subtask=-1 task=DevLoop
DEBU[0001] Command output: [
BEGIN JIB JSON
{"image":"skaffold-spring-boot-example","project":"org.skaffold:skaffold-spring-boot-example"}
]  subtask=-1 task=DevLoop
DEBU[0001] metadata not present in yaml, continuing      subtask=-1 task=DevLoop
DEBU[0001] apiVersion not present in yaml, continuing    subtask=-1 task=DevLoop
DEBU[0001] apiVersion not present in yaml, continuing    subtask=-1 task=DevLoop
DEBU[0001] apiVersion not present in yaml, continuing    subtask=-1 task=DevLoop
? Which builders would you like to create kubernetes resources for?
DEBU[0003] Running command: [tput colors]                subtask=-1 task=DevLoop
DEBU[0003] Command output: [256
]                        subtask=-1 task=DevLoop
one or more valid Kubernetes manifests are required to run skaffold
```

**Comment by tejal29** [comment]
@Fdslk Are you running a init command with deploy config already present?
```
deploy:
  kubectl:
    manifests:
      - k8s-*
```
