### ISSUE TITLE
Skaffold generated with generate-manifests doesnt sync code when you use with Cloud Code "Debug on Kubernetes"

### ISSUE THREAD

**Issue by VeerMuchandi** [GoogleContainerTools/skaffold#7247]
### Expected behavior
If you make changes to the code while in "Debug on Kubernetes" the code sync between the editor and the container should work exactly the same way as with "Run on Kubernetes"

### Actual behavior
Instead of syncing the code, it rebuilds the container and deploys again.

### Information

- Skaffold version:  1.36.0
- Operating system:  Running from Cloud Workstations
- Installed via: 
- Contents of skaffold.yaml:

```
apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: mynodejsapp
build:
  artifacts:
  - image: mynodejsapp
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - deployment.yaml
portForward:
- resourceType: service
  resourceName: mynodejsapp
  port: 8080

```

### Steps to reproduce the behavior

1. Follow the steps here https://github.com/VeerMuchandi/InnerLoopDev/blob/main/NodeJsInnerLoopSetup.md
2. Run the application in debug mode with `Debug on Kubernetes`
3. Make a change to the message while in the debug mode and notice that it rebuilds the container and redeploys as opposed to just syncing the files when you use "Run on Kubernetes"
