### ISSUE TITLE
If a package name does not exist it is not automatically created

### ISSUE THREAD

**Issue by mm-fsai** [GoogleContainerTools/skaffold#7254]
### Expected behavior
It seems that if a package name exists already, skaffold will push an image.

If I change the package name to a new name, skaffold will fail to push the image, stating "MANIFEST_UNKNOWN"

### Actual behavior
```
build [fsai-python-3.9.10-slim] failed: getting image: GET https://ghcr.io/v2/[GH_ORG]/[IMAGE_NAME]/manifests/latest: MANIFEST_UNKNOWN: manifest unknown
```
### Information

- Skaffold version: skaffold/v2beta28
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config

build:
  platforms: ["linux/amd64", "linux/arm64"]

  artifacts:
    - image: fsai_python-3_9_10
      context: ./images/
      custom:
        dependencies:
          dockerfile:
            path: ./fsai-python-3.9.10-slim.Dockerfile

```
