### ISSUE TITLE
container hooks on deploy phase do not work when a pod has multiple containers

### ISSUE THREAD

**Issue by nao23** [GoogleContainerTools/skaffold#7257]
Container hooks on deploy phase do not work when a pod has multiple containers.

When a pod has two containers and I specify the second container as a target container by `containerName` key,
the command is not executed. On the other hand, it works when I specify the first container.

### Expected behavior

Command is executed when I specify the second container as a target container.

### Actual behavior

Command is not executed when I specify the second container as a target container.

### Information

- Skaffold version: v1.37.1
- Operating system: macOS v12.2 (Monterey)
- Installed via: Homebrew 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: test-success
deploy:
  kubectl:
    manifests:
      - test.yaml
    hooks:
      after:
        - container:
            podName: test-*
            containerName: aaa
            command: ["echo", "HELLO"]
---
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: test-failure
deploy:
  kubectl:
    manifests:
      - test.yaml
    hooks:
      after:
        - container:
            podName: test-*
            containerName: bbb
            command: ["echo", "HELLO"]
```

- Contents of test.yaml:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-template
data:
  default.conf.template: |-
    server {
      listen $NGINX_PORT;
      location / {
        return 200;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: aaa
        image: "nginx:1.21"
        env:
        - name: NGINX_PORT
          value: "8080"
        volumeMounts:
        - name: nginx-conf-template
          mountPath: "/etc/nginx/templates/"
      - name: bbb
        image: "nginx:1.21"
        env:
        - name: NGINX_PORT
          value: "8081"
        volumeMounts:
        - name: nginx-conf-template
          mountPath: "/etc/nginx/templates/"
      volumes:
        - name: nginx-conf-template
          configMap:
            name: nginx-conf-template
            items:
              - key: default.conf.template
                path: default.conf.template
```

### Steps to reproduce the behavior

1. `skaffold run --module test-success`

```shell
❯ skaffold run --module test-success
Generating tags...
Checking cache...
Starting test...
Tags used in deployment:
Starting deploy...
 - deployment.apps/test configured
Waiting for deployments to stabilize...
 - deployment/test is ready.
Deployments stabilized in 4.155 seconds
Starting post-deploy hooks...
[aaa] HELLO
Completed post-deploy hooks
Waiting for deployments to stabilize...
Deployments stabilized in 17.646507ms
```

2. `skaffold run --module test-failure`

```shell
❯ skaffold run --module test-failure
Generating tags...
Checking cache...
Starting test...
Tags used in deployment:
Starting deploy...
 - deployment.apps/test configured
Waiting for deployments to stabilize...
 - deployment/test is ready.
Deployments stabilized in 3.168 seconds
Starting post-deploy hooks...
Completed post-deploy hooks
Waiting for deployments to stabilize...
Deployments stabilized in 20.270331ms
```
