### ISSUE TITLE
[Question] Documentation disambiguation of inferred v.s. manual sync behavior

### ISSUE THREAD

**Issue by dominicfollett** [GoogleContainerTools/skaffold#7261]
Hi there. I have a question about the expected behavior of different syncing options using Skaffold. It seems that inferred syncs only perform a file sync on the pod's container but with no rebuild and deploy, whereas a manual sync will rebuild and deploy the new container image. At least this is the behavior I am observing with the configuration below. Is this assumption correct? I could not verify that this is the case from the documentation.

### Expected behavior
Unsure

### Actual behavior
Inferred syncing does not rebuild and deploy a container image.

### Information

- Skaffold version: v1.37.1
- Operating system: MacOS Monterey 12.2.1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config

build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    push: false
    useDockerCLI: true
    useBuildkit: true
  artifacts:
  - image: mygoapp
    context: /Users/admin/mygoapp
    docker:
      dockerfile: /Users/admin/goapp/Dockerfile
    sync:
      manual:
        - dest: /go/src/app
          src: /Users/admin/goapp/**/*

  - image: myrubyapp
    context: /Users/admin/myrubyapp
    docker:
      buildArgs:
        environment: development
      dockerfile: /Users/admin/myrubyapp/Dockerfile
    sync: 
      infer: ["**/*"]

deploy:
  kubeContext: docker-desktop
  kustomize:
    paths: 
      - ./overlays/development
    hooks:
      before:
        - host:
            command: ["sh", "-c", "./hooks/templates.envsubst.sh development"]
```
