### ISSUE TITLE
skaffold dev not working in WSL2

### ISSUE THREAD

**Issue by DhansAL** [GoogleContainerTools/skaffold#7288]
### Expected behavior
after entering `skaffold dev` command,
it should be making the assigned deployments and services and tracking changes over the files.

### Actual behavior
After entering the command , it is unable to list files to watch

**logs**

```zsh
skaffold dev   
                                                                                                
Listing files to watch...
 - username/auth
listing files: parsing ONBUILD instructions: retrieving image "node:alpine": GET https://index.docker.io/v2/library/node/manifests/alpine: unexpected status code 408 Request Timeout: <html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>
```

**but it works if done on windows with windows suitable skaffold binary.**

### Information

- Skaffold version: v1.38.0
- Operating system: running in WSL2* Ubuntu 20.04 LTS, windows 10 
- Installed via:  skaffold.dev (Linux x86_64 binary from skaffold official webiste)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: username/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
```
