### ISSUE TITLE
New files in kubectl.manifests dir are not discovered until an existing file is modified

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#729]
Skaffold 0.7

I have a setup like:

```
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
```

while `skaffold dev` is watching, if I create a new manifest like `foo.yaml` and keep saving changes to it, these changes are not detected at all.

So I end up changing an existing .yaml in that dir, now it notices `foo.yaml` and adds it to the watch list. Bug or by design?
