### ISSUE TITLE
Skaffold dev not smart enough to deploy just helm chart that changed

### ISSUE THREAD

**Issue by felipem1210** [GoogleContainerTools/skaffold#7297]
### Expected behavior

When running `skaffold dev` with a skaffold file that have multiple artifacts deployed with helm I want skaffold to be smart enough to trigger the deploy process just for the artifacts that have changed using the automatic sync mode.

### Actual behavior

Actually, when change occurs in just one artifact, helm chart deploy process is run for all the artifacts

### Information

- Skaffold version: `v1.37.0`
- Operating system: `Ubuntu 20.04`
- Installed via: `skaffold.dev`
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta22
kind: Config
build:
  local:
    push: false      
  artifacts:
    - image: myservice
      context: microservice/myservice
    - image: myservice2
      context: microservice/myservice2

deploy:
  kubeContext: kind-example
  helm:
    releases:
      - name: myservice
        chartPath: ./helm/charts/myservice
        namespace: microservices
        createNamespace: true
        valuesFiles:
          - "./helm/dev/microservices/myservice/values.yaml"
        artifactOverrides:
          global.image: myservice
        imageStrategy:
          helm: {}

      - name: myservice2
        chartPath: ./helm/charts/myservice2
        namespace: microservices
        createNamespace: false
        valuesFiles:
          - "./helm/dev/microservices/myservice2/values.yaml" 
        artifactOverrides:
          global.image: myservice2
        imageStrategy:
          helm: {} 
```

### Steps to reproduce the behavior
Run skaffold dev, make changes of code in just `myservice2`. `Skaffold dev` default is to rerun the deployment for both.
