### ISSUE TITLE
WORKSPACE.bazel not being found

### ISSUE THREAD

**Issue by betaboon** [GoogleContainerTools/skaffold#7304]
### Expected behavior
`WORKSPACE.bazel` is detected (and takes precendence over `WORKSPACE`)

### Actual behavior
skaffold fails to detect `WORKSPACE.bazel`

log: `listing files: unable to find the WORKSPACE file: no WORKSPACE file found`

[location of interest 1](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/build/bazel/dependencies.go#L91)
[location of interest 2](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/build/bazel/dependencies.go#L113)

### Information

- Skaffold version: v1.38.0
- Operating system: NixosOS 22.05.20220411.3377270 (Quokka)
- Installed via: nix (nixos package-manager)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: example-3rdparty
      bazel:
        target: //python/service/example:container.tar
```
