### ISSUE TITLE
Can't re-apply StatefulSet because of forbidden fields

### ISSUE THREAD

**Issue by LukeeeeBennett** [GoogleContainerTools/skaffold#7309]
### Expected behaviour

`skaffold apply`ing a set of kustomize manifests from `skaffold render` should successfully apply any allowed manifest updates to a statefulset

### Actual behavior

`StatefulSet.apps "..." is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

### Information

- Skaffold version: 1.37.1
- Operating system: alpine
- Installed via: Google Cloud SDK
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ...
build:
 ...
deploy:
  kustomize:
    ...
resourceSelector:
  allow:
    - groupKind: 'StatefulSet.apps'
      image: ['.*']
      labels: ['.*']
  deny:
    - groupKind: 'StatefulSet.apps'
      labels:
        [
          '.spec.volumeClaimTemplates.*.metadata.labels',
          '.spec.metadata.labels',
          '.spec.template.metadata.labels',
        ]
profiles:
   ...
```

### Steps to reproduce the behavior

When first applying the following (with `volumeClaimTemplates` uncommented), the stateful set deploys successfully.
When applying it again, it complains about `'replicas', 'template', and 'updateStrategy'`.
But even if I comment out `volumeClaimTemplates`, it still errors with this. If I remove the other properties that are not  `'replicas', 'template', and 'updateStrategy'`, then apply will fail because `selector` and `serviceName` are required.

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ...
spec:
  selector:
    matchLabels:
      app: ...
  serviceName: ...
  replicas: 1
  template:
    metadata:
      labels:
        app: ...
    spec:
      terminationGracePeriodSeconds: 2
      containers:
        - name: postgres
          image: postgres:13.3
          ...
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: ...
  # volumeClaimTemplates:
  #   - metadata:
  #       name: ...
  #     spec:
  #       storageClassName: standard
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 100Gi
  updateStrategy:
    type: RollingUpdate
```
