### ISSUE TITLE
Skaffold/Kaniko with ECR

### ISSUE THREAD

**Issue by jicowan** [GoogleContainerTools/skaffold#731]
This is a feature request.  I'd like to be able to use Skaffold to create a Kaniko container/pod on KOPS cluster for building container images and then pushing them to an ECR registry.  I'd also like to be able to use an S3 bucket for the build context.

**Comment by dlorenc** [comment]
Using s3 for the build context needs to be implemented first in kaniko. I think there's a feature request over in that repo detailing more flexible build context locations.

**Comment by bhack** [comment]
@dlorenc https://github.com/GoogleContainerTools/kaniko/issues/121

**Comment by jicowan** [comment]
If Kaniko is running on an EC2 instance, you can assign the instance an IAM role that grants it access to ECR.  You shouldn't need to use the credential helper in that instance.

**Comment by bhack** [comment]
On EC2 it is solvable also with https://github.com/jtblin/kube2iam

**Comment by dlorenc** [comment]
Do you have any pointers to how docker actually fetches access tokens in an environment like that? 

gcr works the same way from gce, but the access token fetching happens from inside the credential helper.

Basically auth works like this currently:

* docker or kaniko parse the registry out of the image name
* they look up the credential helper for that registry from the docker config.json
* they call the credential helper to get an access token
* the credential helper determines it is running on gce and gets an access token using the IAM roles the VM service account is bound to

This all works easily with gcr because there is a small set of valid registry urls (us.gcr.io, eu.gcr.io, etc.) that we can hardcode inside the config.json, instructing the calling tool to use the gcr credential helper.

**Comment by bhack** [comment]
Simply you need to give the listed permission in https://kubernetes.io/docs/concepts/containers/images/#using-aws-ec2-container-registry to the pod with kube2iam

**Comment by bhack** [comment]
Of course these are for read you need to add the write ones for pushing

**Comment by dlorenc** [comment]
In this case it looks like the Kubelet has direct support for ec2 in it:

```
The kubelet will fetch and periodically refresh ECR credentials. It needs the following permissions to do this:
```

We would need to do something similar in https://github.com/google/go-containerregistry to make this work.

**Comment by bhack** [comment]
@dlorenc https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/aws/aws_credentials.go#L76.
But I think that if you can have the [aws ecr credential helper](https://github.com/awslabs/amazon-ecr-credential-helper) and you authorize i.e. with kube2iam it can work with the basic auth pieple that you have described.

**Comment by bhack** [comment]
Sorry I am not on this anymore currently so I have not the setup ready test this immediately. Can you test it in the meantime?

**Comment by nkubala** [comment]
I haven't tested it personally, but Kaniko's ECR support *should* fix this issue. Going to close for now, please reopen if anyone sees any issues with it.

**Comment by azaiter** [comment]
Although Kaniko has ECR support, the pod template is made for Google Container Registry, as in https://github.com/GoogleContainerTools/skaffold/blob/cff3918df8c165f2c4bb17b07f3ed50222f6a63c/pkg/skaffold/build/kaniko/sources/sources.go#L66 kaniko secret should be adjusted to a volume mount under `/root/.aws/aws-secret` instead of google's GOOGLE_APPLICATION_CREDENTIALS environment variable (maybe aws has also a similar env var too? if so, this should be an easy ternary operation to choose which env var.)

**Comment by azaiter** [comment]
@nkubala could you kindly re-open this issue? thanks!

**Comment by priyawadhwa** [comment]
For this to work, we could add a `PullSecretMountPath` field to [ClusterDetails](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/latest/config.go#L238), and then mount in that path in the generated pod [here](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/build/kaniko/sources/sources.go#L73).

Would anyone be interested in submitting a PR?

**Comment by jonjohnsonjr** [comment]
IIUC, kaniko is using k8schain on-cluster, so this getting fixed (soon) should help: https://github.com/google/go-containerregistry/issues/355

**Comment by tejal29** [comment]
@azaiter Going to link this issue to #1892 which will solve this problem.

**Comment by balopat** [comment]
@priyawadhwa  can we add this to your Kaniko registry revamp todo list? :)

**Comment by priyawadhwa** [comment]
@balopat for sure!

**Comment by priyawadhwa** [comment]
Hey @azaiter , I added `PullSecretMountPath` as an option to `ClusterDetails` in #2975. Please comment here if this doesn't resolve your issue & we can reopen this one.

**Comment by azaiter** [comment]
Hey @priyawadhwa, The MR looks good and should do the job, I've been using the build from [this MR](https://github.com/GoogleContainerTools/skaffold/pull/1700) for the longest time and the only difference is the environment variable setting for ECR region (in which I think it defaults to [us-east-1](https://github.com/GoogleContainerTools/kaniko/blob/4ce8b8db817047f0be7a78c0fdffab71f797e8f8/vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go#L43) but I'm not sure). Are there any plans to support setting up environment variables on [Kaniko pod](https://github.com/GoogleContainerTools/kaniko/blob/master/vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go)? I believe we discussed that https://github.com/GoogleContainerTools/skaffold/issues/1892 and https://github.com/GoogleContainerTools/skaffold/pull/1906 were part of the original proposal of generalizing container registry config. @tejal29 What do you think?

I'll pull the latest build and test it with our setup, if it happens that the environment variable piece is necessary for ECR, I'll report back and re-open the issue. Thanks for your efforts!

**Comment by priyawadhwa** [comment]
Sounds good, thanks @azaiter ! If the env variable is necessary I think it makes sense to support that in the pod.

**Comment by cyrildiagne** [comment]
Thanks a lot @priyawadhwa for adding the `PullSecretMountPath` property.

I'm still facing an issue when trying to build with Kaniko on an EKS cluster pushing the image to ECR. I can see the logs of the image building in the Kaniko pod but as soon as the build is complete skaffold returns an error: `getting image: unsupported status code 401; body: Not Authorized`.

I don't see any specific reference to the `AWS_REGION` env var, but I wonder if that could be the problem since it's the only thing that seems different between the failing skaffold config and the working kaniko config.

Edited `skaffold dev` log:
```
Listing files to watch...
 - XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/hello-world
List generated in 4.0196944s
Generating tags...
 - XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/hello-world -> XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/hello-world:2019-10-21_19-04-20.994_UTC
Tags generated in 240.2µs
Starting build...
Creating kaniko secret [default/aws-secret]...
Creating docker config secret [docker-kaniko-secret]...
Building [XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/hello-world]...
Storing build context at /tmp/context-c730a796c18102623c402918e34b137a.tar.gz

[ ... DOCKER BUILD LOG ... ]

Pruning images...
Image prune complete in 31.4µs
FATA[0057] exiting dev mode because first build failed: build failed: building [XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/hello-world]: kaniko build for [XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/hello-world]: getting image: unsupported status code 401; body: Not Authorized 
```

My skaffold config:
```yaml
apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
    - image: XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/hello-world
      kaniko:
        buildContext:
          localDir: {}
  cluster:
    pullSecretName: aws-secret
    pullSecretMountPath: /root/.aws/
    dockerConfig: 
      secretName: docker-kaniko-secret
    namespace: default
  tagPolicy:
    dateTime: {}
deploy:
  kubectl:
    manifests:
      - k8.yaml
```

The following kaniko yaml builds successfully when applied directly:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=Dockerfile",
            "--context=s3://elasticbeanstalk-eu-west-1-XXXXXXXXXX/test.tar.gz",
            "--destination=XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/hello-world:test-1"]
    volumeMounts:
      - name: aws-secret
        mountPath: /root/.aws/
      - name: docker-config
        mountPath: /kaniko/.docker/
    env:
      - name: AWS_REGION
        value: eu-west-1
  restartPolicy: Never
  volumes:
    - name: aws-secret
      secret:
        secretName: aws-secret
    - name: docker-config
      configMap:
        name: docker-config
```
