### ISSUE TITLE
Run development skaffold on multiple microservices in parallel

### ISSUE THREAD

**Issue by mor-cybellum** [GoogleContainerTools/skaffold#7310]
### Expected behavior

Run all the microservices that compose the system in dev mode, when skaffold dev it should build each of them in parallel

### Actual behavior

It runs build one microservice at a time (one after another)

### Information

- Skaffold version: v1.38.0
- Operating system: Linux ubuntu 20.04
- Installed via: skaffold.dev
- Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    concurrency: 10
    useBuildkit: true
requires:
  - path: ../Microservice1/skaffold.yaml
  - path: ../Microservice2/skaffold.yaml
  - path: ../Microservice3/skaffold.yaml  
```

I run skaffold dev on this yaml.
Although I put the concurrency at 10 it doesn't seem to build and deploy all of them in parallel but going 1 after another:
Build Microservice1 -> Build Microservice2 -> Build Microservice3 -> Deploy

### Steps to reproduce the behavior

run skaffold dev on the yaml
