### ISSUE TITLE
COPY . . not copying all files if Dockerfile is under Windows junction

### ISSUE THREAD

**Issue by ArneMancofi** [GoogleContainerTools/skaffold#7322]
### Expected behavior

Running `skaffold build` should copy the same files as `docker build` when executing a `COPY . .` command in the Dockerfile, also when the Dockerfile is referenced via a Windows junction directory.

### Actual behavior

Only a (deterministic) subset of the files are copied.

### Information

- Skaffold version: 1.35.2
- Operating system: Windows 11, 10.0.22000 Build 22000
- Installed via: Chocolatey
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: root
build:
  local:
    push: false
    tryImportMissing: true
  tagPolicy:
    inputDigest: { }
  artifacts:
  - image: myregisry/myrootname/myprojectname
    context: ../../../MyDirectory
    docker:
      dockerfile: Dockerfile
```
Note: **MyDirectory** is a Windows junction pointing to another directory:
```
ls -l
lrwxrwxrwx 1 MyUser 4096 21 Apr 19 10:16 MyDirectory -> ../myroot/MyDirectory/
```

- Contents of Dockerfile:
```
...
RUN ls -la
COPY . .
RUN ls -la
...
```

- Contents of **MyDirectory**: Various files, like angular.json, tsconfig.json, etc.

### Steps to reproduce the behavior

1. `skaffold build`
