### ISSUE TITLE
Outdated Kustomize build flags in Examples

### ISSUE THREAD

**Issue by javiercanadillas** [GoogleContainerTools/skaffold#7331]
### Expected behavior
Run https://github.com/GoogleContainerTools/skaffold/tree/main/examples/kustomize example following the `README.md` file should work out of the box.

### Actual behavior
Running `skaffold deploy -f skaffold-kustomize-args.yaml` fails with:

```text
running [kustomize build --load_restrictor none .]
 - stdout: ""
 - stderr: "Error: unknown flag: --load_restrictor\n"
 - cause: exit status 1
```

### Information

- Skaffold version: v1.38.0
- Kustomize version: 4.5.4
- Operating system: Debian Linux, Google Cloud Shell
- Installed via: 
- Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kustomize: {}
```

### Steps to reproduce the behavior

1. Go to https://github.com/GoogleContainerTools/skaffold/tree/main/examples/kustomize
2. Click "Open in Cloud Shell"
3. Start minikube cluster: `minikube start`
4. Launch the suggested command line example: `skaffold deploy -f skaffold-kustomize-args.yaml`

### Proposed solution

Update `skaffold-kustomize-args.yaml` to reflect syntax changes in Kustomize v4+:

```yaml
apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kustomize:
    buildArgs:
      - "--load-restrictor LoadRestrictionsNone"
```
