### ISSUE TITLE
Logging when Skaffold doesn't do build

### ISSUE THREAD

**Issue by JJRdec** [GoogleContainerTools/skaffold#7341]
Hi there, this a feature request.

I have a Skaffold profile (dev2 ) configured to deploy to a remote cluster. The profile has only a deploy stage, which uses k8s deployment files which pulls images from our remote private registry (using imagePullSecrets) .

**Example (one of many microservices)**
Note: Local's build and deploy stage have been excluded.
```
apiVersion: skaffold/v2beta28
kind: Config
profiles:
  - name: local
       .
       .
       .
  - name: dev2
    test:
      - image: cache
    deploy:
      kubeContext: <remote-context>
      logs:
        prefix: container
      kustomize:
        paths:
          - k8s/dev2
```

The issue is that Skaffold won't log for deployments/pods where the images haven't been built by Skaffold itself - why is this? 

This is a real pain for us as we are using to Skaffold to deploy to our remote clusters and using "--tail" would be great for a quick sanity check rather than using kubectl logs <pod> on all our micro-services. 

Request: have skaffold log for pods where it it hasn't built the image itself. 

Thanks :)
