### ISSUE TITLE
Templated Fields default not working on unset env var

### ISSUE THREAD

**Issue by tbuchier** [GoogleContainerTools/skaffold#7345]
Hello, 

I'm trying to use the `default` function added in this PR: [6136](https://github.com/GoogleContainerTools/skaffold/pull/6136)

### Expected behavior

I set a Templated Fields for my helm release version, and expect the default value to be used if my env var is not set.

### Actual behavior

```
cannot expand chart version "{{default \"0.1.0\" .CHART_VERSION}}": template: envTemplate:1:18: executing "envTemplate" at <.CHART_VERSION>: map has no entry for key "CHART_VERSION"
```

### Information

- Skaffold version: v1.38.0
- apiVersion: skaffold/v2beta28

```yaml
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: my-chart-name
deploy:
  helm:
    releases:
      - name: mychart
        remoteChart: myrepo/mychart
        namespace: dummy
        version: '{{default "0.1.0" .CHART_VERSION}}'
```

Thanks
