### ISSUE TITLE
fix/feat: The WIP Helm renderer must support writing labels labels via the `-l` flag

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7348]
Related to:
- #7336 

Currently there is a hotfix release being worked on (`v1.37.2`) which addresses #7336.  This change will also need to be in V2 when the time comes.  I would add it there now but the V2 helm renderer is still WIP so I have created this issue to track this work

**Comment by aaron-prindle** [comment]
Assigning @MarlonGamez.  No rush, just wanted to make you aware that this is required for the renderer to not break an important use case for partners

**Comment by aaron-prindle** [comment]
Manually verified this, working as intended on skaffold v2:
```
aprindle@aprindle ~/skaffold/examples/helm-deployment  [repro-7348]$ skaffold render -a build.artifacts --default-repo=gcr.io/aprindle-test-cluster -l hello=hello
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skaffold-helm
    hello: hello
  name: skaffold-helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skaffold-helm
  template:
    metadata:
      labels:
        app: skaffold-helm
        hello: hello
    spec:
      containers:
      - image: gcr.io/aprindle-test-cluster/skaffold-helm:v1.38.0-158-g6148e97c8@sha256:edc56808722d54433c342e40d99a699887b293f40e17769319f6980ac72d3498
        name: skaffold-helm

```
