### ISSUE TITLE
Helm Skaffold documentation could be made consistent

### ISSUE THREAD

**Issue by ShaneWhelan** [GoogleContainerTools/skaffold#7351]
Skaffold-Helm documentation is inconsistent about what artifactOverride to use.
https://skaffold.dev/docs/pipeline-stages/deployers/helm/

### Expected behavior
The documentation uses a consistent key under artifactOverides:
```yaml
      artifactOverrides:
        imageKey: gcr.io/my-project/my-image # no tag present!
```
        
### Actual behavior
The documentation linked above states: "**IMPORTANT: To get Skaffold to work with Helm, the `image` key must be configured in the skaffold.yaml.**"

Then has this yaml snippet using **"image"** as the key:
```yaml
      artifactOverrides:
        image: gcr.io/my-project/my-image # no tag present!
```

But in the **Image Reference Strategies** section the yaml snippet uses **"imageKey"** as the key:
```yaml
        artifactOverrides:
          imageKey: gcr.io/my-project/my-image 
```

So in my Skaffold Yaml I had **"image"** as the **IMPORTANT** warning had scared me into using it.
```yaml
        artifactOverrides:
        image: gcr.io/my-project/my-image # no tag present!`
```
Then in my deployment.yaml file I had **Values.imageKey**:
```yaml
spec:
  containers:
    - name: {{ .Chart.Name }}
      image: "{{.Values.imageKey}}"
```

There was a mismatch and no clear error that the Helm Values file override had not happened as expected, I figured it out by running Skaffold in debug mode, found the Helm command that Skaffold issued and ran it manually, then I could start to understand what went wrong.

I suggest the docs are cleaned up at least. I can imagine this is a hard situation to detect for the Skaffold code, unless Skaffold diffed the resulting yaml file and found that no variable override had taken place.

### Information

- Skaffold version: v1.37.1
- Operating system: macOS
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: helloworldk-s
build:
  artifacts:
  - image: gcr.io/xxxx/xxxx
    context: .
    jib: {}
deploy:
  helm:
    releases:
      - name: helloworld-app
        chartPath: helm/helloworld-app
        artifactOverrides:
          imageKey: gcr.io/xxxx/xxxx
        imageStrategy:
          fqn: {}
```
