### ISSUE TITLE
Getting error - build [skaffold-example] failed: exit status 125. Docker build ran into internal error.

### ISSUE THREAD

**Issue by rahu7624** [GoogleContainerTools/skaffold#7354]
Hi Team , 

Getting below error , while configuring skaffold for testing purpose.

 getting-started]$ skaffold dev
Listing files to watch...
 - skaffold-example
Generating tags...
 - skaffold-example -> skaffold-example:6157e06-dirty
Checking cache...
 - skaffold-example: Not found. Building
Starting build...
Found [custom] context, using local docker daemon.
Building [skaffold-example]...
Target platforms: [linux/amd64]
unknown flag: --platform
See 'docker build --help'.
build [skaffold-example] failed: exit status 125. Docker build ran into internal error. Please retry.
-->

### Information

- Skaffold version: v1.38.0-2-g31a5f6704
- Operating system: CentOS Linux release 7.9.2009 (Core)
- Installed via:  skaffold.dev   , https://skaffold.dev/docs/quickstart/
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...
