### ISSUE TITLE
Local builds are not used when overwriting values files

### ISSUE THREAD

**Issue by JoostDeCupere** [GoogleContainerTools/skaffold#7369]
### Expected behavior
artifactOverrides and valuesFiles can be used togheter. When a local build is done (in my case on kind) the image should be pushed in the cluster by skaffold and the cluster will use that pushed image without trying to fetch it from a docker repo

### Actual behavior
When I use this without the valuesFiles overwrite the image is found by my Pod. When I do have the valuesFiles overwrite my pod will try to pull the image from a docker repository.
### Information
The image seems to be loaded in the cluster correctly in both cases
```
Loading images into kind cluster nodes...
 - acs:89a51b77c871e11a847a8de213bc6ebc9c96c404f739ed8c2abccfc1d863b53e -> Loaded
```
And they are referenced correctly in the pod's image tag:
```yaml
 containers:
  - envFrom:
    - configMapRef:
        name: acs-configmap
    - secretRef:
        name: acs-secret
    image: acs:89a51b77c871e11a847a8de213bc6ebc9c96c404f739ed8c2abccfc1d863b53e
```
The only difference I see in the 2 pods is that when using the skaffold file withouth the valuesFiles overwrite (and all works) the containerStatusses of the pod it looks like this
```yaml
containerStatuses:
  - containerID: containerd://5f108f679b5449ee248e747d76cff3a43f85ecb6d915240eedf07cbd191fd20e
    image: docker.io/library/acs:89a51b77c871e11a847a8de213bc6ebc9c96c404f739ed8c2abccfc1d863b53e
    imageID: sha256:89a51b77c871e11a847a8de213bc6ebc9c96c404f739ed8c2abccfc1d863b53e
```
When the valuesFiles overwrite is specified the containerStatusses of the pod look like this (and it fails to pull the image)
```yaml
 containerStatuses:
  - image: acs:89a51b77c871e11a847a8de213bc6ebc9c96c404f739ed8c2abccfc1d863b53e
    imageID: ""
```

- Skaffold version: v1.36.0
- Operating system: Windows 10 pro - running skaffold from WSL
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: dauntless
build:
  local:
    concurrency: 0
  artifacts:
    - image: acs
      custom:
        buildCommand: ./buildAcsDockerImage.sh

deploy:
  helm:
    releases:
      - name: dauntless
        chartPath: helm
        artifactOverrides:
          acs.image.repository: acs
        valuesFiles:
          - local-values.yaml
```

### Steps to reproduce the behavior

Reproduced with skaffold dev

Logs from `skaffold dev -vdebug:
[skaffold-logs.txt](https://github.com/GoogleContainerTools/skaffold/files/8611380/skaffold-logs.txt)
