### ISSUE TITLE
Cannot pull image from Jfron to aks

### ISSUE THREAD

**Issue by sb185296** [GoogleContainerTools/skaffold#7385]
Hi team ,

its look like that the image tag that push , its not the image tag that its try to pull

i add my secret to the Image pull : 
```
      imagePullSecrets:
        - name: secret
      containers:
      - name: node
        image: docker-snapshots.jfrog.io/shaytest
        ports:
        - containerPort: 80
```

- Skaffold version: v1.38.0
- Operating system: Windows10
- Installed via: Chocolatey 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: service
build:
  artifacts:
  - image: docker-snapshots.jfrog.io/shaytest
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml


```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. skaffold dev

      waiting:
        message: 'rpc error: code = NotFound desc = failed to pull and unpack image
![image](https://user-images.githubusercontent.com/66299621/167317316-869776bc-3810-4061-98b1-1c22a3144bb5.png)
![image](https://user-images.githubusercontent.com/66299621/167317619-9859b080-48d5-421a-a7d4-de62624c3e86.png)
![image](https://user-images.githubusercontent.com/66299621/167317671-39176ae4-c24e-4a27-a169-6fc493aedc12.png)
