### ISSUE TITLE
Document an example on remote modules + local module

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#7392]
When talking with @russwolf, I realized we dont have an example demo for an application where there is one remote module along with  local module. 

e.g. 

```
apiVersion: skaffold/v2beta11
kind: Config
requires:
- git:
    repo: https://github.com/GoogleContainerTools/skaffold
    path: examples/multi-config-microservices/leeroy-app
    ref: main

- path: ./leeroy-web

```
and 
```
apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: web-config
requires:
- path: ../base
build:
  artifacts:
  - image: leeroy-web
    requires:
    - image: base
      alias: BASE
deploy:
  kubectl:
    manifests:
    - kubernetes/*
portForward:
- resourceType: deployment
  resourceName: leeroy-web
  port: 8080
  localPort: 9000
```

It will be cool to demo this set up to your users.
