### ISSUE TITLE
Add labels to Metadata

### ISSUE THREAD

**Issue by jlewi** [GoogleContainerTools/skaffold#7425]
I'd like to allow labels to be specified in the metadata of the Skaffold Config. e.g.

```
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: somename
  labels:
    somelabel: some value
```

The reason for this is we'd like to be able to use selectors to match some config.

I submitted https://github.com/GoogleContainerTools/skaffold/pull/6782 a while back to add labels to metadata.

Looks like a number of versions have been cut since then but they don't include the changes.
https://github.com/GoogleContainerTools/skaffold/blob/0aeb28476ffc7c84a457bb3bf63cd129728dbbec/pkg/skaffold/schema/v2beta28/config.go#L60

Any pointers about what additional changes are needed to properly support labels?

**Comment by ericzzzzzzz** [comment]
The pr was not linked to an issue when it was merged in to main, the issue should be closed.

**Comment by jlewi** [comment]
Thanks. I double checked and confirmed that this appears to be working with skaffold version `v2.0.3`.

And v4beta1.

```
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: vscode
  labels:
    somelabel: app
build:
  artifacts:
  - image: gcr.io/someimage/quickstart-image
    context: .
    kaniko:
      dockerfile: Dockerfile
```

```
~/Downloads/skaffold-darwin-arm64 build
Generating tags...
 - gcr.io/acme/quickstart-image -> gcr.io/acme/quickstart-image:bf99532-dirty
Checking cache...
 - gcr.io/acme/quickstart-image: Not found. Building
Starting build...
Building [gcr.io/acme/quickstart-image]...
```
