### ISSUE TITLE
Skaffold forcing localhost when other registry name is specified

### ISSUE THREAD

**Issue by nwithers-ecr** [GoogleContainerTools/skaffold#7431]
### Expected behavior
Skaffold will tag the artifacts with the registry provided
`registry.localhost:32000/api-gateway:2d7ca77d4@sha256:e11640290a608312c2cdd72c038bdfaef65cf2d7f2cca1fb62092ba28a265197`

### Actual behavior
Skaffold tags the artifacts forcing localhost and using the original registry as part of the name
`localhost:32000/registry_localhost_32000_api-gateway:2d7ca77d4@sha256:e11640290a608312c2cdd72c038bdfaef65cf2d7f2cca1fb62092ba28a265197`

### Information

- Skaffold version: v1.38.0
- Operating system: ubuntu 20.04 kernel 5.4.0-110-generic
- Installed via: skaffold.dev 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
  - image: registry.localhost:32000/api-gateway
    context: ../../../api-gateway
    docker:
      dockerfile: Dockerfile
      target: dev-test
      buildArgs:
        BUILD_TYPE: dev-test
  insecureRegistries:
  - registry.localhost:32000
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    push: true
    useBuildkit: true
    concurrency: 0
deploy:
  helm:
    releases:
    - name: nloop
      chartPath: ../../../../charts/split-charts/stable/nloop
      valuesFiles:
      - values.yaml
      artifactOverrides:
        apiGateway.deployment.image: registry.localhost:32000/api-gateway
      namespace: nloop
      createNamespace: true
      skipBuildDependencies: true
      imageStrategy:
        helm:
          explicitRegistry: true
  statusCheckDeadlineSeconds: 600
  kubeContext: k3d-nl-local
portForward:
- resourceType: Service
  resourceName: postgresql
  namespace: postgres
  port: 5432
  localPort: 5432
- resourceType: Service
  resourceName: redis-master
  namespace: nloop
  port: 6379
  localPort: 6379
```

### Steps to reproduce the behavior

1. A helm chart with a deployment to match the artifactOverride
2. `skaffold dev`
3. `kubectl describe pod`

### skaffold log

```
Listing files to watch...
 - registry.localhost:32000/api-gateway
Generating tags...
 - registry.localhost:32000/api-gateway -> localhost:32000/registry_localhost_32000_api-gateway:2d7ca77d4
Checking cache...
 - registry.localhost:32000/api-gateway: Found Remotely
Tags used in deployment:
 - registry.localhost:32000/api-gateway -> localhost:32000/registry_localhost_32000_api-gateway:2d7ca77d4@sha256:e11640290a608312c2cdd72c038bdfaef65cf2d7f2cca1fb62092ba28a265197
Starting deploy...
NAME: nloop
LAST DEPLOYED: Thu May 19 23:12:32 2022
NAMESPACE: nloop
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The website can be accessed at localhost
Waiting for deployments to stabilize...
 - nloop:deployment/api-gateway: waiting for rollout to finish: 0 of 1 updated replicas are available...
Cleaning up...
release "nloop" uninstalled
```

**Comment by msaunois-dzr** [comment]
Hi, I confirm the issue with skaffold v1.36.0.
I use a k3d cluster with a local registry (created by `k3d cluster create --registry-create my-registry.localhost:10042`).
I added an entry `127.0.0.1 my-registry.localhost` in my `/etc/hosts`. The deployment tries to pull the image from `localhost:10042` instead of using the original repository hostname.

**Comment by kamikasee** [comment]
I am seeing this behavior on 1.39.1 with a similar configuration -- the helm chart deployed by skaffold has the image set to something like:
`localhost:34523/k3d-quotable_registry_localhost_34523_quotable_backend:v0.1.1-25-g234f3a5@sha256:6ffe905441174d370d9376abc7796ebf42a013bec1c9dddc748d8781e0fcf9b6`

Where the image name in the skaffold file is:  `k3d.quotable.registry.localhost:34523/quotable/backend`

I've confirmed that an image named `k3d-quotable_registry_localhost_34523_quotable_backend:v0.1.1-25-g234f3a5@sha256:6ffe905441174d370d9376abc7796ebf42a013bec1c9dddc748d8781e0fcf9b6` exists in the registry.  The whole problem is the `localhost` which is not valid from inside the k3d cluster. 

It's notable that it's munging the the registry name into the image name.

I don't have a way to confirm this, but just because I was messing around with `*.localhost` name resolution, I wonder if it's caused by `k3d.quotable.registry.localhost` being resolved to `127.0.0.1` and then later `127.0.0.1` is reverse-resolved to `localhost`.

**Comment by blackandred** [comment]
Similar issue with k3d, unusable.

```
backup-maker-operator:pod/backup-maker-operator-584b85cf74-j8plh: container manager is waiting to start: localhost:5000/bm-registry_5000_backup-maker-operator:latest@sha256:2b6eb1dea55dceb7f6a038578ef7ab077000cd8c5babe9dcfbcc15351481bfea can't be pulled
```

```yaml
---
apiVersion: skaffold/v3
kind: Config
build:
    artifacts:
        - image: bm-registry:5000/backup-maker-operator
    local:
        push: true
        useBuildkit: true
    tagPolicy:
        gitCommit: { }
deploy:
    helm:
        releases:
            - name: backup-maker-operator
              chartPath: charts/backup-maker-operator
              recreatePods: true
              namespace: backup-maker-operator
              createNamespace: true
              setValueTemplates:
                  installCRD: "false"
                  image.repository: 'bm-registry:5000/backup-maker-operator'
                  image.tag: '{{.IMAGE_TAG}}'

```

**Comment by nwithers-ecr** [comment]
Still seeing this behavior in `v2.0.2-18-g682002a6e`

**Comment by gsquared94** [comment]
This seems due to [this](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/config/util.go#L367) local registry discovery implemented for local clusters in v1.36.0. Can you try deleting or modifying the `local-registry-hosting` config map in the `kube-public` namespace if it exists?

**Comment by rofrano** [comment]
I'm still seeing this behavior on v2.6.2 but I do have a workaround. Perhaps this will give some insight into what is happening:

I added `127.0.0.1    k3d-registry.local` to my `/etc/hosts` file, so that `k3d-registry.local` resolves to `127.0.0.1`

### Failure use case

If I create the k3d cluster with this command:

```bash
k3d cluster create --registry-create k3d-registry.local:0.0.0.0:5000
```

I can manually push images to `k3d-registry.local:5000/hitcounter` and it works fine. But if I use `scaffold dev`, Skaffold uses localhost and creates the wrong image name.

```
Generating tags...
 - k3d-registry.local:5000/hitcounter -> localhost:5000/k3d-registry_local_5000_hitcounter:0ac3d27-dirty
```

### Success use case

If, however, I create the registry separate from the cluster it works:

```bash
k3d registry create registry.local --port 5000
k3d cluster create --registry-config k3d-registries.yaml
```

Where `k3d-registries.yaml` contains:

```yaml
mirrors:
  "k3d-registry.local:5000":
    endpoint:
      - http://k3d-registry.local:5000
```

Then `scaffold dev` correctly picks up the correct registry name:

```
Generating tags...
 - k3d-registry.local:5000/hitcounter -> k3d-registry.local:5000/hitcounter:0ac3d27-dirty
```

I'm not sure why the first way fails and the second way succeeds but it is a workaround for anyone who is experiencing this problem.
