### ISSUE TITLE
`skaffold delete` not working as expected when using the WIP Cloud Run deployer

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7437]
Using the WIP Cloud Run Deployer it seems running `skaffold delete` fails and does not successfully delete the deployed Cloud Run service.  

Debug error logs for `$ skaffold delete`:
```
aprindle@aprindle ~/cloud-run-test $ skaffold -v debug delete
DEBU[0000] skaffold API not starting as it's not requested  subtask=-1 task=DevLoop
INFO[0000] Skaffold &{Version:v1.38.0-62-gf7575f014 ConfigVersion:skaffold/v3alpha1 GitVersion: GitCommit:f7575f014ddbce265704cf6f69d1908a8a0dc6da BuildDate:2022-05-23T13:40:54Z GoVersion:go1.18-pre13 cl/434556159 +428533fab4 Compiler:gc Platform:linux/amd64 User:}  subtask=-1 task=DevLoop
DEBU[0000] Disable housekeeping messages for command explicitly  subtask=-1 task=DevLoop
DEBU[0000] parsed 1 configs from configuration file /usr/local/google/home/aprindle/cloud-run-test/skaffold.yaml  subtask=-1 task=DevLoop
DEBU[0000] Defaulting build type to local build          subtask=-1 task=DevLoop
INFO[0000] Using kubectl context: gke_aprindle-test-cluster_us-central1-c_cluster-1  subtask=-1 task=DevLoop
INFO[0000] Loaded Skaffold defaults from "/usr/local/google/home/aprindle/.skaffold/config"  subtask=-1 task=DevLoop
DEBU[0000] Running command: [minikube version --output=json]  subtask=-1 task=DevLoop
DEBU[0000] Command output: [{"commit":"3e64b11ed75e56e4898ea85f96b2e4af0301f43d","minikubeVersion":"v1.25.1"}
]  subtask=-1 task=DevLoop
DEBU[0000] Running command: [/usr/local/bin/minikube profile list -o json --user=skaffold]  subtask=-1 task=DevLoop
DEBU[0000] Command output: [{"invalid":[],"valid":[]}]   subtask=-1 task=DevLoop
DEBU[0000] Running command: [/usr/local/bin/minikube profile list -o json --user=skaffold]  subtask=-1 task=DevLoop
DEBU[0000] Command output: [{"invalid":[],"valid":[]}]   subtask=-1 task=DevLoop
DEBU[0000] setting Docker user agent to skaffold-v1.38.0-62-gf7575f014  subtask=-1 task=DevLoop
INFO[0000] manifests hydration will take place in /usr/local/google/home/aprindle/cloud-run-test/.kpt-pipeline  subtask=-1 task=DevLoop
DEBU[0000] setting up kubectl renderer                   subtask=-1 task=DevLoop
DEBU[0000] CLI platforms provided: ""                    subtask=-1 task=DevLoop
DEBU[0000] platforms detected from active kubernetes cluster nodes: ""  subtask=-1 task=DevLoop
DEBU[0000] Using builder: local                          subtask=-1 task=DevLoop
DEBU[0000] push value not present in NewBuilder, defaulting to true because cluster.PushImages is true  subtask=-1 task=DevLoop
INFO[0000] build concurrency set to default value of -1  subtask=-1 task=DevLoop
Cleaning up...
DEBU[0000] Running command: [tput colors]                subtask=-1 task=DevLoop
DEBU[0000] Command output: [256
]                        subtask=-1 task=DevLoop
unexpected manifest for Cloud Run

```

Repro files & steps:

`skaffold.yaml`
```
apiVersion: skaffold/v3alpha1 
kind: Config
metadata:
   name: cloud-run-test
manifests:
  rawYaml:
    - service.yaml
deploy:
  cloudrun:
    defaultprojectid: aprindle-test-cluster
    region: us-central1
```

`service.yaml`
```
aprindle@aprindle ~/cloud-run-test $ cat service.yaml

apiVersion: "serving.knative.dev/v1"
kind: Service
metadata:
  name: skaffold-demo 
spec:
  template:
    spec:
      containers:
      - image: gcr.io/cloudrun/hello
```

steps:
```
$ skaffold deploy # using the above files
# it succeeds...
```
```
$ skaffold delete # using the above files
# it fails...
```
