### ISSUE TITLE
M1 users need `trustBuilder: true` to deploy with buildpacks

### ISSUE THREAD

**Issue by emmanuelbaah** [GoogleContainerTools/skaffold#7446]
When debugging with @gsquared94 discovered. that M1 users need `trustBuilder: true` to be able to deploy with buildpacks

### Expected behavior
After building the v1 branch, which has this #7355 fix, that M1 users would be able to use buildpacks and deploy to GKE
### Actual behavior
Instead fails with the following
```
Starting deploy...
 - deployment.apps/java-hello-world created
 - service/java-hello-world-external created
Waiting for deployments to stabilize...
 - pod/java-hello-world-745c8d748b-scgm8: creating container server
 - deployment/java-hello-world: creating container server
    - pod/java-hello-world-745c8d748b-scgm8: creating container server
 - pod/java-hello-world-745c8d748b-scgm8: container server terminated with exit code 1
1/1 deployment(s) failed
```
or gets hung up and never fails.

To get buildpacks to deploy, had to update the buildpacks section of the skaffold.yaml as follows
```
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
      trustBuilder: true
```
### Information

- Skaffold version: v1.38.0-13-g6cc40f32a
- Operating system: MacOS ARM
- Installed via: manually built v1 branch
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: java-hello-world
    context: .
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: dockerfile
  build:
    artifacts:
    - image: java-hello-world
```

### Steps to reproduce the behavior

1. Set up Cloud Code IntelliJ
2. clone hello world java sample app
3. (manually)configure skaffold.yaml for buildpacks (CCIJ is currently not allowing buildpacks as a builder option so you will have to manually configure the skaffold.yaml)
4. Attempt to `Develop on Kubernetes`
