### ISSUE TITLE
Support templating in build.artifacts.*.image

### ISSUE THREAD

**Issue by dinvlad** [GoogleContainerTools/skaffold#7455]
### Expected behavior
I'm trying to create a `skaffold.yaml` config to be reused among multiple projects. Right now, the only blocker is inability to set `build.artifacts.image` via a template variable, like so:
```yaml
apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
  - image: &name "{{.PROJECT}}"
    jib:
      project: *name
deploy:
  helm:
    releases:
    - name: *name
      chartPath: helm
      artifactOverrides:
        image: *name
```
which _could_ work using something like
```bash
PROJECT=project-name skaffold dev
```

### Actual behavior
Instead, since template variables are not understood in `build.artifacts.*.image`, we have to either
1) hard-code the image name and thus have a separate copy of `skaffold.yaml` for each individual project, or
2) use an external template substitution tool, for example `envsubst` or `gomplate` to pre-process `skaffold.yaml`, like so:
```bash
PROJECT=project-name envsubst <skaffold.yaml | skaffold dev -f -
```

Otherwise, Skaffold complains with a message like `invalid image "{{.PROJECT}}": invalid reference format`

### Information

- Skaffold version: `v1.38.0`
- Operating system: `MacOS 12.4`
- Installed via: Homebrew Google Cloud SDK
- Contents of skaffold.yaml: please see above

### Steps to reproduce the behavior

1. Create a Skaffold config similar to the above, with template variables in `build.artifacts.*.image`
2. Use any Skaffold command with it
3. Observe that template variables are not understood in `build.artifacts.*.image`
