### ISSUE TITLE
listing files: file pattern [./src/service2] must match at least one file

### ISSUE THREAD

**Issue by psolarcz** [GoogleContainerTools/skaffold#7457]
### Expected behavior
When using single Dockerfile to build multiple services Skaffold shouldn't consider files that are not required for specified service.

### Actual behavior
Skaffold gives following error:

``` bash
skaffold dev
Listing files to watch...
 - service1
listing files: file pattern [./src/service2] must match at least one file
```

### Information

- Skaffold version: v1.38.0
- Operating system: MacOs Monterey 12.3.1
- Installed via:  Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app
build:
  
  artifacts:
  # image tags are relative; to specify an image repo (e.g. GCR), you
  # must provide a "default repo" using one of the methods described
  # here:
  # https://skaffold.dev/docs/concepts/#image-repository-handling
  - image: service1
    context: .
    docker:
      buildArgs:
        SERVICE: "service1"

  local:
    push: false
    useBuildkit: true
    # useDockerCLI: false

```

Dockerfile:
``` yaml
ARG SERVICE

FROM python:3.9.13-alpine3.16 as base

FROM base AS app-prod-service1
    COPY ./src/service1 /app/src/

FROM base AS app-prod-service2
    COPY ./src/service2 /app/src/

FROM app-prod-${SERVICE} as app
```

### Steps to reproduce the behavior

1. `skaffold dev`
