### ISSUE TITLE
Can I use pre build hooks to calculate the value for env vars?

### ISSUE THREAD

**Issue by yfried** [GoogleContainerTools/skaffold#7458]
Hi
I have this build configuration:
```yaml
build:
  artifacts:
  - hooks:
      before:
        - command:
            - bash
            - -c
            - skaffold/pre_skaffold.sh
    docker:
      buildArgs:
        IMAGE_TAG: "{{ .BASE_IMAGE_TAG }}"
```
Is there a way I can set the value for `BASE_IMAGE_TAG` using pre build hook script?
(I need calc it base on git tags)

I think adding
`export BASE_IMAGE_TAG=$(git describe --tags)`
to the script won’t work. will it?

**Comment by aaron-prindle** [comment]
Currently, it is not possible to export env vars from hooks.  There is a TODO to add this feature to hooks but it is currently not prioritized and not prioritized in roadmap for the next ~6 months.

**Comment by kenho811** [comment]
I have a similar need to calculate the value for env vars before I invoke `skaffold deploy`.

I notice that `skaffold.env` only allows for static variables.

For instance, the below in `skaffold.env` does not work

```
KUBE_CONTEXT=$(kubectl config current-context)
```

When I use 


The below `skaffold.yaml` does not resolve {{ .KUBE_CONTEXT }} correct. it's resolved to `$(kubectl config current-context)`, without evaluating the expression....

```
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: skaffold-cfg

deploy:
  helm:
    releases:
      - name: traefik-cfg-{{ .KUBE_CONTEXT }}
        chartPath: ./k8s/helm/traefik-cfg
        namespace: kube-system
        valuesFiles:
          - ./k8s/helm/common/common.values.yaml
          - ./k8s/helm/common/{{ .KUBE_CONTEXT }}.values.yaml
      - name: minio-{{ .KUBE_CONTEXT }}
```
