### ISSUE TITLE
artifacts.hook.after and before doesn't login to container registry on host

### ISSUE THREAD

**Issue by rstoermer** [GoogleContainerTools/skaffold#7469]
### Expected behavior
I am executing a hook to login to our container registry. The login should work

### Actual behavior
I am not logged in and have to do it manually:
build [XXXXX.azurecr.io/orchestrator] failed: getting image: POST https://XXXXX.azurecr.io/oauth2/token: unexpected status code 401 Unauthorized

### Information

- Skaffold version: v1.38.0
- Operating system: OS X most current
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
      push: false
      useDockerCLI: true
      useBuildkit: true
  artifacts:
      - image: XXXXXXX.azurecr.io/orchestrator
        hooks:
          after:
          - command: ["az", "acr", "login", "-n", "nextordev"]
            os: [darwin]
        context: .
        docker:
            dockerfile: Dockerfile
            target: local
            buildArgs:
                NPM_TOKEN: "{{ .NPM_TOKEN }}"
        sync:
            manual:
                # Sync all folders relevant for application development
                - src: "src/**"
                  dest: .
```

before also doesn't work
