### ISSUE TITLE
Custom labels only added to select resources

### ISSUE THREAD

**Issue by omus** [GoogleContainerTools/skaffold#7471]
### Expected behavior

Expecting that using the `-l`/`--label` functionality skaffold provides to apply the label to all resources

### Actual behavior

The custom label is only applied to a subset of resources (e.g. Job, Deployment, Pod, Service) but not others (e.g. ConfigMap, Secret, SecretProviderClass).

### Information

- Skaffold version: v1.38.0
- Operating system: macOS 12.2.1 (arm64)
- Installed via: Homebrew
- Contents of `skaffold.yaml`:

```yaml
---
apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kubectl:
    manifests:
     - configmap.yaml
     - pod.yaml
```

- Contents of `configmap.yaml`:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
data:
  FOO: BAR
```

- Contents of `pod.yaml`:
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
```

### Steps to reproduce the behavior

1. Create an empty directory and populate it with the `skaffold.yaml`, `configmap.yaml`, and `pod.yaml` mentioned above
2. `skaffold render --digest-source=local --label custom=label`
3. Rendered ConfigMap does not contain the label `custom: label`
