### ISSUE TITLE
Modules from a multi-config project are deploying in the wrong contexts

### ISSUE THREAD

**Issue by renzodavid9** [GoogleContainerTools/skaffold#7506]
In a multi config project  (different `skaffold.yaml` files), where each config has a different deploy context (`kubeContext`), running `skaffold dev` deploys all the modules in all the contexts.

### Expected behavior
Every module should be deploy in its corresponding context

### Actual behavior
All the modules are deployed in all the contexts

### Information

- Skaffold version: v1.38.0-79-gc319fd6c3
- Operating system: MacOS Monterey
- Installed via: Local build using the main branch
- Contents of skaffold.yaml:

We can use the  example project [multi-config-microservices](https://github.com/GoogleContainerTools/skaffold/tree/main/examples/multi-config-microservices), adding different `kubeContext` for each module:

Modify `leeroy-app` skaffold.yaml file to add a `kubeContext`:
```yaml
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app-config
requires:
- path: ../base
build:
  artifacts:
  - image: leeroy-app
    requires:
    - image: base
      alias: BASE
deploy:
  kubeContext: context-one
  kubectl:
    manifests:
    - kubernetes/*
portForward:
- resourceType: deployment
  resourceName: leeroy-app
  port: http
  localPort: 9001
```

Modify `leeroy-web` skaffold.yaml file to add a `kubeContext`:
```yaml
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: web-config
requires:
- path: ../base
build:
  artifacts:
  - image: leeroy-web
    requires:
    - image: base
      alias: BASE
deploy:
  kubeContext: context-two
  kubectl:
    manifests:
    - kubernetes/*
portForward:
- resourceType: deployment
  resourceName: leeroy-web
  port: 8080
  localPort: 9000
```

The other yaml files in the example don't need a change.

### Steps to reproduce the behavior

1. Open the [multi-config-microservices](https://github.com/GoogleContainerTools/skaffold/tree/main/examples/multi-config-microservices) example
2. Modify the `skaffold.yaml` files listed above to add different `kubeContext`
3. Create the `context-one` and `context-two` contexts
4. Run `skaffold dev` in the multi-config-microservices example
5. Check the pods deployed in each context running `kubectl get pods --context=context-one` and `kubectl get pods --context=context-two`, you'll notice that all the modules were deployed in all the contexts
