### ISSUE TITLE
Allow use of remote manifests when specifying manifests 

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7558]
### Expected behavior
Skaffold v2 should be able to apply remote manifests (cluster resources) specified in `manifests.rawYaml`

### Actual behavior
Skaffold v2 doesn't currently have the piece of code needed for this ported over, so it doesn't work

**Comment by aaron-prindle** [comment]
This seems to work IIUC:

`skaffold.yaml`
```
aprindle@aprindle-ssd ~/skaffold/examples/remote-getting-started  [fix-7558]$ ls
build.artifacts  Dockerfile  main.go  README.md  skaffold.yaml

aprindle@aprindle-ssd ~/skaffold/examples/remote-getting-started  [fix-7558]$ cat skaffold.yaml 
apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - https://raw.githubusercontent.com/GoogleContainerTools/skaffold/main/examples/getting-started/k8s-pod.yaml
# deploy:
#   kubectl:
#     manifests:
```

```
aprindle@aprindle-ssd ~/skaffold/examples/remote-getting-started  [fix-7558]$ skaffold-v1.39.1 render -a build.artifacts --default-repo=gcr.io/aprindle-test-cluster 
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
  namespace: default
spec:
  containers:
  - image: gcr.io/aprindle-test-cluster/skaffold-example:v1.38.0-140-g804abffed-dirty@sha256:4d344cb9f87ec41c9a160ff62b685fd2e74968e420099f34ff113ac4d8161adb
    name: getting-started
aprindle@aprindle-ssd ~/skaffold/examples/remote-getting-started  [fix-7558]$ skaffold render -a build.artifacts --default-repo=gcr.io/aprindle-test-cluster 
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
spec:
  containers:
  - image: gcr.io/aprindle-test-cluster/skaffold-example:v1.38.0-140-g804abffed-dirty@sha256:4d344cb9f87ec41c9a160ff62b685fd2e74968e420099f34ff113ac4d8161adb
    name: getting-started
```
