### ISSUE TITLE
Feature request: Allow activating profile only when all (not any) of its activations are triggered

### ISSUE THREAD

**Issue by anhpngt** [GoogleContainerTools/skaffold#7604]
### Background

Currently, as per the [doc](https://skaffold.dev/docs/references/yaml/#profiles-activation):

> ... The profile is auto-activated if *any one* of the activations are triggered.

In my case, we have different profiles for different environments and tenants. Say, we have the following
- Environments: `ENV=stag` and `ENV=prod`
- Tenants: `ORG=us` and `ORG=eu`

meaning we have in total 4 different environment-tenant deployments (each has a different configuration).

The problem is when all 4 of those deployments stay in the same k8s cluster, we can't use profiles to make Skaffold auto-select the correct configuration (`command` and `kubeContext` values are identical for all 4 deployments).

We had hoped to use `env`, something like:

```yaml
profiles:
- name: stag.us
  activation:
  - env: ENV=stag
  - env: ORG=us
  # patch #1
- name: stag.eu
  activation:
  - env: ENV=stag
  - env: ORG=us
  # patch #2
...
```

However, since the activation strategy is `ANY`, not `ALL`, we cannot make it to have only 1 profile triggered.

### Suggestion/Request

Is it possible to have a new field (`requireAllActivations: boolean` maybe?) to customize that behavior? I'm looking at the [activatedProfiles](https://github.com/GoogleContainerTools/skaffold/blob/88a27ab9f81f337fa0fe4207aa829f632a01787e/pkg/skaffold/schema/profiles.go#L92) function. Looks like changing it may help.

### Follow-up design

A new config `requiresAllActivations` will be introduced:

```yaml
profiles:
- name: ...
  activation: []
  requiresAllActivations: false # Must be a boolean. Defaults to `false`.
```

when this field is `true`, **all** the activations are required in order to make profile auto-activated.

The addition is backward compatible.

### Implementation plan

- Add config field `requiresAllActivations`
- Update logic in [activatedProfiles function](https://github.com/GoogleContainerTools/skaffold/blob/88a27ab9f81f337fa0fe4207aa829f632a01787e/pkg/skaffold/schema/profiles.go#L92)
- Unit tests and documentation

### Information

- Skaffold version: `v1.39.1`
- Operating system: `Ubuntu 22.04`
- Installed via: `skaffold.dev`
- Contents of skaffold.yaml: N/A

(Updated on Jul 2 to try to make it a proper [design proposal](https://github.com/GoogleContainerTools/skaffold/blob/main/docs/design_proposals/design-proposal-template.md))
