### ISSUE TITLE
Skaffold's status check is skipping Deployments that have duplicate sections in their manifest

### ISSUE THREAD

**Issue by alex12345555** [GoogleContainerTools/skaffold#7605]
### Information

I had this Kubernetes manifest - mistakenly, I have put **2 same sections (_ports_ section)** in the manifest. I prepared an example configuration to reproduce this issue. This is the manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        ports:
        - containerPort: 80
```
When I put this in Helm chart and deploy it with
`helm install --wait nginx nginx`
helm waits until the Deployment is Ready.

When I try to do this with skaffold, it doesn't even recognize it as a deployment that should be waited for and the `skaffold dev|deploy` commands finish immediately (in milliseconds).

### Expected behavior
When running `skaffold dev` or `skaffold deploy`, the following behaviour should be expected by skaffold.

![image](https://user-images.githubusercontent.com/108415709/176476111-ae2a946f-a2a9-4030-a709-1eb1624905b5.png)

### Actual behavior
This is the actual behavior when having a Kubernetes manifest with 2 same sections.

![image](https://user-images.githubusercontent.com/108415709/176476641-2870fe42-06e9-4f30-be55-20f9bfb885e7.png)

This also happens if there is a duplicate **env** section in the Deployment manifest. Probably happens with other sections too, but haven't tested them.

### Versions

Skaffold and Helm were installed through asdf.

- Skaffold version: 1.39.1
- Helm version: 3.8.2
- Kubernetes version: 1.22

### Steps to reproduce the behavior

1. ```git clone https://github.com/alex12345555/skaffold-deployment```
2. Run `skaffold dev` or `skaffold deploy` and see the actual behavior.
3. To get the expected behavior, remove one of the **ports** sections in _nginx/templates/deployment.yaml_ file and run `skaffold dev` again.
