### ISSUE TITLE
Could not build with kaniko when docker proxy with auth

### ISSUE THREAD

**Issue by yurchenkosv** [GoogleContainerTools/skaffold#7615]
### Expected behavior
Successful build 

### Actual behavior
ImagePullBackOff in k8s cluster when skaffold build with kaniko

### Information

- Skaffold version: v1.35.2  
- Operating system: MacOS 
- Installed via: Homebrew 
- Contents of skaffold.yaml:

```yaml
build:
  artifacts:
    - image: <imagename>
      kaniko:
        dockerfile: build/Dockerfile
        buildArgs:
          BASE_IMAGE_NAME: "{{ .BASE_IMAGE_NAME }}"
        cache: {}
  cluster:
    concurrency: 1
    namespace: "default"
    randomDockerConfigSecret: false
    randomPullSecret: false
    pullSecretName: pullsecret
    dockerConfig:
      path: dockerconfig.json
    resources:
      requests:
        cpu: '200m'
        memory: '500Mi'
      limits:
        cpu: '200m'
        memory: '500Mi'       
  tagPolicy:
    envTemplate:
      template: "{{ or .IMAGE_TAG }}"
```

### Steps to reproduce the behavior

1. k8s  cluster without internet for kanko build  
2. docker proxy only able to get docker images 
3. skaffold build
4. kubectl describe pod ...
ImagePullBackoff in status
