### ISSUE TITLE
Skaffold crashes if it fails to delete kaniko pods

### ISSUE THREAD

**Issue by GagarinX** [GoogleContainerTools/skaffold#7620]
### Desired behavior

Skaffold continues deploying the app after building it, even if it failed to delete Kaniko pod(s).

### Actual behavior

If skaffold fails to delete kaniko pod(s) after building the image(s), it exits with a fatal error.

### Information

- Skaffold version: v1.39.1
- Operating system: Ubuntu Linux 20.04
- Installed via: binary from Github Releases
- Contents of skaffold.yaml (relevant parts):

```yaml
apiVersion: skaffold/v2beta7
kind: Config
profiles:
  - name: dev-remote
    build:
      artifacts:
        - image: <redacted>
          context: ../.
          sync:
            manual:
              *sync_folders
          kaniko:
            dockerfile: <redacted>
            cache:
              repo: <redacted>
      cluster:
        dockerConfig:
          secretName: dockerconfig
      tagPolicy:
        dateTime: { }
    deploy:
      helm:
        releases:
          - name: <redacted>
            chartPath: <redacted>
            version: <redacted>
            remote: true
            upgradeOnChange: true
            artifactOverrides:
              image: <redacted>
            imageStrategy:
              helm: { }
            valuesFiles:
              - ./values.yaml
```

### Steps to reproduce the behavior

1. In skaffold.yaml describe image building in k8s cluster using kaniko.
2. Run `skaffold dev`
3. Watch pods in your k8s clusted, and wait until kaniko pod is done building and moves to "Completed" phase
4. Delete the kaniko pod before skaffold does.
5. Skaffold exits with a fatal error and the app is not deployed:

```
FATA[0071] deleting pod: pods "kaniko-m4hdz" not found   subtask=<redacted> task=Build
```

### Description
kube-controller-manager does garbage collection, which cleans up terminated Pods when their number exceeds the configured threshold. It leads to situations when kube-controller-manager deletes completed kaniko pods before skaffold deletes them, which leads to skaffold crashing.

My proposal:
- Skaffold should not crash, instead it should emit an error and go on with deploying. Failing to delete the pods is not a big enough deal for skaffold IMO to crash completely.
- To do it, you may change log level of pod deletion error from Fatal to Error: #7621 
- Another possible solution is adding an option, which would allow to choose whether skaffold should crash or not.
