### ISSUE TITLE
Using Kustomize plugins (old style) with Skaffold fails due to undetermined plugin path for Kustomize

### ISSUE THREAD

**Issue by spstarr** [GoogleContainerTools/skaffold#7623]
### Expected behavior
Kustomize plugin runs accordingly from the git repo cloned

### Actual behavior
$ KUSTOMIZE_PLUGIN_HOME="?????" NAMESPACE=myapp-dev ECR_PATH=develop DEPLOYMENT_COLOR=blue COMPONENT_NAME="my-app" COMPONENT_BUILD=develop skaffold deploy --profile dev -f skaffold.yaml 
Tags used in deployment:
Starting deploy...
running [kustomize build --enable-alpha-plugins --enable-exec /home/spstarr/.skaffold/repos/SZ3H6TqRJBxZmak0c_kMWYmFOJ73zJ8i/kustomize/overlays/dev]
 - stdout: ""
 - stderr: "Error: unable to find plugin root - tried: ('/build/skaffold/kustomize/plugins'; homed in $KUSTOMIZE_PLUGIN_HOME), ('<no value>'; homed in $XDG_CONFIG_HOME), ('/home/spstarr/.config/kustomize/plugin'; homed in default value of $XDG_CONFIG_HOME), ('/home/spstarr/kustomize/plugin'; homed in home directory)\n"
 - cause: exit status 1
 - 
### Information

- Skaffold version: v1.39.1
- Operating system: Fedora
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

Top level-skaffold.yaml:
```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
   name: darwin
requires:
     - configs: ["skaffold-my-app"]
       git:
         repo: https://github.com/MyCompany/my-app.git
         path: skaffold/dev/skaffold.yaml
         ref: develop
       activeProfiles:
       - name: dev
         activatedBy: [dev]
profiles:
- name: dev
```

Repo level `skaffold.yaml`:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: skaffold-my-app

profiles:
  - name: dev
    activation:
      - env: DEPLOY_OVERLAY=dev
    deploy:
      kustomize:
        paths:
         - ../kustomize/overlays/dev
        flags:
          disableValidation: false
        defaultNamespace: myapp-dev
        buildArgs: ["--enable-alpha-plugins", "--enable-exec"]
```

### Steps to reproduce the behavior

`KUSTOMIZE_PLUGIN_HOME="?????" NAMESPACE=myapp-dev ECR_PATH=develop DEPLOYMENT_COLOR=blue COMPONENT_NAME="my-app" COMPONENT_BUILD=develop skaffold deploy --profile dev -f skaffold.yaml `
