### ISSUE TITLE
[Verify Support] skaffold verify command should fail if run with no verify stanza/tests

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7631]
Currently if `skaffold verify` is run on on a skaffold.yaml configuration w/o a verify stanza, verify exits with exitCode:0.  To prevent misconfigurations, etc we want this to instead exit with exitCode:1 on this error.

ex:
```
apiVersion: skaffold/v3alpha1
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  local: {}
deploy:
  kubectl:
    manifests:
    - /manifests/deployment.yaml
  logs:
    prefix: container
```

```
$ skaffold verify
...<prints some to stdout but runs nothing>
$ echo $?
0 # <-- want 1 in this case
```
