### ISSUE TITLE
[Multi-platform Support] Update render output with appropriate `nodeAffinity` definitions for image `platforms`

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#7637]
In the `Render` phase, during image reference substitution, in the kubernetes manifests that reference a built artifact, Skaffold should add the appropriate `nodeAffinity` definition to schedule pods in matching platforms. For example, for an artifact `skaffold-example` built for the platforms `linux/arm64` and `linux/amd64` and referenced in a `Pod` spec, Skaffold will add the following nodeAffinity that forces it to be scheduled on an `arm64` or `amd64` arch node.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values: [ "arm64", "amd64" ]
          - key: kubernetes.io/os
            operator: In
            values: [ "linux" ]
  containers:
    - name: skaffold-example
      image: gcr.io/skaffold-example:latest
```
