### ISSUE TITLE
"skaffold verify" erroring when same container (image+tag) is reused in multiple steps (eg: alpine:latest)

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7640]
Currently if "skaffold verify" is run with the same container-image+tag (eg: alpine:3 in the below example) skaffold verify will have some issues running-containers/reading-logs as there is mutliple containers with duplicate names.  

skaffold.yaml `verify` snippet:
```
verify:
- name: integration-test
  container:
    name: integration-test-container
    image: alpine:3
    command: ["/bin/false"]
- name: environment-variables
  container:
    name: environment-variables-container
    image: alpine:3
    command: ["/bin/echo"]
    args: ["$GOOGLE_APPLICATION_CREDENTIALS"]
- name: random-print
  container:
    name: randomly-printing
    image: alpine:3
    command: ["/bin/echo"]
    args: ["calling it a day!"]
```

shell error:
```
$ skaffold verify
Tags used in verification:
3: Pulling from library/alpine
Digest: sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
Status: Image is up to date for alpine:3
3: Pulling from library/alpine
Digest: sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
Status: Image is up to date for alpine:3
3: Pulling from library/alpine
Digest: sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
Status: Image is up to date for alpine:3
[alpine:3] calling it a day!
2 error(s) occurred:
* creating container in local docker: Error response from daemon: Conflict. The container name "/alpine-6" is already in use by container "6d2c78907132b4775089dd1a87742d608174982ab9a049a27726fc9e15ce8cd4". You have to remove (or rename) that container to be able to reuse that name.
* verify test failed: "integration-test" running container image "alpine:3" errored during run with status code: 1
```

The best fix here is likely to modify the container name to instead be the `verify-test-name` although I as verify is built on the docker deployer this will likely be nontrivial
