### ISSUE TITLE
running skaffold dev: unable to find manifests

### ISSUE THREAD

**Issue by qwerjkl112** [GoogleContainerTools/skaffold#7649]
### Expected behavior

service should be created and deployed

### Actual behavior

Got above error and service is not created

### Information

- Skaffold version: 
 v1.29.0-537-g1dd36d207
- Operating system: 
glinux
- Installed via: 
make && make install
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3alpha1 
kind: Config
metadata:
   name: cloud-run-test
build:
    artifacts:
      - image: gcr.io/***/devdemo
    local:
      push: true
manifests:
  rawYaml:
    - service.yaml
deploy:
  cloudrun:
    projectid: ****
    region: ***
portForward:
  - resourceType: service
    resourceName: skaffold-demo
    localPort: 9000
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold dev`
