### ISSUE TITLE
skaffold doesn't support upgrade schema for kustomize project with buildArg

### ISSUE THREAD

**Issue by ericzzzzzzz** [GoogleContainerTools/skaffold#7678]
while running skaffold render with v2beta29 schema for an kustomize project
```yaml
apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kustomize:
    buildArgs:
      - "-o fail.yaml"
```
got this error : 
```bash
parsing skaffold config: error parsing skaffold configuration file: transforming skaffold config: upgrading main pipeline: converting deploy.kustomize.buildArgs isn't currently supported
```

it looks like that skaffold doesn't support buildArg upgrade for kustomize on purpose. However, when running ``skaffold render`` with the newest schema, 
```yaml
apiVersion: skaffold/v3alpha1
kind: Config
manifests:
  kustomize:
    paths:
      - .
    buildArgs:
      - "-o abc.yaml"
```
everything works perfectly. 

### Expected Behavior
 - not sure what is the expected behavior, if the new config provided above works, why skaffold doesn't support upgrade buildArg? 

### Actual Behavior 
 - skaffold failed to upgrade schema for kustomize project with buildArg

### Information

- Skaffold version: 
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

### Steps to reproduce the behavior

1. run `skaffold render -f skaffold-kustomize-upgrade-fail.yaml` in this project https://github.com/ericzzzzzzz/skaffold/tree/bug-bash-testing/examples/kustomize
2. should see this error 
```bash
parsing skaffold config: error parsing skaffold configuration file: transforming skaffold config: upgrading main pipeline: converting deploy.kustomize.buildArgs isn't currently supported
```
