### ISSUE TITLE
Skaffold build fails with Colima VM

### ISSUE THREAD

**Issue by akharlamov** [GoogleContainerTools/skaffold#7708]
### Expected behavior
`skaffold build` works without any issues

### Actual behavior
```
$ colima start
$ docker ps -a
 aih1013@AIH1013-TAILIFY > ~/dev/fides > docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
$ scaffold build
Generating tags...
 - registry.tailify.com/tailify/fides-base -> registry.tailify.com/tailify/fides-base:0861de9b9beae704f3e3b965f05cb330a0e819517a3656eb4b22ad30ed14e315
 - registry.tailify.com/tailify/fides-code -> registry.tailify.com/tailify/fides-code:20374fc0946ce50a6ddfb3ce02832d2ccfc274a2a690893f363b5d1aa1a31125
 - registry.tailify.com/tailify/fides-spark -> registry.tailify.com/tailify/fides-spark:94f4115f235371916e517567e810af4a6f210f88f2423d0dc85a974f4753db09
 - registry.tailify.com/tailify/fides-backend -> registry.tailify.com/tailify/fides-backend:a3c2db8950352e944a5ab2cfcf88be208a2dc988402b81e1378dd9ac6c91c8b2
Checking cache...
 - registry.tailify.com/tailify/fides-base: Not found. Building
 - registry.tailify.com/tailify/fides-code: Not found. Building
 - registry.tailify.com/tailify/fides-spark: Not found. Building
 - registry.tailify.com/tailify/fides-backend: Not found. Building
Starting build...
Building [registry.tailify.com/tailify/fides-backend]...
Target platforms: [linux/amd64]
#1 [internal] load build definition from Dockerfile.backend
#1 sha256:0448532a0304b4a56a83da5345330cd1f71be66c64f1c2d0c98b1ae414370612
#1 transferring dockerfile: 45B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:e393cd93bd39a52ab83f9d569bd301cad02a034eee3057cd8f3a599fbcb56a74
#2 transferring context: 35B done
#2 DONE 0.0s

#3 [internal] load metadata for registry.tailify.com/docker.io/library/node:16-alpine
#3 sha256:97b11614939362db708758ed8a49b050c8b976f2d42809171f31d35a6684e1f7
#3 DONE 1.0s

[CUT]

#15 exporting to image
#15 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#15 exporting layers done
#15 writing image sha256:81974760b21c79c155e6d35b503518a3cfb87ed29f9f4ffeb4603f0b3a9f5f40 done
#15 naming to registry.tailify.com/tailify/fides-backend:a3c2db8950352e944a5ab2cfcf88be208a2dc988402b81e1378dd9ac6c91c8b2 done
#15 DONE 0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building [registry.tailify.com/tailify/fides-base]...
Target platforms: [linux/amd64]
Build [registry.tailify.com/tailify/fides-base] was canceled
getting imageID for registry.tailify.com/tailify/fides-backend:a3c2db8950352e944a5ab2cfcf88be208a2dc988402b81e1378dd9ac6c91c8b2: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..

$ docker ps -a
 🐍 fides-dThD9j3p-py3.9  ⎈ |kubernetes-admin@gaia:dev2   master
 aih1013@AIH1013-TAILIFY  ~/dev/fides  docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

### Information

- Skaffold version: v1.37.0
- Operating system: Darwin AIH1013-TAILIFY.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: fides
build:
  artifacts:
    - image: registry.tailify.com/tailify/fides-base
      context: .
      docker:
        dockerfile: k8s/docker/Dockerfile.base
      sync:
        infer:
          - /opt/*
    - image: registry.tailify.com/tailify/fides-code
      requires:
        - image: registry.tailify.com/tailify/fides-base
          alias: BASE
      sync:
        infer:
          - /opt/*
      context: .
      docker:
        dockerfile: k8s/docker/Dockerfile.code
    - image: registry.tailify.com/tailify/fides-spark
      context: .
      docker:
        dockerfile: k8s/docker/Dockerfile.spark
      requires:
        - image: registry.tailify.com/tailify/fides-code
          alias: BASE
    - image: registry.tailify.com/tailify/fides-backend
      context: .
      docker:
        dockerfile: k8s/docker/Dockerfile.backend
  platforms:
    - linux/amd64
  local:
    push: true
    useBuildkit: true
    tryImportMissing: true
  tagPolicy:
    inputDigest: {}
deploy:
  kustomize:
    buildArgs:
      - "--load-restrictor=LoadRestrictionsNone"
    paths:
      - k8s/base
```

### Steps to reproduce the behavior
See above

Debug logs
```
Generating tags...
 - registry.tailify.com/tailify/fides-base -> registry.tailify.com/tailify/fides-base:0861de9b9beae704f3e3b965f05cb330a0e819517a3656eb4b22ad30ed14e315
 - registry.tailify.com/tailify/fides-code -> registry.tailify.com/tailify/fides-code:20374fc0946ce50a6ddfb3ce02832d2ccfc274a2a690893f363b5d1aa1a31125
 - registry.tailify.com/tailify/fides-spark -> registry.tailify.com/tailify/fides-spark:94f4115f235371916e517567e810af4a6f210f88f2423d0dc85a974f4753db09
 - registry.tailify.com/tailify/fides-backend -> registry.tailify.com/tailify/fides-backend:a3c2db8950352e944a5ab2cfcf88be208a2dc988402b81e1378dd9ac6c91c8b2
Checking cache...
 - registry.tailify.com/tailify/fides-base: Not found. Building
 - registry.tailify.com/tailify/fides-code: Not found. Building
 - registry.tailify.com/tailify/fides-spark: Not found. Building
 - registry.tailify.com/tailify/fides-backend: Not found. Building
Starting build...
Building [registry.tailify.com/tailify/fides-base]...
Target platforms: [linux/amd64]
#1 [internal] load build definition from Dockerfile.base
#1 sha256:c9eebc0e856ec4cb297d9b2936bbd8db0f13ea82e945ddc5f62a646f7ac38f1f
#1 transferring dockerfile: 2.40kB done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:8ca0d079f5b50b75d999e6d76776ee399de45b70b549855ba9c375a418ae1670
#2 transferring context: 35B done
#2 DONE 0.0s

#3 resolve image config for docker.io/docker/dockerfile:1.2
#3 sha256:b239a20f31d7f1e5744984df3d652780f1a82c37554dd73e1ad47c8eb05b0d69
#3 DONE 0.5s

#4 docker-image://docker.io/docker/dockerfile:1.2@sha256:e2a8561e419ab1ba6b2fe6cbdf49fd92b95912df1cf7d313c3e2230a333fdbcc
#4 sha256:37e0c519b0431ef5446f4dd0a4588ba695f961e9b0e800cd8c7f5ba6165af727
#4 CACHED

#5 [internal] load metadata for registry.tailify.com/docker.io/library/ubuntu:focal-20220113
#5 sha256:08d21ef3719edb55ef4648b11df81433765fec62f44be0fe2b08c501f1a9a5cb
#5 DONE 0.8s

#6 [stage-0  1/16] FROM registry.tailify.com/docker.io/library/ubuntu:focal-20220113@sha256:669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be
#6 sha256:aa681eb17be6cb97f3e77562309061240e9f5f24ba48d3934093311e4e8f90bb
#6 DONE 0.0s

#12 [internal] settings cache mount permissions
#12 sha256:95f4b4893eef947aaefc6923e2f32ce095fea57ec8916f90d13cc8c208ad8b2d
#12 DONE 0.0s

#14 [internal] load build context
#14 sha256:879655afb433719adb6008518b3eb162c24cdc68934a7ce0af4da4b0eb991024
#14 transferring context: 31.42kB done
#14 DONE 0.0s

#10 [stage-0  5/16] RUN rm -f /etc/apt/apt.conf.d/docker-clean &&     echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
#10 sha256:99e819905dd107d2930b38f802b306ed719f492ceaedf7d7a9ad530d7231a3ad
#10 CACHED

#20 [stage-0 13/16] COPY k8s/docker/spark/decom.sh /opt
#20 sha256:7a917f72e398e762b68e02ea4042470f9da8f8d08dc401fdeec1787869a2f998
#20 CACHED

#13 [stage-0  7/16] RUN --mount=type=cache,target=/tmp/pycache,uid=0,sharing=locked     /usr/bin/python3.9 -m pip install -U pip &&     pip install setuptools wheel &&     pip install poetry==1.2.0b3 &&     virtualenv --python /usr/bin/python3.9 /opt/venv
#13 sha256:59f2c74c0134a7e340efedf35bbd26ad3dafe26fa012224bc17569f33606984b
#13 CACHED

#15 [stage-0  8/16] COPY requirements.txt requirements.txt
#15 sha256:a5324e19ca6157dccec97cc1513d19fc724ff62eb983ccf869fff72485b71b6f
#15 CACHED

#21 [stage-0 14/16] COPY java-deps.csv /opt
#21 sha256:6e06212a11f6d4138423683cda14b6be12918a89d9df7dd96b00bab709ae7c18
#21 CACHED

#17 [stage-0 10/16] RUN webdrivermanager --downloadpath /opt --linkpath /usr/local/bin firefox
#17 sha256:71a05f0f173a5c656ea18bd1c942a3da0a1f29ac10ce6ba4cc4aa1a3fcc11bf3
#17 CACHED

#18 [stage-0 11/16] COPY k8s/docker/spark/entrypoint.sh /opt/spark-entrypoint.sh
#18 sha256:2279aa3ef2794fb22e37de3300549830deda37f4cc02875de6e479da3356ee44
#18 CACHED

#16 [stage-0  9/16] RUN --mount=type=cache,target=/tmp/pycache,uid=0,sharing=locked     pip install --no-dependencies -r requirements.txt
#16 sha256:f15f7c94efa0a5626b0eb21c553e326a25e40038b9b5950a801f017632539141
#16 CACHED

#19 [stage-0 12/16] COPY k8s/docker/spark/history-server-entrypoint.sh /opt/history-server-entrypoint.sh
#19 sha256:201d0dd61dbabdd2896b2b1bb630ecc904227dc9e234bf688c242770c882af9e
#19 CACHED

#8 [stage-0  3/16] WORKDIR /opt/project
#8 sha256:db8b71e66034eec5a6be9cb9d53572ed9fa1a919e73387673540321b92e17c83
#8 CACHED

#22 [stage-0 15/16] COPY tools/lib/common.sh /opt
#22 sha256:bed99c223a30aa23bcfbf2422017749fd2a9e4aaa818fd761fc80534b38efdc7
#22 CACHED

#9 [stage-0  4/16] RUN ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone
#9 sha256:70c53fbac730a128af3368515d096cf2d776ba00e319ccf15316f1a1d1e3a065
#9 CACHED

#7 [stage-0  2/16] RUN mkdir -p /opt/project && chmod -R ug+rw /opt &&    mkdir -p /tmp/pycache/pip
#7 sha256:48d16817fe5df48a5f21f9b4c4e73b5145ce143a68d3f9b3fd1d53b79354eaca
#7 CACHED

#11 [stage-0  6/16] RUN --mount=type=cache,target=/var/cache/apt,sharing=locked     --mount=type=cache,target=/var/lib/apt,sharing=locked     apt-get update &&    apt-get -y --no-install-recommends install curl apt-utils ca-certificates             python3.9 python3-pip python3-mysqldb python3-virtualenv             openjdk-8-jdk firefox bash tini util-linux mysql-client
#11 sha256:4f1cb73c1a7687100374957db442ff123ae28d46bed7ca871b8b9e6599bda066
#11 CACHED

#23 [stage-0 16/16] RUN SPARK_DIR=$(/opt/venv/bin/python /opt/venv/bin/find_spark_home.py) &&     ln -s $SPARK_DIR /opt/spark &&     . /opt/common.sh &&     download_java_deps /opt/java-deps.csv /opt/spark/jars
#23 sha256:89f7fa883ada5b1898bf6615c1fc651f905a5274c5b9cd5a72b7218a04877013
#23 CACHED

#24 exporting to image
#24 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#24 exporting layers done
#24 writing image sha256:bde384220663fac74d74b1ef620ae91205c40ed5865fca1147f6740782664c43 done
#24 naming to registry.tailify.com/tailify/fides-base:0861de9b9beae704f3e3b965f05cb330a0e819517a3656eb4b22ad30ed14e315 done
#24 DONE 0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building [registry.tailify.com/tailify/fides-backend]...
Target platforms: [linux/amd64]
Build [registry.tailify.com/tailify/fides-backend] was canceled
```
