### ISSUE TITLE
Skaffold build fails after `docker prune`

### ISSUE THREAD

**Issue by akharlamov** [GoogleContainerTools/skaffold#7710]
### Expected behavior
Build succeeds

### Actual behavior
```
Generating tags...
 - registry.tailify.com/tailify/fides-base -> registry.tailify.com/tailify/fides-base:0861de9b9beae704f3e3b965f05cb330a0e819517a3656eb4b22ad30ed14e315
 - registry.tailify.com/tailify/fides-code -> registry.tailify.com/tailify/fides-code:ab17de4ef721d27debf7d7899716a43ee44b59431f0618faa3b3d6d4ea0e33e7
 - registry.tailify.com/tailify/fides-spark -> registry.tailify.com/tailify/fides-spark:d2ec5688f8edcba2bd795dd7a533763f2733ab40c5543e24c60cef44306c2419
 - registry.tailify.com/tailify/fides-backend -> registry.tailify.com/tailify/fides-backend:35c051b2ede582eff6d342a8af8bc7aea250c4a73452fda7dc3159d411c78911
Checking cache...
 - registry.tailify.com/tailify/fides-base: Found Remotely
 - registry.tailify.com/tailify/fides-code: Found Remotely
 - registry.tailify.com/tailify/fides-spark: Found Remotely
 - registry.tailify.com/tailify/fides-backend: Found Remotely

Error response from daemon: No such image: registry.tailify.com/tailify/fides-code:ab17de4ef721d27debf7d7899716a43ee44b59431f0618faa3b3d6d4ea0e33e7
Error: Process completed with exit code 1.
```

### Information

- Skaffold version: 1.37.0
- Operating system: Darwin AIH1013-TAILIFY.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: fides
build:
  artifacts:
    - image: registry.tailify.com/tailify/fides-base
      context: .
      docker:
        dockerfile: k8s/docker/Dockerfile.base
      sync:
        infer:
          - /opt/*
    - image: registry.tailify.com/tailify/fides-code
      requires:
        - image: registry.tailify.com/tailify/fides-base
          alias: BASE
      sync:
        infer:
          - /opt/*
      context: .
      docker:
        dockerfile: k8s/docker/Dockerfile.code
    - image: registry.tailify.com/tailify/fides-spark
      context: .
      docker:
        dockerfile: k8s/docker/Dockerfile.spark
      requires:
        - image: registry.tailify.com/tailify/fides-code
          alias: BASE
    - image: registry.tailify.com/tailify/fides-backend
      context: .
      docker:
        dockerfile: k8s/docker/Dockerfile.backend
  platforms:
    - linux/amd64
  local:
    push: true
    useBuildkit: true
    tryImportMissing: true
  tagPolicy:
    inputDigest: {}
deploy:
  kustomize:
    buildArgs:
      - "--load-restrictor=LoadRestrictionsNone"
    paths:
      - k8s/base
```

### Steps to reproduce the behavior

1. `skaffold build`
OK
2. docker prune system 
3. `skaffold build`
Failure
4. `rm -rf ~/.skaffold/cache`
5. `skaffold build`
OK
