### ISSUE TITLE
[v2][verify] skaffold verify docker.io images that have a "/" in them - ex: "alpine/curl:latest"

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7752]
Currently `skaffold verify` is not able to properly parse skaffold docker.io images (with the repo ommitted) that have a "/" in them - ex: "alpine/curl:latest".  For example:

working `verify` stanza
```
- name: alpine-wget
  container:
    name: alpine-wget
    image: alpine:3.15.4
    command: ["/bin/sh"]
    args: ["-c", "wget http://www.google.com"]
```

not working `verify` stanza
```
- name: alpine-curl
  container:
    name: alpine-curl
    image: alpine/curl:3.15.4
    args: ["http://www.google.com"]
```

error output:
```
aprindle@aprindle ~/verify-test $ skaffold verify -a build.artifacts 
Tags used in verification:
 - integration-test-container -> gcr.io/aprindle-test-cluster/integration-test-container:latest@sha256:6d6da2378765cd9dda71cbd20f3cf5818c92d49ab98a2554de12d034613dfa6a
 - metrics-test-container -> gcr.io/aprindle-test-cluster/metrics-test-container:latest@sha256:3fbce881177ead1c2ae00d58974fd6959c648d7691593f6448892c04139355f7
[integration-test-container] Integration Test 1/4 Running ...
[integration-test-container] Integration Test 1/4 Passed!
[integration-test-container] Integration Test 2/4 Running...!
[integration-test-container] Integration Test 2/4 Passed!
[integration-test-container] Integration Test 3/4 Running...!
[integration-test-container] Integration Test 3/4 Passed!
[integration-test-container] Integration Test 4/4 Running...!
[integration-test-container] Integration Test 4/4 Passed!
[metrics-test-container] Metrics test in progress...
[metrics-test-container] Metrics test passed!
Error response from daemon: manifest for alpine/curl:3.15.4 not found: manifest unknown: manifest unknown
```
