### ISSUE TITLE
Skaffold 1.39.1 still fails with index out of range [0] with length 0

### ISSUE THREAD

**Issue by akharlamov** [GoogleContainerTools/skaffold#7771]
### Expected behavior
Build succeeds

### Actual behavior
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cache.needsRemoteTagging.Tag({{0x14000bb6780, 0x40}, {0x14000eee1c0, 0x68}, {0x14000a78d20, 0x47}}, {0x107c03d18, 0x14000b96f30}, 0x1400001a800, {0x14000a91170})
	/private/tmp/skaffold-20220624-80169-j89lh6/pkg/skaffold/build/cache/details.go:94 +0x218
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cache.(*cache).Build(0x1400001a800, {0x107c03c70, 0x14000dc4180}, {0x107bb2580, 0x14000392690}, 0x14000b97110, {0x1400001ebe0, 0x4, 0x4}, {0x14000a91170}, ...)
	/private/tmp/skaffold-20220624-80169-j89lh6/pkg/skaffold/build/cache/retrieve.go:85 +0xd04
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*Builder).Build(0x140007c4600, {0x107c03d18, 0x14000b970b0}, {0x107bb2580, 0x14000392690}, {0x1400001ebe0, 0x4, 0x4})
	/private/tmp/skaffold-20220624-80169-j89lh6/pkg/skaffold/runner/build.go:105 +0x8fc
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doBuild.func1({0x107c4a820, 0x140007c4600}, {0x14000b704e0, 0x1, 0x1})
	/private/tmp/skaffold-20220624-80169-j89lh6/cmd/skaffold/app/cmd/build.go:72 +0x118
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner({0x107c03c70, 0x14000030100}, {0x107bb2580, 0x14000a03310}, 0x140008e7530)
	/private/tmp/skaffold-20220624-80169-j89lh6/cmd/skaffold/app/cmd/runner.go:55 +0x184
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doBuild({0x107c03c70, 0x14000030100}, {0x107bb2580, 0x14000a03310})
	/private/tmp/skaffold-20220624-80169-j89lh6/cmd/skaffold/app/cmd/build.go:71 +0x11c
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0x140003d0840, {0x140009d5a10, 0x0, 0x3})
	/private/tmp/skaffold-20220624-80169-j89lh6/cmd/skaffold/app/cmd/commands.go:138 +0x9c
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.applyPostRunHooks.func1(0x140003d0840, {0x140009d5a10, 0x0, 0x3})
	/private/tmp/skaffold-20220624-80169-j89lh6/cmd/skaffold/app/cmd/commands.go:185 +0x5c
github.com/spf13/cobra.(*Command).execute(0x140003d0840, {0x140009d59e0, 0x3, 0x3})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x998
github.com/spf13/cobra.(*Command).ExecuteC(0x140003c4c80)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x7b8
github.com/spf13/cobra.(*Command).ExecuteContextC(0x140003c4c80, {0x107c03c70, 0x14000030100})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:911 +0x74
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run({0x107bb15e0, 0x14000010018}, {0x107bb15e0, 0x14000010020})
	/private/tmp/skaffold-20220624-80169-j89lh6/cmd/skaffold/app/skaffold.go:50 +0x3e4
main.main()
	/private/tmp/skaffold-20220624-80169-j89lh6/cmd/skaffold/skaffold.go:49 +0x29c

 🐍 fides-8TUr9fL4-py3.9  ⎈ |kubernetes-admin@gaia:dev2   fix/FID-XXX-docker-env-fides-dir
 ✘ aih1013@MacBook-Pro  ~/fides  skaffold version
v1.39.1
```
### Information

- Skaffold version: 1.39.1
- Operating system: MacOS
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: fides
build:
  artifacts:
    - image: registry.tailify.com/tailify/fides-base
      context: .
      docker:
        dockerfile: k8s/docker/Dockerfile.base
      sync:
        infer:
          - /opt/*
    - image: registry.tailify.com/tailify/fides-code
      requires:
        - image: registry.tailify.com/tailify/fides-base
          alias: BASE
      sync:
        infer:
          - /opt/*
      context: .
      docker:
        dockerfile: k8s/docker/Dockerfile.code
    - image: registry.tailify.com/tailify/fides-spark
      context: .
      docker:
        dockerfile: k8s/docker/Dockerfile.spark
      requires:
        - image: registry.tailify.com/tailify/fides-code
          alias: BASE
    - image: registry.tailify.com/tailify/fides-backend
      context: .
      docker:
        dockerfile: k8s/docker/Dockerfile.backend
  platforms:
    - linux/amd64
  local:
    push: true
    useBuildkit: true
    tryImportMissing: true
  tagPolicy:
    inputDigest: {}
deploy:
  kustomize:
    buildArgs:
      - "--load-restrictor=LoadRestrictionsNone"
    paths:
      - k8s/base
profiles:
  - name: production
    deploy:
      kustomize:
        buildArgs:
          - "--load-restrictor=LoadRestrictionsNone"
        paths:
          - k8s/prod
```

### Steps to reproduce the behavior

`skaffold build`
