### ISSUE TITLE
deploy.helm.releases -> manifests.helm.releases from config upgrade breaks profiles

### ISSUE THREAD

**Issue by anhpngt** [GoogleContainerTools/skaffold#7773]
`skaffold fix` (and config upgrade in general) from `v2beta29` to `v3alpha1` does not automatically update the profile paths. Thus, if the `skaffold.yaml` contains any profile patch that points to `deploy.helm.releases`, it would fail.

Example `skaffold.yaml`:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
deploy:
  helm:
    releases:
      - name: skaffold-helm
        chartPath: charts
profiles:
  - name: customize
    patches:
    - op: add
      path: /deploy/helm/releases/0/namespace
      value: customized
```

Running `skaffold fix` produces:

```yaml
apiVersion: skaffold/v3alpha1
kind: Config
manifests:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
deploy:
  helm: {}
profiles:
- name: customize
  patches:
  - op: add
    path: /deploy/helm/releases/0/namespace  # path no longer valid, causing failure
    value: customized
```

The manual fix is to update the path above to `/manifests/helm/releases/0/namespace`, or moving helm back to `deploy` from `manifests`.

Unfortunately, profiles are ignored when upgrading config (pipeline-only thing), so it seems we can't really update these paths while upgrading :sweat_smile: asking here to see if there's any better solution to it

This would cause running skaffold `v2.0.0-beta1` with config `v2beta29` to fail due to invalid paths. Probably helm.flags is also affected, looking at the code.

### Information

- Skaffold version: v2.0.0-beta1
- Operating system: 
- Installed via: [binary](https://github.com/GoogleContainerTools/skaffold/releases)

### Others

[new-render-and-deploy.md](https://github.com/GoogleContainerTools/skaffold/blob/main/docs/design_proposals/new-render-and-deploy.md#helm-deployer) is a good read on the reasoning behind this change
