### ISSUE TITLE
arm Image cannot be deployed to mixed nodes cluster

### ISSUE THREAD

**Issue by ericzzzzzzz** [GoogleContainerTools/skaffold#7779]
### Expected behavior
 - running command ``skaffold dev  --platform linux/arm64 --default-repo=gcr.io/k8s-skaffold``  should successfully deploy image to a mixed cluster without any special configuration.

### Actual behavior
 - pods cannot be scheduled
 - log 
```bash
Waiting for deployments to stabilize...
 - pods: Unschedulable: 0/1 nodes available:
    - pod/getting-started: Unschedulable: 0/1 nodes available:
```
### Information

- Skaffold version:  main
- Operating system:  MAC OS 12.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
  - image: skaffold-example
    context: .
    docker:
      dockerfile: Dockerfile
      noCache: true
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 1
manifests:
  rawYaml:
  - k8s-*
profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: {}
```

### Steps to reproduce the behavior
 - **connect kubectl to a mixed cluster** 
 - use integration/examples/cross-platform-builds example in skaffold project to run ``skaffold dev  --platform linux/arm64 --default-repo=gcr.io/k8s-skaffold`` 
 - Note that : adding the following toleration to k8s_pod.yaml manifest under spec can make deployment success  but we shouldn't any configuration .. 
  ```yaml
    tolerations:
    - key: kubernetes.io/arch
      operator: Equal
      value: arm64
      effect: NoSchedule
```
