### ISSUE TITLE
Skaffold patching helm values with profile breaks in 2.0.0-beta1

### ISSUE THREAD

**Issue by msonnleitner** [GoogleContainerTools/skaffold#7792]
### Expected behavior

patching helm values with a profile works as in skaffold 1.x. Helm Chart is a basic chart created with `helm create my-chart`

`skaffold run -p my-profile
`

### Actual behavior
`./skaffold-2 run -p my-profile`
fails with 

parsing skaffold config: failed to apply profiles to config "my-config" defined in file "[redacted]/skaffold-issue/skaffold.yaml": applying profile "my-profile": invalid path: /deploy/helm/releases/0/setValues/foo. There's an issue with one of the profiles defined in config "my-config" in file "[redacted]/skaffold-issue/skaffold.yaml"; refer to the documentation on how to author valid profiles: https://skaffold.dev/docs/environment/profiles/.

### Information

- Skaffold version: 
v2.0.0-beta1
- Operating system: 
tried with MacOS and Linux
- Installed via: `curl -Lo skaffold-2 https://storage.googleapis.com/skaffold/releases/v2.0.0-beta1/skaffold-darwin-amd64`
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: my-config
deploy:
  helm:
    releases:
      - name: my-release
        chartPath: helm/my-chart
        setValues:
          foo: "bar"
profiles:
  - name: my-profile
    patches:
      - op: replace
        path: /deploy/helm/releases/0/setValues/foo
        value: "bar-2"


```
