### ISSUE TITLE
missing --- separator between helm charts

### ISSUE THREAD

**Issue by lyra95** [GoogleContainerTools/skaffold#7793]
### Expected behavior

`skaffold render` output should contain `---` separator between helm charts i.e.

```yaml
# omitted mysql chart content
  volumeClaimTemplates:
  - metadata:
      annotations: null
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: mysql
        app.kubernetes.io/name: mysql
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
--- # <- I expect the separator here!
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-17.1.0
  name: redis
  namespace: default
```

### Actual behavior

`---` is missing.

```yaml
# omitted mysql chart content
  volumeClaimTemplates:
  - metadata:
      annotations: null
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: mysql
        app.kubernetes.io/name: mysql
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-17.1.0
  name: redis
  namespace: default
```

### Information

- Skaffold version: v2.0.0-beta1 
- Operating system: windows 10 64bits 
- Installed via: Chocolatey 
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
# minimum configuration for reproducing the bug
apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts: # need at least 1 artifacts to reproduce this bug
    - image: docker.io/library/alpine # any images
deploy:
  helm:
    releases:
      - name: mysql # any chart
        repo: "https://charts.bitnami.com/bitnami"
        remoteChart: mysql
      - name: redis # any chart
        repo: "https://charts.bitnami.com/bitnami"
        remoteChart: redis
```

### Steps to reproduce the behavior

1. create directory and copy above `skaffold.yaml` file.
2. run `skaffold render > output.yaml`
3. check `output.yaml` whether it contains `---` between `mysql` and `redis` charts
