### ISSUE TITLE
`skaffold.yaml` schema should accept annotations 

### ISSUE THREAD

**Issue by zevisert** [GoogleContainerTools/skaffold#7797]
### Expected behavior

I should be free to add annotations to the root metadata of a `skaffold.yaml` file. My intent is to annotate my skaffold file with `config.kubernetes.io/local-config: "true`. 

### Actual behavior

According the the KRM schema: `"Property metadata.annotations is not allowed"`

### Information

- Skaffold version: v1.39.1
- Operating system: (`uname --all`): `Linux 🐀 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: hula
  annotations:
    config.kubernetes.io/local-config: "true"
build: {}
deploy: {}
```

### Steps to reproduce the behavior

1. Add metadata.annotations to any schema-validated `skaffold.yaml` file.
2. ` skaffold diagnose`
  > error parsing skaffold configuration file: unable to parse config: yaml: unmarshal errors:
  >    line 31: field annotations not found in type latest.Metadata
