### ISSUE TITLE
Delve is too old for Go version 1.19.0

### ISSUE THREAD

**Issue by sergeygalaxy** [GoogleContainerTools/skaffold#7816]
### Expected behavior
`skaffold debug` - doesn't show warnings

### Actual behavior
`skaffold debug` - shows warning
 WARNING: undefined behavior - version of Delve is too old for Go version 1.19.0 (maximum supported version 1.18)

### Information

- Skaffold version: v1.39.2
- Operating system: arm64 MacOS
- Installed via: 
tried both: Homebrew  and Cloud Code 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: x-service
build:
  local:
    push: false
    useDockerCLI: true
  artifacts:
  - image: io.x/x-service
    platforms:
      - linux/arm64
    custom:
      buildCommand: make docker IMAGE="$IMAGE"
      dependencies:
        dockerfile:
          path: ./Dockerfile
deploy:
  kubectl:
    manifests:
    - build/local/deployment.yaml
```
