### ISSUE TITLE
Verify command does not pull images from remote image registries

### ISSUE THREAD

**Issue by henrybell** [GoogleContainerTools/skaffold#7833]
### Expected behavior
When running `skaffold verify`, an image specified in `artifacts.json` and referenced in the `verify` stanza should be pulled from the remote image registry and executed in the local docker environment.

### Actual behavior
An image built remotely (e.g. with Cloud Build) is not pulled from the remote repository, and so cannot be executed locally.

### Information

- Skaffold version: v2.0.0-beta2
- Operating system: Debian-based Linux (Google Cloud Shell) / Rodete / MacOS 12.5.1 
- Installed via: [Skaffold GitHub releases page](https://github.com/GoogleContainerTools/skaffold/releases)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: hello-app
build:
  artifacts:
    - image: hello-verify
      context: hello-verify
  googleCloudBuild:
    projectId: ${PROJECT_ID}
deploy:
  cloudrun:
    region: us-east1
    projectid: ${PROJECT_ID}
profiles:
  - name: test
    verify:
    - name: verify-deployment
      container:
        name: hello-verify
        image: hello-verify
```

### Steps to reproduce the behavior

1. Build an image to be be used for `skaffold verify` with Cloud Build (or build locally, push to remote registry, and remove local)
2. Run `skaffold verify -a artifacts.json --profile test`
3. Observe `Error: No such image` error message, with image not available locally per `docker images`
