### ISSUE TITLE
Skaffold shell output loses color when using concurrent

### ISSUE THREAD

**Issue by BoKKeR** [GoogleContainerTools/skaffold#7837]
### Expected behavior
Colors in terminal
### Actual behavior
Colors are in the terminal but dissapear after concurrency build starts

![image](https://user-images.githubusercontent.com/2664857/188083721-bb3396f2-0eac-48af-97dc-95c5070d9463.png)

### Information

- zsh 5.8 (x86_64-apple-darwin21.0)
- Skaffold version: v1.39.1
- Operating system: 12.2.1 Monterey
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: namespace
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: local/infra-seeding
    context: ../infra
    docker:
      dockerfile: Dockerfile
  - image: local/k8s-wait-for
    context: ../infra/k8s-wait-for
    docker:
      dockerfile: Dockerfile
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    concurrency: 5
```

### Steps to reproduce the behavior
1. add `concurrency: 5`
2. wait for rebuild
3. lose all colors in terminal

![image](https://user-images.githubusercontent.com/2664857/188083695-9e28c545-156d-4afe-a20d-f8b77526f9cf.png)
