### ISSUE TITLE
kpt 1.0.0-beta.XX deployer support

### ISSUE THREAD

**Issue by jmcudd** [GoogleContainerTools/skaffold#7854]
### Expected behavior

skaffold kpt deployer should work with kpt >= 1.0.0-beta.XX

### Actual behavior
![2022-09-09_13-01 57](https://user-images.githubusercontent.com/1785592/189404208-0ff97488-ad33-413e-8ab7-8752e465e4c8.png)

### Information

- Skaffold version: v1.39.1
- Operating system: arch linux
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: my-service
build:
deploy:
  kpt:
    dir: k8s
```

### Steps to reproduce the behavior

see the actual behavior screenshot
