### ISSUE TITLE
customTemplate tagger doesn't have any alias to inputDigest tagger

### ISSUE THREAD

**Issue by mikekamornikov** [GoogleContainerTools/skaffold#7865]
### Expected behavior

The following `tagPolicy` is supported
```yaml
tagPolicy:
  customTemplate:
    template: test-{{.INPUT_DIGEST}}
```

### Actual behavior

`inputDigest` is supported only if it's explicitly added to components. While other taggers have aliases (`SHA`, `GIT`, `DATE`):

```yaml
tagPolicy:
  customTemplate:
    template: test-{{.SHA}}-{{.GIT}}-{{.DATE}}-{{.INPUT_DIGEST}}
    components:
    - name: INPUT_DIGEST
      inputDigest: {}
```

### Information

- Skaffold version: 1.39.2
- Operating system: macOS 12.4
- Installed via: downloaded from Github release assets
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: quay.io/org/project
    context: ../../..
    bazel:
      target: //projects/go/cmd/project:docker.tar
      args:
      - --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64
  tagPolicy:
    customTemplate:
      template: cxp-mothership-operator-{{.SHA}}-{{.GIT}}-{{.DATE}}-{{.INPUT_DIGEST}}
  local:
    useBuildkit: false
```

### Steps to reproduce the behavior

1. Modify `tagPolicy` in `skaffold.yaml`
2.  Run `skaffold build`
