### ISSUE TITLE
Suggestion on volume mount and env variables for custom image test command.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [GoogleContainerTools/skaffold#7881]
### Expected behavior

```yml
...
 artifacts:
  - image: service
  - image: cukes
    docker:
      dockerfile: Dockerfile.test

test:
  - image: cukes
    custom:
      - command: "60"
        timeoutSeconds: 60
        dependencies:
          paths:
          -  features

```

The docker compose command

```
version: '2.1'
services:  
  service-tests:
    environment:
      - SERVICE_ENDPOINT=http://service:8089
      - SPIN=${SPIN:-false}
    volumes:
      - "./test-results:/cucumber/test-output"
    build:
      context: .
      dockerfile: Dockerfile.test
    command: "60"
    depends_on:
      - service
```

### Information

- Skaffold version: :   v1.39.2
- Operating system: 
- Installed via: Homebrew
- Contents of skaffold.yaml - above 

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold dev`
3. ...
