### ISSUE TITLE
Skaffold update files but the app still use the start Docker image

### ISSUE THREAD

**Issue by karimennassiri** [GoogleContainerTools/skaffold#7894]
### Expected behavior
Skaffold update files but the app still use the start Docker image

### Actual behavior
I'm having a local cluster using [K3d](https://k3s.io/), inside it, there is an API developed in Lumen (Laravel).

In my case the files did change inside the container but the app still act as the first pod creation. So I can change file any time the app still have the same state always.
### Information

- Skaffold version: v1.39.2
- Operating system: Windows 11
- Installed via: Chocolatey 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: api
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*'
            dest: .
deploy:
  kustomize:
    paths:
      - k8s\dev
profiles:
  - name: base
    deploy:
      kustomize:
        paths:
          - k8s\base
```

### Steps to reproduce the behavior

1. `skaffold dev`
