### ISSUE TITLE
skaffold render ignores namespace command line argument

### ISSUE THREAD

**Issue by cmeury** [GoogleContainerTools/skaffold#7897]
### Expected behavior

When specifying a namespace on the command line using the `--namespace` argument, `skaffold render` produces a helm command that specifies the namespace:

    helm [..] template test chart --namespace foo

### Actual behavior

The generated helm command uses the namespace from `skaffold.yaml`:

    helm [..] template test chart --namespace main

### Information

- Skaffold version: v2.0.0-beta3
- Operating system: Darwin Kernel Version 21.6.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: test
deploy:
  helm:
    releases:
      - name: test
        namespace: main
        chartPath: chart
```

### Steps to reproduce the behavior

Run:

```shell
skaffold version
v2.0.0-beta3

skaffold render --namespace foo -v DEBUG 2>&1 | grep -e "--namespace"
[..] msg="Running command: [helm [..] template test chart --namespace main]" subtask=0 task=Render

skaffold render -v DEBUG 2>&1 | grep -e "--namespace"
[..] msg="Running command: [helm [..] template test chart --namespace main]" subtask=0 task=Render
```

## Regression

This worked in 1.x, with `v1.39.2` and this configuration `skaffold-old.yaml`:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: test
deploy:
  helm:
    releases:
      - name: test
        namespace: main
        chartPath: chart
```

We see:

```shell
/opt/homebrew/bin/skaffold version
v1.39.2

/opt/homebrew/bin/skaffold render -f skaffold-old.yaml --namespace foo -v DEBUG 2>&1 | grep -e "--namespace"
[..] msg="Running command: [helm [..] template test chart --namespace foo]" subtask=-1 task=DevLoop

/opt/homebrew/bin/skaffold render -f skaffold-old.yaml  -v DEBUG 2>&1 | grep grep -e "--namespace"
[..] msg="Running command: [helm [..] template test chart --namespace main]" subtask=-1 task=DevLoop

```
