### ISSUE TITLE
Skaffold v2.0.0-beta3 with manifests.transform is trying to deploy whole .kpt-pipeline with cloud run including Kptfile (so fails)

### ISSUE THREAD

**Issue by jancespivo** [GoogleContainerTools/skaffold#7899]
### Expected behavior

Skaffold deploys only hydrated manifests and not whole .kpt-pipeline directory including Kptfile itself

### Actual behavior

Skaffold deploys hydrated manifests + Kptfile which fails

### Information

- Skaffold version: 

v2.0.0-beta3 

- Operating system: 

Linux 5.19.7-1-MANJARO

- Installed via: 

Manually

- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: test

build:
  artifacts:
    - image: us-west1-docker.pkg.dev/****/docker/test
manifests:
  rawYaml:
    - cloudrun.yaml
  transform:
    - name: create-setters
      configMap:
        - "SERVICE-NAME:$(SERVICE-NAME)"
        - "PROJECT:$(PROJECT)"
        - "VPC-PROJECT:$(VPC-PROJECT)"
        - "REGION:$(REGION)"
    - name: apply-setters
      configMap:
        - "SERVICE-NAME:test"
        - "REGION:us-west1"
        - "PROJECT:***"
        - "VPC-PROJECT:***"
deploy:
  cloudrun:
    projectid: ***
    region: us-west1
```

### Steps to reproduce the behavior

`skaffold render` output shows hydrated manifest and also Kptfile itself, so probably that is the start of the problem.

`skaffold run` output:
```
...
Starting deploy...
Deploying Cloud Run service:
	 .kpt-pipeline
googleapi: Error 400: spec.template.spec: Revision template was empty
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Revision template was empty",
        "field": "spec.template.spec"
      }
    ]
  }
]
```
