### ISSUE TITLE
Jib build failing in multi-module gradle project

### ISSUE THREAD

**Issue by hpuac** [GoogleContainerTools/skaffold#7902]
Skaffold tries to run the following command during the Jib build:
`gradle _skaffoldFailIfJibOutOfDate -Djib.requiredVersion=1.4.0 :_jibSkaffoldFilesV2`
But the `_jibSkaffoldFilesV2` task gets executed on the root project.
In a multi-module gradle project this task does not exist on the root project.

### Expected behavior

I would expect Skaffold to support the Jib build in a multi-module gradle project.

### Actual behavior

Skaffold is failing during the Jib build in a multi-module gradle project.

### Information

- Skaffold version: v1.39.2
- Operating system: macOS Monterey
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: hello-jib
build:
  artifacts:
  - image: hello-jib
    jib:
      type: gradle
    context: .
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - k8s/deploy.yaml
```

### Steps to reproduce the behavior

1. Clone the Jib repository and open the [multi-module example](https://github.com/GoogleContainerTools/jib/tree/master/examples/multi-module)
2. Change directory into one of the sub-modules like the [hello-service](https://github.com/GoogleContainerTools/jib/tree/master/examples/multi-module/hello-service) 
3. Run `skaffold build -v debug` or run `gradle _skaffoldFailIfJibOutOfDate -Djib.requiredVersion=1.4.0 :_jibSkaffoldFilesV2` directly
4. The command will fail with the error `Task '_jibSkaffoldFilesV2' not found in root project 'jib-multimodule'.`

**Comment by araminian** [comment]
This problem can be fixed by change the context to tell `Skaffold` to use `gradle` file in root level and specifying the name of the project you want  to build(name of the project can be found by running `gradle projects`).

```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: hello-jib
build:
  artifacts:
  - image: hello-jib
    jib:
      type: gradle
      project: [PROJECT-NAME]
    context: ..
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - k8s/deploy.yaml
```
