### ISSUE TITLE
Skaffold is not using the image repository project for Cloud Build

### ISSUE THREAD

**Issue by kschaab** [GoogleContainerTools/skaffold#7923]
Set gcloud default project to a specific project, deploy to cluster in a different gcloud project with the registry set to that project.  Using cloudbuild to build attempt build, it will utilize cloud build in the gcloud default project rather than the expected project.

### Expected behavior
Cloud build uses the container registry project for building

### Actual behavior
Cloud build uses the gcloud default project

### Information

- Skaffold version: v1.39.2
- Operating system: MacOS 12.6 (21G115)
- Installed via: skaffold.dev
- Contents of skaffold.yaml:
```yaml
# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta28
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: go-hello-world
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
profiles:
- name: cloudbuild
  build:
    platforms: ["linux/amd64"]
    googleCloudBuild: {}
```

### Steps to reproduce the behavior

1. Set gcloud default project to a specific project
2. Deploy to cluster in a different gcloud project with the registry set to that project.  
3. Using cloud build to build attempt build, it will utilize cloud build in the gcloud default project rather than the expected project.
