### ISSUE TITLE
Deploy with pre-built images does not work

### ISSUE THREAD

**Issue by ventsyv** [GoogleContainerTools/skaffold#7924]
Per the documentation for skaffold deploy:
`  -i, --images=: A list of pre-built images to deploy, either tagged images or NAME=TAG pairs`

### Expected behavior
When I run:
```skaffold deploy -i my_img:latest -i my_other_img:latest```
I expect the images I provided to override the images in deploy.helm.releases.artifactOverrides
Instead of building the images, I expect skaffold to execute the helm chart and deploy the pre-built artifacts.

### Actual behavior
```
skaffold deploy --default-repo -i my_img:latest -i my_other_img:latest
unknown command "my_img:latest" for "skaffold deploy"
```

```
skaffold deploy --default-repo --images=my_img:latest,my_other_img:latest
You either need to:
run [skaffold deploy] with [--images TAG] for each pre-built artifact
or [skaffold run] instead, to let Skaffold build, tag and deploy artifacts.
no tag provided for image [my_img]
```

```
skaffold deploy --default-repo --images=my_img:latest my_other_img:latest
unknown command "my_other_img:latest" for "skaffold deploy"
```

```

skaffold deploy --default-repo --images=my_img:latest --images=my_other_img:latest
You either need to:
run [skaffold deploy] with [--images TAG] for each pre-built artifact
or [skaffold run] instead, to let Skaffold build, tag and deploy artifacts.
no tag provided for image [my_img]
```

### Information

- Skaffold version:  v1.39.2
- Operating system:  Ubuntu 22.04.1 LTS
-
- Installed via: https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
- Contents of skaffold.yaml:
```
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: myrelease
deploy:
  kubectl:
    manifests:
      - k8s/pgadmin.yaml
  kubeContext: minikube
  helm:
    releases:
      - name: myImg1
        chartPath: charts/my_chart
        artifactOverrides:
          #Key must match the setting in values.yaml
          #The value must match the image in the arfifacts section of this file
          mi_img.container.image: my_img
      - name: myImg2
        chartPath: charts/my_chart
        artifactOverrides:
          my_img2.container.image: my_other_img
```

### Steps to reproduce the behavior

`skaffold deploy --image ?`
