### ISSUE TITLE
Deploy might not work properly warning while building an image

### ISSUE THREAD

**Issue by mikekamornikov** [GoogleContainerTools/skaffold#7972]
### Expected behavior

There should not be any "deploy" related warnings if Kubernetes context is not relevant.
Alternatively I expect an option to suppress such warnings.

### Actual behavior

I get the following on `skaffold build`:
```
time="2022-10-22T14:40:11Z" level=warning msg="unable to get the kubectl context's namespace - deploy might not work properly!" subtask=-1 task=DevLoop
```
https://github.com/GoogleContainerTools/skaffold/pull/7965 assumes I do have a configured namespace in the current context. But I don't even have `kubectl` installed in that environment.

### Information

- Skaffold version: 2.0.0
- Operating system: MacOS 12.4
- Installed via: `storage.googleapis.com/skaffold/releases/v2.0.0`
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
  - image: quay.io/org/project
    context: ./docker/project
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    customTemplate:
      template: prefix-{{.INPUT_DIGEST}}
  local:
    useBuildkit: false
```

### Steps to reproduce the behavior

1. Prepare `skaffold.yaml`
2. Remove `kubectl` from the PATH
3. Execute `skaffold build`
