### ISSUE TITLE
Rendering using helm and digest-source local produces invalid image tag

### ISSUE THREAD

**Issue by cmeury** [GoogleContainerTools/skaffold#7978]
### Expected behavior

The image tag in the final manifest is valid (`foo:552d840-dirty`). Even better would be if `skaffold build --dry-run` would actually calculate the checksum so we can use when rendering.

### Actual behavior

The image tag contains an `@` at the end, making it invalid (`foo:552d840-dirty@`).

### Information

- Skaffold version: v2.0.0
- Operating system: macOS 12.6
- Installed via: homebrew

### Steps to reproduce the behavior

Using the skaffold files from below:

```shell
helm create chart
git init
git commit --allow-empty -m "-"
skaffold build -f skaffold.yaml --dry-run --file-output=output.json
skaffold render -f skaffold.yaml --build-artifacts=output.json --digest-source='local' | grep 'image: foo'
      - image: foo:552d840-dirty@
```

This is a regression, when compared to rendering with skaffold v1.39.2:

```shell
./skaffold-v1.39.2 render -f skaffold-v1.39.2.yaml --build-artifacts=output.json --digest-source='local' | grep 'image: "foo'
          image: "foo:552d840-dirty"
```

Using new `skaffold.yaml`:

```yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: test
build:
  artifacts:
    - image: foo
      context: .
  local: {}
  tagPolicy:
    gitCommit: {}
deploy:
  helm:
    releases:
      - name: alpine
        namespace: main
        chartPath: chart
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO}}'
          image.tag: '{{.IMAGE_TAG}}@{{.IMAGE_DIGEST}}'
```

Older schema, `skaffold-v1.39.2.yaml`:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: test
build:
  artifacts:
    - image: foo
      context: .
  local: {}
  tagPolicy:
    gitCommit: {}
deploy:
  helm:
    releases:
      - name: alpine
        namespace: main
        chartPath: chart
        artifactOverrides:
          image: foo
        imageStrategy:
          helm: { }
```
