### ISSUE TITLE
The skaffold connection fails on macOS m1.

### ISSUE THREAD

**Issue by naman9199** [GoogleContainerTools/skaffold#7981]
### Expected behavior
command ```skaffold run``` or ```skaffold dev``` should've worked as the docker client is running on my device

### Actual behavior
Fails with error:
Build Failed. Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Check if docker is running.

### Information

- Skaffold version: v2.0.0
- Operating system: macOS 13.0
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    buildpacks:
      env:
      - GOPROXY={{.GOPROXY}}
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
```

### Steps to reproduce the behavior

1. ```git clone git@github.com:GoogleContainerTools/skaffold.git``` 
2. ```cd examples/buildpacks```
3. `skaffold dev` or `skaffold run` (both shows same error)

<img width="727" alt="temp1" src="https://user-images.githubusercontent.com/82203888/197879472-210169a3-c9fd-494b-bb18-a9351d48f4fa.png">

I am pretty sure that the docker client is running and working correctly!
