### ISSUE TITLE
Helm hooks are not using the correct image tag

### ISSUE THREAD

**Issue by michelesr** [GoogleContainerTools/skaffold#7989]
### Expected behavior

When specifying an image override for a helm deployment, hooks should use the correct image tag just the rest of the resources.

### Actual behavior

When specifying an image override for a helm deployment, the tag for hooks isn't changed, just the repository.

### Information

- Skaffold version: v2.0.0-5-gbef0268b8
- Operating system: Arch Linux (but is not relevant)
- Installed via: built from source
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: localhost/nginx
deploy:
  kubeContext: minikube
  helm:
    releases:
      - name: test
        namespace: test
        skipBuildDependencies: true
        createNamespace: true
        chartPath: ./chart
        artifactOverrides:
          image.repository: localhost/nginx
```

### Steps to reproduce the behavior

1.  clone https://github.com/michelesr/skaffold-test-repo
2. `skaffold dev`
3. observe the pods with `kubectl get pods -n test`

The foo pod (which represents the hook) fails with `ImagePullBackOff`.

Observe image tag set for the deployment

```
$ kubectl get deployment -n test test-chart -o=jsonpath={.spec.template.spec.containers[0].image}
localhost/nginx:0d5bf3701e4847eaa6faff0ff8c8e7c26b34dc32fc8bd50b7aceb04b174d81e6
```
Observe image tag for the hook

```
$ kubectl get job -n test foo -o=jsonpath={.spec.template.spec.containers[0].image}
localhost/nginx:1.16.0
```

### Additional information

In skaffold v1.39.2 it was possible to set the image strategy, giving more flexibility on how image tags propagated to helm. Right now, what happens is that the value is set to the repository only (without tag), and then `--post-renderer` replaces the image references in the template directly.

v1 (with default image strategy):

```
$ helm get values test -n test
USER-SUPPLIED VALUES:
image:
  repository: localhost/nginx:0d5bf3701e4847eaa6faff0ff8c8e7c26b34dc32fc8bd50b7aceb04b174d81e6
```

v2:

```
$ helm get values test -n test
USER-SUPPLIED VALUES:
image:
  repository: localhost/nginx
```
While v1 is still wrong (as repository shouldn't contain the tag), it is possible to modify the chart to just use a single value for the whole image reference, thus making sure that every resource is using the right ref (e.g. just using a `image` string value instead of `image.repository` and `image.tag`)

Debug log: [log.txt](https://github.com/GoogleContainerTools/skaffold/files/9869838/log.txt)

**Comment by michelesr** [comment]
https://github.com/helm/helm/issues/7891 might be the cause.

**Comment by aaron-prindle** [comment]
Thanks for flagging this @michelesr, our current integration tests don't have any hooks so this seems to have been missed when we changed our `helm` integrations to use the `--post-renderer` as you noted.  We are currently thinking through fixes on our end but have not landed on a solution currently.  I will keep you updated in the thread here.  I have created an issue to add integration tests for `helm` hook support in response to this

**Comment by aaron-prindle** [comment]
I am planning on changing the recommended way that skaffold handles inserting values into rendered yamls.  Currently we use `setValues` to insert the <artifact-name>(eg: skaffold image) into first pass of `helm` rendering and then use the skaffold post-renderer to change <artifact-name> to the fully qualified name (eg: skaffold-image -> gcr.io/skaffold-image:tag@sha256:<sha256-digest>).  This replacement though (identical to what is done for the kubectl deployers and others) is not UX friendly with the expectations from `helm`.  

I believe the appropriate fix is to instead use `setValueTemplates` and improve our templating to support more use cases as these get properly populated in the "first pass" of helm prior to the `post-renderer`.


When using your example with my PR at #8147 I see the hook values being correct:

skaffold.yaml @ that PR:
```
6.0aprindle@aprindle-ssd ~/skaffold-test-repo  [master]$ skaffold fix
apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: localhost/nginx
manifests:
  helm:
    releases:
    - name: test
      chartPath: ./chart
      namespace: test
      setValueTemplates:
        image.repository: '{{.IMAGE_FULLY_QUALIFIED_localhost_nginx}}' # <-- env var added w/ the PR mentioned
      createNamespace: true
      skipBuildDependencies: true
deploy:
  helm: {}
```

```
aprindle@aprindle-ssd ~/skaffold-test-repo  [master]$ kubectl get deployment -n test test-chart -o=jsonpath={.spec.template.spec.containers[0].image}
gcr.io/aprindle-test-cluster/localhost/nginx:2ff8c19-dirty@sha256:5cfa549eefd73aea2f5bd2768d2b3e3a0955092be15eb6620b6c32ea17465f16:1.1aprindle@aprindle-ssd ~/skaffold-test-repo  [master]$ kubectl get job -n test foo -o=jsonpath={.spec.template.spec.containers[0].image}ge}
gcr.io/aprindle-test-cluster/localhost/nginx:2ff8c19-dirty@sha256:5cfa549eefd73aea2f5bd2768d2b3e3a0955092be15eb6620b6c32ea17465f16:1.16.0aprindle@aprindle-ssd ~/skaffold-test-repo  [master]$ 
```

**Comment by michelesr** [comment]
@aaron-prindle not sure I'm doing thing alright, but I'm running skaffold from your PR head 81db505394496c43f48b3a4bb3d889c05beaf22c (skaffold version returns `v2.0.2-19-g81db50539`). `skaffold fix` is returning the following:

```
apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: localhost/nginx
manifests:
  helm:
    releases:
    - name: test
      chartPath: ./chart
      namespace: test
      setValueTemplates:
        image.repository: '{{.IMAGE_FULLY_QUALIFIED_localhost/nginx}}' # this seems wrong
      createNamespace: true
      skipBuildDependencies: true
deploy:
  helm: {}
  kubeContext: minikube
```

After changing `{{.IMAGE_FULLY_QUALIFIED_localhost/nginx}}` with `{{.IMAGE_FULLY_QUALIFIED_localhost_nginx}}` I tried `skaffold dev` but the values are not correct:

```
$ helm get values -n test test
USER-SUPPLIED VALUES:
image:
  repository: <no value>
```

**Comment by aaron-prindle** [comment]
@michelesr sorry the PR now has the most up-to-date code.  I fixed this to replace and handle (`/` & `-`) chars which helm templates don't support.  I am planning to add some additional validation/messaging/support to make this easier.  I used your repro repository to verify the fix worked so this should work when you test it.  If you can retry and confirm with the PR @ HEAD now that would be great

**Comment by michelesr** [comment]
@aaron-prindle with your latest code I could make it work with this:

```yaml
apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: localhost/nginx
manifests:
  helm:
    releases:
    - name: test
      chartPath: ./chart
      namespace: test
      setValueTemplates:
        image.repository: '{{.IMAGE_REPO_localhost_nginx}}'
        image.tag: '{{.IMAGE_TAG_localhost_nginx}}'
      createNamespace: true
      skipBuildDependencies: true
deploy:
  helm: {}
  kubeContext: minikube
```
That's because the chart template is concatenating repository and tag -> https://github.com/michelesr/skaffold-test-repo/blob/2ff8c191ab6d2d1b43b0e5fdcb04bbf5976b3a60/chart/templates/deployment.yaml#L34 (same for the hooks)

`IMAGE_FULLY_QUALIFIED` seems to work okay with another project I have where a single value containing the full image reference is required, rather than repository and tag.

So far it's looking good, I'd make sure to document exactly when to use `IMAGE_TAG`, `IMAGE_REPO` and `IMAGE_FULLY_QUALIFIED` to avoid confusion for the end users.
