### ISSUE TITLE
remoteManifests no longer works in v2.0.0

### ISSUE THREAD

**Issue by rishka** [GoogleContainerTools/skaffold#7990]
### Expected behavior
Remote manifests loads manifest from specified kubernetes resource

### Actual behavior
Manifests are looked for locally

### Information
- Skaffold version: working: v1.37.2, not working: v2.0.0
- Operating system: Ubuntu 20.04
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
  - image: test
deploy:
  kubectl:
    remoteManifests:
      - deploy/test
```

### Steps to reproduce the behavior

1. clone https://github.com/rishka/skaffold-manifests-bug
2. run `kubectl apply -f deploy.yaml`
3. run `skaffold run`
4. results in `nothing to deploy` in v2, correctly applies in v1

**Comment by aaron-prindle** [comment]
This is actually an error with our automatic updating.  The field deploy.kubectl.remoteManifests no longer exists for Skaffold `v2.0.0` (apiVersion: skaffold/v3).  This will work in skaffold v2.0.0 if you manually configure this to be:
```
apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
  - image: test
manifests:
  rawYaml:
  - deploy/test
  - https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
```

In skaffold `v2.0.0` whether a manifest is remote is inferred by string:
https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/render/generate/generate.go#L73-L116

The issue currently is that our automatic update code for the `skaffold.yaml` does not actually move `deploy.kubectl.remoteManifests` to manifests.rawYaml, instead leaving the stanza there and breaking the `skaffold.yaml`.  I will submit a fix for skaffold to properly update such `skaffold.yaml` files but in the meantime you can manually edit your  `skaffold.yaml` file to move the `deploy.kubectl.remoteManifests` values to be in the list at `manifests.rawYaml`
