### ISSUE TITLE
Images are not getting loaded on Kind Cluster

### ISSUE THREAD

**Issue by zeyaddeeb** [GoogleContainerTools/skaffold#7992]
### Expected behavior

the deployment is live and port is forwarded

### Actual behavior

deployment always fails

When I inspect the images on the kind cluster it never gets loaded: 
```bash
docker exec -it $(kind get clusters | head -1)-control-plane crictl images
```

### Information

- Skaffold version: v2.0.0 
- Operating system:  macOS 13.0 (22A380)  - Darwin 22.1.0 
- Installed via: Homebrew 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta20
kind: Config

build:
  artifacts:
    - image: apps-web
      docker:
        dockerfile: apps/web/Dockerfile
      context: .
  local:
    push: false

profiles:
  - name: dev
    build:
      local:
        useBuildkit: true
      artifacts:
        - image: apps-web
          docker:
            dockerfile: apps/web/Dockerfile
          context: .

    deploy:
      kubeContext: kind-local-dev
      helm:
        releases:
          - name: apps-web
            chartPath: deployments/helm/web
            upgradeOnChange: true

    portForward:
      - resourceType: deployment
        resourceName: apps-web
        port: 3000
        localPort: 3000
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold dev --profile dev `
