### ISSUE TITLE
`defaultNamespace` value is not put in the `SKAFFOLD_NAMESPACES` environment variable for deploy hook usage

### ISSUE THREAD

**Issue by dallasvaughan** [GoogleContainerTools/skaffold#7995]
### Expected behavior
If the `skaffold.yaml` `deploy.kubectl.defaultNamespace` element is set, this value is put into the `SKAFFOLD_NAMESPACES` list of namespaces and resolves to this value when the `$SKAFFOLD_NAMESPACES` is referenced in a host pre- or post-deploy hook command and a namespace is not provided in the `skaffold` command.

### Actual behavior
If the `skaffold.yaml` `deploy.kubectl.defaultNamespace` element is set, this value is not put into the `SKAFFOLD_NAMESPACES` list of namespaces and resolves to an empty string when referenced in a host pre- or post-deploy hook command.

This variable is only set when a namespace is passed in via the CLI `--namespace` argument, though I believe the intent of `defaultNamespace` is to provide the deploy namespace when the CLI option argument is not explicitly provided. It seems to reason that in both cases this variable should represent whatever namespace(s) skaffold is configured to deploy to.

### Information

- Skaffold version: v2.0.0
- Operating system: macOS 12.5.1
- Installed via: skaffold.dev
- Contents of skaffold.yaml:
```yaml
# any valid config
deploy:
  kubectl:
    defaultNamespace: testNS
    hooks:
      before:
        - host:
            command: [ "sh", "-c", "echo $SKAFFOLD_NAMESPACES" ]
      after:
        - host:
           command: [ "sh", "-c", "echo $SKAFFOLD_NAMESPACES" ]
```
### Steps to reproduce the behavior 

1. `skaffold dev` on valid project with `defaultNamespace` set and with `$SKAFFOLD_NAMESPACES` referenced in host hook command(s)
2. Empty strings are printed in the output before and after k8s resources are deployed to `testNS` namespace.
