### ISSUE TITLE
.dockerignore behavior on "!" operator isn't correct for some cases with buildargs

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/skaffold#800]
### Expected behavior
files marked with `!` are not ignored

### Actual behavior
files marked with `!` in a subdirectory are ignored

### Information

- Skaffold version: v0.9.0
- Operating system: linux
- Contents of skaffold.yaml: 

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/<some-project>/birds
    docker:
      buildArgs:
        GOOSE_FILE: "goose/goose.txt"
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. Create a new directory with `Dockerfile`, `.dockerignore`, `goose/goose.txt`, `skaffold.yaml`

`Dockerfile`
```
FROM alpine
ARG GOOSE_FILE
COPY ${GOOSE_FILE} duck.txt
ENTRYPOINT ["cat", "duck.txt"]
```

`.dockerignore`
```
**
!goose/goose.txt
```

`goose/goose.txt`
```
hi
```

2. run `docker build . --build-arg GOOSE_FILE=goose/goose.txt -t birds` <-- this works

3. run `skaffold build` <-- this fails
FATA[0000] build step: building [gcr.io/<some-project>/birds]: running build: COPY failed: stat .../docker/tmp/docker-builder277924338/goose/goose.txt: no such file or directory
