### ISSUE TITLE
Helm deployer examples still reference artifactOverrides

### ISSUE THREAD

**Issue by cmeury** [GoogleContainerTools/skaffold#8002]
See: https://skaffold.dev/docs/pipeline-stages/deployers/helm/#image-configuration (file: `docs-v2/content/en/docs/pipeline-stages/deployers/helm.md`)

Coincidentally, it's also mentioned here and in some other places (maybe a global grep might be useful):
* `examples/helm-deployment/README.md`

Also, the alert at the top of the page mentions `artifactsOverride` when in fact the key was called `artifactOverrides`.

**Comment by alewis001** [comment]
With help from @cmeury I was able to get my migration from v1 to v2 to work. The migration required the changed below. Therefore It may be beneficial to others to include this information in the documentation when addressing this issue.

## Changes
The `image:` mapping within the Helm templates is no longer `{{ .Values.image }}` but `"{{ .Values.image.repository }}:{{ .Values.image.tag }}"` and then include the following within the `releases` sequence of the `manifest` section in `skaffold.yaml`:
```
setValueTemplates:
        image.repository: '{{.IMAGE_REPO}}'
        image.tag: '{{.IMAGE_TAG}}@{{.IMAGE_DIGEST}}'
```

**Comment by cmeury** [comment]
As mentioned in the MR, `artifactOverrides` is still shown as examples on the page. Don't think this is resolved completely.

**Comment by chris13524** [comment]
Looks like `imageStrategy` was also removed? I was using the `fqn` mode which was the default. To workaround, I can use use `setValueTemplates` w/ a value of `{{.IMAGE_REPO}}:{{.IMAGE_TAG}}@{{.IMAGE_DIGEST}}`. But this becomes increasingly challenging since I have a dozen or more images, so I need to use `N`

It's unclear to me what Skaffold's new default imageStrategy is when not specifying  `setValueTemplates`. Seems like it can infer the artifact based on the values file structure?

**Comment by toniopelo** [comment]
I don't understand how it's supposed to work either @chris13524, did you find out the logic behind the implementation (without `imageStrategy` ?).

cc @aaron-prindle, as mentionned above `imageStrategy` is not in the schema anymore and you PR doesn't correct that part. adding a little more guidance on how to have the helm classic values structure (as following) would be a lot of help :)
```yaml
# example values file where skaffold should replace values for every image it builds

service1:
  image:
    repository:
    tag:

service2:
  image:
    repository:
    tag:
```

I'm using `setValueTemplates` but it's cumbersome when you have multiple images, and it also produce the following warning for every image which make me think it's not the intended way:
```sh
WARN[0025] image [...] is not used.  subtask=-1 task=DevLoop
WARN[0025] See helm documentation on how to replace image names with their actual tags: https://skaffold.dev/docs/pipeline-stages/deployers/helm/#image-configuration  subtask=-1 task=DevLoop
```

**Comment by falcorocks** [comment]
@toniopelo hey, I have a similar situation to your but I can't get the deploy tag to match that used in build. Can you provide me with a full example of your workaround?

```yaml
# my values.yaml
base:
  image:
    repository: xxx/base
    tag: v1.7.5
    pullPolicy: IfNotPresent

webserver:
  image:
    repository: xxx/webserver
    tag: v1.7.5
```

```yaml
# skaffold.yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: myapp
build:
  artifacts:
    - image: xxx/base
      context: ./base
    - image: xxx/webserver
      context: .
deploy:
  helm:
    releases:
    - name: myapp
      createNamespace: true
      namespace: dev
      chartPath: .
      version: 0.1.0
      valuesFiles:
        - values.yaml
      setValueTemplates:
        base.image.repository: '{{.IMAGE_NAME}}'
        base.image.tag: '{{.IMAGE_TAG}}'
        webserver.image.repository: '{{.IMAGE_NAME2}}'
        webserver.image.tag: '{{.IMAGE_TAG2}}'
```

```yaml
$ skaffold dev  
Listing files to watch...
 - xxx/base
 - xxx/webserver
Generating tags...
 - xxx/base -> xxx/base:v1.7.5 #notice that this is a git submodule with tree set at tag v1.7.5
 - xxx/webserver -> xxx/webserver:32ed75d-dirty
Tags used in deployment:
 - xxx/base -> xxx/base:2f007284f8587f4618c03921aa8972a8bfc0a726de9a925d87a4b270d4edd474
 - xxx/webserver -> xxx/webserver:bcd5006051826c35e7cd38336593eb6a07c7c48bab4fd0fa3ca4504d1469b9b9
# which then fails because of mismatch
 ```

**Comment by aaron-prindle** [comment]
Adding some more context here.  The change to remove `artifactOverrides` (and subsequently `imageStrategy`) comes from the PR here which explains the rationale: https://github.com/GoogleContainerTools/skaffold/pull/6949

> This PR removes the Helm deployer's artifactOverrides configuration by using Skaffold as the Helm post-renderer to perform our manifest transformations, including image replacement. This simplifies configuring Helm projects and also avoiding resource churn (e.g., setting a label on a deployments will re-create its pods; https://github.com/GoogleContainerTools/skaffold/issues/3133).

> This change requires moving our minimum supported Helm version to 3.1.0. This change will break any users that use their own post-renderer hooks via deploy.helm.flags.

I think some of the context and important information was not conveyed in the current `No more artifactOverrides` note we have here - https://skaffold.dev/docs/pipeline-stages/deployers/helm/#configuring-your-helm-project-with-skaffold.  I will update the note there and the examples to have some additional/more-complex solutions as well as explicitly callout that `imageStrategy` is also removed.  The actual logic for migrating v1 `artifactOverrides` to `v2` `setValues` (for imageStrategy:`fqn`) or `setValues` & `setValueTemplates` (for imageStrategy:`helm`) is here

**Comment by aaron-prindle** [comment]
@falcorocks I believe the issue you are having is that the tag values:
```yaml
base.image.tag: '{{.IMAGE_TAG}}'
```

should instead be
```yaml
base.image.tag: '{{.IMAGE_TAG}}@{{.IMAGE_DIGEST}}'
```

**Comment by aaron-prindle** [comment]
@toniopelo my PR attempted to acccount for `fqn` and `helm` image strategies (see the comments below): https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/schema/v2beta29/upgrade.go#L118-L143

Is there possibly an issue in the logic there?

**Comment by aaron-prindle** [comment]
Created https://github.com/GoogleContainerTools/skaffold/issues/8057 to track adding more context and migration information to the relevant helm documentation

**Comment by aaron-prindle** [comment]
Also did users here find that `skaffold fix` (or the auto-upgrade) broke them and they required manual

**Comment by alewis001** [comment]
Hi @aaron-prindle , yes `skaffold fix` didn't produce a working file. The output from `fix` used `setValues` but I had to change that to `setValuesTemplate` as per my earlier comment here: https://github.com/GoogleContainerTools/skaffold/issues/8002#issuecomment-1298359406

**Comment by aaron-prindle** [comment]
@alewis001 can you post a redacted version of the `v1` `skaffold.yaml` that did not work in the thread here?  That way we can try to fix this issue in `skaffold fix`.

**Comment by alewis001** [comment]
> @alewis001 can you post a redacted version of the `v1` `skaffold.yaml` that did not work in the thread here? That way we can try to fix this issue in `skaffold fix

Ha, I just updated my previous comment before you posted. Yes, I'll try to get that today if I can. Unfortunately not at my computer much today so it might be tomorrow.

**Comment by falcorocks** [comment]
> @falcorocks I believe the issue you are having is that the tag values:
> 
> ```yaml
> base.image.tag: '{{.IMAGE_TAG}}'
> ```
> 
> should instead be
> 
> ```yaml
> base.image.tag: '{{.IMAGE_TAG}}@{{.IMAGE_DIGEST}}'
> ```

thank you @aaron-prindle , but it's still won't work, even in a single image scenario. BTW I'm working with a local kubernetes cluster (k3d) could this be relevant?

```
# skaffold.yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: crs-watcher
build:
  artifacts:
    - image: registry.gitlab.com/cyberrs/watcher
deploy:
  helm:
    releases:
    - name: crs-watcher
      namespace: staging
      createNamespace: true
      chartPath: .
      valuesFiles:
        - values.yaml
      setValueTemplates:
        image.repository: '{{.IMAGE_REPO}}'
        image.tag: '{{.IMAGE_TAG}}@{{.IMAGE_DIGEST}}'
```

```
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cyberrs-watcher
  name: {{ .Release.Name }}-watcher
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberrs-watcher
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cyberrs-watcher
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: watcher
        resources: {}
```

```
# values.yaml
image:
  repository: registry.gitlab.com/cyberrs/watcher
  tag: latest
```

```bash
$ skaffold dev
Listing files to watch...
 - registry.gitlab.com/cyberrs/watcher
Generating tags...
 - registry.gitlab.com/cyberrs/watcher -> registry.gitlab.com/cyberrs/watcher:69dae48
Checking cache...
 - registry.gitlab.com/cyberrs/watcher: Found. Tagging
Tags used in deployment:
 - registry.gitlab.com/cyberrs/watcher -> registry.gitlab.com/cyberrs/watcher:9552842b0246863c7c151716c102822d5dd23ee17fe9c54f9dd26a9ea8e403e5
Starting deploy...
Loading images into k3d cluster nodes...
Images loaded in 84ns
Release "crs-watcher" has been upgraded. Happy Helming!
NAME: crs-watcher
LAST DEPLOYED: Thu Nov 10 10:46:02 2022
NAMESPACE: staging
STATUS: deployed
REVISION: 12
TEST SUITE: None
WARN[0006] image [registry.gitlab.com/cyberrs/watcher:9552842b0246863c7c151716c102822d5dd23ee17fe9c54f9dd26a9ea8e403e5] is not used.  subtask=-1 task=DevLoop
WARN[0006] See helm documentation on how to replace image names with their actual tags: https://skaffold.dev/docs/pipeline-stages/deployers/helm/#image-configuration  subtask=-1 task=DevLoop
Waiting for deployments to stabilize...
 - staging:deployment/crs-watcher-watcher: InspectFailed: Failed to apply default image tag "registry.gitlab.com/cyberrs/watcher:9552842b0246863c7c151716c102822d5dd23ee17fe9c54f9dd26a9ea8e403e5@": couldn't parse image reference "registry.gitlab.com/cyberrs/watcher:9552842b0246863c7c151716c102822d5dd23ee17fe9c54f9dd26a9ea8e403e5@": invalid reference format
    - staging:pod/crs-watcher-watcher-858d468b76-wvpb9: InspectFailed: Failed to apply default image tag "registry.gitlab.com/cyberrs/watcher:9552842b0246863c7c151716c102822d5dd23ee17fe9c54f9dd26a9ea8e403e5@": couldn't parse image reference "registry.gitlab.com/cyberrs/watcher:9552842b0246863c7c151716c102822d5dd23ee17fe9c54f9dd26a9ea8e403e5@": invalid reference format
```

**Comment by alewis001** [comment]
Hi,

Hopefully the attached files are useful. I have removed some profiles as they were just repeats with minor changes but I have left a single profile in each file.

## Skaffold v1 (api version: v2beta16)
The Helm Template `spec.template.spec.containers.image: {{ .Values.image }}` in order to have the value populated by Skaffold v1 binary (_this was as a result of my understanding of the docs and it worked so I assumed, rightly or wrongly, that I was doing the right thing_).

When using Skaffold v2 binary, the Helm Template value was `null`.

[skaffold.v2beta16.yaml.txt](https://github.com/GoogleContainerTools/skaffold/files/9979802/skaffold.v2beta16.yaml.txt)

## Skaffold v2 (api version: v3)
This file was generated using `skaffold fix`. This did not change the behaviour of skaffold v2 binary, the image value remained `null`.

[skaffold.v3.yaml.txt](https://github.com/GoogleContainerTools/skaffold/files/9979809/skaffold.v3.yaml.txt)

## Skaffold v2 (api version: v3) - Fixed
After guidance from @cmeury, I made the changes as I mentioned [in this comment](https://github.com/GoogleContainerTools/skaffold/issues/8002#issuecomment-1298359406l) to produce this file.

I.e. Changed the Helm Template to `spec.template.spec.containers.image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"` and the following in the `skaffold.yaml`:

```
setValueTemplates:
  image.repository: '{{.IMAGE_REPO}}'
  image.tag: '{{.IMAGE_TAG}}@{{.IMAGE_DIGEST}}'
```

[skaffold.v3-fixed.yaml.txt](https://github.com/GoogleContainerTools/skaffold/files/9979816/skaffold.v3-fixed.yaml.txt)

**Comment by aaron-prindle** [comment]
Thanks for the information @alewis001.  In reading through this I still trying to understand how the [skaffold.v3.yaml.txt](https://github.com/GoogleContainerTools/skaffold/files/9979809/skaffold.v3.yaml.txt) file produced `null` for the image. If I understand correctly, your project setup is (with respect to helm + skaffold) very similar to our example here:
https://github.com/GoogleContainerTools/skaffold/blob/main/examples/helm-deployment/skaffold.yaml

which does have it's `image: ` field populated:

`skaffold render`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skaffold-helm
  name: skaffold-helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skaffold-helm
  template:
    metadata:
      labels:
        app: skaffold-helm
    spec:
      containers:
      - image: gcr.io/aprindle-test-cluster/skaffold-helm:latest@sha256:9b1a4826a617ebd2d17527cebad1ca6584e470116235da13528553f7a07149eb
        name: skaffold-helm
```

Ideally we want to move away from using `setValueTemplates` in our migration logic as it is not-intuitive as a result of #5317 (#8008 shows an example of this).  Can you possibly share any logs for the failing runs?  Currently my understanding of the issues with migrating from `v1` -> `v2` using `artifactOverrides` is essentially that `setValueTemplates` doesn't work as the upgrade `fix` logic intended (`IMAGE_TAG` is not sufficient for multi-config, need `IMAGE_TAG`, `IMAGE_TAG2`, `IMAGE_TAGX`) and currently the new solution would be to instead do something like:

`imageStrategy: fqn` ->
setValueTemplates:
  image: image-name
  
`imageStrategy: helm` ->
setValueTemplates:
  image.repository: image-name
  image.tag: image-name
    
`imageStrategy: helm+explicitRegistry` ->
  setValueTemplates:
    image.regsitry: image-name
    image.repository: image-name
    image.tag: image-name
