### ISSUE TITLE
Cleanup is not working when helm deployer is used with skaffold dev

### ISSUE THREAD

**Issue by ericzzzzzzz** [GoogleContainerTools/skaffold#8033]
### Expected behavior
 - skaffold should clean up running resource if helm deployer is used with skaffold dev

### Actual behavior
 - releases are still running. 

### Information

- Impacted Skaffold version: 2.*.*
 - in this example https://github.com/GoogleContainerTools/skaffold/tree/main/examples/helm-deployment , replace skaffold.yaml with the following ones 
 ```yaml
apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
  - image: skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
```
 - run ```skaffold dev```

the cause is that when only helm deployer being used,  https://github.com/GoogleContainerTools/skaffold/blob/main/cmd/skaffold/app/cmd/dev.go#L74 value is always empty, so cleanup never gets triggered.

### Potential solution

can we remove this condition and always run cleanup?
