### ISSUE TITLE
Skaffold build create kpt-pipeline folder even if not needed

### ISSUE THREAD

**Issue by cmeury** [GoogleContainerTools/skaffold#8041]
### Expected behavior

No kpt folder is created.

### Actual behavior

`.kpt-pipeline` is created in the local directory.

### Information

- Skaffold version: 2.0.1
- Operating system: macOS 13
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: foo
```

### Steps to reproduce the behavior

1. Change into temporary directory
2. Drop above `skaffold.yaml` into it
3. `skaffold build`
4. `ls -la`
