### ISSUE TITLE
Helm [UPDATED] docs only partially?

### ISSUE THREAD

**Issue by falcorocks** [GoogleContainerTools/skaffold#8048]
Hey all,

I'm trying to use v2 with helm, but I can't get the image tagging to override as intended. I may be missing something, but It looks like the docs were updated only partially:

section title at https://skaffold.dev/docs/pipeline-stages/deployers/helm/#configuring-your-helm-project-with-skaffold says 
```
No more `artifactsOverride`
Skaffold no longer requires the intricate configuring of artifactsOverride and image naming strategies.
```

but then the immediately following subsection https://skaffold.dev/docs/pipeline-stages/deployers/helm/#image-configuration gives an example using `artifactsOverride`, which skaffold v2 is not happy with!

So without a working example in the docs, how do I configure helm and images overrides in v2?

**Comment by johnnyhuy** [comment]
Used `setValuesTemplates` instead based on this [document](https://skaffold.dev/docs/environment/templating/)

```yaml
---
apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: example
build:
  artifacts:
    - image: examplecr
deploy:
  helm:
    releases:
      - name: example
        chartPath: charts/example

        # this
        setValueTemplates:
          image: '{{.IMAGE_REPO}}:{{.IMAGE_TAG}}'
```

Not sure if this is expected to be the official solution 🤔
