### ISSUE TITLE
Skaffold not deploying Kustomize resources

### ISSUE THREAD

**Issue by RajithaA97** [GoogleContainerTools/skaffold#8068]
### Expected behavior
  I'm trying to deploy below using "skaffold deploy -p local". 

### Actual behavior
It deploys Helm resources but it doesn't deploy Kustomize resources.

### Information

- Skaffold version: v2.0.2
- Operating system: macOS v12.4
- Installed via: Homebrew
- Contents of skaffold.yaml:

```
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: app-one
manifests:
  helm:
    releases:
      - name: zookeeper
        remoteChart: zookeeper
        namespace: zookeeper
        setValues:
          image.registry: placeholder
          image.repository: placeholder
          image.tag: placeholder
          maxClientCnxns: "0"
          service.type: ClusterIP
        createNamespace: true
        wait: true
        skipBuildDependencies: true
        repo: https://charts.bitnami.com/bitnami
      - name: minio
        remoteChart: minio
        namespace: minio
        setValues:
          auth.rootPassword: miniosecret
          auth.rootUser: minioaccess
          defaultBucket.policy: public
          image.tag: placeholder
          mode: standalone
          persistence.size: 10G
          readinessProbe.initialDelaySeconds: "10"
          readinessProbe.timeoutSeconds: "5"
          service.type: ClusterIP
          tls.enabled: "false"
        createNamespace: true
        repo: https://charts.bitnami.com/bitnami
deploy:
  helm: {}
portForward:
  - resourceType: service
    resourceName: app-svc
    namespace: app
    port: 9311
    localPort: 9311
profiles:
  - name: local
    patches:
      - op: replace
        path: /manifests/helm/releases/0/setValues/image.registry
        value: bitnami
    manifests:
      kustomize:
        paths:
          - ./k8s/overlays/
    deploy:
      kubeContext: k3d-local
```

**Comment by ericzzzzzzz** [comment]
Hi @RajithaA97 , could you provide a minimum reproduction project? thanks

**Comment by ericzzzzzzz** [comment]
Hi @RajithaA97  , to deploy kustomize manifests. you need to use kubectl deployer.  You can replace helm with kubectl deployer under deploy stanza, like 
```yaml
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: app-one
manifests:
  helm:
    releases:
      - name: zookeeper
       ....
deploy:
  kubectl: {}
...
profiles:
  - name: local
    patches:
      - op: replace
        path: /manifests/helm/releases/0/setValues/image.registry
        value: bitnami
    manifests:
      kustomize:
        paths:
          - ./k8s/overlays/
    deploy:
      kubeContext: k3d-local
```

then your kustomzie manifests should be deployed when running ``skaffold deploy -p local``, but this is gonna be a little awkward as you won't be able to manage your release with helm. If this is ok for you, I think that might be the easiest way to fix.  Or you can add kubectl deployer instead of replacing helm deployer with it. Although you can use manage your release with helm now,  some artifacts are deployed twice, one from helm deployer -- it only deploys helm releases defined in manifests stanza, another from kubectl deployer, it deploys everything defined in manifests. You may not want this either. The awkward is caused by deployers are not able to specify which manifests they want to deploy, they just deploy manifests defined in the same pipeline. We need to do some improvement to enable a deployer to choose what to deploy. 
Alternatively, you can use skaffold module feature as a workaround.  In your case, that should looks like 
a root skaffold.yaml

```yaml
apiVersion: skaffold/v4beta1
kind: Config
requires:
  - path: your/kustomize/project/path
  - path: your/helm/project/path
```
and two dependent skaffold yaml files  and put each of them in their own project. 
helm project 
```yaml
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: app-one
build:
  artifacts:
   ...
manifests:
  helm:
    releases:
       ....
deploy:
  helm: {}
profiles:
  - name: local
    patches:
    ....
```
kustomize project
```yaml
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: app-two
manifests:
  kustomize:
    paths:
      - ....
deploy:
  kubectl: {}
```

then run ``skaffold deploy -p local -m app-one -m app-two`` in your root project,  that should let helm only deploy your helm releases, and kubectl only deploys kustomize manifests.
