### ISSUE TITLE
Deploy fails with unset Kubernetes context

### ISSUE THREAD

**Issue by laurivosandi** [GoogleContainerTools/skaffold#8098]
### Expected behavior

`skaffold dev --kube-context foo` works even if `current-context` is not  set in `~/.kube/config`

### Actual behavior

Deploy fails

### Information

- Skaffold version: v2.0.1-24-g8dc3b9bbd
- Operating system:Ubuntu 22.04.1 LTS
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: hello-python
build:
  artifacts:
  - image: hello-python
deploy:
  kubectl: {}
manifests:
  rawYaml:
     - deployment.yaml
```

### Steps to reproduce the behavior

Unset `current-context` in `~/.kube/config`

With `-vdebug` it is seen that particular command that will fails is `kubectl config view --minify -o jsonpath='{..namespace}'` with message `error: current-context must exist in order to minify`
