### ISSUE TITLE
skaffold debug not working with yarn2 and nestjs

### ISSUE THREAD

**Issue by Rankarusu** [GoogleContainerTools/skaffold#8142]
I'm having trouble configuring step debugging in my nestjs project using yarn2(pnp + zero install). After a little troubleshooting I was advised to open an issue here.

I already tried changing the entrypoint in the dockerfile to just `start` and setting the `WRAPPER_ENABLED=false` environment variable. It seems that yarn itself takes in the `NODE_OPTIONS : --inspect=0.0.0.0:9229` set by `skaffold debug` before passing it to the actual process.

### Expected behavior
when running skaffold debug, my breakpoints should be bound and hit
### Actual behavior
`Starting inspector on 0.0.0.0:9229 failed: address already in use` is displayed during startup and breakpoints cannot be bound
### Information

- Skaffold version:  v1.39.2
- Operating system: Windows 10
- Installed via:  Chocolatey
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: test
build:
  local:
    push: false
    concurrency: 0 #build as much parallel as possible
  artifacts:
    - image: test
      context: .
      docker:
        dockerfile: docker/Dockerfile
        target: devserver
      sync:
        manual:
          - src: 'src/**/*'
            dest: '.'
      hooks:
        before:
          - command: ['sh', '-c', 'yarn install']
deploy:
  kustomize:
    paths:
      - k8s/overlays/docker-desktop
  kubeContext: docker-desktop
```

### Steps to reproduce the behavior

1. [a clonable repository with the sample skaffold project](https://github.com/Rankarusu/skaffold_yarn2_nestjs_debugging)
2. `skaffold debug`
3. try to set a breakpoint in vscode and send a GET-request to `test.dev.localhost`

**Comment by Rankarusu** [comment]
I managed to find a workaround, albeit using `skaffold dev` instead of `skaffold debug`.
Here is what I did:

1. Expose Port 9229 in the dockerfile
2. Change the entrypoint to start:debug (nest script, but that should be the equivalent to --inspect)
3. Add a port forward for `9229` to `skaffold yaml`
4. use a working debugger config inside `launch.json`

```yml
#skaffold.yaml
portForward:
- resourceType: deployment
  resourceName: test
  port: 9229
  localPort: 9229
```

```jsonc
//launch.json
        {
            "type": "node",
            "request": "attach",
            "name": "Attach Node Debugger to Skaffold",
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/nest",
            "port": 9229,
            "restart": true
        },
```
