### ISSUE TITLE
Dockerfile 1.4 heredoc syntax not supporter

### ISSUE THREAD

**Issue by jsok** [GoogleContainerTools/skaffold#8160]
### Expected behavior

A `Dockerfile` like the following should build:

```Dockerfile
# syntax=docker/dockerfile:1.4
FROM scratch
COPY <<EOF /hello.text
Hello, World!
EOF
```

### Actual behavior

Skaffold returns the error:

```
getting hash for artifact "heredoc-example": getting dependencies for "heredoc-example": file pattern [<<EOF] must match at least one file
```

### Information

- Skaffold version: v2.0.2
- Operating system: macOS 12.6.1
- Installed via: homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: heredoc-example
      docker:
        dockerfile: Dockerfile
```

### Steps to reproduce the behavior

Use the above `skaffold.yaml` and `Dockerfile` to reproduce.
