### ISSUE TITLE
File watching for sync is very slow on Mac OS

### ISSUE THREAD

**Issue by corporealshift** [GoogleContainerTools/skaffold#8166]
### Expected behavior
Syncing files previously would notice changes in a few seconds (or less).
### Actual behavior
Since upgrading to version v2.0.2 it takes 15 seconds or more to notice files to sync. During this time the skaffold process consumes an entire core of CPU power (100% in activity monitor). Once the "Syncing 1 file to..." message gets posted to the console the CPU usage goes down.

### Information

- Skaffold version: v2.0.2
- Operating system: MacOS Monterey 12.6.1 
- Installed via:Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  # Creating a new image requires a new ECR repo by adding a file here and following the README instructions.
  # https://github.com/fulcrumapp/eks-flux2/tree/main/infrastructure/base/fulcrum-ops/ecr
  #
  #
  #   READ BEFORE CHANGING ANYTHING IN ARTIFACTS!!!!
  #
  #
  # Changing anything here needs to consider the other profiles lower in the file that might override
  # or make assumptions on the these lists of artifacts
  - image: snip 
    sync:
      manual:
      - src: app/**
        dest: .
      - src: public/**
        dest: .
      - src: vendor/**
        dest: .
      - src: test/**
        dest: .
      - src: spec/**
        dest: .
      - src: lib/tasks/**
        dest: .
      # this one is less about syncing and more making sure we don't rebuild
      # since we don't use this path in this container
      - src: lib/assets/fulcrum-components/**
        dest: .
      hooks:
        after:
        - container:
            # This should be safe to run on every pod in chaos, but it would be better to only run on sidekiq.
            command: ["sh", "-c", "ps auxww | grep sidekiq | grep app | grep -v grep | awk '{ print $2; }' | xargs -r kill -12"]
            # Currently unsupported by sync hooks, but hopefully soon.
            #containerName: sidekiq
            #podName: rails-fulcrum-sidekiq-all*
        - host:
            command: ["sh", "-c", "echo Restarting sidekiq."]
            os: [darwin, linux]
    docker:
      dockerfile: docker/ruby/Dockerfile
      buildArgs:
        ENV: production
        BASE_VERSION: stable
        ASSETS_VERSION: "dev-{{.USER}}"
  - image: snip 
    docker:
      dockerfile: docker/components/Dockerfile
    sync:
      manual:
      - src: lib/assets/fulcrum-components/src/**
        dest: src
        strip: lib/assets/fulcrum-components/src/
  tagPolicy:
    gitCommit: {}
  platforms: ["linux/amd64"]
  local:
    useBuildkit: true
    concurrency: 2
deploy:
  helm:
    releases:
    - name: rails
      chartPath: charts/fulcrum
      valuesFiles:
      - ./charts/fulcrum/values.yaml
      namespace: '{{.USER}}'
      setValueTemplates:
        # See https://skaffold.dev/docs/environment/templating/ for using IMAGE_TAGN et al
        # skaffold requires the digest to match the image when syncing files
        image.tag: '{{.IMAGE_TAG}}@{{.IMAGE_DIGEST}}'
        rails_tag: '{{.IMAGE_TAG}}@{{.IMAGE_DIGEST}}'
        rails_beta_tag: '{{.IMAGE_TAG3}}@{{.IMAGE_DIGEST3}}'
        components_tag: '{{.IMAGE_TAG2}}@{{.IMAGE_DIGEST2}}'
        fulcrum.stripe.use_stripe_for_trials: false
        fulcrum.stripe.webhook_signing_secret: '{{.STRIPE_WEBHOOK_SIGNING_SECRET}}'
        # To work on expressions, uncomment this, and deploy to your env in the fulcrum-expressions repo
        # fulcrum.rails.config.expression_sandbox_url: "https://fulcrumapp-world-{{.USER}}.s3.amazonaws.com/expv1/expressions.html"
        previewPrefix: '{{.USER}}'
        setup.database.always_drop_and_recreate: "false"
        autoscaling.enabled: false
        servicemonitoring.enabled: false
        fulcrum.rails.subsets.stable.enabled: true
        fulcrum.rails.subsets.beta.enabled: false
        fulcrum.rails.stdin: true
        fulcrum.rails.tty: true
        # uncomment to test subsets
        fulcrum.rails.deploy_subsets_without_traffic: false
      skipBuildDependencies: true
      useHelmSecrets: true
      packaged:
        appVersion: dev-{{.USER}}
    flags:
      install:
      - --timeout
      - 600s
      upgrade:
      - --timeout
      - 600s
  statusCheckDeadlineSeconds: 600
profiles:
- name: arm
  activation:
  - env: FULCRUM_ARCH=arm64
  build:
    platforms: ["linux/arm64"]
  patches:
  - op: add
    path: /deploy/helm/releases/0/setValueTemplates/architectures[0]
    value: arm64
- name: beta
  activation:
  - env: FULCRUM_BETA=true
  patches:
  - op: add
    path: /build/artifacts/-
    value:
      image: snip
      sync:
        manual:
        - src: app/**
          dest: .
        - src: public/**
          dest: .
        - src: vendor/**
          dest: .
        - src: test/**
          dest: .
        - src: spec/**
          dest: .
        # this one is less about syncing and more making sure we don't rebuild
        # since we don't use this path in this container
        - src: lib/assets/fulcrum-components/**
          dest: .
        hooks:
          after:
          - container:
              # This should be safe to run on every pod in chaos, but it would be better to only run on sidekiq.
              command: ["sh", "-c", "ps auxww | grep sidekiq | grep app | grep -v grep | awk '{ print $2; }' | xargs -r kill -12"]
              # Currently unsupported by sync hooks, but hopefully soon.
              #containerName: sidekiq
              #podName: rails-fulcrum-sidekiq-all*
          - host:
              command: ["sh", "-c", "echo Restarting sidekiq."]
              os: [darwin, linux]
      docker:
        dockerfile: docker/ruby/Dockerfile
        buildArgs:
          ENV: production
          GEMFILE: Gemfile.beta
          BASE_VERSION: beta
          ASSETS_VERSION: "dev-{{.USER}}"
  - op: add
    path: /deploy/helm/releases/0/setValueTemplates/fulcrum.rails.subsets.beta.enabled
    value: true
  - op: add
    path: /deploy/helm/releases/0/setValueTemplates/fulcrum.rails.deploy_subsets_without_traffic
    value: true
- name: ci
  build:
    platforms: ["linux/amd64"]
    tagPolicy:
      gitCommit:
        ignoreChanges: true
        variant: AbbrevCommitSha
  patches:
    - op: replace # stable build
      path: /build/artifacts/0/docker/buildArgs/ASSETS_VERSION
      value: "{{.IMAGE_TAG}}"
    - op: replace # beta build
      path: /build/artifacts/2/docker/buildArgs/ASSETS_VERSION
      value: "{{.IMAGE_TAG}}"
- name: kaniko
  build:
    artifacts:
    - image: snip 
      sync:
        manual:
        - src: app/**
          dest: .
        - src: public/**
          dest: .
        - src: vendor/**
          dest: .
        - src: test/**
          dest: .
        - src: spec/**
          dest: .
        - src: lib/tasks/**
          dest: .
        # this one is less about syncing and more making sure we don't rebuild
        # since we don't use this path in this container
        - src: lib/assets/fulcrum-components/**
          dest: .
        hooks:
          after:
          - container:
              # This should be safe to run on every pod in chaos, but it would be better to only run on sidekiq.
              command: ["sh", "-c", "ps auxww | grep sidekiq | grep app | grep -v grep | awk '{ print $2; }' | xargs -r kill -12"]
              # Currently unsupported by sync hooks, but hopefully soon.
              #containerName: sidekiq
              #podName: rails-fulcrum-sidekiq-all*
          - host:
              command: ["sh", "-c", "echo Restarting sidekiq."]
              os: [darwin, linux]
      kaniko:
        cache: {}
        dockerfile: docker/ruby/Dockerfile
        buildArgs:
          ENV: production
          BASE_VERSION: stable
          ASSETS_VERSION: "dev-{{.USER}}"
        useNewRun: true
        logTimestamps: true
        reproducible: true
    - image: snip 
      sync:
        manual:
        - src: app/**
          dest: .
        - src: public/**
          dest: .
        - src: vendor/**
          dest: .
        - src: test/**
          dest: .
        - src: spec/**
          dest: .
        # this one is less about syncing and more making sure we don't rebuild
        # since we don't use this path in this container
        - src: lib/assets/fulcrum-components/**
          dest: .
        hooks:
          after:
          - container:
              # This should be safe to run on every pod in chaos, but it would be better to only run on sidekiq.
              command: ["sh", "-c", "ps auxww | grep sidekiq | grep app | grep -v grep | awk '{ print $2; }' | xargs -r kill -12"]
              # Currently unsupported by sync hooks, but hopefully soon.
              #containerName: sidekiq
              #podName: rails-fulcrum-sidekiq-all*
          - host:
              command: ["sh", "-c", "echo Restarting sidekiq."]
              os: [darwin, linux]
      kaniko:
        cache: {}
        dockerfile: docker/ruby/Dockerfile
        buildArgs:
          ENV: production
          GEMFILE: Gemfile.beta
          BASE_VERSION: beta
          ASSETS_VERSION: "dev-{{.USER}}"
        useNewRun: true
        logTimestamps: true
        reproducible: true
    - image: snip 
      kaniko:
        dockerfile: docker/components/Dockerfile
        cache: {}
        useNewRun: true
        logTimestamps: true
        reproducible: true
      sync:
        manual:
        - src: lib/assets/fulcrum-components/src/**
          dest: src
          strip: lib/assets/fulcrum-components/src/
    tagPolicy:
      gitCommit: {}
    platforms: ["linux/amd64"]
    cluster:
      serviceAccount: ci-pipeline
      namespace: ci
      resources:
        requests:
          cpu: 1000m
          memory: 6Gi
      tolerations:
      - key: "arch"
        value: "arm64"
        operator: "Equal"
        effect: "NoExecute"
- name: base
  build:
    artifacts:
    - image: snip 
      kaniko:
        dockerfile: docker/base_images/nginx.Dockerfile
        cache: {}
        useNewRun: true
        logTimestamps: true
        reproducible: true
    - image: snip
      kaniko:
        dockerfile: docker/base_images/tmpwatch.Dockerfile
        cache: {}
        useNewRun: true
        logTimestamps: true
        reproducible: true
    - image: snip 
      kaniko:
        dockerfile: docker/base_images/ruby.Dockerfile
        buildArgs:
          BASE: ruby:3.1.2-slim-bullseye
        cache: {}
        useNewRun: true
        logTimestamps: true
        reproducible: true
    - image: snip 
      kaniko:
        dockerfile: docker/base_images/ruby.Dockerfile
        buildArgs:
          BASE: ruby:3.1.2-slim-bullseye
        cache: {}
        useNewRun: true
        logTimestamps: true
        reproducible: true
    - image: snip 
      kaniko:
        dockerfile: docker/base_images/rails.Dockerfile
        cache: {}
        useNewRun: true
        logTimestamps: true
        reproducible: true
      requires:
      - image: snip 
        alias: RUBYBASE
    - image: snip
      kaniko:
        dockerfile: docker/base_images/rails.Dockerfile
        buildArgs:
          GEMFILE: Gemfile.beta
        cache: {}
        useNewRun: true
        logTimestamps: true
        reproducible: true
      requires:
      - image: snip
        alias: RUBYBASE
    - image: snip 
      kaniko:
        dockerfile: docker/base_images/components.Dockerfile
        cache: {}
        useNewRun: true
        logTimestamps: true
        reproducible: true
    - image: snip
      kaniko:
        dockerfile: docker/base_images/expressions.Dockerfile
        cache: {}
        useNewRun: true
        logTimestamps: true
        reproducible: true
    platforms: ["linux/amd64", "linux/arm64"]
    tagPolicy:
      dateTime:
        format: "2006-01-02_15-04-05"
        timezone: "UTC"
    cluster:
      serviceAccount: ci-pipeline
      namespace: ci
      resources:
        requests:
          cpu: 1000m
          memory: 6Gi
      tolerations:
      - key: "arch"
        value: "arm64"
        operator: "Equal"
        effect: "NoExecute"
    # local:
    #   useBuildkit: true
    #   concurrency: 2

```

### Steps to reproduce the behavior

1. `skaffold dev -vdebug`
2. Change any file
3. See the watcher file in the debug logs
4. nothing happens for some time
5. Finally see the message about syncing 1 file

```
INFO[0907] files modified: [app/controllers/api/private/plans_controller.rb]  subtask=-1 task=DevLoop
DEBU[0907] Found dependencies for dockerfile: [{jenkins-js.sh /app true 12 12} {jenkins-lint.sh /app true 12 12} {jenkins-rubocop.sh /app true 12 12} {jenkins-test.sh /app true 12 12} {lib/assets/fulcrum-components /app true 13 13}]  subtask=-1 task=DevLoop

[ 10+ seconds ....]

DEBU[0919]  devloop: build false, sync true, deploy false  subtask=-1 task=DevLoop
Syncing 1 files for [280296955917.dkr.ecr.us-east-2.amazonaws.com/rails-stable:v3.9.4-696-g9d4bf6bafe-dirty@sha256:56e412d5b1a91b84299ecf5a0e39dd22d200d30850ddb982151eb383a36aa950](http://280296955917.dkr.ecr.us-east-2.amazonaws.com/rails-stable:v3.9.4-696-g9d4bf6bafe-dirty@sha256:56e412d5b1a91b84299ecf5a0e39dd22d200d30850ddb982151eb383a36aa950)
111
```
