### ISSUE TITLE
Logs not streamed from manifests with specific namespaces

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#818]
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: custom-ns
spec:
  containers:
  - name: nginx
    image: nginx
```

Skaffold will deploy this correctly, but won't stream the logs
