### ISSUE TITLE
[FR] Support for Skaffold sync + Jib + war

### ISSUE THREAD

**Issue by GenghisChen** [GoogleContainerTools/skaffold#8182]
### Expected behavior
Skaffold and Jib work together, on war projects, to auto-sync changed files to a deployed container so as to avoid the need to rebuild, redeploy, and restart the corresponding pod

### Actual behavior
When setting up auto-sync on a war project, deployment errors out with the following message:
_"[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.3.1:\_skaffold-sync-map (default-cli) on project web: **Skaffold sync is currently only available for 'jar' style Jib projects**, but the packaging of web is 'war'"_

### Information

- Skaffold version: v2.0.1
- Operating system: Windows 11
- Installed via: Cloud Code
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3
kind: Config

activation:
  - kubeContext: minikube
build:
  artifacts:
    - image: server-local
      context: .
      jib:
        project: web
      sync:
        auto: true
manifests:
  kustomize:
    paths:
      - k8s/overlays/local
```
