### ISSUE TITLE
[regression] Skaffold @ HEAD (in no releases) currently adds a namespace to all rendered manifests

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8186]
With #8105 merged, currently skaffold will always add a namespace to rendered yamls:
```
aprindle@aprindle-ssd ~/skaffold/examples/getting-started  [main]$ skaffold render
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
  namespace: default # <--- this is set
spec:
  containers:
  - image: skaffold-example:v2.0.2-45-g130df30ae
    name: getting-started
```

This is an issue as skaffold cannot then use rendered manifests to deploy to multiple namespaces as most/all deployers will not "overwrite" a namespace set in the yaml config (will error stating such).  

Behavior should  be:
When no namespace is explicitly set, no namespace should be added to allow for deploying to multiple namespaces
