### ISSUE TITLE
Allow templating for buildpack volumes

### ISSUE THREAD

**Issue by ghost** [GoogleContainerTools/skaffold#8207]
### Expected behavior
Templating for buildpack volumes work

### Actual behavior
Templating for buildpack volumes doesn't work

### Information

- Skaffold version: v2.0.3
- Operating system: macOS
- Installed via: Homebrew
- Contents of skaffold.yaml:

This is a java project we are trying to build with maven

```yaml
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: foo
profiles:
  - name: local
    build:
      local:
        concurrency: 1
        tryImportMissing: false
        useDockerCLI: false
      artifacts:
      - image: foo.dkr.ecr.eu-west-1.amazonaws.com/myapp/demo
        buildpacks:
          clearCache: false
          trustBuilder: false
          builder: paketobuildpacks/builder:tiny
          env:
            - ARTIFACTORY_USERNAME={{.ARTIFACTORY_USERNAME}}
            - ARTIFACTORY_PASSWORD={{.ARTIFACTORY_PASSWORD}}
          volumes:
            - host: {{.PWD}}/platform/bindings/maven
              target: /platform/bindings/maven
    manifests:
      rawYaml:
        - ./k8s/*.yaml
    deploy:
      kubectl: {} 
      kubeContext: kind-kind
```

### Steps to reproduce the behavior

1. Use the yaml above
2. Start a kind cluster
3. `skaffold run -p local`
4. See that the buildpack is not able to resolve the templated value
