### ISSUE TITLE
`inputDigest()` build tagging policy doesn't take `Dockerfile` into account

### ISSUE THREAD

**Issue by danielgafni** [GoogleContainerTools/skaffold#8226]
### Expected behavior
Dockerfile should be taken into account when calculating the hash (even when outside the build context).

### Actual behavior
The Dockerfile changes don't trigger a rebuild. In my case the Dockerfile is placed outside of the build context and is not included into the image. 

### Information

- Skaffold version: v2.0.1
- Operating system: Arch Linux
- Installed via: `pacman`
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: my-name

build:
  tagPolicy:
    inputDigest: {}
  artifacts:
    - image: myImage
      context: context-dir
      docker:
        dockerfile: Dockerfile
  local:
    useBuildkit: true
```

### Steps to reproduce the behavior

Make the following project structure:

```
.
├── Dockerfile
├── skaffold.yaml
└── context-dir
    └── file.txt
```

 - run `skaffold build`. 
 - make an edit to `Dockerfile`
 - run `skaffold build`

**Comment by ericzzzzzzz** [comment]
Hi @danielgafni thank you for the feedback, I think it make sense to take Dockerfile into account when computing hash.

**Comment by nicknovitski** [comment]
It should also include changes to the `buildArgs`, even if those do not affect the file source dependencies.  For example:

```
# Dockerfile
ARG node_version

FROM node:${node_version}

# ...
```

```
# skaffold.yaml
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: example
build:
  artifacts:
  - image: example
    docker:
      buildArgs:
        node_version: "18.x.x"
```
