### ISSUE TITLE
Override pushing per image

### ISSUE THREAD

**Issue by GeertJohan** [GoogleContainerTools/skaffold#8237]
I have a scenario where it would be very useful to disable image pushing for a specific image.
Given the following skaffold.yaml (excerpt):
```yaml
apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: base-build
      context: .
      docker:
        dockerfile: base/Dockerfile.build
    - image: base-release
      context: .
      docker:
        dockerfile: base/Dockerfile.release 
    - image: my-app
      context: .
      docker:
        dockerfile: my-app/Dockerfile
      requires:
        - image: base-build
          alias: BASE_BUILD
        - image: base-release
          alias: BASE_RELEASE

... more app builds which all use the base-build and base-release images.

```

And `my-app/Dockerfile`:

```Dockerfile
ARG BASE_BUILD
ARG BASE_RELEASE

FROM $BASE_BUILD as build

.. steps to build the app

FROM $BASE_RELEASE as release

COPY --from=build /build/dist/bin/my-app /usr/local/bin/my-app
