### ISSUE TITLE
dev: dev step: watching files: listing files in folders: lstat : no such file or directory

### ISSUE THREAD

**Issue by joonasmyhrberg** [GoogleContainerTools/skaffold#824]
### Expected behavior
Skaffold watches the configuration file for changes.

### Actual behavior
`walk(dirs)` returns an error in `pkg/skaffold/watch/files.go:52`, ~~where `dirs` contains `skaffold.yaml`. Basically `NewFileWatcher` expects directories, but the dev command stack passes it the configuration file.~~

### Information

- Skaffold version: 0.10.0
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: myapp
    workspace: ../
deploy:
  helm:
    releases:
    - name: myapp
      chartPath: myapp
      values:
        image: myapp
```

### Steps to reproduce the behavior

1. Run `skaffold dev`
