### ISSUE TITLE
Profiles activated by "activation" stanza not propagated

### ISSUE THREAD

**Issue by aran** [GoogleContainerTools/skaffold#8240]
### Expected behavior
Given a configuration like this:

```yaml
apiVersion: skaffold/v4beta1
kind: Config
profiles:
- name: dev
  activation:
    - command: dev
requires:
- path: ./dep/that/uses/profile/dev
```

expect `skaffold dev` and `skaffold dev -p dev` to have the same behavior.

### Actual behavior

When running `skaffold dev`, the `dev` profile is not activated in `/dep/that/uses/profile/dev`. 

### Information

My guess is `--propagate-profiles` does not apply to profiles that are auto-activated with the `activation` stanza, and instead only applying to profiles that are loaded explicitly with with `-p`. 

- Skaffold version: v2.0.3 
- Operating system: macOS 12.6.1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta1
kind: Config
profiles:
- name: dev
  activation:
    - command: dev
requires:
- path: ./dep/that/uses/profile/dev
```

### Steps to reproduce the behavior

1. Create a root `skaffold.yaml` with dev profile activation and requiring a child `skaffold.yaml`
2. Use the dev profile in child `skaffold.yaml` without activation clause
3. Run `skaffold dev`
