### ISSUE TITLE
Skaffold apply fails:  <manifest.yaml> is not a valid Kubernetes manifest

### ISSUE THREAD

**Issue by ttruong-dexcom** [GoogleContainerTools/skaffold#8247]
Is there a way to bypass validation when doing a `skaffold apply`?
`Skaffold deploy` works but doing a skaffold render then apply fails here with terse message.

### Expected behavior
skaffold apply <manifest.yaml>  deploys the manifest.yaml
### Actual behavior
`<manifest.yaml> is not a valid Kubernetes manifest` error
### Information

- Skaffold version: v2.0.3 and v1.39.1
- Operating system: Ubuntu 20.04.2 LTS
- Installed via: curl 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
deploy:
  helm:
    releases:
      - name: clouddeploy-email
        namespace: tt-email
        remoteChart: oci://path/to/chart
        #repo: my-repo
        version: 2.2.6
        valuesFiles:
          - ./environments/common.yaml
          - ./environments/dev/dev.yaml
    flags:
      upgrade:
        - --install
```
