### ISSUE TITLE
Mapping key "somename" already defined at line 

### ISSUE THREAD

**Issue by ehsantashkhisi** [GoogleContainerTools/skaffold#8248]
### Expected behavior
As neither `helm lint` nor `helm install` checks the duplicate key in the YAML files, skaffold post process should not validate this duplication, If it is there to help the developer not to use duplicate keys, it should not consider this in chart dependencies, I am using some dependencies that are using duplicate key somewhere in their chart and because of this behavior I am unable to use those chart as a dependency when using skaffold, but with helm itself, those chart can be installed, it seems that there are extra checks in skaffold post render process.
### Actual behavior
When there is a duplicate key in labels or other elements, running `scaffold dev` show this error:
```
Error: UPGRADE FAILED: error while running post render on files: error while running command /Users/tashkhisi/.asdf/installs/skaffold/2.0.1/bin/skaffold. error output:
reading Kubernetes YAML: yaml: unmarshal errors:
  line 12: mapping key "clusterName" already defined at line 11
```
### Information

- Skaffold version: v2.0.1
- Operating system: mac
- Installed via: Homebrew 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: identity-management

deploy:
  helm:
    releases:
      - name: my-release
        setValues:
          test.image.registry: ""
          test.image.separator: ""
          test.image.repository: my-project
        chartPath: ./my-chart

build:
  tagPolicy:
    gitCommit: { }
  artifacts:
    - image: my-project
      context: my-project
      docker:
        dockerfile: Dockerfile
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...
