### ISSUE TITLE
exclude subdirectories from being watched

### ISSUE THREAD

**Issue by ekimia** [GoogleContainerTools/skaffold#825]
### Expected behavior
I can specify (somehow) certain subfolders to exclude from the watch list.
### Actual behavior
I can't. Or can't find out how.

### Information
Idea is to exclude a directory from being watched, as that directory will be mounted for super super fast local development.

**Comment by ekimia** [comment]
After forking I found this:
`https://github.com/GoogleContainerTools/skaffold/blob/e6f37af6eac07da071070c432760d4bdce47d442/pkg/skaffold/watch/files.go#L31`

Recommend a yaml sequence specifying the folders to exclude. Would do it myself but unfortunately too tied up at the moment.

**Comment by taylorKonigsmark** [comment]
This could be something that i'd be interested working on.

Would the appropriate configuration be something along the lines of:

```
build:
  watchPolicy:
    ignoredDirectories:
      - /path/to/ignored/dir
    ignoredFiles:
      - /path/to/ignored/file.txt
```
