### ISSUE TITLE
'add' patch to setValueTemplates overwrites, rather than appends

### ISSUE THREAD

**Issue by JoelOtter** [GoogleContainerTools/skaffold#8250]
To give a highly contrived example, please see this YAML:

```yaml
apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: my-service
      docker:
        dockerfile: my-service.Dockerfile
manifests:
  helm:
    releases:
      - name: my-service
        chartPath: ./deployment/helm/my-service
        namespace: my-service
        setValueTemplates:
          image: '{{.IMAGE_FULLY_QUALIFIED_my_service}}'
deploy:
  helm: {}
profiles:
  - name: local
    patches:
      - op: add
        path: /manifests/helm/releases/0/setValueTemplates
        value:
          someValue: foo
```

### Expected behavior

I would expect the values to contain both `image` and `someValue` as I used an `add` op rather than `replace`. `add` ought to append.

### Actual behavior

The `image` value is removed, while `someValue` does get rendered in the template.

### Information

- Skaffold version: `v2.0.3`
- Operating system: macOS 12.6
- Installed via: Homebrew

I can replicate the desired behaviour by replacing the patch path with ` /manifests/helm/releases/0/setValueTemplates/` (i.e. a trailing slash). I'm not sure this is the intended behaviour. 

Many thanks to the team for their work on Skaffold; I've been using it for several years now and it's a great tool.

**Comment by ericzzzzzzz** [comment]
I think ``add`` actually means ``insert``, so adding something at index 0 happens to looks like replace but your original node should be at index 1?

**Comment by aaron-prindle** [comment]
Haven't' had time to investigate - re: 

> I think add actually means insert, so adding something at index 0 happens to looks like replacing but your original node should be moved to index 1?

Here are the JSON patch docs for `add`:
https://jsonpatch.com/#add

**Comment by JoelOtter** [comment]
From my reading this implies it should add it to the `setValueTemplates` object (I assume it's an object?) rather than overwriting. It also doesn't really explain why there's a difference between the path with a trailing slash and the one without.

**Comment by ericzzzzzzz** [comment]
according to https://www.rfc-editor.org/rfc/rfc6902#section-4.1 , it is expected ``If the target location specifies an object member that does exist, that member's value is replaced.`` 
I think you need change your config like this to add filed in setValueTemplates obj
```yaml
profiles:
  - name: local
    patches:
      - op: add
        path: /manifests/helm/releases/0/setValueTemplates/someValue
        value: foo
```
