### ISSUE TITLE
Skaffold docs currently have one instance of old/incorrect config for Helm Deployer & renderer

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8260]
Currently skaffold docs page has old/incorrect config which will confuse users & not work in Skaffold (this style was proposed at one point but then changed so it won't work w/ Skaffold and shouldn't be in our docs):

has the following snippet:
```
build:
  artifacts:
    - image: myFirstImage # must match in setValueTemplates
    - image: mySecondImage # must match in setValueTemplates
deploy:
  helm:
    releases:
    - name: my-release
      setValueTemplates:
        image.repository: "{{.myFirstImage.IMAGE_REPO}}"
        image.tag: "{{.myFirstImage.IMAGE_TAG}}"
        image2.repository: "{{.mySecondImage.IMAGE_REPO}}"
        image2.tag: "{{.mySecondImage.IMAGE_TAG}}"
      setValues:
        image.pullPolicy: "IfNotPresent"
        image2.pullPolicy: "IfNotPresent"
```

This is incorrect, it should be of the form:
```
build:
  artifacts:
    - image: myFirstImage  # must match in setValueTemplates
    - image: mySecondImage  # must match in setValueTemplates
deploy:
  helm:
    releases:
      - name: my-chart
        chartPath: helm
        setValueTemplates:
          image: {{.IMAGE_FULLY_QUALIFIED_myFirstImage}}
          image2: {{.IMAGE_FULLY_QUALIFIED_mySecondImage}}
```
