### ISSUE TITLE
[regression] skaffold render + Helm Deployer returning empty values for `image:`

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8262]
Currently @ HEAD if the `skaffold render` command is used with the helm renderer, the image: value is empty (vs populated as it is with `skaffold run` or `skaffold dev`)

```
apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: gcr.io/aprindle-test-cluster/skaffold-helm
manifests:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      setValueTemplates:
        image.repository: '{{.IMAGE_REPO_gcr.io_aprindle_test_cluster_skaffold_helm}}'
        image.tag: '{{.IMAGE_TAG_gcr.io_aprindle_test_cluster_skaffold_helm}}@{{.IMAGE_DIGEST_gcr.io_aprindle_test_cluster_skaffold_helm}}'
deploy:
  helm: {}
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
```

```
aprindle@aprindle-ssd ~/v1-helm-deployment $ skaffold render --images=gcr.io/aprindle-test-cluster/skaffold-helm:latest |& tee ~/out.txt
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skaffold-helm
  name: skaffold-helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skaffold-helm
  template:
    metadata:
      labels:
        app: skaffold-helm
    spec:
      containers:
      - image: :@
        name: skaffold-helm
```

Here the `image: ` field has value `:@` instead of the proper value like `v1.39.4` produces:
```
aprindle@aprindle-ssd ~/v1-helm-deployment $ skaffold-v1.39.4 render --images=gcr.io/aprindle-test-cluster/skaffold-helm:latest 
---
# Source: skaffold-helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-helm
  labels:
    app: skaffold-helm
spec:
  selector:
    matchLabels:
      app: skaffold-helm
  replicas: 2
  template:
    metadata:
      labels:
        app: skaffold-helm
    spec:
      containers:
      - name: skaffold-helm
        image: "gcr.io/aprindle-test-cluster/skaffold-helm:latest@sha256:9b1a4826a617ebd2d17527cebad1ca6584e470116235da13528553f7a07149eb"
```
