### ISSUE TITLE
Project with Cloud Run deployer should not depend on k8s context to determine if an image should be push to remote registry

### ISSUE THREAD

**Issue by renzodavid9** [GoogleContainerTools/skaffold#8289]
Project with Cloud Run deployer should not depend on k8s context to determine if an image should be push to remote registry

### Expected behavior
A project using the Cloud Run deployer should push to a registry the images created, regardless of the k8s context detected by Skaffold (local or remote cluster).

### Actual behavior
A project using the Cloud Run deployer determines when to push an image according to the k8s cluster detected + other rules, even when Cloud Run does not deploy to k8s.

### Information

- Skaffold version: latest version @ HEAD
- Operating system: all
- Installed via: built from @ HEAD
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta2
kind: Config

build:
  artifacts:
  - image: skaffold-example-cloudrun-img

manifests:
  rawYaml:
    - service.yaml

deploy:
  cloudrun:
    projectid: k8s-skaffold
    region: us-central1
```

- Cloud Run service.yaml

```yaml
apiVersion: "serving.knative.dev/v1"
kind: Service
metadata:
  name: skaffold-example-cloudrun-img
spec:
  template:
    spec:
      containers:
      - image: gcr.io/k8s-skaffold/skaffold-example-cloudrun-img
```

### Steps to reproduce the behavior

1. Set you current k8s context to a local cluster, e.g, minikube
2. Go to https://github.com/GoogleContainerTools/skaffold/tree/main/examples/getting-started
3. Replace the content of the `skaffold.yaml` file with the one above, and create a `service.yaml` file with the content above
4. Run `skaffold run --default-repo=gcr.io/k8s-skaffold --tag=latest`
5. You will see the following output:
```
Generating tags...
 - skaffold-example-cloudrun-img -> gcr.io/k8s-skaffold/skaffold-example-cloudrun-img:latest
Checking cache...
 - skaffold-example-cloudrun-img: Found Locally
Starting test...
Tags used in deployment:
 - skaffold-example-cloudrun-img -> gcr.io/k8s-skaffold/skaffold-example-cloudrun-img:156d09e016c111994cbccd674a104ba4ee0985d2d0e491d6fe9c468ee627f185
Starting deploy...
Deploying Cloud Run service:
         skaffold-example-cloudrun-img
Cloud Run Service skaffold-example-cloudrun-img failed with error: Service failed to start: Revision 'skaffold-example-cloudrun-img-7qm2h' is not ready and cannot serve traffic. Image 'gcr.io/k8s-skaffold/skaffold-example-cloudrun-img' not found.
skaffold deployment failed. 0/1 failed to complete
```

**Comment by ar3s3ru** [comment]
I think the issue comment I left here is somewhat related to this: https://github.com/GoogleContainerTools/skaffold/issues/8886#issuecomment-1630482125

**Comment by renzodavid9** [comment]
Hey @ar3s3ru, from your case in https://github.com/GoogleContainerTools/skaffold/issues/8886#issuecomment-1630482125, can you try copying the `build.local.push` property to both profiles? I think this will solve your case, it will look something like this:
```yaml
apiVersion: skaffold/v4beta5
kind: Config

build:
  platforms: ["linux/amd64"]
  local:
    push: true
  artifacts:
  - image: backend
    bazel:
      target: //apps/backend:image.tar


profiles:
- name: local
  manifests:
    rawYaml:
    - apps/**/deploy.local.yaml
    - tools/k3d/manifests/*.yaml

  deploy:
    kubectl: {}

- name: prod
  manifests:
    rawYaml:
    - apps/**/deploy.prod.yaml
  deploy:
    cloudrun:
      projectid: <PROJECT>
      region: <REGION>
```

I have moved the `build.local.push` to the main `build` stanza. This will allow it to be shared by both the `local` and `prod` profiles.
