### ISSUE TITLE
Getting error - build [skaffold-example] failed: exit status 1. Docker build ran into internal error

### ISSUE THREAD

**Issue by rishabhchauhan421** [GoogleContainerTools/skaffold#8291]
### Expected behavior
Build to run successfully

### Actual behavior
Build is not working correctly, it the giving below error:
build [rshbhchauhan/client] failed: exit status 1. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..

### Information

- Skaffold version: v2.0.2
- Operating system: Windows 11 21H2 (22000.1335)
- Installed via: Chocolatey
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: rshbhchauhan/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: rshbhchauhan/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: rshbhchauhan/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: rshbhchauhan/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: rshbhchauhan/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: rshbhchauhan/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
```

### Steps to reproduce the behavior

1. https://github.com/rishabhchauhan421/Skaffold-Error-Repo--01-03-2022
2. skaffold dev
3. Just clone it and run the command
