### ISSUE TITLE
Checking cache step takes several minutes to complete

### ISSUE THREAD

**Issue by Yamaha32088** [GoogleContainerTools/skaffold#8300]
### Expected behavior
Running `skaffold dev` should start booting services quickly
### Actual behavior
Running `skaffold dev` occasionally takes several minutes on the `checking cache` step. Sometimes I have to wait up to 10 minutes before it starts to deploy. 
### Information

- Skaffold version: 2.0.4
- Operating system: Windows 10
- Installed via: Windows binary
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
portForward:
  - resourceType: deployment
    resourceName: cache-depl
    namespace: default
    port: 6379
  - resourceType: service
    resourceName: service-mongo-srv
    namespace: default
    port: 27017
    localPort: 27019
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - ./infra/dev-deployment/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: blah/service1
      context: service1
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.scss"
            dest: .
          - src: "**/*.css"
            dest: .
          - src: "**/*.jsx"
            dest: .
          - src: "**/*.ts"
            dest: .
          - src: "**/*.tsx"
            dest: .
    - image: blah/service2
      context: service2
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.scss"
            dest: .
          - src: "**/*.css"
            dest: .
    - image: blah/service3
      context: service3
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
          A_CODE_VERSION: "dev"
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.scss"
            dest: .
          - src: "**/*.css"
            dest: .
    - image: blah/service4
      context: service4
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.cfm"
            dest: .
          - src: "**/*.cfc"
            dest: .
          - src: "**/*.html"
            dest: .
          - src: "**/*.gif"
            dest: .
          - src: "**/*.js"
            dest: .
          - src: '**/*.jsx'
            dest: .
          - src: '**/*.ts'
            dest: .
          - src: '**/*.tsx'
            dest: .
          - src: '**/*.css'
            dest: .
          - src: '**/*.scss'
            dest: .
          - src: '**/*.vue'
            dest: .
          - src: "**/*.json"
          
            dest: .
    - image: blah/service5
      context: service5
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.js"
            dest: .
    - image: blah/service6
      context: service6
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.js"
            dest: .
    - image: blah/service7
      context: service7
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.js"
            dest: .
    - image: blah/service8
      context: service8
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.js"
            dest: .
    - image: blah/service9
      context: service9
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: '{{.NPM_TOKEN}}'
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
          - src: '**/*.js'
            dest: .
          - src: '**/*.json'
            dest: .
    - image: blah/service10
      context: service10
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.js"
            dest: .
    - image: blah/service11
      context: service11
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.js"
            dest: .
    - image: blah/service12
      context: service12
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.js"
            dest: .
    - image: blah/service13
      context: service13
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.js"
            dest: .
    - image: blah/service14
      context: service14
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.cfm"
            dest: .
          - src: "**/*.cfc"
            dest: .
    - image: blah/service15
      context: service15
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.js"
            dest: .

```
