### ISSUE TITLE
Skaffold attempts unexpected post-build action

### ISSUE THREAD

**Issue by gilbahat** [GoogleContainerTools/skaffold#8302]
### Expected behavior

skaffold build completes successfully with no error message

### Actual behavior

it appears as if the build does complete successfully, but is followed up by an unwarranted registry action:

getting image: GET https://index.docker.io/v2/library/cpu-hogger/manifests/03955c6-dirty: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/cpu-hogger Type:repository]]

### Information

- Skaffold version: v2.0.3
- Operating system: MacOS ventura 13.1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: cpu_hogger
build:
  artifacts:
  - image: cpu-hogger
    kaniko:
      dockerfile: Dockerfile.cpu_hogger
      noPush: true
      verbosity: info
  cluster: {}
```

(unfortunately, I cannot share the dockerfile and contents of cpu_hogger)

### Steps to reproduce the behavior

1. Install docker desktop, set kubernetes context to docker desktop.
2. run skaffold -m build -v debug

see attached log with redactions to dockerfile contents:
[skaffold-log.txt](https://github.com/GoogleContainerTools/skaffold/files/10366193/skaffold-log.txt)
