### ISSUE TITLE
[docs/examples] update examples/helm-deployment (and other examples if needed) to reflect setValueTemplates preference (vs setValues)

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8313]
Issues tracks updates examples/helm-deployment (and other examples if needed) to reflect setValueTemplates preference (vs setValues).  Currentlyt the example has the following `skaffold.yaml`:
```
apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      setValues:
        image: skaffold-helm
```

This is confusing as it seems to suggest `setValues` usage for image subst. which is not correct to do (causes errors w/ multiple images).  It should instead be:
```
apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      setValueTemplates:
        image: {{.IMAGE_FULLY_QUALIFIED_skaffold_helm}}
```
