### ISSUE TITLE
Skaffold by default currently adds a namespace to all rendered manifests (--offline=true must be used to change this).  We should change the default not to add a `namespace``

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8318]
Currently when rendering a manifest with skaffold (`skaffold render ...`) by default skaffold adds a namespace to all rendered objects:
```
aprindle@aprindle-ssd ~/skaffold/examples/getting-started  [main]$ skaffold render -a artifacts.json
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
  namespace: default # <--- namespace is added
spec:
  containers:
  - image: gcr.io/aprindle-test-cluster/skaffold-example:v2.0.2-79-g8d655cdb2@sha256:f45a3b94c62ea0a2f3375745809601af3cbb1aa64ebe36f388927096947f26c1
    name: getting-started
```

This is likely not the best experience for skaffold users as having a hard coded namespace on a manifest when it is not explicity requested in some form can lead to issues where users might want to `render` and then `deploy` to a different namespace but the manifests won't be deployable to that namespace as it has a namespace set likely unintentionally. 

Currently to get skaffold not to add a namespace when doing `skaffold render`, the `offline=true` flag must be added:
```
aprindle@aprindle-ssd ~/skaffold/examples/getting-started  [main]$ skaffold render -a artifacts.json --offline=true
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
spec:
  containers:
  - image: gcr.io/aprindle-test-cluster/skaffold-example:v2.0.2-79-g8d655cdb2@sha256:f45a3b94c62ea0a2f3375745809601af3cbb1aa64ebe36f388927096947f26c1
    name: getting-started
```

This is not obvious (`offline` controls namespacing) and the default here should likely mimic this case vs what it does currently

NOTE: 
We should do a git-bisect and identify what PRs or what skaffold versions introduced this behavior and if this is a regression or how it has always worked
