### ISSUE TITLE
[regression] Skaffold v1 -> v2 helm `artifactsOverride` usage not automatically updated -> failures

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8321]
We have a report where a user using Skaffold in CI/CD noted that for their helm chart which does not set a namespace, Skaffold v2 is deploying the helm chart to a different namespace than Skaffold v1 (this actually errors for them in this case).  Still waiting for more repro information and more specific project/skaffold information, will update the issue with that when it is available

**Comment by aaron-prindle** [comment]
The issue here is that a `v1` skaffold manifest like:
```
apiVersion: skaffold/v2beta6
kind: Config
build:
  artifacts:
  - image: skaffold-helm
deploy:
 helm:
   releases:
     - name: skaffold-helm
       chartPath: charts
       artifactOverrides:
         image: stub-image
       imageStrategy:
         helm: {}
profiles:
 - name: profile-1
   patches:
      - op: replace
        path: /deploy/helm/releases/0/artifactOverrides/image
        value: skaffold-helm
```

IS converted to 
```
apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: skaffold-helm
manifests:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      namespace: repro-ns
      setValueTemplates:
        image.repository: '{{.IMAGE_REPO_fake}}'
        image.tag: '{{.IMAGE_TAG_fake}}@{{.IMAGE_DIGEST_fake}}'
deploy:
  helm: {}
profiles:
- name: non-prod
  patches:
  - op: replace
    path: /manifests/helm/releases/0/artifactOverrides/image
    value: skaffold-helm
```
which fails when the profile is set as the field `artifactOverrides` no longer exists.
