### ISSUE TITLE
Wrong log URL is shown

### ISSUE THREAD

**Issue by shuuji3** [GoogleContainerTools/skaffold#8322]
### Expected behavior

Output the correct log URL like `https://storage.cloud.google.com/shuuji3_cloudbuild/o/log-7df9dc55-168d-48f9-8b9b-be9a6b2040b6.txt`

### Actual behavior

I got the old URL format `https://console.cloud.google.com/m/cloudstorage/b/shuuji3_cloudbuild/o/log-7df9dc55-168d-48f9-8b9b-be9a6b2040b6.txt`. This URL format has been deprecated so I cannot see any log text and the following message is shown instead:

```
This Google Cloud Storage object download format is no longer supported. If you rely on this format, modify your download URLs to use the storage.cloud.google.com API instead.

Example:
console.cloud.google.com/m/cloudstorage/b/my-bucket/o/my-object -> storage.cloud.google.com/my-bucket/my-object

If you exported maps with Earth Engine before 2022-07-18, you can re-export your maps to correct the link or follow the instructions above.

Contact us at gcs-object-download-migration-help@google.com if you need support with migrating.
```

### Information

- Skaffold version: v2.0.3
- Operating system: macOS
- Installed via: Cloud Code
- Contents of skaffold.yaml:

```yaml
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: takahe
build:
  platforms: ["linux/arm64"]
  artifacts:
    - image: gcr.io/shuuji3/takahe-dev
      context: .
      docker:
        dockerfile: docker/Dockerfile
  googleCloudBuild:
    timeout: 3600s
deploy:
  statusCheckDeadlineSeconds: 300
manifests:
  rawYaml:
    - kubernetes/configmap.yaml
    - kubernetes/postgres.yaml
    - kubernetes/secret.yaml
    - kubernetes/stator.yaml
    - kubernetes/webserver.yaml
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project (sorry there is no repository)
2. `skaffold dev`:
```shell
Validating Kubernetes dependencies...
Validating image repository settings...

/Users/shuuji3/Library/Application Support/cloud-code/bin/versions/0031dbdda2711c2792ffe249194dabbb8599cded7f7b28a0d9085f5455359ec5/skaffold dev --filename skaffold.yaml --label ide=cloudcodeintellij --rpc-port 50051 --port-forward=true --wait-for-deletions-max=2m0s --status-check=true --verbosity warn
```
3. Then, it will output the log URL `https://console.cloud.google.com/m/cloudstorage/b/shuuji3_cloudbuild/o/log-7df9dc55-168d-48f9-8b9b-be9a6b2040b6.txt`

```
Listing files to watch...
 - gcr.io/shuuji3/takahe-dev
Generating tags...
 - gcr.io/shuuji3/takahe-dev -> gcr.io/shuuji3/takahe-dev:0.6.1-82-g4f2f5f5-dirty
Checking cache...
 - gcr.io/shuuji3/takahe-dev: Not found. Building
Starting build...
Building [gcr.io/shuuji3/takahe-dev]...
Target platforms: [linux/arm64]
Pushing code to gs://shuuji3_cloudbuild/source/shuuji3-6da4754f-77e5-4fba-903e-6468b9217ded.tar.gz
Logs are available at 
https://console.cloud.google.com/m/cloudstorage/b/shuuji3_cloudbuild/o/log-7df9dc55-168d-48f9-8b9b-be9a6b2040b6.txt
starting build "7df9dc55-168d-48f9-8b9b-be9a6b2040b6"
...
```
