### ISSUE TITLE
skaffold apply uses incorrect namespace if kubectl `-n` or `--namespace` flag is provided in deploy.kubectl.flags.apply field

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8336]
There is currently an issue where skaffold apply uses incorrect namespace if kubectl `-n` or `--namespace` flag is provided in deploy.kubectl.flags.apply field

Repro:

`skaffold.yaml`
```
apiVersion: skaffold/v4beta1
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
  - /workspace/source/deployment.yaml
  - /workspace/source/service.yaml
  - /workspace/source/httproute.yaml
deploy:
  kubectl:
    flags:
      apply:
      - --namespace=service-mesh
  logs:
    prefix: container
```

`manifests.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-mesh
  name: service-mesh-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-mesh
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service-mesh
    spec:
      containers:
      - image: gcr.io/google-containers/nginx:latest
        imagePullPolicy: Always
        name: hello-app
```

Unexpected/Bug-indicating Error message (should work):
```
- the namespace from the provided object "default" does not match the namespace "service-mesh". You must pass '--namespace=default' to perform this operation.
```

Works with:
```
    flags:
      global:
      - --namespace=service-mesh
```

But not:
```
    flags:
      apply:
      - --namespace=service-mesh
```
