### ISSUE TITLE
Skaffold 2 appears unable to deal with : in repository name (eg when registry runs on non-5000 port)

### ISSUE THREAD

**Issue by agxs** [GoogleContainerTools/skaffold#8358]
### Expected behavior

Skaffold should support image repository names with : in them when registries run on non-standard ports.

### Actual behavior

When running eg `skaffold dev` the following error occurs:

```
construct override args: unable to parse template: "{{.IMAGE_TAG_registry_url:1234_container}}": template: envTemplate:1: expected :=
```

### Information

- Skaffold version: 2.1.0 & 2.0.6 (Skaffold 1.39 was fine, although it works in a different way)
- Operating system: MacOS 13.1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: releaseName
build:
  artifacts:
  - image: registry:1234/container
    context: ../container
manifests:
  helm:
    releases:
    - name: releaseName
      chartPath: releaseName
      valuesFiles:
      - config.dev.yaml
      setValueTemplates:
        image.name: '{{.IMAGE_REPO_registry_1234_container}}'
        image.tag: '{{.IMAGE_TAG_registry:1234_container}}'
deploy:
  helm: {}
```

### Steps to reproduce the behavior

Essentially run a registry on a non-standard port and try and put this registry name with the port as the repository name.

My configuration was actually generated via `skaffold fix` from the following skaffold 1 file:

```yaml
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: releaseName
build:
  artifacts:
  - image: registry:1234/container
    context: ../container
deploy:
  helm:
    releases:
    - name: releaseName
      chartPath: releaseName
      valuesFiles:
      - config.dev.yaml
      artifactOverrides:
        image: registry:1234/container
      imageStrategy:
        helm: {}
```

https://skaffold.dev/docs/pipeline-stages/deployers/helm/#image-configuration specified sanitization characters but : is not among them.
