### ISSUE TITLE
[FeatureRequest] Allow remoteChart downloaded to an alias

### ISSUE THREAD

**Issue by lzvoyager** [GoogleContainerTools/skaffold#8366]
### Information

- Skaffold version: v2.0.4
- Operating system: Linux Debian 5.19.11-1rodete1
- Installed via: curl -Lo skaffold \
https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
sudo install skaffold /usr/local/bin/

- Contents of skaffold.yaml (excerpt):

```yaml
profiles:
- name: local-mobile-api-gateway
  manifests:
    helm:
      releases:
      - name: istio-ingress
        remoteChart: gateway
        namespace: istio-ingress
        version: 1.12.0
        setValues:
          service.type: ClusterIP
        createNamespace: false
        wait: true
        repo: gs://verily-plato-helm-charts-thirdparty/istio
      - name: plato-gateway
        remoteChart: gateway
        namespace: istio-ingress
        version: 1.12.0
        setValues:
          gatewayCertificate: cluster-gateway-cert
        wait: true
        repo: gs://verily-plato-helm-charts-stable/
```

In the above excerpt, 2 releases both point to remoteChart: gateway. They both will end up getting pulled down into repo cache - interfering with each other. Is there a way to pull remoteChart: FOO into ALIAS-FOO?
