### ISSUE TITLE
Skaffold slow to start before first log

### ISSUE THREAD

**Issue by nickdapper** [GoogleContainerTools/skaffold#8367]
Trying to migrate v2 to v3 with about 40+ microservices. If I comment out more microservices, the startup time gets faster. Definitely a correlation there. 

### Expected behavior
Should see logs almost immediately to see what's happening

### Actual behavior
No logs for about 1.5 minutes.  

### Information

- Skaffold version:` v2.0.4`
- Operating system: `mac 12.5.1`
- Installed via: `homebrew`

Top level config file with microservices in each command folder. For example: 
```yaml
apiVersion: skaffold/v3
kind: Config
requires:
  - path: cmd/service-1/skaffold.yaml
  - path: cmd/service-2/skaffold.yaml
  - path: cmd/service-3/skaffold.yaml
  - path: cmd/service-4/skaffold.yaml
  - path: cmd/service-5/skaffold.yaml
  
```

Microservice: 
```yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: service-1
profiles:
  - name: dev
    manifests:
      rawYaml:
        - 'deployment.yml'
        - 'service.yml'
    build:
      tagPolicy:
        inputDigest: {}
      artifacts:
        - image: myregistry/myorg/service-1
          context: build
          docker:
            dockerfile: Dockerfile
    deploy:
      kubectl: {}
```

### Steps to reproduce the behavior
`skaffold build -f skaffold.yaml -p dev`

### Logs
While I can't paste all logs (security), I can paste where I think the slowdown is. I didn't know about the `-vdebug` option before.  

```
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
...repeats for 102 seconds? 
DEBU[0102] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
```
