### ISSUE TITLE
skaffold verify behaves inconsistently when skaffold.yaml requires other skaffold.yaml configs

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8368]
# Reproduction steps
1) Have a top-level `skaffold.yaml` which requires other configs and has verify section.
```
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: accounts
requires:
- configs:
  - contacts
  path: contacts/skaffold.yaml
- configs:
  - userservice
  path: userservice/skaffold.yaml
deploy:
  kubectl: {}
build:
  artifacts:
    - image: e2e-tests
      context: .github/workflows/ui-tests
verify:
  - name: e2e-test
    container: 
      name: e2e-test-container
      image: e2e-tests
```
2) Run `skaffold build --file-output artifacts.json`
3) Run `skaffold verify --build-artifacts artifacts.json`

# Expected behavior
Skaffold runs the verify test using the e2e-tests image.

# Observed behavior
skaffold outputs error: "invalid skaffold config: verify command expects non-zero number of test cases"

# Additional skaffold configuration that leads to the same issue

## skaffold.yaml
```
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: accounts
requires:
- configs:
  - contacts
  path: contacts/skaffold.yaml
- configs:
  - userservice
  path: userservice/skaffold.yaml
- configs:
  - e2e-accounts
  path: ../../skaffold-e2e.yaml
deploy:
  kubectl: {}
  tolerateFailuresUntilDeadline: true
```

## skaffold-e2e.yaml
```
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: e2e-accounts
build:
  artifacts:
    - image: e2e-tests
      context: .github/workflows/ui-tests
verify:
  - name: e2e-test
    container: 
      name: e2e-test-container
      image: e2e-tests
```

# Known workaround
Use the same `skaffold-e2e.yaml` but put the `requires` list element that refers to `skaffold-e2e.yaml` as the first element of the list.
```
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: accounts
requires:
- configs:
  - e2e-accounts
  path: ../../skaffold-e2e.yaml
- configs:
  - contacts
  path: contacts/skaffold.yaml
- configs:
  - userservice
  path: userservice/skaffold.yaml
deploy:
  kubectl: {}
  tolerateFailuresUntilDeadline: true
```
