### ISSUE TITLE
using `--tag` re-tags `linux/amd64` image on multi-platform builds

### ISSUE THREAD

**Issue by dsiebel** [GoogleContainerTools/skaffold#8380]
### Preface

We are using buildkit to build multi-arch images with  `BUILDKIT_INLINE_CACHE=1` and `cacheFrom` to benefit from proper layer-caching on our CI system.
To achieve that we basically run

```sh
# regular build
skaffold build

# cache build in a separate step
skaffold build --tag cache
```

We make use of the Skaffold cache for this, which, on the cache build, has to just re-tag and push:

```
   Generating tags...
   - myimage -> myimage:cache
  Checking cache...
   - myimage: Found. Tagging
```

We noticed that when building for multiple architectures - arm and x86 - the x86 image gets re-tagged instead of the multi-arch manifest:

![image](https://user-images.githubusercontent.com/145283/215436298-32d40d85-eb83-423b-aee5-da53bffa2465.png)
(images in Google Aritfact Registry)

This leads to the layer caching to only work for the x64 images, which does not cut down the build time in the end.

### Expected behavior

Using `--tag` re-tags the multi-arch manifest (no arch prefix, just short sha) instead of the `_linux_amd64` image variant.

### Actual behavior

Additional tag `:cache` is created for the `_linux_amd64` tag.

### Information

- Skaffold version: `2.1.0`
- Operating system: macOS 12.6, Ubuntu 22.04.1
- Installed via: Homebrew, [yokawasa/action-setup-kube-tools](https://github.com/yokawasa/action-setup-kube-tools)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: my-workload

build:
  artifacts:
    - image: my-image
      context: .
      docker:
        buildArgs:
          BUILDKIT_INLINE_CACHE: '1'
        cacheFrom:
          - my-image:cache
        dockerfile: docker/my-service.Dockerfile
  local:
    push: true
    tryImportMissing: true
    useBuildkit: true
  platforms:
    - linux/amd64
    - linux/arm64
  tagPolicy:
    gitCommit:
      ignoreChanges: true
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold build`
3. `skaffold build --tag cache`
4. Check resulting images & tags in registry
