### ISSUE TITLE
Skaffold does not template Helm images properly

### ISSUE THREAD

**Issue by cpspyros** [GoogleContainerTools/skaffold#8399]
### Expected behavior
`.IMAGE_FULLY_QUALIFIED` should template the full path of the image built and tagged

### Actual behavior
Skaffold seems to tag the image properly but template the sha in helm.

### Information

- Skaffold version: 2.1.0
- Operating system: Ubuntu 22.04.1 LTS
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: osi
build:
  local:
    push: false
    concurrency: 3
    tryImportMissing: false
    useBuildkit: true
    useDockerCLI: false
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
      ignoreChanges: true
  artifacts:
    - image: my_image
      context: ./
      docker:
        dockerfile: checks/my_image/Dockerfile
        buildArgs:
          BUILDER_IMAGE: ubuntu:latest
          BASE_IMAGE: scratch
  
profiles:
  - name: my-profile
    deploy:
      helm:
        releases:
          - name: my-release
            namespace: my-namespace
            createNamespace: false
            skipBuildDependencies: false
            useHelmSecrets: false
            wait: false
            setValueTemplates:
              my_image.image: "{{.IMAGE_FULLY_QUALIFIED_my_image}}"
            valuesFiles:
              - "./helm/values.yaml"
            chartPath: ./helm
```

### Steps to reproduce the behavior

`skaffold run -f ./skaffold.yaml -p my-profile --default-repo <repoid>.dkr.ecr.eu-west-2.amazonaws.com --detect-minikube=false --digest-source=local`

Output:
```
Generating tags...                                                                                                                                                            
 - my_image -> <repoid>.dkr.ecr.eu-west-2.amazonaws.com/my_image:5c1f0a6                                                                                                  
Checking cache...                                                                                                                                                             
 - my_image: Found Locally                                                                                                                                                  
Tags used in deployment:                                                                                                                                                      
 - my_image -> <repoid>.dkr.ecr.eu-west-2.amazonaws.com/my_image:a89968170663548ced35404ddd185ce37bcd273e52e44cd650ffa2890001b394                                         
Starting deploy...                                                                                                                                                            
Hang tight while we grab the latest from your chart repositories...                                                                                                           
[...]
````

The tag to be used in the deployment looks like a sha (maybe?) if that's the case, since this tag has never been pushed the deployment can't pull the relevant image.
