### ISSUE TITLE
[Regression] `meta.namespace` added in manifests using kustomize renderer

### ISSUE THREAD

**Issue by renzodavid9** [GoogleContainerTools/skaffold#8403]
Skaffold v2 injects a `metadata.namespace` in the resulting manifests when using the `skaffold render` command in a project that uses the `kustomize` renderer.

### Expected behavior
The resulting output from `skaffold render` to not have any injected `metada.namespace`. Should keep the same behavior of Skaffold v1.

### Actual behavior
A `metadata.namespace` field is injected in the resulting output.

### Information

- Skaffold version: v2 @ HEAD
- Operating system: all
- Installed via: build from source code
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta2
kind: Config
manifests:
  kustomize:
    paths:
      - .
```

### Steps to reproduce the behavior

1. Use the `examples/kustomize` project in skaffold's repository. Go to that folder
2. Run `skaffold render`
3. You'll see in the resulting output a `metadata.namespace` injected:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kustomize-test
  name: kustomize-test
  namespace: fromflag
...
```
