### ISSUE TITLE
`skaffold delete` does not delete namespace when using createNamespace

### ISSUE THREAD

**Issue by davegallant** [GoogleContainerTools/skaffold#8405]
### Expected behavior

Skaffold should delete namespaces it creates with `createNamespace: true`.

### Actual behavior

When running `skaffold delete`, resources within the namespace are deleted, but the namespace is not.

### Information

- Skaffold version: v2.0.4
- Operating system: macOS 13.2
- Installed via: Nix
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: third-party
profiles:
- name: local
  deploy:
    kubeContext: kind-kind
  activation:
    - env: ENV=local
deploy:
  helm:
    releases:
    - name: external-secrets
      repo: https://charts.external-secrets.io
      remoteChart: external-secrets
      version: 0.5.9
      namespace: skaffold-delete-test
      createNamespace: true
      wait: true
      upgradeOnChange: true
```

### Steps to reproduce the behavior

1. `ENV=local skaffold run`
2. `ENV=local skaffold delete`
3. The namespace `skaffold-delete-test` still exists
