### ISSUE TITLE
jx-release-version support

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#841]
Feature request: Support using [jx-release-version](https://github.com/jenkins-x/jx-release-version) in the `tagPolicy` to set the docker image tag.

- Skaffold version: v0.10.0
- Operating system: Windows & Linux
- _Possible_ skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: myrepo.com/my-image
    docker:
      dockerfilePath: Dockerfile
    tagPolicy:
      # run following binary to get required tag version
      binary:
          jx-release-version
```
