### ISSUE TITLE
[Feature request] support for `--skip-refresh` when updating helm chart dependencies

### ISSUE THREAD

**Issue by muzalevs** [GoogleContainerTools/skaffold#8413]
In our project we use a separate Helm library chart for re-usable templates. Every other chart has it defined as a dependency, e.g.:

```yaml
dependencies:
  - name: template-lib
    version: 0.1.0
    repository: file://../template-lib
```

In many our charts it is the only dependency.  It enforces us to have `skipDependencyUpdate: false`, but also updates cache of remote helm repositories every time we run deploy, which sometimes is time-consuming.

We would like skaffold to be able to pass `--skip-refresh` option to the `helm dependency update` [command](https://helm.sh/docs/helm/helm_dependency_update/#options). This way it would be possible for users to skip refreshing cache of every repo from `helm repo list`.
