### ISSUE TITLE
Skaffold project with no deployers doesn't show any warning

### ISSUE THREAD

**Issue by renzodavid9** [GoogleContainerTools/skaffold#8424]
Currently, if we run, e.g, `skaffold dev` on a project that has no deployers configured, skaffold will show the following message: `Starting deploy...`, but doesn't warn that no deployers were found. This could be confusing for users, due to it doesn't show exactly what's hapenning. This is something that can happen in multi config/module projects.

### Expected behavior
To have a message that warn the user that no deployers were found in a project.

### Actual behavior
A `Starting deploy...` message is shown in the console, but no warning about no deployers found.

### Information

- Skaffold version: v2.1.0
- Operating system: all
- Installed via: Built from source code
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta2
kind: Config

requires:
  - path: module.yaml
```

- Content of `module.yaml`:
```yaml
apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: skaffold-example
manifests:
  rawYaml:
  - k8s-pod.yaml
```

### Steps to reproduce the behavior

1. Usinge the [examples/getting-started](https://github.com/GoogleContainerTools/skaffold/tree/main/examples/getting-started) project
2. Rename the `skaffold.yaml` file to `module.yaml`
3. Create a new `skaffold.yaml` file with the following content:
```yaml
apiVersion: skaffold/v4beta2
kind: Config

requires:
  - path: module.yaml
```
4. Run `skaffold dev`
5. It won't deploy anything, but also doesn't show any warn about it
