### ISSUE TITLE
Skaffold Helm Renderer Fails on Certain String Literals in Values

### ISSUE THREAD

**Issue by mike-capyh** [GoogleContainerTools/skaffold#8429]
### Expected behavior

As long as a string literal in values is fully escaped, it should be left untouched by skaffold.

### Actual behavior

String literals containing an exclamation mark are converted to empty strings by skaffold render.

This appears inconsistent with an equivalent helm template invocation, and interferes with values customization.

Of note, deleting the build stage in skaffold configuration appears to prevent the issue.

### Information

- Skaffold version: v2.1.0
- Operating system: Ubuntu 20.04.5 LTS
- Installed via: `https://storage.googleapis.com/skaffold/releases/`
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta2                                                    
kind: Config                                                                    
metadata:                                                                       
  name: skaffold-helm-bug-exclamationmark                                       
build:                                                                          
  artifacts:                                                                    
  - image: busybox                                                              
    docker:                                                                     
      dockerfile: Dockerfile                                                    
deploy:                                                                         
  helm:                                                                         
    releases:                                                                   
    - name: test                                                                
      chartPath: test                                                           
      valuesFiles:                                                              
      - test/values.yaml                                                        
      version: 0.1.0 
```

### Steps to reproduce the behavior
Assuming a compatible nix system, the following command lines are a minimal repro:

```bash
skaffold version
echo 'Tested with: v2.1.0'

REPRO_DIR=~/temp/skaffold-helm-exclamationmark-repro
mkdir -p $REPRO_DIR && pushd $REPRO_DIR

helm create test
echo 'testValue: "!exclamationMarkInStringLiteral"' >> test/values.yaml

echo 'FROM busybox:latest' > Dockerfile

cat > ./skaffold.yaml <<EOF
apiVersion: skaffold/v4beta2                                                    
kind: Config                                                                    
metadata:                                                                       
  name: skaffold-helm-bug-exclamationmark                                       
build:                                                                          
  artifacts:                                                                    
  - image: busybox                                                              
    docker:                                                                     
      dockerfile: Dockerfile                                                    
deploy:                                                                         
  helm:                                                                         
    releases:                                                                   
    - name: test                                                                
      chartPath: test                                                           
      valuesFiles:                                                              
      - test/values.yaml                                                        
      version: 0.1.0 
EOF

cat > test/templates/config.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  test-value: {{ .Values.testValue }}
EOF

echo 'Expected:  both output: test-value: !exclamationMarkInStringLiteral'
echo 'However, only helm does so, skaffold spits out "":'
helm template test ./test --values ./test/values.yaml |
  grep 'test-value'

skaffold render |
  grep 'test-value'

echo 'Note: commenting/deleting build section of skaffold.yaml fixes the inconsistency.'
```

### Some Speculation

My current best guess is that, since skaffold takes the standard output of `helm template` as-is:

- `helm template` output does not include the quotes, so the `!` is no longer escaped
- if skaffold uses that buffer as-is with no further processing, it dodges the bullet.
- if skaffold attempts to re-parse that buffer as yaml, it runs afoul of the `!` not being escaped and thus being treated as a yaml tag marker.

(However, I am new to skaffold, and have not attempted to confirm this guess)

If this guess is correct, then a further question is, is this a bug in helm or in skaffold?  If `helm template` is expected to output re-parse-able yaml, then it probably should be outputting these strings escaped.
