### ISSUE TITLE
skaffold build with gradle jib works locally but not in github actions workflow

### ISSUE THREAD

**Issue by tobias-neubert** [GoogleContainerTools/skaffold#8440]
### Expected behavior
I can execute skaffold build for my gradle project and the jib plugin successfull locally. It builds the image and pushes it to my github container registry (ghcr). I am executing it locally like so:

If I execute it in a github actions workflow it builds and pushes the images successfully as well, gradle reports success, but afterwards "someone" tries to get the image and github workflow tells me that it is not authorized, which leads to a failed build.

I really don't know what I should change or if this a problem of github actions or of skaffold. If this is the wrong place to ask for, excuse me please. But if someone can help I would be thankful.

### Information

- Skaffold version: 2.1.0
- Operating system: ubuntu 22.04
- Contents of skaffold.yaml:

#### skaffold.yaml:
```yaml
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: motd-service
build:
  artifacts:
    - image: ghcr.io/tobias-neubert/motd-service
      jib: {}
manifests:
  rawYaml:
    - cluster/k8s/mtls.yaml
    - k8s/tls.yaml
    - k8s/deployment.yaml
    - k8s/istio.yaml
```
#### github-workflow.yaml
```
name: Motd Service
run-name: build motd-service

on:
  push:

permissions:
  packages: write

env:
  GH_PASSWORD: '${{ secrets.GITHUB_TOKEN }}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

      - name: Deactivate collecting skaffold metrics
        run: skaffold config set --global collect-metrics false

      - name: Build the motd image
        run: skaffold build
```

#### build.gradle
```
buildscript {
  repositories {
    mavenCentral()
  }
}

plugins {
  id 'java'
  id 'idea'
  id 'org.springframework.boot' version '3.0.1'
  id 'com.google.cloud.tools.jib' version '3.3.1'
  id 'io.spring.dependency-management' version '1.1.0'
}

ext {
  // adding timestamp of build to project properties (displayed within spring boot banner)
  timestampOfBuild = new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
  yearOfBuild = new Date().format("yyyy")
  if (project.hasProperty('githubPassword')) {
    githubPassword = project.property('githubPassword')
  } else {
    githubPassword = "$System.env.GH_PASSWORD"
  }
}

repositories {
  mavenCentral()
}

group = "com.neubert.skaffold"
version = "0.0.1"

java {
  sourceCompatibility = JavaVersion.VERSION_17
  targetCompatibility = JavaVersion.VERSION_17
}

compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

configurations {
  published
  compileOnly {
    extendsFrom annotationProcessor
  }
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-web'
  annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
  testImplementation 'org.springframework.boot:spring-boot-starter-test'

  testImplementation('org.assertj:assertj-core')
  testImplementation('org.junit.jupiter:junit-jupiter-api')
  testRuntimeOnly('org.junit.jupiter:junit-jupiter-engine')
}


tasks.withType(Test) {
  useJUnitPlatform()
}

springBoot {
  buildInfo()
}

bootJar {
  enabled = false
}

jar {
  enabled = true
}

def baseImage = 'ghcr.io/tobias-neubert/eclipse-temurin:17.0.2_8-jre'
jib {
  from {
    image = baseImage
    auth {
      username = "_"
      password = githubPassword
    }
  }
  to {
    image = 'ghcr.io/tobias-neubert/motd-service'
    auth {
      username = "_"
      password = githubPassword
    }
  }
  container {
    mainClass = 'com.neubert.scaffold.motdservice.MotdServiceApplication'
    ports = ['8080']
  }
}
```

### Skaffold/Github Workflow output
```
Run skaffold build  --skip-tests=true  --wait-for-connection=true
  
Generating tags...
 - ghcr.io/tobias-neubert/motd-service -> ghcr.io/tobias-neubert/motd-service:b98be44-dirty
Checking cache...
 - ghcr.io/tobias-neubert/motd-service: Not found. Building
Starting build...
Building [ghcr.io/tobias-neubert/motd-service]...
Welcome to Gradle 7.4!
Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains
For more details see https://docs.gradle.org/7.4/release-notes.html
> Task :_skaffoldFailIfJibOutOfDate
> Task :bootBuildInfo
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :jib
Containerizing application to ghcr.io/tobias-neubert/motd-service:b98be44-dirty...
Base image 'ghcr.io/tobias-neubert/eclipse-temurin:17.0.2_8-jre' does not use a specific image digest - build may not be reproducible
Using credentials from to.auth for ghcr.io/tobias-neubert/motd-service:b98be44-dirty
Getting manifest for base image ghcr.io/tobias-neubert/eclipse-temurin:17.0.2_8-jre...
Building dependencies layer...
Building resources layer...
Building classes layer...
Building jvm arg files layer...
The base image requires auth. Trying again for ghcr.io/tobias-neubert/eclipse-temurin:17.0.2_8-jre...
Using credentials from from.auth for ghcr.io/tobias-neubert/eclipse-temurin:17.0.2_8-jre
Using base image with digest: sha256:cb3d05d72a5f2c7782a87ebdb2f1a5b8bad46998f51a50611aad0deed2096718
Container entrypoint set to [java, -cp, @/app/jib-classpath-file, com.neubert.scaffold.motdservice.MotdServiceApplication]
Built and pushed image as ghcr.io/tobias-neubert/motd-service:b98be44-dirty
BUILD SUCCESSFUL in 13s
4 actionable tasks: 4 executed
time="2023-02-15T18:00:18Z" level=error msg="No matching credentials were found for \"ghcr.io\""
time="2023-02-15T18:00:19Z" level=error msg="No matching credentials were found for \"ghcr.io\""
getting image: GET https://ghcr.io/token?scope=repository%3Atobias-neubert%2Fmotd-service%3Apull&service=ghcr.io: UNAUTHORIZED: authentication required
Error: Process completed with exit code 1.
```
