### ISSUE TITLE
Not able to reference secrets path to home folder

### ISSUE THREAD

**Issue by griseau** [GoogleContainerTools/skaffold#8453]
### Expected behavior
I want to reference a secret file in `build.artifacts.docker.secret.src` in the home directory. This works well if using the realpath but not ~.
### Actual behavior
Using the realpath /home/username/.npmrc works, but using ~/.npmrc doesn't work because skaffold is appending ~/.npmrc to the actual working directory making it search to the wrong place.
I also tried to reference the home directory using $HOME env variable, but it's not a templated field, so doesn't work
### Information

- Skaffold version:  skaffold 2.1.0
- Operating system:  MacOS Ventura 13
- Installed via:  brew
- Contents of skaffold.yaml:

```yaml
build:
  local:
    useBuildkit: true
  artifacts:
  - image: image-name
    context: .
    docker:
      secrets:
        - id:   npmrc
          src: ~/.npmrc
```
