### ISSUE TITLE
`"{{.IMAGE_NAME}}"` is not dynamic per each deployment

### ISSUE THREAD

**Issue by zeyaddeeb** [GoogleContainerTools/skaffold#8471]
### Expected behavior
When using multiple skaffold files `"{{.IMAGE_NAME}}"` all the deployments get the same name even though they are different

### Actual behavior

All deployments get the same name which is incorrect

### Information

- Skaffold version: v2.0.2
- Operating system: 
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml

---
apiVersion: skaffold/v3alpha1
kind: Config
requires:
  - path: ./shared
  - ...
--
...
  - name: dev
    activation:
      - kubeContext: kind-local-dev
    build:
      artifacts:
        - image: api1
          context: api1

    deploy:
      helm:
          - name: api1
            chartPath: deployments/helm/api1
            setValueTemplates:
              image.repository: "{{.IMAGE_NAME}}"
              image.tag: "{{.IMAGE_TAG}}"
---
...
  - name: dev
    activation:
      - kubeContext: kind-local-dev
    build:
      artifacts:
        - image: api2
          context: api2

    deploy:
      helm:
          - name: api2
            chartPath: deployments/helm/api2
            setValueTemplates:
              image.repository: "{{.IMAGE_NAME}}"
              image.tag: "{{.IMAGE_TAG}}"

```

### Steps to reproduce the behavior
1- create a monorepo with multiple skaffold files (different builds different deployments)
2- create a root `skaffold.yml` to reference subprojects
3- all deployments get same  `"{{.IMAGE_NAME}}"` which is incorrect
