### ISSUE TITLE
Support BuildKit in Docker 18.06.0-ce

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#848]
### Actual behavior

I'm trying to use the new BuildKit support in Docker 18.06.0-ce but hit the following issue
```
export DOCKER_BUILDKIT=1
skaffold-windows-amd64.exe build

Starting build...
Building [repo.mycompany.com/my-app]...
2018/07/23 15:40:39 No matching credentials found for index.docker.io, falling back on anonymous
Sending build context to Docker daemon  30.36MB
FATA[0005] build step: building [repo.mycompany.com/my-app]: build artifact: running build: docker build: Error response from daemon: Dockerfile parse error line 7: Unknown flag: mount
```

My Dockerfile is using runmount
```
# syntax = tonistiigi/dockerfile:runmount20180618
FROM maven:3-jdk-8-alpine AS BUILD

# build
ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
COPY . .
RUN --mount=target=/root/.m2,type=cache mvn -B clean package
```

### Information

- Skaffold version: v0.10.0
- Operating system: Windows 10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: repo.mycompany.com/my-app
    docker:
      dockerfilePath: Dockerfile
  tagPolicy:
    envTemplate:
         template: "{{.IMAGE_NAME}}:latest"
  local:
    skipPush: false          
deploy:
  helm:
    releases:
    - name: my-app
      chartPath: helm
      wait: true
      namespace: default
      version: ""
```

### Steps to reproduce the behavior

1. `DOCKER_BUILDKIT=1 DOCKER_BUILDKIT=1 skaffold-windows-amd64.exe build`
