### ISSUE TITLE
skaffold not creating namespace for helm release

### ISSUE THREAD

**Issue by mm-fsai** [GoogleContainerTools/skaffold#8515]
### Expected behavior
Redis deploy successfully

### Actual behavior
```
Error from server (NotFound): error when creating "STDIN": namespaces "redis" not found
```

Works if I create the namespace manually.

### Information

- Skaffold version: 2.2.0
- Operating system: Mac Monterey 12.4
- Installed via: Homebrew
- Contents of skaffold.yaml:

### Steps to reproduce the behavior

`skaffold dev`

```yml
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: redis
manifests:
  helm:
    releases:
    - name: redis
      createNamespace: true
      repo: https://charts.bitnami.com/bitnami 
      remoteChart: redis
      namespace: redis

profiles:
  - name: dev
    activation:
      - command: dev
```

**Comment by aaron-prindle** [comment]
Thanks for flagging this @mm-fsai.  This is an issue with Skaffold, the `manifests.helm.releases[].createNamespace` field should not actually exist (created #8533 tracking removing it) and instead `deploy.helm.releases[].createNamespace` .  In you case I believe something like:

```
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: redis
deploy:
  helm:
    releases:
    - name: redis
      createNamespace: true
      repo: https://charts.bitnami.com/bitnami 
      remoteChart: redis
      namespace: redis

profiles:
  - name: dev
    activation:
      - command: dev
```
should work here

**Comment by krumware** [comment]
For other's landing here. I was also facing this issue, alongside one where the helm chart's kubeVersion check was reflecting a different helm version than what was actually running on the cluster.

**Comment by ericzzzzzzz** [comment]
The difference is in the doc, 
``In Skaffold v2 the primary difference between the helm renderer (manifest.helm.*) and the helm deployer (deploy.helm.*) is the use of helm template vs helm install``

more info can be found here. https://skaffold.dev/docs/deployers/helm/

**Comment by AndreasBergmeier6176** [comment]
I am using `deploy.helm.releases.createNamespace` but am getting the same error

**Comment by Richard87** [comment]
Hi, I'm also getting this error, just upgraded from 1.39.4 to 2.6.0 and got this error:
```
Helm release eportal not installed. Installing...
Error: INSTALLATION FAILED: create: failed to create: namespaces "staging-224" not found
```

**Comment by jagathprakash** [comment]
assign @jagathprakash

**Comment by pydolan** [comment]
The above suggested fix works for me for OP's original config, but I switched to the latest API version (`skaffold/v4beta7`) and am using v2.8.0 of the CLI app (on minikube):

```yaml
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: redis
deploy:
  helm:
    releases:
      - name: redis
        createNamespace: true
        repo: https://charts.bitnami.com/bitnami
        remoteChart: redis
        namespace: redis

profiles:
  - name: dev
    activation:
      - command: dev
```

For those still having the error, ensure you're including `createNamespace` and share your full yaml config
