### ISSUE TITLE
Cannot reapply `Job` type resource using `skaffold apply`

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#8544]
### Expected behavior
Skaffold can reapply `Job` type resource

### Actual behavior
Skaffold fails to reapply `Job` type resources
### Information

- Skaffold version: wait for https://github.com/GoogleContainerTools/skaffold/pull/8543 to merge, or build from that branch
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta3
kind: Config
manifests:
  helm:
    releases:
    - name: agones
      repo: https://agones.dev/chart/stable/
      remoteChart: agones
      namespace: agones-system
      createNamespace: true
deploy:
  kubectl:
    flags:
      apply: ['--server-side']
```

### Steps to reproduce the behavior

1. with above `skaffold.yaml` file run:
   ```
   skaffold render --output=render.yaml
   ```
2. The rendered manifest has a Job type resource
3. Now run: 
    ```
    skaffold apply render.yaml
    ```
    The resources should get applied correctly.  
5. Now run step 4 again. This time the deployment will fail with an error like:
    ```
     The Job "agones-delete-agones-resources" is invalid:  ... field is immutable
    ```
