### ISSUE TITLE
Manifests.transform rendering failing in gcr.io/k8s-skaffold/skaffold:v2.2.0 image with exit status 1

### ISSUE THREAD

**Issue by aablsk** [GoogleContainerTools/skaffold#8579]
**Disclaimer: This might be the same issue as https://github.com/GoogleContainerTools/skaffold/issues/8578** 

### Expected behavior
When running `skaffold render -a artifacts.json` with manifests.transform configuration in the gcr.io/k8s-skaffold/skaffold:v2.2.0 container image, rendering succeeds.

### Actual behavior
When running `skaffold render -a artifacts.json` with manifests.transform configuration in the gcr.io/k8s-skaffold/skaffold:v2.2.0 container image, rendering fails with the following output:
```
exit status 1
```

### Information

- Skaffold version: v2.2.0
- Operating system: Linux
- Installed via: official images for [skaffold](gcr.io/k8s-skaffold/skaffold:v2.2.0), [Cloud Deploy](us-central1-docker.pkg.dev/cd-image-prod/cd-image/cd@sha256:b8473dd92df8130a8833ca0aa00585c42682076f367f44b0972a518a9dc110ae)
- Contents of [skaffold.yaml](https://github.com/aablsk/skaffold-clouddeploy-test/blob/main/modules/manifests-transform/skaffold.yaml):

```yaml
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: manifests-transform
requires:
  - configs:
    - namespace
    path: ../../shared/namespace/skaffold.yaml
manifests:
  rawYaml:
    - k8s/base/*
  transform:
    - name: set-labels
      configMap:
        - "app:manifests-transform"
    - name: create-setters
      configMap:
        - "name:kustomize"
    - name: apply-setters
      configMap:
        - "name:manifests-transform"
  validate:
   - name: kubeval
  output: render/result.yaml # TODO: create bug - this does nothing
test:
  - image: hello
    custom:
    - command: /bin/bash -c "echo Testing module manifests-transform && diff golden_render.yaml <(skaffold render -a ../../artifacts.json)" 
verify:
- name: verify-manifests-transform
  container:
    name: verify-http-status-200-manifests-transform
    image: google/cloud-sdk:latest
    command: ["bin/bash"]
    args: ["-c", "gcloud container fleet memberships get-credentials gke-membership && if [[ $(curl http://$(kubectl get service manifests-transform -n skaffold-clouddeploy-test -o jsonpath='{.status.loadBalancer.ingress[0].ip}') --write-out '%{http_code}'  --silent --head --output /dev/null) -ne '200' ]]; then exit 1; fi"]

```

### Steps to reproduce the behavior

1. `git clone https://github.com/aablsk/skaffold-clouddeploy-test && cd skaffold-clouddeploy-test`
2. Run skaffold render for the `manifests-transform` module in the container. From repository root run: `docker run -v $(pwd):/skaffold -v/var/run/docker.sock:/var/run/docker.sock gcr.io/k8s-skaffold/skaffold:v2.2.0 /bin/bash -c "cd /skaffold/modules/manifests-transform && skaffold render -a ../../artifacts.json -vdebug"`

```
$ docker run -v $(pwd):/skaffold -v/var/run/docker.sock:/var/run/docker.sock gcr.io/k8s-skaffold/skaffold:v2.2.0 /bin/bash -c "cd /skaffold/modules/manifests-transform && skaffold render -a ../../artifacts.json -vdebug"
time="2023-03-24T09:33:21Z" level=debug msg="skaffold API not starting as it's not requested" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=info msg="Skaffold &{Version:v2.2.0 ConfigVersion:skaffold/v4beta3 GitVersion: GitCommit:bfc52e41ca7fbeac8a9f1da681118d14e197d6d4 BuildDate:2023-03-06T21:26:17Z GoVersion:go1.19.2 Compiler:gc Platform:linux/amd64 User:}" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="Disable housekeeping messages for command explicitly" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="config version out of date: upgrading to latest \"skaffold/v4beta3\"" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="parsed 1 configs from configuration file /skaffold/modules/manifests-transform/skaffold.yaml" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="Defaulting build type to local build" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="config version out of date: upgrading to latest \"skaffold/v4beta3\"" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="parsed 1 configs from configuration file /skaffold/shared/namespace/skaffold.yaml" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="Defaulting build type to local build" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=info msg="Using kubectl context: " subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=info msg="Loaded Skaffold defaults from \"/root/.skaffold/config\"" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="getting client config for kubeContext: ``" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="no kube-context set and no kubeConfig found, attempting in-cluster config" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="Running command: [minikube version --output=json]" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="setting Docker user agent to skaffold-v2.2.0" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="push value not present in isImageLocal(), defaulting to true because cluster.PushImages is true" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=info msg="no kpt renderer or deployer found, skipping hydrated-dir creation" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="Running command: [kubectl config view --minify -o jsonpath='{..namespace}']" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="CLI platforms provided: \"\"" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="platform detection from active kubernetes cluster is not enabled" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="Using builder: local" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="push value not present in NewBuilder, defaulting to true because cluster.PushImages is true" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="Using builder: local" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=debug msg="push value not present in NewBuilder, defaulting to true because cluster.PushImages is true" subtask=-1 task=DevLoop
time="2023-03-24T09:33:21Z" level=info msg="build concurrency set to default value of -1" subtask=-1 task=DevLoop
time="2023-03-24T09:33:23Z" level=info msg="Starting render..." subtask=-1 task=DevLoop
time="2023-03-24T09:33:23Z" level=info msg="starting render process" subtask=0 task=Render
time="2023-03-24T09:33:23Z" level=debug msg="Executing template &{envTemplate 0xc0006c0b40 0xc0009000f0  } with environment map[DEBIAN_FRONTEND:noninteractive HOME:/root HOSTNAME:0534b2c66af4 OLDPWD:/skaffold PATH:/usr/local/go/bin:/root/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/google-cloud-sdk/bin PWD:/skaffold/modules/manifests-transform SHLVL:0 _:/usr/bin/skaffold]" subtask=-1 task=DevLoop
time="2023-03-24T09:33:23Z" level=debug msg="image [hello] is not used by the current deployment" subtask=-1 task=DevLoop
time="2023-03-24T09:33:23Z" level=debug msg="manifests with tagged images:apiVersion: v1\nkind: Namespace\nmetadata:\n  name: skaffold-clouddeploy-test" subtask=0 task=Render
time="2023-03-24T09:33:23Z" level=debug msg="manifests set with namespace apiVersion: v1\nkind: Namespace\nmetadata:\n  name: skaffold-clouddeploy-test" subtask=-1 task=DevLoop
time="2023-03-24T09:33:23Z" level=info msg="starting render process" subtask=1 task=Render
time="2023-03-24T09:33:23Z" level=debug msg="Executing template &{envTemplate 0xc0001b6a20 0xc000900230  } with environment map[DEBIAN_FRONTEND:noninteractive HOME:/root HOSTNAME:0534b2c66af4 OLDPWD:/skaffold PATH:/usr/local/go/bin:/root/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/google-cloud-sdk/bin PWD:/skaffold/modules/manifests-transform SHLVL:0 _:/usr/bin/skaffold]" subtask=-1 task=DevLoop
time="2023-03-24T09:33:23Z" level=debug msg="Running command: [tput colors]" subtask=-1 task=DevLoop
time="2023-03-24T09:33:23Z" level=debug msg="error checking for color support: checking terminal colors: running [tput colors]\n - stdout: \"\"\n - stderr: \"tput: No value for $TERM and no -T specified\\n\"\n - cause: exit status 2" subtask=-1 task=DevLoop
exit status 1
```
