### ISSUE TITLE
profile activation based in many env variables

### ISSUE THREAD

**Issue by FernandoArteaga** [GoogleContainerTools/skaffold#8589]
More than an issue this is a request 🙂 

It is possible to provide more than one `ENV` variable for activating a profile?

### Expected behavior

Being able of providing a list of `env` variables for matching the activation. Could also be really nice to handle `&&` or `||`, but starting with `&&` will be super awesome.

```yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: bananas
profiles:
  - name: gcp_test
    activation:
      - env: 
        - ENV=test
        - PROVIDER=gcp
  - name: aws_test
    activation:
      - env: 
        - ENV=test
        - PROVIDER=aws
```

### Actual behavior

The activation profile only allows one variable at the time

### Information

- Skaffold version: `2.2.0` 
- Operating system: macOS(M1) 
- Installed via: Homebrew
