### ISSUE TITLE
Hash/dependency check of multi-stage `Dockerfile` fails if unused stage references files/folders that do not exist

### ISSUE THREAD

**Issue by mattupstate** [GoogleContainerTools/skaffold#8608]
### Expected behavior

Unreferenced Dockerfile stages to be excluded from hash/dependency check.

### Actual behavior

Skaffold appears to do some check against the whole `Dockerfile` despite a stage not being built.

### Information

- Skaffold version: 
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

Create a `Dockerfile` with a stage that is not built by Skaffold, pseudo code:

```
FROM ubuntu as base

FROM base as dev
# should be skipped over by build
COPY ./local_dir_that_does_not_exist ./

FROM base
# What skaffold should build without a `target` specified
```

Reference the `Dockerfile` in skaffold `build` section without specifying `target`:

```
build:
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    concurrency: 2
  artifacts:
    - image: ghcr.io/<redacted>
      context: <redacted>
      docker:
        dockerfile: Dockerfile

Run `skaffold dev`:

```
$ skaffold dev
Generating tags...
 - ghcr.io/<redacted> -> ghcr.io/<redacted>:ef6b868
Checking cache...
 - ghcr.io/<redacted>: Error checking cache.
Cleaning up...
Error: uninstall: Release not loaded: <redacted>: release: not found
Cleaning up resources encountered an error, will continue to clean up other resources.
getting hash for artifact "ghcr.io/<redacted>": getting dependencies for "ghcr.io/<redacted>": file pattern [./local_dir_that_does_not_exist] must match at least one file
```
