### ISSUE TITLE
Support templating in the `chartPath` field

### ISSUE THREAD

**Issue by aniskhan001** [GoogleContainerTools/skaffold#8626]
It would be very nice to have templating support in the `chartPath` field.

## Use case
I have a repo containing multiple projects which need to render separately.
Separate render is important here because I'm trying to the rendered manifests for different ArgoCD Applications.
Using a matrix in GitHub Action gives me the flexibility of changing the name of each project.

Here is an example pipeline in GitHub Action:
```yaml
name: 'GitOps'
on:
  push:
    branches:
      - 'my-branch'

jobs:
  skaffold-gitops:
    name: 'GitOps'
    runs-on: ['ubuntu-latest']

    strategy:
      matrix:
        app-name:
          - 'app-name-1'
          - 'app-name-2'
          - 'app-name-3'

    steps:
      - name: 'Checkout'
        id: 'checkout'
        uses: 'actions/checkout@3.0.0'

      - name: 'Render Manifests'
        uses: 'example-workflow-skaffold@1.0.0'
        env:
          PROJECT_NAME: ${{ matrix.app-name }}
```

And in the Skaffold config file, I would like to use that `PROJECT_NAME` so that I don't have to keep multiple files for each project.

```yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: {{.PROJECT_NAME}}

manifests:
  helm:
    releases:
      - name: {{.PROJECT_NAME}}
        # chartPath does not support templating at the moment, sadly 😢
        chartPath: kubernetes/helm/charts/{{.PROJECT_NAME}}
        valuesFiles:
          - kubernetes/helm/values/values-global.yaml
```

### Steps to reproduce the behavior

Right now, if I run `skaffold render` command with above configuration, it would give me the following error:

```bash
std out err: %!(EXTRA *errors.errorString=Error: repo kubernetes not found
exit status 1
)
```

### Information

- Skaffold version: v2.3.0
- Operating system: macOS 13.3
- Installed via: Homebrew
