### ISSUE TITLE
Kaniko build hangs waiting for a long-running build that has already finished and pushed the image

### ISSUE THREAD

**Issue by mikedld** [GoogleContainerTools/skaffold#8658]
### Expected behavior

Cluster (kaniko) build succeeds regardless of how long it takes.

### Actual behavior

If build takes considerable time (in my case, more than 35-55 minutes), skaffold hangs after completing and pushing an image.

### Information

- Skaffold version: 2.3.0, 2.1.0, 1.39.7
- Operating system: alpine:3.17 (amd64)
- Installed via: downloaded from storage.googleapis.com as indicated in GH release description
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta20
kind: Config
build:
  cluster:
    namespace: foobar-ns
    serviceAccount: foobar-sa
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits: {}
    concurrency: 1
    timeout: 40m
  artifacts:
    - image: foobar
      context: foobar-dir
      kaniko:
        logFormat: text
        logTimestamp: true
        verbosity: debug
  tagPolicy:
    sha256: {}
```

- Kubernetes version: 1.23 (AWS EKS)
- Kaniko version: 1.9.2, 1.8.1, 1.7.0
- Contents of foobar-dir/Dockerfile:

```dockerfile
FROM alpine:3.17
RUN sleep $(( 38 * 60 ))
```

### Steps to reproduce the behavior

1. run build in Jenkins, K8s plugin spins up the pod (definition in log attached) with container that has skaffold preinstalled
2. `skaffold --interactive=false --verbosity=debug build --default-repo=000000000000.dkr.ecr.eu-west-1.amazonaws.com`

While trying to troubleshoot, I've cloned the repo, added some logging (patch attached), and built it myself, hence the version in the log doesn't match 2.3.0 release but current `main`. The log shows that at some point (before the image is built and before the cluster timeout is reached) the pods watcher starts to report events with empty type and nil object in a tight loop, no pod termination event is ever reported.

I've adjusted the cluster timeout for this report so that it comes 2 minutes after sleep ends in Dockerfile, to reduce the log size, otherwise Jenkins kills the build. Increasing the cluster timeout doesn't help, I once waited for 4 hours and nothing happened, it was still there waiting after the "Pushed \<image>" message.

Increasing cluster resource requests (for kaniko pod) doesn't help, I tried with 3000m and 8Gi. EKS nodes are r5.xlarge and were idling during the test.

Files:
* [jenkins-log.txt](https://github.com/GoogleContainerTools/skaffold/files/11183443/jenkins-log.txt)
* [skaffold-hang.patch](https://github.com/GoogleContainerTools/skaffold/files/11183124/skaffold-hang.patch)
