### ISSUE TITLE
Annotating service account with special chars

### ISSUE THREAD

**Issue by tonsV2** [GoogleContainerTools/skaffold#8679]
### Expected behavior

Deploy the service account with the given annotation

### Actual behavior

    Error: UPGRADE FAILED: YAML parse error on whoami-go/templates/serviceaccount.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field .metadata.annotations of type string

### Information

Please note that I'm actually listing the `serviceAccount` etc. under `setValueTemplates` because I want to interpolate an environment variable into the string as well. Eventually I want to annotate with something like the below but for the sake of simplifying things I left that out. I also tried both with and without quoting the string.

    "eks.amazonaws.com/role-arn": "arn:aws:iam::767224633206:role/whatever-{{ .ENVIRONMENT }}"

- Skaffold version: v2.3.1
- Operating system: Linux, Fedora, 37
- Installed via: curl
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: tons/whoami-go
  tagPolicy:
    inputDigest: { }
deploy:
  helm:
    releases:
      - name: whoami-go
        namespace: whoami
        createNamespace: true
        chartPath: helm
        setValueTemplates:
          repository:
            image: tons/whoami-go
          serviceAccount:
            annotations:
              "eks.amazonaws.com/role-arn": "arn:aws:iam::767224633206:role/whatever"
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
https://github.com/tonsV2/whoami-go/tree/bug/skaffold

2. `skaffold dev`

3. See the error
