### ISSUE TITLE
`skaffold verify` if used with `--rpc-port=... & --event-log-file=...` seems to have issues (can cause hanging)

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8683]
Issue tracks bug where `skaffold verify` if used with `--rpc-port=0 --event-log-file=/workspace/verify/skaffold-event-logs.txt --docker-network=cloudbuild` seems to have issues (can cause hanging).  

Repro:
```
apiVersion: skaffold/v4beta4
kind: Config
manifests:
  rawYaml:
  - deployment.yaml
  - service.yaml
deploy:
  kubectl:
    flags:
      global:
      - --namespace=trying
verify:
- name: verify-name
  container:
    name: connect-with-service
    image: curlimages/curl
    command: ["/bin/sh"]
    args: ["-c", "curl http://test-name-service"]
  executionMode:
    kubernetesCluster:
      jobManifestPath: nested/jobManifest.yaml
      overrides: '{"metadata": {"namespace" : "trying"}}'
```

Command:
```
$ skaffold verify --rpc-port=0 --event-log-file=/workspace/verify/skaffold-event-logs.txt --docker-network=cloudbuild
```

Output:
```
aprindle@aprindle-ssd ~/darien-issue-v2 skaffold verify --rpc-port=0 --event-log-file=/workspace/verify/skaffold-event-logs.txt --docker-network=cloudbuild
Tags used in verification
# ... <-- hangs 
```
