### ISSUE TITLE
skaffold with requires fails to deploy with error `nothing to deploy`

### ISSUE THREAD

**Issue by agoru** [GoogleContainerTools/skaffold#8745]
I am trying to deploy a mesh of services using a top level skaffold project with `requires` referring to local projects which have their own skaffold. The individual subprojects work fine independently, but at top level mesh project level, I can build but not deploy

Oddly `skaffold render` works fine and it produces the same output at mesh level and individual project level,  but `skaffold run`  fails at mesh level with error `nothing to deploy`  (Command output: [256])

Mesh skaffold

```
❯ cd /projects/mesh
❯ cat skaffold.yaml 
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: mesh
requires:
  - configs: ["service1"]
    path: ../service1/skaffold.yaml
deploy:
  kubectl: {}
```

Service1 skaffold

```
❯ cd /projects/service1
❯ cat skaffold.yaml 
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: service1
build:
  artifacts:
    - image: service1
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - kubernetes.yaml
```

### Expected behavior

```
❯ cd /projects/mesh
❯ skaffold run
Generating tags...
 - service1 -> service1:89e747d-dirty
Checking cache...
 - service1: Found Locally
Starting test...
Tags used in deployment:
 - service1 -> service1:f9ed68a04f60f38dbc3651f80af4a9e55d12a92b97d9ab4e1b5abf9b81c02916
Starting deploy...
 - deployment.apps/service1 created
 - service/service1 created
Waiting for deployments to stabilize...
 - deployment/service1 is ready.
Deployments stabilized in 2.307 seconds
```

`skaffold run` fine from within service1, I would expect the same happening from within mesh project, but instead I get an error.

### Actual behavior

```
❯ cd /projects/mesh
❯ skaffold run
Generating tags...
 - service1 -> service1:89e747d-dirty
Checking cache...
 - service1: Found Locally
Starting test...
Tags used in deployment:
 - service1 -> service1:f9ed68a04f60f38dbc3651f80af4a9e55d12a92b97d9ab4e1b5abf9b81c02916
Starting deploy...
nothing to deploy
```

### Information

- Skaffold version: v2.3.1
- Operating system: ubuntu 23.04
- Installed via: https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: mesh
requires:
  - configs: ["service1"]
    path: ../service1/skaffold.yaml
deploy:
  kubectl: {}
```

### Steps to reproduce the behavior

1. see above for top level and subproject skaffolds
2.  `skaffold run`

```
Starting deploy...
DEBU[0002] getting client config for kubeContext: `minikube`  subtask=-1 task=DevLoop
DEBU[0002] Running command: [tput colors]                subtask=-1 task=DevLoop
DEBU[0002] Command output: [256
]                        subtask=-1 task=DevLoop
nothing to deploy
DEBU[0002] exporting metrics   
```

As mentioned above, `skaffold render` generates output fine
