### ISSUE TITLE
Skaffold failing to track pod running in fargate

### ISSUE THREAD

**Issue by gilqubex** [GoogleContainerTools/skaffold#8753]
### Expected behavior

successful helm install of a given deployment

### Actual behavior

while the helm command succeeds and the pod is okay, skaffold thinks it isn't and faults the deployment.

### Information

- Skaffold version: v2.4.0
- Operating system: MacOS Ventura
- Installed via: Google Cloud SDK 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: redacted
build:
  platforms: ["linux/amd64"]
  artifacts:
    - image: redacted
      context: .
      docker:
        dockerfile: Dockerfiles/redacted/redacted.dockerfile
deploy:
  helm:
    releases:
    - name: redacted
      namespace: redacted
      chartPath: helm/redacted
      setValueTemplates:
        image.repository: "{{.IMAGE_REPO_redacted}}"
        image.tag: "{{.IMAGE_TAG_redacted}}@{{.IMAGE_DIGEST_redacted}}"
      setValues:
        image.pullPolicy: "IfNotPresent"
```

### Steps to reproduce the behavior

1. set up an EKS cluster running on fargate-only. this can be done using the aws terraform eks module and appropriate configuration. In particular, coredns needs its computeType set to 'fargate' or removed.
2. try to deploy chart above (sorry, but it's private code. I hope this reproduces with non-private code as well)

### Further notes:

So, I ran skaffold dev with trace verbosity and ran the helm command running behind the scenes manually. this resulted in a perfectly working deployment with no errors. Also, for bad runs, kubectl get events does not show any failure of note.
Skaffold trace logging shows the following:

DEBU[0019] Running command: [kubectl --context redacted rollout status deployment redacted --namespace redacted --watch=false]  subtask=0 task=Deploy
DEBU[0021] Command output: [Waiting for deployment "redacted" rollout to finish: 0 of 1 updated replicas are available...
]  subtask=0 task=Deploy
DEBU[0021] getting client config for kubeContext: ``     subtask=-1 task=DevLoop
DEBU[0022] Unable to determine current service state of pod "redacted-XXXXX-YYYYY"  subtask=-1 task=DevLoop
DEBU[0022] Fetching events for pod "redacted-XXXXX-YYYYY"  subtask=-1 task=DevLoop
DEBU[0022] marking resource failed due to error code STATUSCHECK_UNKNOWN  subtask=0 task=Deploy
