### ISSUE TITLE
Skaffold render for Helm charts with dependencies causes invalid YAML

### ISSUE THREAD

**Issue by dsiebel** [GoogleContainerTools/skaffold#8754]
### Description

A feature introduced in 2.4.0 - [feat: helm dependency build on render](https://github.com/GoogleContainerTools/skaffold/pull/8486) - breaks YAML output of `skaffold render` when `manifests.helm.releases` contains Charts with dependencies.
This is due to the fact that the underlying `helm dep build`, which is run before rendering,
outputs to stdout, not stderr, and will be included in the render-output.

### Expected behavior

`skaffold render --output="out.yaml"` outputs valid Kubernetes manifest YAML to `out.yaml`.

### Actual behavior

Outputs `helm dep build`'s output before the manifest YAML

```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "runatlantis" chart repository
...Successfully got an update from the "chartmuseum" chart repository
...Successfully got an update from the "trivago" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Deleting outdated charts
apiVersion: v1
kind: ...
```

### Information

- Skaffold version: `2.4.0`
- Operating system: `macos 12.6.5`
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: my-app
build:
  artifacts: [] # omitted for readability
manifests:
  helm:
    releases:
    - name: my-chart-with-dependencies
      chartPath: charts/my-chart
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold render`
3. check YAML output

**Comment by dsiebel** [comment]
Workaround: set `skipBuildDependencies: false` on the releases that are causing issues:

```yaml
manifests:
  helm:
    releases:
    - name: my-chart-with-dependencies
      chartPath: charts/my-chart
      skipBuildDependencies: false
```

`skipBuildDependencies: false` disables dependency updates before rendering.
