### ISSUE TITLE
Q: Should `skaffold diagnose` replace env vars in output?

### ISSUE THREAD

**Issue by dsiebel** [GoogleContainerTools/skaffold#8758]
### Description

We use `skaffold diagnose --yaml-only` in CI to do some feature-detection on the resulting YAML output to identify required dependencies, like Java/Jib, Qemu+Buildkit, Cloud Run / gcloud SDK.
This allows us to only install what is needed and reduce build times.

A recent use-case uses _one_ `skaffold.yaml` to build multiple artifacts and render multiple Helm Charts (for GitOps with ArgoCD) using env vars to change what needs to change for each Chart.

In the example `skaffold.yaml` below the variable `APP_NAME` is being passed via CI env.
This works well for `skaffold build` and `skaffold render`, but when running `skaffold diagnose` the output contains `{{ .APP_NAME }}`.

Our pipelines use `metadata.name` from `skaffold diagnose --yaml-only` to determine the filename for `skaffold render --out ${filename}.yaml` in a later step:

```yaml
effective_skaffold_config="$(skaffold diagnose --yaml-only --filename "${SKAFFOLD_FILE}" --profile "${profile}")"
filename="$(yq eval '.metadata.name' - <<< "${effective_skaffold_config}")"
```

resulting in filename `{{ .APP_NAME }}.yaml`, causing `skaffold render` to overwrite the same file multiple times.

Seeing that profiles and config dependencies are evaluated before output, should env vars be replaced with their value in the output as well?
Is there another way to achieve this, that I am not aware of?

### Information

- Skaffold version: `2.4.0`
- Operating system: `macos 12.6.5`
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: {{ .APP_NAME }}
build:
  artifacts:
    - jib: {}
      # rest omitted for readability
manifests:
  helm:
    releases:
      - name: {{ .APP_NAME }}
        chartPath: chart/app
        setValues:
          nameOverride: {{ .APP_NAME }}
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold diagnose`
3. Check output
