### ISSUE TITLE
Skaffold version 2.3.x issue - Unable to do our deployments using Kustomize

### ISSUE THREAD

**Issue by BabuRajan002** [GoogleContainerTools/skaffold#8802]
### Expected behavior
Our CI/CD setup is done in GCP cloud. We are using cloud deploy service to do our deployments. GCP Cloud deploy delivery pipeline internally calls the Skaffold to do our deployments in the GKE environment. In the Skaffold definition file we use Kustomize to deploy with respect to the each environments/namespaces. This is brief about our setup.

This entire setup was working fine with the previous skaffold version 1.39

Link to the GCP Documentation -> https://cloud.google.com/deploy/docs/using-skaffold 

### Actual behavior

As per this GCP Documentation --> https://cloud.google.com/deploy/docs/using-skaffold/select-skaffold we upgraded our Skaffold to the latest version 2.3.x and Schema version v4beta4. 
After we did that it is not recognizing our namespace parameter specified in the Skaffold definition file. Because of this it was deploying the application in the default namespace instead of our specific namespace. 

We suspect that whether do we need to modify anything with respect to Kustomization file to match with the Skaffold upgraded version.

### Information

- Skaffold version:  2.3
- Operating system:  GKE
- Installed via:  Google Cloud SDK 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: sample-app
manifests:
  kustomize:
    paths:
      - /path-to-our-base-folder
profiles:
  - name: test-env
    build: 
      cluster: 
         namespace: namespace-test-env
    manifests:
      kustomize:
        paths:
          - /overlays-folder-path
  - name: stg-env
    build: 
      cluster: 
         namespace: namespace-stg-env
    manifests:
      kustomize:
        paths:
          - /overlays-folder-path
  - name: preprd-env
    build: 
      cluster: 
         namespace: namespace-preprd-env
    manifests:
      kustomize:
        paths:
          - /overlays-folder-path
```
Note: Per our organization policy I should not suppose to share the exact Skaffold.yaml file we use. But the above is dummy file is similar to our actual one.

### Kustomization YAML file

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- name: dummy-config
  files:
    - dummy.json
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  env: test
nameSuffix: -test
```

With this above configurations of Skaffold and Kustomization YAML files, We were able to successfully deploy our application but the problem is it could not able to deploy it in the specific K8s namespace defined in the skaffold.yaml file. Instead of that it was going to ONLY the default  K8s namespace. 

Somehow it is not recognizing our namespace specified in the Skaffold.YAML definition file. We need your help, on how to specify the namespace in the new version of skaffold 2.3.x. Your help in this will be highly appreciated.!

**Comment by renzodavid9** [comment]
Hey @BabuRajan002, thanks for opening this issue and for explaining the full context.

According to Cloud Deploy docs (https://cloud.google.com/deploy/docs/using-skaffold#how_does_use_skaffold), the deployment is done using the `skaffold apply` command which apply the manifests to the cluster using `kubectl`; `kustomize` is only used to render the final manifests.

Taking a look to your `skaffold.yaml` manifest, you are setting the namespace under `build.cluster.namespace`, which is a property used to control in-cluster builds, not deployments. I think the way to go here should be the [`deploy.kubectl.defaultNamespace` property](https://skaffold.dev/docs/references/yaml/#deploy-kubectl-defaultNamespace) which controls the namespace to use in a deployment using the `kubectl` deployer. For your case, according to the example you sent, the `skaffold.yaml` file will look something similar to this:

```
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: sample-app
manifests:
  kustomize:
    paths:
      - /path-to-our-base-folder
profiles:
  - name: test-env
    deploy:
      kubectl:
        defaultNamespace: namespace-test-env
    manifests:
      kustomize:
        paths:
          - /overlays-folder-path
  - name: stg-env
    deploy:
      kubectl:
        defaultNamespace: namespace-stg-env
    manifests:
      kustomize:
        paths:
          - /overlays-folder-path
  - name: preprd-env
    deploy:
      kubectl:
        defaultNamespace: namespace-preprd-env
    manifests:
      kustomize:
        paths:
          - /overlays-folder-path
```

Could you try using the `deploy.kubectl.defaultNamespace` property and let us know if that works for you? Thanks a lot!
