### ISSUE TITLE
Invalid reference format (missing sha prefix on digest) when building with ko

### ISSUE THREAD

**Issue by danistrebel** [GoogleContainerTools/skaffold#8852]
### Expected behavior

ko build creates an image reference with `:TAG@sha256DIGEST` version indication

### Actual behavior

ko build creates an image reference with `:TAG@DIGEST` where the DIGEST doesn't start with a sha prefix

### Information

- Skaffold version: v2.5.0 
- Operating system: macOS 13.4 
- Installed via: skaffold.dev 
- Contents of skaffold.yaml (ko example + -v flag):

```yaml
apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
  - image: skaffold-ko
    ko:
      flags:
        - -v
      dependencies:
        paths:
        - "**/*.go"
        - go.*
      fromImage: gcr.io/distroless/static-debian11:nonroot
profiles:
- name: gcb
  build:
    googleCloudBuild:
      koImage: us-central1-docker.pkg.dev/k8s-skaffold/testing/skaffold:v1.37.2
```

### Steps to reproduce the behavior

1. clone this repo
2. `cd exammples/ko`
3. set a docker repo in skaffold.env e.g. `SKAFFOLD_DEFAULT_REPO=europe-west1-docker.pkg.dev/my-project/ko-test`
4. `skaffold dev`

Logs

```txt
WARN[0008] error adding artifact to cache; caching may not work as expected: parsing reference "europe-west1-docker.pkg.dev/my-project/ko-test/skaffold-ko:v2.5.0-5-g97de7dba7-dirty@a2c9160597f329f43c02029e47d5da2b7de3d9967e36b62a008064ccb4d4c1ca": invalid reference format  subtask=skaffold-ko task=Build
```
