### ISSUE TITLE
Patch profile for deploy hooks don't work in Skaffold v2

### ISSUE THREAD

**Issue by mtanida** [GoogleContainerTools/skaffold#8854]
### Expected behavior
We have a skaffold config with a profile that patches the 'before' hook in the deploy section. This was working just fine in Skaffold v1, but does not work in Skaffold v2. 

### Actual behavior
When running with the profile enabled in Skaffold v2, we get the error that says:  `invalid path: /manifests/helm/hooks/before/0/host/command`, despite the fact that the path specified in our patch is clearly "/deploy/helm/hooks/before/0/host/command". I don't know why it is trying to patch '/manifests' because, indeed, we don't have a before hook in the manifests section. Everything works in v1, but every version of v2 that I've tried has this same issue.

### Information
- Skaffold version: v2.5.0 (but I've tried other versions of Skaffold >=2.0 and they all exhibit this behavior)
- Operating System: Ubuntu 18.04, 20.04, 22.04
- Installed via: prebuilt releases from Github
- Contents of skaffold.yaml (edited because our codebase is proprietary):

```yaml
apiVersion: skaffold/v2beta22
kind: Config
build:
  artifacts:
    - image: apps/pdapp
      context: .
      docker:
        dockerfile: docker/Dockerfile
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: pdapp
        namespace: dexterity
        createNamespace: true
        repo: https://artifact-repo./repository/helm
        remoteChart: pdapp
        version: 1.0.0
        skipBuildDependencies: true
        artifactOverrides:
          image: apps/pdapp
        imageStrategy:
          helm: {}
    hooks:
      before:
        - host:
            command: ["true"]
      after:
        - host:
            command: ["true"]
profiles:
  - name: cell1
    patches:
      - op: replace
        path: /deploy/helm/hooks/before/0/host/command
        value:
          - "bash"
          - "-c"
          - "./tools/script.sh"
```

### Steps to reproduce the behavior

1.Run skaffold diagnose -p cell1
