### ISSUE TITLE
manifest kustomize paths using environment variables that specify absolute paths are broken in skaffold v2.2.0+

### ISSUE THREAD

**Issue by ryanohnemus** [GoogleContainerTools/skaffold#8870]
### Expected behavior
I am using an environment variable of `MY_KUSTOMIZATION_PATH=/path/to/kustomization_folder`. 
My skaffold file uses this environment variable: 

```yaml
manifests:
  kustomize:
    paths: 
      - "{{.MY_KUSTOMIZATION_PATH}}/"
```

I am expecting the skaffold render to be able to resolve this environment variable to the correct path when calling kustomize.

### Actual behavior

In v2.1.0 of skaffold, the above config works without issue and is able to create the absolute path in the generated `kustomize build` command. 

In v2.2.0+ of skaffold, the above config generates a kustomize build command is generated incorrectly. The context (or build path) is prepended creating an invalid path and an error of `Error: must build at directory: not a valid directory: evalsymlink failure on '/path/to/build//path/to/kustomization_folder'. 

This is specific to using an environment variable within the `paths`. If you set an absolute path in the paths without an environment variable the kustomize build command is rendered with the proper path.

### Information

- Skaffold version: 2.2.0+
- Operating system: Mac OS x86_64
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
manifests:
  kustomize:
    paths: 
      - "{{.MY_KUSTOMIZATION_PATH}}/"
```

### Steps to reproduce the behavior

Use skaffold v2.2.0 or higher with `manifests.kustomize.paths.[]` which uses an environment variable that has an absolute path.
