### ISSUE TITLE
deploy fails with no error details when using kustomize with an invalid manifest

### ISSUE THREAD

**Issue by mrob95** [GoogleContainerTools/skaffold#8884]
### Expected behavior
skaffold should 
### Information

- Skaffold version: 2.4.1
- Operating system: WSL ubuntu
- Installed via: APT
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta4
kind: Config
manifests:
  kustomize:
    paths:
      - deployment.yaml
deploy:
  kubectl: {}
```

Contents of deployment.yaml (note that `env` section is indented incorrectly):
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: application
          image: nginx/nginx
          imagePullPolicy: Always
        env:
          - name: "ENV_VAR"
            value: "abc"
```

### Steps to reproduce the behavior

Run `skaffold deploy` with the above files in an otherwise empty directory. skaffold just prints `exit status 1` and exits with no other error details.
