### ISSUE TITLE
Templated fields documentation: artifact naming unclear when using fully qualified image

### ISSUE THREAD

**Issue by mattmelgard** [GoogleContainerTools/skaffold#8887]
### Overview

It's unclear to me how to reference an artifact when the image name is a fully qualified image. The [documentation](https://skaffold.dev/docs/environment/templating/) says to use the format `IMAGE_NAME_<artifact-name>`  but when using a build block that looks like this for example:

```
...
build:

  artifacts:
  - image: gcr.io/some-project/someservice
    context:./apiv2
    docker:
      dockerfile: ./Dockerfile

  tagPolicy:
    customTemplate:
      template: '{{ .USERNAME }}_{{ .COMMIT }}'
      components:
      - name: USERNAME
        envTemplate:
          template: '{{ .USER }}'
      - name: COMMIT
        gitCommit:
          variant: AbbrevCommitSha

  local:
    push: false
    useBuildkit: true
    concurrency: 0
...
```

Referencing the artifact name in a Helm release like this:

```
deploy:
  helm:
    releases:
      name: someservice
      valuesFiles:
        - some/values/file.yaml
      setValueTemplates:
        app.image.tag: "{{ .IMAGE_TAG_gcr.io_some_project_some_service }}"
        app.image.repository: "{{ .IMAGE_REPO_gcr.io_some_project_some_service }}"
```

Does not seem to produce a value for the image and the documentation doesn't really provide enough information to determine what the `<artifact-name>` part of `IMAGE_NAME_<artifact-name>` should be.

If I'm just missing some documentation somewhere that explains this better, please let me know, but I wasn't able to find anything to help better explain how to reference those images.

### Other Details

- Skaffold version: 2.3
- Operating system: macOS
- Installed via:  Homebrew
