### ISSUE TITLE
Support for docker's "--target" option

### ISSUE THREAD

**Issue by bryanlarsen** [GoogleContainerTools/skaffold#890]
In #889 I asked for support for dependent artifacts.    Instead, we could combine our dependent Dockerfile's into multi-stage Dockerfile's, which skaffold does support.

Then in production, we can take advantage of docker's "--target" to tag and push the intermediate stages.

A naive interpretation of this would end up with 8 large Dockerfiles only differing in the last stage, which is sometimes only a few lines long.

So instead I tried combining all the Dockerfiles into one and faking --target using a build arg.   It appears to work:

Dockerfile:
```
ARG TARGET=api

FROM ubuntu:16.04 as base
....

FROM ubuntu:16.04 as conf
ARG ENV=minikube
...

FROM base as api-unconfigured
...

FROM api-unconfigured as api
COPY --from=conf /conf.json /
...

FROM base as dispatcher-unconfigured
...

FROM dispatcher-unconfigured as dispatcher
COPY --from=conf /conf.json /
...

FROM ${TARGET}
```

skaffold.yaml:

```
artifacts:
  - imageName: minikube-api
    docker:
      buildArgs:
        ENV: minikube
        TARGET: api

  - imageName: minikube-dispatcher
    docker:
      buildArgs:
        ENV: minikube
        TARGET: dispatcher
```

BuildKit builds the resulting monstrosity better than current versions of Docker, but layer caching keeps it basically cost-free even with current versions.

I appear to have an acceptable workaround, so this is a low-priority request.
