### ISSUE TITLE
Support wildcards in config dependencies path

### ISSUE THREAD

**Issue by ad-ops** [GoogleContainerTools/skaffold#8914]
### Expected behavior
Able to use wildcards in file paths for config dependencies.
```yaml
requires:
   - path: ./projects/*/skaffold.yaml
      configs: []
```

This would be helpful since often there are multiple projects under one or more folders and even if it is not a big change to the root config it make more commits and more steps to automate editing projects.

##### Error message

parsing skaffold config: could not find skaffold config file "/Users/foo/ws/bar/x/*/skaffold.yaml" that is referenced as a dependency in config file "/Users/foo/ws/bar/skaffold.yaml": stat /Users/foo/ws/bar/x/*/skaffold.yaml: no such file or directory. Modify the `requires` definition in the configuration file "/Users/foo/ws/bar/skaffold.yaml" to point to the correct path for the dependency "/Users/foo/ws/bar/x/*/skaffold.yaml".

### Information

- Skaffold version: v2.5.1
- Operating system: macOS Ventura 13.4.1
- Installed via: Google Cloud SDK
- Contents of skaffold.yaml:

##### root skaffold.yaml at `./skaffold.yaml`
```yaml
apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: root
requires:
- configs: []
  path: ./x/*/skaffold.yaml
```

##### sub skaffold.yaml at `./x/a/skaffold.yaml`
```yaml
apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: a
```

### Steps to reproduce the behavior

1.  create dir `./x` and `./x/a`.
2. add `skaffold.yaml` from above information in dirs.
3. `skaffold build`
