### ISSUE TITLE
How to handle different image repositories for each profile

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [GoogleContainerTools/skaffold#8920]
I have a repository `europe-west1-docker.pkg.dev/foo-dev/bar` that I need to build/push 20 images in profile _dev_.
In profile _tst_, I need to build/push the same 20 images but to `europe-west1-docker.pkg.dev/foo-tst/bar`.

How would I handle this with Skaffold without duplicating every artifact?

**Comment by dkirrane** [comment]
I was looking for this same feature.
Instead of having to run `skaffold config set default-repo my-dev.azurecr.io` &  `skaffold config set default-repo my-stage.azurecr.io`
Allow setting it via profiles

e.g

```yaml
apiVersion: skaffold/v4beta2
kind: Config

build:
...

deploy:
...

profiles:
  - name: dev
    config:
      repo: my-dev.azurecr.io
    ...
  - name: stage
    config:
      repo: my-stage.azurecr.io
    ...
    
         
```
