### ISSUE TITLE
Helm deprecation: `--recreate-pods`

### ISSUE THREAD

**Issue by userbradley** [GoogleContainerTools/skaffold#8924]
### Expected behavior

When using Skaffold to deploy Helm charts, one may want to use the below to have helm _roll_ the deployment

Helm will roll the deployment.

```yaml
recreatePods: true
```

### Actual behavior

Helm notifies user of deprecated command and asks users to navigate to the below URL

`https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments`

### Information

- Skaffold version: `v2.5.1`
- Operating system: `Max OSX Ventura 13.4 Darwin Kernel Version 22.5.0`
- Installed via: `Homebrew`

### Contents of `skaffold.yaml`

```yaml
apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: <>
profiles:
...

  - name: test
    deploy:
      kubeContext: prd
      helm:
        releases:
          - name: <>
            namespace: <>
            remoteChart: <>/<>
            upgradeOnChange: true
            valuesFiles:
              - test/values.yaml
            setValues:
              image.repository: europe-west2-docker.pkg.dev/<>/<>
              image.container: frontend
              image.tag: dev
              image.pullPolicy: Always
            setValueTemplates:
              ingress.iap.clientId: "{{.test_clientid}}"
              ingress.iap.clientSecret: "{{.test_clientsecret}}"
...

```

### Steps to reproduce the behavior

1. Add the key and value pair `recreatePods: true` to the deployment
2. `skaffold deploy`
