### ISSUE TITLE
skaffold verify with locally built artifact within k8s cluster

### ISSUE THREAD

**Issue by jack1902** [GoogleContainerTools/skaffold#8926]
### Expected behavior

When building artifacts which are pushed into a local cluster (such as `kind`) i assumed that i would then be able to run `skaffold verify` with those images inside the cluster, however i am observing that `docker.io` is being added and it is failing to pull those images in the cluster even though they have been "loaded" into the cluster.

To note, this SHOULD be possible as it appears possible when reviewing the docs: https://skaffold.dev/docs/verify/

### Actual behavior

Running `skaffold build -q > build_result.json` followed by `skaffold verify -a build_result.json` or simply `skaffold deploy -q | skaffold verify` even though i can see that the image is in the cluster, it is not able to pull it as the `registry` is incorrect.

For `skaffold deploy` via helm, i can specify the `image.registry` etc to ensure that the images being pulled by the cluster match those that have been loaded into the cluster by `skaffold`. It appears that this is what is missing as the link between what has been loaded into the cluster and what is being pulled is invalid.

I can't see a working `local-build` artifact example of `verify` when i look here: https://github.com/GoogleContainerTools/skaffold/tree/main/integration/testdata under all `verify-*`.

The closest example i can get which shows this issue happening is to use `verify-succeed` but extend the `local-built-artifact` with `executionMode.kubernetesCluster: {}`

Is it expected that locally built artifacts can be ran inside the k8s cluster? I was hoping to get tests running after a deployment of a system such that i could `verify` that the deployment has worked which might require poking things inside the cluster which aren't exposed via ports or ingress objects.

### Information

- Skaffold version:  v2.5.1
- Operating system:  MacOS
- Installed via:  HomeBrew
- Contents of skaffold.yaml:
This is from the above link which is in the testdata directory of skaffold.
```yaml
apiVersion: skaffold/v4beta6
kind: Config
verify:
- name: hello-world-1
  container:
    name: hello-world-1
    image: docker.io/hello-world:latest
- name: hello-world-2
  container:
    name: hello-world-2
    image: docker.io/hello-world:latest
- name: alpine-1
  container:
    name: alpine-1
    image: alpine:3.15.4
    command: ["/bin/sh"]
    args: ["-c", "echo $FOO; sleep 10; echo bye"]
- name: alpine-2
  container:
    name: alpine-2
    image: alpine:3.15.4
    command: ["/bin/sh"]
    args: ["-c", "echo $FOO; sleep 10; echo bye"]

profiles:
  - name: no-duplicated-logs
    verify:
      - name: alpine-1
        container:
          name: alpine-1
          image: alpine:3.15.4
          command: ["/bin/sh"]
          args: ["-c", "echo alpine-1; sleep 2; echo bye alpine-1"]

  - name: local-built-artifact

    build:
      artifacts:
        - image: localtask
          context: ./app
        - image: img-not-used-in-verify
          context: ./app


    verify:
      - name: alpine-1
        container:
          name: alpine-1
          image: alpine:3.15.4
          command: ["/bin/sh"]
          args: ["-c", "echo alpine-1; sleep 2; echo bye alpine-1"]

      - name: localtask
        container:
          name: localtask
          image: localtask
        # Added executionMode to not run locally but in k8s
        executionMode:
          kubernetesCluster: {}
```

### Steps to reproduce the behavior

1. Clone skaffold repo
2. `cd skaffold/integration/testdata/verify-succeed`
3. Add the below to the local-built-artifact:
```yaml
  executionMode:
          kubernetesCluster: {}
```
4. `skaffold verify -p local-built-artifact`

Skaffold will be completely stuck (kill it via the pid, control + c won't work)

<details>
  <summary>skaffold verify -p local-built-artifact -vdebug </summary>

```log
DEBU[0000] skaffold API not starting as it's not requested  subtask=-1 task=DevLoop
INFO[0000] Skaffold &{Version:v2.6.0 ConfigVersion:skaffold/v4beta6 GitVersion: GitCommit:23c5c16b9fc777b87602aa27dcbe3136291959f3 BuildDate:2023-06-27T16:57:47Z GoVersion:go1.20.5 Compiler:gc Platform:darwin/arm64 User:}  subtask=-1 task=DevLoop
INFO[0000] Loaded Skaffold defaults from "/Users/jack1902/.skaffold/config"  subtask=-1 task=DevLoop
DEBU[0000] parsed 1 configs from configuration file /Users/jack1902/skaffold-test/skaffold/integration/testdata/verify-succeed/skaffold.yaml  subtask=-1 task=DevLoop
INFO[0000] applying profile: local-built-artifact        subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field Build  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field artifacts  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field insecureRegistries  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field tagPolicy  subtask=-1 task=DevLoop
INFO[0000] no values found in profile for field TagPolicy, using original config values  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field platforms  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field BuildType  subtask=-1 task=DevLoop
INFO[0000] no values found in profile for field BuildType, using original config values  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field Test   subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field Render  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field Generate  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field rawYaml  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field remoteManifests  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field kustomize  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field helm   subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field kpt    subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field hooks  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field before  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field after  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field transform  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field validate  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field output  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field Deploy  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field DeployType  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field docker  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field helm   subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field kpt    subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field kubectl  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field cloudrun  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field statusCheck  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field statusCheckDeadlineSeconds  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field tolerateFailuresUntilDeadline  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field kubeContext  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field logs   subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field prefix  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field jsonParse  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field fields  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field -      subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field PortForward  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field ResourceSelector  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field allow  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field deny   subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field Verify  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field CustomActions  subtask=-1 task=DevLoop
DEBU[0000] Defaulting build type to local build          subtask=-1 task=DevLoop
DEBU[0000] Defaulting deploy type to kubectl             subtask=-1 task=DevLoop
INFO[0000] map entry found when executing locate for &{localtask ./app <nil> {0x14000cb80b0 <nil> <nil> <nil> <nil> <nil> <nil>} [] {[] []} [] } of type *latest.Artifact and pointer: 1374401774608  subtask=-1 task=DevLoop
INFO[0000] map entry found when executing locate for &{img-not-used-in-verify ./app <nil> {0x14000cb8160 <nil> <nil> <nil> <nil> <nil> <nil>} [] {[] []} [] } of type *latest.Artifact and pointer: 1374401774816  subtask=-1 task=DevLoop
INFO[0000] Using kubectl context: kind-kind              subtask=-1 task=DevLoop
DEBU[0000] getting client config for kubeContext: `kind-kind`  subtask=-1 task=DevLoop
DEBU[0000] getting client config for kubeContext: `kind-kind`  subtask=-1 task=DevLoop
DEBU[0000] Running command: [minikube version --output=json]  subtask=-1 task=DevLoop
DEBU[0000] setting Docker user agent to skaffold-v2.6.0  subtask=-1 task=DevLoop
INFO[0000] no kpt renderer or deployer found, skipping hydrated-dir creation  subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0000] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0000] CLI platforms provided: ""                    subtask=-1 task=DevLoop
DEBU[0000] platform detection from active kubernetes cluster is not enabled  subtask=-1 task=DevLoop
DEBU[0000] platforms selected for artifact "localtask": ""  subtask=-1 task=DevLoop
DEBU[0000] platforms selected for artifact "img-not-used-in-verify": ""  subtask=-1 task=DevLoop
DEBU[0000] Using builder: local                          subtask=-1 task=DevLoop
DEBU[0000] push value not present in NewBuilder, defaulting to false because cluster.PushImages is false  subtask=-1 task=DevLoop
INFO[0000] build concurrency first set to 1 parsed from *local.Builder[0]  subtask=-1 task=DevLoop
INFO[0000] final build concurrency value is 1            subtask=-1 task=DevLoop
DEBU[0000] getting client config for kubeContext: `kind-kind`  subtask=-1 task=DevLoop
Loading images into kind cluster nodes...
Images loaded in 125ns
DEBU[0000] getting client config for kubeContext: `kind-kind`  subtask=-1 task=DevLoop
DEBU[0000] getting client config for kubeContext: `kind-kind`  subtask=-1 task=DevLoop
```

</details>
