### ISSUE TITLE
Debug port is not forwarded when using Helm deploy

### ISSUE THREAD

**Issue by jdartigalongue** [GoogleContainerTools/skaffold#8927]
### Expected behavior
Skaffold should automatically create a port-forward for the defined services and the debug port .
### Actual behavior
Skaffold only creates the port-forward for the services ports.

### Information

- Skaffold version: v2.6.0
- Operating system: 13.4.1 (22F82)  Macbook Pro M1 
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta2
kind: Config
build:
  local:
    concurrency: 5
    push: false
  artifacts:
    - image: myservice
      context: .
      ko: {}

deploy:
  helm:
    releases:
      - name: myapp
        chartPath: ./chart
        namespace: default
        setValueTemplates:
          image: myservice

profiles:
  - name: test
    manifests:
      helm:
        releases:
          - name: myapp
            chartPath: ./chart
            setValues:
              image: myservice
    deploy:
      kubectl: {}
```

### Steps to reproduce the behavior

1. Clone https://github.com/jdartigalongue/skaffold-issue
2. `skaffold debug --port-forward` Notice that the only port forwarded is 8080
3. `skaffold debug --port-forward -p test` Using Helm render and deploy via Kubectl works fine though. Both 8080 and  56268 (debug) are forwarded
