### ISSUE TITLE
Skaffold "runtimeType" not working

### ISSUE THREAD

**Issue by anthonyalayo** [GoogleContainerTools/skaffold#8936]
There is something wrong with "runtimeType". Despite going through the Skaffold source code to verify the schema of the yaml file, my IDE setup with Cloud Code is still complaining that `runtimeType: jvm` is not allowed.

![image](https://github.com/GoogleContainerTools/skaffold/assets/17555572/f2b4b584-d5ef-4f2e-a1c0-4d938ee529fd)

I have seen this for months now, and I had thought that this was just a bug. However today I added `dumb-init` in front of my java process to fix other issues related to running as PID 1 in Linux. That's when I noticed that `runtimeType: jvm` is most definitely not working, because now `JAVA_TOOL_OPTIONS` is no longer set.

### Expected behavior

When specifying the following in a skaffold file:

```yaml
build:
  artifacts:
    - image: backend-java-app
      runtimeType: jvm
      docker:
        dockerfile: ci/Dockerfile
```

Regardless of what my entrypoint/command is for my Dockerfile, `JAVA_TOOL_OPTIONS` will be set.

### Actual behavior

`JAVA_TOOL_OPTIONS` is not set unless `java` is the command entry point.

### Information

- Skaffold version: v2.6.1
- Operating system: macOS Venture 13.2
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
#nonk8s
apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
    - image: backend-java-app
      runtimeType: jvm
      docker:
        dockerfile: ci/Dockerfile
  tagPolicy:
    inputDigest: { }
  local:
    push: false
    tryImportMissing: true
deploy:
  helm:
    releases:
      - name: backend-java-app
        chartPath: ./charts/backend-java-app
        valuesFiles:
          - ./charts/backend-java-app/values.yaml
          - ./charts/backend-java-app/values/dev/values.yaml
        setValueTemplates:
          fullnameOverride: backend-java-app
          image.repository: '{{.IMAGE_REPO}}'
          image.tag: '{{.IMAGE_TAG}}'
```
