### ISSUE TITLE
Kustomize does not support remote URLs

### ISSUE THREAD

**Issue by jackwilsdon** [GoogleContainerTools/skaffold#8940]
### Expected behavior
Running `skaffold run` with a remote Kustomize path should succeed (Kustomize supports this natively).

### Actual behavior
`skaffold run` fails, reporting that the path does not exist.

### Information

- Skaffold version: v2.6.0
- Operating system: macOS Ventura 13.4.1
- Installed via: skaffold.dev
- Contents of skaffold.yaml:
   ```yaml
   apiVersion: skaffold/v4beta5
   kind: Config
   manifests:
     kustomize:
       paths:
         - "https://github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.7.1"
   ```

### Steps to reproduce the behavior

1. Create a `skaffold.yaml` containing the above
2. `skaffold run`
3. The run fails as Skaffold treats the URL as a path:
   ```text
   No tags generated
   Starting test...
   running [kubectl --context docker-desktop kustomize /tmp/https:/github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.7.1]
    - stdout: ""
    - stderr: "error: must build at directory: not a valid directory: evalsymlink failure on '/tmp/https:/github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.7.1' : lstat /private/tmp/https:: no such file or directory\n"
    - cause: exit status 1
   ```

**Comment by ericzzzzzzz** [comment]
Hi @jackwilsdon , could you try to create a kustomization.yaml file 
and put something like 

```yaml
resources:
 - "https://github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.7.1"
```yaml

then your skaffold.yaml becomes 
```yaml
apiVersion: skaffold/v4beta5
kind: Config
manifests:
  kustomize:
    paths: 
       - .
```
does this work for you ?

**Comment by jackwilsdon** [comment]
That does seem to be working for me - it'd be nice if Skaffold supported URLs directly in its configuration but I can use that for now. Thanks!

**Comment by jdoylei** [comment]
Hi @ericzzzzzzz, we've been using Skaffold for about a year now and ran into this same issue.

* Skaffold version: v2.6.2
* OS: Windows
* Excerpt from skaffold.yaml:

```
apiVersion: skaffold/v1
kind: Config
build:
...
deploy:
  kustomize:
    path: "{{or .SKAFFOLD_INSTANCE_DIR \"https://x.y.z.com/scm/archrepo/archrepo-config.git/\"}}{{or .SKAFFOLD_INSTANCE (printf \"%v%v\" .USERNAME \"-01\")}}"
```
* Excerpt from output:
```
$ skaffold dev -f skaffold-jib.yaml
Generating tags...
...
Cleaning up...
 - No resources found
running [kustomize build C:\Users\jdoyle\git\ARCHREPO\archrepo\https:\x.y.z.com\scm\archrepo\archrepo-config.git\jdoyle-01]
 - stdout: ""
 - stderr: "Error: evalsymlink failure on 'C:\\Users\\jdoyle\\git\\ARCHREPO\\archrepo\\https:\\x.y.z.com\\scm\\archrepo\\archrepo-config.git\\jdoyle-01' : CreateFile C:\\Users\\jdoyle\\git\\ARCHREPO\\archrepo\\https:: The filename, directory name, or volume label syntax is incorrect.\n"
 - cause: exit status 1
```

The same config and remote Kustomize Git URL works fine with v1.37.2.

When we ran it on a developer's laptop with v2.0.0 installed, we started having issues, and updating to v2.6.2 confirms in more detail that Skaffold is treating the Git URLs as though they are relative paths that need to be adjusted before passing into Kustomize.

The suggestion for @jackwilsdon above makes sense, and that is our workaround - point to a local Kustomization dir that pulls in a remote base.  But the workaround sort of contradicts what we were accomplishing with Skaffold v1.37.2 and the remote URLs in skaffold.yaml:
* We were trying to avoid having individual developer files committed into the source code repo.
* We wanted to have developers manage individual developer Kustomize overlays in the remote repo.
* And then using skaffold.yaml's (very helpful!) path templating, the developer could just set an environment variable for which overlay in the remote repo to use, e.g. "https://x.y.z.com/scm/archrepo/archrepo-config.git/jdoyle-01"

Can a fix be made to Skaffold to leave Kustomize URLs be?  There is definitely logic for detecting URLs elsewhere, e.g. https://github.com/GoogleContainerTools/skaffold/blob/v2.6.2/pkg/skaffold/render/renderer/kustomize/kustomize.go#L296  

Thanks for your help!
