### ISSUE TITLE
"multiple deploy.kubectl.defaultNamespace values set" when depending on multiple configurations with different namespaces

### ISSUE THREAD

**Issue by jackwilsdon** [GoogleContainerTools/skaffold#8941]
### Expected behavior
Depending on two configurations with different namespaces does not produce a warning.

### Actual behavior
Depending on two configurations with different namespaces produces the following warning:
```text
WARN[0000] multiple deploy.kubectl.defaultNamespace values set, only last pipeline's value will be used  subtask=-1 task=DevLoop
```
The manifests are deployed to the correct namespaces, so the warning doesn't seem correct.

### Information

- Skaffold version: v2.6.0
- Operating system: macOS Ventura 13.4.1
- Installed via: skaffold.dev
- Contents of skaffold.yaml:
  ```yaml
  apiVersion: skaffold/v4beta5
  kind: Config
  requires:
    - path: project-a/skaffold.yaml
    - path: project-b/skaffold.yaml
  ```

### Steps to reproduce the behavior

1. `git clone https://github.com/jackwilsdon/skaffold-kubectl-namespace-issue`
2. `cd skaffold-kubectl-namespace-issue`
3. `skaffold run`
