### ISSUE TITLE
Google Cloud Run deploy hook commands do not print to Google Cloud logs

### ISSUE THREAD

**Issue by charlie-map** [GoogleContainerTools/skaffold#8947]
### Expected behavior
Adding an `echo` command into the Cloud Run hooks should log in a similar way that of other Skaffold logs during deploy. For instance, the following is a log from skaffold during the deploy step:

![image](https://github.com/GoogleContainerTools/skaffold/assets/75760351/0f09c8a0-8fc6-4206-8f4d-6c725ab40cee)

From my understanding of #8173, this would be where (see additional context below) the `before` hook would run. However, I haven't been able to find specific documentation on this and never saw a follow up issue [related to documentation](https://github.com/GoogleContainerTools/skaffold/pull/8173#issuecomment-1344631521) (granted, I saw that  #8384 also exists).

### Actual behavior
There are is no message from attempted `echo`.

#### Some additional context of deployment behavior:
<img width="840" src="https://github.com/GoogleContainerTools/skaffold/assets/75760351/3235fdfa-0787-4614-b8ad-decf435cf8fe"/>

Clearly, logs from Skaffold show up in the Google Cloud logs, but the specific log I add (see `skaffold.yaml` below) does not show up in the deploy step here. I have not tested any other commands, so I am unsure if the command is actually running. At the very least, by viewing the Skaffold config within Cloud Deploy, I see the existence of the below command:

<img width="840" src="https://github.com/GoogleContainerTools/skaffold/assets/75760351/55115754-8089-4983-b110-143911cf53aa"/>

### Information

- Skaffold version: `skaffold/v4beta2` to `skaffold/v4beta4` (`skaffold/v4beta5`+ is not supported by Google Cloud, which perhaps may be what's causing this particular issue as well 🤔 )
- Operating system: Linux
- Installed via: Google Cloud SDK
- Contents of skaffold.yaml:

#### `skaffold.yaml`
```yaml
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: my-pipeline

build:
  artifacts:
    - image: deploy-image
      context: my-pipeline
  googleCloudBuild:
    projectId: ${PROJECT_ID}

profiles:
  - name: staging
    manifests:
      rawYaml:
        - staging.yaml

deploy:
  cloudrun:
    hooks:
      before:
        - command: ['sh', '-c', 'echo PRE-DEPLOY Cloud Run MODULE1 host hook!']
          os: [linux]
```

#### `staging.yaml`
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-staging
spec:
  template:
    spec:
      containers:
        - image: deploy-image
```

### Steps to reproduce the behavior

1. Project shouldn't matter as this is solely the CI side. The above is used through a Cloud Deploy pipeline:
```yaml
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-pipeline
description: A pipeline
serialPipeline:
  stages:
    - targetId: staging
      profiles: [staging]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: Cloud Run staging service
run:
  location: projects/{PROJECT_ID}/locations/{REGION}
```
2. Create a release with some image (which shouldn't matter) to run through the pipeline steps

I can't share much else, but feel free to ping with additional questions/clarifications. Thanks!
