### ISSUE TITLE
Google Cloud Deploy not selecting Skaffold Profile

### ISSUE THREAD

**Issue by radioactive11** [GoogleContainerTools/skaffold#8956]
### Expected behavior

Google Cloud Deploy should dynamically select profile, but only the default profile is used for applying manifests.

### Actual behavior

Stage & Prod have same config

### Information

- Skaffold version: v4beta6
- Operating system: GKE
- Installed via: Google Cloud SDK
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta6
kind: Config

build:
  artifacts:
    - image: ****
  googleCloudBuild:
    projectId: ****

manifests:
  rawYaml:
    - k8s-deployment.yaml

profiles:
  - name: stage
    activation:
      - kubeContext: ****
      - command: stage
    build:
      artifacts:
        - image: ****
      googleCloudBuild:
        projectId: ****
    manifests:
      rawYaml:
        - k8s-deployment.yaml
    deploy:
      kubectl: {}

  - name: prod
    activation:
      - kubeContext: ****
      - command: prod
    build:
      artifacts:
        - image: ****
      googleCloudBuild:
        projectId: ****
    manifests:
      rawYaml:
        - k8s-deployment-prod.yaml

    deploy:
      kubectl: {}

```

### Steps to reproduce the behavior

Using Google Cloud Deploy

```yaml
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: ****
description: gke deployment pipeline
serialPipeline:
  stages:
    - targetId: staging
      profiles:
        - stage
    - targetId: production
      profiles:
        - prod

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: staging cluster
gke:
  cluster: ****

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: production cluster
gke:
  cluster: ****

```
