### ISSUE TITLE
debug.cloud.google.com/probe/timeouts is not a valid k8s annotation key syntax

### ISSUE THREAD

**Issue by t2tse** [GoogleContainerTools/skaffold#8962]
### Expected behavior
Able to use the `debug.cloud.google.com/probe/timeouts` annotation in Deployment pod spec to rewrite k8s probe timeout

### Actual behavior
Unable to use such annotation. Error is seen when applying it with my Deployment YAML against a k8s cluster.

`The Deployment "nginx-1" is invalid: spec.template.annotations: Invalid value: "debug.cloud.google.com/probe/timeouts": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')`

`debug.cloud.google.com/probe/timeouts` does not seem to be a correct k8s annotation key syntax per
https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set

### Information

- Skaffold version: v2.6.0
- Operating system: linux
- Installed via: Cloud Code / GCP Cloud Shell
- Contents of skaffold.yaml: N/A

### Steps to reproduce the behavior

1. Create a Deployment YAML with the `debug.cloud.google.com/probe/timeouts`  annotation in the pod spec
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1
  namespace: sample
  labels:
    app: nginx-1
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
      annotations:
        debug.cloud.google.com/probe/timeouts: '1800s'
    spec:
      containers:
      - name: nginx-1
        image: nginx:latest
```
2. `kubectl apply` the above YAML to a GKE cluster
3.  Above validation error is seen
