### ISSUE TITLE
.Capabilities.APIVersions.Has does not work in Helm charts when using Helm as a renderer

### ISSUE THREAD

**Issue by jackwilsdon** [GoogleContainerTools/skaffold#8969]
### Expected behavior
`.Capabilities.APIVersions.Has` works in Helm charts when using Helm as a manifest renderer.

### Actual behavior
`.Capabilities.APIVersions` is only populated with default API versions available to `kubectl` (not versions available in the cluster).

### Information

- Skaffold version: v2.6.0
- Operating system: macOS Ventura 13.4.1
- Installed via: skaffold.dev
- Contents of skaffold.yaml:
  ```yaml
  apiVersion: skaffold/v4beta5
  kind: Config
  manifests:
    helm:
      releases:
        - name: my-release
          chartPath: my-chart
  deploy:
    kubectl: {}
```

### Steps to reproduce the behavior

1. Clone https://github.com/jackwilsdon/skaffold-capabilities-issue
2. `skaffold run` or `skaffold render`
3. Note that the generated ConfigMap only lists the default API versions and not any additional ones installed into the cluster
