### ISSUE TITLE
kubeContext doesn't work with skaffold run

### ISSUE THREAD

**Issue by JoelOtter** [GoogleContainerTools/skaffold#8970]
### Expected behavior

When deploying a Skaffold configuration with a `kubeContext` set, I would expect it to deploy to that context regardless of what my current kube context is on my system.

### Actual behavior

For the following minimal reproducible example:

```yaml
apiVersion: skaffold/v4beta6
kind: Config
deploy:
  kubeContext: docker-desktop
  helm:
    releases:
    - name: redis-release
      repo: https://charts.bitnami.com/bitnami 
      remoteChart: redis
```

Running `skaffold run` starts the pods on the correct context, but then fails when checking if it has rolled out successfully. It appears to deploy to the specified context but then run its tests/checks against the one that's set. If I set my kube context to an old broken one for a context that doesn't exist, my logs look like this:

```
[18:10] -> skaffold run
WARN[0000] failed to detect active kubernetes cluster node platform. Specify the correct build platform in the `skaffold.yaml` file or using the `--platform` flag  subtask=-1 task=DevLoop
No tags generated
Starting test...
Starting deploy...
Helm release redis-release not installed. Installing...
NAME: redis-release
LAST DEPLOYED: Tue Jul 25 18:10:59 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: redis
CHART VERSION: 17.13.2
APP VERSION: 7.0.12

Waiting for deployments to stabilize...
 - statefulset/redis-release-master: creating container redis
    - pod/redis-release-master-0: creating container redis
 - statefulset/redis-release-master failed. Error: creating container redis.
1/2 deployment(s) failed
```

However, if I switch over to the correct context (`docker-desktop`) then the pods have started up correctly. Running `skaffold delete` _does_ work correctly regardless of which context I have selected.

### Information

- Skaffold version: 2.6.2, also tested and verified on 2.3.1
- Operating system: macOS 13.4.1
- Installed via: Homebrew

Many thanks.
