### ISSUE TITLE
Unexpected "Error creating: Unauthorized"

### ISSUE THREAD

**Issue by aran** [GoogleContainerTools/skaffold#8972]
### Expected behavior
`skaffold dev -p dev` reliably deploys a helm-based skaffold deploy to kubernetes running in Colima.

### Actual behavior

I’m seeing a `skaffold dev` fail with `“Failed to create Pod for Deployment <…>: Error creating: Unauthorized”`
However with `--keep-running-on-failures` and `--tolerate-failures-until-deadline`, I am able to see with `kubectl get deployment -A` that the deployment has in fact succeeded. Running with `--verbosity='trace'` isn’t showing any other clues that look obvious. 

### Information

- Skaffold version:& {Version:v2.6.2 ConfigVersion:skaffold/v4beta6 GitVersion: GitCommit:0d544d26766058c5a49ba80907edf438a01c90d4 BuildDate:2023-07-18T19:56:24Z GoVersion:go1.20.6 Compiler:gc Platform:darwin/arm64 User:}
- Operating system: macOS 
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
---
"apiVersion": "skaffold/v4beta5"
"build":
  "artifacts":
  - "bazel":
      "target": "//foundation/cloudnative-pg:cloudnative-pg.tar"
    "image": "cloudnative-pg"
  - "bazel":
      "target": "//foundation/cloudnative-pg:busybox.tar"
    "image": "busybox"
  "tagPolicy":
    "sha256": {}
"kind": "Config"
"metadata":
  "name": "cloudnative-pg"
"profiles":
- "deploy":
    "helm":
      "releases":
      - "createNamespace": true
        "name": "cloudnative-pg-release"
        "namespace": "cnpg-system"
        "remoteChart": "cloudnative-pg"
        "repo": "https://cloudnative-pg.io/charts/"
        "setValueTemplates":
          "image.repository": "{{.IMAGE_REPO_cloudnative_pg}}"
          "image.tag": "{{.IMAGE_TAG_cloudnative_pg}}@{{.IMAGE_DIGEST_cloudnative_pg}}"
          "test.image.repository": "{{.IMAGE_REPO_busybox}}"
          "test.image.tag": "{{.IMAGE_TAG_busybox}}@{{.IMAGE_DIGEST_busybox}}"
        "setValues":
          "image.pullPolicy": "IfNotPresent"
          "serviceAccount.create": "true"
          "serviceAccount.name": "cloudnative-pg-release"
          "test.image.pullPolicy": "IfNotPresent"
  "name": "dev"
- "deploy":
    "helm":
      "releases":
      - "createNamespace": false
        "name": "cloudnative-pg-release"
        "namespace": "cnpg-system"
        "remoteChart": "cloudnative-pg"
        "repo": "https://cloudnative-pg.io/charts/"
        "setValueTemplates":
          "image.repository": "{{.IMAGE_REPO_cloudnative_pg}}"
          "image.tag": "{{.IMAGE_TAG_cloudnative_pg}}@{{.IMAGE_DIGEST_cloudnative_pg}}"
          "test.image.repository": "{{.IMAGE_REPO_busybox}}"
          "test.image.tag": "{{.IMAGE_TAG_busybox}}@{{.IMAGE_DIGEST_busybox}}"
        "setValues":
          "image.pullPolicy": "IfNotPresent"
          "serviceAccount.create": "false"
          "serviceAccount.name": "cloudnative-pg-release"
          "test.image.pullPolicy": "IfNotPresent"
  "manifests":
    "rawYaml":
    - "namespace.yaml"
    - "sa.yaml"
  "name": "prod"
...

```

### Steps to reproduce the behavior
`skaffold dev -p dev` in a folder with the above skaffold.yaml file.

On another mac, with same skaffold, colima and kubernetes versions, the same issue does not occur. 

Arguably there's a logging enhancement implicit in this as it is hard to diagnose what is occurring from the existing logs.

[skaffold_debug2.txt](https://github.com/GoogleContainerTools/skaffold/files/12166538/skaffold_debug2.txt)

**Comment by ocni-dtu** [comment]
I'm experiencing the same error.
The skaffold deployment fails, but if I let the deployment/pods run after skaffold's failure the pod successfully starts.
It possibly happened after updating to v2.6.0

**Comment by davidedmondsMPG** [comment]
I'm getting similar installing [Agones](https://agones.dev) via Helm, in both the Render (subsequently deployed with kubectl with --server-side flag) and Deploy phases:

(anonymized)
```
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: service

build:
  artifacts:
    - image: service
      ko:
        main: ./cmd/service

manifests:
  kustomize:
    paths:
      - # two paths for kustomization resources
  helm:
    releases:
      - name: agones
        namespace: agones-system
        createNamespace: true
        remoteChart: agones
        repo: https://agones.dev/chart/stable
        version: 1.33.0
        setValues:
          agones.ping.install: false

deploy:
  kubectl:
    flags:
      apply:
        - --server-side
        - --force-conflicts

portForward:
  - # three deployment port forwards
```

Log output (anonymised):
```
- priorityclass.scheduling.k8s.io/agones-system serverside-applied
# snip
Waiting for deployments to stabilize...
# snip
 - agones-system:deployment/agones-extensions: Failed to create Pod for Deployment agones-extensions: Error creating: pods "agones-extensions-5cd94689cb-" is forbidden: no PriorityClass with name agones-system was found
 - agones-system:deployment/agones-extensions failed. Error: Failed to create Pod for Deployment agones-extensions: Error creating: pods "agones-extensions-5cd94689cb-" is forbidden: no PriorityClass with name agones-system was found.
 - agones-system:deployment/agones-controller: Failed to create Pod for Deployment agones-controller: Error creating: pods "agones-controller-6d55775b94-" is forbidden: no PriorityClass with name agones-system was found
 - agones-system:deployment/agones-controller failed. Error: Failed to create Pod for Deployment agones-controller: Error creating: pods "agones-controller-6d55775b94-" is forbidden: no PriorityClass with name agones-system was found.
```

Running the Helm chart outside of skaffold results in working pods - I don't see them going into a failure state when watching in Kubectl, but they definitely go through that state in the event log:

```
0s          Normal    NoPods                   poddisruptionbudget/agones-controller-pdb   No matching pods found
0s          Normal    NoPods                   poddisruptionbudget/agones-extensions-pdb   No matching pods found
0s          Normal    NoPods                   poddisruptionbudget/agones-controller-pdb   No matching pods found
0s          Normal    NoPods                   poddisruptionbudget/agones-extensions-pdb   No matching pods found
0s          Normal    EnsuringLoadBalancer     service/agones-allocator                    Ensuring load balancer
0s          Normal    ScalingReplicaSet        deployment/agones-extensions                Scaled up replica set agones-extensions-69d554d97 to 2
0s          Normal    AppliedDaemonSet         service/agones-allocator                    Applied LoadBalancer DaemonSet kube-system/svclb-agones-allocator-ca3aa78a
0s          Normal    ScalingReplicaSet        deployment/agones-controller                Scaled up replica set agones-controller-bf5d58f54 to 2
0s          Warning   FailedCreate             replicaset/agones-controller-bf5d58f54      Error creating: pods "agones-controller-bf5d58f54-" is forbidden: no PriorityClass with name agones-system was found
0s          Normal    ScalingReplicaSet        deployment/agones-allocator                 Scaled up replica set agones-allocator-88cffb566 to 3
0s          Warning   FailedCreate             replicaset/agones-extensions-69d554d97      Error creating: pods "agones-extensions-69d554d97-" is forbidden: no PriorityClass with name agones-system was found
0s          Normal    Scheduled                pod/agones-allocator-88cffb566-lrcdw        Successfully assigned agones-system/agones-allocator-88cffb566-lrcdw to colima
1s          Normal    SuccessfulCreate         replicaset/agones-allocator-88cffb566       Created pod: agones-allocator-88cffb566-lrcdw
0s          Normal    Scheduled                pod/agones-extensions-69d554d97-jhm9w       Successfully assigned agones-system/agones-extensions-69d554d97-jhm9w to colima
0s          Normal    Scheduled                pod/agones-allocator-88cffb566-5cgkm        Successfully assigned agones-system/agones-allocator-88cffb566-5cgkm to colima
0s          Normal    Scheduled                pod/agones-allocator-88cffb566-krjht        Successfully assigned agones-system/agones-allocator-88cffb566-krjht to colima
0s          Normal    Scheduled                pod/agones-controller-bf5d58f54-6g75g       Successfully assigned agones-system/agones-controller-bf5d58f54-6g75g to colima
1s          Normal    SuccessfulCreate         replicaset/agones-allocator-88cffb566       Created pod: agones-allocator-88cffb566-krjht
0s          Normal    Scheduled                pod/agones-controller-bf5d58f54-snpj2       Successfully assigned agones-system/agones-controller-bf5d58f54-snpj2 to colima
0s          Normal    Scheduled                pod/agones-extensions-69d554d97-n4kgf       Successfully assigned agones-system/agones-extensions-69d554d97-n4kgf to colima
1s          Normal    SuccessfulCreate         replicaset/agones-allocator-88cffb566       Created pod: agones-allocator-88cffb566-5cgkm
1s          Normal    SuccessfulCreate         replicaset/agones-extensions-69d554d97      Created pod: agones-extensions-69d554d97-jhm9w
1s          Normal    SuccessfulCreate         replicaset/agones-controller-bf5d58f54      Created pod: agones-controller-bf5d58f54-6g75g
1s          Normal    SuccessfulCreate         replicaset/agones-controller-bf5d58f54      Created pod: agones-controller-bf5d58f54-snpj2
1s          Normal    SuccessfulCreate         replicaset/agones-extensions-69d554d97      Created pod: agones-extensions-69d554d97-n4kgf
0s          Warning   FailedMount              pod/agones-allocator-88cffb566-lrcdw        MountVolume.SetUp failed for volume "client-ca" : failed to sync secret cache: timed out waiting for the condition
0s          Normal    Pulled                   pod/agones-extensions-69d554d97-jhm9w       Container image "us-docker.pkg.dev/agones-images/release/agones-extensions:1.33.0" already present on machine
0s          Normal    Created                  pod/agones-extensions-69d554d97-jhm9w       Created container agones-extensions
0s          Normal    Pulled                   pod/agones-controller-bf5d58f54-snpj2       Container image "us-docker.pkg.dev/agones-images/release/agones-controller:1.33.0" already present on machine
0s          Normal    Created                  pod/agones-controller-bf5d58f54-snpj2       Created container agones-controller
0s          Normal    Started                  pod/agones-extensions-69d554d97-jhm9w       Started container agones-extensions
0s          Normal    Started                  pod/agones-controller-bf5d58f54-snpj2       Started container agones-controller
0s          Normal    Pulled                   pod/agones-allocator-88cffb566-5cgkm        Container image "us-docker.pkg.dev/agones-images/release/agones-allocator:1.33.0" already present on machine
0s          Normal    Pulled                   pod/agones-controller-bf5d58f54-6g75g       Container image "us-docker.pkg.dev/agones-images/release/agones-controller:1.33.0" already present on machine
0s          Normal    Created                  pod/agones-allocator-88cffb566-5cgkm        Created container agones-allocator
0s          Normal    Pulled                   pod/agones-allocator-88cffb566-krjht        Container image "us-docker.pkg.dev/agones-images/release/agones-allocator:1.33.0" already present on machine
0s          Normal    Created                  pod/agones-controller-bf5d58f54-6g75g       Created container agones-controller
0s          Normal    UpdatedLoadBalancer      service/agones-allocator                    Updated LoadBalancer with new IPs: [] -> [192.168.106.2]
0s          Normal    Pulled                   pod/agones-allocator-88cffb566-lrcdw        Container image "us-docker.pkg.dev/agones-images/release/agones-allocator:1.33.0" already present on machine
0s          Normal    Created                  pod/agones-allocator-88cffb566-krjht        Created container agones-allocator
1s          Normal    Created                  pod/agones-allocator-88cffb566-lrcdw        Created container agones-allocator
1s          Normal    Pulled                   pod/agones-extensions-69d554d97-n4kgf       Container image "us-docker.pkg.dev/agones-images/release/agones-extensions:1.33.0" already present on machine
1s          Normal    Created                  pod/agones-extensions-69d554d97-n4kgf       Created container agones-extensions
0s          Normal    Started                  pod/agones-allocator-88cffb566-5cgkm        Started container agones-allocator
0s          Normal    Started                  pod/agones-allocator-88cffb566-krjht        Started container agones-allocator
0s          Normal    Started                  pod/agones-controller-bf5d58f54-6g75g       Started container agones-controller
0s          Normal    Started                  pod/agones-extensions-69d554d97-n4kgf       Started container agones-extensions
0s          Normal    Started                  pod/agones-allocator-88cffb566-lrcdw        Started container agones-allocator
```
