### ISSUE TITLE
Allow templating for `requires[].git.repo`

### ISSUE THREAD

**Issue by w4rdy** [GoogleContainerTools/skaffold#8982]
### Expected behavior
Templating should work for `requires[].git.repo`. This field doesn't seem to support templating, as outlined in the docs: https://skaffold.dev/docs/environment/templating/

### Actual behavior
Templating does not work for `requires[].git.repo`

### Information

- Skaffold version: v2.4.0
- Operating system: Ubuntu 22.04.1
- Installed via: Standalone binary 
- Contents of skaffold.yaml:

```yaml
---
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: kafka

requires:
  - configs:
      - kafka
    git:
      repo: "https://{{.PAT}}@dev.azure.com/my-org/my-project/_git/kafka"
      path: skaffold.yaml
      sync: true
      ref: develop
```

### Steps to reproduce the behavior

1. Store a skaffold config in a remote repository
2. Run `skaffold run -m kafka` while passing in a PAT env var for your repo
3. See that skaffold is not able to resolve the templated value
