### ISSUE TITLE
ko build with sha256 tag policy uses image:latest@sha256:... tag instead of image@sha256:...

### ISSUE THREAD

**Issue by eikemeier** [GoogleContainerTools/skaffold#8990]
### Expected behavior

```
skaffold run
...
Tags used in deployment:
 - registry/image -> registry/image@sha256:xxxxxxx
```

### Actual behavior

```
skaffold run
...
Tags used in deployment:
 - registry/image -> registry/image:latest@sha256:xxxxxxx
```

Kubernetes fails to pull the image.

### Information

- Skaffold version: HEAD
- Operating system: macOS
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: sample
build:
  artifacts:
    - image: registry/image
      ko: {}
  tagPolicy:
    sha256: {}

manifests:
  kustomize:
    paths:
      - k8s/sample
```

### Steps to reproduce the behavior

Excerpt from logs:

```
DEBU[0000] Using builder: local                          subtask=-1 task=DevLoop
DEBU[0000] push value not present in NewBuilder, defaulting to true because cluster.PushImages is true  subtask=-1 task=DevLoop
...
Generating tags...
 - registry/image -> registry/image:latest
INFO[0000] Tags generated in 216.083µs                   subtask=-1 task=Build
...
INFO[0001] Render completed in 68.060416ms               subtask=-1 task=DevLoop
Tags used in deployment:
 - registry/image -> registry/image:latest@sha256:xxxxxxx
```
