### ISSUE TITLE
Build Failed. Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Check if docker is running.

### ISSUE THREAD

**Issue by cay-cospete** [GoogleContainerTools/skaffold#9001]
### Expected behavior
It should build it successfully when running `skaffold dev`

### Actual behavior
It fails due to `Build Failed. Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Check if docker is running.`

### Information

- Skaffold version: v2.6.3
- Operating system: MAC
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: bk-blog-microservice
build:
  artifacts:
    - image: ash/client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: ash/comments
      context: comments
      docker:
        dockerfile: Dockerfile
    - image: ash/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
    - image: ash/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
    - image: ash/posts
      context: posts
      docker:
        dockerfile: Dockerfile
    - image: ash/query
      context: query
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/client-depl.yaml
    - infra/k8s/comments-depl.yaml
    - infra/k8s/event-bus-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/moderation-depl.yaml
    - infra/k8s/posts-depl.yaml
    - infra/k8s/posts-srv.yaml
    - infra/k8s/query-depl.yaml
****
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...
