### ISSUE TITLE
Local sync of Ariflow DAGs with Airflow Deployment deployed within Kind Cluster Failing

### ISSUE THREAD

**Issue by RossKohler** [GoogleContainerTools/skaffold#9014]
### Expected behavior
My Airflow DAGs are synced with my Airflow deployment sitting within my KIND cluster. Any changes made to the DAGs outside the cluster are copied into the deployment and the updates appear in the Airflow UI.

### Actual behavior
Syncing of the changes with the deployment fail with the below error message:
` Skipping deploy due to sync error:copying files: didn't sync any files: sync failed for artifact "airflow:cfde63662cf5b5895f0dddf80b0a0a367803ab16712dd8fab136dcf053f4a8d3"  subtask=-1 task=DevLoop`

Here are the logs shown after the `skaffold dev --port-forward` command:

```
skaffold dev --port-forward
Generating tags...
 - airflow -> airflow:12acb9a-dirty
Checking cache...
 - airflow: Found Locally
Tags used in deployment:
 - airflow -> airflow:cfde63662cf5b5895f0dddf80b0a0a367803ab16712dd8fab136dcf053f4a8d3
Starting deploy...
Loading images into kind cluster nodes...
 - airflow:cfde63662cf5b5895f0dddf80b0a0a367803ab16712dd8fab136dcf053f4a8d3 -> Loaded
Images loaded in 2 minutes 13.188 seconds
Helm release airflow not installed. Installing...
NAME: airflow
LAST DEPLOYED: Fri Aug 11 14:31:50 2023
NAMESPACE: airflow
STATUS: deployed
REVISION: 1
TEST SUITE: None
WARN[0257] image [airflow:cfde63662cf5b5895f0dddf80b0a0a367803ab16712dd8fab136dcf053f4a8d3] is not used.  subtask=-1 task=DevLoop
WARN[0257] See helm documentation on how to replace image names with their actual tags: https://skaffold.dev/docs/pipeline-stages/deployers/helm/#image-configuration  subtask=-1 task=DevLoop
Waiting for deployments to stabilize...
 - airflow:statefulset/airflow-triggerer is ready. [4/5 deployment(s) still pending]
 - airflow:deployment/airflow-scheduler is ready. [3/5 deployment(s) still pending]
 - airflow:deployment/airflow-statsd is ready. [2/5 deployment(s) still pending]
 - airflow:statefulset/airflow-postgresql is ready. [1/5 deployment(s) still pending]
 - airflow:deployment/airflow-webserver: Liveness probe failed: Get "http://10.244.2.3:8080/health": dial tcp 10.244.2.3:8080: connect: connection refused
    - airflow:pod/airflow-webserver-76f7947c54-c9p6g: Liveness probe failed: Get "http://10.244.2.3:8080/health": dial tcp 10.244.2.3:8080: connect: connection refused
 - airflow:deployment/airflow-webserver is ready.
Deployments stabilized in 11.102 seconds
Port forwarding service/airflow-webserver in namespace airflow, remote port 8080 -> http://127.0.0.1:8080
port forwarding service-airflow-statsd-airflow-9125 got terminated: output: error: UDP protocol is not supported for 9125

Port forwarding service/airflow-postgresql in namespace airflow, remote port 5432 -> http://127.0.0.1:5432
Port forwarding service/airflow-postgresql-hl in namespace airflow, remote port 5432 -> http://127.0.0.1:5433
Port forwarding service/airflow-statsd in namespace airflow, remote port 9102 -> http://127.0.0.1:9102
Port forwarding service/airflow-triggerer in namespace airflow, remote port 8794 -> http://127.0.0.1:8794
Listing files to watch...
 - airflow
Press Ctrl+C to exit
Watching for changes...
Syncing 1 files for airflow:cfde63662cf5b5895f0dddf80b0a0a367803ab16712dd8fab136dcf053f4a8d3
WARN[0291] sync failed for artifact "airflow:cfde63662cf5b5895f0dddf80b0a0a367803ab16712dd8fab136dcf053f4a8d3"  subtask=-1 task=DevLoop
WARN[0291] Skipping deploy due to sync error:copying files: didn't sync any files: sync failed for artifact "airflow:cfde63662cf5b5895f0dddf80b0a0a367803ab16712dd8fab136dcf053f4a8d3"  subtask=-1 task=DevLoop
Watching for changes...
```

### Information

- Skaffold version: v2.6.0
- Operating system: MacOS Venture 13.4.1
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
# skaffold.yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: airflow
      context: ./
      sync:
        manual:
          - src: "dags/**/*.py"
            dest: dags
            strip: dags/
  local:
    useDockerCLI: true
deploy:
  helm:
    releases:
      - name: airflow
        namespace: airflow
        chartPath: helm/airflow
        valuesFiles:
          - "./helm/airflow/values.yaml"
          - "./helm/airflow/values.local.yaml"
        skipBuildDependencies: true
        values:
          airflow.airflow.image: airflow
        setValueTemplates:
          airflow.dags.persistence.enabled: false
          airflow.logs.persistence.enabled: false
          airflow.airflow.config.AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
          airflow.airflow.config.GUNICORN_CMD_ARGS: "--log-level DEBUG"
        imageStrategy:
          helm: {}
portForward:
  - resourceType: service
    resourceName: airflow-webserver
    port: 8080
    localPort: 8080
```
My KIND cluster is provisioned with the following config:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: data-platform-cluster
nodes:
- role: control-plane
  image: &image kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      controllerManager:
          extraArgs:
            cluster-signing-cert-file: /etc/kubernetes/pki/ca.crt
            cluster-signing-key-file: /etc/kubernetes/pki/ca.key
- &workerConfig
  role: worker
  image: *image
  extraMounts:
    - hostPath: .
      containerPath: /data-platform
    - hostPath: ./.kind-pv-data
      containerPath: /var/local-path-provisioner
- *workerConfig
```

### Steps to reproduce the behavior

1. Create a KIND cluster according to the config above.
2. Use the charts from the official Airflow repository apache-airflow https://airflow.apache.org (https://airflow.apache.org/docs/helm-chart/stable/index.html)
3. Use the skaffold.yaml above and run the `skaffold dev --port-forward` and attempt to sync your local DAGs with the deployment
4. The error should appear when trying to sync

I'll happy share the debug logs if it's believed to still be helpful. I believe there's something wrong with my config as I've got the skaffold working with the community helm chart for Airflow https://github.com/airflow-helm/charts. Any help would be greatly appreciated 🙏

**Comment by ericzzzzzzz** [comment]
This seems interesting, could you provide a minimum reproducible project for us to debug? Thanks

**Comment by RossKohler** [comment]
@ericzzzzzzz I created a repository that has everything needed to reproduce the issue I'm experiencing: https://github.com/RossKohler/skaffold-airflow-sync-error. It's very possible that it's a config error that I can't spot, I'm not as familiar with Skaffold as I would like to be in trying to fix this. Would appreciate the extra 👀's on it.

**Comment by ericzzzzzzz** [comment]
Hi @RossKohler , thank you for providing this project. 
There are two issues in this project:
 - The cause of syncing file failure is that the image built by skaffold is not used when installing releases. That means when installing the release, it still use apache:airflow 2.6.2 from your dependency chart. We need to override some values from the chart in skaffold yaml.  The updated version is here: 
 
 ```yaml
# skaffold.yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: airflow
      context: ./
      sync:
        manual:
          - src: "dags/**/*.py"
            dest: dags
            strip: dags/
  local:
    useDockerCLI: true
deploy:
  helm:
    releases:
      - name: airflow
        namespace: airflow
        chartPath: helm/airflow
        valuesFiles:
          - "./helm/airflow/values.yaml"
          - "./helm/airflow/values.local.yaml"
        skipBuildDependencies: true
#        values:
#          airflow.airflow.image: airflow
        setValueTemplates:
          airflow.dags.persistence.enabled: false
          airflow.logs.persistence.enabled: false
          airflow.airflow.config.AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
          airflow.airflow.config.GUNICORN_CMD_ARGS: "--log-level DEBUG"
### add the below two lines
          airflow.images.airflow.repository: "{{.IMAGE_REPO_airflow}}"
          airflow.images.airflow.tag: "{{.IMAGE_TAG_airflow}}@{{.IMAGE_DIGEST_airflow}}"
portForward:
  - resourceType: service
    resourceName: airflow-webserver
    port: 8080
    localPort: 8080
```
 more info about helm image replacement can be found here https://skaffold.dev/docs/deployers/helm/#image-configuration
 - After fixing this, I got some application error, seems like the chart you use requires newer versions of airflow images,
I changed the base image in your dockerfile to `FROM apache/airflow:2.7.0rc1-python3.10` that works for me .

**Comment by RossKohler** [comment]
Thanks for the clarirification @ericzzzzzzz ! One last question, I'm getting confused with all these image references between the charts, the Dockerfile and now this reference. What roles does this one play? My understanding was that the image built locally using the `Dockerfile` is being loaded into the cluster and we'd want to reference that, but the two lines you added make it seem like they're coming from a remote repository?:
```
### add the below two lines
         airflow.images.airflow.repository: "{{.IMAGE_REPO_airflow}}"
         airflow.images.airflow.tag: "{{.IMAGE_TAG_airflow}}@{{.IMAGE_DIGEST_airflow}}"
```

Would a step be required that uploads my image to a remote repository? Sorry I'm not understanding the need for them (or what values to substitute). I would appreciate the clarification :)

**Comment by RossKohler** [comment]
Nevermind @ericzzzzzzz I figured it out 😅 I understand now. The two override values we add just need to reference the image that gets built and loaded into the nodes correctly. So one more thing I need to add to the `skaffold.yaml` is a specific tag for the build, for simplicity just using `latest` should be fine.  So this would be the complete `skaffold.yaml` for anyone who might have this question in the future:
```
# skaffold.yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: airflow-skaffold
      docker:
        dockerfile: Dockerfile
      context: ./
      sync:
        manual:
          - src: "dags/**/*.py"
            dest: dags
            strip: dags/
      
  local:
    push: false
    useDockerCLI: true
deploy:
  helm:
    releases:
      - name: airflow
        namespace: airflow
        chartPath: helm/airflow
        valuesFiles:
          - "./helm/airflow/values.yaml"
          - "./helm/airflow/values.local.yaml"
        skipBuildDependencies: true
        setValueTemplates:
          airflow.dags.persistence.enabled: false
          airflow.logs.persistence.enabled: false
          airflow.airflow.config.AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
          airflow.airflow.config.GUNICORN_CMD_ARGS: "--log-level DEBUG"
          airflow.images.airflow.repository: "airflow-skaffold"
          airflow.images.airflow.tag: "latest"
portForward:
  - resourceType: service
    resourceName: airflow-webserver
    port: 8080
    localPort: 8080
```

All pods start up correctly using this `skaffold.yaml` except for one `airflow-run-airflow-migrations` which still seems to be having a hard time finding the correct image with the `latest` tag. Weirdly, it works fine if I manually add the computed SHA into the override tag  like this:

`airflow.images.airflow.tag: "8120b925ab6cb795e37a9ce5cfe490f740878561df5eed7c260e085bf3d192f0"`

@ericzzzzzzz any ideas?
