### ISSUE TITLE
Homebrew installed Skaffold gives "invalid Host header" error

### ISSUE THREAD

**Issue by habuma** [GoogleContainerTools/skaffold#9019]
### Expected behavior

`skaffold dev`, `skaffold run`, and `skaffold build` should work as expected without undue error.

### Actual behavior

When using Skaffold installed on Mac via Homebrew, those Skaffold commands result in an error like:

```
build [habuma/hello] failed: executing lifecycle: http: invalid Host header
```

I experienced this error on 3 different MacOS machines (one Apple M1, one Apple M1 Pro, and one Intel) and across three different cluster types (Kind, Docker Desktop Kubernetes, and K3D).

After uninstalling Skaffold via Homebrew, I reinstalled from a downloaded binary. It now works as expected.

### Information

- Skaffold version: I tried this with several Skaffold versions, but most recently v2.6.0
- Operating system: MacOS Ventura 13.4.1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: hello-k-s
build:
  artifacts:
    - image: habuma/hello-k8s
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        env:
          - "GOOGLE_RUNTIME_VERSION=17"
        trustBuilder: true
manifests:
  rawYaml:
    - target/classes/META-INF/dekorate/kubernetes.yml
```

(That said, I tried this with several different variations of that skaffold.yaml file and with several different variations of a deployment manifest that I know have worked in the past.)

### Steps to reproduce the behavior

1. Install Skaffold via Homebrew
2. `skaffold dev`, `skaffold run`, or `skaffold build`
3. See error

I no longer have access to such logs after reinstalling Skaffold from the downloaded binary. If deemed necessary, I can reinstall via Homebrew on one of my machines to retrieve debug logs. However, I viewed those logs myself and found nothing of great interest leading up to that error. 

What I did discover, however, was that the underlying "invalid Host header" error seems to be coming from the Docker client. It *might* be related to https://github.com/docker/cli/issues/4437 and/or https://github.com/golang/go/issues/61431. I'll leave the diagnosis to the Skaffold team, but I speculate that the Homebrew version is built against a buggy version of the client, whereas the downloaded binary is built against a fixed version.
