### ISSUE TITLE
Sync Failure on Nested Folders

### ISSUE THREAD

**Issue by RossKohler** [GoogleContainerTools/skaffold#9021]
### Expected behavior
Changing `.py` files anywhere inside a folder structure should trigger a sync to the deployment.

### Actual behavior
Changing `.py` files one level deeper than the root folder given in the `skaffold.yaml` config file results in an error and the file is not synced with the new changes.

The error is as follows:
```
WARN[0138] Skipping deploy due to sync error:copying files: running [kubectl --context kind-airflow-sync-error-cluster exec airflow-webserver-86649d6786-xkb6k --namespace airflow -c webserver -i -- tar xmf - -C / --no-same-owner]
 - stdout: ""
 - stderr: "tar: Removing leading `/' from member names\ntar: opt/airflow/dags/test_folder/test_dag_1.py: Cannot open: File exists\ntar: Exiting with failure status due to previous errors\ncommand terminated with exit code 2\n"
 - cause: exit status 2: sync failed for artifact "airflow-skaffold:1e848fa7f2a293361600329f269d2829fe3ca8c58267195ead78bb8d50de216e"  subtask=-1 task=DevLoop
Watching for changes...
```

### Information

- Skaffold version: v2.6.0
- Operating system: MacOS Venturea 13.4.1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
# skaffold.yaml
apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: airflow-skaffold
      docker:
        dockerfile: Dockerfile
      context: ./
      sync:
        infer:
          - "dags/**/*.py"
          - "dags/**/*.sql"

  local:
    push: false
    useDockerCLI: true
deploy:
  helm:
    releases:
      - name: airflow
        namespace: airflow
        chartPath: helm/airflow
        valuesFiles:
          - "./helm/airflow/values.yaml"
          - "./helm/airflow/values.local.yaml"
        skipBuildDependencies: true
        setValueTemplates:
          airflow.dags.persistence.enabled: false
          airflow.logs.persistence.enabled: false
          airflow.airflow.config.AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
          airflow.airflow.config.GUNICORN_CMD_ARGS: "--log-level DEBUG"
          airflow.images.airflow.repository: "{{.IMAGE_REPO_airflow_skaffold}}"
          airflow.images.airflow.tag: "{{.IMAGE_TAG_airflow_skaffold}}@{{.IMAGE_DIGEST_airflow_skaffold}}"
portForward:
  - resourceType: service
    resourceName: airflow-webserver
    port: 8080
    localPort: 8080

```

### Steps to reproduce the behavior

Create a minimal repository that can be used to reproduce the issue. Find it here https://github.com/RossKohler/skaffold-airflow-sync-error.
