### ISSUE TITLE
Assign NULL in deploy.helm.releases.[0].setValueTemplates

### ISSUE THREAD

**Issue by YunanJeong** [GoogleContainerTools/skaffold#9066]
### Expected behavior
I wanted to use `skaffold dev`, after temporarily removing some defaults in the Helm template.
(e.g. `nodeSelector`)

In the skaffold.yaml below,
Expected behavior is that the nodeSelector statement is deleted, when `null` or `{}` is assigned to `deploy.helm.releases.[0].setValueTemplates.nodeSelector`.

### Actual behavior
`"null"`, `""` works correctly
`null`, `{}`, `"{}"` doesn't work

### Information

- Skaffold version: v2.6.0-1-gb25a5ed52
- Operating system: Ubuntu 22 LTS
- Installed via: Cloud Code
- Contents of skaffold.yaml:
```yaml
# my helm template
      (...)

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      (...)
```

```yaml
# my default helm values
(...)
nodeSelector:
  my-node: worker
(...)
```
```yaml
# skaffold.yaml
(...)
  - name: alpha                               
    patches:
      - op: add
        path: /deploy/helm/releases
        value:
          - name: my-release                
            (...)
            setValueTemplates:
              nodeSelector: "null"  # PASS: "null", ""  # FAIL: {}, "{}", null  
(...)
```

### P.S.
- Is this the original intended feature of skaffold?
- If you know related docs or issue numbers, please let me know.
Thank you
