### ISSUE TITLE
Container deploy hooks only executes the first element from the list

### ISSUE THREAD

**Issue by renzodavid9** [GoogleContainerTools/skaffold#9076]
### Expected behavior
The whole list of hooks to be executed

### Actual behavior
When two or more container deploy hooks are configured to run in the same pod + container, only the first one is executed, the others are ignored.

### Information

- Skaffold version: v2.7.0
- Operating system: all
- Contents of skaffold.yaml:
Using the examples/getting-started project, replace the yaml file with this:
```yaml
apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
  - image: skaffold-example
manifests:
  rawYaml:
  - k8s-pod.yaml

deploy:
  kubectl:
    hooks:
      after:
      - container:
          command: ["echo", "container-hook-1"]
          containerName: getting-started
          podName: getting-started*
      - container:
          command: ["echo", "container-hook-2"]
          containerName: getting-started
          podName: getting-started*

```

### Steps to reproduce the behavior

1. With the previous configuration, using the examples/getting-started project
2. Run `skaffold run`
3. You'll see only the first hook is executed:
```
Generating tags...
 - skaffold-example -> skaffold-example:v2.7.0-8-gbca77a4f2-dirty
Checking cache...
 - skaffold-example: Found Locally
Starting test...
Tags used in deployment:
 - skaffold-example -> skaffold-example:44a6ed8a74fae4eff0c69a9892d4c27c1acb5a44963a8543d8601fc0c9d8375f
Starting deploy...
Loading images into kind cluster nodes...
 - skaffold-example:44a6ed8a74fae4eff0c69a9892d4c27c1acb5a44963a8543d8601fc0c9d8375f -> Found
Images loaded in 61.163041ms
 - pod/getting-started created
Waiting for deployments to stabilize...
 - pods is ready.
Deployments stabilized in 2.078 seconds
Starting post-deploy hooks...
[getting-started] container-hook-1
Completed post-deploy hooks
You can also run [skaffold run --tail] to get the logs
```
