### ISSUE TITLE
How to rebuild all targets forcefully?

### ISSUE THREAD

**Issue by k82cn** [GoogleContainerTools/skaffold#9082]
### Expected behavior

Rebuild all target on-demand

### Actual behavior

One of target can not rebuild.

### Information

- Skaffold version: v2.6.0
- Operating system: Ubuntu:20.04
- Installed via: manually
- Contents of skaffold.yaml:

```yaml
    - image: registry.minikube/xflops-pxe
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.pxe.localdev
      sync:
        infer:
          - "xflops"
          - pxe/templates/*
          - pxe/static/*
```

### Steps to reproduce the behavior

```
$ skaffold build 
Generating tags...
 - registry.minikube/xflops-dns -> registry.minikube/xflops-dns:latest
 - registry.minikube/xflops-pxe -> registry.minikube/xflops-pxe:latest
 - registry.minikube/xflops-api -> registry.minikube/xflops-api:latest
 - registry.minikube/xflops-dhcp -> registry.minikube/xflops-dhcp:latest
Checking cache...
 - registry.minikube/xflops-dns: Not found. Building
 - registry.minikube/xflops-pxe: Error checking cache.
getting hash for artifact "registry.minikube/xflops-pxe": getting dependencies for "registry.minikube/xflops-pxe": file pattern [.skaffold/target/xflops-pxe/debug/xflops] must match at least one file
```
