### ISSUE TITLE
skaffold build with "useDockerCLI: true" and local cluster does not create image with proper tag. 

### ISSUE THREAD

**Issue by mmx86** [GoogleContainerTools/skaffold#9085]
I'm using rancher-desktop as local cluster. And I cannot make my deployment to work. Pod in rancher cannot find the image (because it really isn't there). 
**skaffold.yaml**
```yaml
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: dsp

build:
  artifacts:
    - context: .
      image: dsp-test
  local:
    push: false
    useDockerCLI: true

manifests:
  rawYaml:
    - ./deployment.yaml
```
**deployment.yaml**
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsp-test
spec:
  selector:
    matchLabels:
      app: dsp-test
  template:
    metadata:
      labels:
        app: dsp-test
    spec:
      containers:
        - image: dsp-test
          name: dsp-test
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
```
**Dockerfile**
```yaml
FROM crccheck/hello-world
```
**~/.skaffold/config**
```yaml
global:                        
  local-cluster: true
  survey:
    last-prompted: "2023-09-08T10:36:29+03:00"
  collect-metrics: false
  update:
    last-prompted: "2023-09-11T16:38:21+03:00"
kubeContexts: []
```
**skaffold dev**
```
Generating tags...                                          
 - dsp-test -> dsp-test:latest
Some taggers failed. Rerun with -vdebug for errors.
Checking cache...
 - dsp-test: Not found. Building
Starting build...
Found [rancher-desktop] context, using local docker daemon.
Building [dsp-test]...
Target platforms: [linux/amd64]
#0 building with "rancher-desktop" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 64B 0.0s done
#1 DONE 0.1s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.2s

#3 [internal] load metadata for docker.io/crccheck/hello-world:latest
#3 DONE 6.0s

#4 [1/1] FROM docker.io/crccheck/hello-world@sha256:0404ca69b522f8629d7d4e9034a7afe0300b713354e8bf12ec9657581cf59400
#4 resolve docker.io/crccheck/hello-world@sha256:0404ca69b522f8629d7d4e9034a7afe0300b713354e8bf12ec9657581cf59400 0.0s done
#4 sha256:0404ca69b522f8629d7d4e9034a7afe0300b713354e8bf12ec9657581cf59400 734B / 734B done
#4 sha256:24349d78cb62b52f99af125f18ada6149df5ed7fe6bdeb286004412a202c270d 2.34kB / 2.34kB done
#4 sha256:e685c5c858e36338a47c627763b50dfe6035b547f1f75f0d39753db71e319016 0B / 772.79kB 0.2s
#4 sha256:7bf3c383dbcd4f16e7b52a83f2c93e7d29cf4fce4ba19cfda5db91f236a493f9 0B / 259B 0.2s
#4 extracting sha256:e685c5c858e36338a47c627763b50dfe6035b547f1f75f0d39753db71e319016
#4 sha256:e685c5c858e36338a47c627763b50dfe6035b547f1f75f0d39753db71e319016 772.79kB / 772.79kB 0.6s done
#4 sha256:7bf3c383dbcd4f16e7b52a83f2c93e7d29cf4fce4ba19cfda5db91f236a493f9 259B / 259B 0.6s done
#4 extracting sha256:e685c5c858e36338a47c627763b50dfe6035b547f1f75f0d39753db71e319016 0.1s done
#4 extracting sha256:7bf3c383dbcd4f16e7b52a83f2c93e7d29cf4fce4ba19cfda5db91f236a493f9 done
#4 DONE 1.2s

#5 exporting to image
#5 exporting layers done
#5 writing image sha256:2ab9825dec1b2b605ea4f38b24a700effe807241092d2ba515c65caddd571e8f 0.0s done
#5 naming to docker.io/library/dsp-test:latest 0.0s done
#5 DONE 0.1s
Build [dsp-test] succeeded
Tags used in deployment:
 - dsp-test -> dsp-test:24349d78cb62b52f99af125f18ada6149df5ed7fe6bdeb286004412a202c270d
Starting deploy...
 - deployment.apps/dsp-test created
Waiting for deployments to stabilize...
 - deployment/dsp-test: creating container dsp-test
    - pod/dsp-test-785678c8cf-lps68: creating container dsp-test
 - deployment/dsp-test: container dsp-test is waiting to start: dsp-test:24349d78cb62b52f99af125f18ada6149df5ed7fe6bdeb286004412a202c270d can't be pulled
    - pod/dsp-test-785678c8cf-lps68: container dsp-test is waiting to start: dsp-test:24349d78cb62b52f99af125f18ada6149df5ed7fe6bdeb286004412a202c270d can't be pulled
 - deployment/dsp-test failed. Error: container dsp-test is waiting to start: dsp-test:24349d78cb62b52f99af125f18ada6149df5ed7fe6bdeb286004412a202c270d can't be pulled.
Cleaning up...
 - deployment.apps "dsp-test" deleted
1/1 deployment(s) failed
```
It can't be pulled because such tag (`24349d78cb62b52f99af125f18ada6149df5ed7fe6bdeb286004412a202c270d`) hasn't been cretated in rancher-desktop context:
```
 » docker -c rancher-desktop images                        [c6b0d57]
REPOSITORY                                          TAG                    IMAGE ID       CREATED             SIZE
rancher/klipper-helm                                v0.8.2-build20230815   5f89cb8137cc   3 weeks ago         256MB
rancher/klipper-lb                                  v0.4.4                 af74bd845c4a   3 months ago        12MB
rancher/mirrored-library-traefik                    2.9.10                 d1e26b5f8193   5 months ago        138MB
rancher/local-path-provisioner                      v0.0.24                b29384aeb4b1   5 months ago        40.1MB
rancher/mirrored-metrics-server                     v0.6.3                 817bbe3f2e51   5 months ago        68.9MB
rancher/mirrored-coredns-coredns                    1.10.1                 ead0a4a53df8   7 months ago        53.6MB
rancher/mirrored-library-busybox                    1.34.1                 827365c7baf1   8 months ago        4.86MB
dsp-test                                            latest                 2ab9825dec1b   22 months ago       1.24MB
rancher/mirrored-pause                              3.6                    6270bb605e12   2 years ago         683kB
ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy   latest                 9d111955b096   292 years ago       5.1MB
```
If I remove  `useDockerCLI: true` in `skaffold.yaml`, then it creates two tags for this image, but in the default context:
```
docker -c default images        
REPOSITORY                     TAG                                      
                          IMAGE ID       CREATED          SIZE
dsp-test                       24349d78cb62b52f99af125f18ada6149df5ed7fe6bdeb286004412a202c270d   24349d78cb62   22 months ago    1.24MB
dsp-test                       latest                                                             24349d78cb62   22 months ago    1.24MB
```
- Skaffold version: 2.6.3
- Operating system: archlinux
- Installed via: pacman

[skaffold-test.tar.gz](https://github.com/GoogleContainerTools/skaffold/files/12577101/skaffold-test.tar.gz)
