### ISSUE TITLE
Testing pod fails

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [GoogleContainerTools/skaffold#9108]
### Expected behavior

Testing should just succeed

### Actual behavior

Testing fails

### Information

- Skaffold version: 2.7.0
- Operating system: Ubuntu 22.04
- Installed via: skaffold run
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: grafana
manifests:
  helm:
    releases:
      - name: grafana
        remoteChart: grafana
        namespace: monitoring
        version: 6.60.1
deploy:
  kubectl:
    defaultNamespace: monitoring
```

Grafana has a test pod. The pod succeeds but is then not marked as ready once successful.
Thus Skaffold prints:

> pods: pods not ready: [grafana-test]

### Steps to reproduce the behavior

1. `skaffold run`

**Comment by pydolan** [comment]
As noted by https://github.com/GoogleContainerTools/skaffold/issues/8515#issuecomment-1494738139, remote chart releases should be in `deploy` instead of `manifests`. With this, you can also remove the kubctl section; for example:

```yaml
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: grafana
deploy:
  helm:
    releases:
      - name: grafana
        repo: https://grafana.github.io/helm-charts
        remoteChart: grafana
        version: 6.60.1
        namespace: monitoring
        createNamespace: true
```

Side note to skaffold team: please add a note about this to https://skaffold.dev/docs/references/yaml/ (I also struggled with this for far too long!)
