### ISSUE TITLE
failed to apply profiles to config

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [GoogleContainerTools/skaffold#9110]
### Expected behavior

There should not be an error.

### Actual behavior

Just gives an error message:

> parsing skaffold config: failed to apply profiles to config "monitoring" defined in file "/code/skaffold_monitoring.yaml": applying profile "tst": invalid path: /manifests/helm/releases/0/setValues/serviceAccount/annotations. There's an issue with one of the profiles defined in config "monitoring" in file "/code/skaffold_monitoring.yaml"; refer to the documentation on how to author valid profiles: https://skaffold.dev/docs/environment/profiles/.

### Information

- Skaffold version: v2.8.0
- Operating system: Ubuntu 22.04
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: all
requires:
  - path: skaffold_monitoring.yaml
```

skaffold_monitoring.yaml:
```yaml
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: monitoring
manifests:
  helm:
    releases:
      - name: grafana
        remoteChart: grafana
        namespace: monitoring
        version: 6.60.2
        setValues:
          deploymentStrategy.type: Recreate
          persistence.enabled: "true"
          plugins[0]: grafana-bigquery-datasource
          rbac.namespaced: "true"
          serviceAccount.annotations: {}
          # Needed to disable tests since Skaffold 2.7.1 cannot handle them properly
          testFramework.enabled: "false"
        createNamespace: true
        skipBuildDependencies: true
        repo: https://grafana.github.io/helm-charts
deploy:
  kubectl:
    defaultNamespace: monitoring
profiles:
  - name: dev
    patches:
      - op: replace
        path: /manifests/helm/releases/0/setValues/serviceAccount/annotations
        value:
          iam.gke.io/gcp-service-account: grafana@foo-dev.iam.gserviceaccount.com
    deploy:
      kubeContext: gke_foo-dev_europe-west1_bar
  - name: prd
    patches:
      - op: replace
        path: /manifests/helm/releases/0/setValues/serviceAccount/annotations
        value:
          iam.gke.io/gcp-service-account: grafana@foo-prd.iam.gserviceaccount.com
    deploy:
      kubeContext: gke_foo-prd_europe-west1_bar
  - name: tst
    patches:
      - op: replace
        path: /manifests/helm/releases/0/setValues/serviceAccount/annotations
        value:
          iam.gke.io/gcp-service-account: grafana@foo-tst.iam.gserviceaccount.com
    deploy:
      kubeContext: gke_foo-tst_europe-west1_bar

```

From looking at the code it might be related to internal marshalling before passing the config into the patching library.

### Steps to reproduce the behavior

1. `skaffold build -p tst`
