### ISSUE TITLE
helm gets passed quoted values wrong

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [GoogleContainerTools/skaffold#9111]
### Expected behavior

Quoted values should be passed to helm as quoted.

```
env:
  value: "true"
```

### Actual behavior

`--set api.deployment.sidecars[0].env[3].value=true`

### Information

- Skaffold version: v2.7.1
- Operating system: Ubuntu 22.04
- Installed via: apt
- Contents of skaffold.yaml:

```yaml
manifests:
      helm:
        releases:
          - name: codecov
            chartPath: helm-charts/codecov
            namespace: codecov
            setValues:
              api.deployment.sidecars[0].env[1].name: CSQL_PROXY_HEALTH_CHECK
              api.deployment.sidecars[0].env[1].value: "true"
              api.deployment.sidecars[0].env[2].name: CSQL_PROXY_PROMETHEUS
              api.deployment.sidecars[0].env[2].value: "true"
              api.deployment.sidecars[0].env[3].name: CSQL_PROXY_STRUCTURED_LOGS
              api.deployment.sidecars[0].env[3].value: "true"
```

### Steps to reproduce the behavior

1. `skaffold render`

> DEBU[0000] Running command: [helm --kube-context gke_foo-dev_europe-west1_bar template codecov helm-charts/codecov --set api.deployment.sidecars[0].env[0].name=CSQL_PROXY_INSTANCE_CONNECTION_NAME --set api.deployment.sidecars[0].env[0].value=foo-dev:europe-west1:codecov --set api.deployment.sidecars[0].env[1].name=CSQL_PROXY_HEALTH_CHECK --set api.deployment.sidecars[0].env[1].value=true --set api.deployment.sidecars[0].env[2].name=CSQL_PROXY_PROMETHEUS --set api.deployment.sidecars[0].env[2].value=true --set api.deployment.sidecars[0].env[3].name=CSQL_PROXY_STRUCTURED_LOGS --set api.deployment.sidecars[0].env[3].value=true --set api.deployment.sidecars[0].image=eu.gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.6.1 --set api.deployment.sidecars[0].livenessProbe.httpGet.path=/liveness --set api.deployment.sidecars[0].livenessProbe.httpGet.port=proxy-health --set api.deployment.sidecars[0].name=cloud-sql-proxy --set api.deployment.sidecars[0].ports[0].containerPort=5432 --set api.deployment.sidecars[0].ports[0].name=cloud-sql-proxy --set api.deployment.sidecars[0].ports[0].protocol=TCP --set api.deployment.sidecars[0].ports[1].containerPort=9090 --set api.deployment.sidecars[0].ports[1].name=proxy-health --set api.deployment.sidecars[0].ports[1].protocol=TCP --set api.deployment.sidecars[0].readinessProbe.httpGet.path=/readiness --set api.deployment.sidecars[0].readinessProbe.httpGet.port=proxy-health --set api.deployment.sidecars[0].resources.limits.cpu=500m --set api.deployment.sidecars[0].resources.limits.ephemeral-storage=1Gi --set api.deployment.sidecars[0].resources.limits.memory=536432Ki --set api.deployment.sidecars[0].resources.requests.cpu=500m --set api.deployment.sidecars[0].resources.requests.ephemeral-storage=1Gi --set api.deployment.sidecars[0].resources.requests.memory=536432Ki --set api.resources.limits.cpu=250m --set api.resources.limits.ephemeral-storage=1Gi --set api.resources.limits.memory=256M --set api.resources.requests.cpu=250m --set api.resources.requests.ephemeral-storage=1Gi --set api.resources.requests.memory=256M --set api.serviceAccount.annotations.iam\.gke\.io/gcp-service-account=codecov-api@foo-dev.iam.gserviceaccount.com --set codecovConfig.services.database_url=postgres://codecov@172.22.2.3:5432/postgres --set codecovConfig.services.minio.bucket=codecov --set codecovConfig.services.minio.host=storage.googleapis.com --set codecovConfig.services.minio.port=443 --set codecovConfig.services.minio.region=europe-west1 --set codecovConfig.services.minio.verify_ssl=true --set codecovConfig.services.redis_url=redis://172.22.0.19:6379 --set codecovConfig.services.timeseries_database_url=postgres://postgres:testpassword@timescale:5432/postgres --set codecovConfig.setup.codecov_url=https://codecov.foo.de --set codecovConfig.setup.enterprise_license=F5O0Fu5ASFTPtWXM51BK8YQlq7IM2s+8TBGULrf9Um7wHjfPwI+Z3E4PfF/dPs6Uc5A+MLti+2etHq5dnFEfZgoiIVCLZ8x+0BVmUSWwPS42vJXnf1veY9Bglang4mDIhmfWfp5l6AT6cxmAVFpGrwobiK6OcN9pjWx4iWabazmsOiF9LM++v0WtuHNvhgzRcKmnJPgqahEB7qqF6KQ1hg== --set codecovVersion=v5.0.1 --set frontend.deployment.resources.limits.cpu=500m --set frontend.deployment.resources.limits.ephemeral-storage=1Gi --set frontend.deployment.resources.limits.memory=536870912 --set frontend.deployment.resources.requests.cpu=500m --set frontend.deployment.resources.requests.ephemeral-storage=1Gi --set frontend.deployment.resources.requests.memory=536870912 --set github.client_id=Iv1.67c27fb8e5c8dd8e --namespace codecov]  subtask=1 task=Render
