### ISSUE TITLE
Support set-json for helm

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [GoogleContainerTools/skaffold#9112]
Skaffold uses a very magicy yaml library.
This makes it often very hard/impossible to pass boolean/numeric values to helm as a strings.

Supporting passing raw (uninterpreted) json values to `helm` via `--set-json` should fix that.

And example could be:

```yaml
manifests:
  helm:
    releases:
    - name: foo
      setJsonValues: {port: "345"}
```

This of course only works if one can force the yaml library to handle values of `setJsonValues` always as strings.
Alternatively one could add an escape hatch via a release-specific `flags`:

```yaml
manifests:
  helm:
    releases:
    - name: foo
      flags:
      - --set-json={"port": "345"}

```
