### ISSUE TITLE
Set value for map

### ISSUE THREAD

**Issue by phuongnt287** [GoogleContainerTools/skaffold#912]
I cannot override annotations value in value.yaml which is in map format as below:
```
    ingress:
      annotations:
        kubernetes.io/ingress.allow-http: "false"
        nginx.ingress.kubernetes.io/proxy-body-size: "30m"
        nginx.ingress.kubernetes.io/client-max-body-size: "30m"
```
### Actual behavior
cannot unmarshal !!map into string
### Information

- Skaffold version: v0.7.0
- Operating system: ubuntu
- Contents of skaffold.yaml:

```
setValues:
  ingress.annotations:
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/client-max-body-size: "50m"
```

**Comment by balopat** [comment]
I think you wanted to use `overrides` instead of `setValues`.

```
      overrides:
        ingress:
             annotations:
                  kubernetes.io/ingress.allow-http: "true"
                  nginx.ingress.kubernetes.io/proxy-body-size: "50m"
                  nginx.ingress.kubernetes.io/client-max-body-size: "50m"

```

Does this help?
