### ISSUE TITLE
Could not get docker context

### ISSUE THREAD

**Issue by userbradley** [GoogleContainerTools/skaffold#9121]
When using skaffold to render and deploy helm charts, and docker is not installed, when running `skaffold -p dev deploy` I get the below error

```
➜ skaffold -p dev deploy
WARN[0000] Could not get docker context: starting command docker context inspect --format {{.Endpoints.docker.Host}}: exec: "docker": executable file not found in $PATH, falling back to the default docker host  subtask=-1 task=DevLoop
Starting deploy...
Error: UPGRADE FAILED: error while running post render on files: error while running command /opt/homebrew/bin/skaffold. error output:
time="2023-10-08T23:59:24+01:00" level=warning msg="Could not get docker context: starting command docker context inspect --format {{.Endpoints.docker.Host}}: exec: \"docker\": executable file not found in $PATH, falling back to the default docker host" subtask=-1 task=DevLoop
missing Resource metadata
: exit status 1
deploying "data-portal": install: exit status 1

```

### Expected behavior

Skaffold continues as usual and doesnt care that docker isnt installed

### Actual behavior

Skaffold throws a fit

### Information

- Skaffold version: v2.8.0
- Operating system: `Darwin l 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64
`
- Installed via: Homebrew 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: redacted
profiles:
  - name: dev
    deploy:
      kubeContext: prd
      helm:
        releases:
          - name: redacted
            namespace: redacted-dev
           # remoteChart: redacted/redacted
            chartPath: ../../helm-charts/redacted/chart
            version: 0.3.0
            upgradeOnChange: true
            setValues:
              redacted:
                mountGcs: false
                image:
                  tag: dev
              env: dev
            setValueTemplates:
              redacted:
                config:
                  auth:
                    clientSecret: "{{.AZURE_CLIENT_SECRET}}"
  - name: test
    deploy:
      kubeContext: prd
      helm:
        releases:
          - name: redacted
            namespace: redacted-test
            remoteChart: redacted/redacted
            version: 0.3.0
            upgradeOnChange: true
            setValues:
              redacted:
                mountGcs: false
                image:
                  tag: dev
              env: dev
            setValueTemplates:
              redacted:
                config:
                  auth:
                    clientSecret: "{{.AZURE_CLIENT_SECRET}}"
  - name: prd
    deploy:
      kubeContext: prd
      helm:
        releases:
          - name: redacted
            namespace: redacted-prd
            remoteChart: redacted/redacted
            version: 0.3.0
            upgradeOnChange: true
            setValues:
              redacted:
                mountGcs: false
                image:
                  tag: 9d0e698
              env: dev
            setValueTemplates:
              redacted:
                config:
                  auth:
                    clientSecret: "{{.AZURE_CLIENT_SECRET}}"

```

### Steps to reproduce the behavior

1. Install podman
2. Install skaffold version 2.8
3. Run skaffold -p dev deploy
