### ISSUE TITLE
Kustomize Manifest is ignored when only helm deployer is specified

### ISSUE THREAD

**Issue by bellis-ai** [GoogleContainerTools/skaffold#9134]
### Expected behavior
If I specify kustomize manifests in the `manifests` block, and specify an exterior helm chart (i.e. postgres, redis, or some other db, which is specified in the `deploy` section), both the manifests and the helm chart are deployed

### Actual behavior
The kustomize resources specified in the `manifests` section are ignored, unless the `kubectl` deployer is otherwise specified.

Note: If kustomize is not used and instead rawYaml is passed in, the manifests section is NOT ignored... which makes this very strange.

### Information

- Skaffold version: v2.8.0
- Operating system: Ubuntu 20.04.4 LTS on WSL2, 5.10.102.1-microsoft-standard-WSL2
- Installed via: skaffold.dev (command line)
- Contents of skaffold.yaml:

```yaml
kind: Config
metadata:
  name: helmtest
manifests:
  rawYaml:
    - pod.yaml
deploy:
  kubeContext: custom
  helm:
    releases:
      # https://artifacthub.io/packages/helm/bitnami/redis
      - name: redis
        createNamespace: true
        remoteChart: redis
        repo: "https://charts.bitnami.com/bitnami"
        setValues:
          "master.persistence.enabled": "true"
          "replica.replicaCount": "1"
```

### Steps to reproduce the behavior
0. Follow the steps in the tutorial to init minikube
    - minikube start --profile custom
    - skaffold config set --global local-cluster true
    - eval $(minikube -p custom docker-env)
2. Pull the repo: https://github.com/bellis-ai/skaffold-kustomize-fail
3. `skaffold dev`
4. Only the redis cluster is created. The file from the kustomize directory is not created

### Temporary Workaround
Add kubectl deployer to config

```yaml
kind: Config
metadata:
  name: helmtest
manifests:
  rawYaml:
    - pod.yaml
deploy:
  kubeContext: custom
  kubectl: {}
  helm:
    releases:
      # https://artifacthub.io/packages/helm/bitnami/redis
      - name: redis
        createNamespace: true
        remoteChart: redis
        repo: "https://charts.bitnami.com/bitnami"
        setValues:
          "master.persistence.enabled": "true"
          "replica.replicaCount": "1"
```

-->
