### ISSUE TITLE
[Custom Actions] New config option to check images in local host before pull

### ISSUE THREAD

**Issue by renzodavid9** [GoogleContainerTools/skaffold#9139]
### Actual behavior
Right now, when we run a [local custom action](https://skaffold.dev/docs/custom-actions/#local-docker), Skaffold will trigger a pull of the image every single time, e.g:

With this `skaffold.yaml`
```yaml
apiVersion: skaffold/v4beta7
kind: Config

customActions:
  - name: action
    containers:
      - name: alpine-task
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "echo From action"]
```

Executing `skaffold exec action` will produce the following logs:
```
Starting execution for action
latest: Pulling from library/alpine
Digest: sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978
Status: Image is up to date for alpine:latest
[alpine-task] From action
```
The previous log indicates that Skaffold is triggering a pull of the `alpine` image, even when the image is already in the local host.

### Expected behavior
We want to add a new config option to prevent Skaffold to trigger the pull of the images every single time for a given [local custom action](https://skaffold.dev/docs/custom-actions/#local-docker). Per default (no config set explicitly), Skaffold should keep its current behavior and trigger the pull every time an action is run. With the new config option set in the `skaffold.yaml` Skaffold should first check if the images of the custom action exist in the local host before triggering a pull.
