### ISSUE TITLE
caused ValidationError only Jobs when use helm

### ISSUE THREAD

**Issue by naruse666** [GoogleContainerTools/skaffold#9145]
### Expected behavior
No errors.

### Actual behavior
caused `ValidationError` only Jobs resource.

### Information

- Skaffold version: v2.8.0
- Operating system: macOS ventura 13.5
- Installed via: homebrew
- Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: job
manifests:
  helm:
    releases:
    - name: jobs
      chartPath: ./jobs
```

#### Jobs manifest (helm chart) as `jobs.yaml`
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    metadata:
      labels:
        {{- include "jobs.labels" . | nindent 4 }}  # This is cause error
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

#### _helpers.tpl
default generated by `helm create`.

### Error message
```
- error: error validating "STDIN": error validating data: [
ValidationError(Job.spec.template): unknown field "app.kubernetes.io/instance" in io.k8s.api.core.v1.PodTemplateSpec, 
ValidationError(Job.spec.template): unknown field "app.kubernetes.io/managed-by" in io.k8s.api.core.v1.PodTemplateSpec, 
ValidationError(Job.spec.template): unknown field "app.kubernetes.io/name" in io.k8s.api.core.v1.PodTemplateSpec, 
ValidationError(Job.spec.template): unknown field "app.kubernetes.io/version" in io.k8s.api.core.v1.PodTemplateSpec, 
ValidationError(Job.spec.template): unknown field "helm.sh/chart" in io.k8s.api.core.v1.PodTemplateSpec]; 
if you choose to ignore these errors, turn validation off with --validate=false
```

### Steps to reproduce the behavior

1. execute `helm create <name>`
2. copy `jobs.yaml` to `template/`. don't need other yaml.
3. execute `skaffold dev`

### Additional Information
doesn't cause error on other resource. like this.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        {{- include "jobs.labels" . | nindent 4 }}  # no errors
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

Why this error caused?
