### ISSUE TITLE
[Verify] New config option to check images in local host before pull

### ISSUE THREAD

**Issue by renzodavid9** [GoogleContainerTools/skaffold#9148]
### Actual behavior
(Similar to #9139)
Right now, when we run a local verify test case, Skaffold will trigger a pull of the image every single time, e.g:

With this skaffold.yaml
```yaml
apiVersion: skaffold/v4beta7
kind: Config

verify:
  - name: my-action
    container:
      name: gcloud-task
      image: gcr.io/cloud-builders/gcloud:latest
      command: ["/bin/sh"]
      args: ["-c", "gcloud version"]
```
Executing `skaffold verify` will produce the following logs:

```
latest: Pulling from cloud-builders/gcloud
Digest: sha256:0d6d21ed135170e723e982ce3a74b40255323dab446af149f51d73792a46d4eb
Status: Image is up to date for gcr.io/cloud-builders/gcloud:latest
...
```
The previous log indicates that Skaffold is triggering a pull of the gcloud image, even when the image is already in the local host.

### Expected behavior
Same as described in #9139
