### ISSUE TITLE
kaniko in-cluster build: pulling kaniko images from private registry w/ image pull secret

### ISSUE THREAD

**Issue by dherges** [GoogleContainerTools/skaffold#9170]
### Expected behavior

Pull the kaniko [image](https://skaffold.dev/docs/references/yaml/#build-artifacts-kaniko-image) and [imitImage](https://skaffold.dev/docs/references/yaml/#build-artifacts-kaniko-initImage) from a private registry with pull secret credentials

The private registry requires an [`imagePullSecret`](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L3592-L3598) for the [kaniko pod spec](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/build/cluster/pod.go#L59)

The `dockerConfig.secretName` and `pullSecretName` are only mounted inside the kaniko pod, if i understand correctly. The use case described by me would require a pull secret for the kaniko images itself.

For my personal use case, it would solve the issue [if the `cluster.pullSecretName` was also added to the kaniko `PodSpec`](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/build/cluster/pod.go#L88-L91):

```go
	// Add secret for pull secret
	if b.ClusterDetails.PullSecretName != "" {
		addSecretVolume(pod, kaniko.DefaultSecretName, b.ClusterDetails.PullSecretMountPath, b.ClusterDetails.PullSecretName)

		pod.Spec.ImagePullSecrets = []v1.LocalObjectReference{{
			Name: b.ClusterDetails.PullSecretName,
		}}
	}
```

Could that be added as a general option?`What do you think?

### Actual behavior

Failed to pull image "private.registry.com/k8s-skaffold/skaffold-helpers/busybox": rpc error: code = Unknown desc = failed to pull and unpack image "private.registry.com/k8s-skaffold/skaffold-helpers/busybox": failed to resolve reference "private.registry.com/k8s-skaffold/skaffold-helpers/busybox": **failed to authorize: failed to fetch anonymous token:
 unexpected status: 401**

### Information

- Skaffold version: v2.8.0
- Operating system: Windows 7
- Installed via: skaffold.dev standalone executable
- Contents of skaffold.yaml: 

```yaml
build:
  artifacts:
    - image: private.registry.com/myapp
      kaniko: 
        initImage: private.registry.com/k8s-skaffold/skaffold-helpers/busybox
        image: private.registry.com/kaniko-project/executor
  cluster:
    dockerConfig:
      secretName: private-registry-push
    pullSecretName: private-registry-pull
```

### Steps to reproduce the behavior

1. a private container registry at `private.registry.com` that requires token authentication for pulling images
2. `skaffold build`

```
time="2023-11-10T10:35:02+01:00" level=info msg="Waiting for kaniko-m8x5s to be initialized" subtask=private.registry.com/myapp task=Build copying sources: waiting for pod to initialize: context deadline exceeded
```

**Comment by dherges** [comment]
The private registry requires an [`imagePullSecret`](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L3592-L3598) for the [kaniko pod spec](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/build/cluster/pod.go#L59)

The dockerConfig.secretName and pullSecretName are only mounted inside the kaniko pod, if i understand correctly. The use case described by me would require a pull secret for the kaniko images itself.

**Comment by dherges** [comment]
I let ChatGPT try very hard, here's what it had to say... 
[chat.txt](https://github.com/GoogleContainerTools/skaffold/files/13318357/chat.txt)

**Comment by dherges** [comment]
FOr my personal use case, it would solve the issue [if the `cluster.pullSecretName` was also added to the kaniko `PodSpec`](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/build/cluster/pod.go#L88-L91):


```go
	// Add secret for pull secret
	if b.ClusterDetails.PullSecretName != "" {
		addSecretVolume(pod, kaniko.DefaultSecretName, b.ClusterDetails.PullSecretMountPath, b.ClusterDetails.PullSecretName)

		pod.Spec.ImagePullSecrets = []v1.LocalObjectReference{{
			Name: b.ClusterDetails.PullSecretName,
		}}
	}
```

**Comment by dherges** [comment]
There is one solution to the issue in current version of skaffold already supported:

Create a service account in the kubernetes cluster, reference the image-pull-secret

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skaffold
imagePullSecrets:
- name: my-image-pull-secret
```

like here explained in k8s docs: [Pull an Image from a Private Registry](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials)

in skaffold.yaml, let the service account create the kaniko pod:

```yaml
apiVersion: skaffold/v4beta11
kind: Config
build:
  cluster:
    serviceAccount: skaffold
```

That service account should do it!
