### ISSUE TITLE
(Feature Request) Support ValueFile from Google Cloud Stroage 

### ISSUE THREAD

**Issue by asubramanianrl** [GoogleContainerTools/skaffold#9172]
### Expected behavior

Skaffold should read the ValueFile from Google Storage Bucket as well(with Application Default Credential)

```yaml
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - env-values/dev-values.yaml
          - external-configuration/env-values/dev-values.yaml
          - gs://XXXX/ops.yaml
```

### Actual behavior
We hold the infrastructure-related information in the Storage Bucket and it must be available publicly to pass it to the Helm.  Due to security reasons, we want to block the public usage of this bucket.  At the moment, we will have a workaround to download this file using the prehook and pass it with the local path.

```yaml
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - env-values/dev-values.yaml
          - global/env-values/dev-values.yaml
          - https://storage.googleapis.com/XXXX/ops.yaml
```
