### ISSUE TITLE
render image name in other fields for rawyaml

### ISSUE THREAD

**Issue by cristifalcas** [GoogleContainerTools/skaffold#9175]
### Expected behavior

Currently we save generated sha strings for images in a configmap (with rules_k8s).
They are used in order to start pods with the correct image via a custom tool we have. 

We would like to use scaffold for deploys, but we need the generated image sha to be replaced in other places as well (at least config map data).

### Actual behavior

We can't render the image name outside of the `image:` and `label:` fields.

### Information

- Skaffold version: v2.8.0
- Operating system: macos
- Installed via: Google Cloud SDK

**Comment by renzodavid9** [comment]
Hey @cristifalcas, thanks for opening this issue. Let me check if I'm understanding correctly your use case: In a ConfigMap, you want to be able to replace a specific `data` value that has your image name, so it has the proper image + tag? In other words, you want to be able to transform this ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: example
data:
  myImage1: my-image
```
To something like this:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: example
data:
  myImage1: my-image@sha:1234567 # Here the image has the tag/sha
```

If that's the case, then I think [Skaffold's resource selector](https://skaffold.dev/docs/tutorials/skaffold-resource-selector/) could help here. For the specific case of the example above, my `skaffold.yaml` file will look like this:

```yaml
apiVersion: skaffold/v4beta8
kind: Config

build:
  artifacts:
    - image: my-image
      context: .

manifests:
  rawYaml:
  - configmap.yaml

resourceSelector:
  allow:
    - groupKind: "ConfigMap"
      image: [".data.myImage1"] # Here the image selector is pointing to data.myImage1 key in the ConfigMap
      labels: [".*"]
```
Let us know if this helps for your use case. Thanks! 😄
