### ISSUE TITLE
When the image is remote and cached, skaffold tries to pull it locally and ignores the cache.

### ISSUE THREAD

**Issue by 3droj7** [GoogleContainerTools/skaffold#9177]
Hey,
We're using helm to deploy our images to the EKS and the images themselves are saved in the gitlab registry.
When we're trying to use skaffold, it will always try to download the image locally when it shouldn't because the deployment doesn't use the local images.

There's seems to be a bug in https://github.com/GoogleContainerTools/skaffold/blob/1f591bafe367868e61eedc38f427acaae61e0a31/pkg/skaffold/build/cache/lookup.go#L83
It tries to import the image when the image can be remote and doesn't need to be imported.
https://github.com/GoogleContainerTools/skaffold/blob/1f591bafe367868e61eedc38f427acaae61e0a31/pkg/skaffold/runner/new.go#L229

Also I would suggest to put some debug logs to understand if skaffold decided that the image is remote or local.

### Expected behavior
Checking cache...
 - manager_microservice: Found
### Actual behavior
Checking cache...
 - manager_microservice: Not found. Building
### Information
- Skaffold version: 2.9.0
- Operating system: ubuntu 22.04
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: manager-microservice
build:
  cluster: {}
  artifacts:
    - image: manager_microservice
      context: ../../
      sync: {}
      custom:
        buildCommand: Build/buildx.sh "Manager/DtmMicroservice/Dockerfile" development
        dependencies:
          dockerfile:
            path: Manager/DtmMicroservice/Dockerfile
  tagPolicy:
    inputDigest: {}
```
skaffold build --default-repo registry.gitlab.com/.... --platform=linux/amd64 -v debug
