### ISSUE TITLE
SKAFFOLD_PROFILE not being substituted in setValueTemplates

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [GoogleContainerTools/skaffold#9187]
### Expected behavior
```yaml
setValueTemplates:
  serviceAccount.annotations.iam\.gke\.io/gcp-service-account: bar@foo-{{ .SKAFFOLD_PROFILE }}.iam.gserviceaccount.com
```
should render to
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: bar@foo-dev.iam.gserviceaccount.com
```

### Actual behavior
Renders to:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: bar@foo-.iam.gserviceaccount.com
```

### Information

- Skaffold version:  v2.9.0
- Operating system:  Ubuntu 22.04
- Installed via:  apt
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: foo
manifests:
profiles:
  - name: dev
    manifests:
      helm:
        releases:
          - name: foo
            chartPath: helm-charts/foo
            namespace: foo
            setValueTemplates:
              serviceAccount.annotations.iam\.gke\.io/gcp-service-account: bar@foo-{{ .SKAFFOLD_PROFILE }}.iam.gserviceaccount.com
```

Nowhere in the -vdebug output are there `SKAFFOLD_` environment variables - which seems to contradict the docs.
