### ISSUE TITLE
Default Deployer not set using `skaffold dev`  when having multiple configurations

### ISSUE THREAD

**Issue by Z3po** [GoogleContainerTools/skaffold#9215]
Hi Skaffold people!

First of all I'd like to thank you for building skaffold and doing the heavy work of maintaining such a project!

I'm not sure if the behaviour I recognized is a Bug or a Feature but it's kind of annoying therefore I decided to report it here.

We're using skaffold with Customresources being deployed into our kubernetes clusters. We have specified the necessary resourceSelectors in a central templates directory in our gitlab instance. This file is then imported into all the projects using this kind of resource with the following config snippet:

```
apiVersion: "skaffold/v4beta2"
kind: "Config"
requires:
  - configs:
      - "OurCustomResource"
    git:
      repo: "git@XXXXXXXXXXXXXX:our/path/to/skaffold-templates.git"
      path: "ourcustomresource.yaml"
      ref: "v2"
```

The file itself is nothing more then a resource selector allowing the images and labels being overwritten wherever they are in the custom resource itself:

```
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: "OurCustomResource"
resourceSelector:
  allow:
    - groupKind: "OurCustomResource.ourcustompath.com"
      image: [".*"]
      labels: [".spec.labels", ".*"]
```

Now while the whole rendering path works totally fine and replaces the image tags where necessary we recognized that neither artifacts nor the manifests themselfs are loaded and deployed in a local kind cluster when running `skaffold dev`.

### Expected behavior

When running `skaffold dev` our artifacts are built, the manifests get rendered by kustomize, the artifacts get loaded into the local kind cluster and our manifests get deployed.

### Actual behavior

Running `skaffold dev` just shows the following output

```
Generating tags...
 - registry.xxxxxxxxxxxxxxxxxx/our-application -> registry.xxxxxxxxxxxxxxxxxx/our-application:dev
Checking cache...
 - registry.xxxxxxxxxxxxxxxxxx/our-application: Found Locally
Tags used in deployment:
 - registry.xxxxxxxxxxxxxxxxxx/our-application -> registry.xxxxxxxxxxxxxxxxxx/our-application:ac5b47775a6556f3a5433ce985286faeac53ff13cabcea834be2b79a4c53a66d
Starting deploy...
Listing files to watch...
 - registry.xxxxxxxxxxxxxxxxxx/our-application
Press Ctrl+C to exit
Watching for changes...
^CCleaning up...
```

That means the artifacts are being built but nothing else happens.
Even when running with debug loglevel no hint of what could be the issue is being echoed.

### Information

- Skaffold version: v2.9.0
- Operating system: debian trixie

### Additional hints

I've taken the time already to take a deeper look into the issue and the culprit seems to be that when running `skaffold dev` with multiple configurations no default renderer and deployer get assigned (see https://github.com/GoogleContainerTools/skaffold/blob/4a7cad0659196f0acc19708ada215bdfaf37eda6/cmd/skaffold/app/cmd/runner.go#L153-L161).

This works contrary to e.g. `skaffold apply` which defaults to loading a default deployer if none has been specified (see https://github.com/GoogleContainerTools/skaffold/blob/4a7cad0659196f0acc19708ada215bdfaf37eda6/pkg/skaffold/runner/deployer.go#L92-L137).

The whole thing doesn't print any hints of what's going wrong because the whole deployment just gets silently skipped if just an empty Deployer mux has been initialized (see https://github.com/GoogleContainerTools/skaffold/blob/4a7cad0659196f0acc19708ada215bdfaf37eda6/pkg/skaffold/deploy/deploy_mux.go#L119-L154).

Now you have to decide whether this is a bug or a feature :)

If it's a feature can you maybe add a logline that I'm missing a deployer and therefore nothing gets deployed?

Thanks in advance for taking care!
