### ISSUE TITLE
build tagpolicy gitcommit behaviour not expected

### ISSUE THREAD

**Issue by jack1902** [GoogleContainerTools/skaffold#9220]
### Expected behavior
When using `gitcommit`, as the build-tag using the default `variant` i expected that the `git-commit` hash would be used unless a tag on that SPECIFIC commit existed.

When reviewing the documentation here: https://skaffold.dev/docs/taggers/#gitcommit-uses-git-commitsreferences-as-tags the documentation states the following:

```txt
    If the workspace is on a Git tag, that tag is used to tag images
    If the workspace is on a Git commit, the short commit is used <--- this is NOT true, it prepends with the last known tag
    If the workspace has uncommitted changes, a -dirty suffix is appended to the image tag
```

### Actual behavior

When running `skaffold build --dry-run` i am observing the last git-tag being used as a prefix with the current commit-hash as the suffix. This is really weird, as i might of had `v1.0.0` then a random commit-hash, i didn't expect to have `v1.0.0-random-commit-hash`

### Information

- Skaffold version: v2.9.0
- Operating system: MacOS 14.2
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: test

build:
  local:
    useBuildkit: true
    push: false
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: test
      docker:
        cacheFrom:
          - test
```

### Steps to reproduce the behavior

1. Clone this repository : https://github.com/jack1902/skaffold-tagging
2. Run `skaffold build --dry-run` and observe:
```sh
➜ skaffold build --dry-run
Generating tags...
 - test -> test:v1.0.0-1-HASH
```
