### ISSUE TITLE
skaffold run always forces redeploy with helm renderer

### ISSUE THREAD

**Issue by joreetz-otto** [GoogleContainerTools/skaffold#9222]
### Expected behavior
'skaffold run' should only force a new revision of a deployment if there are any changes in the code.
This is currently not the case.
But rendering skaffold and applying it manually via kubectl does not force a new revision.
`skaffold render | kubectl --context gke_abc --namespace abc apply -f -`

### Information

- Skaffold version: v2.9.0
- Operating system: Ubuntu 22.04.3 LTS
- Installed via: Google Cloud SDK
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: abc
build:
  artifacts:
    - image: abc/abc
      context: ../abc
      docker:
        dockerfile: Containerfile
        pullParent: true
  local:
    push: true
    useBuildkit: true
    concurrency: 0
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    defaultNamespace: abc
  tolerateFailuresUntilDeadline: true
manifests:
  helm:
    releases:
      - name: abc
        chartPath: helm-charts/abc
        namespace: abc
        setValues:
          nothing_interesting: true
        setValueTemplates:
          image.digest: "{{ .IMAGE_DIGEST_abc_abc }}"
          image.repository: "{{ .IMAGE_REPO_abc_abc }}"
          image.tag: "{{ .IMAGE_TAG_abc_abc }}"
        createNamespace: true
        wait: true
  rawYaml:
    - manifests/namespace_abc.yaml
profiles:
  - name: dev
    deploy:
      kubeContext: gke_abc_dev
  - name: prd
    deploy:
      kubeContext: gke_abc_prd
  - name: tst
    deploy:
      kubeContext: gke_abc_tst
```
