### ISSUE TITLE
Argo Rollouts With Canary Fail to Render and Deploy

### ISSUE THREAD

**Issue by lucasoskorep** [GoogleContainerTools/skaffold#9229]
### Expected behavior
Argo rollouts which use 2 services for canary rollouts with traffic management should be rendered and deployed as expected. 

### Actual behavior
Argo rollouts with 2 services are not able to be rendered or deployed with skaffold

"""
Error: INSTALLATION FAILED: error while running post render on files: error while running command /opt/homebrew/bin/skaffold. error output:
reading Kubernetes YAML: yaml: unmarshal errors:
  line 11: mapping key "service" already defined at line 9
: exit status 1
"""

Skaffold complains that there are 2 services defined as it seems to have a hard limit set at 1 for some reason.   Having more than one is a requirement of proper argo rollouts with traffic management though - https://argo-rollouts.readthedocs.io/en/stable/features/traffic-management/

The services are nearly identical - one just has the definition -canary and the other does not have the canary appendix 

### Information

- Skaffold version: v2.9.0
- Operating system: Macos 
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
deploy:
  kubeContext: "context-here"
  helm:
    releases:
      - name: release-name
        namespace: release-namespace
        chartPath: helm/release-chart
```

### Steps to reproduce the behavior

I do not have these atm, but will work on that as needed. 

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...
