### ISSUE TITLE
Output from post render hook not printed in console

### ISSUE THREAD

**Issue by renzodavid9** [GoogleContainerTools/skaffold#9262]
When running a post render hook, with `withChange: false`, Skaffold is not printing in console the stdout from the hook command, as it used to do in previous versions.

To preserve previous behaviour (Skaffold version < 2.10), and for the user to be able to see what's happening when running the hook, it should be ok to print the output from the associated script.

### Information

- Skaffold version: 2.10.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta8
kind: Config
manifests:
  rawYaml:
    - any-k8s-manifest.yaml
  hooks:
    after:
      - host:
          command: ["sh", "-c", "echo running post-render hook 1"]
```

### Steps to reproduce the behavior

1. With previous `skaffold.yaml` file, run `skaffold render`, you won't see the message `running post-render hook 1` in console (or anywhere)
2. Take a previous Skaffold version, run `skaffold render` and you will see the message in console
