### ISSUE TITLE
Configmaps, PVC's, PV's, and potentially other "rawYaml" files are only deployed after a second consecutive skaffold run 

### ISSUE THREAD

**Issue by Sacmunraga** [GoogleContainerTools/skaffold#9266]
### Expected behavior
Configmaps, PVC's, PV's, and other yaml files listed under manifests.rawYaml should be deployed the right away after running `skaffold run`.
### Actual behavior
Configmaps, PVC's, PV's, and other yaml files listed under manifests.rawYaml are deployed only after running `skaffold run` a second, consecutive, time. They ARE NOT deployed after running `skaffold run` the first time.

### Information

- Skaffold version: v2.10.0
- Operating system: MacOs
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta4
kind: Config
build:
  ... omitted ...
manifests:
  rawYaml:
    - ./values/yaml1.yaml
    - ./values/yaml2.yaml
    - ./values/pvc.yaml
deploy:
  kubectl: {}
```

```pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

```yaml1.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume
  namespace: default
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/on/my/machine"
```

### Steps to reproduce the behavior

1. Add any yaml file(s) that contains PV's, PVC's, or Configmap's under the manifests.rawYaml section of a skaffold.yaml file
2. `skaffold run --cache-artifacts=false`
3. `kubectl get pvc -n default` (There should NOT be any PVCs)
4. Re-run `skaffold run --cache-artifacts=false`
5. `kubectl get pvc -n default` (Now there should be a PVC)
