### ISSUE TITLE
Incorrect cache invalidation in skaffold build

### ISSUE THREAD

**Issue by aran** [GoogleContainerTools/skaffold#9279]
Outputs of `skaffold build` not reflecting input changes.

### Expected behavior
Whenever my files change, the output hashes change. :)

### Actual behavior
I noticed that changes are not being reflected in the output skaffold-manifest, even though `skaffold dev -p dev` would update my local docker with the right images. All my images are built with bazel.

When I turned off docker and ran with `--cache-artifacts=false`, my skaffold build image hashes updated.

### Information

I have a gitops-style deployment using skaffold that is effectively this:

`skaffold build --filename skaffold-namespaced.yaml --default-repo <snip-repo>/artifacts --profile=prod --profile-auto-activation=false --quiet --push | skaffold render --filename skaffold-namespaced.yaml --build-artifacts - --profile=prod --output <snip>/skaffold/skaffold-manifest.yaml`

The skaffold build step is retrieving the same image from cache even when its input files change. However, the sha256 of the bazel tar target was changing, so I believe Bazel was picking up the change. 

- Skaffold version: v2.10.0
- Operating system: macos 14.2.1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml skaffold-namespaced.yaml
apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ./code/front
  - path: ...
  - ...many more paths...
profiles:
  - name: dev
    activation:
      - command: dev
  - name: prod

```

```yaml
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: front
build:
  artifacts:
    - image: front
      bazel:
        target: :front_image.tar
  tagPolicy:
    sha256: {}
deploy:
  kubectl: {}
profiles:
  - name: dev
    manifests:
      kustomize:
        paths:
          - kustomize/dev
  - name: prod
    manifests:
      kustomize:
        paths:
          - kustomize/prod
```

**Comment by ath88** [comment]
I am seeing the same regression after upgrading to v2.10.

Content of `skaffold.yaml` is:
```
apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: example
build:
  artifacts:
    - image: example
      context: container
deploy:
  helm:
    releases:
      - name: chart
        chartPath: chart
        setValueTemplates:
          image: localhost:5000/example:{{.IMAGE_TAG_example}}@{{.IMAGE_DIGEST_example}}
```

When making changes in container/Dockerfile (such as adding a `RUN ls`or similar), I will get the following output:

```
Generating tags...
 - example -> localhost:5000/example:123b516-dirty
Checking cache...
 - example: Found Remotely
Tags used in deployment:
 - example -> localhost:5000/example:123b516-dirty@sha256:eaca7009de6bf883b897623a31d3443449a59aed42a6fb030d9c2b009149c727
Starting deploy...
```

So there is no rebuild, which there was when using skaffold v2.9.
