### ISSUE TITLE
Add Custom Staging Bucket Option

### ISSUE THREAD

**Issue by shikanime** [GoogleContainerTools/skaffold#9281]
### Expected behavior

Users should be able to specify a custom staging bucket for Skaffold builds, such as a bucket with a specific region constraint or naming convention.

### Actual behavior

Skaffold will create a new staging bucket if it does not exist, but there is no option to specify a custom bucket.

https://github.com/GoogleContainerTools/skaffold/blob/30dda179448ee2462b6b3dad266681cef9e8f00c/pkg/skaffold/build/gcb/cloud_build.go#L109-L123

I am open to contributing if the issue is relevant and I am not missing something that might solve my problem.

### Information

- Skaffold version: v2.10.0
- Operating system: Ubuntu 22.04.3 LTS
- Installed via: Nixpkgs
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: foo
build:
  artifacts:
    - image: europe-docker.pkg.dev/foo/app
      kaniko: {}
  googleCloudBuild:
    projectId: foo
    region: europe-west9
```

```text
creating bucket if not exists: googleapi: Error 412: 'us' violates constraint 'constraints/gcp.resourceLocations', conditionNotMet
```
