### ISSUE TITLE
skaffold build with docker fails to set BUILDPLATFORM variable 

### ISSUE THREAD

**Issue by aizam6066** [GoogleContainerTools/skaffold#9284]
We have a step in our Github workflow, where we use skaffold to build a Docker image to run some unit-tests. Recently, the following command:

`skaffold build --push=false --platform=linux/amd64 -b $APP`

fails with this error:

```docker build failure: failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument. Please fix the Dockerfile and try again..```

In our Dockerfile, we have:
`FROM --platform=$BUILDPLATFORM golang:1.19 AS builder`

and it seems that $BUILDPLATFORM is empty.

### Expected behavior
$BUILDPLATFORM should be set with flag `--platform=linux/amd64`

### Actual behavior
$BUILDPLATFORM is ""

### Information

- Skaffold version: 2.10.0
- Operating system: 
```
Current runner version: '2.312.0'
Operating System
  Ubuntu
  LTS
Runner Image
  Image: ubuntu-22.0
  Version: 20240122.3.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240122.3/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240122.3
```
- Contents of skaffold.yaml:
```yaml

apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: app1
      sync:
        infer:
          - internal/**
          - pkg/**
          - cmd/kafka/**
          - main.go
          - go.mod
      platforms: ["linux/amd64", "linux/arm64"]
      docker:
        buildArgs:
          app_name: kafka
    - image: app2
      sync:
        infer:
          - internal/**
          - pkg/**
          - cmd/grpc/**
          - main.go
          - go.mod
      platforms: ["linux/amd64", "linux/arm64"]
      docker:
        buildArgs:
          app_name: grpc

```
Any help with this would be greatly appreciated! Thanks!
