### ISSUE TITLE
Cannot get resourceSelector to work on CRD SparkApplication (sparkoperator.k8s.io)

### ISSUE THREAD

**Issue by maxhillaert** [GoogleContainerTools/skaffold#9304]
### Expected behavior

I'm trying to get skaffold to work with SparkApplication CRD and I'm using resourceSelector  as follows:

```yaml
apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: my-app
      context: ..
      jib:
        project: my-app

manifests:
  rawYaml:
    - ./k8/spark-app-hello-world.yaml


resourceSelector:
  allow:
    - groupKind: SparkApplication
      image: [".spec.image"]  # tried ".*"

deploy:
  kubectl:
    defaultNamespace: my-namespace

```

This is what a SparkApplication looks like:

```yaml
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
spec:
  type: Scala
  mode: cluster
  image: my-app
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.1.1.jar"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
```

I expect the image to get replaced when I do skaffold render

### Actual behavior

It does not get replaced and debug output isn't showing me any clue why.   

### Information

- Skaffold version: 2.10.0
- Operating system: windows
- Installed via: Chocolatey
- Contents of skaffold.yaml:

```yaml

apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: my-app
      context: ..
      jib:
        project: my-app

manifests:
  rawYaml:
    - ./k8/spark-app-hello-world.yaml


resourceSelector:
  allow:
    - groupKind: SparkApplication
      image: [".spec.image"]  # tried ".*"

deploy:
  kubectl:
    defaultNamespace: my-namespace


```

**Comment by maxhillaert** [comment]
Found the problem.   groupKind is not just SparkApplication but you need to add the group key of the CRD to it.


This worked:


```yaml
resourceSelector:
  allow:
    - groupKind: SparkApplication.sparkoperator.k8s.io
      image: [".*"]
```
