### ISSUE TITLE
Skaffold dev creates deployment loop when helm chart has dependencies

### ISSUE THREAD

**Issue by Uvedale** [GoogleContainerTools/skaffold#931]
### Expected behavior
After running `skaffold dev` and the initial build and deployment is done, it will only trigger a new build / deploy when I make a change to the artifact directory or helm chart directory.

### Actual behavior
After the initial build, the chart is continuously re-deployed in a loop. 
This is because as part of the deployment process, `helm dep build` is run which re-creates the files in the `charts` subdirectory if the chart has dependencies. This change is caught by the change watcher and causes a redeploy, and the process repeats itself.

### Information

- Skaffold version: v0.12
- Operating system: OSX 10.13.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: internal-registry/some-app
deploy:
  helm:
    releases:
    - name: some-app
      chartPath: /charts/some-app
      valuesFilePath: /charts/some-app/overrides.yaml
      namespace: default
      imageStrategy:
        helm: {}
      values:
        "some-app.image": internal-registry/some-app
```

### Steps to reproduce the behavior

1. Create a chart that has a dependency
2. Create a skaffold config that deploys that chart
3. skaffold dev
