### ISSUE TITLE
Get "docker compose not yet supported by skaffold" when trying to deploy a docker container with useCompose: true

### ISSUE THREAD

**Issue by NarenPurighalla** [GoogleContainerTools/skaffold#9321]
### Expected behavior
When deploying an image built by Skaffold to docker using docker compose by running `skaffold deploy --images image:test`, skaffold should go through the process without any issues

### Actual behavior
Get an error "docker compose not yet supported by skaffold"
### Information

- Skaffold version:  2.10.0
- Operating system:  Ubuntu 22.04
- Installed via:  skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: custom-config
build:
  artifacts:
    - image: "image1"
      context: .
      buildpacks:
        builder: gcr.io/buildpacks/builder
deploy:
  docker:
    images:
      - "image1"
    useCompose: true
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...
