### ISSUE TITLE
gcloud warnings with GitHub Actions

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#9336]
### Expected behavior

I have a very basic skaffold file I'm building. I'm not suing GCP

### Actual behavior
I get the following warnings when using Skaffold in a GitHub Actions workflow.
```
WARNING: Could not open the configuration file: [/home/runner/.config/gcloud/configurations/config_default].
time="2024-03-12T17:05:54Z" level=warning msg="Failed to get credentials for registry: eu.gcr.io" error="error getting credentials - err: exit status 1, out: `You do not currently have an active account selected. See https://cloud.google.com/sdk/docs/authorizing for more information.`"
```

### Information

- Skaffold version: v2.10.1
- Operating system: GitHub Action workflow `runs-on: ubuntu-latest`
- Installed via: `curl --location https://github.com/GoogleContainerTools/skaffold/releases/download/v2.10.1/skaffold-linux-amd64`

skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: sample-app
      context: .
      docker:
        dockerfile: Dockerfile
```

Dockerfile:
```
FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu
CMD ["java", "--version"]
```

### Steps to reproduce the behavior

`skaffold build --push=false --file-output=tags.json`
