### ISSUE TITLE
breaking up manifest files causes IP to not get assigned

### ISSUE THREAD

**Issue by skamansam** [GoogleContainerTools/skaffold#934]
### Expected behavior
When I use multiple files in `deploy.kubectl.manifests`, I expect my service to come up in the same way as if the files were in a single manifest.
```
$ minikube service minio-service --url
http://192.168.39.27:32451
```

### Actual behavior
When using multiple files, i get the following:
```
$ minikube service minio-service --url
Waiting, endpoint for service is not ready yet...
```

### Information

- Skaffold version: 0.12.0
- minikube version: 0.28.0
- Operating system: Fedora 28 x86_64
- manifest file copied verbatim from https://www.minio.io/kubernetes.html, then broken into separate files
- Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
deploy:
  kubectl:
    manifests:
    # - ./deploy/minio/sample/single-file.yaml # single-file version
    - ./deploy/minio/sample/storage.yaml
    - ./deploy/minio/sample/deployment.yaml
    - ./deploy/minio/sample/service.yaml
```

REVISION: This seems to be definitively reproducible. The workaround is to clear the minikube config directory: `rm -rf ${HOME}/.minikube` (`minikube delete` doesn't do it), then start minikube again, and re-run `skaffold dev`. The problem seems to be related to the config files being changed. Maybe I don't understand enough about k8s or skaffold, but it doesn't really make sense to have to destroy everything when a file changes.
