### ISSUE TITLE
`--digest-source` not working when `skaffold run` on remote cluster

### ISSUE THREAD

**Issue by fengye87** [GoogleContainerTools/skaffold#9350]
### Expected behavior

For remote clusters, `skaffold run` default to use `remote` digest-source, that's all right. But since it doesn't handle dirty file changes nicely, I was trying to change digest source to `local`, the default when `skaffold run` on local (minikube) clusters. But seems it has no effect and skaffold run behaves just like `--digest-source=remote`

### Actual behavior

`--digest-source=local` should invoke docker build and use the result as the image digest

### Information

- Skaffold version: v2.10.1 
- Operating system: Rocky 9
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: foobar
build:
  artifacts:
    - image: foobar
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - deploy/
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold run --digest-source=local`
