### ISSUE TITLE
Modules activated by profiles?

### ISSUE THREAD

**Issue by seagullmouse** [GoogleContainerTools/skaffold#9386]
My requirement is as follows
- Use profiles to conditionally build and deploy a large set of images
- These images are separated into modules
- `core` config should always be run, but `all`, `config1` and `config2` should only run based on the profiles
- I can't work out the `skaffold.yaml`, my pseudo-skaffold.yaml is below 

```
apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: example
requires:
  - configs: ["core"]
profiles:
  - name: all
    requires:
      - configs: ["config1", "config2"]
  - name: config1
    requires:
      - configs: ["config1"]
  - name: config2
    requires:
      - configs: ["config2"]
```

Please advise
