### ISSUE TITLE
Handle optional port-forwarding

### ISSUE THREAD

**Issue by viglesiasce** [GoogleContainerTools/skaffold#94]
I started to go down the route of figuring out how to work with Skaffold and use a remote debugger (delve in my case). 

The only thing I really needed from Skaffold was for it to be able to reconfigure a port-forwarding setup to one of the new pods that was created.

I think it could look something like:

```yaml
portForwarding:
  - labelSelector:
      app: my-app
      component: backend
    port: 2345
  - labelSelector:
      app: my-app
      component: frontend
    port: 8080:80
```

Skaffold could pick the most recently deployed pod that matches the selectors, although some more precise detection of the "right pod" may be necessary.
