### ISSUE TITLE
Kaniko builder can't push to private registry

### ISSUE THREAD

**Issue by BoomBlee** [GoogleContainerTools/skaffold#9426]
### Expected behavior
Image push to registry

### Actual behavior
Image push returns UNAUTHORIZED

### Information

- Skaffold version:  gcr.io/k8s-skaffold/skaffold:v2.12.0
- Operating system:  ubuntu:22.04
- Installed via: skaffold.dev 
- Contents of skaffold.yaml:

```yaml
    build:
      artifacts:
        - image: <name_image>
          context: .
          kaniko:
            image: gcr.io/kaniko-project/executor:v1.23.0
            buildArgs:
              DEMO_MODE: ""
      cluster:
        namespace: dev
        randomDockerConfigSecret: true
        dockerConfig:
          path: /kaniko/.docker/config.json
      tagPolicy:
        envTemplate:
          template: "{{.GIT_BRANCH_DASH}}-{{.CI_DOCKER_IMAGE_TAG}}"
```

### Steps to reproduce the behavior

1. skaffold build

error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "docker.io/<name_image>:<tag>": POST https://index.docker.io/v2/library/<name_image>/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/<name_image> Type:repository] map[Action:push Class: Name:library/<name_image> Type:repository]]
