### ISSUE TITLE
Unable to pull helm dependencies from a private helm repo

### ISSUE THREAD

**Issue by fabioformosa** [GoogleContainerTools/skaffold#9432]
### Expected behavior
I have a local helm chart which includes some remote deps from a private helm repo. I run skaffold through Google Cloud Deploy.
I expect skaffold was able to get authenticated to the helm private repo to pull the dependencies.

### Actual behavior
I get this error message
`building helm dependencies: exit status 1` 

### Information

- Skaffold version: 2.11.0
- Operating system: no OS. Google Cloud Deploy
- Installed via: Google Cloud Deploy
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta7
kind: Config
profiles:
  - name: preprod
    deploy:
      helm:
        releases:
          - name: foo
            createNamespace: true
            namespace: default
            chartPath: ./helm
            repo: https://example.com/repository/helm
            skipBuildDependencies: false
            valuesFiles:
              - envs/preprod/values.yaml
            setValueTemplates:
              image.tag: "0.0.1"
  - name: prod
    deploy:
      helm:
        releases:
          - name: foo
            createNamespace: false
            namespace: default
            chartPath: ./helm
            repo: https://example.com/repository/helm
            valuesFiles:
              - envs/prod/values.yaml
            setValueTemplates:
              image.tag: "0.0.1"
```
