### ISSUE TITLE
Allow helm deploy to get the value of the generated tag

### ISSUE THREAD

**Issue by nathkn** [GoogleContainerTools/skaffold#948]
I would like my the helm deploy configuration to be able to overwrite a value in my values.yaml file to the generated tag so I could make use of it in my helm chart.

Currently I'm able to extract the image name with the appended tag, but I was unable to find any functionality to extract the appended tag separate from the image name.

so a skaffold.yaml that looks something like this:
```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    gitCommit: {}  
  artifacts:
  - imageName: test-app
    workspace: ../
  local:
    skipPush: true
deploy:
  helm:
    releases:
    - name: test-app
      chartPath: test-app
      namespace: test-app
      valuesFilePath: test-app/values.yaml
      values:
        image: test-app
        tag: <some reference to the tag>
```
