### ISSUE TITLE
skaffold verify requires explicit build artifacts

### ISSUE THREAD

**Issue by benmoss** [GoogleContainerTools/skaffold#9506]
### Expected behavior
I can run `skaffold verify` and it builds and/or uses prebuilt images already cached

### Actual behavior
`skaffold verify` errors out with `ErrImagePull` unless you provide `--build-artifacts`

### Information

- Skaffold version: `v2.13.2`
- Operating system: OSX 14.6.1
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: bootstrap
      docker: {}
verify:
- name: bootstrap
  container:
    name: bootstrap
    image: bootstrap
```

```dockerfile
FROM hello-world:latest
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold verify`
