### ISSUE TITLE
skaffold render not... rendering the images?

### ISSUE THREAD

**Issue by Geethree** [GoogleContainerTools/skaffold#9533]
### Expected behavior
When running `skaffold render` I expect the image digest to be put into the rendered manifests

### Actual behavior
It just returns what is in the manifest `image:latest`. 

Note: `Skaffold dev` works as expected against a local cluster.

### Information

I am using latest skaffold + latest bazel + helm.

```yaml
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: azure
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: azure_service
      bazel:
        target: //services/azure/cmd:cmd.skaffold.tar
    - image: azure_migrator
      bazel:
        target: //services/azure/internal/db/model:migrate.skaffold.tar

manifests:
  helm:
    releases:
      - name: azure-service
        chartPath: ../../charts/service
        setValueTemplates:
          image: "{{.IMAGE_REPO_azure_service}}"
          migrateImage: "{{.IMAGE_REPO_azure_migrator}}"
        setValues:
          name: "azure"
          postgres.dbName: "azure"
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: azure
    port: grpc
    localPort: 8081
  - resourceType: service
    resourceName: postgres-azure
    port: 5432
    localPort: 15432
```

## The rendered manfiest
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure
spec:
  selector:
    matchLabels:
      app: azure
  template:
    metadata:
      labels:
        app: azure
    spec:
      containers:
        - args:
            - -db-url=postgres-azure
          image: azure_service:latest
          name: azure
          ports:
            - containerPort: 50050
 ---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-azure
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - args:
            - -path=/migrations
            - -database=postgres://myuser:mypassword@postgres-azure:5432/azure?sslmode=disable
            - up
          image: azure_migrator:latest
          name: migrate-azure
      restartPolicy: Never
```

## Debug
```
DEBU[0001] image [azure_service] is not used by the current deployment  subtask=-1 task=DevLoop
DEBU[0001] image [azure_migrator] is not used by the current deployment  subtask=-1 task=DevLoop
DEBU[0001] manifests with tagged images:apiVersion: v1
```

Any pointers would be appreciated!
