### ISSUE TITLE
Discussion: rethink builders/artifacts

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#955]
The concept of builders is a bit confusing:

**Naming**: Is a builder is really the _thing_ that builds or just a build context? 

**In-cluster vs local vs remote**: 

What is the `local` builder?  It depends on the "artifact" - for a docker artifact it can be the Docker Daemon? Docker CLI? Buildkit? 

Kaniko builds in-cluster but only Docker artifacts. It's never going to support bazel or jib. 

GCB as a builder is a "remote" Docker daemon. If we use the published skaffold image as a buildstep to build in GCB, we could use the same strategy locally as well, and then people wouldn't have to install bazel, etc. on their local machines, just use skaffold "in-docker" (sind?) + we could do in-cluster builds with the skaffold image as a pod. 

**structure**: 
Plus currently in a multi-artifact project all the artifacts are expected to be built using the same "builder" - are there use cases where you want to build the artifacts in different "build-contexts"?

**Comment by coollog** [comment]
Maybe artifacts could be a part of each builder?

```
build:
  local:
    ... options ...
    artifacts:
    - image: ...
      context: ...
      docker: {}
  kaniko:
    ... options ...
    artifacts:
    - image: ...
      context: ...
      docker: {}
```
