### ISSUE TITLE
Specify exact image(s) to build with skaffold build

### ISSUE THREAD

**Issue by jsok** [GoogleContainerTools/skaffold#9550]
`skaffold build --build-images=[]` is useful in being able to build just a subset of images, however the `string.Contains()` matching is problematic for configurations that have similarly named images.

### Expected behavior

Given a config like:

```yaml
apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: foo-api
    - image: bar-api
    - image: bar-api-v2
```

### Information

- Skaffold version: 
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: foo-api
    - image: bar-api
    - image: bar-api-v2
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...
