### ISSUE TITLE
Feature: Support TemplatedField for build.artifacts.docker.cliFlags

### ISSUE THREAD

**Issue by kitagry** [GoogleContainerTools/skaffold#9581]
### Expected behavior

Upon installing Docker Buildx, the docker build command becomes an [alias for docker buildx build](https://docs.docker.com/reference/cli/docker/buildx/build/). This means that any subsequent docker build commands will be executed using the more advanced features provided by Buildx. Specifically, we intend to leverage the `--cache-to=type=registry,ref=repo/image:tag` flag within these commands. In order to several registry, I want to TemplateField for `build.artifacts.docker.cliFlags` as following.

```yaml
build:
  artifacts:
    - image: repo/image
      context: .
      docker:
        dockerfile: Dockerfile
        cliFlags:
          - "--cache-to={{ .IMAGE_REPO }}/{{ .IMAGE_NAME }}:latest-cache"
```

### Actual behavior

We can't use TemplateField with cliFlags.
