### ISSUE TITLE
Sync unable to work when file is changed

### ISSUE THREAD

**Issue by jefersoneiji** [GoogleContainerTools/skaffold#9590]
### Expected behavior

Image shoud be updated with new code after change in the original file.

### Actual behavior

I get this error from skaffold 
```cmd
time="2024-11-29T08:12:57-03:00" level=debug msg="Running command: [kubectl --context docker-desktop exec posts-deploy-58c5697876-gx972 --namespace default -c posts -i -- tar xmf - -C / --no-same-owner]" subtask=-1 task=DevLoop
time="2024-11-29T08:12:57-03:00" level=warning msg="Skipping deploy due to sync error:copying files: running [kubectl --context docker-desktop exec posts-deploy-58c5697876-gx972 --namespace default -c posts -i -- tar xmf - -C / --no-same-owner]\n - stdout: \"\"\n - stderr: \"tar: Removing leading `/' from member names\\ntar: app/src/routes.ts: Cannot open: File exists\\ntar: Exiting with failure status due to previous errors\\ncommand terminated with exit code 2\\n\"\n - cause: exit status 2: sync failed for artifact \"blog/posts:df9fbc2741142307f50656f1cbce787da37b2df4467f3d5eaa3a03ea33a6a835\"" subtask=-1 task=DevLoop
```
### Information

- Skaffold version: 2.13.2
- Operating system: Windows Home
- Installed via: [standalone binary](https://skaffold.dev/docs/install/#standalone-binary)
- Contents of skaffold.yaml: [file content](https://github.com/jefersoneiji/microservices-skaffold/blob/master/skaffold.yaml)

```yaml
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: blog
build:
  local: 
    push: false
  artifacts:
    - image: blog/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.tsx" 
            dest: .
    - image: blog/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts" 
            dest: .  
    - image: blog/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts" 
            dest: .
    - image: blog/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts" 
            dest: .
    - image: blog/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts" 
            dest: .
    - image: blog/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts" 
            dest: .
manifests:
  rawYaml:
    - infra/k8s/client-deploy.yml
    - infra/k8s/comments-deploy.yml
    - infra/k8s/event-bus-deploy.yml
    - infra/k8s/ingress-service.yml
    - infra/k8s/moderation.deploy.yml
    - infra/k8s/posts-deploy.yml
    - infra/k8s/posts-service.yml
    - infra/k8s/query-deploy.yml
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold dev`
3. make any change in the routes.ts in posts, query or comments folder

**Comment by jefersoneiji** [comment]
I changed the sync field from this: 

```yaml
sync: 
   manual:
      - src: "src/**/*.ts" 
         dest: .
````            
to this: 
```yaml
sync: 
    manual:
       - src: "src/***/*.ts" 
          dest: .
```
But the three stars in the glob pattern are supposed to mean nothing. Yet, skaffold was able to parse files after this change. My guess is that something is wrong with the parser or windows is causing this error during sync  

maybe related to: 
https://github.com/GoogleContainerTools/skaffold/issues/4767
https://github.com/GoogleContainerTools/skaffold/issues/1222#issuecomment-487632737
