### ISSUE TITLE
skaffold verify --default-repo doesn't work the same way as in build or deploy

### ISSUE THREAD

**Issue by nathanperkins** [GoogleContainerTools/skaffold#9592]
### Expected behavior

`skaffold verify --default-repo=$IMAGE_REPO` should apply the default repo to verify images, similar to how it works with `skaffold build`, `skaffold `deploy`, etc.

### Actual behavior

`skaffold verify --default-repo=$IMAGE_REPO` resulted in the default repo not being added to the image.

### Information

- Skaffold version: v1
- Operating system: Linux
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
build:
  local:
    useBuildkit: true
    concurrency: 0
  artifacts:
    ...
    - image: foo-e2e-test
      docker:
        dockerfile: build/images/foo-e2e-test/Dockerfile
      requires:
        - image: gobuilder
          alias: GOBUILDER
          
verify:
  - name: foo-e2e-test
    container:
      name: foo-e2e-test
      image: foo-e2e-test
    executionMode:
      kubernetesCluster: {}
```

### Steps to reproduce the behavior

1. Create a skaffold yaml which builds a test container locally without repo provided and uses it for verify.
2. Run `skaffold verify --default-repo=$IMAGE_REPO`.
