### ISSUE TITLE
skaffold verify need to specify env vars, with templating

### ISSUE THREAD

**Issue by nathanperkins** [GoogleContainerTools/skaffold#9593]
The `skaffold.yaml` API for `verify` container only documents usage for name, image, command and args. This is insufficient for us to specify our tests which need env vars and need to be able to template values based on the environment that is running skaffold.

We would like to do something like:

```yaml
verify:
  container:
  - name: foo
    env:
    - name: MY_STATIC_ENV
       value: "Hello from the environment"
    - name: MY_TEMPLATE_ENV
       value: "Hello from {{.MY_EXTERNAL_VAR}}"
```

### Information

- Skaffold version: 2.13.0
- Operating system: Linux
- Installed via: skaffold.dev
- Contents of skaffold.yaml.

**Comment by nathanperkins** [comment]
I checked whether it is possible to achieve the desired result using overrides but it doesn't seem so.

```yaml
verify:
  - name: foo-e2e-test
    container:
      name: foo-e2e-test
      image: foo-e2e-test
      args:
      - -test.v
    executionMode:
      # kubernetesCluster: {}
      kubernetesCluster:
        overrides: |-
          {
            "kind": "Job",
            "apiVersion": "batch/v1",
            "spec": {
              "template": {
                "spec": {
                  "containers": [
                    {
                      "name": "foo-e2e-test",
                      "env": [
                        {
                          "name": "FOO",
                          "value": "BAR"
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }
```

```yaml
DEBU[0065] Running command: [tput colors]                subtask=-1 task=DevLoop
DEBU[0065] Command output: [256
]                        subtask=-1 task=DevLoop
1 error(s) occurred:
* creating verify job in cluster: Job.batch "foo-e2e-test" is invalid: spec.template.spec.containers[0].image: Required value
```
