### ISSUE TITLE
skaffold support for podman login store

### ISSUE THREAD

**Issue by kaplan-michael** [GoogleContainerTools/skaffold#9605]
### Expected behavior
`podman login <registry>`
`skaffold build`
skaffold is able to build and push images
(podmans docker compatibility is enabled, so builds work fine)

### Actual behavior
skaffold fails on missing registry credentials, as it can't find `$XDG_RUNTIME_DIR/containers/auth.json`

### Information

- Skaffold version: v2.13.2
- Operating system: Fedora 41
- Installed via: github release
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: podman test

build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
      ignoreChanges: true

  artifacts:
    - image: <private registry>
      context: .
      docker:
        dockerfile: ./container_images/Containerfile
        buildArgs:
          GIT_HASH: "{{.GIT.COMMIT}}"
```
