### ISSUE TITLE
skaffold dev not working with bazel artifact and helm deployment

### ISSUE THREAD

**Issue by enriched** [GoogleContainerTools/skaffold#961]
### Expected behavior

Running `skaffold dev` with bazel artifact and helm deploy works.

### Actual 

Running skaffold dev produces:

```
Cleaning up...
Error: release: "my-service" not found
Cleanup complete in 170.72637ms
FATA[0000] watching files for deployer: listing files: unable to stat file : stat : no such file or directory
```

### Information

- Skaffold version: v0.13.0
- Operating system: macOS 10.13.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
    - imageName: my.repo.com/my-service
      workspace: .
      bazel:
        target: //services/my-service:image.tar
  local: {}
deploy:
  helm:
    releases:
      - name: my-service
        chartPath: helm/my-service
```

### Steps to reproduce the behavior

1. Pull example [here](https://github.com/Intelight/bazel-javascript/tree/node-typescript-app-skaffold/examples/node-typescript-app)
2. run `skaffold deploy`
3. run `skaffold dev`
