### ISSUE TITLE
KCL-lang support

### ISSUE THREAD

**Issue by th0ger** [GoogleContainerTools/skaffold#9644]
I would like to use http://kcl-lang.io since Helm got too clumsy. 
Can I still use skaffold?

**Comment by th0ger** [comment]
I have tried to use a pre-rendering hook to support KCL as follows:

```yaml
apiVersion: skaffold/v4beta13
kind: Config
profiles:
- name: dev
  manifests:
    hooks:
      before:
        - host:
            command: ["/usr/local/bin/kcl", "run", "-Y", "kcl.yaml", "-o", "output.yaml"]
            dir: "kcl/overlays/dev/"
    rawYaml:
      - kcl/overlays/dev/output.yaml
```
(The `kcl/overlays/dev/` dir contains `*.k` KCL files used to generate k8s yaml manifests, and the main config `kcl.yaml`.)

But it does not work well because skaffold expects the temp file `output.yaml` to exist **before** the before-hook runs(!):

```bash
$ skaffold render -p dev

invalid skaffold config: source: [...]skaffold.yaml, in module "[...]":
source: [...]/skaffold.yaml, in module "[...]": 
Manifest file "kcl/overlays/dev/output.yaml" referenced in skaffold config could not be found. 
Verify that file "kcl/overlays/dev/output.yaml" referenced in config "[...]/skaffold.yaml" exists and the path and naming are correct.
```

To prove this, note that this command executes as intended:

```bash
echo "" > kcl/overlays/dev/output.yaml; skaffold render -p dev
```

Any suggestions on how to set this up correctly?
