### ISSUE TITLE
Updates of workloads due to ConfigMap changes

### ISSUE THREAD

**Issue by viglesiasce** [GoogleContainerTools/skaffold#97]
When a ConfigMap manifest is updated, users may want that to automatically update the workload that it references. Unfortunately the deployment will only update if the configmap name or any other field changes in the spec.

**Comment by lucperkins** [comment]
Having changes to a config file trigger changes to the appropriate ConfigMap, Deployment, etc. would be fantastic, but probably difficult to implement and more suited for a release further down the line. In the short term, however, I think it would be extremely helpful to be able to define configs even *without* auto-updating. Something like this:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  local: {}
  artifacts:
  - imageName: my-app
    bazel:
      target: //:my-app.tar
  configs:
  - name: prometheus-config
    file: config/prometheus.yml
  - name: nginx-config
    file: config/nginx.conf
```
