### ISSUE TITLE
skaffold render with Kustomize and --set fails for inline patches

### ISSUE THREAD

**Issue by coperni** [GoogleContainerTools/skaffold#9731]
Kustomize supports [inline patching](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/inlinePatch.md). I noticed this issue while I was deploying a Kustomization w/ GCP Cloud Deploy

## Expected behavior

Given the following input: https://github.com/coperni/skaffold-kustomize-issue

```yaml
# skaffold.yaml
apiVersion: skaffold/v4beta7
kind: Config
profiles:
  - name: dev
    manifests:
      kustomize:
        paths:
          - overlays/dev
  - name: prod
    manifests:
      kustomize:
        paths:
          - overlays/prod
```

With overlay

```yaml
# ./overlays/dev/kustomization.yaml
resources:
  - ../../base

patches:
  - target:
      kind: Pod
    patch: |-
      - op: replace
        path: /spec/containers/0/image
        value: nginx:latest
```

```yaml
# ./overlays/prod/kustomization.yaml
resources:
  - ../../base
namePrefix: prod-
patches:
  - target:
      kind: Pod
    patch: |-
      - op: replace
        path: /spec/containers/0/image
        value: nginx:123
```

I would expect the following output when running `skaffold render -p dev --set="foo=bar"` or `skaffold render -p dev`

```yaml
apiVersion: v1
data:
  foo: bar!
kind: ConfigMap
metadata:
  name: example-map
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: myapp-pod
spec:
  containers:
    - image: nginx:latest
      name: nginx
```

and running `skaffold render -p prod --set="foo=bar"` or `skaffold render -p prod`

```yaml
apiVersion: v1
data:
  foo: bar!
kind: ConfigMap
metadata:
  name: prod-example-map
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: prod-myapp-pod
spec:
  containers:
    - image: nginx:123
      name: nginx
```

## Actual behavior
`skaffold render -p dev`

```yaml
apiVersion: v1
data:
  foo: bar!
kind: ConfigMap
metadata:
  name: example-map
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: myapp-pod
spec:
  containers:
    - image: nginx:latest
      name: nginx
```

`skaffold render -p dev --set="foo=bar"`

```bash
read /Users/REDACTED/tmp/kustomize_example/overlays/prod: is a directory
```

## Information

- Skaffold version: v2.14.0
- Operating system: macOS 15.3.1 (24D70)
- Installed via: curl w/ latest stable binary

## Steps to reproduce

Checkout https://github.com/coperni/skaffold-kustomize-issue

- skaffold render -p dev --set="foo=bar"
- skaffold render -p prod --set="foo=bar"

## Current workarounds

A mitigation would be to omit the `--set` flags since I don't have anything templated in the inline patch but our CI/CD pipeline injects build parameters into skaffold when we render our manifests. We are able to workaround this by placing the patches in dedicated patch files which are referenced in the kustomization.yaml overrlay.

```
# example 
# ./overlays/dev/kustomization.yaml
resources:
  - ../../base

patches:
  - target:
      kind: Pod
    path: patch.yaml
```

But I would prefer to not to have to create additional files for the amount of overlays we use.

I will submit a fix for this issue.
