### ISSUE TITLE
Skaffold post-render does not inject image tag for ScaledJobs & Jobs

### ISSUE THREAD

**Issue by mjhuber** [GoogleContainerTools/skaffold#9742]
using skaffold `2.14.1` the image tag is not getting injected for Job and ScaledJob objects.  Example bit of generated yaml from command `skaffold render`:

 ```yaml
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  labels:
    app.kubernetes.io/instance: rqworker-chargejob
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rqworker
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: rqworker-0.1.0
    name: unscheduled-charges
  name: rqworker-chargejob-unscheduled-charges
spec:
  failedJobsHistoryLimit: 1
  jobTargetRef:
    activeDeadlineSeconds: 50400
    backoffLimit: 0
    completions: 1
    parallelism: 1
    template:
      metadata:
        labels:
          app.kubernetes.io/instance: rqworker-chargejob
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: rqworker
          app.kubernetes.io/version: 1.16.0
          helm.sh/chart: rqworker-0.1.0
          name: unscheduled-charges
      spec:
        affinity:
          podAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: name
                        operator: In
                        values:
                          - unscheduled-charges
                  topologyKey: kubernetes.io/hostname
                weight: 100
        containers:
          - args:
              - --worker-class=customcheckout.rqjobs.sentry_worker.SentryWorker
              - --job-class=customcheckout.rqjobs.json_job.JsonJob
              - --burst
              - --max-jobs=100
              - unscheduled_charges
            command:
              - rqworker
            envFrom:
              - configMapRef:
                  name: rqworker-chargejob
            image: us-docker.pkg.dev/recharge-infra-services-8b42/gcr.io/customcheckout
            imagePullPolicy: Always
            name: unscheduled-charges
            resources:
              limits:
                cpu: 800m
                memory: 2Gi
              requests:
                cpu: 500m
                memory: 1Gi
            volumeMounts:
              - mountPath: /etc/customcheckout
                name: ejson
                readOnly: true
        dnsConfig:
          options:
            - name: ndots
              value: "2"
        securityContext:
          runAsUser: 2000
        serviceAccountName: rqworker-chargejob
        terminationGracePeriodSeconds: 50400
        volumes:
          - name: ejson
            secret:
              secretName: rqworker-chargejob-unscheduled-charges-files
  maxReplicaCount: 100
  pollingInterval: 15
  rolloutStrategy: gradual
  scalingStrategy:
    strategy: accurate
  successfulJobsHistoryLimit: 0
  triggers:
    - metadata:
        address: <redacted>
        listLength: "1"
        listName: rq:queue:unscheduled_charges
      type: redis
---
# Source: rqworker/templates/install.rq.crons.yml
apiVersion: batch/v1
kind: Job
metadata:
  name: rqworker-chargejob-install
  labels:
    helm.sh/chart: rqworker-0.1.0
    app.kubernetes.io/name: rqworker
    app.kubernetes.io/instance: rqworker-chargejob
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": post-install,post-rollback,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: rqworker-chargejob-install
      labels:
        helm.sh/chart: rqworker-0.1.0
        app.kubernetes.io/name: rqworker
        app.kubernetes.io/instance: rqworker-chargejob
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      restartPolicy: Never
      serviceAccountName: rqworker-chargejob
      securityContext:
        runAsUser: 2000
      containers:
      - name: install
        image: "us-docker.pkg.dev/recharge-infra-services-8b42/gcr.io/customcheckout"
        command:
          - python
          - /var/www/customcheckout/cli.py
          - prepare_rq_post_deploy
        args:
          - --enqueue-queue-warmer
          - "true"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: rqworker-chargejob
        volumeMounts:
        - name: ejson
          mountPath: /etc/customcheckout
          readOnly: true
        resources:
          limits:
            cpu: 600m
            memory: 550Mi
          requests:
            cpu: 400m
            memory: 350Mi
      volumes:
      - name: ejson
        secret:
          secretName: rqworker-chargejob-install-files
```
