### ISSUE TITLE
Skaffold dev fails

### ISSUE THREAD

**Issue by dreambucket13** [GoogleContainerTools/skaffold#9743]
skaffold dev does not work on version 2.14.1.  I am not sure where the issue began, but I installed 2.3.4 which does appear to work.

RE: the malformed YAML error - I passed it through a linter and it seems OK.

```
Generating tags...
 - docker_user_name/client -> docker_user_name/client:ca74516
 - docker_user_name/comments -> docker_user_name/comments:ca74516
 - docker_user_name/event-bus -> docker_user_name/event-bus:ca74516
 - docker_user_name/moderation -> docker_user_name/moderation:ca74516
 - docker_user_name/posts -> docker_user_name/posts:ca74516
 - docker_user_name/query -> docker_user_name/query:ca74516
Checking cache...
 - docker_user_name/client: Found. Tagging
 - docker_user_name/comments: Found. Tagging
 - docker_user_name/event-bus: Found. Tagging
 - docker_user_name/moderation: Found. Tagging
 - docker_user_name/posts: Found. Tagging
 - docker_user_name/query: Found. Tagging
Cleaning up...
 - No resources found
MalformedYAMLError: yaml: line 2: mapping values are not allowed in this context
```

Trying skaffold fix results in this which does not work either:

```
apiVersion: skaffold/v4beta12
kind: Config
build:
  artifacts:
    - image: docker_user_name/client
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker_user_name/comments
      context: comments
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker_user_name/event-bus
      context: event-bus
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker_user_name/moderation
      context: moderation
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker_user_name/posts
      context: posts
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker_user_name/query
      context: query
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
```

The yaml using v4beta3:

```
apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: docker_user_name/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: docker_user_name/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: docker_user_name/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: docker_user_name/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: docker_user_name/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: docker_user_name/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .

```
