### ISSUE TITLE
Manifests are not deployed when reference from another config

### ISSUE THREAD

**Issue by pengux** [GoogleContainerTools/skaffold#9782]
Config:

```yaml
# skaffold.yaml
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: cfg
requires:
  - configs: ["cfg2"]
---
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: cfg2
manifests:
  rawYaml:
    - skaffold-namespace.yaml
deploy:
  kubectl:
```

```
# skaffold-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
```

Running `skaffold dev -vdebug` does not create the namespace but instead show this log line:
```
DEBU[0000] manifests with tagged images:apiVersion: v1
kind: Namespace
metadata:
  name: test  subtask=0 task=Render
DEBU[0000] manifests with labels apiVersion: v1
kind: Namespace
metadata:
  name: test  subtask=-1 task=DevLoop
```

What I'm trying to achieve is to have a namespace created before deploying releases to that custom namespace, is this not the right approach?

**Comment by mjlshen** [comment]
I don't know why this is, but I ran into a similar thing and found that `manifests` is no longer a top-level key? https://skaffold.dev/docs/design/config/

I was able to get this to work using `deploy` instead, e.g.

```yaml
# skaffold.yaml
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: cfg
requires:
  - configs: ["cfg2"]
---
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: cfg2
deploy:
  rawYaml:
    - skaffold-namespace.yaml
deploy:
  kubectl:
```
