### ISSUE TITLE
Skaffold deploy not passing flags to Helm

### ISSUE THREAD

**Issue by bhardwick** [GoogleContainerTools/skaffold#9798]
I have tried the following variations to reduce the send the `--history-max 1` flag to Helm:

```yaml
deploy:
  helm:
    releases:
      - name: my-app
    flags:
      upgrade: ["--history-max", "1"]
```

```yaml
deploy:
  helm:
    releases:
      - name: my-app
    flags:
      upgrade: ["--history-max=1"]
```

```yaml
deploy:
  helm:
    releases:
      - name: my-app
    flags:
      upgrade:
        - "--history-max=1"
```

However, Skaffold ignores this option:
`Running command: [helm --kube-context gke_gcp-my-cluster-dev upgrade my-app skaffold/helm --post-renderer /usr/bin/skaffold --namespace test -f skaffold/helm/values/globals.yml -f skaffold/helm/values/values-dev.yml]`

What is the correct way to pass flags to Helm upgrade?
