### ISSUE TITLE
Skaffold hangs on deploying job with Helm hook

### ISSUE THREAD

**Issue by ivanovaleksey** [GoogleContainerTools/skaffold#9824]
Hey, I am trying to deploy [zitadel](https://github.com/zitadel/zitadel-charts) Helm chart using skaffold. Unfortunately `skaffold run` just hangs while creating job resources.

I tried to debug and narrow down the problem and noticed that the issue was jobs having those annotations
```
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "2"
```

Does skaffold support Helm hooks?
I can remove those annotation as they are customizable via values but the jobs seem to need to be run before the deployment is created/updated.
