### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by slender789** [GoogleContainerTools/skaffold#9834]
I have a target which is not under the current directory but a folder above:
```
  - image: operations/ops-image
    context: ../operations
    docker:
      dockerfile: ../operations/operations-tests.Dockerfile

  - name: minikube
    activation:
    - command: dev
    manifests:
      kustomize:
        paths:
        - kubernetes/kustomize-folder/
    deploy:
      kubectl: {}
    build:
      tagPolicy:
        sha256: {}
      local:
        push: false
        useBuildkit: true
```

And when calling skaffold dev:
```
INFO[0005] Cache check completed in 4.538 seconds        subtask=-1 task=Build
Starting build...
Found [minikube] context, using local docker daemon.
Building [operations/ops-image]...
Target platforms: [linux/amd64]
DEBU[0005] Running command: [docker build ../operations --file /usr/local/home/user/Desktop/kubernetes/operations/operations-tests.Dockerfile -t operations/ops-image:latest --platform linux/amd64 --load]  subtask=operations/ops-image task=Build
unknown flag: --load
See 'docker build --help'.
DEBU[0005] Running command: [kubectl --context minikube delete --ignore-not-found=true --wait=false -f -]  subtask=-1 task=DevLoop
 - No resources found
INFO[0005] Cleanup completed in 51.69773ms               subtask=-1 task=DevLoop
DEBU[0005] Running command: [tput colors]                subtask=-1 task=DevLoop
DEBU[0005] Command output: [256
]                        subtask=-1 task=DevLoop
build [operations/ops-image] failed: exit status 125. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..
```

Skaffold version is 2.16.0
