### ISSUE TITLE
Google cloud builds: cheaper instances

### ISSUE THREAD

**Issue by afoninsky** [GoogleContainerTools/skaffold#988]
According to annotated-skaffold.yaml - it is possible to use only N1_HIGHCPU_8 or N1_HIGHCPU_32 for remote builds.

But there are one more machine: n1-standard-1. It is not so fast, but much cheaper. Is it possible to add this option to enum `build.options.machine_type`?

https://cloud.google.com/cloud-build/pricing

**Comment by afoninsky** [comment]
Also, default value for `diskSizeGb` is 200. Can we reduce it to 50-100?
```
BuildOptions supports a diskSizeGb field that lets you request SSDs of up to 1000GB beyond the default 100GB. The price for additional SSDs is $0.17 per GB per month
```

**Comment by dgageot** [comment]
@afoninsky I believe there's no check on the value in Skaffold. Have you tried submitting a build with `n1-standard-1`? If it works, wdyt about fixing the `annotated-skaffold.yaml` with a PR?

**Comment by afoninsky** [comment]
`skaffold build` says:
```
Starting build...
Building [gcr.io/facetohealth/test]...
Pushing code to gs://facetohealth_cloudbuild/source/facetohealth-cebd05f0fe0565733e0991ddbdc46c2d.tar.gz
FATA[0010] build step: building [gcr.io/facetohealth/test]: could not create build: googleapi: Error 400: Invalid value at 'build.options.machine_type' (TYPE_ENUM), "n1-standard-1", badRequest
```


Current config:
```
apiVersion: skaffold/v1alpha2
kind: Config

build:
  artifacts:
    - imageName: gcr.io/facetohealth/test
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.TAG}}"
  googleCloudBuild:
    diskSizeGb: 50
    machineType: n1-standard-1
deploy:
  helm:
    releases:
      - name: test-service
        chartPath: makeomatic/microservice
        values:
          image: gcr.io/facetohealth/test
```
```
# skaffold version
v0.12.0
```

So I believe there is a code issue

**Comment by dgageot** [comment]
Ok, it seems that Cloud Build doesn't support this value. The way to use a `n1-standard-1` is to not specify any type...

Can you try to not specify any machine type? It should use the `n1-standard-1` type by default.

**Comment by afoninsky** [comment]
Well, at least it was executed. But I can't see any information about machine type, so I _guess_ it is n1-standart-1. Any way how I can check it?
```
# gcloud builds describe 14438414-c6ae-4439-bfc9-df15418aa8f6                                                                        artifacts:
  images:
  - gcr.io/facetohealth/test
createTime: '2018-09-20T08:00:28.430258213Z'
finishTime: '2018-09-20T08:01:14.800972Z'
id: 14438414-c6ae-4439-bfc9-df15418aa8f6
images:
- gcr.io/facetohealth/test
logUrl: https://console.cloud.google.com/gcr/builds/14438414-c6ae-4439-bfc9-df15418aa8f6?project=202568290664
logsBucket: facetohealth_cloudbuild
options:
  diskSizeGb: '50'
  logging: LEGACY
projectId: facetohealth
....
```
