### ISSUE TITLE
Helm Image Incorrectly parses tag when docker image contains a port number

### ISSUE THREAD

**Issue by maddisondavid** [GoogleContainerTools/skaffold#994]
When an image contains a port number such as `myreg.com:8116/product/ui:test-tag` and an imageStrategy of `helm` the tag is incorrectly parsed

`skaffold run -v debug` provides the following:

```
helm --kube-context vermin install --name ui-helm --version dev charts/ui --namespace testing -f charts/ui/values.yaml --set image.repository=myreg.com,image.tag=8116/product/ui
```

### Expected behavior
It's expected that it would correct parse the tag from the image name by splitting from the colon on the right hand side.

.i.e. It should generate the following Helm command
```
helm --kube-context vermin install --name ui-helm --version dev charts/ui --namespace testing -f charts/ui/values.yaml --set image.repository=myreg.com:8116/product/ui,image.tag=test-tag
```

### Actual behavior
Image is split on the FIRST colon
``` 
helm --kube-context vermin install --name ui-helm --version dev charts/ui --namespace testing -f charts/ui/values.yaml --set image.repository=myreg.com,image.tag=8116/product/ui
```
### Information

- Skaffold version: v0.14.0
- Operating system: macOS 10.12.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:dev-{{.DIGEST_HEX}}"
  artifacts:
  - imageName: ui
deploy:
  helm:
    releases:
    - name: ui-helm
      chartPath: charts/ui
      valuesFilePath: charts/fui/values.yaml
      namespace: testing
      imageStrategy:
        helm: {}
      values:
        image: ui
      version: "dev"
      recreatePods: false
```

### Steps to reproduce the behavior

1. Use a docker image that points to a private docker registry with a port number
2. skaffold run -v debug
